### ISSUE TITLE
zachovani sloupcu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#10]
```
pokud si v indexovani v leve casti obrazovky upravim zobrazovane sloupce, tak 
pri pristim prihlaseni jsou jiz opet defaultni. bylo by mozne zapamatovat si je 
pro kazdeho uzivatele?
```

Original issue reported on code.google.com by `psenic...@gmail.com` on 28 Jun 2012 at 7:45

**Comment by MartinRumanek** [comment]
Nastavení sloupců v “proarcu” si má pamatovat sloupce (tak jak je to v RDFlow).

**Comment by pokorsky** [comment]
Přidáno. Nutno otestovat.

**Comment by nezbedova** [comment]
Po odhlášení a znovu přihlášení ses sloupce vrátí do původního (továrního) nastavení.

**Comment by MartinRumanek** [comment]
Chyba se mi neprojeví, můžete sem prosím pro jistotu zkopírovat verzi build a revizi z dialogového okýnka o Proarcu? (jde vyvolat z menu)

**Comment by nezbedova** [comment]
Build: 20171108075259, revize 9d2145782

**Comment by SykoraLukas** [comment]
@nezbedova projevuje se tato chyba i v nové verzi na testovacím serveru?

**Comment by nezbedova** [comment]
Ano. Po odhlášení a znovu přihlášení ses sloupce vrátí do původního (továrního) nastavení.

**Comment by pavelkocourek** [comment]
Přesunuto: zachovani sloupcu (#10) #36
