### ISSUE TITLE
3.5.13 Export pro Crossref je prázdný

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1007]
Resp. není úplně prázdný, jsou v něj údaje k ročníku a k číslu, ale chybějí údaje ke článkům.

**Comment by krizovj** [comment]
Takhle vypadá ve verzi 3.5.13
![Crossref3513](https://user-images.githubusercontent.com/21309201/67391631-5ec3b480-f59f-11e9-9486-e34df29cc85b.jpg)

A takhle má zhruba vypadat, je to z verze 3.5.7
![crossref357](https://user-images.githubusercontent.com/21309201/67391678-726f1b00-f59f-11e9-9185-e5ebf5fbc191.jpg)

**Comment by SykoraLukas** [comment]
Data eČlánku se exportují, jen v případě, že má článek vyplněný identifikátor DOI. @krizovj mohla bys prosím zkontrolovat, že váš eČlánek toto DOI má?

**Comment by krizovj** [comment]
No vidíš to, nemají :) 
Přidala jsem ho tam a vypadá to, že je to v pohodě. Aspoň takhle na první pohled. Zeptám se Kačky, jestli je tam všechno. Díky!
