### ISSUE TITLE
3.5.12 balíček NDK eMonografie - divný věci

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1012]
Poslala jsem dva balíčky ještě z verze 3.5.12 (ptž ve 3.5.13 mi nejdou vyexportovat, viz. tady: https://github.com/proarc/proarc/issues/1009). 
V obou chybí PREMIS object, i když v jednom z balíčků je PDF/A (-2b). Klidně vyzkouším ještě další typy PDF/A, když budu moct exportovat balíčky :)

V Premis event je element linkingAgentRole, jehož hodnota je "role", což je trochu divný. Bylo by dobré, kdyby ta hodnota byla třeba "software", což dává větší smysl.

Ve structMap je logická a fyzická strukturální mapa, jako je to u tištěných dokumentů, ale ve standardu pro eMonografie to tak rozděleno není... Aspoň já jsem to tam nikde nenašla: začíná na s. 64: https://www.ndk.cz/standardy-digitalizace/dmf_e-publikace_monografie_2-2-1

**Comment by SykoraLukas** [comment]
@krizovj muzes mi prosim potvrdit, ze takhle má být ta strukturalni mapa?


![image](https://user-images.githubusercontent.com/27210823/67762701-5c9da200-fa46-11e9-86c5-7edb759730a4.png)

**Comment by krizovj** [comment]
@SykoraLukas  mně teda připadá, že by tam neměl být ten první div s type=title. Pochopila jsem to tak, že title se používá jen pro tu nejvyšší úroveň vícedílné monografie...

Ale kdyby to nevadilo, tak to dám na github NDK, aby se na to podívali. Pokud se neozvou třeba do čtvrtka, tak ti napíšu, jak to udělat. Šlo by to?

**Comment by SykoraLukas** [comment]
Klidně, apson to bude od někoho, kdo to vymýšlel.

Tady je ta druhá varianta
![image](https://user-images.githubusercontent.com/27210823/67764568-8f499980-fa4a-11e9-83fa-49ad437d6b95.png)

**Comment by krizovj** [comment]
https://github.com/NLCR/Standard_NDK/issues/108

**Comment by krizovj** [comment]
Z NK odpověděli, tady je příklad strukturální mapy. 
![structmapemonografie](https://user-images.githubusercontent.com/21309201/68201234-aa278b00-ffc1-11e9-858a-8189214b11f7.jpg)

Což odpovídá té druhé variantě, jak to tak vidím...

**Comment by SykoraLukas** [comment]
vidím to stejně, upravím to podle toho.

**Comment by krizovj** [comment]
Verze 3.5.14 - PREMIS object tam pořád není :sob: 

Zkoušela jsem to jak u dříve založených, tak nově založených záznamů a nic. PDF mám PDF/A-2b.

@SykoraLukas Není potřeba něco ještě někde změnit nebo nakonfigurovat, aby to získávalo ta metadata??

**Comment by krizovj** [comment]
Zkoušeli jsem to PDF ověřit v Acrobatu a taky pan Kotýnek ve veře PDF a je kompatibilní s PDF/A-2b.
