### ISSUE TITLE
Mazání v import - historie

### ISSUE THREAD

**Issue by Bartojan** [proarc/proarc#1015]
Dobrý den, naše pracovnice by rády mazaly v Import - Historie. Máme tam třeba nějaké prvotní pokusy.

1. Je to možné a pokud ano, jak?
2. Je to k něčemu dobré? Jsou s tím spojeny nějaké složky a soubory na disku, či úložišti (ať už se stavem uloženo, nebo chyba načítání)? Nebo, jak je v dokumentaci, se jedná opravdu jen o informace, tedy něco jako je historie v internetovém prohlížeči?

V rozhraní ani dokumentaci jsem nic o mazání historie nenašel.

**Comment by SykoraLukas** [comment]
Mazání historie nelze. Vývojový tým tuto možnost zakázal. Je to jen informační sdělení, jako je historie v prohlížeči.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
