### ISSUE TITLE
vytvorit automatickou tvorbu hierarchie gramodesek

### ISSUE THREAD

**Issue by filipsir** [proarc/proarc#1021]

**Comment by SykoraLukas** [comment]
Nutné nakonfigurovat.

**Comment by filipsir** [comment]
prosim @SykoraLukas o zmenu: zjistili jsme, ze se podle nazvu souboru vytvori v ProArcu casti skladby i tam, kde byt nemaji - tzn. tam, kde je jen skladba a audio ma byt prirazene primo pod ni. Je mozne nastavit pravidlo, ktere muzeme aplikovat a ktere nam dovoli vytvorit strom, jak ma byt? Tzn. identifikovat, kdy uz po skladbe neni zadna cast? 
pr. Xxxx-01-01-01.mp3 a druhy soubor 01.02.01.mp3 - naznacuje, ze neni zadna dalsi cast, protoze hned po skladbe jedna je na desce dalsi skladba + z dalsich zdroju vime, ze je to tak (skeny).
Radi bychom v tomhle pripade chteli pouzit na poslednim dvojcisli dve nuly 00. Tedy v pripade, kdy nechceme aby se vytvorila cast skladby a audio soubor se zaradil primo pod skladbu.

**Comment by filipsir** [comment]
Jak to vypada? Podarilo se?
