### ISSUE TITLE
Archivační balík - složka description

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1030]
Pokud vyexportuji jako archivační balíček třeba ročník časopisu nebo vícedílnou monografii, tak je složka description jen v jednom z balíčků (většinou jen v tom prvním), ale v těch ostatních chybí.
Potřebovali bychom, aby byla ve všech balíčcích.

**Comment by krizovj** [comment]
Tak změna, může to být ve více, než jednom balíčku, ale nikdy to není ve všech. Ale někdy třeba i ve dvou. U ročníku časopisu, který má 15 čísel (=15 balíčků) to bylo ve dvou balíčcích a v ostatních ne.

**Comment by SykoraLukas** [comment]
Implementováno v #1080

**Comment by krizovj** [comment]
Zkoušela jsem jak pro periodikum (f4136c8d-4962-4d2b-be3a-ea63b26618e4), tak pro vícedílnou monografii (64aac7a1-d9ea-4db8-8e7b-532b0ad7b85e) a vypadá to v pohodě, složka description je ve všech balíčcích.
