### ISSUE TITLE
Hlavička METS - lastmoddate - archivační balík

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1031]
Potřebovali bychom do archivního balíčku přidat do metsu do hlavičky atribut lastmoddate, jako je to v NDK balíčcích:
![image](https://user-images.githubusercontent.com/21309201/69537744-08240e80-0f81-11ea-959e-dac8f580155c.png)

**Comment by SykoraLukas** [comment]
Součást #1051.
