### ISSUE TITLE
NDK export periodika 

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1033]
U NDK exportu chybí v hlavním mets v hlavičce název periodika, je tam jen datum vydání a číslo čísla.

**Comment by mhalva** [comment]
Souhlasím! Bylo by praktické mít název periodika v hlavičce, a případně i ve fyzické strukturální mapě, i když to tam není podle standardu povinné.

**Comment by mhalva** [comment]
Tak na ten chybějící název v Label.v hlavním mets jsme byli opakovaně upozorněni při validaci dodaných PSP balíčků do NK. Přimlouvám se za opravení. 🙂

**Comment by krizovj** [comment]
Už tam je:
![nazev](https://user-images.githubusercontent.com/21309201/74151400-6a012580-4c0c-11ea-939c-169d916b64ea.jpg)

Ale vyzkoušela jsem to jen na periodiku, které jsem měla v ProArcu založené od minulé verze. Na nově založeném mi to nejde vyzkoušet, kvůli tomuto problému: https://github.com/proarc/proarc/issues/1106

**Comment by krizovj** [comment]
Takže bych to zavřela, až budu moct vyzkoušet i nově založené periodikum.

**Comment by krizovj** [comment]
Je tam, vyzkoušeno na nově založeném periodiku:
![nazevcasopisu](https://user-images.githubusercontent.com/21309201/75686474-999bce80-5c9c-11ea-9126-3e38ef007afd.jpg)
