### ISSUE TITLE
Stahování sysna - málo číslic

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1034]
V tabulce Record Identifier - R se do pole Identifier - R stahují informace z MARC pole 001. Stahuje se jen prvních 8 číslic. Prosím navýšit na 10.

**Comment by nezbedova** [comment]
Dělá to testovací verze 3.5.14 při stahování z katalogu Orientálního ústavu. Např. číslo 002452983

**Comment by luckajirku** [comment]
Nemůže to nějak dělat jen ten jeden katalog? Když založím třeba Základy embryologie 002397384 z KNAV-mon, je to v pořádku, všech 8 číslic na místě.

**Comment by nezbedova** [comment]
Vypadá to, že to dělá jen katalog orientalního ústavu. Zadává se to někde v nastavení?

**Comment by SykoraLukas** [comment]
Co to je za katalog? KNAV-monografie je postven na Z39.50. Může být, že to druhé je OAI nebo XServer a proto se to děje.

Na vyzkoušení potřebuji konfiguraci celého katalogu Orientálního ústavu.

**Comment by luckajirku** [comment]
že by to bylo to samé co tady https://github.com/proarc/proarc/issues/975?

**Comment by PetrKotynek** [comment]
Je to XServer,
catalog.aleph_skc.url=https://aleph22.lib.cas.cz/X?base=OUAA
catalog.aleph_skc.name=Souborný katalog
catalog.aleph_skc.type=AlephXServer
catalog.aleph_skc.fields=bar, cnb, ssn, sbn, sg, sig, sys
catalog.aleph_skc.field.sig.query=sig
catalog.aleph_skc.field.sig.title=Signatura
catalog.aleph_skc.field.bar.query=bar
catalog.aleph_skc.field.bar.title=\u010C\u00E1rov\u00FD k\u00F3d
catalog.aleph_skc.field.cnb.query=cnb
catalog.aleph_skc.field.cnb.title=CCNB
catalog.aleph_skc.field.ssn.query=ssn
catalog.aleph_skc.field.ssn.title=ISSN
catalog.aleph_skc.field.sbn.query=sbn
catalog.aleph_skc.field.sbn.title=ISBN
catalog.aleph_skc.field.sg.query=sg
catalog.aleph_skc.field.sg.title=Zkr\u00E1cen\u00E1 signatura
catalog.aleph_skc.field.sys.query=sys
catalog.aleph_skc.field.sys.title=Sysno

A možná, kdyby 403, tak by to chtělo Vaši IP. 
Petr Kotýnek

**Comment by mjtecka** [comment]
Zkontrolujte si, jestli máte chybu i v Record Identifer - Source. Jestli je to ten problém s úvozovkama v OAI MARCu, tak vám budou nejspíš chybět nějaké znaky i tam. Nám to předělává CZ-PrCU na CZ-PrC (jak je popsané v #975)

**Comment by zabak** [comment]
Stejný problém máme i v MZK:

jedná se o pole mods:recordIdentifier - uřezává to i poslední znak v CZ-BrMZK

např. <mods:recordIdentifier source="CZ-BrMZ">00088269</mods:recordIdentifier>

Je to vidět v několika záznamech s:
mods:recordInfoNoteConverted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl
(Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)</mods:recordInfoNote>
Např. Revision 1.119 2018/06/21 to má dobře... a v KNAV mají dobře i to co dělali s 1.98.

http://www.digitalniknihovna.cz/mzk/uuid/uuid:c0acb191-92a3-4d68-83e1-d614acf2acab
http://www.digitalniknihovna.cz/mzk/uuid/uuid:2be20185-5537-43b4-a2ff-7b72196e567f
http://www.digitalniknihovna.cz/mzk/uuid/uuid:d13a5ada-79a4-4423-80cd-d95180c0abe5
Co jsem se díval tak to vypadá, že z Kroměříže se to přenáší v pořádku, problém je jen se záznamy z MZK. Týká se to jak věcí z MZK01 (8 cifer místo 9) i věcí z MZK03 (tam identifikátor začíná mzk03 a pak 8 čísel místo 9).

**Comment by mjtecka** [comment]
> Co jsem se díval tak to vypadá, že z Kroměříže se to přenáší v pořádku, problém je jen se záznamy z MZK. Týká se to jak věcí z MZK01 (8 cifer místo 9) i věcí z MZK03 (tam identifikátor začíná mzk03 a pak 8 čísel místo 9).

@zabak  Tipnul bych, že v Kroměříži nemají na rozdíl od MZK  Aleph X-Server, ale používají Z39.50? Jinak co jsem to tak kdysi zkoumal (a jestli si to pamatuju), tak ohrožená jsou (kvůli tomu jak lezou z Alephu bez úvozovek co jsou ve standardu) pole 00X..

**Comment by zabak** [comment]
Vyřešeno, navrhuji zavřít
