### ISSUE TITLE
Mazání dat z ProArcu

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1049]
Čistili jsme testovací verzi ProArcu (verze 3.4.3, Build: 20180327225530, revize 7ec46c46c) a po kompletním odmazání veškerého obsahu má adresář fedora/data stále přes 700 GB (nevím přesně, kolik to bylo před tím, ale celkově má disk 1 TB, takže o moc víc to být nemohlo). Podle všeho se tedy při mazání objektů z ProArcu nesmazala data z fedory.

- Jak se správně odmazávají data z ProArcu, aby se smazala i z Fedory? (V uživatelské dokumentaci jsem o tom nic nenašel).

- Jak teď můžu smazat data z fedory, když v ProArcu nejsou vidět žádné objekty? Je možné prostě smazat adresář fedora/data?

**Comment by svetlym** [comment]
Koukám, že neumím hledat v issues, podle #453 by mazat z úložiště mělo jít. Nemůžu ale přijít na to, jak se to dělá.

**Comment by svetlym** [comment]
Smazat celý adresář fedora/data nejde, Proarc pak nenaběhne. Nefunguje pak ani skript fedora-rebuil.sh. Zkoušel jsem taky smazat jen podadresáře /datastreamStore a /objectStore a ani pak fedora nenaběhne.

Napadá mě už jen udělat úplně novou instalaci fedory i proarcu, ale to se asi bude s tou stávající bít o tabulky v databázi.

**Comment by SykoraLukas** [comment]
Z fedory lze mazat stejne jako z normální uživatel. Vyberete objekt, který chcete smazat a dáte smazat. Objeví se okno a v zaškrtávátku potvrdíte, že chcete smazat trvale (tedy z fedory).

![image](https://user-images.githubusercontent.com/27210823/73362690-92e9f800-42a7-11ea-8c35-a68d1641bb27.png)

**Comment by svetlym** [comment]
@SykoraLukas: Děkuju za návod.

Problém ovšem je, že kolegyně už v Proarcu všechno smazala ve verzi, kde ještě tohle zaškrtávátko nebylo, takže Proarc se teď tváří, že v něm nic není. Je možné v Proarcu vyhledat objekty, které jsou smazané, ale ne trvale, abych je mohl smazat trvale?

**Comment by SykoraLukas** [comment]
V proarcu toto není možné. Musí se mazat přímo ve fedoře. 

Možnost smazat objektytrvale  je od verze 3.2. https://github.com/proarc/proarc/issues/453

**Comment by svetlym** [comment]
> V proarcu toto není možné. Musí se mazat přímo ve fedoře.

V tom případě to založím jako návrh na vývoj, tohle určitě budou dříve nebo později potřebovat všichni.

Děkuju za odpověď, otázky v této issue jsou zodpovězeny.
