### ISSUE TITLE
Kroniky - export balíčku podobného NDK

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1050]
Udělat export podobný NDK balíčku monografie, bez URN:NBN a bez nutnosti Alto a Ocr

**Comment by pavelkocourek** [comment]
Pro informaci - popis z Vysočiny
[Kroniky - popisná metadata podle ZP.docx](https://github.com/proarc/proarc/files/4121528/Kroniky.-.popisna.metadata.podle.ZP.docx)
