### ISSUE TITLE
Autority - číslo autority ze staženého záznamu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1052]
Pokud stáhnu záznam z katalogu, bylo by dobré, kdyby se číslo autority u autorů přepisovalo do elementu "nameIdentifier". Teď je v xml číslo autority, ale ve formuláři není vidět. 

![image](https://user-images.githubusercontent.com/21309201/71954193-b825a200-31e4-11ea-96bf-ddd20a92e2de.png)

V MARCu je číslo autority u autorů (pole 1XX a 7XX) v podpoli 7.

**Comment by SykoraLukas** [comment]
O jaký jde záznam? Z čeho si ho a pomocí jakých identifikátorů mohu stáhnout?

**Comment by krizovj** [comment]
Tohle konkrétně nevím, co bylo za záznam, ale to nevadí, dělají to všechny. Stáhni si z našeho katalogu pro monografie (Knihovna AV ČR Monografie) záznam knihy (vyhledat podle názvu): Švejk ve střední Evropě.

Je tam autor Hrabal, Jiří, který má v záznamu číslo autority, ale do formuláře do pole nameIdentifier se nepropíše. Ale v XML je vidět:
![cautority](https://user-images.githubusercontent.com/21309201/73539147-06694200-442d-11ea-99bb-4351ece44d90.jpg)

![ca](https://user-images.githubusercontent.com/21309201/73539155-09643280-442d-11ea-8147-2ea209a71fa8.jpg)

![ca2](https://user-images.githubusercontent.com/21309201/73539160-0c5f2300-442d-11ea-8b30-634603924e36.jpg)

**Comment by SykoraLukas** [comment]
dík, tohle jsem potřwboval na testování

**Comment by SykoraLukas** [comment]
Standard nezná pole ValueURI. Musí se upravit šablona, aby se hodnota ukládata místo do ValueURI do NameIdentifier. Má se zachovat i pole ValueURI nebo to se má smazat? Aby se informace nedržela dvakrát, doporučuji informaci z ValueURI smazat. Můžu to tak udělat?

![image](https://user-images.githubusercontent.com/27210823/73552050-d11e1d80-4447-11ea-86eb-001ba88bf879.png)

V obrázku je zachována informace v obou polích.

**Comment by krizovj** [comment]
Mělo by tam být jen to číslo. Koukala jsem i do vzorového balíčku z NDK:
![image](https://user-images.githubusercontent.com/21309201/73629200-a3f18b00-4652-11ea-8442-16a1fa8bb699.png)

ValueURI se může smazat.

**Comment by SykoraLukas** [comment]
Dobře, udělám

**Comment by krizovj** [comment]
Šlo by smazat i authorityURI? Validátor pořád prudí, že je to neočekávaný element. Vadilo by to něčemu?

**Comment by SykoraLukas** [comment]
Dle upravené šablony:
![image](https://user-images.githubusercontent.com/27210823/73656900-5fd1ab00-4691-11ea-9969-819b15789487.png)

@krizovj je to takhle ok?

**Comment by krizovj** [comment]
Dobrý 👍

**Comment by krizovj** [comment]
V xml se objevil nový atribut (možná tam byl už předtím, ale nikdy jsem si ho nevšimla)
nameTitleGroup="1"

![name](https://user-images.githubusercontent.com/21309201/74141120-9f027d80-4bf6-11ea-9033-2610fb850871.jpg)

**Comment by SykoraLukas** [comment]
Dle obrazku z teto issue, tam byl element již dříve

**Comment by krizovj** [comment]
A jó, už to vidím. Tak toho jsem si doteď nevšimla, ono to není všude. A nevíš, co to je?

**Comment by SykoraLukas** [comment]
Vychází to z oficiální šablony NK. 
![image](https://user-images.githubusercontent.com/27210823/74145422-0e7c6b00-4bff-11ea-8fbd-6309184bf203.png)

**Comment by krizovj** [comment]
jasný, už to chápu.
