### ISSUE TITLE
NDK strana - povinnost elementu extent

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1054]
Element extent je podle standardu nepovinný (O). V ProArcu je povinný (navíc ještě zatím nevím, k čemu přesně je...):
![ndkstranaindex](https://user-images.githubusercontent.com/21309201/72141001-412e0c00-3392-11ea-938c-87dd365f70ca.jpg)

**Comment by SykoraLukas** [comment]
Opraveno v #1065
