### ISSUE TITLE
NDK strana - úprava formuláře?

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1055]
Šlo by ten formulář pro NDK stranu trochu upravit?
Aby se daly hodnoty pro pole genre, note, typeofresource vybrat ze seznamu? 
![ndkstranaformular](https://user-images.githubusercontent.com/21309201/72141384-0d9fb180-3393-11ea-90c2-5366386b608b.jpg)

Hnidopišská poznámka: u note má být singlePage, ale v popisku u pole je "siglaPage"

**Comment by SykoraLukas** [comment]
Opraveno v #1065
