### ISSUE TITLE
NDK strana X strana

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1056]
Když se přepne ProArc tak, že vyrábí místo stran NDK strany, tak ale když se podívám na formulář obyčejné strany, zobrazí se mi formulář pro NDK stranu:
![NDKstranastrana](https://user-images.githubusercontent.com/21309201/72141566-62dbc300-3393-11ea-8cca-7dc1dbbdd748.jpg)

Je to trochu matoucí, ptž do toho formuláře nejde samozřejmě nic zapsat...

**Comment by SykoraLukas** [comment]
Opraveno v #1065
