### ISSUE TITLE
Nový model Sbírka výstřižků

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1063]
Nový model bude založen na modelu Ndk monografie.

**Comment by svetlym** [comment]
Dobrý den,

v Městské knihovně v Praze výstřižky skenujeme a testovali jsme i možnosti zpracování. Velice doporučuju založit model spíš na periodiku než na monografii. Důvodem je, že výstřižky nejsou uzavřený formát, knihovníci průběžně přidávají nové a zařazují je do existujících obálek, případně sbírek.

Příklad naší sbírky výstřižků zpracované jako periodikum: https://digitalniknihovna.mlp.cz/uuid:ef7cd8c7-1336-4922-8b83-dfc69a224897
