### ISSUE TITLE
NDK vícedílná emonografie - genre a strukturální mapa

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1066]
Když vyexportuji vícedílnou emonografii, tak v záznamu pro vícedílku má být v genre: electronic title a v DC:type model:electronicmonograph. To je správně. 

Ale v záznamech jednotlivých dílů má být v genre: electronic volume a v DC:type model:electronicmonographunit, ale teď je tam jen electronicmonograph, jako by to nebyla vícedílná monografie.

**Comment by krizovj** [comment]
A ještě jsem při exportu narazila v tom balíčku na špatnou strukturální mapu. Chybí tam úroveň title. Už jsme to řešili v jiném issue, kdy tam ten title byl, ale to šlo o nevícedílnou monografii. 

Má tam být, pokud jde o vícedílnou monografii.

**Comment by tumovam** [comment]
Stále přetrvává chyba v < dc:type > u svazku ve vícedílné monografii.
Nyní chybně: < dc:type>model:electronicmonograph</dc:type > 
Správně má být: < dc:type>model:electronicmonographunit</dc:type >

Stále přetrvává chyba ve strukturální mapě vícedílky, kde chybí < mets:div ID="TITLE_0001" DMDID="MODSMD_TITLE_0001" TYPE="TITLE" > 
Nyní chybně:
![obrazek](https://user-images.githubusercontent.com/31240271/127646431-022213ab-dffb-4b71-ab11-3ec915b860a2.png)

Mělo by být:
![obrazek](https://user-images.githubusercontent.com/31240271/127646784-9eef273b-8206-45e0-8971-1b18d1ed5c92.png)

**Comment by kerschfilip** [comment]
Obě zmíněné chyby přetrvávají i ve verzi 3.7.1 - @SykoraLukas bylo by možné to opravit v dohledné době, nebo je to příliš složité? Docela by se to hodilo, začínají se nám hromadit nezpracované věci...  
Díky!

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, bylo by možné tuhle opravu dostat do verze 3.7.2?  Teď už se to u nás bohužel stalo prioritou a oprava by nám velmi pomohla. Děkuji.

**Comment by kerschfilip** [comment]
testováno v 3.7.2:

chyba v `<dc:type>` je opravená, díky!

Ve strukturální mapě přibyl div pro TITLE, ale myslím si, že není správně, protože neobsahuje atribut DMDID, kterým by linkoval na dmdSec, ale místo toho obsahuje LABEL:

![image](https://user-images.githubusercontent.com/57805328/142007524-b4e1bccd-e89a-486e-9ca4-6c6a440438a6.png)

**Comment by kerschfilip** [comment]
ještě doplním, že právě podoba strukturální mapy znemožňuje import do Krameria, který padá na:
_Caused by: java.lang.NullPointerException
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processElectronicDiv(MetsPeriodicalConvertor.java:398)
	at org.kramerius.importmets.convertor.MetsPeriodicalConvertor.processStructMap(MetsPeriodicalConvertor.java:169)_

**Comment by SykoraLukas** [comment]
Mapa je opravena.
![image](https://user-images.githubusercontent.com/27210823/144233012-2187fef7-e2fa-4886-8de6-fbb23407f5ff.png)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky :-)

**Comment by kerschfilip** [comment]
testováno v 3.7.3 -> vypadá to dobře, strukturální mapa odpovídá standardu. Moc děkuju!

mám ještě problém se zobrazením v Krameriovi, ale import proběhl v pořádku, takže předpokládám, že to s ProArcem nesouvisí a issue se může zavřít.
