### ISSUE TITLE
NDK strana - urn:nbn

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1067]
Nevím, jestli to určitě souvisí s NDK stranou, ale vypadá to, že nejspíš jo.

Když mám monografii s obyčejnými stranami, tak se urn:nbn přidělí, ale když jsou v ní NDK strany, tak to nejde. Píše "no page found". 
Obyčejné strany
![stranaunr](https://user-images.githubusercontent.com/21309201/72613972-532f2200-3931-11ea-82b6-262f5318fb9e.jpg)

NDK strany
![ndkstranaurn](https://user-images.githubusercontent.com/21309201/72613981-588c6c80-3931-11ea-85e8-1abbc78aad74.jpg)

@SykoraLukas Není potřeba ještě něco měnit v konfiguraci nebo tak?

**Comment by SykoraLukas** [comment]
Díky, tohle jsem neřešil. Opravím
