### ISSUE TITLE
NDK strana - chybí možnost označit řadu

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1073]
Při paginaci NDK monografie s NDK stranou chybí tlačítko "Označit řadu" a při použití pravé myši, se jen označí, ale nepřeskočí dolní tabulka.

**Comment by nezbedova** [comment]
Tlačítko je, ale  needituje Typ strany.

**Comment by SykoraLukas** [comment]
@nezbedova, prosím otestovat

**Comment by nezbedova** [comment]
Funguje.
