### ISSUE TITLE
Chyba při editaci stran ve vazbách

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1074]
Při hromadné změně stran v Editoru připojených objektů se zasekne proces na
![obrazek](https://user-images.githubusercontent.com/13831946/73085853-b855bb00-3ecf-11ea-9b19-2200bf8e597a.png)

Tato chyba se objevila 2x a 6x to fungovalo normálně. Nepodařilo se mi zjistit, co je důvodem.

**Comment by krizovj** [comment]
Teď jsem to zkusila v jedné monografii desetkrát za sebou a nepovedlo se mi to ani jednou :)

**Comment by nezbedova** [comment]
To je tajná chyba :-) Mně už se to také nepovedlo.
