### ISSUE TITLE
RDflow - čárový kod se nepropíše

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1077]
Čárový kód je v metadatech
 <mods:identifier type="barcode">26001600877</mods:identifier>

Ale nezobrazí se v tabulce Bibliografického záznamu.

**Comment by SykoraLukas** [comment]
Pole se nově propisuje, ale je potřeba yaložit nový záměr, nebo editovat u stávajícího xml a po uložení obnovit stránku (omezeno smartGWT)

**Comment by nezbedova** [comment]
Funguje :-)
