### ISSUE TITLE
Hromadné zakládání čísel periodika bez nutnosti vyplnit číslo

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1078]
V případě, že nelze dopočítat čísla výtisků, se číslo výtisku neuvádí. při hromadném zakládání ve vazbách je to povinné pole. prosím o změnu nebo vytvoření zástupného znaku.

**Comment by SykoraLukas** [comment]
ProArc potřebuje dopočítávat, bez toho není možné vytvářet nová čísla. Do pole se musí zapisovat pouze čísla. Element je dle standardu povinný, proto pokud je nějaká výjimka tak je nutné čísla odmazat ručně.

**Comment by nezbedova** [comment]
Toto pole už není povinné, ale MA. Tedy "pokud známe" 

Budeme odmazávat ručně.
