### ISSUE TITLE
NDK strana - type 

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1079]
Ve formuláři pro NDK stranu je vždycky defaultně vybraná hodnota normalPage, ale nepropíše se do xml. Typ strany se tam propíše, jen když ho vyberu ručně.

**Comment by luckajirku** [comment]
Tohle už se kdysi řešilo... 
https://github.com/proarc/proarc/issues/458
https://github.com/proarc/proarc/issues/455

**Comment by krizovj** [comment]
Chápu, ale podle standardu je teď type u strany povinný. Tu chybu mi nahlásil validátor. Dám sem screenshot.

**Comment by luckajirku** [comment]
jj, vím, nerozporuju, jen dodávám kontext:-)
