### ISSUE TITLE
Hledání a obnova smazaných objektů

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1081]
V Proarcu momentálně není možné vyhledat objekty, které jsou smazané bez zaškrtnutí možnosti "smazat trvale". Jediná možnost, jak je smazat, je přímo ve Fedoře (viz #1049) - což je problém, protože na to je třeba znát uuid, které není jak zjistit, protože je není možné vypsat. Ze stejného důvodu také "dočasně" smazané objekty není možné obnovit.

Navrhuji tedy následující:

- implementovat možnost vyhledávání dočasně smazaných objektů
- implementovat možnost obnovit dočasně smazané objekty

**Comment by SykoraLukas** [comment]
Administrátor může vyhledat smazané (Deaktivované) objekty. Tyto objekty smazat (tlačítkem Smazat) nebo obnovit (tlačítko Administrace - Obnovit objekty). Objekty se  obnovují bez napojení na nadřazený objekt.

![image](https://user-images.githubusercontent.com/27210823/78810957-65b57680-79c9-11ea-8874-e75f3622ba0a.png)

**Comment by krizovj** [comment]
Vyzkoušela jsem to na jednom eČlánku. Nejdřív jsem ho smazala, pak jsem ho zkoušela vyhledat ve smazaných podle uuid. Našlo ho to, zkusila jsem ho obnovit, fungovalo to a pak jsem ho zkusila trvale smazat. A skutečně se trvale smazal. Podle mě to funguje. 

Může se to zavřít? @svetlym

**Comment by SykoraLukas** [comment]
Když se nechají prázdná všechna pole a jako model se vybere "Vyhovuje všemu" najdou se všechny modely s příznakem smáno.

**Comment by krizovj** [comment]
Jo, to mi taky jde

**Comment by svetlym** [comment]
@krizovj: Prosím o pár týdnů strpení, prioritu má teď zprovozňování covidové verze Kraméria. Určitě na to nezapomenu, protože na testovacím Proarcu máme prakticky plný disk a potřebujeme ho promazat. Issue po otestování zavřu.

**Comment by krizovj** [comment]
@svetlym ok

**Comment by svetlym** [comment]
Mazání funguje, ale občas se chová podivně:

- Někdy můžu označit všechny nalezené objekty, někdy mi to řekne, že jsem jich označil příliš mnoho.

- Když označím víc objektů než se vejde do okna a dám je smazat, tak se po smazání nerefreshne obsah okna - když je dám smazat znova, hodí to chybu, protože už tam nejsou (že to souvisí s tím, co se vejde do okna, jen hádám, ale vypadá to tak).

- když označím opravdu hodně objektů (což se ne vždy podaří, viz výše) a dám je smazat, tak se nestane nic.

Nic z toho nebrání funkčnosti, po malých kusech mazat jde.

**Comment by nezbedova** [comment]
To jsou stejné chyby jako při mazání ve Vazbách. Takže "normální" stav.


> Někdy můžu označit všechny nalezené objekty, někdy mi to řekne, že jsem jich označil příliš mnoho.

 Oprava: Vždy se musí kliknout na vybranou stranu. To, že se objeví podbarvený 1. řádek není výběr, ale jen info, že tam jste.


> Když označím víc objektů než se vejde do okna a dám je smazat, tak se po smazání nerefreshne obsah okna - když je dám smazat znova, hodí to chybu, protože už tam nejsou (že to souvisí s tím, co se vejde do okna, jen hádám, ale vypadá to tak).


Tohle se mi nestalo. 


> když označím opravdu hodně objektů (což se ne vždy podaří, viz výše) a dám je smazat, tak se nestane nic.

- Mazat v proArcu jde jen po určitém počtu objektu. Myslím si, že po 140. U nás mažeme po 100.

**Comment by svetlym** [comment]
Jestli se nepletu a je to všechno chování související se starým uživatelským rozhraním, navrhuju tuhle issue zavřít coby funkční a případné další problémy řešit až u nového rozhraní.
