### ISSUE TITLE
Organizace uživatelů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#109]
```
Přidat možnost rozdělení uživatelů do organizací a oddělit digitální 
objekty podle organizací.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 18 Nov 2013 at 12:59

**Comment by slapakovai** [comment]
https://github.com/proarc/proarc/wiki/NavrhOrganizaceUzivatelu
Podrobnější zadání připraví M. Lhoták.

**Comment by ZdenkaSera** [comment]
Návrh na uzavření - zdůvodnění v [203](https://github.com/proarc/proarc-client/issues/203)
