### ISSUE TITLE
NDK strana - pravidla popisu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1090]
V xml NDK strany je navíc element recordInfo s informací o pravidlech popisu. Myslím, že na úrovni strany je to asi zbytečné, nešlo by to dát pryč? Vadilo by to někomu?
![image](https://user-images.githubusercontent.com/21309201/73648033-fc3d8280-467c-11ea-8e1e-7b087ac298a7.png)
 
Asi to souvisí s tímhle? https://github.com/proarc/proarc/issues/927

**Comment by SykoraLukas** [comment]
ProArcu to nevadí a dle standardu to tam nemá být.

**Comment by krizovj** [comment]
Oukej, tak v tom případě bych to dala pryč.
 @luckajirku na úrovni strany to nepotřebujete?
