### ISSUE TITLE
Příloha periodika

### ISSUE THREAD

**Issue by mhalva** [proarc/proarc#1091]
Soubor mets na úrovni přílohy periodika obsahuje nesprávný zápis elementu mods:genre. ProArc v exportu PSP balíčku uvede `<mods:genre>issue_supplement</mods:genre>`, ale správně to má být `<mods:genre type=“issue_supplement“>supplement</mods:genre>`.

Dále tam chybí element `mods:physicalDescription `včetně povinného dceřiného elementu `mods:form `a DC ekvivalentu `dc:format`.

**Comment by luckajirku** [comment]
Ta první věc - mods:genre - vypadá v pořádku.
Tu druhá s physicalDescription je ale pořád trochu divná. Automaticky se mi vyplnilo jen form:print. Ve formuláři to vidím, v xml se to ale neukáže. Propíše se to až ve chvíli, kdy vyplním i authority:marcform. K tomu mě ale nic nenutí, protože ač je to "M", varování neřve...

**Comment by luckajirku** [comment]
Takže physicaldescription není opravené - ač ve formuláři je, šablonou se převede správně, do xml se povinný element nepropíše a při validaci proarc nic nehlásí.
ač je form M, je vidět jen ve formuláři. Propíše se do xml až ve chvíli, kdy se vyplní i authority, což je ale R/MA, takže by to na tom nemělo být závislé. 
Je třeba to opravit, aby se form z formuláře propisovalo do xml.

**Comment by SykoraLukas** [comment]
Opraveno, nasazeno na test

**Comment by luckajirku** [comment]
mods:form už se propisuje i do xml. DC na testovacím nezkontroluju.

**Comment by ZdenkaSera** [comment]
@luckajirku Dívala jsem se na naše data vytvořená ve verzi 3.7.3 - podle mého je to ok včetně DC. Můžeme to uzavřít?

**Comment by luckajirku** [comment]
jj, vypadá to OK - jak u přílohy čísla, tak u přílohy ročníku

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
