### ISSUE TITLE
verze MODS

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1092]
Verzi MODSu máme uvedenou zde:
![modsversion](https://user-images.githubusercontent.com/21309201/73653999-dc14c000-468a-11ea-859a-8a37415112e3.jpg)

Ale podle standardu má být tady:
![modsversion2](https://user-images.githubusercontent.com/21309201/73654013-e59e2800-468a-11ea-9d83-6f8721a29a9e.jpg)

![modsversion3](https://user-images.githubusercontent.com/21309201/73654069-036b8d00-468b-11ea-84cb-1a0e72802586.jpg)

Máme nějaký důvod pro to, že ten údaj máme jinde? Jestli jo, tak v pohodě, pokud ne, tak by to mohlo být podle standardu, ne?

**Comment by SykoraLukas** [comment]
Důvodem bylo, že když je to mods a jeho verze, tak by to mělo být uvedené v modsu a ne v metsu, ale pokud to standard vyžaduje, přesuneme to

**Comment by krizovj** [comment]
Jako zatím to nevyžaduje a je to O, ale pokud to ProArcu v ničem nevadí a nic dalšího to neovlivňuje, tak bych to přesunula.

**Comment by krizovj** [comment]
je to i na úrovni strany a validátor to vyhazuje jako varování.

**Comment by SykoraLukas** [comment]
Atribut se nedá smazat trvale. Dle šablony MODSu, je tento atribut povinný. Pokud jsem zakládal mods bez atributu hlásilo mi to chybu a nešlo ho uložit. 

Udělal jsem to však tak, že mods má atribut verion a při exportu se tento atribut přesune do pole MDTYPEVERSION. Tedy splňuje jak šablonu MODSu, tak i požadavky standardu.

Výsledek:
![image](https://user-images.githubusercontent.com/27210823/79353491-67d48380-7f3b-11ea-8fcf-2b83f42b53bb.png)
