### ISSUE TITLE
Strana - NDK strana

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1097]
Potřebovali bychom nějak zařídit, aby bylo možné z dokumentů s obyčejnými stranami (což je všechno, co máme teď v ProArcu) udělat validní NDK balíčky. 

Takže pokud udělám NDK export nebo archivní export, tak by se ProArc podíval, co má ten dokument za strany. A pokud by zjistil, že jsou to obyč. strany a ne NDK strany, tak by je do NDK / archivního exportu vytvořil jako NDK strany. Ideální by bylo, kdyby se zeptal, jestli to chci do exportu převést jako NDK stranu a nebo nechat jako model strana :)

Takže z tohoto (model strana): 
![stranaNDKstrana](https://user-images.githubusercontent.com/21309201/73747818-80186d00-4758-11ea-9295-8034f1aac630.jpg)

by se stalo tohle (model NDK strana):
![stranaNDKstrana2](https://user-images.githubusercontent.com/21309201/73747828-83135d80-4758-11ea-94f8-4f0347d39fb9.jpg)

Šlo by to? Mám sepsat, co všechny by tam mělo přibýt /zmizet / změnit se nebo tak?

**Comment by SykoraLukas** [comment]
Tohle bych videl jako funkci přímo v proarcu, nikoli až při exportu. 

Převod strany na Ndk Stranu.

Šla by pustit na nadřazených modelech ndk (periodikum, ročník, číslo, monografie, vícesvazek, přílohy). Prošla by podřízenou hierarchii a z každé strany by to udělalo ndk stranu a upravila metadata. UUID by zůstalo stejné.

**Comment by SykoraLukas** [comment]
Podobně by bylo dělané tlačítko na převod Kramerius modelů na NDK modely. Toto je v jiném issue.

**Comment by SykoraLukas** [comment]
Funkce je dostupná pouze pro administrátora (většinou uživatel proarc). 

Pokud kliknu na (ndk) stranu objeví se tlačítko Administrace a v seznamu odpovídající volba:
Převod ze Strany na NDK stranu
Převod z NDK strany na Stranu

Vždy se upravují i metadata, podle aktuálního standardu.

Pokud kliknu na jakýkoli jiný model, objeví se v menu Administrace obě tlačítka. Po vybrání Funkce projde všechny modely pod vybraným a pokud najde (NDK) stranu, převede ji na druhý model.

Po proběhnutí funkce je nutné kliknout na tlačítko Obnovit. Aby se načetly nové informace o daných modelech.

**Comment by krizovj** [comment]
Zatím jsem to zkoušela u monografií a mám k tomu tři drobnosti. 

Po převedení vyskočí hláška něco jako "Objekt byl převeden na model NDK strana" nebo tak nějak. Ale vyskočí to samé, i když převádím NDK stranu na obyč stranu. Ale to je jen detail. 

Když převedu NDK stranu na stranu, tak zmizí z formuláře číslo strany (pageNumber). V xml i v popisu stran zůstane, ale z formuláře to zmizí. Když tu stejnou monografii převedu zpět na NDK stranu, číslo strany ve formuláři se vrátí. 

Když převedu NDK stranu na stranu (teď zrovna mě nenapadá situace, proč bych to chtěla udělat, ale když to jde, tak můžu), tak ve vazbách se nezmění model na "Strana". Zůstává tam "NDK strana". 
![ndkstrana](https://user-images.githubusercontent.com/21309201/79327558-f681da00-7f14-11ea-80af-27b748b04304.jpg)

**Comment by krizovj** [comment]
Vyzkouším to ještě na nějakém periodiku

**Comment by krizovj** [comment]
Druhý a třetí se vyřešilo F5, takže dobrý.

**Comment by krizovj** [comment]
Zkoušela jsem to na vícedílné monografii - šlo to z NDK strany na stranu i zpět. Fungovalo i když měl jeden z dílů ještě přílohu monografie. 

Otestováno periodikum, kde byla příloha ročníku i příloha čísla a šlo to z NDK strany na stranu i zpět. 

U jedné monografie, která měla Strany vyhodilo neočekávanou chybu (mega moc dlouhou) ,ale přesto se to převedlo na NDK strany. Nevím, jestli to nemohlo být tím, že měla hodně stránek (cca 250), měla taky přílohu. Ostatní testovací objekty měly vždy málo stránek (cca 20).

Jiné kombinace už mě nenapadají. Ještě bych mohla vyzkoušet export něčeho, kde byly původně strany a převedly se na NDK strany...

**Comment by SykoraLukas** [comment]
U těch stran ale bude chybět ten element dc:coverage

**Comment by krizovj** [comment]
jasně, budu s tím počítat

**Comment by krizovj** [comment]
Teď jsem to zkoušela ve verzi 3.5.18 a pořád je tam ta stejná hláška, ať převádím NDK strany na Strany nebo Strany na NDK strany. 
Ona tam může být vlastně stejná hláška, ale nějaká nematoucí. Třeba: Model převeden. nebo Hotovo. :)

**Comment by tumovam** [comment]
Už jsem chtěla psát, že převod Stran na NDK Strany funguje, ALE... 

Ve verzi 3.6 jsme přišli na docela zásadní problém. Když převádím Strany na NDK Strany a skenů je méně než 100 (opravdu vyzkoušeno na x monografiích), tak se Strany převedou na NDK Strany hned napoprvé a objeví se správná hláška "Model byl převeden na NDK Strana".

Bohužel když se snažím o převedení více než 100 Stran na NDK Strany, tak se po nějaké době se zobrazí hláška "Neočekávaná chyba" (jak psala Jana K. výše "mega moc dlouhá" :)). I přes tuto chybovou hlášku + po refreshnutí se Strany převedou na NDK Strany. Bohužel jen zdánlivě. Proč zdánlivě? Na první pohled vše vypadá v pořádku, všechny modely ve struktuře jsou NDK Strany, ale od nějakého skenu (2x se mi stalo, že to byla Prázdná strana, ale vždy max. do s. 100) jsou v XML metadata pouze jednoduché Strany. Takže i když se model nazývá NDK Strana, v metadatech není part dozdělen do dvou partů = není to NDK Strana.

A teď vtipná situace - ty špatně převedené NDK Strany jsem v testovacím PA v3.6. převedla zpět na Strany (opět chybová hláška, ale to neřeším). Převod Stran na NDK Strany proběhl v pořádku. A když jsem tyto zpětně převedené Strany převedla ještě jednou na NDK Strany, už to bylo v pořádku (všechny NDK Strany rozdělené do dvou partů, nazývají se NDK Strany). Tenhle fígl funguje pouze v testovací instalaci a jen a pouze v Chromu, ve Firefoxu ať převádím, jak převádím, nikdy se nepřevedly všechny Strany na NDK Strany.

Takže v tuto chvíli 100% funguje převod Stran na NDK Strany pouze u monografií (periodika jsem netestovala, pardon) do 100 stran. Ta finta s převáděním sem a tam je sice docela dobrá, ale byla bych moc ráda, kdybych mohla ProArcu věřit hned ;) @SykoraLukas, nevíš, čím by to mohlo být? Šlo by to, prosím, opravit? 

Jo a jen detail - stále při převodu NDK Stran na Strany se zobrazuje hláška "Model byl převeden na NDK Strana". Jana výše navrhuje jednotnou hlášku "Model převeden", to mi přijde jako dobré řešení. Hlášky nás ale v současné době moc nepálí... Klidně obětuju hlášku za správné převedení všech Stran na NDK Strany.  

Děkuju, M.

**Comment by PetrKotynek** [comment]
Testovani na novem serveru: cituji z e-mailu kolegy Kersche. Připojuji logy podle času. 
[1304.txt](https://github.com/proarc/proarc/files/5318078/1304.txt)
[1307.txt](https://github.com/proarc/proarc/files/5318079/1307.txt)
[1329.txt](https://github.com/proarc/proarc/files/5318080/1329.txt)


 Petr Kotýnek
[1249.txt](https://github.com/proarc/proarc/files/5318067/1249.txt)
[1300.txt](https://github.com/proarc/proarc/files/5318068/1300.txt)



Otestoval jsem převod stran na monografiích růžných velikostí. U velmi krátkých a krátkých (do cca 70 stran) většinou proběhne vše OK, ne ale vždy. Delší monografie skoční vždy chybou

Pokusil jsem se sepsat kdy, u jakého uuid a jakého převodu chyba nastala, třeba to k něčemu bude:

    uuid: 47f51293-0d12-4e42-9cf9-008537a2c8e6,
        převod Strana->NDK Strana,
        cca 12:49,
        chyba u strany 53 (436fd230-c735-46c2-9fe5-ff1e36fe8ece)
    uuid: d4c31dc9-cf9f-453e-9d92-93697e8a7c10,
        převod Strana->NDK Strana,
        cca 13:00,
        chyba u strany 27 (6a55de1a-217e-41a4-8b2b-0f4096e003ce)
    uuid: d4c31dc9-cf9f-453e-9d92-93697e8a7c10,
        převod NDK Strana->Strana,
        cca 13:04,
        ProArc hlásí chybu, ale všechny strany jsou převedeny
    uuid: d4c31dc9-cf9f-453e-9d92-93697e8a7c10,
        převod Strana->NDK Strana,
        cca 13:07,
        chyba u strany 27 (2e53179c-37db-432b-97ca-cebc6ddd957c)
    uuid: 73c72d93-3572-4cdb-bf89-75b7736e3415,
        převod Strana->NDK Strana,
        cca 13:29,
        chyba u strany 35 (b71ebab5-82b3-4b60-a28b-c022fe107e28)

Filip K.

**Comment by PetrKotynek** [comment]
Logy. Petr Kotynek
[PageToNdkPage.zip](https://github.com/proarc/proarc/files/5318118/PageToNdkPage.zip)

**Comment by tumovam** [comment]
Zatím otestovány monografie s max. 250 stranami. Zkouším dál... :)

**Comment by tumovam** [comment]
Tak pokračování testování - PA v 3.6.2 ani s opakovaným ingestem do Fedory nepřevede všechny Strany na NDK Strany. 
Resp. ono to vypadá, že ano, protože Všechny typy stran jsou NDK Strana, ale od určitého skenu není xml rozděleno do 2 Parts. Ukázka: 
![obrazek](https://user-images.githubusercontent.com/31240271/102319941-eb87b980-3f7b-11eb-9d1d-8438268648d5.png)
 :( A ne, nepomáhá ani refresh...

**Comment by tumovam** [comment]
Případně nešlo by opravit, že když vyberu určitý počet Stran, tak se VŠECHNY tyto vybrané Strany převedou na NDK strany?
Např. když vyberu s. 1-5 a dám "Převést Stranu na NDK stranu"... 
![Před](https://user-images.githubusercontent.com/31240271/102339880-1848ca80-3f96-11eb-92bf-fccc88a8fa45.JPG)
Tak se převede pouze poslední vybraná - v tomto případě s. 5, ne s. 1-5, což očekávám...
![Po](https://user-images.githubusercontent.com/31240271/102339907-20a10580-3f96-11eb-8b61-0da36f255458.JPG)
Kdyby toto fungovalo, mohla bych si vždy vybrat určitý počet Stran a postupně třeba po 100-150 stranách je převádět na NDK Strany... tedy do té doby než převod doladíme. Díky moc

**Comment by nezbedova** [comment]
@SykoraLukas Poslední úprava ve v.3.6.5-SNAPSHOT funguje dobře. Děkuji

Strany se převádí postupně a po obnovení je vidět, kam až převod doběhl.

**Comment by ZdenkaSera** [comment]
@krizovj Tohle je funkční, jde převádět po částech tam a zpátky, funguje , zatím bez protipříkladu s chybou. Jsou upraveny i hlášky na "model byl převeden na stranu"/"model byl převeden na NDK strana".

**Comment by krizovj** [comment]
@ZdenkaSera A na tu chybu je založeno nějaké zvláštní issue? Pokud ano, tak bych to zavřela.

**Comment by ZdenkaSera** [comment]
@krizovj To jsme si nerozuměly - myslela jsem to tak, že jsem nenašla žádný příklad, kde by to nefungovalo :-)  Chyby se dořešily tady:  [#1389](https://github.com/proarc/proarc/issues/1389).

**Comment by krizovj** [comment]
@ZdenkaSera aha :) tak to jo, tak zavírám
