### ISSUE TITLE
NDK článek - part

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1098]
U ND článku má být element part rozdělený na dva elementy part, v jednom je index a ve druhém číslo stránky. Teď je to takhle:
![part2](https://user-images.githubusercontent.com/21309201/73749242-41d07d00-475b-11ea-928f-2398955c193a.jpg)

A potřebovali bychom to takhle:
![part3](https://user-images.githubusercontent.com/21309201/73749270-4bf27b80-475b-11ea-86a6-68e45a631720.jpg)

Ještě to prozkoumám, co všechno by tam mělo být jinak.

**Comment by krizovj** [comment]
https://github.com/NLCR/Standard_NDK/issues/117

**Comment by krizovj** [comment]
Pořád neodpověděli, takže nevím, jak to má přesně vypadat (co přesně s elementem detail?)

**Comment by krizovj** [comment]
https://github.com/NLCR/Standard_NDK/issues/117 už máme odpověď, jak má element part přesně vypadat. Platí pro články a kapitoly.

**Comment by krizovj** [comment]
Ještě se to trochu změnilo, atribut type (pageNumber nebo pageIndex) je už u part a ne až v subelementu detail, jako to bylo předtím.
![75957100-96315e80-5eb9-11ea-8ecc-827735b06f6a](https://user-images.githubusercontent.com/21309201/76746061-2c496c80-6777-11ea-993c-217dc9698c71.png)

**Comment by krizovj** [comment]
platí i pro verzi 3.5.18

**Comment by tumovam** [comment]
ve v3.6.1 funguje

**Comment by tumovam** [comment]
U nově vytvořených NDK Článků je vše v pořádku, ale co budeme dělat s dříve vytvořenými? V PA máme x tisíc (ehm...) NDK článků, u nichž máme PageNumber a PageIndex v jednom Partu. A podle standardu to máme mít 2 Party. @SykoraLukas, nešla by naprogramovat zase nějaká vychytávka (obdobná tomu, co máme na převod Stran na NDK Strany)? Děkuju, M.

**Comment by SykoraLukas** [comment]
Ano šla, jen nedokazeme rozlisit mezi novym a starym Článkem. Budou se muset projít všechny články. Vyhovuje?

**Comment by tumovam** [comment]
Jj, předpkládala jsem, že se to bude muset vyřešit nějak takhle. I když je pravda, že v KNAV máme vlastně všechny NDK Články špatné (nerozdělené do dvou partů), protože na ostré inst. PA máme v3.6, kde je v tomto ještě chyba...

**Comment by SykoraLukas** [comment]
Otev5el jsem issue pro novou funkci, toto issue zavírám.

**Comment by tumovam** [comment]
Ještě jednou jsem se dívala na NDK a zase tam máme chybu. 

pageIndex a pageNumber už mají každý svůj part 👍 , ale bohužel podle vyjádření v https://github.com/NLCR/Standard_NDK/issues/117 to má být takto:

![obrazek](https://user-images.githubusercontent.com/31240271/105729628-ba60b880-5f2d-11eb-9333-92e7de971279.png)

Oprava v NDK standardu zatím není. Ale oprava v ProArcu by byla potřeba, abychom nevyráběli špatně další desítky NDK článků... Děkujeme, KNAV

**Comment by tumovam** [comment]
Ve v3.6.4-preview otestováno u NDK článků a NDK Kapitol. Funguje. Díky moc!

**Comment by tumovam** [comment]
Verze 3.6.5 - při zakládání nového NDK článku chybí <mods:extent unit="pages">

**Comment by tumovam** [comment]
Verze 3.6.6 - při zakládání nového NDK článku chybí <mods:extent unit="pages">

![obrazek](https://user-images.githubusercontent.com/31240271/120324049-753b0180-c2e6-11eb-94b3-bddbc120561b.png)

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by tumovam** [comment]
Ve v3.6.7 - při zakládání nového NDK článku už NEchybí <mods:extent unit="pages">, zbytek Parts vypadá též v pořádku.
