### ISSUE TITLE
Emonografie - export s kapitolami 

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1101]
Emonografii nejde vyexportovat, pokud pod ní jsou záznamy ekapitol. 
Napíše tuto chybu:

![ekapitola](https://user-images.githubusercontent.com/21309201/73835367-92a0ae00-480d-11ea-85d8-ce7830a980e3.jpg)

**Comment by krizovj** [comment]
Mám na mysli NDK export.

**Comment by kerschfilip** [comment]
ve verzi 3.8.2 export stále nefunguje. Asi by bylo dobré řešit to i v návaznosti na standard a způsob zápisu kapitol do strukturální mapy: https://github.com/NLCR/Standard_NDK/issues/133

**Comment by kerschfilip** [comment]
Otestováno znovu na DEV na verzi `Klient: verze v2.3-visk24 (13.05.2024)Jádro: verze 4.2.0-SNAPSHOT - build 20240711100059`. Objekt k případnému testování: uuid:c326e591-5497-46bf-9f9c-73a3f9924917

MODS vypadá OK, chyba při NDK exportu stále stejná: `Unable to find DIV for page order:VOLUME_0001 8`

**Comment by kerschfilip** [comment]
@SykoraLukas při exportu NDK PSP dostávám chybu, že pro kapitoly chybí RAW stream. Např:

```
Chyba (uuid:7e29f99e-dff3-4794-b6aa-fd1d95543af3) Objekt neobsahuje RAW stream.
Chyba (uuid:28c73723-4823-424d-95e0-2e4f5b02576b) Objekt neobsahuje RAW stream.
Chyba (uuid:c3b7becb-6397-478f-8ee0-09423a26c216) Objekt neobsahuje RAW stream.
```

Kapitoly jsou ale stejně jako u tištěných monografií jen mods popis s rozsahem stran, žádná PDF pod to nepatří (klient by to neměl ani nabízet)

**Comment by SykoraLukas** [comment]
Tak na tuhle situaci nikdy nebyl ProArc ani Kramerius připraven.

NDK eKapitola se chová stejně jako ečlánek a NDK eČlánek. Tedy v tomto případě pod NDK eMonografií není žádné PDF a vždy kapitola má své pdf. Stejně jako NDK eČíslo nemá své PDF a všechny jsou na úrovni NDK eČlánků.

**Comment by kerschfilip** [comment]
> Rozdíl u tištěných je v tomto: U NDK článků i NDK kapitol se odkazuješ na stránky, které jsou připojené pod NDK Monografií / NDK Číslem.

No já myslím, že podle standardu to právě mělo být stejně i tady - že kapitolami jen odkazuješ na stránky v PDF schovaném pod tím svazkem monografie (snad se teda nepletu). 

Druhá věc je, že se na jednotlivé stránky dá odkazovat v MODS, ale funkční propojení v Krameriovi (nebo obecně prostě pro práci s těmi kapitolami) z toho pak nevznikne. To se dlouhodobě nějak řeší, ale ne moc intenzivně...

Nicméně teď jsem teda zkusil dát PDF pod jednotlivé kapitoly a jsem zpátky u chyby: Unable to find DIV for page order:VOLUME_0001 8

**Comment by SykoraLukas** [comment]
A jakou verzi používáš?

**Comment by kerschfilip** [comment]
2.3.0/4.2.0 zkoušel jsem u nás i na masteru. testovací UUID u vás: uuid:c326e591-5497-46bf-9f9c-73a3f9924917

**Comment by SykoraLukas** [comment]
Problémem je vyplněnost elementu mods:part. Když vyplněn není, export projde. Viz: uuid:6582cdbe-d8b0-4abf-8799-c8f4190fd100

Podívám se na to ještě.

**Comment by SykoraLukas** [comment]
Opraveno.
