### ISSUE TITLE
3.5.16 - Index strany - chyba při exportu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1106]
Když chci vyexportovat Archivní balík nebo NDK balík, tak mi proarc vyhodí toto:
![chybastrana](https://user-images.githubusercontent.com/21309201/74149638-84390480-4c08-11ea-9dc8-608859ac6a62.jpg)

Prý mu chybí index hned u první strany, ale přitom je vyplněný:
![indexneni](https://user-images.githubusercontent.com/21309201/74149715-b2b6df80-4c08-11ea-9024-a781532432b3.jpg)

Zkoušela jsem všechny strany označit a udělat validaci ve vazbách a ta žádnou chybu nenašla:
![validaceok](https://user-images.githubusercontent.com/21309201/74149736-c2362880-4c08-11ea-8a5e-158c9b8487f6.jpg)

Nevím, čím by to mohlo být... Zkusila jsem tu 1 v indexu přepsat ručně a znovu uložit a nic...

**Comment by krizovj** [comment]
@nezbedova můžete prosím vyzkoušet, jestli vám to taky dělá tuhle věc?

**Comment by nezbedova** [comment]
Teď jsem k tomu došla. Dělá mi to také.

**Comment by nezbedova** [comment]
A dělá to, ikdyž chci archive export.

**Comment by nezbedova** [comment]
Zkoušela jsem ve vazbách reindexaci a nepomohlo to.

**Comment by SykoraLukas** [comment]
Chyba je v kódu. U klasické strany je pageIndex v prvnim elementu mods:part, kde se také kontroluje. U NDK strany ale je až v druhém elementu mods:part. Bude opraveno, logika je podle toho o jaký model se jedná.

**Comment by krizovj** [comment]
Aha, ok.

**Comment by krizovj** [comment]
Funguje, minimálně u periodika NDK číslo se mi vyexportovalo jako NDK balík i jako archivní balík. 
Ještě zkusím monografie.

**Comment by krizovj** [comment]
Vyzkoušela jsem to na dvou monografiích a vypadá to v pohodě.
