### ISSUE TITLE
Import dat z Krameria - stránky pod ročníkem

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1111]
Bylo by možné upravit import tak, že když zjistí, že pod ročníkem jsou přímo stránky, aby se automaticky založilo číslo, pod kterou by se zařadily? Mohlo by se jmenovat třeba jenom "?", aby bylo hned jasné, že je potřeba ten záznam ještě upravit.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
