### ISSUE TITLE
Import dat z Krameria - "import dokončen"

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1112]
Při importu ProArc jen řekne "import byl naplánován" a už nic dalšího. Bylo by super, kdyby mi ještě dokázal sdělit, že je ten import dokončený.

![import2](https://user-images.githubusercontent.com/21309201/74630206-57ca3e80-515a-11ea-8e23-ef106963369a.jpg)

**Comment by ZdenkaSera** [comment]
@krizovj @kerschfilip Vzhledem k importním procesům v novém klientovi tohle zavírám.
