### ISSUE TITLE
Import dat z Krameria - divná chyba

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1114]
U jedné monografie se mi stalo, že se naimportovala jen jedna strana (z asi 60). U další už to bylo v pohodě, ale nevím, co bylo u této špatně. 
![importmonografie](https://user-images.githubusercontent.com/21309201/74636135-b21dcc00-5167-11ea-908b-3183a054f2ad.jpg)

V proarc_import_status.log je jen tohle (to samé je tam u všech, jen samozřejmě s jiným číslem):
![proarcimportstatus](https://user-images.githubusercontent.com/21309201/74636192-c9f55000-5167-11ea-9d4d-2af0b36226b7.jpg)

A ve složce proarc_import to vypadá, že jsou všechny stránky.

**Comment by ZdenkaSera** [comment]
zavírám po domluvě s @krizovj
