### ISSUE TITLE
3.5.16 chyba zobrazení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1133]
Nevím, jak se mi to povedlo.
![obrazek](https://user-images.githubusercontent.com/13831946/75750983-a87a9380-5d25-11ea-87db-e3b3ebab4698.png)

**Comment by SykoraLukas** [comment]
Už jsem to zjistil. Po načtení složek, když se ložka proarc_import smaže a načte se znovu, tak jsou v historii 2 záznamy se stejným jménem. Ten novější obsahuje i soubory, ale ten starší neobsahuje nic, a proto to vypadá takto.
