### ISSUE TITLE
generování JP2K až při exportu

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc#1134]
Konfigurovatelné

**Comment by luckajirku** [comment]
Můžeš to @pavelkocourek trochu rozvést, kdy by se to mělo použít?

**Comment by ZdenkaSera** [comment]
Po domluvě ze schůzky 9.11. zavírám
Důvody: výkonost a problém paměti 
- místo toho vyřešeno jinak, bylo realizováno issue s podobnou pracností https://github.com/proarc/proarc/issues/1432
