### ISSUE TITLE
urn:nbn - přidělování přílohám

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1138]
Nemělo by se urn:nbn přidělovat i přílohám? 

Když chci vyexportovat monografii s přílohou, tak NDK export proběhne v pořádku, ale archivní export řve, že chybí urn:nbn. Přitom monografie už ho má přidělené, takže mu zřejmě vadí, že ho nemá příloha. 

Ve standardu u přílohy je urn:nbn uvedeno, ale nevím, jestli je nutné ho přidělovat všem přílohám, i těm, které například nemají svůj záznam v katalogu. 

@luckajirku co si o tom prosím myslíš?

**Comment by luckajirku** [comment]
Nevím, ale brala bych to stejně jako přílohu čísla u periodika. Hned na začátku ve standardu je "URN:NBN **může** být přidělováno také nižším logickým úrovním (entitám) – např. článek ve sborníku, příloha". Tak pokud **MŮŽE**, ne _musí_, export by řvát neměl.

**Comment by luckajirku** [comment]
a teď koukám, že na stejné straně je "povinné, pokud lze přidělit"... tak tohle vzdávám:-)))

**Comment by krizovj** [comment]
@luckajirku No právě :D já zas nechci dělat v něčem zmatek a bordel, ale právě ty přílohy mi přijdou celý divný :) 

Jak zpracováváte přílohy vy? My je děláme tak, že normálně v ProArcu pod monografií na úrovni stran založíme záznam přílohy monografie a pak je to v balíčku spolu s monografií. Takhle to děláme u všech příloh :) 

Ale podle pravidel pro popis je to asi špatně...? Tam se totiž řeší typ, tvar a velikost té přílohy a podle toho se dělá zvláštní balíček nebo ne... https://www.ndk.cz/standardy-digitalizace/pppmono2.2.verze4.pdf 
Řešíte, jak příloha vypadá nebo zpracováváte všechny stejně? :)

**Comment by luckajirku** [comment]
Tak my se řídíme katalogizačním záznamem, aby se to nerozcházelo. Pokud to katalogizátor dá to na jeden záznam, nevidím důvod tam při digitalizaci vnášet něco nového a dělit to. Takže jeden balíček a v něm na úrovni stran vytvořená příloha, samozřejmě dobře popsaná, aby se dala vyhledat.

**Comment by krizovj** [comment]
Jasný, chápu. Takže to taky neděláte podle těch pravidel pro popis? Ono to podle nich má být tak (aspoň jsem to tak pochopila), že pokud ta příloha má jako třeba jiný formát a velikost než ten dokument, ke kterému patří, tak se musí udělat pro tu přílohu zvlášť balíček. Což mi teda přijde takový dost mimo, ptž to by ta příloha byla zvlášť od té monografie i v Krameriovi a to je úplný nesmysl... Jen zkoumám, jestli to tak někdo dělá... 

My prostě přílohu vždycky zpracujeme dovnitř monografie na úrovni stran, aby byla vidět v Krameriovi u té monografie.

**Comment by luckajirku** [comment]
Tak je to otázka výkladu, jak nakládat s "přílohou odlišného typu, tvaru a velikosti než je popisovaný svazek monografie". Odpíchni se od té další věty: "která se
skenuje zvlášť na svazku nezávisle". Skenuješ to na svazku nezávisle? A co znamená nezávisle?  Upravila bych to řvaní v ProArcu a neřešila bych to.

**Comment by krizovj** [comment]
Oukej, to bude asi nejlepší řešení :) Mně právě moc nedává smysl skenovat přílohu čehokoliv "zvlášť na svazku nezávisle", ještě jsem asi na nic takovýho nenarazila... Díky za konzultaci :)

**Comment by krizovj** [comment]
@SykoraLukas šlo by to teda prosím upravit tak, aby při exportu archivačního balíčku, kde je příloha, ProArc neřval, když příloha nemá přidělené urn:nbn? NDK neřve.

**Comment by krizovj** [comment]
Zkoušela jsem založit pod monografii přílohu, která nemá urn:nbn a NDK export i archivační export proběhl v pohodě, takže zavírám...
