### ISSUE TITLE
Řazení modelů dle abecedy 

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1141]

**Comment by krizovj** [comment]
Zkoušela jsem to a funguje to tak, že vyberu "Abecedně", pak vyberu model a jestli chci řadit vzestupně nebo sestupně. Jestli to tak má fungovat, tak to funguje. 

Akorát jsem přišla na jednu divnou věc, ale nevím, jestli je to chyba. Dolní uvozovky na začátku názvu mi to našlo na konci abecedy a horní uvozovky na začátku. Šlo by je dát oboje na začátek?

**Comment by SykoraLukas** [comment]
Zkusím

**Comment by SykoraLukas** [comment]
Doděláno

**Comment by krizovj** [comment]
Mně to ty dolní uvozovky hodí ne na začátek abecedy k těm horním, ale někam asi jako ke konci abecedy.

ečlánky
![proarcuvozovky](https://user-images.githubusercontent.com/21309201/82215953-763a0480-9918-11ea-920e-3417f187b070.jpg)

NDK monografie
![proarcuvozovky1](https://user-images.githubusercontent.com/21309201/82215971-7d611280-9918-11ea-81fb-7a09937368a7.jpg)

**Comment by nezbedova** [comment]
Nešlo by nějak udělat řazení podle abecedy podle české abecedy? To, že jsou názvy titulů začínající písmenem s diakritikou až za písmenem "Z", je uživatelsky poněkud krkolomné. Co mi ale opravdu vadí je, že se tak řadí i názvy, které mají písmeno s diakritikou na druhém nebo dalším místě.
 
![obrazek](https://user-images.githubusercontent.com/13831946/111872062-b7ae9c80-898d-11eb-9bf9-23a9d783b94e.png)

**Comment by SykoraLukas** [comment]
Fedora nepodporuje české řazení, proto se na konec dávají znaky, které nejsou v anglické klávésnici. Jakmile se přejde na jiné uložiště a nahradí se resource index Solrem s možností české lokalizace, tak se toto vyřeší.

**Comment by ZdenkaSera** [comment]
**Test v 3.8-beta** 
Řazení titulů/objektů podle abecedy funguje jen částečně 
- dolní uvozovky jsou stále na konci
- výše zmíněné nepodporované české řazení do toho vnáší záhady - viz 2x titul Zpráva o Jaroslavu Haškovi na připojením obrázku
- přesto navrhuji uzavřít do přechodu na Akubru @krizovj @nezbedova 

![image](https://user-images.githubusercontent.com/79305516/157661822-8ac8d372-961f-4245-8e04-8849cc6bc857.png)
