### ISSUE TITLE
3.5.17 - u strany chybí dc:coverage

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1147]
Chybělo to už v předešlé verzi, ale nestihla jsem to založit. 

Na úrovni strany chybí v DC page number. Měl by být v elementu dc:coverage.

**Comment by krizovj** [comment]
Mělo by to být v obou metsech, jak v archivačním balíku, tak v NDK.

**Comment by SykoraLukas** [comment]
DC:coverage se dělá z elementu Extent u strany. Budu to dělat z pageIndex. Extent totiž vyžaduje jen číslo bez závorek a písmen, tedy to, co odpovídá indexu. Je to takhle ok?

**Comment by krizovj** [comment]
Jo, super. 
Podle mě to má validátor asi blbě nastavený, ptž si myslím, že povinný to bejt nemůže. Vždyť celý element extent je O... ale dc:coverage je povinný... :D Udělej to z pageIndex prosím.

**Comment by krizovj** [comment]
je tam
