### ISSUE TITLE
RDflow - automatizace propojení

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1154]
Při připojení skenů k objektu automaticky uzavřít úkol "Připojení skenů"

**Comment by nezbedova** [comment]
Funguje u úkolu Popis v ProArcu. Úkol připojení skenů je tímto duplicitní.
Při tvorbě xml RDflow používat (sjednotit) jen úkol Popis v ProArcu.
Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.

**Comment by ZdenkaSera** [comment]
Jen z evidenčních důvodů přidávám štítek "Rozšíření 2021".
