### ISSUE TITLE
Dvě úrovně typu dokumentu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1155]
V popisu by kromě modelu mělo být další rozdělení na typy dokumentu. Mohlo by se zapisovat do elementu "genre" s nějakým konkrétním atributem. 

Dále je potřeba vytvořit seznam hodnot, které by se pro jednotlivé modely daly vybrat.

**Comment by krizovj** [comment]
Ideální by bylo, aby se tento údaj přidával už do katalogizačního záznamu...

**Comment by luckajirku** [comment]
tak tohle bude na poradu s katalogizátory, nabízí se využití pole 655, ale "Podle katalogizační praxe NK ČR se věcná zpřesnění v rámci tohoto pole nepoužívají." Ale zdroj termínů bychom měli, aby to nebyla volná tvora - šlo by vyjít z: https://autority.nkp.cz/vecne-autority/soubor-formalnich-deskriptoru-1/soubor-zakladnich-formalnich-deskriptoru/

**Comment by pavelkocourek** [comment]
**Návrh na řešení podtypu dokumentu v Krameriovi**

Pole genre, atribut type=”class”
Např.
<mods:genre type=”class”>yearbook</mods:genre>

Bude kontrolovaný slovník. 
Ukládat se budou kódy ze slovníku.
Na straně klienta se pak slovníkový kód přeloží na název v jazyce, ve kterém uživatel klienta používá.

Na straně ProArcu se pak bude vybírat ze slovníku omezeného podle modelu dokumentu.
Slovník bude možné konfigurovat na straně klienta ProArcu.

V Solr Krameria bude nové pole class.
Indexer bude do class přebírat z MODS všechny genre type=”class”.
Indexer nebude řešit slovník. Bude přebírat všechny výskyty.
Pro přidání nového prvku do slovníku nebude potřeba zasahovat do Krameria nebo Proarcu. Budou stačit změny na klientovi.
**Slovníky**
Periodika
- Noviny
- Časopisy
- Kalendáře
- Ročenky
- Adresáře
Grafiky
- Pohlednice
- Kresby
- Plakáty
- Fotografie
- Veduty

**Comment by ZdenkaSera** [comment]
Zavírám po interní dohodě v KNAV.
