### ISSUE TITLE
Nastavit status objektu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1162]

**Comment by krizovj** [comment]
Asi teď zrovna nevím, o co přesně jde. Co to má dělat a jak?

**Comment by krizovj** [comment]
Ahá, to patří zřejmě k RDflow, že jo?

**Comment by nezbedova** [comment]
Já nevím. je to tak podrobně popsané . . .

**Comment by SykoraLukas** [comment]
Funkční, více ve [správě uživatelů](https://github.com/proarc/proarc/wiki/U%C5%BEivatel%C3%A9-spr%C3%A1va)
