### ISSUE TITLE
Chybová hláška archive balíček

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1169]
Při pokusu o export archivebalíčku mi vyskakuje hláška o chybě uuid, které nemám.

![obrazek](https://user-images.githubusercontent.com/13831946/82226547-ecddfe80-9926-11ea-9951-e6854519b35b.png)

**Comment by SykoraLukas** [comment]
Stalo se ještě někdy?

**Comment by nezbedova** [comment]
Mně ne, to bych to sem přidala.
