### ISSUE TITLE
Proč jde zapisovat k výběru typu strany?

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1170]
![obrazek](https://user-images.githubusercontent.com/13831946/82227864-9e316400-9928-11ea-93e2-85b88e0728c6.png)

**Comment by nezbedova** [comment]
A proč nelze vybírat ze seznamu za pomocí prvního písmene? Dříve to šlo.

**Comment by nezbedova** [comment]
Nemohu otestovat, nemám NDK strany.

**Comment by luckajirku** [comment]
Vypadá to v pořádku,
1. zapisovat k typu strany nejde, OK
2. vybírat ze seznamu pomocí 1. písmene jde, OK
