### ISSUE TITLE
chyba načítání

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1171]
@SykoraLukas poslala jsem Vám soubory, které mi nejdou načíst do ProArcu. je u nich i printscreen chyby.
Prosím o sdělení, v čem je chyba, prošč to nelze.

**Comment by SykoraLukas** [comment]
Již mám staženo. Problém je v tom, že všechny soubory se musí jmenovat stejně a lšit se pouz příponou.

např:

0001.tif
0001.xml
0001.txt

Vaše soubory se jmenují takto:
![image](https://user-images.githubusercontent.com/27210823/82665268-b9a3b400-9c33-11ea-820e-46ea4603345f.png)

Po opravě by to již mělo být v pořádku.

**Comment by nezbedova** [comment]
Děkuji za rychlou reakci.
