### ISSUE TITLE
3.5.18 - Stažení článku z katalogu - geografická klíčová slova

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1172]
Mám problém, pokud stahuju záznam článku z katalogu a je tam geografické klíčové slovo (Česko, Šumava, atd...) - v Alephu je to pole 651. 
Když k tomu klíčovému slovu chci doplnit jazyk, tak ProArc vyhodí tuto neočekávanou chybu a záznam neuloží (když doplním jazyk k ostatním klíčovým slovům, tak je to OK):

Transport error - HTTP code: 500 for URL: https://proarc-ozc-test.lib.cas.cz/proarc/rest/v1/object/mods/custom
Status: -90
Query: { "operationType":"update", "dataSource":"ModsCustomDataSource", "data":{ "pid":"uuid:dc22d67c-8369-40b9-ac51-415fb6458314", "timestamp":"1590737726337", "editorId":"model:bdmarticle", "jsonData":{ "mods":{ "classification":[ { "value":"2", "authority":"Konspekt" }, { "value":"57/59", "authority":"udc", "edition":"Konspekt" } ], "genre":[ { "value":"article" }, { "value":"text", "authority":"rdacontent" }, { "value":"články", "authority":"czenas" }, { "value":"journal articles", "authority":"eczenas" } ], "identifier":[ { "value":"dc22d67c-8369-40b9-ac51-415fb6458314", "type":"uuid" }, { "value":"0044-4812", "type":"issn" } ], "language":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "location":{ "physicalLocation":{ "value":"ABA007" } }, "name":{ "namePart":[ { "value":"Čihař", "type":"family" }, { "value":"Jiří", "type":"given" }, { "value":"1930-2009", "type":"date" } ], "role":{ "roleTerm":{ "value":"aut", "authority":"marcrelator", "type":"code" } }, "nameIdentifier":{ "value":"jk01021822" }, "usage":"primary", "type":"personal" }, "note":{ "value":"Jiří Čihař.", "type":"statement of responsibility", "altRepGroup":"00" }, "part":{ "extent":{ "start":{ "value":"178" } } }, "physicalDescription":{ "form":[ { "value":"print", "authority":"marcform", "type":"code" }, { "value":"bez média", "authority":"rdamedia", "type":"media" }, { "value":"svazek", "authority":"rdacarrier", "type":"carrier" } ], "extent":{ "value":"Ilustrace." } }, "recordInfo":{ "recordContentSource":{ "value":"ABA007", "authority":"marcorg" }, "recordCreationDate":{ "value":"20200529T093106", "encoding":"iso8601" }, "recordChangeDate":{ "value":"20200529T093526", "encoding":"iso8601" }, "recordIdentifier":{ "value":"002464205", "source":"CZ PrAS" }, "languageOfCataloging":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "recordOrigin":{ "value":"machine generated" }, "recordInfoNote":{ "value":"Converted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl\n (Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)" } }, "relatedItem":{ "identifier":{ "value":"0044-4812", "type":"issn" }, "name":{ "type":"personal" }, "originInfo":{ "publisher":{ "value":"SSČ" } }, "part":[ { "text":{ "value":"Roč. 38, č. 4 (1990), s. 178-179" } }, { "detail":[ { "number":{ "value":"38" }, "level":1 }, { "number":{ "value":"4" }, "level":2 }, { "level":3 } ] } ], "titleInfo":{ "title":{ "value":"Živa : časopis přírodnický" } }, "type":"host" }, "subject":[ { "geographicCode":[ { "value":"e-xr---", "authority":"marcgac" }, { "value":"e-xr-cc" }, { "value":"e-gx---", "authority":"marcgac" }, { "value":"e-au---", "authority":"marcgac" } ] }, { "topic":{ "value":"Biologické vědy" }, "authority":"Konspekt" }, { "topic":{ "value":"zoologie" }, "authority":"czenas" }, { "topic":{ "value":"obojživelníci" }, "authority":"czenas" }, { "topic":{ "value":"čolek horský" }, "authority":"czenas" }, { "topic":{ "value":"zoology" }, "authority":"eczenas" }, { "topic":{ "value":"amphibians" }, "authority":"eczenas" }, { "topic":{ "value":"Triturus alpestris", "lang":"cze" }, "authority":"eczenas" }, { "geographic":{ "value":"Šumava (pohoří : oblast)" }, "authority":"czenas", "topic":{ "lang":"cze" } }, { "geographic":{ "value":"Šumava Mountains" }, "authority":"eczenas" } ], "targetAudience":{ "value":"specialized", "authority":"marctarget" }, "titleInfo":{ "title":{ "value":"Čolek hořský na Šumavě" }, "subTitle":{ "value":"vliv teploty na vývoj" } }, "typeOfResource":{ "value":"text" }, "version":"3.6" }, "reviewed":"false", "rdaRules":"true" }, "_operationType":"update", "_textMatchStyle":"exact", "_dataSource":"ModsCustomDataSource", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "requestId":"ModsCustomDataSource$62762", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "willHandleError":true, "showPrompt":true, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"PUT", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "originalData":{ "pid":"uuid:dc22d67c-8369-40b9-ac51-415fb6458314", "timestamp":"1590737726337", "editorId":"model:bdmarticle", "jsonData":{ "mods":{ "classification":[ { "value":"2", "authority":"Konspekt" }, { "value":"57/59", "authority":"udc", "edition":"Konspekt" } ], "genre":[ { "value":"article" }, { "value":"text", "authority":"rdacontent" }, { "value":"články", "authority":"czenas" }, { "value":"journal articles", "authority":"eczenas" } ], "identifier":[ { "value":"dc22d67c-8369-40b9-ac51-415fb6458314", "type":"uuid" }, { "value":"0044-4812", "type":"issn" } ], "language":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "location":{ "physicalLocation":{ "value":"ABA007" } }, "name":{ "namePart":[ { "value":"Čihař", "type":"family" }, { "value":"Jiří", "type":"given" }, { "value":"1930-2009", "type":"date" } ], "role":{ "roleTerm":{ "value":"aut", "authority":"marcrelator", "type":"code" } }, "nameIdentifier":{ "value":"jk01021822" }, "usage":"primary", "type":"personal" }, "note":{ "value":"Jiří Čihař.", "type":"statement of responsibility", "altRepGroup":"00" }, "part":{ "extent":{ "start":{ "value":"178" } } }, "physicalDescription":{ "form":[ { "value":"print", "authority":"marcform", "type":"code" }, { "value":"bez média", "authority":"rdamedia", "type":"media" }, { "value":"svazek", "authority":"rdacarrier", "type":"carrier" } ], "extent":{ "value":"Ilustrace." } }, "recordInfo":{ "recordContentSource":{ "value":"ABA007", "authority":"marcorg" }, "recordCreationDate":{ "value":"20200529T093106", "encoding":"iso8601" }, "recordChangeDate":{ "value":"20200529T093526", "encoding":"iso8601" }, "recordIdentifier":{ "value":"002464205", "source":"CZ PrAS" }, "languageOfCataloging":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "recordOrigin":{ "value":"machine generated" }, "recordInfoNote":{ "value":"Converted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl\n (Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)" } }, "relatedItem":{ "identifier":{ "value":"0044-4812", "type":"issn" }, "name":{ "type":"personal" }, "originInfo":{ "publisher":{ "value":"SSČ" } }, "part":[ { "text":{ "value":"Roč. 38, č. 4 (1990), s. 178-179" } }, { "detail":[ { "number":{ "value":"38" }, "level":1 }, { "number":{ "value":"4" }, "level":2 }, { "level":3 } ] } ], "titleInfo":{ "title":{ "value":"Živa : časopis přírodnický" } }, "type":"host" }, "subject":[ { "geographicCode":[ { "value":"e-xr---", "authority":"marcgac" }, { "value":"e-xr-cc" }, { "value":"e-gx---", "authority":"marcgac" }, { "value":"e-au---", "authority":"marcgac" } ] }, { "topic":{ "value":"Biologické vědy" }, "authority":"Konspekt" }, { "topic":{ "value":"zoologie" }, "authority":"czenas" }, { "topic":{ "value":"obojživelníci" }, "authority":"czenas" }, { "topic":{ "value":"čolek horský" }, "authority":"czenas" }, { "topic":{ "value":"zoology" }, "authority":"eczenas" }, { "topic":{ "value":"amphibians" }, "authority":"eczenas" }, { "topic":{ "value":"Triturus alpestris", "lang":"cze" }, "authority":"eczenas" }, { "geographic":{ "value":"Šumava (pohoří : oblast)" }, "authority":"czenas", "topic":{ "lang":"cze" } }, { "geographic":{ "value":"Šumava Mountains" }, "authority":"eczenas" } ], "targetAudience":{ "value":"specialized", "authority":"marctarget" }, "titleInfo":{ "title":{ "value":"Čolek hořský na Šumavě" }, "subTitle":{ "value":"vliv teploty na vývoj" } }, "typeOfResource":{ "value":"text" }, "version":"3.6" }, "reviewed":"false", "rdaRules":"true" } }, "unconvertedDSRequest":{ "operationType":"update", "dataSource":"ModsCustomDataSource", "data":{ "pid":"uuid:dc22d67c-8369-40b9-ac51-415fb6458314", "timestamp":"1590737726337", "editorId":"model:bdmarticle", "jsonData":{ "mods":{ "classification":[ { "value":"2", "authority":"Konspekt" }, { "value":"57/59", "authority":"udc", "edition":"Konspekt" } ], "genre":[ { "value":"article" }, { "value":"text", "authority":"rdacontent" }, { "value":"články", "authority":"czenas" }, { "value":"journal articles", "authority":"eczenas" } ], "identifier":[ { "value":"dc22d67c-8369-40b9-ac51-415fb6458314", "type":"uuid" }, { "value":"0044-4812", "type":"issn" } ], "language":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "location":{ "physicalLocation":{ "value":"ABA007" } }, "name":{ "namePart":[ { "value":"Čihař", "type":"family" }, { "value":"Jiří", "type":"given" }, { "value":"1930-2009", "type":"date" } ], "role":{ "roleTerm":{ "value":"aut", "authority":"marcrelator", "type":"code" } }, "nameIdentifier":{ "value":"jk01021822" }, "usage":"primary", "type":"personal" }, "note":{ "value":"Jiří Čihař.", "type":"statement of responsibility", "altRepGroup":"00" }, "part":{ "extent":{ "start":{ "value":"178" } } }, "physicalDescription":{ "form":[ { "value":"print", "authority":"marcform", "type":"code" }, { "value":"bez média", "authority":"rdamedia", "type":"media" }, { "value":"svazek", "authority":"rdacarrier", "type":"carrier" } ], "extent":{ "value":"Ilustrace." } }, "recordInfo":{ "recordContentSource":{ "value":"ABA007", "authority":"marcorg" }, "recordCreationDate":{ "value":"20200529T093106", "encoding":"iso8601" }, "recordChangeDate":{ "value":"20200529T093526", "encoding":"iso8601" }, "recordIdentifier":{ "value":"002464205", "source":"CZ PrAS" }, "languageOfCataloging":'$$BACKREF$$:.data.jsonData.mods.recordInfo.languageOfCataloging', "recordOrigin":{ "value":"machine generated" }, "recordInfoNote":{ "value":"Converted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl\n (Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)" } }, "relatedItem":{ "identifier":{ "value":"0044-4812", "type":"issn" }, "name":{ "type":"personal" }, "originInfo":{ "publisher":'$$BACKREF$$:.data.jsonData.mods.relatedItem.originInfo.publisher' }, "part":[ { "text":{ "value":"Roč. 38, č. 4 (1990), s. 178-179" } }, { "detail":[ { "number":{ "value":"38" }, "level":1 }, { "number":{ "value":"4" }, "level":2 }, { "level":3 } ] } ], "titleInfo":{ "title":{ "value":"Živa : časopis přírodnický" } }, "type":"host" }, "subject":[ { "geographicCode":[ '$$BACKREF$$:.data.jsonData.mods.subject[0].geographicCode[0]', '$$BACKREF$$:.data.jsonData.mods.subject[0].geographicCode[1]', '$$BACKREF$$:.data.jsonData.mods.subject[0].geographicCode[2]', '$$BACKREF$$:.data.jsonData.mods.subject[0].geographicCode[3]' ] }, { "topic":{ "value":"Biologické vědy" }, "authority":"Konspekt" }, { "topic":{ "value":"zoologie" }, "authority":"czenas" }, { "topic":{ "value":"obojživelníci" }, "authority":"czenas" }, { "topic":{ "value":"čolek horský" }, "authority":"czenas" }, { "topic":{ "value":"zoology" }, "authority":"eczenas" }, { "topic":{ "value":"amphibians" }, "authority":"eczenas" }, { "topic":{ "value":"Triturus alpestris", "lang":"cze" }, "authority":"eczenas" }, { "geographic":{ "value":"Šumava (pohoří : oblast)" }, "authority":"czenas", "topic":{ "lang":"cze" } }, { "geographic":{ "value":"Šumava Mountains" }, "authority":"eczenas" } ], "targetAudience":{ "value":"specialized", "authority":"marctarget" }, "titleInfo":{ "title":'$$BACKREF$$:.data.jsonData.mods.titleInfo.title', "subTitle":{ "value":"vliv teploty na vývoj" } }, "typeOfResource":{ "value":"text" }, "version":"3.6" }, "reviewed":"false", "rdaRules":"true" } }, "requestId":"ModsCustomDataSource$62762", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "willHandleError":true, "showPrompt":true, "lastClientEventThreadCode":"MUP9", "$135w":null, "parentNode":null, "httpMethod":"PUT", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "originalData":{ "pid":"uuid:dc22d67c-8369-40b9-ac51-415fb6458314", "timestamp":"1590737726337", "editorId":"model:bdmarticle", "jsonData":{ "mods":{ "classification":[ { "value":"2", "authority":"Konspekt" }, { "value":"57/59", "authority":"udc", "edition":"Konspekt" } ], "genre":[ { "value":"article" }, { "value":"text", "authority":"rdacontent" }, { "value":"články", "authority":"czenas" }, { "value":"journal articles", "authority":"eczenas" } ], "identifier":[ { "value":"dc22d67c-8369-40b9-ac51-415fb6458314", "type":"uuid" }, { "value":"0044-4812", "type":"issn" } ], "language":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "location":{ "physicalLocation":{ "value":"ABA007" } }, "name":{ "namePart":[ { "value":"Čihař", "type":"family" }, { "value":"Jiří", "type":"given" }, { "value":"1930-2009", "type":"date" } ], "role":{ "roleTerm":{ "value":"aut", "authority":"marcrelator", "type":"code" } }, "nameIdentifier":{ "value":"jk01021822" }, "usage":"primary", "type":"personal" }, "note":{ "value":"Jiří Čihař.", "type":"statement of responsibility", "altRepGroup":"00" }, "part":{ "extent":{ "start":{ "value":"178" } } }, "physicalDescription":{ "form":[ { "value":"print", "authority":"marcform", "type":"code" }, { "value":"bez média", "authority":"rdamedia", "type":"media" }, { "value":"svazek", "authority":"rdacarrier", "type":"carrier" } ], "extent":{ "value":"Ilustrace." } }, "recordInfo":{ "recordContentSource":{ "value":"ABA007", "authority":"marcorg" }, "recordCreationDate":{ "value":"20200529T093106", "encoding":"iso8601" }, "recordChangeDate":{ "value":"20200529T093526", "encoding":"iso8601" }, "recordIdentifier":{ "value":"002464205", "source":"CZ PrAS" }, "languageOfCataloging":{ "languageTerm":{ "value":"cze", "authority":"iso639-2b", "type":"code" } }, "recordOrigin":{ "value":"machine generated" }, "recordInfoNote":{ "value":"Converted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl\n (Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)" } }, "relatedItem":{ "identifier":{ "value":"0044-4812", "type":"issn" }, "name":{ "type":"personal" }, "originInfo":{ "publisher":{ "value":"SSČ" } }, "part":[ { "text":{ "value":"Roč. 38, č. 4 (1990), s. 178-179" } }, { "detail":[ { "number":{ "value":"38" }, "level":1 }, { "number":{ "value":"4" }, "level":2 }, { "level":3 } ] } ], "titleInfo":{ "title":{ "value":"Živa : časopis přírodnický" } }, "type":"host" }, "subject":[ { "geographicCode":[ { "value":"e-xr---", "authority":"marcgac" }, { "value":"e-xr-cc" }, { "value":"e-gx---", "authority":"marcgac" }, { "value":"e-au---", "authority":"marcgac" } ] }, { "topic":{ "value":"Biologické vědy" }, "authority":"Konspekt" }, { "topic":{ "value":"zoologie" }, "authority":"czenas" }, { "topic":{ "value":"obojživelníci" }, "authority":"czenas" }, { "topic":{ "value":"čolek horský" }, "authority":"czenas" }, { "topic":{ "value":"zoology" }, "authority":"eczenas" }, { "topic":{ "value":"amphibians" }, "authority":"eczenas" }, { "topic":{ "value":"Triturus alpestris", "lang":"cze" }, "authority":"eczenas" }, { "geographic":{ "value":"Šumava (pohoří : oblast)" }, "authority":"czenas", "topic":{ "lang":"cze" } }, { "geographic":{ "value":"Šumava Mountains" }, "authority":"eczenas" } ], "targetAudience":{ "value":"specialized", "authority":"marctarget" }, "titleInfo":{ "title":{ "value":"Čolek hořský na Šumavě" }, "subTitle":{ "value":"vliv teploty na vývoj" } }, "typeOfResource":{ "value":"text" }, "version":"3.6" }, "reviewed":"false", "rdaRules":"true" } } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1590742330042, "useHttpProxy":null }

**Comment by krizovj** [comment]
Tak to dělají také chronologická klíčová slova (pole 648 v MARCu).

**Comment by pavelkocourek** [comment]
Ze zápisu : KN doplní do issue, odkud stahujeme, co se neukládá apod.

**Comment by NeradovaK** [comment]
Záznamy článků se stahují z katalogu Knihovny AV ČR - Analytika. Záznam se v pořádku stáhne a uloží, pokud ovšem chceme doplnit u některých klíčových slov jazyk, záznam se nám už neuloží a hlásí neočekávanou chybu.
Jde o předmětové heslo osoby (v Alephu pole 600 17),
jméno korporace (v Alephu pole 610),
geografické předmětové heslo (v Alephu pole 651),  
chronologické předmětové heslo (v Alephu 648)

**Comment by tumovam** [comment]
Ve v3.6.1 nelze otestovat, na testovacích instalacích KNAV nefunguje stahování z katalogu. Chybová hláška je kilometr dlouhá a je téměř totožná jako první komentář Jany K. v tomto issue.

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) už stahování z katalogů funguje (ne SKC, ale to se řeší v jiném issue). Otestovali jsme předmětové heslo osoby, jméno korporace, geografické předmětové heslo, i chronologické předmětové heslo a vypadá to, že je vše, jak má být :)

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
