### ISSUE TITLE
3.5.18 - export CEJSH - chybějící metadata

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1173]
V exportu do CEJSH chybí u článků podnázvy. V ostré verzi ProArcu (3.5.7) ale jsou. 
ProArc 3.5.7:
![cejsh3 5 7](https://user-images.githubusercontent.com/21309201/83243397-1f48f080-a19e-11ea-8b2e-785d34b18520.jpg)

Stejný článek ProArc 3.5.18:
![cejsh3 5 18](https://user-images.githubusercontent.com/21309201/83243424-2a9c1c00-a19e-11ea-8488-5c493a120e5e.jpg)

S tím souvisí dotaz, kde a jak přesně se dá prosím nastavit, co přesně v tom exportu bude?

**Comment by krizovj** [comment]
Ve verzi 3.6 se objevila související drobná chyba, v CEJSH exportu se po názvu objeví v xml dvojtečka i v tom případě, že tam žádný podnázev není. Dvojtečka tam má být jen pokud následuje po názvu také podnázev.

**Comment by tumovam** [comment]
Aktualizace od KN: na konci názvu se objevuje dvojtečka a mezera jen v případě, když název nemá vyplněný i podnázev. 

Když je název i podnázev, tak je vše v pořádku ✔️

**Comment by tumovam** [comment]
ve v3.6.1 se zdá být název a podnázev (vč. dvojtečky) v pořádku. Navrhuji issue zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
