### ISSUE TITLE
Import nového archivačního balíku do ProArcu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1174]
Tohle už je zavřeno (https://github.com/proarc/proarc/issues/1051), takže se může udělat import nového archivačního balíku zpátky do ProArcu. 

Zkoušela jsem to ve verzi 3.5.18 a naimportuje se to, ale asi to neumí najít ocr a alto, ptž ty jsou až v NDK balíčku a když z toho chci znovu udělat archivační balík, tak ProArc vyhodí chybu "TXTGRP is missing".

Musí ale zůstat zachovaná možnost importovat zároveň starý archivační balík :)

**Comment by tumovam** [comment]
Jak to vypadá s prací na tomto issue, prosím? Ještě než budeme mazat z PA, rádi bychom vyzkoušeli reimport archivních balíčků do PA... děkuji

**Comment by nezbedova** [comment]
Balíček vyexportovaný z ostrého PA v. 3,6 jsem nahrála do testovacího PA. A nemohu ho najít.

**Comment by nezbedova** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<folder xmlns="http://proarc.lib.cas.cz/xml/common/import/v1/">
    <batchId>35</batchId>
</folder>

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/96572431-1b447900-12cd-11eb-9154-04106d9353a7.png)

**Comment by tumovam** [comment]
@nezbedova Vám šel načíst celý archivní balíček?

**Comment by nezbedova** [comment]
Načetlo se 6 xml a description_device_0001_4c80880b-4e3a-4c91-8d6a-6f2f82bee96e

**Comment by nezbedova** [comment]
Zkusila jsem další. Ten od Inge. Ten se mi načetl a má i OCR.

**Comment by nezbedova** [comment]
archive_eeb76158-8225-4e3c-bc77-feae17ade627

Zase se to zastavilo.

Vypadá to, že neprochází archive balíčky, které jsem dělala včera. Filip je má na kontrolu.
Třeba tam mám nějakou chybu.

**Comment by SykoraLukas** [comment]
Můžete mi prosím jen z těch balíčků, co nejdou naimportovat zaslat? Vyzkouším to u sebe. Děkuji

**Comment by nezbedova** [comment]
f375a406-13d2-42e2-b7fd-adec42224df0

Balíček z 15.6. zkontrolovaný FK. Nenačetl se.

**Comment by tumovam** [comment]
Mně se ještě nepovedl naimportovat ani jeden archivní balíček. Ve Správě importních dávek (Menu -> Import - Historie) mám u všech stav "Chyba načítání!". 

Plus ještě mám asi úplně pitomý dotaz, ale když jsem ve Výběr adresáře s digitalizovanými daty pro přípravu metadat (Menu -> Import -  Nová dávka), mám v Parametrech vybrat Profil "Archivace" nebo jiný? Děkuju

**Comment by SykoraLukas** [comment]
Profil archivace.

Můžete mi nějaký balíček, co nešel naimportovat zaslat?

**Comment by nezbedova** [comment]
Posílám.

**Comment by SykoraLukas** [comment]
Děkuji

**Comment by SykoraLukas** [comment]
Problém nalezen. Je možné, že to jsou arcivní balíčky ze starších verzí? 3.5.17 a starší?

**Comment by nezbedova** [comment]
To by u toho, který jsem poslala mohlo být. Ale to by také mělo fungovat, ne? Máme jich hromadu udělaných.

Posílám další. Ten je ze včera. Ale není po kontrole, snad tam nemám chybu.

archive_ba1b36ab-17bf-4eb1-801a-27172cd62faa

**Comment by SykoraLukas** [comment]
Ano, už to pro ně také funguje.

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) se mi **podařilo** naimportovat archivní balíček z v3.6 s NDK Stranami.
Volám sláva a budu se celý víkend radovat :)) Díííky moc!

**Comment by nezbedova** [comment]
archive_ba1b36ab-17bf-4eb1-801a-27172cd62faa - načetl se

archive_f375a406-13d2-42e2-b7fd-adec42224df0 - nenašla jsem ani podle uuid ani podle názvu

archive_aac93395-bce2-4eae-8266-29f4d9ad886b - načetl se

**Comment by SykoraLukas** [comment]
Jak to vypadá, dají se už balíčky načítat?

**Comment by nezbedova** [comment]
archive_26b08553-f729-4376-b744-b3ed48d03036 - nenačetl se. Uvnitř je jen

![obrazek](https://user-images.githubusercontent.com/13831946/102108742-92ad0980-3e33-11eb-9a86-1f8a4a565e98.png)

**Comment by nezbedova** [comment]
4f7b6537-e7bc-4c2f-acea-cf3f4a663e65 - se načetl

**Comment by nezbedova** [comment]
archive_1b36964b-6463-4323-8d22-3de20b3deda8 - nenačetl se. 

Ty dva, které se nenačetly jsou z července.

Ještě zkusím nějaký z poslední verze, ale až zítra. Mám k dispozici jen vícedílky a nemohu do PA.

**Comment by tumovam** [comment]
Zkoušela jsem archivní balíčky, vyexportované z ostré v3.6 během uplynulých 2 týdnů. Všechno v pořádku. Ještě potřebuju vyzkoušet vícedílku, ale archivní balíček VD právě teď nemám... Zatím prosím nezavírat, děkuji

**Comment by nezbedova** [comment]
Já jsem si přes noc nakopírovala vícedílku.

archive_588dbee3-6a36-45f7-88f2-17aa34aede87

Balíček se nahrál.

**Comment by nezbedova** [comment]
archive_385a764c-b90e-41fd-a8fe-588a5e12aa91 z letošního března se nahrál

**Comment by tumovam** [comment]
Ve verzi 3.6.2 i 3.6.3 funguje, přidávám label 7 - návrh na zavření... Díky!

**Comment by SykoraLukas** [comment]
Uzavírám na základě otestování.
