### ISSUE TITLE
Původní nezpracované skeny - připojení k archivnímu balíčku přes ProArc

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1175]
Původní nezpracované skeny by se měly k archivačnímu balíčku připojovat přes ProArc. Popis ze zápisu  ze schůzky, která k tomu byla v únoru 2020: 

Původní nezpracované skeny by měly být součástí archivního balíčku (KNAV - dodáváme je tam po exportu z ProArcu ručně) - měly by jít do ProArcu nebo ne? Zřejmě asi ne - možná by se v metadatech mohly objevit názvy souborů
- na úrovni čísla, monografie (na úroveň, na kterou se přiděluje urn:nbn) by se přidal seznam názvů souborů původních nezpracovaných skenů
- při exportu se zkontroluje, že jsou validní cesty. Pokud ano, tak vyexportuje soubor do určené složky (v KNAV Original_Tif) v archivním balíčku
- reimport - vezme složku a $PROARC_HOME/archival_copies vytvoří složku podle uuid objektu, ke kterému se váže balík (stejná úroveň, které se přiděluje urn:nbn) a do složky překopíruje data ze vstupu (ze složky Original_Tif)
- Při exportu hledá ProArc soubor s cestami, pokud tam soubor s cestami není, podívá se do $PROARC_HOME/archoval_copies jestli tam najde složku s uuid objektu, ze kterého se tvoří balíček. Pokud ani tady není seznam obrázků, vyhodí dialogové okno, že nenašel, pokud chtějí pokračovat s exportem bez archival copy.

**Comment by tumovam** [comment]
prosím @SykoraLukas

**Comment by ZdenkaSera** [comment]
- @krizovj Jano, hledala jsem, jestli máme něco dalšího k tomuhle issue - našla jsem zatím jen to, že vzniklo na základě diskuse z 2/2020 - [tady](https://docs.google.com/document/d/1uLewLOibk_Cb8UBZYQMW8fPqstZN2ODuHjin5emxDJI/edit). Prosím Tě, nevíš o něčem dalším k tomuhle tématu?  

- @nezbedova Martino, mám dojem, že o poli, kam by se ukládala cesta ke skenům, byla řeč v souvislosti s RDF, ale také nemám detaily. Prosím, nenapadá Tě k tomu něco?

Díky oběma.

**Comment by SykoraLukas** [comment]
Byla 5e4 o tom, 6eby se to mohlo dopisovat ATM objektu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas já mám dojem, že jsem podobné okénko pro cestu ke skenům viděla někde v úkolech (nemůžu najít) ale je pravda, že RDF nepoužívají všichni (a nejspíš nebudou), takže pokud by ta cesta byla dostupná jen odtud, bylo by to omezující. Pokud by ale byla sdílená, takže by k ní uživatelé RDF mohli přes úkoly/záměry a ostatní třeba přes ATM .... 
![image](https://user-images.githubusercontent.com/79305516/174295663-83bb5077-c424-44e4-8c74-755aa2f5d6c9.png)

**Comment by krizovj** [comment]
@ZdenkaSera řešilo se to ještě na samostatné schůzce s dalšími věcmi - zápis je [tady](https://docs.google.com/document/d/1KUlAniDi8TO6tUSQMRUs5vLF5KKhlZrMgwZkEu7Zk6A/edit?usp=sharing), ale nevím, jestli v tom zápisu najdeš něco navíc. Info jsem přímo zkopírovala, aby to bylo přesně... Co byste k tomu ještě potřebovali vědět?

**Comment by ZdenkaSera** [comment]
@krizovj Zatím děkuju - tenhle zápis jsme našla a měl na něj být odkaz výše, jen jsem omylem klikla na lednový, jak jsem měla otevřenou celou řadu zápisů. Ozvu se ti mimo issue.

**Comment by SykoraLukas** [comment]
Co znamená, že vyhodí okno (uplně na konci)? Jak se mám chovat Aplikace na toto? Má to být jen informativní, nebo má spadnout  export do chyby?

**Comment by kerschfilip** [comment]
pardon, v posledním bodě, pokud nebude nalezena cesta k nezpracovaným skenům, nic nebude v $PROARC_HOME/archoval_copie a nevyužijí se ani ty varianty "Skeny nejsou k dispozici" nebo "Přidat Informaci", tak by měl export spadnout do chyby

**Comment by ZdenkaSera** [comment]
Chyba při exportu archivu (non-extended) založena zde https://github.com/proarc/proarc-client/issues/493

**Comment by SykoraLukas** [comment]
Upraveno. Aby proběhl rozšířený archivní balíček, tak musí být zapnutá konfigurace a zároveň spuštěn archivní export z nového klienta.

Pokud:
konfigurace API vypnutá (bez ohledu na archivní export z klienta)--> klasický archivní balíček
konfigurace API zapnutá + klasický archivní export z klienta --> klasický archivní balíček
konfigurace API zapnutá + rozšířený archivní export z klienta --> rozšířený archivní balíček

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, o tomhle issue jsme se včera bavili - prosíme o uživatelský popis funkčnosti, mj. 
- kam zadat cestu ke skenům v jádře/klientovi ručně  (RDflow, v ATM v klientovi asi chybí vstupní pole?)
- kde všude a s jakým pořadím přístupu se cesta hledá (RDFlow, ATM, adresář automaticky založený při importu archivu do ProArcu..)
- - odkud se vezmou skeny, když naimportuji archiv se surovými skeny do ProArcu, některé skeny doplním, nahradím ... a uložím a) jen tyto nové, b) původní včetně nových do vlastního adresáře a adresář vzniklý při importu nesmažu?

Děkujeme.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zařadíme do dalšího balíčku priorit.

**Comment by SykoraLukas** [comment]
Skeny se vždy berou v tomto pořadí, bez ohledu na to, jaká operace je s nimi prováděna. Jakmile se najde první složka co existuje tak se použije. Primárně se hledá v ATM monografie, čísla periodika, poté se hledá ve složce archival_copies v $PROARC_HOME dle pidu monografie/čísla periodika a naposled se hledá ve workflow dle pidu monografie/čísla periodika.

V novém klientovi políčko pro vyplnění chybí. Zakládám na klientovi s prioritou.

**Comment by SykoraLukas** [comment]
Pole je doplněné do klienta https://github.com/proarc/proarc-client/issues/580

**Comment by ZdenkaSera** [comment]
k testu na klientovi.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)

**Comment by ZdenkaSera** [comment]
Znovu otevírám, jen aby oprava nebyla opomenuta ve verzi.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV, zavírám.
