### ISSUE TITLE
Import NDK balíku do ProArcu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1177]
Výhledově by se měl zprovoznit import NDK balíku do ProArcu.

**Comment by ZdenkaSera** [comment]
Dořešit, jak naložit s "neúplným" NDK balíčkem - bude vytvořen jako neúplný

**Comment by SykoraLukas** [comment]
Mezi importní profily je nutné přidat hodnotu: profile.default_ndk_import

**Comment by SykoraLukas** [comment]
Popis konfigurace je dostupný [zde](https://github.com/proarc/proarc/wiki/Konfigurace#ndk-import)

Implementováno pro NDK Periodika, NDK monografie, STT monografie, NDK Zvukové dokumenty, NDK eMonografie a NDK ePeriodika.

**Comment by ZdenkaSera** [comment]
Při pokusu o import NDK balíčku NDK svazku monografie se objevila nepřeložená hláška "IMPORT_PLANNED" (verze cs-en)

Následně vyskočila přiložená chyba. Tu nešlo nijak překonat (lze ji zavřít, ale nepomůže to) a vyskakuje opakovaně při pokusu zobrazit ve správě procesů "vše" nebo "načítání". 
Monografie v balíčku má NDK strany, testovací systém je pro standardní importy skenů nastaven na použití modelu "strana" .

![image](https://github.com/proarc/proarc/assets/79305516/9a096f47-eb9b-4de7-8cae-6ebf89630a6a)

Překvapivě se nakonec se ukázalo, že je zapotřebí mít trpělivost, monografie se načetla, pouze nelze sledovat průběh jejího načítání (ani ničeho jiného ve frontě načítání), dokud proces neskončí. Ve správě procesů pak chuybí překlad ve sloupci "profil"

![image](https://github.com/proarc/proarc/assets/79305516/48aecd59-19d4-4689-a094-79f57e88982b)

**Comment by SykoraLukas** [comment]
Posli mi prosim tento balicek. Podivam se na to

**Comment by ZdenkaSera** [comment]
@SykoraLukas odeslán mail.

**Comment by SykoraLukas** [comment]
Doplněna podpora pro import na urovni uuid.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Kdyby to mohlo pomoci - Petr @PetrKotynek připravil konfig do zipu, tak můžeme poslat mimo issue.

**Comment by PetrKotynek** [comment]
Jeste logy, myslel jsem že tam nic nebude ale možná ?  PK

12-Feb-2024 09:14:01.123 SEVERE [ajp-nio2-127.0.0.1-9009-exec-12] cz.cas.lib.proarc.webapp.server.rest.v2.ImportResource.listBatchItems PID: uuid:02f42524-7c3b-4797-9ed0-80dd20893c7f, Unexpected model for NDK page: model:ndkmonographvolume
	cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:02f42524-7c3b-4797-9ed0-80dd20893c7f, Unexpected model for NDK page: model:ndkmonographvolume
[log.zip](https://github.com/proarc/proarc/files/14257077/log.zip)

**Comment by ZdenkaSera** [comment]
@PetrKotynek Moc děkuji. Prosím, mohl bys vytáhnout log k uuid.3a99c250-bc5d-4318-a5a8-db00547fd5c4? To byl poslední import 12.2. kolem 12:40, tj. odpovídá stávajícímu nastavení.

**Comment by ZdenkaSera** [comment]
Rekapitulace rozhovoru s @SykoraLukas 
- test je v KNAV na Fedoře
- chybný převod na STT strany už je na inovatice opraven
- pro účely vstupu do objektu načteného (ve statusu uloženo) je ve správě procesů nové tlačítko "Přejít do objektu" - to je funkční, zároveň se do objektu lze dostat dvojklikem, což bude zřejmě vypnuto
- když přejdu do objektu, dostanu se do běžné editace v úložišti; ani po provedení změny a jejím uložení nelze objekt v "Hledání" najít podle názvu ani uuid

**Comment by ZdenkaSera** [comment]
K dořešení také import NKD balíčku k e-objektům. Test na testovacím OZČ s Fedorou na e-monografii - načítání lze spustit bez vybraného zařízení, což je správně. Proces se ale ve skutečnosti nespustí - prosíme o doplnění, co je zapotřebí v konfiguraci. Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Po nasazení fixu: **Test v klientovi**
- [ ] načítání balíčku už lze spustit na úrovni uuid - ok
- [ ] nevyskakuje už chyba "unexpected model" - ok
- [ ] do zobrazení např. "načítání" nebo "vše" ve správě procesů ale stále nejde přejít během načítání, vyskakuje chyba "importní dávku nelze editovat"
- [ ] po uložení lze dávku ze správy procesů otevřít (přejit na objekt) - má NDK strany - ok
- [ ] objekt lze vyhledat i v úložišti - ok
- [ ] dávky načtené před nasazením fixu jsou i nadále dohledatelné jen jádře přes "rozšířený dotaz"; dá se tzam s nim i pracovat (převést STT strany na NDK ...)

**Comment by SykoraLukas** [comment]
Staré dávky bych neresil. Prosím o smazání a znovu naimportovani.

**Comment by ZdenkaSera** [comment]
Při importu NDK balíčku k NDK svazku monografie s přílohou se příloha zařadila na začátek před strany monografie - lze ji sice ručně přesunout, ale je to matoucí. Půjde to změnit a zařadit přílohu za poslední sken monografie rovnou? Připravím ještě příklad s několika přílohami.

![image](https://github.com/proarc/proarc/assets/79305516/662b03f6-ffd2-4820-a0c2-9ac15c79cd26)

**Comment by SykoraLukas** [comment]
Vychází to z toho, jak je řazeno v NDK. Můžeme změnit pořadí, ale bude se to týkat všech.

**Comment by ZdenkaSera** [comment]
NDK balíček k vícedílné monografii už lze načíst z její horní úrovně, netřeba po dílech. Díky.

**Comment by ZdenkaSera** [comment]
**NDK PSP vícedílky - test importu lokálně v verzi 4.1.2./2.2.1**
- Lze importovat na úrovni uuid vícedílné monografie (tj. opravena potřeba importovat na úrovni  urn:nbn jednotlivých dílů)
- Svazky VD vytvořené ve starší verzi standardu (tj. jako NDK svazky monografie) se při importu rovnou konvertují do modelu NDK svazek vícedílné monografie
- následný export nového NDK PSP balíčku a archivu z importované VD bez problémů (zatím bez validace).
