### ISSUE TITLE
Doplnění upozornění (k releasu) o nutnosti updatovat dokumenty při přechodu z verze <3.5.17 na verzi >= 3.5.18

### ISSUE THREAD

**Issue by mjtecka** [proarc/proarc#1179]
Zdravím,

šla by přidat noticka na změny, které se musí udělat při přechodu z verze menší než 3.5.17 i k dalším verzím než jen 3.5.18? Nebo to vyřešit nějak systematičtěji? Můj "problém":

1) Updatuju z verze 3.5.9 na 3.5.19
2) nevšimnu si poznámky u 3.5.18 (Pro update z verze 3.5.17 a nižší je nutné postupovat podle návodu https://github.com/proarc/proarc/wiki/Instalace#upgrade-z-verze-3517-a-star%C5%A1%C3%AD.)
3) nevidím žádné objekty, mám to nějaké rozbité...
4) pátrám, pátrám...
5) nakonec mě nějak napadne, že to možná není bug.. a dopracuju se na správné místo ...

... ale stejně - nemělo/nemohlo by být u _každé_ verze upozornění na potřeby provádění větších změn? Nebo se předpokládá, že budu číst changelogy všech verzí mezi tou kterou mám a tou kterou instaluju?

**Comment by SykoraLukas** [comment]
Ve většině verzí není potřeba s objekty nic dělat. Ale doplním informaci o přechodu z verze 3.5.17 a nižších do všech novějších verzí.

**Comment by SykoraLukas** [comment]
Informace přidána ke všem novějším releasum.
