### ISSUE TITLE
pageNumber X page number

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1183]
Šlo by všude prosím opravit atribut "page number" na "pageNumber"? Ve standardu je to sice s mezerou, ale je to překlep a než se to tam všude změní, tak by to chtělo, aby to ProArc vyráběl dobře. Pak s tím má Kramerius problém při importu. Díky!
Je to tak na úrovni strany, a taky na úrovni kapitol a článků, všude v elementu "part".

**Comment by mhalva** [comment]
Při zkušebním exportu NDK balíčku jsem našel totéž. Hodnota "page number" se mi tam objevila na úrovni NDK strany a NDK článku.

**Comment by tumovam** [comment]
Na úrovni Strany, NDK Článku, NDK Kapitoly už je to v pořádku, ale stále přetrvává u **NDK Strany**.

**Comment by tumovam** [comment]
@SykoraLukas, šlo by, prosím, vydat opravu pouze této chyby? Občas proběhne převod Stran na NDK Strany správně, ale kvůli tomuto "detailu" v KNAV nechceme archivní balíčky zálohovat. Lukáši, podíváš se na to, prosím? Ideálně ASAP :)) Díky moc, M.

**Comment by tumovam** [comment]
ve v3.6.1 je PageNumber v pořádku jak u NDK Strany, tak NDK Článku, i NDK Kapitoly. Jsem pro zavření issue.

**Comment by mhalva** [comment]
Potvrzuji, že ve verzi 3.6.1 je PageNumber už v pořádku jak u NDK Strany, tak NDK Článku.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
