### ISSUE TITLE
Přidělování urn:nbn k článkům

### ISSUE THREAD

**Issue by mhalva** [proarc/proarc#1184]
![Poznámka 2020-07-27 183020](https://user-images.githubusercontent.com/41825624/88567289-959b8f00-d037-11ea-933c-633f499e767d.png)

Při pokusu o přidělení urn:nbn k NDK článku se ProArc pokouší ho přidělit k NDK číslu. To už tam ale přidělené je, takže zahlásí chybu, viz screenshot.

Bylo by možné přidělovat urn:nbn i k článkům?

**Comment by tumovam** [comment]
Ve v3.7-Snapshot přidělování urn:nbn NDK článkům funguje.

**Comment by mhalva** [comment]
Potvrzuji. Funguje nám ve verzi 3.6.1. 
Díky za rychlou implementaci.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
