### ISSUE TITLE
Verze 3.6: nefunguje zobrazení typ přílohy periodika ve formuláři

### ISSUE THREAD

**Issue by hosak** [proarc/proarc#1185]
U nové verze 3.6 nefunguje zobrazení Type u druhu přílohy periodika ve formuláři. Jako příklad dávám obrázky z dat popsaných ještě ve starší verzi proarcu (3.5.13 tuším). V XML mají správně uložený druh přílohy (obrázek 1). Formulář se ale tváří, že tam žádný typ přílohy není (obrázek 2).  
![typ přílohy v xml](https://user-images.githubusercontent.com/19148958/89288730-69df6100-d656-11ea-915b-c31d66b7081a.JPG)

![není typ přílohy ve formuláři](https://user-images.githubusercontent.com/19148958/89288739-6d72e800-d656-11ea-80df-b6987d53b8ae.JPG)

**Comment by tumovam** [comment]
26.10. otestováno v SVK HK a funguje. Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
