### ISSUE TITLE
Co všechno se děje se soubory po importu do ProArcu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1186]
Bylo by prosím možné sepsat nějakej přehled, co všechno se děje po tom, co se naimportuje TIFF do ProArcu? 
Například, co se všechno děje s Tifem, že se z nich vyrobí náhledy a kdy který ten proces probíhá. 

Vždycky pak řešíme, kde se nějaká věc bere a proč tam vlastně je a jestli jí tam potřebujeme (viz. JP2 apod.)...

Bylo by možné to nějak srozumitelně sepsat do dokumentace?

**Comment by SykoraLukas** [comment]
Sepsáno zde: https://github.com/proarc/proarc/wiki/Zpracov%C3%A1n%C3%AD-soubor%C5%AF
