### ISSUE TITLE
zdvojený model v DC

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1187]
V Krameriovi máme u novějších záznamů v DC dvakrát model (dc:type, model:monograph), třeba tady: https://kramerius.lib.cas.cz/search/mets?pid=uuid:5cea0a90-b30c-491c-b891-bdc12756c9cc. 
Koukala jsem do foxml do ProArcu a tam je v DC taky dvakrát model, ale jednou je to model: monograph a jednou model:ndkmonographvolume. 

Kramerius z toho pak zřejmě vyrobí dvakrát ten stejný model. Je to tam potřeba mít oboje? Pokud jo, tak oukej, jen abychom věděli, proč to tam je.

**Comment by SykoraLukas** [comment]
Jsou 2x. Opraveno. Model se musí přeuložit, aby se změna projevila. 

U nově založených modelů je dc:type jen jednou.

**Comment by tumovam** [comment]
Vyzkoušeno u dc:type>model:monograph</dc:type

**Comment by tumovam** [comment]
Jen ještě otázka. @SykoraLukas výše píšeš, že "Model se musí přeuložit, aby se změna projevila." ... ehm... kde? Jak přeuložím dříve vytvořené monografie? Děkuju

**Comment by SykoraLukas** [comment]
Otevřít ve formuláři a kliknout na tlačítko uložit.  Další možností je zase funkce na přeuložení všech monografií, podobně, jako se to plánuje k NDK článkům.

**Comment by tumovam** [comment]
Jo ták, funguje. Bála jsem se, že budeme muset znovu stahovat metadata z katalogu :) Tohle asi stačí. Díky.

**Comment by SykoraLukas** [comment]
Uzavírám, na základě otestování.
