### ISSUE TITLE
v. 3.6 - chyba v archive balíčku udělaného z archive balíčku

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1188]
Z testovacího PA v. 3.6 jsem vyexportovala archive balíček. Ten jsem nahrála do ostrého PA v. 3.6. Následně jsem ho exportovala jako archive balíček. Export proběhl s chybovou hláškou 
"Stream:TXTGRP is missing" pid="uuid:ae9ca00e-665d-45c1-8aa4-1a52f5e6d9c8"

Vypátrala jsem, že ve složce NDK jsou jen prázdné složky.

**Comment by nezbedova** [comment]
Další pátrání. Archive balíček se nahraje do ProArcu, ale někam zmizí OCR. Proto se neudělá nový archive balíček. A není to ani v Exportu pro Kramerius (jako že by to nebylo v PA vidět, ale pak by se to záhadně připojilo.)

Žádám o urychlenou nápravu. Bez toho nemůžeme dělat Archive balíčky.

Není to nedostatkem místa. Zkoušela jsem to v "čistém" testovacím ProArcu, kde bylo jen 7 titulů.

**Comment by tumovam** [comment]
@nezbedova a @SykoraLukas tohle souvisí s https://github.com/proarc/proarc/issues/1174 = PA v3.6 ještě neumí reimport balíčku do PA

**Comment by SykoraLukas** [comment]
Můžu poprosit o otestování?

**Comment by nezbedova** [comment]
OCR se načetlo

**Comment by nezbedova** [comment]
archive_8df7ac6a-fe82-4f4b-89a2-b6d1c4d9d59f - je ročník periodika. Sice se při nahrání objevila "neočekávaná chyba". ale ročník se nahrál. Tou chybou mohla být nepřítomnost nadřazeného objektu.
Mám vyzkoušet další ročník a dát sem chybu?

**Comment by nezbedova** [comment]
archive_33b40cc4-9682-4176-a6cb-45cb9fab9222 ročník - hláška o chybě se neobjevila. Ročník se načetl.

**Comment by nezbedova** [comment]
Vypadá to, že se nenahrávají jen balíčky "Inge"

**Comment by tumovam** [comment]
Jsem pro zavření tohoto issue. Chyba (slovy paní N.) "požírání texťáků" vznikla v době, kdy ProArc ještě neuměl načíst i txt z NDK balíčku. Navíc těchto balíčků byly pouze jednotky a v KNAV už jsme je opravili. Ve verzích 3.6.2, 3.6.3 a snad i dalších už tento problém není...

**Comment by SykoraLukas** [comment]
Můžete prosím ještě zkusit otestovat reimport STT archivních balíčků?

**Comment by tumovam** [comment]
prosím @nezbedova , protože nevím, jestli a příp. o které STT šlo. děkuji

**Comment by SykoraLukas** [comment]
Zatím asi o žádný, musí se asi udělat nový export, protože STT archivní balíček je podporován až od verze 3.6.4. Dočasně tedy mažu label návrh na zavření. Pokud export a import archivního balíčku proběhne v pořádku, issue opět označíme k zavření a následně uzavřeme.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, tohle bych uzavřela, ale prosím, mohla bys otestovat na STT?

**Comment by nezbedova** [comment]
Z DC PA Verze: 3.7.3 jsem exportovala archivní balíček.

STT Svazek monografie (uuid:7869563a-c97e-49d4-bec5-a798a86f5a99)

Bez problémů jsem ho nahrála do test PA Verze: 3.8-DEV-BETA.

A bez problémů jsme je vyexportovala. Na první pohled se zdají být komplet.

**Comment by ZdenkaSera** [comment]
@nezbedova Díky!
