### ISSUE TITLE
v 3.6 export s chybou proběhne

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1189]
Pokud se objeví chyba při exportu, tak se objeví chybová hláška, ale export proběhne. Export s chybou by se měl "ztratit" jako to je u chyby, když se nepřidělí urn:nbn.

**Comment by krizovj** [comment]
Balíček by se mohl vyexportovat s chybovým logem a zároveň by před názvem balíčku bylo jasně vidět, že jde o chybový balíček. Např. error_archive_uuid... nebo tak

**Comment by nezbedova** [comment]
Export proběhne, ale balíček má prefix error_archive_, takže ho lze dohledat. Uvnitř je log s chybou a uuid souboru, kde chyba je.

Za nás vpořádku.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
