### ISSUE TITLE
v 3.6 Chybová hláška - odstranit

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1190]
Když se nepřidělí urn.nbn, objeví se hláška, že urn.nbn nebylo přiděleno. Export neproběhne. To je správně.
Ale pak se vzápětí objeví matoucí hláška

![obrazek](https://user-images.githubusercontent.com/13831946/89770472-1b6f0e00-daff-11ea-8168-eb56e45922c9.png)

**Comment by SykoraLukas** [comment]
Toto je chování již od začátku. Vždy pči spuštění importu se objeví tato hláška. Pokud je problém ve Validaci nebo chzbí URN:NBN objeví se poté druhé okno s příslušnou hláškou. 

Bohužel mi to nejde udělat tak, aby se toto okno zavřelo a místo něj se objevilo okno s chybou/validací.

Tento problém se vzřeší v novém klientu.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, můžeme tohle zavřít?

**Comment by nezbedova** [comment]
Nelze změnit. Souhlasím se zavřením. @ZdenkaSera

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
