### ISSUE TITLE
Chyba načítání VSUP

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1192]
Soubory, které u nás načtu do PA, jinde načíst nejdou. Prosím o pomoc. Info z chyby je níže.

/import/proarc_users/users/dejmkova/import/VP 1953/proarc_import/Výtvarná práce I0001.foxml java.io.FileNotFoundException: Missing OCR: /import/proarc_users/users/dejmkova/import/VP 1953/Výtvarná práce I0001.ocr.txt at cz.cas.lib.proarc.common.imports.TiffImporter.importOcr(TiffImporter.java:189) at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:107) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSetImport.java:115) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSets(FileSetImport.java:96) at cz.cas.lib.proarc.common.imports.FileSetImport.start(FileSetImport.java:83) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:210) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:181) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748)

**Comment by SykoraLukas** [comment]
Z toho co vidím, to vypadá na chybu v konfiguraci. Jak se jmenuje soubor ocr? Hádám ze vypadá nějak takto: <název>.txt

Je nutné porovnat konfigurace serverů, můžete mi je prosím poslat na mail?

Nejspíš jedna konfigurace (vaše) bude mít něco jako import.ocr=.txt

Konfigurace na serveru, kde to nelze načíst to bude nejspíš: import.ocr=.ocr.txt

**Comment by nezbedova** [comment]
Požádala jsem jejich IT o zaslání konfigurace jejich ProArcu.

**Comment by nezbedova** [comment]
Získala jsem nějaké informace. 

ProArc

Verze: 3.3

Produkční a archivační systém je nástroj pro výrobu a úpravu popisných, administrativních a technických metadat. Vývoj probíhá pod licencí GNU GPL v3.

Více informací o projektu zde.

Build: 20170517223759, revize fd6149e39
SykoraLukas edited this page 14 days ago · 74 revisions 
Změnila se konfigurace Kakadu - nová hodnota pro element processor.kdu_ac.arg=Creversible\= na hodnotu yes

Dne sjsem do našeho PA nahrála další soubor, který u nich nejde.

**Comment by nezbedova** [comment]
Další info. Tentokrát z IT

nase verze je 3.3 (Build: 20170517223759, revize fd6149e39)

Zaslani konfigurace proArcu si predstavujete jak ? Chcete zaslat obsah proarc.cfg ? Neni problem zde je: 

[root@proarc ~]# cat /home/proarc/.proarc/proarc.cfg
digobject.plugins=ndk, k4, oldprint
# (2.0) ID profilu externího procesu pro vytvoření archivní kopie.
import.ndk_archival.processor=kdu_ac
# (2.0) ID profilu externího procesu pro vytvoření uživatelské kopie.
import.ndk_user.processor=kdu_uc


import.profiles=profile.default, profile.oldprint, profile.default_archive_import
# pridat az bude 3.4 profile.jpgonly,
#oldprints profile

profile.oldprint.label=Staré tisky
profile.oldprint.description=Profil pro staré tisky. Nevyžaduje OCR ani ALTO.
profile.oldprint.file=profile.oldprint.cfg

#oldprints profile JPG
#profile.jpgonly.label=JPG only
#profile.jpgonly.description=Profil pro staré tisky. Nevyžaduje OCR ani ALTO. JPG predloha
#profile.jpgonly.file=profile.oldprint_jpg.cfg


KDU_HOME=/opt/KDU79
KDU_EXEC=${KDU_HOME}/kdu_compress
KDU_LIBPATH=${KDU_HOME}

processor.kdu_ac.exec=${KDU_EXEC}
processor.kdu_ac.environment.LD_LIBRARY_PATH=${KDU_LIBPATH}
processor.kdu_ac.type=kdu_compress
processor.kdu_ac.arg=-quiet
processor.kdu_ac.arg=Cblk\={64\,64}
processor.kdu_ac.arg=Corder\=RPCL
processor.kdu_ac.arg=Stiles\={4096\,4096}
processor.kdu_ac.arg=Cprecincts\={256\,256}\,{256\,256}\,{128\,128}
processor.kdu_ac.arg=ORGtparts\=R
processor.kdu_ac.arg=Creversible\=no
processor.kdu_ac.arg=Clayers\=1
processor.kdu_ac.arg=Clevels\=5
processor.kdu_ac.arg=Cmodes\={BYPASS}
processor.kdu_ac.arg=Cuse_sop\=yes
processor.kdu_ac.arg=Cuse_eph\=yes

processor.kdu_uc.exec=${KDU_EXEC}
processor.kdu_uc.environment.LD_LIBRARY_PATH=${KDU_LIBPATH}
processor.kdu_uc.type=kdu_compress
processor.kdu_uc.arg=-quiet
processor.kdu_uc.arg=Cblk\={64\,64}
processor.kdu_uc.arg=Corder\=RPCL
processor.kdu_uc.arg=Stiles\={1024\,1024}
processor.kdu_uc.arg=Cprecincts\={256\,256}\,{256\,256}\,{128\,128}
processor.kdu_uc.arg=ORGtparts\=R
processor.kdu_uc.arg=-rate
processor.kdu_uc.arg=3
processor.kdu_uc.arg=Clayers\=12
processor.kdu_uc.arg=Clevels\=5
processor.kdu_uc.arg=Cmodes\={BYPASS}

#OAI VSUP TRITIUS
catalogs=aleph_nkp,oai
catalog.oai.url=https://oai.vsup.cz/tritius/oai-provider
catalog.oai.type=OAICatalog
catalog.oai.name=Tritius OAI Katalog
catalog.oai.metadataPrefix=marc21
catalog.oai.fields=id
catalog.oai.field.id.title=Identifikátor

**Comment by SykoraLukas** [comment]
Z toho co tu vidím tak to je opravdu tak, že používají defaultní nastavení pro příponu všech souborů.

Vaše soubory budou mít nejspíše jinou koncovku než jaké povolují jejich konfugurace.

Defualní konfugurace je tato:
import.ndk_archival.file.suffix=.ac.jp2
import.ndk_user.file.suffix=.uc.jp2
import.text_ocr.file.suffix=.ocr.txt
import.alto.file.suffix=.ocr.xml

Řekl bych, že vaše konfigurace bude nejspíš:
jp2 nejspíš neimportujete, protože k jejich vytvoření používáte kakadu
import.text_ocr.file.suffix=.txt
import.alto.file.suffix=.xml

Jejich server vyžaduje na konci .ocr.txt a .ocr.xml, ale vy mu dodáváte soubory s koncovkami .txt a .xml. Proto import neprojde

**Comment by nezbedova** [comment]
A co s tím mají dělat?

**Comment by SykoraLukas** [comment]
Již mají něco zpracované?
Pokud ano - tak by měli přejmenovat soubory, které mají od vás.
Pokud ne - změnil bych konfiguraci tak, aby odpovídala souborům, které jim posíláte.

**Comment by nezbedova** [comment]
Nemají zpracované nic, protože to do ProArcu nedostali. Mají založenou strukturu periodika, ke které budou připojovat.

**Comment by nezbedova** [comment]
Tak jim tu konfiguraci změňte. Za jejich IT to vyřizuje p. Mázl.    lukas.mazl@vsup.cz

**Comment by SykoraLukas** [comment]
Tím pádem doporučuji přidat do souboru proarc.cfg následující:
`
import.text_ocr.file.suffix=.txt
import.alto.file.suffix=.xml
`

Poté by to již mělo jít.

**Comment by SykoraLukas** [comment]
Podařilo se?

**Comment by nezbedova** [comment]
Vše mají hotové. Kde byla chyba nevím. Zavírám.
