### ISSUE TITLE
Podivné chování OAICatalog

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1197]
Na jednom z testovacích serverů vrací následující konfigurace chybu:

catalog.kkp.url=https://tritius.strahovskyklaster.cz/tritius/oai-provider
catalog.kkp.type=OAICatalog
catalog.kkp.name=kkp
catalog.kkp.metadataPrefix=marc21
catalog.kkp.fields=id
catalog.kkp.field.id.title=identifikator
catalog.kkp.fields=name
catalog.kkp.field.name.title=name

Type Exception Report
Message javax.ws.rs.ProcessingException: edu/harvard/hul/ois/jhove/JhoveBase$1
Description The server encountered an unexpected condition that prevented it from fulfilling the request.

viz přiložený soubor. Další instalace vykazují očekávané výsledky. viz obrázek. Příslušnou instalaci jsem reloudoval, bez vlivu.
PK

[strahov_chyba_pri_jeti_jens_test.txt](https://github.com/proarc/proarc/files/5182172/strahov_chyba_pri_jeti_jens_test.txt)
![dotaz_kkp](https://user-images.githubusercontent.com/37083676/92370570-c1ac3480-f0fa-11ea-925a-cd9a4d4a6587.png)

**Comment by SykoraLukas** [comment]
Už se z tohoto katalogu neco stahovalo (fungoval někdy), nebo jde o uplně nový katalog?

**Comment by SykoraLukas** [comment]
Mohl bych ještě poprosit o zaslání proarc.cfg na mail? děkuji

**Comment by PetrKotynek** [comment]
Zdravím,
ano jsou tam nově zřizeny přístupy na Tritius ( předchozi Clavius tam
nějakou chvíli jede, jak jsem pochopil). Zkoušíme se tam nějak dostat a po
delším čekání publikovali OAI a Z39.50.
Děkuji,
Petr Kotýnek
Přikládám cfg od všech strojů.

**Comment by PetrKotynek** [comment]
Změna url=https:// --> url=http:// pomohla. Petr Kotýnek
