### ISSUE TITLE
v. 3.6 chyba při ukládání záznamu staženého z BCBT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1198]
Nejde uložit záznam stažený z katalogu clavius (BCBT). Prověřila jsem to jak v ostrém, tak v testovacím ProArcu a  někdy! to hází "Neočekávaná chyba".  Záznam se založí, ale místo názvu má "?" A nelze uložit změny.

Při zakládání Nového objektu dle id 173298000000422197 - Napíše  "Neočekávaná chyba" . Místo názvu uloží "?" Záznam není editovaný a ani změtně nejdou uložit opravy.

Při zakládání Nového objektu dle id 173298000000514892 - Napíše  "Neočekávaná chyba" Uloží správný název i úpravy. 

Při zakládání Nového objektu dle id 183298000000387814 - žádná hláška a je to založené

![obrazek](https://user-images.githubusercontent.com/13831946/92930890-f691f180-f442-11ea-9b8d-42ae9fd6c1b7.png)

13:56 uzivatel nezbedova - další pokus o založení 173298000000422197. Nový objekt se z databáze stáhl, opravila jsem signaturu. Uložila jsem s "překonat" jiné chyby.

Objevuje se hláška "Neočekávaná chyba". Detail - začátek:
![obrazek](https://user-images.githubusercontent.com/13831946/92931131-4b356c80-f443-11ea-81ee-d073cbd8437d.png)

Odmazala jsem část Title - chyba přetrvává
Zkusila jsem změnu v atributu názvu ze "Zkráceného" na "normální" - zase chyba.

Konzultovala jsem to s p. Kotýnkem a nic jsme nezjistili.

Připomíná mi to chybu, kdy nešlo založit nový záznam přes RDflow. #968 a #866 (to byla opakující se chyba).

U jiné databáze jsme to zatím nezaznamenali.

**Comment by SykoraLukas** [comment]
Záznamy v tohoto katologu jsou vždy pro staré tisky?

Záznamy těch ID uváděných nahoře nemají vyplněné Description Standard, což se očekává, že mít bude.  Pokud vyplněné není, uvádí se hodnota z nastavení (defaultně RDA). Pokud jsou všechny staré tisky popisovány podle AACR, můžeme mu vždy nastavit DescriptionStandard na AACR.

**Comment by nezbedova** [comment]
Mám vyplněno

![obrazek](https://user-images.githubusercontent.com/13831946/95942666-0efb8000-0de4-11eb-8118-6217a0cebbba.png)

**Comment by nezbedova** [comment]
Zajímavé je, že PA titul najde.

![obrazek](https://user-images.githubusercontent.com/13831946/95943040-0e171e00-0de5-11eb-8701-6715b527dc84.png)

**Comment by nezbedova** [comment]
A když se přepnu do metadat, tak se zobrazí

![obrazek](https://user-images.githubusercontent.com/13831946/95943127-428ada00-0de5-11eb-9fac-8993f44e19b2.png)

**Comment by SykoraLukas** [comment]
Děkuji, nyzní se mi již podařilo chybu nasimulovat.

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/96560402-8cc8fb00-12be-11eb-96e7-e05459da6136.png)

Stále mám ? a nezměněná data uvnitř.

**Comment by SykoraLukas** [comment]
Data uvnitř měnit jdou? 

Label se tvoří z titleInfo s prázdným type. Jak máme vyplněné titleInfo?

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/96562062-9eab9d80-12c0-11eb-9b96-26082058003e.png)

**Comment by nezbedova** [comment]
Název změním a dám uložit. Problikne Uloženo. Název je změněný.

Dám Úložiště hledat mám tam ?

Zpátky do metadat. jsou změněná.

**Comment by SykoraLukas** [comment]
Ten otazník tam je protože máte vypněný Type. Pokud bude type prázdný, otazník zmizí a místo něj bude název. Pokud chcete, můžeme to udělat tak, že se bude název dělat z prázdného pole Type a pokud tam žádné takové nebude, udělá se z Type=Abbreviated.

**Comment by nezbedova** [comment]
Jsem ráda, že jste přišel na to, čím to je. Netušila jsem, že se název zobrazí jen když není vyplněný Type. Logické by bylo, aby se zobrazil název pokud je vyplněný Title.

**Comment by SykoraLukas** [comment]
Ono když to má několik titleInfo, tak je tím zaručeno, že se použije právě jeden. Ostatní mají nějaký přiznak (Type). Navrhuji proto, toto vyřešit tak, že nejprve se hledá prázdné type. Pokud není, použije se první type=abbreviated. Pokud není ani to, použije se jakekoli první titleInfo bez ohledu na hodnotu v poli Type.

Souhlasíte?

**Comment by nezbedova** [comment]
Souhlasím.

**Comment by nezbedova** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020)
Titul je vidět. Měnit metadata jdou. Zavírám.
