### ISSUE TITLE
Úprava formuláře pro Vícedílné monografie - NDK i STT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1199]
Do Formuláře pro Vícedílné monografie NDK i STT prosím přidat pole Date Issued. Oprava/úprava tohoto pole je častá a v xml obtížnější než ve formuláři.

**Comment by SykoraLukas** [comment]
Není problém toto udělat, ale pole Date Issued na úrovni Vícedílné monografie není. Nebudeme tak dodržovat standard. Přesto to mám udělat?

**Comment by nezbedova** [comment]
To je otázka na @tumovam

**Comment by nezbedova** [comment]
V xml ta informace je. A velmi špatně se do xml přidává rozsah vydávání start/end. Proto bych uvítala, aby to bylo i ve formuláři.

**Comment by tumovam** [comment]
Nooo, ono je to složitější. Tím, že naši zpracovatelé stahují záznam z katalogu, tak se do xml propisují i údaje, které podle standardu nejsou povinné. Vím, že roky vydání nejsou ve standardu, ale @SykoraLukas, nemohl bys, prosím, rozšířit OriginInfo nad rámec NDK standardu s povinností O? 
OriginInfo:
Place - PlaceTerm - O
Publisher - MA
DateIssued - encoding - point - qualifier - O
Edition - MA

Určitě to vůbec nespěchá, máme issues, která jsou urgentnější... Díky

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) připraveno. Děkujeme! 🥇 Jen ještě.. ehm... kosmetická úprava místo O, tam máš 0 [nula]. Ale do xml nebo jinam se to snad nepřetahuje, ne? Takže to je opravdu jen detail...

**Comment by tumovam** [comment]
Zkoušela jsem u NDK Vícedílky, můžete to @nezbedova prosím otestovat i v v STT, děkuji

**Comment by SykoraLukas** [comment]
Bude opraveno (0 na O).

**Comment by nezbedova** [comment]
Vyzkoušeno u STT. Děkuji.

**Comment by tumovam** [comment]
U NDK Vícedílky, ve verzi 3.6.2 jsou nuly opraveny na O a zbytek také OK :) Díky!
