### ISSUE TITLE
Možnost zastavení načítající se dávky

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1202]
Superadmin by měl mít možnost ve zcela vyjímečných případech zastavit načítání dávky.

**Comment by zabak** [comment]
Bylo by dobré, kdyby bylo možné načítání dávky jen pozastavit a pak ji znovu pustit (zapauzovat ji a zase odpauzovat). Souvisí i s https://github.com/proarc/proarc/issues/1358 - pokud by bylo možné pozastavit jednotlivé běžící importy, tak  by to řešilo náš problém možná ještě lépe. Naše motivace byla dosáhnout toho, aby bylo možné naimportovat něco přednostně, aby operátor nemusel čekat s importem několika stránek pokud běží nějaký rozsáhlý import.

**Comment by ZdenkaSera** [comment]
Funkce v importních procesech - ve fázi načítání lze zastavit a opětovně ručně spustit, přibydou statusy, které stav popíší a umožní filtrovat. Znovu spuštěná dávka se nenačítá od 0, ale již načtená část se využije.

**Comment by SykoraLukas** [comment]
Implementováno v novém klientovi

**Comment by ZdenkaSera** [comment]
Chyba viz https://github.com/proarc/proarc-client/issues/17

**Comment by ZdenkaSera** [comment]
Vzhledem k posledním výsledkům testů v klientovi navrhuji k uzavření.
