### ISSUE TITLE
Řazení titulů v úložišti - zaškrtávátko "zapamatovat" ve 3.6.1 nefunguje

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#1216]
Ve verzi 3.6.1 asi přestalo při hledání v úložišti fungovat zaškrtávátko "zapamatovat". Když zkusím změnit řazení vzestupně na sestupně ve verzi 3.6, volbu si po odhlášení pamatuje, ve 3.6.1 ale už ne.
V podstatě asi nechápu, proč vzestupně má tady přednost před sestupně (praktické využití vzestupného vidím jen u řazení podle abecedy při hledání podle názvu), většinou se ale myslím orientujeme podle data (vytvoření/změny), a tam má v 99% případů smysl sestupné řazení. Ale budiž, pokud si to bude pamatovat volbu. Jenže u verze 3.6.1 tohle asi vypadlo, pokud to teda není úmyslně. 
Můžeš se na to Lukáši prosím mrknout?

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) mi "Zapamatovat" funguje. Zůstává i po odhlášení a opětovném přihlášení.

**Comment by luckajirku** [comment]
no já si to z dovolením ještě zkusím, až ta verze bude venku...

**Comment by tumovam** [comment]
Ve verzi 3.6.2 funguje jen částečně. 
Příklad: Přihlásím se pod svým účtem, dám eČlánek, Sestupně a Zapamatovat. Poté se odhlásím a znovu přihlásím a je správně zapamatovaný eČlánek a řazení Sestupně 👍  
Když se ale odhlásím, přihlásím jako "Proarc" a dám Zapamatovat NDK Periodikum a Vzestupně. Pak odhlásím uživatele Proarc, přihlásím se pod svým vlastním účtem a tam je NDK Periodikum Vzestupně, ne eČlánek a Sestupně 👎 
Vypadá to, že uživatel Proarc "přebije" ostatní uživatele? Nebo si PA vždy pamatuje poslední zapamatovaná kritéria? Neplatí tedy, že "Zapamatovat" platí pro uživatele?

**Comment by SykoraLukas** [comment]
Tohle není závislé na uživateli ale na prohlížeči. Je jedno, jakou roli uživatel má, vždy se pamatuje posledně uložená přes všechny uživatel v daném prohlížeci a PC.
Příklad:
- uživatel ProArc si zapamatuje hledání NDK monografie, sestupně (vyhledá a poté se odhlásí).
- uživatel Test zobrazí hledání (předvybrané je NDK monografie, sestupně) - zůstává od uživatele Proarc. Uživatel Test nakliká NDK Periodikum, vzestupně a dá zapamatovat. (Vyhledá a odhlásí se).
- přihlásí se další uživatel, který vidí předvyplněno NDK Periodikum, vzestupně. A takto to pokracuje dal a dal

**Comment by ZdenkaSera** [comment]
Zdá se, že v souladu s popisem výše, si napříč přihlášení různými uživateli pamatuje co hledat, ale ne jak řadit (ve verzi 3.8-beta tvrdošíjně vrací "naposledy vytvořené" . Zatím ale dávám label k uzavření, navrhuji primárně řešit v novém klientovi.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
