### ISSUE TITLE
test v. 3.6.1 - chybí tlačítko Administrace

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1219]
V Úložiště- Hledat není tlačítko Administrace. Nemohu si převést stranu na NDK stranu a vyzkoušet editaci typu stran viz #1170

**Comment by tumovam** [comment]
@nezbedova prosím jakou máte roli? Vy jste Super Admin?

**Comment by psenickam** [comment]
za me v poradku, bude to pridelenou roli

**Comment by nezbedova** [comment]
Mám roli Admin. Děkuji a zavírám.

**Comment by psenickam** [comment]
beru zpet, ani u superadmina neni. omlouvam se za nedorozumeni. prosim znovuotevrit issue

**Comment by tumovam** [comment]
Administrace (tím myslím Převod strana na NDK stranu, obr. z ostré v3.6:  
![obrazek](https://user-images.githubusercontent.com/31240271/96714453-75fbd480-13a2-11eb-9773-615557188f26.png))

jsem vždy používala jen po přihlášení uživatele Proarc. Nyní jsem nově Super Admin a tuto fci nevidím... Není spíš problém s udělováním rolí?

**Comment by luckajirku** [comment]
ozkoušela jsem to u nás, jako super admin tam tu administraci mám, jako admin ne.

**Comment by SykoraLukas** [comment]
Chyba opravena, objevovala se jen u některých useru.

**Comment by tumovam** [comment]
@SykoraLukas a bude to tedy u Super Admina nebo i Admina? Díky

**Comment by SykoraLukas** [comment]
Tlačítko Administrace je nyni pro SuperAdmina, má ho povolit i pro Admina?

**Comment by tumovam** [comment]
Ne, podle mě stačí u Super Admina. Převod Stran na NDK Strany u nás dělají jen vybraní jedinci.

**Comment by SykoraLukas** [comment]
Zatím nechávám u SuperAdmina, případně v budoucnu upravíme v novem issue.

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) jako Administraci vidím. Mám roli Super Admin

**Comment by nezbedova** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) Administraci vidím. Teď mám roli Super Admin.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
