### ISSUE TITLE
Test v. 3.6.1 dlouhý název souboru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1220]
Do Import - Příprava metadat se načte název souboru s celou cestou. Nevím, zda to je chyba nebo nová vlastnost.

**Comment by SykoraLukas** [comment]
Jde o chybu, ale můžeme to udělat konfigurovatelné, defaultně by byl jen název souboru, ale šlo by to přepnout na kompletní cestu.

**Comment by SykoraLukas** [comment]
Převedeno na konfigurovatelnou možnost. Defaulně se zobrazuje pouze název souboru, po zmeně [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#import) se zobrazuje celá cesta k souboru

**Comment by nezbedova** [comment]
Opraveno. Děkuji. Zavírám.
