### ISSUE TITLE
Test v. 3.6.1 - nelze stahovat z SKC

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1221]
V testovací verzi nefunguje stahování z SKC. Nejspíš to bude jen nastavením, ale raději bych to otestovala komplet.

**Comment by SykoraLukas** [comment]
Katalog SKC je část X Serveru Aleophu NK?

**Comment by nezbedova** [comment]
Nevím. Možná bude vědět. @tumovam nebo p. Kotýnek

**Comment by tumovam** [comment]
Ano, myslím, že to je část X Serveru. Nesouvisí to zase s tím, že X Server Alephu NKP byl omezený/povolený pouze pro vybrané IP adresy?

**Comment by PetrKotynek** [comment]
Ano,
je to stejné jako před časem,  je tam zmena IP adresy a protější strana odpovídá:
<html>
<head>
<title>Error 403</title>
</head>
<body>
<h1>Error 403 Forbidden</h1>
Access from IP address <i>147....</i> not allowed.

Petr Kotýnek

**Comment by nezbedova** [comment]
Stahovat mohu. V. 3.6.4
