### ISSUE TITLE
Problém s vyhledáváním nově vytvořeného objektu

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1225]
Když přes Nový objekt vytvořím NDK Svazek monografie, tak tento nově vzniklý objekt nelze vyhledat. Resp. najde se jen někdy🙂 

Postup, který funguje: _Naposledy vytvořené_ a hledaný model ✅ 
Postup, který funguje: _Naposledy editované_ a hledaný model ✅ 
Postup, který funguje: _Dotaz_ a zadání názvu titulu (svazku) ✅
Postup, který nefunguje: _Rozšířený dotaz_ a zadání názvu titulu (svazku) a ještě vyberu **model NDK Svazek monografie** ⛔
Postup, který funguje: _Rozšířený dotaz_ a zadání názvu titulu (svazku), ale zvolím **model "Vyhovuje vše"**, tak se svazek najde ✅   
Postup, který nefunguje: _Rozšířený dotaz_ a zadání identifikátoru (uuid svazku) a ještě vyberu **model NDK Svazek monografie** ⛔
Postup, který funguje: _Rozšířený dotaz_ a zadání identifikátoru (uuid svazku), ale zvolím **model "Vyhovuje vše"**, tak se svazek najde ✅ 

To samé platí pro model NDK Periodikum (zatím jsem zkoušela jen tyto dva modely).

**Comment by SykoraLukas** [comment]
Tohle se mi nedaří nasimulovat, mohla bys mi to prosím ukázat na nějakých příkladech na testovacím proarcu? Díky

**Comment by tumovam** [comment]
Myslíš klienta (proarc.inovatica)? Tohle se mi stalo, když jsem testovala v "'jádře", ale i klientovi KNAV, na nově nasazené v3.6.1.

**Comment by SykoraLukas** [comment]
Stačí v jadře na proarc.inovatika.dev/api/. Nemám se od čeho chytit totiž. U mě mi fungují všechny postupy, jak jsi napsala výš a do KNAV na test se nedostanu, tak proto tu ukazku na testovacim proar.inovatika. Děkuju

**Comment by tumovam** [comment]
OK, na _PA.ica.dev/api/_ jsem před minutou vytvořila časopis Kontadikce. Když dám Rozšířený dotaz, název periodika a omezím na model "NDK Periodikum", tak se nic nenajde: 
![obrazek](https://user-images.githubusercontent.com/31240271/96845389-f11bc400-1450-11eb-9784-1cfbe0b3f074.png)

Ale bez omezení modelu = Vyhovuje vše se zobrazí hledané periodikum:

![obrazek](https://user-images.githubusercontent.com/31240271/96845566-1c061800-1451-11eb-863d-214a025ebd1a.png)

**Comment by SykoraLukas** [comment]
Ok dík

**Comment by tumovam** [comment]
A to samé, pokud v Rozšířeném vyhl. zadám uuid:83c68faa-9e1c-4875-aa1c-97d60de679f0 (= ten nově vyt. časopis) do pole Identifikátor. 
Když to omezím na model NDK Periodikum, tak žádný výsledek ⛔ 
Když ale neomezím model, ale dám "Vyhovuje vše", tak PA, to periodikum s tím hledaným uuid:83c68faa-9e1c-4875-aa1c-97d60de679f0, najde ✅

**Comment by SykoraLukas** [comment]
Tak jsem právě pochopil, proč proarc tvořil tak nelogicke 2x dc:type. Jednou to mělo hodnotu model:ndkMonographVolume a podruhe model:monograph. 

Hodnota model:monograph se používala kvůli standardu.
Hodnota model:ndkMonographVolume se využívala pro rozšířeném hledání. Tím, že jsem nechali pouze hodnotu dle standardu (model:monograph) tak nejde hledat v rozšířením vyhledávání. 

Budu pracovat na opravě.

**Comment by tumovam** [comment]
V tom případě nám ty dvě (téměř stejné) hodnoty v DC (https://github.com/proarc/proarc/issues/1187) zase tak moc nevadily :))

**Comment by tumovam** [comment]
Ve 3.7-SNAPSHOT (z 23.10.2020) chyba přetrvává.

**Comment by SykoraLukas** [comment]
Moje chyba, udělal jsem opravu, ale zapomnel jsem ji priradit mezi veci, ze kterych se ma delat verze. Opravim.

**Comment by tumovam** [comment]
V PA v3.6.2 lze nově vyt. objekt najít ;) Díky!

**Comment by SykoraLukas** [comment]
Uzavírám, na základě otestování.
