### ISSUE TITLE
RDflow - přidání  xml pro periodika na Wiki

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1238]
Prosím o přidání ukázkového xml pro periodika, které bude obsahovat záměr a podzáměr podle #491.

**Comment by SykoraLukas** [comment]
Do [Workflow wiki](https://github.com/proarc/proarc/wiki/Popis-workflow.xml#cel%C3%A9-uk%C3%A1zkov%C3%A9-xml) byla nahrána ukázka workflow job pro periodikum a ročník periodika. Propojení na subjob je nutné definovat těsně před zavírající element </job>.
