### ISSUE TITLE
RDflow - přidání tlačítka Záměry a dalších

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1240]
Do stávající nebo nové lišty přidat tlačítka pro rychlou orientaci.

![obrazek](https://user-images.githubusercontent.com/13831946/99792619-a52f6e00-2b27-11eb-957c-cdb56c09a482.png)

U nás nejvíce využijeme tři tlačítka, která jsou na obrázku. 
Ostatní uživatele prosím o komentáře, zda by jim to takto vyhovovalo nebo by ještě něco přidali.

**Comment by luckajirku** [comment]
Za nás OK, jen další novou lištu bych kvůli tomu nedělala, pokud je možné dát to do té stávající horní...

**Comment by SykoraLukas** [comment]
Tlačítka mají být až takto na konci nebo spíš mezi tlačítkem Menu a Jazykem? Z logiky většiny aplikací mi připadá lepší to dát hned vedle menu, ať jsou u sebe věci pro práci (Menu, Historie, Hledat, Záměry), a teprve poté věci k nastavení jazyku a informace o přihlášeném uživateli.

Určitě bych to doporučil dát do jedné lišty. Co myslíte? Šlo by to takhle?
![image](https://user-images.githubusercontent.com/27210823/99962780-14f46180-2d91-11eb-9a69-635592d7f3cf.png)

**Comment by nezbedova** [comment]
Hotovo.
