### ISSUE TITLE
premis:formatVersion u TIFFu

### ISSUE THREAD

**Issue by mhalva** [proarc/proarc#1247]
Ve vedlejších mets souborech se nám vyskytuje nesoulad (dvě různé hodnoty) v údajích o verzi formátu TIFF pro původní sken. Zatímco v MIX_001 je uvedeno `<mix:formatVersion>5.0</mix:formatVersion>,` tak v OBJ_001 je nesmyslná hodnota `<premis:formatVersion>1.0</premis:formatVersion>.` Obě hodnoty by měly být stejné, správně je ta první (5.0).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím, podíval by ses na tohle? Není prio1, ale opravdu je k řešení. Díky.

**Comment by kerschfilip** [comment]
ve verzi 4.0.3 je to OK, díky

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
