### ISSUE TITLE
RDFlow - 3x Part Number

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1254]
Při vytváření PodZáměru je ve formuláři 3 x pod sebou Part Number... je to schválně? Má to důvod?

**Comment by SykoraLukas** [comment]
Můžete mi poslat ukáyku obrazovky? Kterého modelu se to týká?

**Comment by SmejkalovaAnna** [comment]
U Ročník periodika
![obrazek](https://user-images.githubusercontent.com/24409660/101880927-fa452980-3b93-11eb-82c6-5798a5c2ec37.png)

**Comment by SykoraLukas** [comment]
Můžete mi prosím ještě vykopírovat xml záznam tohoto objektu?

**Comment by SmejkalovaAnna** [comment]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:classification authority="udc">930.85(495)"395/1453"</mods:classification>
    <mods:classification authority="udc">80(=16)+908(4)</mods:classification>
    <mods:classification authority="udc">316.72/.75</mods:classification>
    <mods:classification authority="udc">93/94</mods:classification>
    <mods:classification authority="udc">80</mods:classification>
    <mods:classification authority="udc">811.14</mods:classification>
    <mods:classification authority="udc">811.124</mods:classification>
    <mods:classification authority="udc">(495)</mods:classification>
    <mods:classification authority="udc">(051)-027.561</mods:classification>
    <mods:classification authority="udc">(082)</mods:classification>
    <mods:classification authority="Konspekt">8</mods:classification>
    <mods:classification edition="Konspekt" authority="udc">930.85</mods:classification>
    <mods:genre>volume</mods:genre>
    <mods:genre>title</mods:genre>
    <mods:genre authority="czenas">odborné časopisy</mods:genre>
    <mods:genre authority="czenas">sborníky</mods:genre>
    <mods:genre authority="eczenas">professional journals</mods:genre>
    <mods:genre authority="eczenas">miscellanea</mods:genre>
    <mods:identifier type="uuid">90fad0c2-9756-4a65-b661-71d24b096dad</mods:identifier>
    <mods:identifier type="ccnb">cnb000390245</mods:identifier>
    <mods:identifier type="issn">0007-7712</mods:identifier>
    <mods:identifier type="issn-l">0007-7712</mods:identifier>
    <mods:identifier type="barcode">26005412994</mods:identifier>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">cze</mods:languageTerm>
    </mods:language>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">eng</mods:languageTerm>
    </mods:language>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">fre</mods:languageTerm>
    </mods:language>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">ger</mods:languageTerm>
    </mods:language>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">rus</mods:languageTerm>
    </mods:language>
    <mods:location>
        <mods:physicalLocation authority="siglaADR">ABA007</mods:physicalLocation>
        <mods:shelfLocator>PE 2911</mods:shelfLocator>
        <mods:shelfLocator>B 316</mods:shelfLocator>
        <mods:shelfLocator>S-N 553</mods:shelfLocator>
        <mods:url displayLabel="Informace o časopisu">http://www.slu.cas.cz/4.html#byzantinoslavica</mods:url>
    </mods:location>
    <mods:name type="corporate">
        <mods:namePart>Slovanský ústav (Akademie věd ČR)</mods:namePart>
    </mods:name>
    <mods:note type="date/sequential designation">Roč. 1, č. 1 (1929)-roč. 60, č. 2 (1999); roč. 61, č. 1 (2003)-</mods:note>
    <mods:note>Od r. 1953 t. 14. podnázev: Revue internationale des études byzantines</mods:note>
    <mods:note>Od r. 1953 Praha : ČSAV (Slovanský ústav ČSAV)</mods:note>
    <mods:note>Od r. 1966 Prague : Academia (Ústav dějin evropských soc. zemí ČSAV)</mods:note>
    <mods:note>Změny názvu vydav.: od r. 1969 Úst. dějin východní Evropy; od r. 1970 Kabinet pro studia řecká římská a latinská ČSAV; od r. 1991 Inst. des études classiques; od r. 1992 Inst. slave</mods:note>
    <mods:note>Od r. 1993 Praha : Euroslavica (Slovanský úst.)</mods:note>
    <mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xr</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Praha</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Praha</mods:placeTerm>
        </mods:place>
        <mods:publisher>Byzantologická komise při Slovanském ústavě</mods:publisher>
        <mods:publisher>Slovanský ústav</mods:publisher>
        <mods:publisher>Euroslavica.</mods:publisher>
        <mods:dateIssued>[1929-]</mods:dateIssued>
        <mods:dateIssued encoding="marc" point="start">1929</mods:dateIssued>
        <mods:dateIssued encoding="marc" point="end">9999</mods:dateIssued>
        <mods:issuance>continuing</mods:issuance>
        <mods:frequency>1x ročně</mods:frequency>
        <mods:frequency authority="marcfrequency">Annual</mods:frequency>
    </mods:originInfo>
    <mods:physicalDescription>
        <mods:form authority="marcform">print</mods:form>
    </mods:physicalDescription>
    <mods:recordInfo>
        <mods:recordContentSource authority="marcorg">ABA007</mods:recordContentSource>
        <mods:recordCreationDate encoding="iso8601">20201211T091612</mods:recordCreationDate>
        <mods:recordChangeDate encoding="iso8601">20201211T093227</mods:recordChangeDate>
        <mods:recordIdentifier source="CZ PrAS">000594029</mods:recordIdentifier>
        <mods:recordOrigin>machine generated</mods:recordOrigin>
        <mods:descriptionStandard>aacr</mods:descriptionStandard>
        <mods:recordInfoNote>Converted from MARCXML to MODS version 3.6 using MARC21slim2MODS3.xsl
                (Revision 1.98 2018/02/09, ProArc patch 16.884 2019/02/10)</mods:recordInfoNote>
    </mods:recordInfo>
    <mods:subject authority="Konspekt">
        <mods:topic>Dějiny civilizace. Kulturní dějiny</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>byzantologie</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>slavistika</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>kulturní vztahy</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>dějiny</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>filologie</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>řečtina</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:topic>latina</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>Byzantine studies</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>Slavic studies</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>cultural relations</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>history</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>philology</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>Greek language</mods:topic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:topic>Latin language</mods:topic>
    </mods:subject>
    <mods:subject authority="czenas">
        <mods:geographic>Byzanc</mods:geographic>
    </mods:subject>
    <mods:subject authority="eczenas">
        <mods:geographic>Byzantine Empire</mods:geographic>
    </mods:subject>
    <mods:titleInfo>
        <mods:title>Byzantinoslavica</mods:title>
        <mods:subTitle>sborník pro studium byzantsko-slovanských vztahů</mods:subTitle>
        <mods:partNumber>14</mods:partNumber>
    </mods:titleInfo>
    <mods:titleInfo type="alternative">
        <mods:title>Byzantinoslavica</mods:title>
        <mods:subTitle>revue internationale des études byzantines</mods:subTitle>
        <mods:partNumber>14</mods:partNumber>
    </mods:titleInfo>
    <mods:titleInfo type="alternative" displayLabel="LXXVI, 2018, supplementum 3:">
        <mods:title>Homage to Francis Dvorník</mods:title>
        <mods:partNumber>14</mods:partNumber>
    </mods:titleInfo>
    <mods:typeOfResource>text</mods:typeOfResource>
</mods:mods>

**Comment by SmejkalovaAnna** [comment]
Ten formulář je ale vůbec nějaký špatný, při vytvoření z PodZáměru se tam vykopíruje Date issued začátek a konec, tam by měl být jen jedno datum, datum ročníku. Nějak se to špatně asi stahuje, ten formulář pro ročník by měl vypadat podlě mě jinak.... resp. vypadá jinak, než když ho vytvořím ve vazbách.... měl by být podlě mne stejný.....

**Comment by SykoraLukas** [comment]
ano, vypadá to na chybně zapsaný záznam. Důvodem, proč tam jsou 3x partNumber je fakt, žev xml je 3x partNumber. Proto se to tam nakopíruje 3x. Bere to počet elementů, které to nalezlo v xml.

POkud tam dáte záznam, který bude lepe popsán jen s jedním partNumber, bude i ve formuláři pouze jeden element.

**Comment by SmejkalovaAnna** [comment]
Je tam i 3x žánr, každopádně, ten formulář by měl vypadat podle mě stejně, jako když dám vytvořit Ročník ve Vazbách, nebo jste se dohodli Martino @nezbedova jinak? Když se z Podzáměru pak automaticky vytvoří Objekt, tak by to mělo být stejné....?

**Comment by SykoraLukas** [comment]
formulář odpovídá datům které jsou v xml. Pokud tam bude vše pouze jednou, bude pak formulář stejný, jako ten v "Proarcu". A naopak, pokud bude v "Proarcu" objekt, který bude mít 3x genre a 3x partNumber, bude vypadat takto.

**Comment by SmejkalovaAnna** [comment]
Můžete to prosím udělat tak, aby se ten záznam k ročníku ( při vytváření podzáměru ) nekopíroval z dat titulu?  Ale chtěli bychom, aby se vytvořil prázdný formulář, jako je to ve vazbách.
Můžete to upravit? Díky.

**Comment by SykoraLukas** [comment]
Určitě to takhle chcete? Nejde jen o kopírování titul-ročník, ale i o kopírování dat do jakéhokoli podzáměru.

**Comment by SykoraLukas** [comment]
Prosím o případné schválení od @nezbedova.

**Comment by SmejkalovaAnna** [comment]
@nezbedova tam jde i o ty vícedílky viď? @SykoraLukas  Lukáši a nejde to udělat jen pro periodika ten podzáměr?

**Comment by SykoraLukas** [comment]
Tohle bohužel nejde. Buďto to jde pro všechny nebo pro žádné.

**Comment by SmejkalovaAnna** [comment]
Já bych obětovala stažení záznamu vícedílek, resp. dílky coby podzáměr, protože nahoře ve formluláři je pod tlačítkem katalog, takže bych se ty záznamy daly pro díly stáhnout dodatečně do toho prázdného fomluláře..... ale uvidíme, co na to Martina @nezbedova

**Comment by nezbedova** [comment]
@SmejkalovaAnna chápu oto správně tak, že by se ze záměru periodikum/vícedílka  nic nekopírovalo do podzáměru? Nový podzáměr by se založil prázdný nebo by se založil stažením z katalogu?

**Comment by SykoraLukas** [comment]
Založil by se prázdný a poté by se do něj mohla stáhnout data pomocí katalogu.

**Comment by SmejkalovaAnna** [comment]
Přesně tak, otevřel by se prázdný formulář a nahoře se kleplo na Metadada a vybralo by se z Katalogu....

**Comment by nezbedova** [comment]
S tím souhlasím. Když jsem to testovala já, u vícedílek jsem také měla problémy. Tohle by to mohlo vyřešit.

**Comment by SykoraLukas** [comment]
OK, ruším tedy kopírování metadat.

**Comment by SmejkalovaAnna** [comment]
Díky. Snad to bude fungovat dobře doufejme....

**Comment by SykoraLukas** [comment]
Ještě s tím související, když smažeme záznam, tak i políčka v v bibliografickém záznamu budou prázdná, dokud se nestáhne a neuloží nový záznam. OK?

![image](https://user-images.githubusercontent.com/27210823/101906669-9e8d9700-3bb9-11eb-927e-2f9727f1b2bb.png)

**Comment by nezbedova** [comment]
Ano. Ale musí tam ten prázdný formulář být.

**Comment by nezbedova** [comment]
Založení prázdného záměru, který se naplní pomocí katalogu funguje.
