### ISSUE TITLE
RDFlow - počet indexů nebo foxml exportu

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1259]
V rámci automatizace  se po proběhnutí Exportu pro Kramerius a Archivace dokončí příslušný úkol. Bylo by možné, aby PA při Exportu pro Kramerius spočítal foxml a zapsal tento počet do úkolu? Nebo když při Archivaci validuje index, zapsal počet indexů do úkolu? 
Potřebovali bychom vědět, kolik skenů se exportovalo ven. Stačilo by nám jedno číslo.V případě foxml si odečteme to na titul.

**Comment by SykoraLukas** [comment]
Tohle by asi šlo udělat, ale je potřeba přesně definovat nazev parametru, do ktereho se to ma zapisovat. Pokud by se změnil nazev tohoto parametru v definici workflow, tak se to nema kam zapsat.

**Comment by nezbedova** [comment]
Idealně tam, kam se automaticky zapisuje Import pro Kramerius. To je "task.exportK4". Parametr -  param.exportK4 - Number

**Comment by nezbedova** [comment]
Vypadá to, že se nenahrávají jen balíčky "Inge"

**Comment by nezbedova** [comment]
archive_8df7ac6a-fe82-4f4b-89a2-b6d1c4d9d59f - je ročník periodika. Sice se při nahrání objevila "neočekávaná chyba". ale ročník se nahrál. Tou chybou mohla být nepřítomnost nadřazeného objektu.
Mám vyzkoušet další ročník a dát sem chybu?

**Comment by SykoraLukas** [comment]
Radši ano, ať potvrdíme, že problémem byl neexistující nadřazený objekt.

**Comment by nezbedova** [comment]
archive_33b40cc4-9682-4176-a6cb-45cb9fab9222 ročník - hláška o chybě se neobjevila. Ročník se načetl.

**Comment by nezbedova** [comment]
Překopírovala jsem špatně zapsané komentáře, které patří do #1188 . Tady jsem je smazala.

**Comment by nezbedova** [comment]
Protože jiné instituce by mohly chtít sledovat počty skenů/obrázků, které se v PA zpracovaly a exportují se z něj ven, bylo by dobré automatický zápis počtu rozšířit i na ostatní exporty.

Za DC to bude:


Úkol | Parametr
-- | --
task.exportArchive | param.exportArchive
task.exportK4 | param.exportK4
task.exportNdkPsp | param.exportNdkPsp.numberOfPackages



A ještě čekám na vyjádření OZC ohledně CEJSH a Crossref.

**Comment by nezbedova** [comment]
OZC nepožaduje rozšíření. Prosím tedy jen počty k taskům v tabulce. Děkuji.

**Comment by nezbedova** [comment]
U nově založeného záměru funguje zapisování počtu foxml do úkolu Export pro Krameria. Archive nemohu vyzkoušet.

**Comment by nezbedova** [comment]
Funguje u exportu do Krameria i u exportu archive balíčku.
Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
