### ISSUE TITLE
Funkce pro opravu NDK článků

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1260]
V návaznosti na #1098 

U nově vytvořených NDK Článků je vše v pořádku, ale co budeme dělat s dříve vytvořenými? V PA máme x tisíc (ehm...) NDK článků, u nichž máme PageNumber a PageIndex v jednom Partu. A podle standardu to máme mít 2 Party. @SykoraLukas, nešla by naprogramovat zase nějaká vychytávka (obdobná tomu, co máme na převod Stran na NDK Strany)? Děkuju, M.

**Comment by SykoraLukas** [comment]
Funkce obsahovala chybu, opraveno od verze 3.6.4

**Comment by tumovam** [comment]
Chtěla jsem otestovat ve v3.6.3, ale tuto fci zde nevidím (a ano, opravdu jsem v testovacím PA v.3.6.3 :)). Měla by být v "Administraci" jako Převod na NDK strany? 
![obrazek](https://user-images.githubusercontent.com/31240271/109168601-49582f00-777f-11eb-9126-73b49f09f1ea.png)
Děkuji, MH

**Comment by SykoraLukas** [comment]
Opraveno, bude v nové verzi.

**Comment by tumovam** [comment]
Ve verzi 3.6.4-preview už je i možnost Update NDK článků. S případnými nesrovnalostmi se ozvu. Dííík, M.

**Comment by tumovam** [comment]
Ve v3.6.5 funguje, navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.

**Comment by tumovam** [comment]
Update NDK článků funguje i ve v3.6.7
