### ISSUE TITLE
STT - nový typ strany Rukopisná poznámka

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1263]
Přidat typ strany "Rukopisná poznámka"

**Comment by SykoraLukas** [comment]
Můžu poprosit o anglicky překlad k této hodnotě?

**Comment by nezbedova** [comment]
Dodám.

**Comment by honza-rychtar** [comment]
Důležitá je hlavně shoda na kódu typu. Ten pak budou všechny systémy používat pro navázání lokalizovaného názvu a případně pro odlišnou logiku při určitých procesech (např. parametry pro OCR).

**Comment by nezbedova** [comment]
Po konzultaci s knihovědným oddělením navrhuji anglický název "manuscript notes"
A kód "ManuscriptNotes". Ale netrváme na tom. Pokud má někdo jiný návrh, sem s ním.

**Comment by nezbedova** [comment]
Typ strany je přidaný. V Krameriovi se zobrazuje špatně.

**Comment by honza-rychtar** [comment]
Přidal jsem nový typ strany do klienta Krameria. Bude v příští verzi.

**Comment by SykoraLukas** [comment]
Jen doplňuji, že kód nového typu je "manuscriptNotes". Aby byla zachována jmenná konvence s ostatními kódy stran.

**Comment by nezbedova** [comment]
V test Krameriovi new client v2.0.5 se zobrazuje rukopisná poznámka správně.

**Comment by nezbedova** [comment]
Tento typ strany se někam ztratil. Prosím znovu přidat. Děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
