### ISSUE TITLE
RDflow - nelze stáhnout záznam z katalogu u Podzáměrů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1264]
Při zakládání podzáměrů u vícedílky nebo Periodika nelze založit podzáměr stažením z katalogu, jen prázdný.
Chyba začíná:
![obrazek](https://user-images.githubusercontent.com/13831946/102471996-1fcfa880-4056-11eb-927e-b4cdb59807c7.png)

**Comment by nezbedova** [comment]
Záznam se dá z katalogu vyhledat. Ale další možnost je pouze Uložit. Záznam se uloží, ale my potřebujeme, aby se zobrazil ve formuláři, který opravíme a pak až ho uložíme.

**Comment by nezbedova** [comment]
Chybí tlačítko "Vytvořit nový záměr", které by přepnulo do formuláře.

**Comment by tumovam** [comment]
Je potřeba ručně "přepnout" do formuláře.

**Comment by nezbedova** [comment]
Otestováno. Funguje.
