### ISSUE TITLE
NDK Monografie - zdvojené údaje v Origin Info

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1266]
Při stahování záznamu Monografie se nám špatně zapisují nakladatelské údaje do Origin Info.

<mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xxu</mods:placeTerm>
        </mods:place>
        <mods:dateIssued encoding="marc">2018</mods:dateIssued>
        <mods:edition>Second edition</mods:edition>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>
    <mods:originInfo eventType="publication">
        <mods:place>
            <mods:placeTerm type="text">Chicago</mods:placeTerm>
        </mods:place>
        <mods:publisher>University of Chicago Press</mods:publisher>
        <mods:dateIssued>2018</mods:dateIssued>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>

Ideální by bylo:

<mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xxu</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Chicago</mods:placeTerm>
        </mods:place>
        <mods:publisher>University of Chicago Press</mods:publisher>
        <mods:dateIssued encoding="marc">2018</mods:dateIssued>
        <mods:edition>Second edition</mods:edition>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>

Myslím, že už jsme to řešili, ale nenašla jsem issue. 

Děkuji, M. H.

**Comment by luckajirku** [comment]
trochu s tím asi souvisí tohle, i když se týká periodik - tam je totiž naopak násobné origininfo žádoucí: https://github.com/proarc/proarc/issues/739

**Comment by tumovam** [comment]
Možná jsem to v úvodu špatně napsala, ale i my chceme, aby se pro každého nakladatele vytvořit samostatný OrigiInfo.

Další příklad. Když např. stáhnu záznam "Úvod do etiky" - ISBN 80-7192-698-1 (Karmelitánské nakladatelství) a 80-200-0953-1 (Academia), tak se mi do PA do jednoho elementu OriginInfo pod sebe stáhnou 2 místa vydání (Praha, Kostelní Vydří) a 2 nakladatelé (Academie a Karmelitánské nakladatelství). V Krameriovi se poté zobrazují pouze pouze 1 místo vydání a 1 nakladatel. MZK snad promine, že používám jejich příklad: https://dnnt.mzk.cz/uuid/uuid:82c951a0-f614-11e7-a97b-005056827e51 . Zobrazení ISBN je věc další, to je věc Krameria... 
v MARC v 260 je to: 1. vyd. |a Praha : |b Academia ; 2. vyd. |a Kostelní Vydří : |b Karmelitánské nakladatelství

Nooo ale když pro každého nakladatele vytvořím samostatný OriginInfo, tak se zobrazují 2 nakladatelé, např. zde: https://kramerius.lib.cas.cz/uuid/uuid:e85fff98-b39f-4fd0-88a9-32c11443af28 
A v MARC ve 264 je to: 1. vyd.: 264 |a Beverly, MA : |b Scrivener Publishing ; 2. vyd.: |a Hoboken, NJ : |b Wiley, |c 2019

**Comment by ZdenkaSera** [comment]
Řešit společně s issue:
[#739](https://github.com/proarc/proarc/issues/739)
[#1267](https://github.com/proarc/proarc/issues/1267)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Jak jsem slíbila, přikládám soubor s příklady, jak se chová v předběžné verzi úprava originInfo u NDK svazku monografie. Všechny příklady se váží k záznamům v RDA
[originInfo.docx](https://github.com/proarc/proarc/files/7905210/originInfo.docx)
.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Otestovala jsem znovu na Inovatice v rámci testů nového klienta, objekty založeny 12.5., Prosím, ještě na to koukněte - obecně jsem narazila na to, že pokud se vytváří více elementů otigininfo, "issuance" se doplní jen k prvnímu a u druhého (měla jsem zatímjen data se 2 originfo) se k dateissued dotahuje neočekávaná hodnota encoding (ta ale v xml není při testu v jádře v 3.8-beta u nás). Obrázek níže.

- 1f056d30-449d-4211-adc5-3713e87f257a - tady navíc u druhého chybí místo 
![image](https://user-images.githubusercontent.com/79305516/168244484-9a24bb20-eb94-4ec4-a3ae-6a4c8989c355.png)

![image](https://user-images.githubusercontent.com/79305516/168244201-b9a64aea-2f9e-4299-a1a0-4bd08e818ff5.png)

Totéž v KNAV:
![image](https://user-images.githubusercontent.com/79305516/168246223-b31cc804-5202-414e-97c5-bf2ccbb7b369.png)

**Comment by ZdenkaSera** [comment]
Pokud jsou dvě různá místa, chybí jen issuance a přebývá encoding "w3cdtf"
- uuid: 756600c7-bf0a-4ce7-8384-aecc9b79038b
![image](https://user-images.githubusercontent.com/79305516/168246848-f53e4603-10eb-4ce1-9781-5c8a215ca018.png)


![image](https://user-images.githubusercontent.com/79305516/168246730-908499d1-b787-4fcd-90d3-ea8f707b8721.png)

**Comment by ZdenkaSera** [comment]
Pokud origininfo duplikuje jen uvedené vydání a místo/nakladatel/rok jsou jednoznační, to zatím nefunguje, ke sloučení do jednoho elementu nedochází
![image](https://user-images.githubusercontent.com/79305516/168248076-5b1b8f09-d609-4cf9-a2d4-183b03eb7368.png)
- uuid: d56fcbf5-6dc5-4bbf-9c5d-48f1cf0d848c
- 
![image](https://user-images.githubusercontent.com/79305516/168248543-cb681161-2453-4314-81d3-f44e3137625f.png)

-

**Comment by SykoraLukas** [comment]
Moc se neorientuji v popisu chyb. Mohu poprosit o čísla záznamů jak jsou stahována, do jaké podoby se stáhonut a jak by to správně mělo vypadat?

Udělám to pak podle toho, jak to má vypadat.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle jsem přehlédla, dodám.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zkusím to shrnout, níže pak jsou 4 příklady z katalogu KNAV, na kterých lze vyzkoušet. 

- pokud je v poli 260 (aacr) nebo 264 (rda) více míst vydání a/nebo nakladatelů, mělo by pro každou kombinaci vzniknout samostatné origininfo; podpole, které se neopakuje, přebere se do všech origiinfo stejně
- údaje o vydání z pole 250 se přebírají do 1. originfo, tj. k prvnímu nakladateli
- ve specifickém případě, kdy je jen jedno místo vydání a nakladatel a má tedy vzniknout jen 1x originfo, přidají se údaje z pole 250 k němu (teď se to rozpadá do dvu origiinfo, jak ukazuje druhý z obrázků výše)
- pokud jde o RDA, musí každé origininfo obsahovat "issuance"


**002695932 (RDA)**
250 - |a 1. vydání 
264 - |a Brno :  |b Centrum pro studium demokracie a kultury ;  |a Praha :  |b Ústav pro studium totalitních režimů,  |c 2020

**002705702 (RDA)**
250 - |a 1. vydání 
264 - |a Brno :  |b Books & Pipes :  |b Masarykova univerzita,  |c 2021

**000036403 (AACR)**
250 - |a Vyd. v tomto překl. 3., v Aca 2. 
260 - |a Praha :  |b Academia ;  |a Kostelní Vydří :  |b Karmelitánské nakladatelství,  |c 2001

**002714840 (RDA)**
250 - |a První vydání 
264 - |a Brno :  |b Host,  |c 2021.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ještě k encoding u dateissued - to fungovalo v minulosti dobře (buď nic nebo marc v souladu se standardy). Takže jde jen o to převzít stejné, pokud je zapotřebí datum zkopírovat do více origininfo.
Díky!

**Comment by ZdenkaSera** [comment]
@SykoraLukas tak ještě jednou  a lépe - issuance  se týká i aacr, nejen rda. Jen jsem při testu zjistila, že se netvoří u všech zakládaných origininfo (to je ten první obrázek z testu výše) a tady jsem to pak napsala špatně. . Co ale je zapotřebí u rda záznamů je eventype :-),

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, bude tohle k testu? Tady jsme si nevyrobili milestone ke 30.6., ale tohle issue (spolu s https://github.com/proarc/proarc/issues/1267 by se hodilo. Děkuji.

**Comment by SykoraLukas** [comment]
> @SykoraLukas Prosím, bude tohle k testu? Tady jsme si nevyrobili milestone ke 30.6., ale tohle issue (spolu s #1267 by se hodilo. Děkuji.

Již je nasazeno. Chybí pouze label. Vyzkoušejte

**Comment by ZdenkaSera** [comment]
zatím nemáme protipříklad, dávám návrh na uzavřen

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.

**Comment by SykoraLukas** [comment]
Jaký je důvod ke znovuotevření? Nebo to byl jen omyl?

**Comment by ZdenkaSera** [comment]
Doplňuji sem dotaz na chybu v origininfo, i když nejde o zdvojené údaje.
Do PA inovatiky jsem stáhla z katalogu KNAV monografii sysno = 000908303, v PA pod uuid:9dabdca9-e8bf-4c64-adcf-957c46446c73.  
V origininfo je 2x místo Praha, první z nich by ale měl být kód země xr z pozic 15-17 pole 008. Tipovala jsem to na chybu v datech ale nevidím ji - prosím o zjištění příčiny. Děkuji.

![image](https://user-images.githubusercontent.com/79305516/195375222-0a3613f4-f61e-434c-965e-82fb6ea5a858.png)

**Comment by ZdenkaSera** [comment]
tahle část je ok, děkuji.

**Comment by ZdenkaSera** [comment]
Mám další příklad chyby z katalogu KNAV:

**sysno = 001044879 (RDA)** - na Inovactice uuid:8aad1636-03cb-4af9-ae1a-47331a8e222e
![image](https://user-images.githubusercontent.com/79305516/196156031-ae5a34fc-fdb1-473b-ab75-976134c92cab.png)

 dva nakladatelé nevedli k rozdělení origininfo
![image](https://user-images.githubusercontent.com/79305516/196156306-e0f567d6-f05c-419e-a92d-0b4c268a4d30.png)


Tohle je už dříve (viz výše) řešený případ, kdy to funguje ok.
**sysno = 002705702 (RDA)** - ok, na Inovatice jako uuid:23b4e812-6144-4ef2-9248-070c968f8fc6
![image](https://user-images.githubusercontent.com/79305516/196155384-afac1657-1d53-45d3-841b-2212c584c3d0.png)

**Comment by ZdenkaSera** [comment]
Chyba výše (sysno 001044879) je ok, díky. 
Mám jinou s rozsahem let: katalog KNAV, v3.9, sysno = 000938836 - založeno jako NDK monografie a jako vícedílka - v obou případech stejná chyba v origininfo
![image](https://user-images.githubusercontent.com/79305516/200311216-2b438ed2-0b5d-4d05-a24d-431b1445551f.png)

![image](https://user-images.githubusercontent.com/79305516/200311873-c8d08f10-f9a2-494a-a2c3-9be0f46f9e2a.png)

**Comment by SykoraLukas** [comment]
Ok opravím, tohle se nemá rozdělit.

**Comment by ZdenkaSera** [comment]
Funguje, díky :-)
