### ISSUE TITLE
NDK Monografie - problém s OriginInfo s více vydavateli a místy vydání

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1267]
Při stahování záznamů s více nakladateli a místy vydání, se špatně zapisují nakladatelské údaje do Origin Info.

Např.:
<mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xr-</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Praha</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Kostelní Vydří</mods:placeTerm>
        </mods:place>
        <mods:publisher>Academia</mods:publisher>
        <mods:publisher>Karmelitánské nakladatelství</mods:publisher>
        <mods:dateIssued>2001</mods:dateIssued>
        <mods:edition>Vyd. v tomto překl. 3., V nakl. Academia 2.</mods:edition>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>

Správně by mělo být rozděleno do dvou OriginInfo:

    <mods:originInfo>
        <mods:place>
            <mods:placeTerm authority="marccountry" type="code">xr-</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Praha</mods:placeTerm>
        </mods:place>
        <mods:publisher>Academia</mods:publisher>
        <mods:dateIssued>2001</mods:dateIssued>
        <mods:edition>Vyd. v tomto překl. 3., V nakl. Academia 2.</mods:edition>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>
    <mods:originInfo>
        <mods:place>
            <mods:placeTerm type="code">xr-</mods:placeTerm>
        </mods:place>
        <mods:place>
            <mods:placeTerm type="text">Kostelní Vydří</mods:placeTerm>
        </mods:place>
        <mods:publisher>Karmelitánské nakladatelství</mods:publisher>
        <mods:dateIssued>2001</mods:dateIssued>
        <mods:edition>Vyd. v tomto překl. 3., V nakl. Academia 2.</mods:edition>
        <mods:issuance>monographic</mods:issuance>
    </mods:originInfo>

Jako příklad použita monografie Úvod do etiky (čnb cnb001065885, https://aleph.nkp.cz/F/?func=direct&doc_number=004093058&local_base=SKC).

Dělá nám to problém i při zobrazení více nakladatelů v Krameriovi.

Souvisí s https://github.com/proarc/proarc/issues/739 = periodika

**Comment by nezbedova** [comment]
Zjistila jsem, že se to zdvojuje tam, kde je vyplněné pole Edition.

**Comment by ZdenkaSera** [comment]
Má se řešit společně s issue [#1266](https://github.com/proarc/proarc/issues/1266) ->> přidávám štítek "Rozšíření 2021".

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
