### ISSUE TITLE
RDflow - automatické dokončení úkolu Smazat z PA

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1269]
Po smazání titulu ( uuid) automaticky dokončit úkol "Smazání z  ProArcu" (nyní se to jmenuje "Smazání z ostrého ProArcu", až budu dělat další opravy/úpravy, tak to změním). Co zůstává, je stále stejný název tasku. Prosím připojit na "task.deletionPA". Param u toho není žádný.

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by SykoraLukas** [comment]
Uzavírám, na základě otestování.
