### ISSUE TITLE
NDK eMonografie - signatura a číslo národní autority

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1273]
Prosím do formuláře přidat:

k < name > **< nameIdentifier >** - RA, tento údaje se z katalogu stáhne, ale když v katalogu chybí, zpracovatel by musel doplňovat v XML, což není správně... 
k < location > **< shelfLocator >** - RA, tento údaj se nikam nestahuje, i když v katalogu je a podle standardu _"signatura nebo lokační údajeo daném konkrétnímdokumentu v případě, že má dokument i tištěnou verzi"_ 

Děkuji, MH

**Comment by tumovam** [comment]
@SykoraLukas je potřeba něco nastavit? Ve v3.6.3 se změny neprojevily. 

NDK Svazek eMonografie: 
![Name - NDK Svazek eMonografie](https://user-images.githubusercontent.com/31240271/108067991-d4d80e80-7061-11eb-8a2e-78f019ac1881.JPG)
![Location - NDK Svazek eMonografie](https://user-images.githubusercontent.com/31240271/108068010-d86b9580-7061-11eb-87ea-1622944f1992.JPG)

Zatímco NDK Svazek Monografie je ok:

![Name - NDK Svazek monografie](https://user-images.githubusercontent.com/31240271/108068036-e15c6700-7061-11eb-94b9-8432119c6ed8.JPG)
![Location - NDK Svazek monografie](https://user-images.githubusercontent.com/31240271/108068157-04871680-7062-11eb-98fa-a0ce42361de5.JPG)

**Comment by SykoraLukas** [comment]
Mělo by stačit Ctrl+F5. 
Na testu proarc.inovatika.dev/api/ je nasazená tato verze a tam to vypadá takto:
![image](https://user-images.githubusercontent.com/27210823/108068741-c5a59080-7062-11eb-8238-3645e33731b1.png)
![image](https://user-images.githubusercontent.com/27210823/108068815-deae4180-7062-11eb-9af8-3b4809384d75.png)

**Comment by tumovam** [comment]
Hm, divné. Na proarc.inovatika.dev/api/ to též vidím 👓  Ale z našeho testovacího jsem se odhlašovala xkrát a refresh také nepomáhá...

**Comment by SykoraLukas** [comment]
Snad jsem to dobře pochopil, je to udělané pro Ndk Svazek eMonografie.

Mohla bys prosím kouknout co vám to píše za verzi? Jestli je to opravdu 3.6.3?

**Comment by tumovam** [comment]
Jo, pochopil jsi to správně. Mělo to být pro EMonografie. A máme opravdu Verze: 3.6.3, Build: 20210216110726, revize 2750c078a. Vymazala jsem cache a až nyní je to OK. Omlouvám se za zmatky. Issue se může zavřít. Přidávám label.

**Comment by SykoraLukas** [comment]
Super, tak dobrý, že to jde.

**Comment by SykoraLukas** [comment]
Uzavírám, na základě otestování.
