### ISSUE TITLE
RDflow - nový objekt s předvyplněným uuid

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1278]
Přidat možnost založit Nový objekt ze záměru s uuid, které je ručně vyplněné v poli PID.

Nebo založit ze Správy digitálních objektů nový záměr.

**Comment by SykoraLukas** [comment]
Navrhuji podobne zakladaní, jako je zakládání v editoru Vazeb.

![image](https://user-images.githubusercontent.com/27210823/109482817-c553bf00-7a7e-11eb-802b-72d3c0d7d04a.png)
 Může to takhle být? 

Možnost založit nový objekt, nebo možnost založit nový objekt s předdefinovaným uuid, které se dopíše v novém formuláři. Proces založení je stejný jako v editoru vazeb.

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by nezbedova** [comment]
Lze založit ze Záměrů.
