### ISSUE TITLE
Viditelnost objektů po updatu z verze 3.5.17

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1282]
Zdravím,

po konverzi objektů při updatu z verze 3.5.17 (nebo starší) uživatelé s rolí User ve vyhledávání nevidí objekty, které založili před updatem, vidí jen nově vytvořené. Nevidí je dokonce ani uživatel s rolí Admin, vidí je pouze SuperAdmin.

**Comment by SykoraLukas** [comment]
Toto je divné chování. Jakou organizaci mají objekty a uživatelé nastavenou? Je rozdíl mezi organizací superAdmina, admina a usera?

**Comment by svetlym** [comment]
Všichni mají nastavenou "Městskou knihovnu v Praze". Projevuje se to navíc, i když jednomu uživateli měním roli - s rolí User nebo Admin svoje staré objekty nevyhledá, s rolí SuperAdmin je vyhledá.

**Comment by SykoraLukas** [comment]
Jakou verzi používáte?

**Comment by svetlym** [comment]
ProArcVerze: 3.6.3
Build: 20210216110726, revize 2750c078a

**Comment by SykoraLukas** [comment]
Můžete prosím připojit screen obrazovky, kde jsou digitální objekty včetně sloupce organizace a zpracovatel? Děkuji

**Comment by svetlym** [comment]
Screenshot asi nebude potřeba - nově vytvořené objekty mají ve sloupci organizace hodnotu "Městská knihovna v Praze", staré tam mají hodnotu "."

Uživatelé mají každopádně všichni organizaci "Městská knihovna v Praze" (kontroloval jsem to) a měli ji už před puštěním updatu objektů.

Možná by mohlo souviset, že jsem konverzi objektů pouštěl nadvakrát - přikládám log tomcatu z prvního pokusu (druhej prošel bez chyb):
[catalina.zip](https://github.com/proarc/proarc/files/6061526/catalina.zip)

**Comment by SykoraLukas** [comment]
A uživatelé s rolí Admin a User vidí pouze nově založené objekty? Pokud ano, tak je problém s tím, že se to spustilo na 2x a ty první mají jinou organizaci než uživatelé s rolí Admin a User. 
U těchto 2 rolí funguje filtrování na základě organizací, SuperAdmin vidí všechny organizace.

**Comment by svetlym** [comment]
Ano, všechny staré objekty mají organizaci "." (znak tečka).

**Comment by SykoraLukas** [comment]
Aha, takže poprvé byl update objektů spuštěn aniž by byla u uživatelů nastavena organizace. Podruhé byl spuštěn s již nastavenou organizací. Problém v tomto případě je, že Pokud uživatel a objekt nemají nastavenou organizaci, do objektu na nastaví "." jako organizace. Pokud uživatel organizaci nastavenou má a objekt nemá, nastaví se do objektu organizace uživatele. 
Pokud ale objekt organizaci již má nastavenou, nic se nemění a objekt se přeskočí.

Tedy, u vás je potřeba doplnit organizace. Pomocí funkce update všech objektů to nejde, protože by nic nenastavila. Všechny objekty už organizaci mají a tak by se všechny objekty přeskočili. Další možností, pokud jich není mnoho je udělat update ručně přes ATM. Tam to funguje tak, že se změní organizace a změna se propíše do všech souborů, které jsou k tomuto objektu připojeny. Další možností je vytvořit obdobnou funkci, jako je "Update všech objektů", ale s tím, že se přepisuje organizace. Tato funkce by mohla vyjít během příštího týdne, kdy plánuji další verzi aplikace. Poté bude nutné opět udělat update všech objektů pomocí nově vzniklé funkce.

**Comment by svetlym** [comment]
Organizaci jsem u všech uživatelů nastaoval před puštěním prvního updatu, postupoval jsem podle návodu a všechno jsem po sobě kontroloval. To je teď ale každopádně jedno.

V Proarcu máme několik tisíc titulů, takže ruční update by byl na dlouho. Poprosil bych tedy o funkci na hromadnou opravu. Jen si ještě říkám, jestli na to opravdu musí být nová funkce - nestačilo by upravit stávající "Update všech objektů" tak, že když autor objektu má nastavenou instituci a objekt má ".", tak se nastaví podle uživatele?

PS: Ještě jedna drobnost - ukončení updatu se do logu nezapisuje. Na testovacím proarcu, kde máme málo objektů, mi v prohlížeči po skončení vyskočil dialog "update dokončen", ale v logu tomcatu nic není.

**Comment by SykoraLukas** [comment]
Děkuji za informace o logu, podívám se na to. Upravit aktuální funkci je také možnost, podívám se na to, co by bylo lepší.

Zatím prosím nastavte všem uživatelům roli superAdmin, ať mohou pracovat. Po změně se role opět sníží na role Admin/user.

**Comment by svetlym** [comment]
Dobrý den,

upravená funkce ve verzi 3.7 funguje, děkujeme. Ukončení procesu se také zapisuje do logu.
