### ISSUE TITLE
Přidání vlastností pro uživatele

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1287]
Prosím o možnost přidání vlastností pro uživatele, které bude přidělovat Super Admin. Např. Administrace -> Převést Stranu na NDK stranu / Převést NDK stranu na Stranu. 
Děkujeme, KNAV

**Comment by tumovam** [comment]
Ve v3.6.4 otestováno. Super Admin po zobrazení všech Uživatelů může vybraným userům (adminům) povolit fci převod modelů. 

Konkrétní uživatel u sebe poté vidí info: " ☑️ Smí spusti funce - BEZ K, ale to neva :) - převody modelů." 

Děkuji a přidávám label "Návrh na zavření", M.

**Comment by SykoraLukas** [comment]
Doplněn popis a opravuji chybějící písmeno.
https://github.com/proarc/proarc/wiki/Spr%C3%A1va-u%C5%BEivatel%C5%AF#vlastnost-sm%C3%AD-spustit-funkce-p%C5%99evody-model%C5%AF
