### ISSUE TITLE
Chyba při NDK exportu

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1289]
Při testování NDK článků (ve v3.6.4-preview) jsem narazila na problém s NDK exportem. 

Exportovala jsem NDK číslo, pod nímž jsou Stránky a NDK články. Zobrazí se hláška:
![obrazek](https://user-images.githubusercontent.com/31240271/109951570-262d0280-7cde-11eb-892b-1a380bad9c61.png)
V logu (proarc_export_status.log) je:
![obrazek](https://user-images.githubusercontent.com/31240271/109952054-b53a1a80-7cde-11eb-9aa6-3b67d52233f1.png)

Zkoušela jsem i NDK export, kde jsou NDK strany a NDK články a tam je obdobná hláška: 
![obrazek](https://user-images.githubusercontent.com/31240271/109952132-c97e1780-7cde-11eb-93f2-385750b4b1e0.png)

Log:
![obrazek](https://user-images.githubusercontent.com/31240271/109952186-d69b0680-7cde-11eb-8701-23f236c22778.png)

Jen pro doplnění, stránky (v prvním případě) 93 i str. 155 (2. ukázka) jsou v příslušné struktuře mezi ostatními stranami. 

@SykoraLukas případně můžu poslat archive balíčky nebo oba NDK exporty z ostrého ProArcu v3.6. Exportovat z ostrého PA totiž jdou. Já jsem potřebovala dostat ty neupravené (nerozdělené do 2 parts atd.) NDK články do test. PA, takže jsem exportovala z ostrého PA a reimportovala do testovacího... 
 
Spíš to na mě dělá dojem, jestli nemáme nějak špatně nastavený testovací ProArc? Protože obdobné chyby už jsme zaznamenali dříve (např.: https://github.com/proarc/proarc/issues/1115 nebo https://github.com/proarc/proarc/issues/1101)

Děkuju, Markéta

**Comment by SykoraLukas** [comment]
Mohla bys mi prosím zkusit zaslat oba archivní balíčky? Díky

**Comment by SykoraLukas** [comment]
Je tam problem s rozdelenim Part do dvou elementů, už to mám opravené a vyřeší se tím i export 1101.

**Comment by tumovam** [comment]
ve v3.6.4 opraveno. NDK export s NDK články proběhne.
