### ISSUE TITLE
Přidání nových časopisů - export Crossref (CEJSH)

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1295]
Bylo by možné umožnit (třeba i Super adminovi) konfigurovat exporty pro Crossref (asi i CEJSH)? 

S příchodem nových časopisů, jejichž exporty posíláme do Crossref, se nám často stává, že jsou exporty pro Crossref prázdné. Dívala jsem se a eČlánky DOI obsahují (to byl problém zmiňovaný v https://github.com/proarc/proarc/issues/1007).

Prázdný soubor se nám zobrazil u nového časopisu, u něhož jsme ještě nic neexportovali. Je potřeba časopis přidat do konfigurace, nebo ručně přímo při vývoji proArcu? Už si nevzpomínám, jak to bylo, ale vzpomínám si, že jsme to nedávno řešili a vlastně vůbec nevěděli, jak přidat nový časopis (je to toto issue https://github.com/proarc/proarc/issues/994 ?). 

A jaké údaje jsou případně potřeba? Název periodika a ISSN? Mohl bys, prosím, případně založit stránku na Wiki a krátce to popsat?

Děkujeme, KNAV

**Comment by SykoraLukas** [comment]
Ahoj, potřebuji abys mi vyplnila obdobu tohoto.
<journal issn="1211-4413">
        <title>Acta Onomastica</title>
        <discipline>PHILOLOGY___LINGUISTICS</discipline>
        <publisherAddress>Acta onomastica, redakce, Ústav pro jazyk český AV ČR, v.v.i., Letenská 4, 118 51  Praha 1, Czech Republic</publisherAddress>
        <publisher>Institute of the Czech Language, Academy of Sciences of the Czech Republic</publisher>
        <journalId>7bb33933-19b8-30c2-b6e2-0001b3e8b6fc</journalId>
        <journalFrequency>ANNUAL</journalFrequency>
        <journalWWW>http://www.ujc.cas.cz/casopisy/acta-onomastica/current-issue-archive/</journalWWW>
        <institutionWWW>http://www.ujc.cas.cz/casopisy/acta-onomastica/</institutionWWW>
        <editorialOffice>Ústav pro jazyk český AV ČR, v. v. i., oddělení onomastiky, Valentinská 1, 116 46 Praha 1, Czech Republic</editorialOffice>
        <depositorName>Ústav pro jazyk český AV ČR, v. v. i.</depositorName>
        <emailAddress></emailAddress>
    </journal>

**Comment by SykoraLukas** [comment]
Nutná konfigurace - https://github.com/proarc/proarc/wiki/Konfigurace#crossrefcejsh-export

**Comment by tumovam** [comment]
@PetrKotynek můžu Vás poprosit? Děkuji, MH

**Comment by PetrKotynek** [comment]
Bude to asi až v 3.6.4 ?? Petr

**Comment by SykoraLukas** [comment]
Přesně tak, pokud vše dobře vyjde, během zítřka vyjde.

**Comment by PetrKotynek** [comment]
Ještě dotaz, jak to bude manipulovat s duplicitou v <journal issn="něco"> ... </journal>, první záznam relativně kompletní, v druhém třeba pouze <journalId>neco-trochu-jineho</journalId>. Přičítá, be první / poslední ? Petr

**Comment by PetrKotynek** [comment]
Ještě upřesnení toto je v 3.6.3
cat cejsh_journals.xml|grep journal\ issn\= |sort|uniq -d
    <journal issn="0009-0468">
    <journal issn="0015-1831">
    <journal issn="1210-0250">
    <journal issn="1210-7050">
    <journal issn="1211-7250">
    <journal issn="1214-7249">
    <journal issn="2570-7485">
Petr

**Comment by PetrKotynek** [comment]
journal issn="0009-0468"
    journal issn="0015-1831"
    journal issn="1210-0250"
    journal issn="1210-7050"
    journal issn="1211-7250"
    journal issn="1214-7249"
    journal issn="2570-7485"

**Comment by ZdenkaSera** [comment]
@SykoraLukas Navazuji na náš rozhovor - plánoval jste v rámci tohoto issue vyčlenění konfigurace pro CEJSH/Crossref? Z issue mi připadá, že tady zatím šlo jen o přidání seznamu nových  časopisů v rámci stávajícího řešení a mělo by tedy fungovat i ve 3.7. Děkuji za upřesnění.

**Comment by SykoraLukas** [comment]
Tak jsem to dohledal. Je to hotové. ProArc obsahuje základní seznam a vše ostatní je možné přidat do nového souboru a ten následně [nakonfigurovat](https://github.com/proarc/proarc/wiki/Konfigurace#crossrefcejsh-export).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkuji, dneska jsme o tom mluvili s panem Kotýnkem, reagoval na moji poznámku výše. K testu se vrátíme, ale zřejmě musíme řešit paralelně s [#1376](https://github.com/proarc/proarc/issues/1376), zatím se nám nedaří export ani "starých" titulů.

**Comment by ZdenkaSera** [comment]
Exporty s externím souborem journalsInfo.xml ve verzi 3.7.2 fungují, issue zatím zavírám a případně znovu otevřu po masivnějších testech.
