### ISSUE TITLE
Změny od MZK

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1299]
Zamergovat změny z verze od MZK:
- Speciální druh exportu KWIS (Kramerius s podporou ImageServeru) - nutná konfigurace
- Import s možností tvoření ALTO/OCR až při běhu ProArcu - nutná konfigurace

@fstepanovsky prosím o doplnění kofigurací.

**Comment by SykoraLukas** [comment]
Dle #1272:

Rozšíření se týká možnosti exportovat exportu do krameria + distribuce obrázků na imageserver.
Rozšíření volá externí nástroj [moravianlibrary/merlin](https://github.com/moravianlibrary/merlin), který vytvoří odpovídající strukturu na imageserveru a nakopíruje tam obrázky, poté zavolá kramerius pro import metadat.
Merlin zároveň připravuje nové záznamy pro Aleph.

V rámci PR je ještě rozšíření na volání externího OCR programu, který provede OCR, k tomu se požívá [AbbyCMD](https://github.com/moravianlibrary/abbycmd).

PR je potřeba důkladně projít, aby něco nerozbil v codebase a zároveň je potřeba předělat změny do udržitelnějšího řešení viz Merlin, který je potřeba upravovat při změně modelů atp.

**Comment by SykoraLukas** [comment]
test

**Comment by fstepanovsky** [comment]
Vypadá to, že vše funguje. Navrhuji zavření issue.

**Comment by SykoraLukas** [comment]
Omlouvam se, omylem jsem okomentoval toto issue a následne komentář tedy smazal.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
