### ISSUE TITLE
Chyba při hledání ve smazaných objektech

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#1300]
Hledání ve smazaných objektech nám hází chybu:

```
javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: com.yourmediashelf.fedora.client.FedoraClientException: HTTP 404 Error: Object not found in low-level storage: uuid:62a77f17-93b8-4eee-99c9-1b0f4351bb8e
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
```

Tipuju, že je to tím, že kolegyně zkoušela mazat a smazala ručně jednotlivé stránky nebo jiné podřazené objekty, takže teď ve fedoře máme tituly, které se odkazují na neexistující objekty.

Nemůžeme už každopádně nic dalšího permanentně smazat, protože díky této chybě nemůžeme smazané objekty vyhledat.

Verze: 3.7-SNAPSHOT
Build: 20210301182912, revize 0f6df0796

**Comment by SykoraLukas** [comment]
Nejspíše bude nutné vypnout aplikaci, nechat běžet pouze postgres a spustit rebuild fedory. Vypadá to, že se nějak pokazila reference.

**Comment by svetlym** [comment]
Když mám ve fedoře třeba monografii a smažu z ní ručně jednu stranu, tak to spraví rebuild  fedory? To by mě docela překvapilo ;)

**Comment by SykoraLukas** [comment]
Je zde možnost, že při smazání došlo k tomu, že objekt byl smazán z low-level storage (acubra, legacy) ale nebyl smazán z ResourceIndexu. Resource index ho tak pořád najde, je zaindexovaný, ale už nenajde odkazovaný soubor v LL storage. Na toto by mohl pomoci rebuild (odtranil by se z RI objekt, který tam už není).

Podívám se ale i na to, jaké jsou jiné možnosti vzniku této chyby.

**Comment by svetlym** [comment]
Děkuju za radu, vypadá to, že rebuild fedory opravdu pomohl.

Za mě je možno issue uzavřít.
