### ISSUE TITLE
eMonografie - born digital

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1303]
Hodnota "born digital" z < mods:digitalOrigin> se nepropisuje do < dc:description >

test v3.6.4, nefunguje ani ve v3.6.3 (pardon, nevšimla jsem si)

**Comment by tumovam** [comment]
U nově vytvořených NDK eMonografií je po exportu NDK balíčku v < dc:description >born digital< dc:description >. U dříve vytvořených je potřeba přeUložit. 
Testováno ve v3.6.5 i 3.6.5-snapshot

**Comment by tumovam** [comment]
Správně i ve verzi 3.6.5.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.
