### ISSUE TITLE
v.3.6.5-SNAPSHOT - chybí pole Dotaz 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1310]
V testovací v. 3.6.5-SNAPSHOT není pole Dotaz pro vyhledávání.

![obrazek](https://user-images.githubusercontent.com/13831946/113832438-eb106a00-9788-11eb-8307-efd356e4761a.png)

Ve v. 3.6.2 je

![obrazek](https://user-images.githubusercontent.com/13831946/113832606-0ed3b000-9789-11eb-88aa-e5ac79fe7b21.png)
 Prosím o vrácení.

**Comment by SykoraLukas** [comment]
Opravím

**Comment by tumovam** [comment]
Ve v3.6.5 už Dotaz je. "Dotaz" k vyhledávání nepoužívám, proto prosím @nezbedova o otestování. Děkuji

**Comment by nezbedova** [comment]
Otestováno v.  3.6.5. Funguje.
Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.
