### ISSUE TITLE
Workflow_information.xml

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1311]
Od (nejspíš) verze 3.6.5-snapshot se do archive exportu přidává workflow_information.xml 

workflow_information.xml souvisí s RDFlow (když není model založený v RDFlow, tak se nemá co vyexportovat). 

Řešilo se to někde i v issue https://github.com/proarc/proarc/issues/571 , ale přece jen když to člověk vidí, je to něco jiného.

S tím workflow_information máme docela problém. Není totiž poznat, k čemu patří. Myslíme si, by bylo dobré mít buď v názvu toho souboru nějaký identifikátor, nebo identifikátor přidat do kořenového elementu toho xml. Bylo by to možné?

Děkuji, MH

**Comment by SykoraLukas** [comment]
Přidám spíše do kořenového elementu, v názvu vy to mohlo dělat problém, pokud by se s tím v budoucnu nějak pracovalo.

**Comment by SykoraLukas** [comment]
Tak jsem upravil strukturu souboru. Mohl by vypadat takto?
![image](https://user-images.githubusercontent.com/27210823/114184831-48511a80-9945-11eb-97fb-e145b2a21987.png)


Informace o tom, k čemu se "job" váže, jsou v jeho atributech. Do kořenového atributu to dát nelze, protože soubor může obsahovat více jobu (pro vícesvazek  i pro monografii) a tedy to musí být rozlišeno až na úrovni jobu.

**Comment by tumovam** [comment]
@SykoraLukas bezva! Takhle to bude určitě lepší, díky moc!

**Comment by tumovam** [comment]
Ve v3.6.5 je uuid zde:  < job uuid="uuid:..." model="model:..." label="XYZ..." profile="job.monografienewZeutschel" >. Za mě to takhle stačí. Díky!

**Comment by tumovam** [comment]
A tedy ještě pro ujištění - u vícedílek musíme mít pouze 1 workflow_information? 

Např. nyní jsem vyexportovala celou vícedílku a do 1. dílu se přidalo workflow_info, které obsahuje:
1. < job uuid="uuid vícedílky" model="model:ndkmonographtitle" ... >
2. < job uuid="uuid 1. dílu" model="model:ndkmonograpvolume" ... >
3. < job uuid="uuid 2. dílu" model="model:ndkmonograpvolume" ... >

Zatímco když vyexportuji pouze 2. díl, tak v workflow_info je < job uuid="uuid 2. dílu" model="model:ndkmonograpvolume" ... >

Nedokážeme u vícedílky oddělit metadata k 1. dílu a 2. dílu = vytvořit 2 workflow_info, které by patřilo k příslušnému uuid, do příslušného balíčku? To je jen dotaz, já vlastně nevím, co je správně. Reimport do PA jsem nezkoušela a RDFlow netestuji. 
Děkuju, M.

**Comment by nezbedova** [comment]
Jen info.

Vícedílky v RDflow fungují tak, že se založí Záměr a k němu Podzáměry. 

U jednotlivých dílů (podzáměrů) se zapisuje skenování a zpracování v Limbu. Pak následuje krok Založit nový objekt (to můžete i hned po založení podzáměru, ale není to praktické). Popis v PA se automaticky zapíše k jednotlivé monografii. (V případě, že exportuji Export pro Kramerius jednoho dílu, tak se automaticky v RDflow zapíše na základě uuid k danému dílu.)
Takto postupuji u všech dílů. 

Po dokončení úkolu Skenování u všech Podzáměrů ručně dokončím úkol Skenování u Záměru.
 
Po dokončení úkolu Zpracování v Limbu u všech Podzáměrů ručně dokončím ůkol Zpracování v Limbu u Záměru.

PAK až ve Správě digitálních objektů připojím jednotlivé díly=monografie k Vícedílné monografii.

Od té chvíle se přestávají úkoly zapisovat na úrovni jednotlivých dílů (podzáměrů), ale zapisují se k nadřazené úrovni(záměru).
Proto jsou ty joby tři. 

Úkoly, které se dělají na úrovni celé vícedílky (K4 export, Zveřejnění, Archive balíček, Smazat) se napropíší k podzáměrům, ale k záměru. 


 1.   < job uuid="uuid vícedílky" model="model:ndkmonographtitle" ... > Export pro Krameria, Zveřejnění, Archive export. Skenování je dokončené jako info, že jsou všechny díly (podzáměry) dokončené. Chybí info o skeneru a počet skenů.
Zpracování stejné jako skenování.
 
  2.  < job uuid="uuid 1. dílu" model="model:ndkmonograpvolume" ... > Skenování - skener, počet skenů, Zpracování - počet skenů. Pokud nebudu z nějakého důvodu dělat Export pro Krameria, tak tam info nebude.
 
 3.   < job uuid="uuid 2. dílu" model="model:ndkmonograpvolume" ... >Skenování - skener, počet skenů, Zpracování - počet skenů. Pokud nebudu z nějakého důvodu dělat Export pro Krameria, tak tam info nebude.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.
