### ISSUE TITLE
main_mets.xml vs. mets.xml

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1312]
Ve v3.6.5-Snapshop otestován archive export pro NDK Svazek monografie. Od předchozích balíčků se liší tím, že ve složce NDK se METS jmenuje main_mets_aba007-něconěco.xml , zatímco v dřívejších archivních exportech to byl "pouze" mets_aba007-něconěco.xml . 

Řešili jsme to částečně v iusue https://github.com/proarc/proarc/issues/1304 , ale radši zakládám samostatné issue. 

Přejmenování METS na MAIN_METS vzniklo kvůli zvukovým dokumentům. 

V KNAV třeba zvuk. dokumenty vůbec nemáme a předpokládám, že mít nebudeme, a všechny naše dosavadní archivní balíčky mají METS pouze jako METS, ne MAIN_mets. Mohlo by se by to main_ opravit, prosím, aby se nám nelišily balíčky z různých PA verzí? 

Pavla Kočišová z Odd. pro standardy NKP mi v issue https://github.com/NLCR/Standard_NDK/issues/146 odpověděla, že "... Z hlediska dokumentů, které již zdigitalizované jsou, nebo dokumentů ve stávajících verzích DMF se změna neplánuje a úzus se v dohledné době ani měnit nebude."

Nemohli bychom se vrátit k pojmenování METS namísto MAIN_mets? 

Děkuji, Markéta z KNAV :)

**Comment by SykoraLukas** [comment]
ano, vrátím to.

**Comment by tumovam** [comment]
Mockrát děkuju! Možná se to zdá jako malichernost, ale zase bychom měli od určitě verze jiné archivní balíčky... M.

**Comment by tumovam** [comment]
Otestováno ve v3.6.5 u archivních balíčků pro NDK Svazek monografie, NDK eMonografie a STT Monografie. Všude v pořádku. Jsem pro zavření.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.
