### ISSUE TITLE
Chyby v exportu NDK PSP balíčků

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1314]
Dnes se při exportování NDK PSP objevily balíčky s chybami.

Každý druh chyby dávám do samostatného komentu. 

Některé error exporty jsme dali znovu a proběhly. Celkem na exportech pracovali tři uživatelé (každý na svých) a dva uživatelé dělali reindexaci.

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114202610-a2f37200-9957-11eb-9fbe-fd7df5e91d7b.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114202696-bbfc2300-9957-11eb-8e82-d1fb54423612.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114202993-0c738080-9958-11eb-897d-7c80a56862cb.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114203570-93c0f400-9958-11eb-9ea4-fe834d8eb083.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114203721-b4894980-9958-11eb-9f44-e041eff5e7e4.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114203898-e3072480-9958-11eb-9112-2243c31b820d.png)

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/114204037-06ca6a80-9959-11eb-8729-e66cbc620fa0.png)

**Comment by SykoraLukas** [comment]
Práce probíhala zároveň? Jaké chyby se opravili tím, že se pustili znovu a jaké ne? Mohlo jít o dočasné vytížení fedory, ale bez dalších informací nemohu říct důvod.

**Comment by nezbedova** [comment]
Ano, práce probíhala zároveň. Nejvíc chyb bylo po 11 hod - z tech se něco opravilo. Pak druhá vlna 13:48 až 14:27 - to jsme nechali na průzkum.

Výše uvedené chyby jsou ty, které se neopravovaly. Teď jsem je pustila od sebe a uvidím, co se opraví.

**Comment by SykoraLukas** [comment]
Děkuji

**Comment by nezbedova** [comment]
Z chyby č. 2 se po novém exportu stala nový chyba

![obrazek](https://user-images.githubusercontent.com/13831946/114212887-9de7f000-9962-11eb-82d2-b05a599202c6.png)

**Comment by nezbedova** [comment]
Z chyby:

![obrazek](https://user-images.githubusercontent.com/13831946/114363519-c3e6dd80-9b78-11eb-8908-0f2bc67fd352.png)

Se po novém exportu stala chyba:

![obrazek](https://user-images.githubusercontent.com/13831946/114363624-dd882500-9b78-11eb-9b19-d82b84ea72df.png)

Po dalším exportu se uuid nemá error, ale chybí log a součty md5. Vše doběhlo v 7:35. Zjistila jsem, že chybí amd_mets_aba007-0002hg_0141.xml

Pa dalším exportu se opakovala předchozí chyba.

**Comment by nezbedova** [comment]
Testováním jsem zjistila, že je jedno, kolik je v PA uživatelů, kolik jich exportuje. Když jsem tam v pátek navečer byla sama, stejně se udělaly chyby.

**Comment by SykoraLukas** [comment]
Dělá to pořád stejné chyby? Případně jakou verzi máte nasazenou?

**Comment by nezbedova** [comment]
NDK PSP balíčky už neexportujeme. Ale asi je to stejná chyba jako  #1329 . PA nedokáže dělat větší množství exportů. 

Verze: 3.6.2

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, nebylo by to zatím k uzavření? NDK balíčky bude zapotřebí přetestovat, ale spíš cíleně po jednom. Děkuji.

**Comment by nezbedova** [comment]
@ZdenkaSera Ano, issue se může zavřít.

**Comment by ZdenkaSera** [comment]
@nezbedova Děkuji a zavírám.
