### ISSUE TITLE
Nelze exportovat jako archivní balíček

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1318]
O parazitech a lidech: 4c914c1f-4393-4f3d-b8f4-684e3ac4d2ee

Fedora OK, index funkční. Je to z ostrého PA a logy jsou mimořádně rozsáhlé, řádu GB. 
Připojuji výtah z logů a proarc_export_status.log zachycený kolegyní Šerou.
[proarc_export_status.log](https://github.com/proarc/proarc/files/6323417/proarc_export_status.log)
[4c914c1f-4393-4f3d-b8f4-684e3ac4d2ee.txt](https://github.com/proarc/proarc/files/6323419/4c914c1f-4393-4f3d-b8f4-684e3ac4d2ee.txt)

Petr Kotýnek

**Comment by SykoraLukas** [comment]
Problém je se stranou, v poli index je napsané něco jiného než číslo. Proto to skončí chybou.

**Comment by zeva1104** [comment]
Děkuji, objekt se podařilo opravit  exportovat. 
Z. Šerá
