### ISSUE TITLE
chyba při přiřazení urn:nbn Process: Changing models failed

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1319]
Dělnická otázka a náš průmysl: ef1429f3-52da-420b-ad7c-33844b4a3a42 - chyba už při přiřazení urn:nbn

Zdroj opět pí. Šerá, ostrý PA. Podle mého relevantní záznam až z ledna.
[ef1429f3-52da-420b-ad7c-33844b4a3a42.txt](https://github.com/proarc/proarc/files/6323487/ef1429f3-52da-420b-ad7c-33844b4a3a42.txt)

Petr Kotýnek

**Comment by SykoraLukas** [comment]
Dle chyby se neprovádělo přidělení URN:NBN ale o změnu modelu (z ndk strany na stranu).
