### ISSUE TITLE
Autority -> Určení: Mods:Subject

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1320]
Kdybych chtěla nějakou osobu (např. Němcová, Božena) přidat do "Subjektu" a vyberu Určení: Mods:Subject, vůbec nic se nenajde. Zatímco když dám dotaz "Němcová, Božena" a vyberu Určení: Any, případně Určení: Mods:Name , nabídne se mi několik Němcových... 
Dělám něco špatně? 
Díky, M.
(testováno ve verzi 3.6.5)

**Comment by SykoraLukas** [comment]
Při hledání se filtruje v čem se vrací odpověď ze serveru. Pokud dáš mods:subject, hledá to jen v mods:subject. Tam nejspíš Němcová není. Když dáš mods:name hledá se v name, tam by být měla. Když se dá any, hledá se v mods:name a mods:subject.

**Comment by tumovam** [comment]
Tak jinak, když chci Němcovou dostat do proarcovského formuláře (a XML) do "Subject", tak to nějak jde, nebo ne? Dokážu si totiž představit, že bude knížka o Boženě N., ale autorkou publikace nebude = chceme ji mít v subjektu, ne v name.

**Comment by SykoraLukas** [comment]
tak to nelze, pokud neni vedena jako vecna autorita, ale jen jako jmena autorita.

**Comment by tumovam** [comment]
Dobře, takhle mi to stačí. Díky ;)

**Comment by SykoraLukas** [comment]
Můžeme tedy issue uzavřít?
