### ISSUE TITLE
Autority -> korporace, konference

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1322]
Když stahuji korporaci nebo konferenci, která má **číslo autority**, tak se toho identifikační číslo do formuláře nepřetáhne. 
Test ve v3.6.5

**Comment by SykoraLukas** [comment]
Můžes uvést příklad? Ať to mám na čem zkoušet. Děkuji

**Comment by tumovam** [comment]
- Tvář naší země - krajina domova (konference) - č. autority ko20211110512
- Analytická cytometrie (konference) - kn20091103005
- Astronomický ústav (Akademie věd ČR) - ko2002150690
--> v PA vyhl. bez závorky

**Comment by SykoraLukas** [comment]
Díky, kouknu na to, ale do pondělí to nebude.

**Comment by tumovam** [comment]
To ani nečekám, my jsme pro změnu nestíhali dříve testovat. Díky

**Comment by tumovam** [comment]
Ve v3.6.6 se číslo autority se stahuje do formuláře i xml. Testováno zatím u NDK Svazku monografie a NDK Článku. Pro další modely prosím @zeva1104

**Comment by ZdenkaSera** [comment]
Testovali jsme ve verzi 3.7.3 a nenašli zatím problém. Jak to vidíte u Vás @luckajirku ? Není to k uzavření? Děkuji.

**Comment by luckajirku** [comment]
Jestli se jedná o stahování autority korporace v rámci bib záznamu, tak za nás OK, stahuje se vč. čísla autority. Ověřovala jsem NDK Svazek mon. a NDK Per. 
(Pokud je tím ale myšleno stahování autorit přímo z báze autorit do prázdného objektu, tak to nepoužíváme.)

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
