### ISSUE TITLE
Autority -> Name geographic

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1323]
Ať hledám v poli Name geographic cokoli, tak se vždy objeví neočekávaná chyba.
![obrazek](https://user-images.githubusercontent.com/31240271/115021090-cec4a980-9ebb-11eb-9a34-75274d899f76.png)

Když ale hledám v "Any", tak už se něco málo objeví:
![obrazek](https://user-images.githubusercontent.com/31240271/115021195-f3b91c80-9ebb-11eb-8495-ac20af271fb0.png)

Když už ale znám č. autority, a zadám ho do pole dotaz, tak se zobrazí se "Geographic code:e-xr-" , ale očekávám "Kbely (Praha, Česko)": 
![obrazek](https://user-images.githubusercontent.com/31240271/115021359-2a8f3280-9ebc-11eb-8e1c-c817639013ff.png)

Testování v3.6.5

**Comment by SykoraLukas** [comment]
Ano, tohle se řešilo už minule na schůzce. Problém je, že jediné, co vrací server Autorit je tenhle kod, který ještě ke všemu není přesný.

**Comment by tumovam** [comment]
Já vím, že se to řešilo, jen jsem to chtěla mít napsané na GH 👼

**Comment by SykoraLukas** [comment]
Podařilo se mi změnit způsob jak se získávají data a díky tomu se nyní získává více informací o Geo autoritách.

Dá se již hledat i dle pole "Name geographic"

Nově se získává právě to, co je očekávané (při dotazu výše je jednou ze stažených věcí hodnota Kbely (Praha, Česko).

Kromě toho geografické kody (napr: e-xr---, překládáme na Česko) překládáme na čitelnou podobu. Vycházíme z https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/schvalene-materialy/geogr-kody1

**Comment by SykoraLukas** [comment]
![image](https://user-images.githubusercontent.com/27210823/119631128-e45cb580-be0f-11eb-9d20-526f9ce39947.png)

**Comment by luckajirku** [comment]
Jenom pro jistotu @SykoraLukas - bereš to tedy z autoritního záznamu odkud? Spolehlivě vždy by to mělo být v autoritním záznamu v poli 151 (popdpole a + v podpoli 7 číslo autority).

**Comment by SykoraLukas** [comment]
Ano, přesně jak píšeš. Pole 151 podpole a. Na číslo té autority jsem založil nové issue #1334. Je potřeba ještě vyřešit, kam se má stahovat číslo autority, jestli se teda má stahovat.

**Comment by ZdenkaSera** [comment]
Ve verzi 3.7.2. funguj, jak je popsáno výše.

**Comment by SykoraLukas** [comment]
Zavírám na základě dohody ze schůzky.
