### ISSUE TITLE
Chyba ve foxml NDK článků (RELS-EX vazby "isOnPage")

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1326]
Když vyexportuji foxml čísla NDK periodika se stránkami a NDK články, tak ve foxml NDK článku chybí jakékoli pořadí stránek. Nechybí v RELS-EX vazbách seznam stránek, které patří pod konkrétní článek? Např. když má článek 3 stránky, nemělo by být součástí K4 exportu něco jako:
< kramerius:isOnPage:uuid:1.str.článku > nebo < kramerius:hasPage:uuid:1.str.článku >
< kramerius:isOnPage:uuid:2.str.článku > nebo < kramerius:hasPage:uuid:2.str.článku >
< kramerius:isOnPage:uuid:3.str.článku > nebo < kramerius:hasPage:uuid:3.str.článku >
?

Podle čeho poté Kramerius pozná, jaké stránky patří pod konkrétní NDK článek, když jejich uuid nejsou zmíněné ve vazbách ve foxml?

Děkuji za odpověď

Testování v PA v3.6.5

**Comment by tumovam** [comment]
@SykoraLukas dohledala jsem, že jsi to před téměř rokem konzultoval s vlahodou _"V FOXML vygenerovanych Proarcem chybi v RELS-EXT clanku vazby na stranky ( kramerius:isOnPage). Konzultoval jsem to s Lukasem Sykorou a tento problem by uz v novejsich verzich Proarcu mel byt opraven. Poskytnuty NDK balicek se naimportoval spravne vcetne cisel stran, issue 727 se ho netyka, protoze neobsahuje MODS pro stranky a convertor NDKMETS->FOXML generuje FOXML stranek, ktere kramerius indexuje spravne."_ (IN: https://github.com/ceskaexpedice/kramerius/issues/760).

Můžeš se na to podívat, prosím? Díky moc!

**Comment by SykoraLukas** [comment]
A je to tedy tak, že článek/kapitola je na stejné urovni jako strany, jen má odkaz na dané stránky.

**Comment by tumovam** [comment]
Ano, přesně tak. Článek/kapitola je na stejné úrovni jako Strana. Ale do foxml článku je potřeba přidat do RELS-EXT vazeb info, že ten konkrétní článek je na stranách (isOnPage) uuid:123xyz...

**Comment by kerschfilip** [comment]
Bylo by, prosím, možné tohle issue vyřešit přednostně, @SykoraLukas? 

Ještě jsem to testoval a myslím, že chyba, kterou popisuje @tumovam, souvisí s Funkcí pro opravu NDK článků #1260. Pokud NDK článek obsahuje původní variantu, kde byly pageIndex a pageNumber v jednom `mods:part`, tak se při Exportu pro Kramerius v části RELS-EXT správně vytvoří příslušené vazby, například:
```xml
<kramerius:isOnPage rdf:resource="info:fedora/uuid:3e42e8ee-3781-47f8-ae9a-09be10876bef"/>
```

Pokud ale na ten stejný článek použiju tu funkci Update NDK článků, tak se sice správně rozdělí pageIndex a pageNumber do dvou `mods:part`, ale v Exportu pro Kramerius potom chybí ty elementy `<kramerius:isOnPage>`. Testoval jsem ve verzi 3.7, Build: 20210823140555, revize ffca7c9c6

Snad to není falešná stopa, ale i kdyby ano, potřebovali bychom s tímhle pohnout :-)

Ještě je potom vzhledem k zobrazení v Krameriovi důležité, aby pořadí jednotlivých `<kramerius:isOnPage>` odpovídalo pořadí stránek (asi tedy pageIndex od nejmenšího k největšímu?). Když uživatel v Krameriovi klikne na název článku, měla by se mu zobrazit první stránka článku. Kramerius ale podle mého testování moc nepřemýšlí nad tím, která stránka je první a prostě bere první výskyt elementu `<kramerius:isOnPage>`. 

Mockrát díky!

FK, KNAV

**Comment by SykoraLukas** [comment]
Problemem tady je, ze stranky dle zarazeni nepatri pod kapitolu/clanek, ale pod svazek monografie/cislo. Clanek/kapitola e na to jen odkazuje pres cislo strany/index strany. Takze proarc nevi, ze nejake takove vazby vubec existuji. 

Resenim tedy je dogenerovani az pri exportu.
U NDK exportu/archivacniho exportu se musi dodatecne doplnit strukturalni vazby.
U K4 exportu je nutné doplnit vazby do FOXML clanku/kapitoly.

Mám to dodělat pro všechnz tři exporty nebo stačí už jen NDK a Archive export?

**Comment by kerschfilip** [comment]
Pokud by to šlo, tak pro všechny 3 exporty. Děkuji!

**Comment by kerschfilip** [comment]
v K4 exportech jsou doplněné vazby ve FOXML článků, takže v Krameriovi už všechno funguje správně. Moc díky!

u NDK exportu a archivního exportu jsem si žádné změny nevšiml. Je potřeba tam ještě něco upravovat @SykoraLukas? Mně připadá, že minimálně NDK PSP odpovídá standardu a žádnou úpravu nepotřebuje.

**Comment by SykoraLukas** [comment]
Nn tam to je vyřešeno na straně krameria. V ndk je pouze potreba, aby se správně zapsala logická a strukturální mapa z které pak kramerius na importu utvori rels-ext vazby pro foxml.

**Comment by kerschfilip** [comment]
vyzkoušel jsem i import NDK balíčku do Krameria a vazby se tvoří správně, takže myslím, že je to takhle všechno. Moc děkuju!
