### ISSUE TITLE
Přidání vlastností pro uživatele - NDK články

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1327]
Prosím o možnost přidání vlastností pro uživatele, které bude přidělovat Super Admin. 

Zatímco issue https://github.com/proarc/proarc/issues/1287 bylo na NDK strany, tak v tomto issue prosím o přidání možnosti převodu NDK článků. 

Funkce je v: Administrace -> Update NDK článků. 

Děkuji za KNAV ;)

**Comment by SykoraLukas** [comment]
My ale nemáme žádnou funkci na převod NDK článku. Jen funkci na opravu metadat NDK článku. Myslíš tuto?

Může to být na základě stejné vlastnosti? Když ji uživatel má, smí převádět modely na NDK modely a opravovat metadata. Nebo to má být separátně?

**Comment by tumovam** [comment]
Promiň, špatně sjem se vyjádřila, samozřejmě mluvím o opravě metadat: https://github.com/proarc/proarc/issues/1260

Pokud je snadnější naprogramovat 1 vlastnost zahrnující Převod na NDK strany + úpravu NDK článků, tak souhlasím. Stejně to budou dělat stejní lidé :)

Díky moc! M.

**Comment by tumovam** [comment]
Otestováno ve v3.6.6. Zavírám.
