### ISSUE TITLE
Nelze načíst data z Krameria k existujícímu nadřazenému objektu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1330]
Potřebuji načíst výtisk ( export z Krameria ) Periodika, přičemž v ProArcu už titul i ročník je. Hodí to chybu, že uuid titulu už ve Fedoře je a nenačte mi to. Potřebujeme, aby se to načetlo.
![obrazek](https://user-images.githubusercontent.com/24409660/119305410-fe0fc880-bc68-11eb-9d3b-55d17cfa5f00.png)

**Comment by SykoraLukas** [comment]
Bylo domluveno, že se načítá jen pokud tam ty objekty nejsou. Stejně to funguje pro import archivního balíčku.

**Comment by SmejkalovaAnna** [comment]
Ano, to je jasný, ale já tam potřebuju dostat dva výtisky z Krameria, které v PA nejsou, ale neprolezou mi tam přez to uuid titulu a zřejmě i ročníku, protože ty tam už jsou.

**Comment by SykoraLukas** [comment]
Možnosti:

- Zachovají se data v ProArcu, smažou se data pro duplicitní objekty z balíčku (Zachová se pouze vazba na daný objekt).
- Zachovají se data v balíčku, smažou se data pro duplicitní objekty z ProArcu (Nebezpečí: rozpojí se stávající vazby v ProArcu týkající se těchto objektů).

**Comment by SmejkalovaAnna** [comment]
@luckajirku Lucko prosím Vás, jak jsme se domluvili tenkrát na schůzce, že to budeme chtít? Zapomněli jsme to sem napsat a já už teď nevím.... aby se to udělalo. Lukáš tady píše dvě možnosti... já si vůbec nejsem jistá, která to byla. Nějak se na to zapomnělo.

**Comment by tumovam** [comment]
@SmejkalovaAnna myslím si, že se na schůzce nedošlo k žádnému závěru. Pro připomenutí, jde tedy o to, že když zpětně reimportuješ uuid, které už v PA je, tak se nic nestane, protože PA ví, že dané uuid už v PA je? Tedy když reimportuješ uuid čísla (ročníku), tak protože je v balíčku i uuid periodika, které už v PA je, tak to celé PA rovnou zahodí, i přes to, že tam třeba chybí nějaké číslo? Je to tento problém? 
V tom případě je určitě je potřeba, aby PA hlásil, že se jedná o duplicitu, tzn. aby vyskočilo okno s hláškou. 
Už jsem nějakou dobu mimo dění, ale v tomto případě se asi nic moc nezměnilo, že? Takže pokud je můj názor ještě relevantní, tak jako bezpečnější mi přijde ta 1. z nabízených variant = **Zachovají se data v ProArcu, smažou se data pro duplicitní objekty z balíčku (Zachová se pouze vazba na daný objekt)**. Protože v KNAV to budete stejně používat pouze kvůli opravám. 
Pokud si správně vybavuji, tak @SykoraLukas zmiňoval možnost, že by např. u periodik šlo zachovat strukturu, která je v ProArcu, a pak zpětně naimportovat (doimportovat) pouze úrovně čísla (např. právě ty chybějící z Krameria). Takže ty, Aničko, jakožto zpracovatel bys věděla, že uuid čísla xyz patří k nadřazené úrovní uuid periodika xyz, kam by sis to přes Nadřazený objekt přiřadila... snad nejsem úplně mimo.

**Comment by SmejkalovaAnna** [comment]
@tumovam a @keschfilip Markéto a Filipe ono to hlídá, vyskočí, že to tam už je, ale problém je taky ten, že importuji dejmetomu ročník nebo výtisk, který tam není, ale je tam ta NADŘAZENÁ úroveň - ten Titul, a ten export z Krameria samozřejmě to uuid titulu v sobě má, takže mi to hodí chybu, že to uuid už tam je a že to nenaimportuje.....na příští schůzce to probereme ještě jednou.

**Comment by SykoraLukas** [comment]
Nepřijde mi to jako dobý návrh, protože v případě toho bodu 2 se nejprve smažou uuid, která již v proarcu jsou (v případě titulového objektu se  smaže vše s tímto uuid a vše pod ním tj. v případě periodika, které má např 20 ročníků a každý z nich 51 čísel, tak pokud budu chtít nahrát jedno číslo, tak tím smažu vše a teprve poté importuji jedno číslo?

U bodu jedna je potřeba rozmyslet, jak se to má chovat, pokud budu chtít importovat i jen číslo/stránku, která v ProArcu je. Je to sice extrémní případ, ale také možný. Tím pádem by se nenaimportovalo nic?

**Comment by kerschfilip** [comment]
Návrh pracuje se dvěma možnostmi, které už jsi zmínil dříve. Bodem dva myslíš "Zachovají se data v balíčku, smažou se data pro duplicitní objekty z ProArcu"? Pokud ano, tak je to taková dost radikální varianta, u které nepředpokládám, že by se ve skutečnosti měla moc používat (proto je v návrhu omezená jen na superadmina). Nicméně neuvažoval jsem o rekurzivním mazání. Tedy pokud budu chtít importovat jedno číslo k periodiku, které má 20 ročníků a každý z nich 51 čísel, tak jsem to myslel tak, že se nahradí uuid ročníku a titulu periodika, ne že se ostatní čísla smažou - jen hrozí to, že se rozpojí vazby. Pokud to i tak působí jako příliš nebezpečné, tak tuhle variantu asi nemusíme realizovat.

V zásadě jde hlavně o to, abych mohl do proarcu dostat číslo periodika, jehož titulní, případně ročníková úroveň tam už je. Na to by varianta "Zachovají se data v ProArcu a smažou se data pro duplicitní objekty z balíčku" měla stačit

Pokud budu chtít nahrát pouze jednu stránku, mělo by se to řešit podle mě funkcí z https://github.com/proarc/proarc/issues/1417

**Comment by SykoraLukas** [comment]
Ano, je to tak jak píšeš. Ještě to nahrazení můžeme udělat, že se to omezí na model (jde nahradit vše kromě modelu strany).

**Comment by SykoraLukas** [comment]
K tomu "Zachovají se data v balíčku, smažou se data pro duplicitní objekty z ProArcu" to bylo myšleno tak, že se nahradí streamy  MODS, DC v ProArcu těmi novými z importního balíčku, ne že se nahradí celý objekt + je do reslExt přidá ta nová vazba.

**Comment by SykoraLukas** [comment]
Nutné probrat:
Omezení, které modely se mají dat přepisovat.
Omezení na streamy, které de přepisují.

Moje predstava je, ze se dá přepisovat
- u skenovanych věci vše kromě Strany, Ndk Strany, Stt strany, zvukové nahrávky a eClanku 
- u ndk eVeci vše kromě Ndk eClanku, Ndk eSvazku (VD) Monografie, Ndk eCisla, Ndk eKapitoly a Ndk ePriloh

Přepisováne streamy jsou Mods, Dc a vždy přidání nového potomka do Rels-Ext původního objektu

**Comment by ZdenkaSera** [comment]
7.9. - schválen návrh

**Comment by ZdenkaSera** [comment]
@SykoraLukas Je tady zapotřebí úprava ve správě procesů i na straně klienta? Zobrazení hlášek ....

**Comment by ZdenkaSera** [comment]
Testovali jsme typickou situaci, pro kterou potřebujeme tuto funkci (viz původní zadání): k periodiku v ProArcu potřebuji načíst výtisk vyexportovaný z Krameria jako FOXML
- Export z Krameria s volbou "včetně foxml rodičů"
- Import do PA spuštěn s profilem Kramerius NDK Periodikum
- Proces skončil s konfiktem načítání daném již existujícím uuid titulové úrovně ->> **načítání spuštěno s volbou "Použít původní metadata"**
- Vyskočila chyba už řešená jinde pro jiné modely (viz obrázek níže), proces ale pokračoval a skončil v zeleném statusu "uloženo"
- V úložišti se na úrovni titulu nic nezměnilo, pouze se aktualizoval timestamp poslední úpravy
- Ročníky s výtisky založené v PA dříve nebyly nijak dotčeny ani se neodpojily
- Nově importovaný výtisk se správně uložil i s nadřazeným ročníkem, ale nenapojil se na titul
- ![image](https://github.com/proarc/proarc/assets/79305516/dd4c640f-5b93-4d86-b4fe-bc5caca6ec46)
- Doimportovaný ročník jsem smazala a stejná data znovu importovala, tentokrát s volbou "Použít nová metadata"
- Proces skončil s chybou ukládání 
- ![image](https://github.com/proarc/proarc/assets/79305516/c0474c4d-67ad-4845-8b2b-2f86f7b65f86)

**Comment by ZdenkaSera** [comment]
Bude zapotřebí ošetřit také situaci, kdy by z Krameria bylo exportováno FOXML "bez foxml rodičů".  Teoreticky se to může stát,  testovala jsem záměrně. Došlo k chybě, která si vyžádala zásah administrátora
![image](https://github.com/proarc/proarc/assets/79305516/deb7a4b2-7e47-4bb2-a07e-d1edaf364415)

**Comment by ZdenkaSera** [comment]
Přepis metadat pomocí foxml nefunguje ani pro monografie. Stejně jako u periodika dlouho zůstává ve statusu "čeká ve frontě", přičemž už existuje chybové hlášení ofocené výše. Nakonec se změní label na chybu ukládání.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tohle nám trošku usnulo, přeřadíme to do dalšího balíčku priorit. Díky.

**Comment by ZdenkaSera** [comment]
Lokálně v KNAV funkční ve v 4.2.0/2.3.0. Není otestováno na všech typech importů (FOXML, NDK PSP, archiv). Zásadní funkce, kdy lze k periodiku v ProArcu  doimportovat FOXML vyexportované z Krameria (zatím test s K5), je ok. 
Navrhuji k uzavření, případné chyby budeme řešit v samostatných issues.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
