### ISSUE TITLE
Kramerius Export

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1339]
K4 kontrola vyplnění typu, indexu a čísla strany. Index musí být ještě nepřetržitý vzrůstající.

**Comment by SmejkalovaAnna** [comment]
Při exportu vícedílky mi to hází chybu, že není vyplnění typ strany, dohledala jsem že u strany 1, ale já tam všechno vyplněné, mám tam normální strana, nic tam nechybí.... přidávám Log
[proarc_export_status.log](https://github.com/proarc/proarc/files/6575920/proarc_export_status.log)

**Comment by SykoraLukas** [comment]
Mužete mito prosím vyexportovat jako Archive export a poslat?

**Comment by SmejkalovaAnna** [comment]
Kam to mám poslat? Je to dost velký.... přez 2 G

**Comment by SykoraLukas** [comment]
Nevadí, pře filesender to pujde. Na lukas.sykora@inovatika.cz. Děkuji

**Comment by SmejkalovaAnna** [comment]
Je to tam Lukáši.

**Comment by SykoraLukas** [comment]
Díky, jdu na to kouknout.

**Comment by nezbedova** [comment]
Export nejde jen když má typ strany "Normální strana". Pokud zadám a uložím jiný typ strany, např. "Ilustrace", tak se K4 vyexportuje. Zadat "Normální strana" a uložit nepomáhá, export nejde.

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by SykoraLukas** [comment]
Zavírám na základě labelu.
