### ISSUE TITLE
NDK eČlánek - přidání PDF

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1341]
V PA není možné přidat PDF u NDK eČlánku.
V Editoru digi dat chybí: ![obrazek](https://user-images.githubusercontent.com/31240271/119966569-bad89100-bfab-11eb-88f1-ae3adb94f401.png)

**Comment by SykoraLukas** [comment]
Doplněno i pro kapitoly.

**Comment by tumovam** [comment]
Testováno ve v3.6.6 -u eČlánky i NDK eČlánku opraveno. U eKapitoly stále chybí.

**Comment by tumovam** [comment]
ve v3.6.7 funguje i eKapitola. Zavírám. Díky!
