### ISSUE TITLE
NDK ePeriodikum, eRočník, eČíslo - chybí exporty

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1342]
chybí Export pro Kramerius, Crossref export, NDK PSP export

**Comment by SykoraLukas** [comment]
NDK PSP export u techto objektu neni. Ale máš pravdu, ž tu chybí Crossref a Kramerius

**Comment by tumovam** [comment]
Exporty doplněny. K4 export ve v3.6.6 funguje. Import do Krameria ne. V tuto chvíli zavírám.
