### ISSUE TITLE
RDflow - změna názvu Uživatel z hlavičky záměru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1345]
Prosím změnit název "Uživatel" na Vytvořil. A zrušit rozbalovátko, aby se to nedalo měnit.

![obrazek](https://user-images.githubusercontent.com/13831946/121332165-e2b6e580-c917-11eb-94ec-80e757771fe3.png)

**Comment by nezbedova** [comment]
Hotovo.

**Comment by SykoraLukas** [comment]
Zavírám na základě labelu.
