### ISSUE TITLE
RDflow - zakázat dokončení u záměru s otevřenými úkoly

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1346]
Pokud se v hlavičce záměru nastaví stav "Hotový", zapíše se u všech úkolů stav "Dokončen". To je chyba. Záměr by neměl jít dokončit, pokud má nějaké úkoly ve stavu "Připraven" nebo "Probíhá". Pokud tam jsou úkoly, které se z nějakého důvodu nedělají, tak u nich lze nastavit stav "Zrušen"

**Comment by SykoraLukas** [comment]
Takže pokud záměr obsahuje nějaké (alespoň jeden úkol ve stavu "Připraven" nebo "Probíhá", tak nedovolit přepnout stav celého záměru na Hotový. Jen se chci ujistit, že jsem vás pochopil.

**Comment by nezbedova** [comment]
Přesně tak. Teď to všude doplní Dokončen, aby se mohl stát Hotovým.

A hodila by se hláška s upozorněním. "Úkoly nejsou dokončené." Nebo někam vykřičník.

**Comment by SykoraLukas** [comment]
Pokud záměr obsahuje alespoň jeden úkol ve stavu "Připraven" nebo "Probíhá" tak vyběhne hláška. 
![image](https://user-images.githubusercontent.com/27210823/121904207-46cb1680-cd29-11eb-9204-a0bb2e785c3c.png)

Ostatní stavy se ignorují. Pokud záměr obsahuje úkoly v jiných stavech než "Připraven" nebo "Probíhá", tak se stav těchto úkolů přepíše na "Dokončen".

**Comment by nezbedova** [comment]
Otestováno. Funguje.

**Comment by SykoraLukas** [comment]
Zavírám na základě labelu.
