### ISSUE TITLE
RDflow - zobrazení verze

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1353]
Přidat do informací o ProArcu (nebo jinam) info o používané verzi RDflow.

**Comment by SykoraLukas** [comment]
Bude zobrazeno v novém klientovi. Jádro je pro to připraveno. Informace se podává stějně jako infromace o jádru proarcu.

@honza-rychtar prosím doplníš do obrazovky o clientovi a o jádru ještě zobrazení tohoto elementu `rdflowVersion`?


K testování je možné použít toto `GET http://localhost:8081/proarc/rest/v1/info`

Odpověď serveru:
```
{
  "response": {
    "status": 0,
    "startRow": 0,
    "endRow": 0,
    "totalRows": 1,
    "data": [
      {
        "version": "3.6.6-SNAPSHOT",
        "timestamp": "20210923224428",
        "revision": "0b3eaca250e43ef3c768ef5142ce9b19b026dd96",
        "rdflowVersion": "TEST-001"
      }
    ]
  }
}

```

**Comment by SykoraLukas** [comment]
Na začátek workflow je potřeba přidat element <version>, který bude obsahovat jakýkoli textový řetězec na jeden řádek.

viz [konfigurace](url)

**Comment by SykoraLukas** [comment]
Dočasné řešení je za url adresu proarcu doplnit `/rest/v1/info`

příklad: https://proarc.inovatika.dev/api/rest/v1/info

Verze je zapsána v elementu `"rdflowVersion":"RDflow_MUO_2021_07_vicedilky"`

**Comment by nezbedova** [comment]
@SykoraLukas Zkusila jsem:

![obrazek](https://user-images.githubusercontent.com/13831946/134648547-9034cb31-9e7b-4924-9477-d60e143ec53c.png)

A není validní:

![obrazek](https://user-images.githubusercontent.com/13831946/134648393-17a1a479-ea6c-4f36-aa93-c6af8c8b8ad4.png)

Je to moje chyba nebo se to musí dát do validátoru?

**Comment by SykoraLukas** [comment]
To znamená, že ještě není nasazena nová verze, která s tímto elementem již počítá  nebo po vložení workflow.xml nebyl Proarc restartován

**Comment by nezbedova** [comment]
@SykoraLukas Děkuji. Zrestartujeme.

**Comment by SykoraLukas** [comment]
Ještě tedy, o jakem validatoru mluvite? ProArc má validator uvnitř, tam je tato změna ošetřena.

**Comment by nezbedova** [comment]
O souboru RDflow_validator_2018.xsd se kterým vždy porovnávám novou verzi RDflow, abych každou chybku neřešila až po nasazení.

**Comment by SykoraLukas** [comment]
aha, mohla byste mi tedy tento soubor zaslat? Upravím vám ho tak, aby nová změna počítala s verzí workflow.

**Comment by nezbedova** [comment]
Bylo zde na Githubu, ale nemohu ho najít. Posílám ho @SykoraLukas emailem. Nový soubor prosím přidat k RDflow. https://github.com/proarc/proarc/wiki/RDflow Děkuji.

**Comment by SykoraLukas** [comment]
nová verze je na [githubu](https://raw.githubusercontent.com/proarc/proarc/master/proarc-common/src/main/resources/cz/cas/lib/proarc/common/workflow/profile/workflow.xsd)

Link doplněn i do konfigurace workflow.xml

**Comment by nezbedova** [comment]
@SykoraLukas Nasazeno a nevidím. Můžete mi, prosím, napsat, kde to má být vidět?

**Comment by SykoraLukas** [comment]
Z jádra ProArcu toto videt neni. Musí se to dodělat do nového klienta. Ale pokud za url adresu doplníte /rest/v1/info tak to uvidíte v parametru `rdflowVersion`

![image](https://user-images.githubusercontent.com/27210823/134654019-69d0e2c7-0949-42d7-b2cb-9ea17f072544.png)


https://proarc.inovatika.dev/api/rest/v1/info

**Comment by nezbedova** [comment]
Dost mi to trvalo. Přidávám sem ukázku pro příště.
Děkuji

![obrazek](https://user-images.githubusercontent.com/13831946/134655019-73196015-3f45-4a56-bc0a-00c0a1110278.png)


![obrazek](https://user-images.githubusercontent.com/13831946/134655059-a54d2dac-56bf-4a8d-a099-258169db6bd5.png)

**Comment by SykoraLukas** [comment]
Vím, že toto není ideální řešení. Bohužel do sekce "O Proarcu" toto nedostaneme.

Mám zkusit vymyslet nějaké řešení do workflow, kde by to bylo v podobě tlačítka, které by nic nedělalo?

**Comment by nezbedova** [comment]
Není to ideální, ale je to funkční. Zatím bych to nechala. Jsou důležitější věci. 
Děkuji

**Comment by nezbedova** [comment]
Návod přidám do dokumentace k v. 3.7.1

Navrhuji zavřít.

**Comment by nezbedova** [comment]
V novém klientovi se zobrazuje pěkně:
![obrazek](https://user-images.githubusercontent.com/13831946/135211142-55f27da0-2521-41fd-8fc8-1e7daa2841d0.png)

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
