### ISSUE TITLE
Importy v MZK: vytvořit speciální importní profil

### ISSUE THREAD

**Issue by zabak** [proarc/proarc#1357]
Kvůli urychlení procesu importu (aby netimeoutoval u velkých dokumentů) jsme vytvořili předimportní skript, který generuje jp2 (přípona jp2), OCR, ale i thumbnail a preview obrázky (přípony .thumb.jpg a .preview.jpg). Potřebujeme pro tuto variantu importu vytvořit nový importní profil vedle stávajícího.

**Comment by ZdenkaSera** [comment]
@zabak Není tohle vzhledem k verzi k uzavření?

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, není to k zavření? Děkuji.

**Comment by ZdenkaSera** [comment]
@erikamirova Vzhledem ke štítku "k testu" a releasu odebírám návrh na rozšíření.

**Comment by ZdenkaSera** [comment]
@zabak @erikamirova Prosím, není tohle k uzavření? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera ano, je :)
