### ISSUE TITLE
Importy v MZK: priority importních procesů

### ISSUE THREAD

**Issue by zabak** [proarc/proarc#1358]
Upravit (konfigurovatelně) zařazování do fronty importů tak, že nově zadané importy se zařadí hned za už běžící import. Cílem je, aby se ručně zadané importy doskenů dostaly před rozsáhlejší fronty automaticky generovaných iportů.

**Comment by ZdenkaSera** [comment]
@zabak @erikamirova Prosím o uzavření, pokud souhlasíte s návrhem na ně. Děkuji.

**Comment by zabak** [comment]
Zavírám, řeší se v jiném issue
