### ISSUE TITLE
Reindexace: vyšší inteligence procesu

### ISSUE THREAD

**Issue by zabak** [proarc/proarc#1360]
proces reindexace je problematický ve vztahu k fedoře,  mulgara je problém - občas nestíhá. Pokud se reindexace nepovede, ProArc se stránku která selhala pokouší ještě 10x reindexovat, pak ale skončí. Z hlediska operátora je nutné zadávat reindexaci po 70 nebo ještě podstatně méně stranách. Při 600 stránkovém svazku to už je hodně nepříjemné. Dalo by se spouštění reindexace nějak lépe automatizovat? Nasimulovat odeslání dokumentu na reindexaci po malých částech?

**Comment by pavelkocourek** [comment]
Proces reindexace se muže logovat do správy procesů (kdo, co, stav)

**Comment by erikamirova** [comment]
@zabak toto už je podle mě vyřešeno, reindexace v novém rozhraní funguje správně
