### ISSUE TITLE
Správa procesů

### ISSUE THREAD

**Issue by zabak** [proarc/proarc#1361]
Umožnit sledování exportních, reindexačních i importních procesů operátorem. Možnost zastavení resp. ukončení běžících procesů, zrušení naplánovaných procesů, přehled o výsledku dokončených procesů (proč zhavarovaly apod.)

**Comment by ZdenkaSera** [comment]
@erikamirova V tabulce k rozvoji jste zmínila issues 16 a 30 - tím jste měla na mysli řádky v tabulce a jde o tato issues? D+kuji.

- [Importy v MZK: priority importních procesů #1358](https://github.com/proarc/proarc/issues/1358)
- [Funkce na zobrazení fronty běžících procesů při importu #5](https://github.com/proarc/proarc-client/issues/5)

**Comment by ZdenkaSera** [comment]
Jedná se o další funkce ve správě importů.

**Comment by ZdenkaSera** [comment]
@zabak Issue s dovolením zavírám.
