### ISSUE TITLE
RDflow - nelze zrušit "nadzáměr"

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1362]
Pokud chci zrušit Záměr, pod kterým jsou Podzáměry, tak nejprve zruším Podzáměry. To jde. Když pak chci zrušit "nadzáměr", tak to nejde, objeví se hláška:

![obrazek](https://user-images.githubusercontent.com/13831946/127317389-ba4a007b-2c26-4560-8f1f-7aef58866eb7.png)

Vyzkoušeno v KNAV i v Inovatice.
Prosím o opravu. Do té doby doporučuji  u "nadzáměru" změnit název na "Ke zrušení", aby se to nemotalo mezi otevřené.

**Comment by nezbedova** [comment]
Po nastavení Zrušeno u Podzáměrů se automaticky zruší jednotlivé úkoly.
Horní úroveň se chová stejně jako záměr založený z monografie. Nejde zrušit. Musí se po jednom postupně zrušit jednotlivé úkoly. Pak se automaticky objeví Stav. Zrušený. u horní úrovně.

**Comment by SykoraLukas** [comment]
Opraveno.

**Comment by nezbedova** [comment]
Funguje. Děkuji. Navrhuji k uzavření.
