### ISSUE TITLE
NDK Periodikum - chybí element mods:start

### ISSUE THREAD

**Issue by eliasskrd** [proarc/proarc#1363]
Pěkný den,
dle vyjádření Národní digitální knihovny nejsou balíčky NDK Periodikum validní. Na úrovni stránky v prvním elementu mods:part by měl patrně být element mods:extend a v něm element mods:start, odpovídající obsahem elementu dc:coverage:

"Na úrovni PAGE nie je prítomný element mods:start. Čo samo o sebe chyba nie je, pretože je len subelementom mods:extent v prvom mods:part, ktorý povinný nie je. Lenže v DC pak uvádzate pole dc:coverage a to sa mapuje práve z mods:start – tj. v DC máte niečo, čo nemá alternativu v MODS. Preto by som doporučila mods:start to dát doplniť."

Detailně by měla umět vysvětlit paní Beňačková (Miroslava.Benackova[zavináč]nkp[tečka]cz), autorka výše citované instrukce.
Bez uvedeného elementu data nebudou v NDK akceptována, nejsme tedy schopni zpracovat  digitalizaci pro VISK 7.

děkujeme za opravu, 
Eliáš Škrdlant
Knihovna Antonína Švehly

**Comment by SykoraLukas** [comment]
Děkuji za upozornění, vydám v příští verzi.

**Comment by SykoraLukas** [comment]
Připraveno do verze 3.7

**Comment by eliasskrd** [comment]
Dobrý den,
u exportu do NDK PSP Periodikum patrně stále chybí Národní digitální knihovnou požadovaný element ‚ mods:start ‘.
Přikládám současnou podobu exportu elementu PAGE. V prvním elementu mods:part by měl být zřejmě element  mods:extent a v něm mods:start ?
Jak prosím řešit tento nedostatek? 
děkuji 
eliáš škrdlant
KAŠ
--------------------------------

<mets:dmdSec ID="MODSMD_PAGE_0001">
        <mets:mdWrap MIMETYPE="text/xml" MDTYPE="MODS" MDTYPEVERSION="3.6">
            <mets:xmlData>
                <mods:mods ID="MODS_PAGE_0001" xmlns:foxml="info:fedora/fedora-system:def/foxml#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                    <mods:genre type="normalPage">page</mods:genre>
                    <mods:identifier type="uuid">13863e4a-7063-4a09-b2af-bbb9f06cf5de</mods:identifier>
                    <mods:part type="normalPage">
                        <mods:detail type="pageNumber">
                            <mods:number>85</mods:number>
    </mods:detail>
  </mods:part>
                    <mods:part>
                        <mods:detail type="pageIndex">
                            <mods:number>1</mods:number>
    </mods:detail>
  </mods:part>
</mods:mods>
            </mets:xmlData>
        </mets:mdWrap>
    </mets:dmdSec>
    <mets:dmdSec ID="DCMD_PAGE_0001">
        <mets:mdWrap MIMETYPE="text/xml" MDTYPE="DC">
            <mets:xmlData>
                <oai_dc:dc>
                    <dc:coverage>85</dc:coverage>
                    <dc:identifier>uuid:13863e4a-7063-4a09-b2af-bbb9f06cf5de</dc:identifier>
                    <dc:type>model:page</dc:type>
                </oai_dc:dc>
            </mets:xmlData>
        </mets:mdWrap>
    </mets:dmdSec>

**Comment by SykoraLukas** [comment]
Problém je v tom, že mods i DC se vytváří přímo při popisu. Proto existují 2 možnosti:
- U nově tvořených stránek se to již vytváří v pořádku.
- U stránek vytvořených v dřívějších verzích je nutné stránky přeuložit. Buďto se to dá udělat ručně u každé stránky a nebo pokud máte roli administrátora, tak je možné kliknout na číslo/ročník/svazek/přílohu, které chcete exportovat a na liště nahoře se zobrazí tlačítko administrace. Tam je funkce update NDK stran. Výsledkem funkce je přeuložení všech stran, které vybraný model obsahuje.

**Comment by eliasskrd** [comment]
Dobrý den,
rozumím, zde je třeba přeuložit.
Již funguje dobře, děkujeme moc!!!!!!!!

**Comment by SykoraLukas** [comment]
Super, děkuji za informace. Mohu tedy toto issue uzavřít?

**Comment by eliasskrd** [comment]
Myslím, že ano… ještě tedy pošlu do NDK, a uvidí se, jeslti jim to vyhovuje – takže jeslti s tím počkáte pár dní, než se ověří, také možné… záleží na vás.

Díky, ProArc je super!

Eliáš Škrdlant
kač

**Comment by SykoraLukas** [comment]
Rozumím, počkáme.

**Comment by eliasskrd** [comment]
tak element 'mods:start' se generuje, avšak pouze, když Číslo stránky má číselnou hodnotu. Když je hodnota řetězec (např. [1] pro nečíslovanou stránku), ProArc hodí při exportu do NDK PSP chybu:
Unable to parse start-end intofrom mods
 java.lang.NumberFormatException: For input string: "[1]"

**Comment by SykoraLukas** [comment]
U monografie myslíte model Svazek monografie? Ve specifikaci jsem nic takového nenašel. Pokud myslíte strany pro NDK monografii, tak tam by to rovněž mělo být již hotovo. ProArc nerozlišuje strany pro Periodikum a pro Monografii.

**Comment by eliasskrd** [comment]
tak to je dobrá zpráva! přegeneroval jsme monografii, a element mods:start je opravdu přítomen, děkujeme!

Ale řešíme jinou věc. V elementu mods:start by mělo být totéž, co v elementu mods:number. Ale nyní se nám objevuje např.
<mods:part type="blank">
<mods:detail type="pageNumber">
<mods:number>[1a]</mods:number>
</mods:detail>
-<mods:extent unit="pages">
<mods:start>1</mods:start>
</mods:extent>
</mods:part> 

tj. příjdeme v elementu mods:start  o hranaté závorky a písmeno malé 'a'. Nevím, jestli je to záměr, ale podle specifikace tam má být totéž, co v mods:number - strana 61.  https://old.ndk.cz/standardy-digitalizace/DMFperiodika_18_final.pdf , i mně to teď přímo potvrdili z NDK. 
A naopak element DC:coverage se nemá opakovat (teď je u stránky dvakrát ) a má obsahovat opět totéž, co mods:number a mods:start , tj. ve výše uvedeném příkladu tam má být opět  [1a]

děkujeme!

**Comment by SykoraLukas** [comment]
Ano, toto byl záměr. Moc děkuji za upozornění. Co jsem nyní zjistil, tak se změnila definice pro pole start. Dříve to mohla být jen číselná hodnota. Nově to smí být jakákoli textová hodnota. Opravím to a vydám s příští verzi (cca příští týden).

**Comment by eliasskrd** [comment]
Rozumím. to je možné, dřívější specifikaci jsme neznal. Rozhodně moc děkujeme, snad to tím bude již vyřešeno.

**Comment by eliasskrd** [comment]
Děkujeme, skvělé! Změna bude tedy v dalším releasu? Kdy asi prosím můžeme očekávat?

**Comment by ZdenkaSera** [comment]
@eliasskrd Na schůzce jsme se dohodli, že je zapotřebí projít a pokud možno uzavřít issues k testu, zvláště z dřívějších verzí. Prosím, je toto k uzavření?

**Comment by eskrdlant** [comment]
Ano, vyřešeno, možno uzavřít. Děkujeme.

**Comment by ZdenkaSera** [comment]
@eskrdlant Děkuji za rychlou reakci a uzavírám.
