### ISSUE TITLE
MIX - dotaz

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#1365]
Mám dotaz ohledně jednoho elementu v MIXu v NDK balíčku. Myslím, že už jsme to někde řešili, ale nemůžu to dohledat. Jde o element 'mix:ReferenceBlackWhite', který není ve standardu, takže na něj upozorňuje validátor, ale není to mega červená chyba. Jen by mě zajímalo, kde se tam ten element vzal? ProArc ho asi jen z něčeho převzal, ne? 
Díky za odpověď

**Comment by SykoraLukas** [comment]
ProArc tento element nikde nevyplňuje. Tedy nejspíše je to vyčtená informace z MIXU originálního Tiffu. Pokud tento element nebude vyplněn v mixu originálního Tiffu, tak tak následně nebude ani v NDK balíčku.

**Comment by krizovj** [comment]
Oukej, díky za odpověď.
