### ISSUE TITLE
Technická metadata - skrýt verze 3.7

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1366]
Skrýt tlačítko Technická metada v Editory

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, tohle je podle mého vyřešené - můžeme to uzavřít?

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Ano, zavřít prosím.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna 👍

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Toto jsme zavřeli, protože v 3.7.1 to bylo odstraněné, ale ve 3.7.3 to tlačítko zase je.....

**Comment by SykoraLukas** [comment]
Kde přesně se to objevuje? Můžu poprosit o screenshot?

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Lukáši omlouvám se, překoukla jsem se. Odvolávám :)
