### ISSUE TITLE
Export původních skenů

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1368]
Navrhuji, aby výstup Export původních skenů vypadal následovně:
 - Tiff (to teď je)
- Adresář - název uuid nadřazeného objektu
- název souboru = 4 místné číslo indexu strany - tj např. 0001.tif - ještě navrhuji variantu, kdy by v prefixu byl kód uživatele - např. As1456_0001.tif
@nezbedova Prosím Martino, okomentuj to, jestli máš lepší nápad a kterou variantu bys případně doporučila,

**Comment by nezbedova** [comment]
Mně by se líbila varianta surových skenů z NDK balíčku. @SykoraLukas šlo by to?

raw_page_0001_da6a36c2-6154-458f-84b5-e7659e2a4b50.tif

**Comment by SykoraLukas** [comment]
Ano, jdou obě varianty.

**Comment by nezbedova** [comment]
Prosím ostatní knihovny, aby se k tomu vyjádřily. Za KNAV preferujeme 
raw_page_0001_da6a36c2-6154-458f-84b5-e7659e2a4b50.tif

**Comment by luckajirku** [comment]
Nám je to asi jedno - nepoužíváme, a neplánujeme používat.

**Comment by SmejkalovaAnna** [comment]
Já souhlasím s Martiny variantou, můžete to prosím dát do další verze? díky

**Comment by SykoraLukas** [comment]
Jen bych zachoval princip názvu složky. Nyní je pid.RAW, nově bych převedl na raw_pid, tak aby to melo stejnou podobu jako kramerius, archive, atd ...

**Comment by SmejkalovaAnna** [comment]
Klidně, souhlasím, může tak být.

**Comment by SykoraLukas** [comment]
Do další verze ne, zařazuji to na konec seznamu issue, co se mají udělat. Nyní je seznam určen tabulkou z hlasování.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Lukáši mám dotaz, zase jsem narazila na jednu knihu, kde by se nám tato úprava hodila, jak moc složité by to bylo udělat do nějaké blízské verze?

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, myslím, že to co dneska řešíš, je popsáno tady[ #1417](https://github.com/proarc/proarc/issues/1417)
@SykoraLukas Pro info

**Comment by SykoraLukas** [comment]
@SmejkalovaAnna co přesně potřebuješ? Pochopil jsem to tak, že chceš vyexportovat původní skeny s názvem pidu a pak je naimportovat zpět, tedy nahradit data u stávajících stran. Je to tak?

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Prosím, zkus to - podle mého ten export funguje ok, ale je třeba vyzkoušet další práci s těmi exportovanými skeny . Díky

**Comment by SmejkalovaAnna** [comment]
Funguje hezky, v názvu je i vlastně index, takže jdou stránky hezky za sebou. Super, já jsem spokojená.

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
