### ISSUE TITLE
Failed to create digital object

### ISSUE THREAD

**Issue by isenkyr** [proarc/proarc#1369]
Dobrý den,

obracím se na vás s problémem ohledně tvorby objektu NDK Periodikum, kdy systém hlásí chybu Failed to create digital object. uuid{0} object already exists. Objekt s daným uuid jsem vytvořil a pak následně smazal a když se snažím objekt vytvořit znovu, tak dostávám uvedenou hlášku. Existuje nějaké řešení tohoto problému?

**Comment by SykoraLukas** [comment]
K úplnému smazání musíte být superAdmin. Klasický user smí dát objektu jen příznak smazáno. 

Pokud superAdmin jste a chcete objekt smazat z uložiště, musíte při mazání zakliknout volbu 'Smazat trvale'.
![image](https://user-images.githubusercontent.com/27210823/132330007-482a7f15-34ca-4f40-a5bb-719d29099331.png)


V současné situaci je jen jedno řešení. Musíte se přihlásit jako SuperAdmin, nahoře v hledání máte možnost hledat ve smazaných. objektech.
![image](https://user-images.githubusercontent.com/27210823/132330168-623f5abc-71cb-4a6d-956f-577694bebcfd.png)
Poté je potřeba objekt vyhledat a smazat ho se zakliknutou volbou 'Smazat trvale'

**Comment by isenkyr** [comment]
Dobrý den,

děkuji vám za rychlou odpověď. Účet superAdmin mám, ale nevidím možnost Hledat ve smazaných?

**Comment by SykoraLukas** [comment]
Ještě teda otázka, jakou máte verzi aplikace?

**Comment by isenkyr** [comment]
Verze 3.4

**Comment by SykoraLukas** [comment]
Aha, tak pak je možné, že tato verze to ještě nepodporovala. Zkuste prosím přejít na aktuální verzi.

**Comment by isenkyr** [comment]
Existuje nějaký jednoduchý způsob jak udělat update proArc na aktuální verzi?

**Comment by SykoraLukas** [comment]
To není, podle kodu by asi mělo stačit jít na verzi 3.5.18 a pak na verzi 3.7. Ale lepší by bylo jít po menších krocích.

**Comment by isenkyr** [comment]
Dobrý den,

ještě se chci prosím zeptat od jaké verze proArcu je podporován standard 1.7 a 1.8 pro periodika.

Děkuji

**Comment by SykoraLukas** [comment]
Nevím od které, ale ve verzi 3.6.3 už by měla být podporována 1.7 a 1.8 je víceméně jen úprava povinností.

**Comment by isenkyr** [comment]
Dobrý den, prosím ještě o radu. Nyní jsem se setkal s proArc viz screenShot. Potřeboval bych vytvořit pod titulem periodika ročník, pod ročníkem výtisk, ale nemohu přijít na to jak? Zkusil by jste mě navést?
![obrazek](https://user-images.githubusercontent.com/19608475/133401325-62952cd0-0b2e-47c2-a9a3-e5470f0a599c.png)

**Comment by SmejkalovaAnna** [comment]
@isenkyr kleplněte na liště v levé části na ty tri čárky - Režim procházení - a podtím je symbol +  vytvořit nový objekt

**Comment by isenkyr** [comment]
Dobrý den,

děkuji za odpověď. Kliknul jsem na režim procházení a žádné plus nevidím.
![obrazek](https://user-images.githubusercontent.com/19608475/133407415-eb4341dc-16b4-4310-b1e2-361faf72295e.png)

**Comment by luckajirku** [comment]
> Dobrý den, prosím ještě o radu. Nyní jsem se setkal s proArc viz screenShot. Potřeboval bych vytvořit pod titulem periodika ročník, pod ročníkem výtisk, ale nemohu přijít na to jak? Zkusil by jste mě navést?
> ![obrazek](https://user-images.githubusercontent.com/19608475/133401325-62952cd0-0b2e-47c2-a9a3-e5470f0a599c.png)

jinak tohle patří do nového klienta - možná fajn zpětná vazba pro @honza-rychtar, nakolik je to přepínání mezi režimy uživatelsky přívětivé a jasné...

**Comment by SmejkalovaAnna** [comment]
@isenkyr Aha, teď na to koukám, Vy máte jinou verzi klienta než já.... Vy to tam nemáte..... přepněte si do starého klienta, ten nový ještě není pro práci ideální.....

**Comment by isenkyr** [comment]
Jak se přepnu do starého klienta? Prosím.

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas ?

**Comment by SykoraLukas** [comment]
Z nového klienta se na starý přepnout nedá.

Pokud pracujete s novým klientem a potřebujete školení, tak mě prosím kontaktujte mailem.

Jinak navrhuji toto issue uzavřít, protože už se nejedná o problémy ProArcu ani o návrhy na rozšíření.

**Comment by isenkyr** [comment]
Na jaký email mám napsat?

**Comment by SykoraLukas** [comment]
Napište mi na mail sykora.lukas@email.cz.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
