### ISSUE TITLE
Periodika - nefunguje export Crossref/CEJSH

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1376]
Ve verzi **3.7** nefungují exporty pro Crossref/CEJSH, logy dávám do přílohy. Předem děkuji za opravu.

[proarc_export_status_CEJSH.log](https://github.com/proarc/proarc/files/7195250/proarc_export_status_CEJSH.log)
[proarc_export_status_CROSSREF.log](https://github.com/proarc/proarc/files/7195251/proarc_export_status_CROSSREF.log)
.

**Comment by SykoraLukas** [comment]
Pošlete mi prosím tento dokument jako archivní balík. Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas dle domluvy jsem místo archivu chtěla poslat K4, ale ani ten nešel udělat - error_log k titulu exportovanému pro CEJSH přikládám. Neměl by ale být problém v datech, je to titul. který se k CEJSH testu použil i v minulosti.
[proarc_export_status.log](https://github.com/proarc/proarc/files/7202491/proarc_export_status.log)

U jiného titulu se podařilo spustit export pro CEJSH, výsledkem ale je pouze adresář a v něm přiložený ok-status, data se nevyexportovala..
[proarc_export_status.log](https://github.com/proarc/proarc/files/7202507/proarc_export_status.log)

**Comment by PetrKotynek** [comment]
přikládám konfig, logy a kus waru Petr Kotýnek
[exp.zip](https://github.com/proarc/proarc/files/7208202/exp.zip)
k

**Comment by SykoraLukas** [comment]
Odpovězeno mailem panu @PetrKotynek, nejspíše se jedná o špatně nakonfigurovanou cestu ke katalogu.

**Comment by PetrKotynek** [comment]
export.cejsh_crossref.journals.path=${proarc.home}/journalsInfo.xml
a výsledek je:

[proarc_export_status_crossref.log](https://github.com/proarc/proarc/files/7217457/proarc_export_status_crossref.log)
[proarc_export_status_cejsh.log](https://github.com/proarc/proarc/files/7217458/proarc_export_status_cejsh.log)

změnil jsem na 
export.cejsh_crossref.journals.path=/home/proarc-test/work_data/journalsInfo.xml
a čekám na další kolo Petr

**Comment by PetrKotynek** [comment]
Tedy zadna moc zmena,
[localhost_access.log](https://github.com/proarc/proarc/files/7217528/localhost_access.log)
 
[fedora.log](https://github.com/proarc/proarc/files/7217529/fedora.log)
[proarc.2021-09-23.log](https://github.com/proarc/proarc/files/7217532/proarc.2021-09-23.log)

PK

**Comment by SykoraLukas** [comment]
Prosím zkuste opravu konfigurace. Linuxový server bere cestu relativně, proto je potřeba cestu k souboru upravit na tutu:

export.cejsh_crossref.journals.path=file:///${proarc.home}/journalsInfo.xml

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkujeme, o to poprosím pana Kotýnka @PetrKotynek. 

Na konci týdne jsem zkoumala xml  s definicí pro jednotlivé časopisy a vyšla mi z toho prosba: jakým způsobem se v kódu hledá odesílaný časopis? Tj. které identifikátory a v jakém pořadí se v PA hledají, případně jaké chyby v datech jsou K.O. kritériem při výběru? Moc děkuji.

**Comment by SykoraLukas** [comment]
Hledá se to vždy podle ISBN, bere se první nález.
Co jsou terminátory pro jednotlivé exporty doplním.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkuji. Dotaz byl motivovaný tím, že v xml jsou někde uvedena uuid  - byla bych čekala, že by mohla např. ukazovat na nejvyšší úroveň časopisu, Ale to někde platilo, jinde bylo uuid, které v PA vůbec není (jde o data z produkce u časopisů jejichž odesílání bez problémů funguje). Takže uuid tam nejspíš nehraje roli ...

**Comment by PetrKotynek** [comment]
Změněno dle doporučení na 2x test serverech, PK

proarc-test@proarc-ozc:
#export.cejsh_crossref.journals.path=${proarc.home}/journalsInfo.xml
#export.cejsh_crossref.journals.path=/home/proarc-test/work_data/journalsInfo.xml
export.cejsh_crossref.journals.path=file:///${proarc.home}/journalsInfo.xml

proarc-test@proarc:~/work_data$ ls
journalsInfo.xml  proarc.cfg.old          proarc.cfg.05_20_1    users                workflow.xml.old.03  workflow.xml.23_9
journalsInfo.10   proarc.cfg.old1         proarc.cfg.07_06      workflow.xml         workflow.xml.old.04  workflow.xml.24_8
journalsInfo.11   proarc.cfg.old2         proarc.cfg.15_11      workflow.xml.bak     workflow.xml.orig
proarc.cfg        proarc.cfg.strahov      proarc.cfg.16_05      workflow.xml.new1    workflow.xml.0924
proarc.cfg.bak    proarc.cfg.template     proarc.10_9           workflow.xml.old     workflow.xml.0924_1
proarc.cfg.jan9   proarc.cfg.04_feb_2021  profile.archive.cfg   workflow.xml.old.01  workflow.xml1.bak
proarc.cfg.may    proarc.cfg.05_20        profile.oldprint.cfg  workflow.xml.old.02  workflow.xml.2

#proarc-test@proarc

# Cesta k souboru journalsInfo.xml s informacemi pro CROSSREF and CEJSH export.
#export.cejsh_crossref.journals.path=${proarc.home}/journalsInfo.xml
export.cejsh_crossref.journals.path=file:///${proarc.home}/journalsInfo.xml

**Comment by ZdenkaSera** [comment]
Děkuji oběma, už to částečně chodí 
1. CEJSH - export se na testu OZČ podařil a jeho obsah vypadá dobře (příští týden požádám o přetestování K. Neradovou). 
2. Crossref znovu s chybou, log připojuji a prosím @SykoraLukas o tip, kde může být problém. Děkuji.
[proarc_export_status.log](https://github.com/proarc/proarc/files/7253228/proarc_export_status.log)
.

**Comment by PetrKotynek** [comment]
Ještě logy PK
[29_exp.zip](https://github.com/proarc/proarc/files/7257365/29_exp.zip)

**Comment by PetrKotynek** [comment]
Abych to doplnil a upřesnil,
toto je tedy posledni chyba: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<exports xmlns="http://proarc.lib.cas.cz/xml/common/export/v1/">
    <export>
        <begin>2021-09-29T17:19:47.007+02:00</begin>
        <end>2021-09-29T17:20:03.441+02:00</end>
        <status>FAILED</status>
        <inputPid>uuid:8854c0d0-a806-4c16-9ac7-61cee1942dc9</inputPid>
        <error message="Validation errors!" pid="uuid:8854c0d0-a806-4c16-9ac7-61cee1942dc9">Column:18 Line:6 cvc-minLength-valid: Value '' with length = '0' is not facet-valid with respect to minLength '1' for type '#AnonType_depositor_name'.
Column:18 Line:6 cvc-type.3.1.3: The value '' of element 'depositor_name' is not valid.
cz.cas.lib.proarc.common.export.ExportException: Validation errors!
	at cz.cas.lib.proarc.common.export.crossref.CrossrefBuilder.createPackage(CrossrefBuilder.java:164)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportPackage(CrossrefExport.java:125)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.exportImpl(CrossrefExport.java:95)
	at cz.cas.lib.proarc.common.export.crossref.CrossrefExport.export(CrossrefExport.java:55)
	at cz.cas.lib.proarc.webapp.server.rest.ExportResource.newCrossrefExport(ExportResource.java:507)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

šel jsem po tomto uuid:
8854c0d0-a806-4c16-9ac7-61cee1942dc9 viz příloha

v jedné rels-ext jsem našel issn
<mods:identifier type="uuid">4035ee25-6cf5-4b66-830f-c8dbce1a29d2</mods:identifier>
<mods:identifier type="issn">0044-4812</mods:identifier>

jelo to v této konfiguraci viz příloha

A na distribučním  PA 3.7.1 , takže zbytek je v proarc-common-3.7.1.jar .

[8_12.zip](https://github.com/proarc/proarc/files/7327443/8_12.zip)

Petr Kotýnek

**Comment by ZdenkaSera** [comment]
Ve verzi 3.7.2. jsme po úpravě dat otestovali jako ok, issue zavírám.
