### ISSUE TITLE
Po updatu na 3.7 v periodiku nejsou vidět některé ročníky/čísla/strany

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#1378]
Máme v ProArcu periodikum (Švanda dudák, cnb001626935), které zpracováváme delší dobu (od 3-5/2020 doteď), postupně děláme opravy a doplňujeme chybějící strany. Hrabalo se do toho tedy v různých verzích ProArcu (od 3.5.13 přes 3.6, pak 3.6.1 až po současnou 3.7). 
A teď **po updatu z 3.6.1 na 3.7 se nám přestaly ve struktuře ukazovat některé ročníky/čísla/strany**.
Na co jsme zatím přišli - ty ročníky, do kterých se sáhlo naposledy loni (5-6/2020), vidět nejsou. Ty, které se dělaly letos, vidět jsou. Další věc jsou čísla, která se dělala dřív a v novější verzi se do nich doplňovaly opravené strany - a tam to vypadá, že místo toho, aby se ty chybějící strany jen doplnily k tomu zbytku, tak jsou v těch číslech teď jen ty samotné nově doplněné strany a zbytek úplně zmizel, resp. není vidět.

**Comment by SykoraLukas** [comment]
Má někdo podobný problém? @nezbedova @ZdenkaSera @kerschfilip @fstepanovsky? Jde mi o to zjistit, jestli je to problem jedne instance (nejspíše souvisí s daty nebo instalací) nebo je to problem aplikace.

**Comment by ZdenkaSera** [comment]
Zatím jsem v testu KNAV na 3.7 nenašla příklad, kde by u dříve zpracovaného periodika chyběla/nezobrazovala se část struktury. Přidání strany zatím nevyzkoušeno.

**Comment by luckajirku** [comment]
Jen radši zdůrazním - ty tituly, které se dělaly dříve, a v novějších verzích se do nich nezasahovalo, vypadají i u nás OK. Problém je s tím, kde se v rámci jednoho titulu dávky zpracovávaly postupně v různých verzích ProArcu.

**Comment by SmejkalovaAnna** [comment]
Teď jsem vyzkoušela přidat strany periodiku, co je vytvořené 17.10.2020, a nic mi nikam nezmizelo, všechno tam je, tak jak je.

**Comment by SmejkalovaAnna** [comment]
Opravím se, to moje periodikum bylo vytvořeno v květnu 2019, pak se do toho hrabalo toho 17.10.2020 a pak teď. A sedí to. Připomíná mi to problém pana Světlého s mizejicími stránkami.....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Díky - já nemám v testu svou delší historii, koukala jsme na cizí data z let 2015/2017, kde se něco měnilo v minulosti a vypadají ok.

**Comment by luckajirku** [comment]
A ještě doplním po dalším zkoumání:
- ty opravy, které se dělaly už přímo ve verzi 3.7, jsou v pořádku.
- ty opravy, které se dělaly v době, kdy jsme měli verze 3.6 a 3.6.1, taky vypadají v pořádku.
- a konečně - vypadá to, že **s updatem na 3.7 zmizely strany/čísla/ročníky, které jsme editovali ve verzi 3.5.13**

**Comment by SykoraLukas** [comment]
Super informace, připojím se k vám na server a zkusím zkoumat. Je možné, že to ve verzi 3.6. a 3.6.1 také nebylo vidět?

**Comment by luckajirku** [comment]
Není. Stoprocentně to předtím vidět bylo. Zmizelo to až teď s updatem na 3.7.

**Comment by SykoraLukas** [comment]
OK, děkuji za info

**Comment by luckajirku** [comment]
lukáši, vykoumal jsi prosím tě něco?

**Comment by luckajirku** [comment]
potřebovali bychom to nutně vyřešit, @SykoraLukas, přišel jsi na něco?

**Comment by SykoraLukas** [comment]
Prosím vyzkoušej, mělo by tam být již vše vidět.

**Comment by luckajirku** [comment]
V 3.7.2 to vypadá OK, jen jsme to zapomněli zavřít, takže zavírám.
