### ISSUE TITLE
problém při hromadném převodu na NDK stranu

### ISSUE THREAD

**Issue by eliasskrd** [proarc/proarc#1382]
Když dám do bloku vícero titulů a zvolím Administrace -> 'Převést Stranu na NDK stranu', strany se u titulů nepřevedou, resp. možná ne u všech vybraných. Když zvolím jeden titul, funguje.
Děkujeme!

**Comment by SykoraLukas** [comment]
O tomto se ví, ale není jednoduchá oprava. Je potřeba změnit uložiště. Řešeno v issue #1099 a #1097. Selhává indexace Mulgary při hromadných změnách. Dočasným řešením reindexace/hromadného převodu modelů je postupovat po menších dávkách.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
