### ISSUE TITLE
Je třeba mít možnost přidělit nové URN:NBN pro NDK balíček

### ISSUE THREAD

**Issue by eliasskrd** [proarc/proarc#1384]
scénář: přidělím např. u modelu NDK svazek monografie URN:NBN, vyexportuju, pošlu balíček do NDK. Jsem odmítnut kvůli chybě v metadatech. Podle požadavků NDK je zřejmě třeba metadata opravit, přidělit nové URN:NBN a znova vygenerovat export.
Patrně je potřeba přidat možnost resetovat přidělené URN:NBN (a možná rovnou do resolveru URN:NBN poslat informaci o jeho zneplatnění), a po opravě mít možnost přidělit nové URN:NBN.
Možná by stačila možnost manuálně z formuláře metadat mít možnost dotčené vymazat a uložit?
děkujeme!

**Comment by SykoraLukas** [comment]
Toto nedovoluje resolver. V resolveru se váže URN:NBN na daného registrátora a uuid objektu. Tedy i kdyby ProArc dovoloval smazat URN:NBN tak mu resolver nepřidělí nové URN:NBN, protože pod daným UUID a registrátorem je již něco zaregistrováno.

**Comment by eliasskrd** [comment]
Musím říci, že jsem specifikaci pochopil jinak - https://old.ndk.cz/archivace/Metodika_URNNBN_final_2.1a.pdf, kapitola 14
Následnický dokument (třeba po změně metadat), mám mít patrně nové urn:nbn, ale stejné uuid? Ještě tedy zkusím nastudovat a poptat se kolegů... případně se ozvu.
děkuji

**Comment by eliasskrd** [comment]
Opravdu to tak není, UUIDse nemusí vázat na jedno URN:NBN, v případě chyby např. v titulu či číslování periodika, tak podle https://old.ndk.cz/archivace/Metodika_URNNBN_final_2.1a.pdf, kapitola 14:
"Dojde-li ke změně velkého rozsahu, musí registrátor
deaktivovat záznam digitální dokumentu (kód 200 pro automatizované postupy pomocí API
nebo manuálně pomocí webového rozhraní u jednotlivých záznamů) a registrovat dokument
s novým identifikátorem URN:NBN bez vytváření následnické vazby."

I paní Beňačková (kurátorka resolveru) mi potvrdila, že dokument se stejným UUID může mít přiřazeno nové URN:NBN.

Tj. měla by být možnost přidělit nové URN:NBN, dosavadní nastavit jako neplatné, ideálně (?) na API resolveru poslat kód 200.
Teď patrně nemám možnost nastavit v ProArc nové URN:NBN, takže při chybě bychom museli vyrábět celý balíček znova, což je jako při psaní knihy po překlepu muset vždy začínat od začátku :(

**Comment by eliasskrd** [comment]
@SykoraLukas 
Dobrý den,
zaregistroval jste prosím připomínku? Nevím, jestli to označení za Neplatné neblokuje odesílání komentářů... mám kdyžtak zadat jako nové issue?

Možnost přidělit nové URN:NBN je podle naší zkušenosti spíše kritická feature, dejte prosím vědět, jeslti bude možné ProArc takto upravit. Ideálně před 10. prosincem, kdy odevzdáváme digitalizaci pro VISK :)
Když se přiděluje je potřeba vymazat UUID u původního záznamu v resolveru. Asi by šlo přes API? Nebo jeslti by 
Varianta: "při chybě v metadatech předělat celý balíček" je příšerná, znamená to místo několika kliknutí klikat třeba mnoho hodin, či dnů :( proto se přimlouvám, abyste toto vyřešili, a ušetřili nás :)

Cituji paní Beňačkovou, kurátorku resolveru URN:NBN:
"Čo sa týka zmeny UUID, tak tam je to na vás, môžete si vybrať či dáte nové UUID nebo zachováte to staré. Niekedy sa necháva pôvodné UUID kvôli odkazom do Krameria, pri zachovaní je ale potom treba vymazat UUID u toho deaktivovaného urn:nbn, pretože resolver kontroluje unikátnosť UUID. Ak sa rozhodnete pre túto možnost, je možné UUID vymazat i přes webové rozhraní.  Alebo môžete prideliť UUID nové, potom sa musí urobiť len úprava v balíčku v hlavnom METS záznamu u identifikátorov. Takže záleží, čo sa Vám viac hodí."

**Comment by SykoraLukas** [comment]
Zásahy do vývoje musí schválit vývojový tým, proto se s tímto prosím připomeňte na příští schůzce, kde se rozhodne jak toto a kdy řešit.

**Comment by ZdenkaSera** [comment]
Vzhledem k založenému issue na řešení komunikace s resolverem  zde navrhuji uzavřít.

**Comment by ZdenkaSera** [comment]
Zavírám vhledem k návrhu na uzavření, který nikdo nerozporoval.
