### ISSUE TITLE
RDflow - nelze zrušit záměr s nezrušenými úkoly

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1387]
V. 3.7.1 - asi to bylo i dříve, jen jsem to nezjistila.

Pokud udělám chybu a založím nový záměr, který nepotřebuji, tak u něj nelze nastavit stav Zrušený, protože jsou pod ním Úkoly ve stavu Připraven. 
Musí se ručně zrušit všechny úkoly. Např. u STT to je 16 položek.

**Comment by nezbedova** [comment]
Tato chyba se vyskytuje i u omylem založených záznamů, kdy se uloží formulář bez tlačítka Uložit.

**Comment by ZdenkaSera** [comment]
@nezbedova @SykoraLukas Slíbila jsem propojit s issue, kde zmiňujeme nechtěně uložené záznamy (tj. dám vytvořit nový objekt, ale pak z něj odejdu bez uložení). Nedaří sem mi issue objevit, tak jen doplňuji: k takto omylem/nechtěně vzniklému objektu se automaticky založí záměr, viz výše.

**Comment by nezbedova** [comment]
Dalším testováním jsem odhalila tyto souvislosti:

Podzáměry založené přes tlačítko Podzáměr zrušit lze.
Ostatní - Nadzáměry a monografie založené přes tlačítko Nový . Zrušit nelze.

Pokud pracujeme ze Záměru:

1) Tlačítko Nový skočí do okna Nový záměr s Katalogem. Stejné jako když se zakládá nový objekt bez záměru. Profil se vybírá z roletky. NELZE ZRUŠIT.

2)Tlačítko Podzáměr nabídne nejdříve Profil, pak přepne do okna Metadat na titul. Zde se musí přepnout do okna Katalog, aby se mohly stáhnout metadata. (nebo vyplnit ručně). LZE ZRUŠIT.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím tě, šlo by něco udělat s touhle starší chybou? Tj. bez ohledu na to, na jakých změnách v RDF se s @nezbedova domluvíte, až se vám podaří sejít. Tohle docela ztěžuje provoz :-) Moc děkujeme.

**Comment by nezbedova** [comment]
Funguje. Děkuji. Navrhuji k uzavření.
