### ISSUE TITLE
Part Number verze: 3.7.1 

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1388]
Ve verzi 3.7.1 je u NDK čísla Part Number s poviností M, ale má být podle standardu MA. Prosím opravit, ale nechat hlášení o nevyplněné položce, jako je to dosud.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Podle mého je tohle hotové - souhlasíš? Díky.

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Beru zpátky, není to změněné úplně.

**Comment by SykoraLukas** [comment]
Takže se to chová tak jak byl požadavek? Změna povinnosti, ale ponechat hlášení o nevyplnění. Můžeme to tedy zavřít?

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko - opravdu si tady představuješ stejnou hlášku, jako byla dříve u pole s povinností M? Protože je hláška  "errorová", zůstává pole vlastně povinné (nebo nevyplníš, ale ukládáš s chybou). Nebylo by zde lepší jen upozornění typu "Uložit partNumber bez hodnoty?" , tj. bez vykřičníku v poli, změnit povahu hlášky jen na upozornění?

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera @SykoraLukas Zdenko, nakonec je mi to asi jedno, ale jestli myslíš, že by to bylo lepší, tak jsem pro. Zdenko rozhodni.

**Comment by SykoraLukas** [comment]
Z hlediska implementace je jednodušší nechat vykřičník, protože o jeho funkcionalu se stará klient. Pokud by měla být hláška, že je nevyplněno partNumber tak by se to muselo validovat na serveru.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky za upřesnění - navrhuji to vzhledem k názoru @SmejkalovaAnna nechat (uzavřít). pokud by to časem někdo rozporoval, můžeme se k tomu vrátit. Děkuji.

**Comment by SykoraLukas** [comment]
Super, díky
