### ISSUE TITLE
v 3.7.1 - Převod NDK Strany na Stranu 

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1389]
Ve verzi 3.7.1 jsem narazil na problém s převodem stran: Ze Strany na NDK Stranu, z NDK Strany na STT stranu a ze STT strany na NDK stranu mi všechno funguje normálně, ale při převodu z NDK Strany na Stranu se objeví neočekávaná chyba:
```
HTTP Status 500 – Internal Server Error
Type Exception Report

Message java.lang.IllegalStateException: Unsupported model: model:page

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: java.lang.IllegalStateException: Unsupported model: model:page
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
Root Cause

java.lang.IllegalStateException: Unsupported model: model:page
	cz.cas.lib.proarc.common.object.oldprint.OldPrintMapperFactory.lambda$get$1(OldPrintMapperFactory.java:54)
	java.util.Optional.orElseThrow(Optional.java:290)
```

**Comment by ZdenkaSera** [comment]
Doplňuji z mailové komunikace - test na "pre-verzi" 3.7.2.
Testovala jsem na:
    NDK svazku monografie
    NDK příloze monografie
    NDK čísle periodika
    STT svazku monografie

Bez problémů byl převod Strany (resp STT strany) na NDK stranu  a zpět - tzn. u všech označených stran odpovídal nastavený typ struktuře xml)
    na úrovni objektu
    při označení jedné strany
    při označení skupiny stran

ALE - celé to má háček: převody nefungují na stranách s římským číslováním, resp. u stran, kde "číslování" neobsahuje arabskou číslici. 
Nejspíše souvislost s issue [#1392](https://github.com/proarc/proarc/issues/1392)

**Comment by ZdenkaSera** [comment]
Otestováno na NDK svazku monografie - je to ok, nenašla jsem zatím protipříklad. @SykoraLukas Díky! 
@kerschfilip Filipe, zavírám, kdybychom někde časem narazili, znovu otevřeme.

**Comment by ZdenkaSera** [comment]
Znovu zavírám, ve verzi 3.7.3 jsme v produktivním používání nenarazili na problém.
