### ISSUE TITLE
Přidání funkce korekce OCR s využitím PERO OCR

### ISSUE THREAD

**Issue by zabak** [proarc/proarc#1393]
Na dnešním workshopu projektu PERO jsme domluvili přidání nového upload API do webové verze PERO OCR https://github.com/DCGM/pero_ocr_web/issues/70 . 

Cílem je umožnit v ProArcu v rámci editace metadat korekce OCR. Workflow: na vstupu se předpokládá dokument včetně OCR (lze vytvořit přes PERO OCR API). Při editaci metadat bude uživateli umožněno přes volbu "vylepšit OCR" předat vybrané stráky do webové verze PERO OCR, tam provést nové OCR (například i s vybráním nového modelu - use case: starý tisk, kde jsou dvě rukopisné stránky - celý se udělá textovým modelem, ty dvě stránky je potřeba udělat rukopisným), ručně opravit výsledek a opravené OCR stáhnout zpět do editovaného dokumentu.  

Další use-case (reálný, z KNAV): digitalizuji staré tisky, OCR titulních listů chci ale mít zcela správně = je potřeba manuální korekce OCR).

Na straně PERO OCR web se vytvoří účet pro danou instalaci ProArcu a každý operátor si tam vytvoří svůj účet.  Při volání API se autentizuje účtem pro tu instanci ProArcu a pošle jako parametr e-mail = login daného operátora a název dokumentu (nebo uuid, čárový kód...) - ten slouží pro orientaci operátora. PERO OCR převezme obrázky a vrátí id úlohy. Do budoucna možná v api přibudou parametry na přímé spuštění OCR (volba modelu apod), zatím ale toto v API nebude. 

Po uploadu vybraných obrázků (a kontrole přes status API, pokud bude existovat na straně PERO OCR) uvidí operátor link do PERO OCR (využije se Id úlohy vrácené při uploadu obrázků). Vedle bude další volba, pro stažení hotových OCR souborů (zase přes Id úlohy). Toto bude zašedlé, dokud nebudou výsledné OCR k dispozici. Operátor se proklikne do PERO OCR, tam spustí OCR dle svých požadavků, provede korekturu a vrátí se do ProArcu, kde vyvolá stažení hotového OCR. To se stáhne a nahradí se jím stávající OCR soubory pro dané stránky.

**Comment by zabak** [comment]
Znovuotevírám, přidám sem volání API pro PERO OCR web:

curl "$SERVER_URL/ocr_api/new_document/test_document/someone@somewhere.com,someone@somewhere.com" --request POST --header "api-key: $API_KEY"   # tohle vrací DOCUMENT_ID, adresy doporučuji zaměnit za skutečné uživatele :)

curl $SERVER_URL/ocr_api/upload_image/$DOCUMENT_ID --request POST --header "api-key: $API_KEY" -F file=@00000003.jpg

curl $SERVER_URL/ocr_api/list_documents --request GET --header "api-key: $API_KEY"

curl $SERVER_URL/ocr_api/document_images/$DOCUMENT_ID --request GET --header "api-key: $API_KEY"

curl  $SERVER_URL/ocr_api/get_results/text/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"
curl  $SERVER_URL/ocr_api/get_results/page/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"
curl  $SERVER_URL/ocr_api/get_results/alto/$DOCUMENT_ID/$IMAGE_ID --request GET --header "api-key: $API_KEY"

curl  $SERVER_URL/ocr_api/delete_document/$DOCUMENT_ID --request POST --header "api-key: $API_KEY"

**Comment by ZdenkaSera** [comment]
7.9. - zde volat PERO bez automaticky spouštěného editoru alta.

**Comment by kerschfilip** [comment]
@zabak @erikamirova na poslední schůzce navrhl @SykoraLukas trochu jiné řešení, než o kterém jsme původně mluvili. Můžete na to kouknout, jestli je to za vás OK?

Nově navrhnuté řešení:
- V ProArcu bude tlačítko na vytvoření nového ALTO/OCR, tím se data pošlou do PERO, 
- z PERA se rovnou vrátí do ProArcu (nebude možné upravovat OCR ve web aplikaci v rámci PERA). 
- Uživatel ale bude moct vstoupit z ProArcu do ALTO OCR editoru (který se vyvíjí při Krameriovi) a upravit si data ručně v něm.

**Comment by zabak** [comment]
Tohle řešení má jedinou navýhodu, ale zato velkou. Není tam jak dát zpětnou vazbu aby se PERO mohlo zlepšovat.

**Comment by SykoraLukas** [comment]
Implementováno. Na Klientovi je potřeba dořešit volání a stavy v procesech.

Nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#pero)

```properties
# (4.1.1) Generator OCR
import.ocr_generator.processor=peroCmd
processor.peroCmd.exec=python3
processor.peroCmd.arg=/opt/pero/pero-ocr.py
processor.peroCmd.timeout=1800000
```

**Comment by ZdenkaSera** [comment]
Do řádku konfigurace "**processor.peroCmd.key=*******" se doplňuje klíč (token) přidělený správcem služby PERO
_Text k doladění/doplnění po lokálních testech v KNAV_
- Funkce se spouští v úložišti nad **jednotlivými** skeny
- Vybraný sken může, ale nemusí mít OCR ani ALTO (tj. lze generovat nové i opravovat stávající datastreamy)
- Fce vždy generuje nový obsah obou datastreamů, tj. případné manuální opravy OCR provedené přímo v ProArcu se přepíší
- Na API Pera se odesílá tiff (resp. ProArc hledá datastream raw; pokud nenajde, použije mastercopy ve fmt jpeg2000 ke konverzi do fmt tiff – odpovídá to např. situaci v MZK, kde se tiffy při importu do ProArcu po konverzích do ostatních potřebných datastreamů "zahazují")
- V Peru se zakládá nová úloha s vlastním id (to poslouží k pojmenování automaticky založeného dočasného podadresáře v /Temp/ProArc/)
- ->> do něj jsou uloženy vytvořené soubory 
- ->> odtud jsou – pokud proces správně skončí – přesunuty do ProArcu a dočasný adresář je smazán
- Pokud by proces selhal nebo se dočasný adresář automaticky nevymazal, smaže se celá temp složka nejpozději při restartu instance ProArcu
- Uživatelsky se do procesu nijak nezasahuje, jeho průběh/statusy lze sledovat ve správě procesů v ProArcu
- 
- 
- **Budoucí možnosti hromadné tvorby OCR/ALTO** (pro knihovny bez vlastního sw na tvorbu OCR, k doplnění starších digitalizovaných dokumentů vytvořených ve formátech bez OCR ...)
- Zavolání API Pera pro celý balík před importem do ProArcu
- - V současné době existuje funkční demoverze - speciální importní profil, kterým se data pošlou do Pera a v druhém kroku importují do PA jako NDK model
- Využití ALTO Editoru zavoláním z ProArcu pro skupinu skenů nebo doplněním přímo v Krameriovi (K7)

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem na inovatice-masteru opravu OCR u tištěného dokumentu - to vypadalo to ok. Pak jsem ale pustila vygenerování OCR k rukopisné straně - tady si Pero neporadilo. Zřejmě bude zapotřebí doladit výběr profilu, spíš jako rozvoj. "Otestováno" až po lokálním testu s exportem a kontrolou alto.

uuid.c32e38b3-5ed7-4398-bb81-da22f196d14a

![image](https://github.com/user-attachments/assets/76badff7-75ba-4e05-802e-392a3aa88efb)

**Comment by zabak** [comment]
Rozhodně je potřeba volit jiný model pro tištěné věci a jiný pro rukopisy.

**Comment by ZdenkaSera** [comment]
> * V ProArcu bude tlačítko na vytvoření nového ALTO/OCR, tím se data pošlou do PERO,
> * z PERA se rovnou vrátí do ProArcu (nebude možné upravovat OCR ve web aplikaci v rámci PERA).

Funkční, otestováno na 4.1.6/2.2.4

Alto editor zde neřešíme, možnost volby modelu v Peru založíme jako návrh na rozšíření.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
