### ISSUE TITLE
Při exportu čísla periodika se nemění signatura u titulu

### ISSUE THREAD

**Issue by eliasskrd** [proarc/proarc#1394]
Podle vyjádření NDK má být v MODSMD_TITLE v elementu  <mods:shelfLocator> stejná signatura, jako v MODSMD_ISSUE v <mods:shelfLocator>. Když dám export celého titulu s vícero ročníky do MODSMD_TITLE v balíčku čísla by se měla propisovat patrně signatura z  daného čísla. Nyní se vezme z metadat titulu, což patrně znemožňuje správný hromadný export. Problém je tedy i při exportu jediného čísla - vezme se signatura z metadat titulu. Jediná možnost je asi manuálně měnit signaturu v metadatech titulu pře exportem každého ročníku, což je dosti nešikovné a zdlouhavé...

**Comment by eliasskrd** [comment]
To máte pravdu… takže myslíte, že podle pravidel NDK je ok exportovat se všemi signaturami uvedenými na úrovni titulu? A kdo by o tom měl rozhodnout? Myslíte, že mám psát paní Beňačkové z NDK a zkusit zjistit, jestli by přecejen nebyla tato varianta (uvedení všech aktuálně digitalizovaných signatur na úrovni titulu periodika) akceptovatelná? Jsem zde nový, nevím, jak situaci řešit…
Děkuji,
eš

**Comment by eliasskrd** [comment]
Tak jsem konzultoval znovu NKD - připustili, že na úrovni titulu je možné vyplnit více signatur oddělených např. lomítkem, i když lepší je mít u titulu stejnou konkrétní signaturu, jako na úrovni čísla. Asi tedy není potřeba upravovat, i když podle NDK takto není ideální.

**Comment by luckajirku** [comment]
Signatury oddělené lomítkem? Stejná signatura u titulu a v čísle je nesmysl. Řekla vám kolegyně z NK taky JAK se to bude chovat na úrovni titulu, když se vám pak v celém titulu třeba 100 svazkových signatur??? V Krameriovi potom NK počítá na úrovni titulu s výpisem všech těch signatur? 
Můžete sem dát odkazy do vašeho katalogu na pár periodik, u kterých tenhle problém máte? Mně pořád totiž není jasné, jakým způsobem tvoříte signatury pro jednotky/svazky a jak vyplňujete pole 910.

**Comment by SmejkalovaAnna** [comment]
Já souhlasím Lucko s Vámi, my to děláme stejně jako vy, výše popsaný způsob kolegyně z NK mi přijde také úplně nesmyslný. My prostě máme na úrovni titulu všechny typy signatur v rozkopírovaném poli, které se u nás u daného titulu vyskytují a pak u jednotlivých výtisků je odmažu a nechám jen tu, ze které je předloha. Takže na úrovni titulu mám např. 3 signatury. U výtisku logicky jednu. Přijde mi to logické.

**Comment by ZdenkaSera** [comment]
@eliasskrd Navrhuji uzavřít - prosím o reakci. Děkuji.

**Comment by SykoraLukas** [comment]
Vzhledem k tomu, že zůstalo přes půl roku bez reakce pana @eliasskrd, uzavírám.
