### ISSUE TITLE
Chyba Exportu k4 ....už ve verzi 3.7.3.. prověřit na 3.7.4

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1402]
Když pustím např. 3 exporty K4 najednou - tři ročníky periodika - tak mi to občas nevytvoří xml soubor úrovně titulu..... nehlásí to chybu ani v PA ani to nevytvoří chybný adresář.... jen je vypsaná chyba v LOgu - přikládám.  Prověřte to prosím na aktuální testovací verzi - 3.7.4. - přikládám LOG
[proarc_export_status.log](https://github.com/proarc/proarc/files/7692663/proarc_export_status.log)

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, neuzavřeme to zatím? Díky.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Zdenko, asi to zavři, ono to souvisí asi s tím, že je to přetížené.... tak to zavři.
