### ISSUE TITLE
v 3.7.3 - Chyba při exportu NDK Čísla

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1410]
Dobrý den, 

ve verzi 3.7.3 se nám nedaří exportovat žádná čísla, ani ročníky periodik, která obsahují eČlánky. Naše poněkud specifická struktura těchto čísel vypadá takhle:
![image](https://user-images.githubusercontent.com/57805328/153160193-0ccaa4aa-3030-47b3-ae5a-bfb9886cee01.png)

Export pro Kramerius vždy skončí s obdobnou chybou:

```
TTP Status 500 – Internal Server Error
Type Exception Report
Message java.lang.IllegalStateException: uuid:887f064a-4c35-11e1-8a24-005056a60003
Description The server encountered an unexpected condition that prevented it from fulfilling the request.
```

Celý chybový výstup: [HTTP Status 500 – Internal Server Error.txt](https://github.com/proarc/proarc/files/8031046/HTTP.Status.500.Internal.Server.Error.txt)

Moc mi z toho není jasné, co se děje. V root Cause je popsáno toto:
```
java.lang.IllegalStateException: uuid:887f064a-4c35-11e1-8a24-005056a60003
cz.cas.lib.proarc.common.export.Kramerius4Export.exportParentPid(Kramerius4Export.java:466)
```
tak je možná problém s exportem FOXML rodičů...  Podle @PetrKotynek není 887f064a-4c35-11e1-8a24-005056a60003 odnikud referencováno. Ve verzi 3.6.x nám ale export fungoval a nic jsme ve struktuře neměnili.

Na obdobný problém jsme u jednoho příkladu narazili i při exportu klasických NDK Čísel se skeny, jinak se to ale týká výhradně těch, které obsahují eČlánky.

@SykoraLukas mohl byste se na to, prosím, podívat. Nevíme jestli je problém v ProArcu, nebo v nějakém našem nastavení. Díky!

**Comment by PetrKotynek** [comment]
Ještě pro upřesnění k 887f064a-4c35-11e1-8a24-005056a60003

dotaz ve formě 
* * <info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003>
má prázdný výstup

dotaz ve tvaru
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> * *
vrací
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#label> "Modern\u00ED d\u011Bjiny: sborn\u00EDk k d\u011Bjin\u00E1m 19. a 20. stolet\u00ED" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#state> <info:fedora/fedora-system:def/model#Active> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/view#lastModifiedDate> "2022-02-04T09:37:09.254Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#createdDate> "2015-12-15T14:38:41.024Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/identifier> "ccnb:cnb000370541" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/identifier> "issn-l:1210-6860" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/identifier> "issn:1210-6860" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/identifier> "uuid:887f064a-4c35-11e1-8a24-005056a60003" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/view#disseminates> <info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003/RELS-EXT> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/view#disseminates> <info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003/DC> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/view#disseminates> <info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003/BIBLIO_MODS> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#hasModel> <info:fedora/fedora-system:FedoraObject-3.0> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#hasModel> <info:fedora/model:ndkperiodical> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/model#ownerId> "melichova" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/title> "Modern\u00ED d\u011Bjiny : 2009-: \u010Dasopis pro d\u011Bjiny 19. a 20. stolet\u00ED" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/title> "Modern history : 2009-: journal for the history of the 19th and 20th century" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/title> "Modern\u00ED d\u011Bjiny: sborn\u00EDk k d\u011Bjin\u00E1m 19. a 20. stolet\u00ED" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "(051)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "Evropa" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "8" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "Europe" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "(4)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "Czechia" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "(437.3)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "\u010Cesko" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "93/94" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "d\u011Bjiny" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "D\u011Bjiny (obecn\u011B)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "history" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "(437)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "\u010Ceskoslovensko" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "Czechoslovakia" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "D\u011Bjiny \u010Ceska a Slovenska" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "94(437)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/subject> "19.-20. stolet\u00ED" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/language> "eng" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/language> "cze" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/language> "ger" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/publisher> "Historick\u00FD \u00FAstav AV \u010CR" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/source> "ABA007" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/source> "PF 2764" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/description> "Navazuje na: Sborn\u00EDk k d\u011Bjin\u00E1m 19. a 20. stolet\u00ED (sign. AP 27)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/description> "V r. 2009 byl \u010Dasopis za\u0159azen do Seznamu recenzovan\u00FDch neimpaktovan\u00FDch \u010Dasopis\u016F vyd\u00E1van\u00FDch v \u010Cesk\u00E9 republice." .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/type> "model:periodical" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/type> "model:ndkperiodical" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/date> "[1993-]" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/date> "9999" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/date> "1993" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/format> "print" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/coverage> "Praha" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:ec67a13d-6fb2-4673-9743-4c28db86b2bc> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:0891f6a8-2026-4cea-aa58-3080fcb747cb> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:4e3a84bf-b61c-4eea-93fd-e799b702a108> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:02c6b45d-8e26-4e69-a553-3ba498159143> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:e0152a00-0afc-46e7-805b-d18fa7519f27> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:ff58f281-d37c-4a52-9eea-4a5e599e4263> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:ad38a654-6a54-4ab9-aea8-ee1d8da98937> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:70d6cbfd-5e9e-4210-b9fd-4b960d89d2ec> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:11ca4c31-024b-4a7a-b537-c5f8ce17c512> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:d518f7c8-8fe0-41a4-b1c0-43eef7216f63> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:808a4e83-2b5c-450c-bdde-a0d9f0e78757> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:637a9eb2-da9b-4804-87fa-e15e278db40d> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:f06d0f41-e50d-4b0b-b46f-e182c99d28c2> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:e6f9b159-e338-4ce2-ab95-32d809c0a2e2> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:f9b97f81-1409-4c22-983c-8f42a8c4f327> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:41058335-88b1-4d3a-9428-6cd0d5768f43> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <info:fedora/fedora-system:def/relations-external#hasMember> <info:fedora/uuid:26b641ee-4b32-465f-bdbb-59f15b49a0c2> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://purl.org/dc/elements/1.1/creator> "Historick\u00FD \u00FAstav (Akademie v\u011Bd \u010CR)" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://proarc.lib.cas.cz/relations#hasExport> "file:/media/vg1-lv1/proarc/work_data/users/fkdigi/export/k4_d518f7c8-8fe0-41a4-b1c0-43eef7216f63/" .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://proarc.lib.cas.cz/relations#organization> <info:fedora/.> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://proarc.lib.cas.cz/relations#status> <info:fedora/exported> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://proarc.lib.cas.cz/relations#user> <info:fedora/all> .
<info:fedora/uuid:887f064a-4c35-11e1-8a24-005056a60003> <http://proarc.lib.cas.cz/relations#hasKrameriusExport> "file:/media/vg1-lv1/proarc/work_data/users/fkdigi/export/k4_d518f7c8-8fe0-41a4-b1c0-43eef7216f63/" .

#1
   pid                uuid:887f064a-4c35-11e1-8a24-005056a60003
   state              A
   ownerId            melichova
   cDate              2015-12-15T14:38:41.024Z
   mDate              2022-02-04T09:37:09.254Z
   dcmDate            2020-03-25T09:35:05.334Z
   title              [Moderní dějiny: sborník k dějinám 19. a 20. století, Modern history : 2009-: journal for the history of the 19th and 20th century, Moderní dějiny : 2009-: časopis pro dějiny 19. a 20. století]
   creator            [Historický ústav (Akademie věd ČR)]
   subject            [Dějiny (obecně), Dějiny Česka a Slovenska, 19.-20. století, dějiny, history, Československo, Česko, Evropa, Czechoslovakia, Czechia, Europe, 93/94, (437), (437.3), (4), (051), 8, 8, 93/94, 94(437)]
   description        [Navazuje na: Sborník k dějinám 19. a 20. století (sign. AP 27), V r. 2009 byl časopis zařazen do Seznamu recenzovaných neimpaktovaných časopisů vydávaných v České republice.]
   publisher          [Historický ústav AV ČR]
   contributor        []
   date               [[1993-], 1993, 9999]
   type               [model:periodical, model:ndkperiodical]
   format             [print]
   identifier         [uuid:887f064a-4c35-11e1-8a24-005056a60003, ccnb:cnb000370541, issn:1210-6860, issn-l:1210-6860]
   source             [ABA007, PF 2764]
   language           [cze, ger, eng]
   relation           []
   coverage           [Praha]
   rights             []

**Comment by SykoraLukas** [comment]
Mohu poprosit o zaslani foxml titulu periodika?

**Comment by PetrKotynek** [comment]
[887f064a-4c35-11e1-8a24-005056a60003.txt](https://github.com/proarc/proarc/files/8127132/887f064a-4c35-11e1-8a24-005056a60003.txt)
Doufam, ze je to ono PK

**Comment by kerschfilip** [comment]
ano, to je ono, díky @PetrKotynek @SykoraLukas

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle nás dost trápí - prosím, nemáte nápad, v čem může být problém? Děkuji.

**Comment by kerschfilip** [comment]
Na poslední schůzce k ProArcu jsme se domluvili, že řešením našeho problému s exportem NDK čísel s ečlánky pro Kramerius bude smazat titulní úrovně a založit je znovu 

po upgradu proarcu na 3.7.3 se zmíněný problém znovu objevil (v minulosti jsme museli downgradovat, abychom mohli časopisy zpracovávat). Dnes jsem zkoušel domluvené řešení a bohužel problém stále přetrvává:

**Postup**  
1. založí se náhradní titul (NDK Periodikum)
2. všechny ročníky problematického periodika se pod tento náhradní titul přesunou (přes vazby->nadřazený objekt)
3. zkopíruje se XML původní titulní úrovně problematického periodika
4. trvale se smaže titulní úroveň problematického periodika
5. založí se nový objekt pod stejným UUID jako měla titulní úroveň problematického periodika
6. do nově založeného objektu se zkopíruje XML původní titulní úrovně
7. všechny ročníky se z náhradního titulu přesunou pod nově založenou titulní úroveň
8. export by měl fungovat

**problém**: Export stále nefunguje a hlásí stejnou chybu popsanou výše
[elanky_k4export_neocekavanaChyba_20220421.txt](https://github.com/proarc/proarc/files/8529562/elanky_k4export_neocekavanaChyba_20220421.txt)
![elanky_k4export_novaVrchniUroven_20220421](https://user-images.githubusercontent.com/57805328/164422198-b1103e4d-baf3-4586-ba29-d84425321936.png)


@SykoraLukas je v postupu něco špatně? co s tím? díky.

**Comment by PetrKotynek** [comment]
Je to hodne podobne i v logu
[21.zip](https://github.com/proarc/proarc/files/8530015/21.zip)
PK

**Comment by PetrKotynek** [comment]
Log ze specialni verse PK
[20.zip](https://github.com/proarc/proarc/files/8737402/20.zip)

**Comment by SykoraLukas** [comment]
Logy z dnešního testování jsou naprosto v pořádku. Děkuji

**Comment by PetrKotynek** [comment]
Nepovedl se upgrade na 3.8-DEV-BETA. Databázový problém. Zkusil jsem postupný upgrade 363 - 373 - 38. 373 se povedla ale 38 nikoli. Zpětný chod naštěstí prošel.
PK
[23.zip](https://github.com/proarc/proarc/files/8756088/23.zip)

**Comment by ZdenkaSera** [comment]
@kerschfilip Nezavřeme to zatím?
