### ISSUE TITLE
problem při navratu 3.7.3 - 3.6.3

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1411]
Při pokusu o návrat k poslední fungující verzi, konkrétně z 3.7.3 zpět na 3.6.3 se tato nespustila. viz dál a příloha. Postup, byl přepsáním waru, posléze i restart tomcatu. Je to možno navrátit a dosáhnout běhu s 3.6.3 ? Petr Kotynek

Úno 09, 2022 10:22:21 DOP. org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class [cz.cas.lib.proarc.webapp.server.EditorServletConfiguration]
java.lang.IllegalStateException: java.sql.SQLException: Invalid schema version 10

..
Úno 09, 2022 10:22:21 DOP. org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Úno 09, 2022 10:22:21 DOP. org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/proarc] startup failed due to previous errors
Úno 09, 2022 10:22:21 DOP. org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive [/home/proarc/apache-tomcat8/webapps/proarc.war] has finished in [3,889] ms
Úno 09, 2022 10:25:41 DOP. org.apache.catalina.startup.HostConfig undeploy
INFO: Undeploying context [/proarc]

[9a.zip](https://github.com/proarc/proarc/files/8031704/9a.zip)

**Comment by SykoraLukas** [comment]
Problémem je schéma DB. Změnilo se na 10. Pro přechod na 9 je nutné manuálně editovat schéma databaze.

Pokud o to mate přesto zájem tak můžu pripravit skript pro úpravu z 10 na 9.

**Comment by PetrKotynek** [comment]
Ten skript by byl užitečný v každém případě.  Ještě upozorním na souvislost s 
https://github.com/proarc/proarc/issues/1410
PK

**Comment by SykoraLukas** [comment]
Pošlu mailem.

**Comment by PetrKotynek** [comment]
bohužel, nepomohlo, nejde ani 3.6.3  ani zpět 373 P
[c.zip](https://github.com/proarc/proarc/files/8034976/c.zip)
K

**Comment by PetrKotynek** [comment]
8 zabralo a 363 naběhla

**Comment by PetrKotynek** [comment]
Děkuji Petr

**Comment by PetrKotynek** [comment]
Nepovedl se upgrade na 3.8-DEV-BETA. Databázový problém. Zkusil jsem  postupný upgrade 363 - 373 - 38. 373 se povedla ale 38 nikoli. Zpětný chod naštěstí prošel. 
[23.zip](https://github.com/proarc/proarc/files/8756073/23.zip)

Petr Kotýnek

**Comment by SykoraLukas** [comment]
Nutné spustit v psql:

alter table proarc_users drop column lock_object_function;
alter table proarc_users drop column unlock_object_function;

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
