### ISSUE TITLE
Hranaté závorky jedním klikem (jádro)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#1412]
Zakládám ještě i tady - je třeba dodělat v jádře vše potřebné, aby mohlo fungovat tohle: https://github.com/proarc/proarc-client/issues/62.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Testování prosím v rámci klienta [#62](https://github.com/proarc/proarc-client/issues/62) Děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
