### ISSUE TITLE
Nefunguje mi import NDK balíčků ani import pro Kramerius

### ISSUE THREAD

**Issue by eskrdlant** [proarc/proarc#1413]
Dobrý den,
když nahraji do adresáře Import balíček NDK (monografie či ročník), zvolím importní profil Kramerius NDK Monografie či Kramerius NDK Periodikum, v Import -> Nová dávka na adresář kliknu, tak tlačítko Načíst adresář zůstane disabled.
U profilu Kramerius sice mohu import spustit, snad i proběhne, ale naimportovaný titul následně není v ProArcu k nalezení.
Funguje jen importní profil Archive, ten zas bez problémů!
V čem prosím může být chyba? Import NDK jakož balíčků ve foxml by se nám velmi hodil...
Potřebujete ještě nějakou informaci? Verzi máme 3.7.3

děkujeme,
eliáš škrdlant
kaš

**Comment by SykoraLukas** [comment]
Toto zatím ProArc neumí (zpětný reimport vytvořených balíčků).

**Comment by SykoraLukas** [comment]
Návrh na tuto funcionalitu je v #1177.

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
