### ISSUE TITLE
Error v názvu adresáře v exportu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#1414]
Pokud se nezdaří export z důvodu např. špatného indexu, tak se do názvu adresáře propíše Error_ atd. To je správně. Ale poslední dobou se občas nezdaří export z důvodu přetížení systému, většinou je v Logu napsáno, že některou stránku nelze ve Fedoře najít. V Logu to je, ale chtěli bychom, aby se slovo Error propsalo i do názvu adresáře.... teď je to tak, že zdánlivě úspěšně proběhne K4 export, ale v Logu se pak dočtu, že to z výše popsaného důvodu nedoběhlo....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Tohle asi nedokážeme nasimulovat v testu - vyzkoušela jsem, že úpravou nebylo dotčeno logování chybného indexu při archivaci. Navrhuji navrhnout k uzavření a počkat na chování při chybách v produkci.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Dobře, navrhni k zavření, to se otestuje časem samo :))

**Comment by SykoraLukas** [comment]
Uzavírám na základě labelu.
