### ISSUE TITLE
Stahování polí 510, 563, 590

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1425]
Požadavek od MZK:

Nově z katalogu stahovat také pole 510, 563 a 590 do pole mods:note.

**Comment by luckajirku** [comment]
@SykoraLukas prosím tě, pro jaké modely to má být? Je někde přesnější zadání?

**Comment by SykoraLukas** [comment]
Není, takhle příslo zadání z MZK. Týká se to stahování metadat pro všechny modely.

**Comment by SykoraLukas** [comment]
Prosím o dodatečné komentáře @erikamirova a @mzkgalanda

**Comment by erikamirova** [comment]
@luckajirku @SykoraLukas Týká se to hlavně STT modelů - konkrétně tato pole používáme u prvotisků.

**Comment by luckajirku** [comment]
Ok, díky. Problém je v tom, že třeba pole 590 (resp. celý blok 59X) je určeno pro lokální použití/definici. Zjišťovala si nejdřív @emirova, než zadala požadavek, jak se ta pole v katalogizaci (i jinde než na jejich pracovišti) používají, zda/jak se liší použití u novodobých dokumentů a STT a jak se používá třeba právě pole 590 v jednotlivých knihovnách? 

Je možné sem podrobněji dopsat, na základě čeho se ta pole teď přidávají, resp. kde je to třeba v NDK standardu (nenašla jsem to tam)? 

Pokud se na základě těch instrukcí z NK pro katalogizaci STT podle RDA využívá v té které knihovně 590 jako poznámka o defektním exempláři, tak OK, ale přeci nelze obecnou šablonu kvůli zpracování jednoho typu dokumentu na jednom pracovišti takhle bez diskuse změnit pro všechny.

Jinak praktický příklad od nás - pole 590 máme pro interní poznámky. V OPACu zůstává skrytá, ale touhle úpravou bychom si ji při digitalizaci stáhli a museli vždycky odmazávat.

**Comment by luckajirku** [comment]
Lukáši, díky za upřesnění. V tom případě je to jedno:-). Jen jestli bude těch issues k MZK šabloně víc, bylo by docela fajn, aby to mělo spešl label nebo to tam bylo aspoň jasně napsané, aby ostatní věděli, že není třeba se děsit:-).

**Comment by SykoraLukas** [comment]
V případě užití je nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#katalogy-s-metadaty).

```properties
## (3.8) Cesta k souboru marc21slim2mods.custom.xsl pro custom transformacni sablonu z MARC21 do MODS
## (3.8) Pokud neni pouzito, pouziva se defualtni sablona ProArcu
catalogs.customTemplate.path=${proarc.home}/marc21slim2mods.custom.xsl
```

**Comment by ZdenkaSera** [comment]
@erikamirova Prosím, není to k zavření? Děkuji.

**Comment by erikamirova** [comment]
@ZdenkaSera Ano, toto už funguje.
