### ISSUE TITLE
Stahování <issuance> 

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1427]
Dobrý den,

v KNAV řešíme problém se stahováním hodnot do elementnu `<issuance>` z katalogu a u monografií jsme narazili na několik problémů:

Standard definuje, že `<issuance>` se vyplňuje jen na úrovni jednotlivých svazků, ale ohledně hodnoty je trochu neurčitý: ![image](https://gitlab.com/DigitalniKnihovnaAkademievedCR/testovani-proarcu/uploads/14a7ad64dccc86f95e7d8ef2c2500622/image.png)
v KNAV jsme se dohodli, že nechceme používat hodnotu `monograph`, ale chceme, aby se nám hodnoty vyplňovaly následovně:
  * Samostatný svazek monografie - `single unit`
  * Svazek Vícedílné monografie - `multipart monograph`
  * Vrchní úroveň vícedílné monografie - nic (podle standardu zde `<issuance>` být vůbec nemá. 

Stejně tak s těmito hodnotami pracuje (pokud vím) NK a MZK a objevují se i ve vzorových balíčcích    
...narazili jsme ale na to, že proarc ty hodnoty stahuje z katalogu poměrně podivně:

### Jednosvazková monografie

ProArc v případě jednosvazkové monografie vždy zapíše hodnotu `monographic` a nikdy ne `single unit`, protože v [transformační šabloně z MODSXML](https://github.com/proarc/proarc/blob/2837b89c0a93b41352aa480f3423848eb3d710df/proarc-common/src/main/resources/xml/MARC21slim2MODS3.xsl) (doufám, že je to ta správná) je nejspíš chyba - v záznamu z katalogu se v leaderu na pozici 19 hledá `"#"`, ale podle [transformační šablony](https://standardy.ndk.cz/ndk/standardy-digitalizace/metadata) z MARC21 do MODS verze 3.6 doporučované NK se má hledat mezera: `" "` 

```xml
<issuance>
  <xsl:choose>
    <xsl:when test="$leader7='a' or $leader7='c' or $leader7='d' or $leader7='m'">monographic</xsl:when>
    <xsl:when test="$leader7='m' and ($leader19='a' or $leader19='b' or $leader19='c')">multipart monograph</xsl:when>
    <xsl:when test="$leader7='m' and ($leader19='#')">single unit</xsl:when>
    <xsl:when test="$leader7='i'">integrating resource</xsl:when>
    <xsl:when test="$leader7='b' or $leader7='s'">serial</xsl:when>
  </xsl:choose>
</issuance>
```
### Vícesvazková monografie - vrchní úroveň
ProArc by neměl hodnotu  `<issuance>` vůbec stahovat, na této úrovni nemá být vyplněná. Často ale stahuje `monographic`

### Svazek vícesvazkové monografie - případ, kdy má každý svazek vlastní záznam v katalogu   
- takové monografie by měly mít zapsaný vlastní název svazku v `245 |p` nebo číslo části v `245 |n`
- transformace by se měla řídit pravidlem:

```xml
<xsl:when test="$leader7='m' and ../marc:datafield[@tag=245]/marc:subfield[@code='n' or @code='p']">multipart monograph</xsl:when>
```

- tohle pravidlo jsem [v transformační šabloně ProArcu](https://github.com/proarc/proarc/blob/2837b89c0a93b41352aa480f3423848eb3d710df/proarc-common/src/main/resources/xml/MARC21slim2MODS3.xsl) vůbec nenašel
- výsledek je, že se do XML stáhne `<mods:issuance>monographic</mods:issuance>`

### Svazek vícesvazkové monografie - jeden záznam pro všechny svazky
- Pro celou vícedílnou monografii existuje jeden záznam
- mělo by se použít pravidlo:

```xml
<xsl:when test="$leader7='m' and $leader19='a'">multipart monograph</xsl:when>
```

- toto pravidlo ProArc obsahuje, zdá se ale, že ne všechny záznamy jsou vytvořeny tak, že do něj spadnou (např. [https://katalog.lib.cas.cz/Record/000919002#details](https://katalog.lib.cas.cz/Record/000919002#details) nebo https://katalog.lib.cas.cz/KNAV/Record/001939531#details) --> asi protože jsou podle AACR a ne RDA
- navíc když jsem našel záznam, kde by to fungovat mělo (https://aleph.nkp.cz/F/?func=direct&doc_number=001005489&local_base=SKC), tak mi proarc pro jistotu `<issuance>` vůbec nevyplnil...

----

Je možné upravit stahování dat do ProArcu tak, aby byly výše zmíněné čtyři problémy vyřešeny? 

Díky

**Comment by luckajirku** [comment]
> ### Jednosvazková monografie
> ProArc v případě jednosvazkové monografie vždy zapíše hodnotu `monographic` a nikdy ne `single unit`

To funguje správně, jednosvazková monografie má být monographic. Single unit je pro svazek monografie, který je částí vícedílné monografie.

> Vícesvazková monografie - vrchní úroveň
ProArc by neměl hodnotu <issuance> vůbec stahovat, na této úrovni nemá být vyplněná. Často ale stahuje monographic

Tady by bylo ideální, kdyby se automaticky vyplnilo "multipart monograph".

> Svazek vícesvazkové monografie - případ, kdy má každý svazek vlastní záznam v katalogu

Tohle by ale přeci nastat nemělo (resp. nejprve by se měly dát do pořádku bib záznamy, pokud to jsou pozůstatky z dřívějška, kdy se vícedílky katalogizovaly trochu divoce). A pak už není co řešit - v případě, že má každý svazek svůj vlastní záznam, jsou to jednosvazkové monografie. A pokud je to vícedílka, tak je to zkatalogizované jako vícedílka. 

> Svazek vícesvazkové monografie - jeden záznam pro všechny svazky
Pro celou vícedílnou monografii existuje jeden záznam
 
Tady jsme nepochopili, v čem je problém.

**Comment by SykoraLukas** [comment]
Děkuji @luckajirku za vysvětlení.

**Comment by kerschfilip** [comment]
děkuji za rychlé reakce, kéž by to tak fungovalo u všech issues :-)  

@luckajirku vysvětlíte mi, prosím, svoje odpovědi?
> To funguje správně, jednosvazková monografie má být monographic. Single unit je pro svazek monografie, který je částí vícedílné monografie.

Jak jste na to, prosím, přišla? Například ve vzorovém balíčku NDK, který je jednosvazkovou monografií mají `single unit`. Když se podíváte do Kramerií NDK nebo MZK, tak uvidíte, že u jednosvazkových monografií mají také `single unit`

A pokud se podíváte do té transformační šablony z MARC do MODS, tak se ty záznamy mají překlápět jako `single unit`, nedělají to kvůli chybě s křížkem místo mezery...

> Vícesvazková monografie - vrchní úroveň
> Tady by bylo ideální, kdyby se automaticky vyplnilo "multipart monograph".

no to právě ne - ve standardu je napsané, že `<issuance>` na vrchní úrovni vícesvazku vůbec není, tudíž tam nemůže být `multipart monograph`

--> podívejte se například na tohle: https://dnnt.mzk.cz/uuid/uuid:9dd93850-e6e7-11e4-a794-5ef3fc9bb22f

> v případě, že má každý svazek svůj vlastní záznam, jsou to jednosvazkové monografie. A pokud je to vícedílka, tak je to zkatalogizované jako vícedílka

Nejsem si jistý, že je to takhle jednoduché. Podle RDA se vícesvazkové monografie katalogizují dvojím způsobem: 
- "Vícesvazkové monografie se společným hlavním názvem a významnými názvy částí se popisují samostatně a je tedy potřeba zapsat nejen hlavní název, ale i označení a vlastní název svazku"
- "Vícesvazkové monografie, jejichž jednotlivé části nemají různé původce s hlavní odpovědností, nemají názvy částí, nebo tyto názvy částí nejsou významné pro samostatné vyhledávání, a všechny části přísluší k témuž vydání, se popisují jako celek v jednom bibliografickém záznamu"

> Tady jsme nepochopili, v čem je problém.

Problém je v tom, že i když záznam splňuje kritéria pro to, aby se do ProArcu stáhlo `multipart monograph`, tak se nic nestáhne

**Comment by luckajirku** [comment]
Tady to bude asi na větší diskusi:-). Je otázka, nakolik ty vzorové balíčky a praxe v knihovnách vychází z toho od začátku v NDK špatně pojatého zpracování vícedílek a jakou to má mít váhu. 
Je fakt, že není úplně jasné, pro co přesně se má použít single unit (btw v tom teď asi spícím návrhu standardu pro vícedílky už single unit není vůbec) - snažili jsme se k tomu v LOC najít, přesně kdy co použít, protože ze šablony a mapování to jasné není, ale zatím se nepodařilo.
Když budeme vycházet "jen" z logiky, tak dává smysl multipart monograph pro titulovou úroveň vícedílky (kde ale nic není) a monographic pro svazek... 
Ty příklady z katalogizace - v tom prvním příkladu (významné názvy částí) budete mít záznam pro každý svazek, v tom druhém záznam pro vícedílku - to je přesně to, co jsem psala.

**Comment by kerschfilip** [comment]
Upřímně jsem žádnou velkou diskuzi neočekával. Důvody jak a proč se má issuance vyplňovat jsem popsal v prvním příspěvku s odkazy na všechny autority, které v tom mají roli - DMF, MODS Guidelines, oficiálně doporučovaná transformační šablona... Připadá mi, že jejich kombinací je plnění elementu docela jasně popsané, ale přiznávám, že se mohu mýlit nebo něco nepostihnout dostatečně. Založil jsem tedy issue na GitHubu Standardů a uvidíme podle odpovědi, jak to tady dále posunout.

**Comment by kerschfilip** [comment]
Z odpovědi NK mi vyplývají následující závěry:

Na úrovni **titulu vícesvazku** zůstává issuance v nové verzi DMF beze změny, tj., není přítomno
- ProArc nyní často stahuje hodnotu `monographic`
- neměl by stahovat do tohoto pole nic

na úrovni **svazku vícedílné monografie** jsou a dále budou možné obě hodnoty: `multipart monograph` a `monographic`
- v případě vícedílné monografie, která je zkatalogizována na jeden záznam je preferovanou hodnotou `multipart monograph`
- nyní to nefunguje v ProArcu spolehlivě - například [z tohoto záznamu](https://katalog.lib.cas.cz/Record/000919002#details) vznikne issuance `monographic`

Na úrovni **jednotlivých svazků** je možné používat hodnoty `monographic` a `single unit`. V případně bezpečných samostatných dokumentů je doporučeno využívat hodnotu `single unit`.
- `single unit` nyní ProArc nikdy nestáhne, domnívám se, že je to kvůli chybě v transformační šabloně popsané v hlavičce issue

**Comment by SykoraLukas** [comment]
Nedá se říci, že se jedná o chybu, když to každý chápe jinak a NK k tomu má své stanovisko, které je taky trochu jiné. 

Abych toto mohl udělat potřebuji souhlas všech knihoven ve vývojovém týmu. Je to změna, která přímo ovlivní všechny. Dokud nebude souhlas, odebírám label `2a k realizaci`.

**Comment by kerschfilip** [comment]
@SykoraLukas stanovisko NK jsem popsal v minulém příspěvku, přijde mi docela jasné. Sporný je maximálně případ svazku vícedílné monografie.

U jednotlivého svazku má být v případě, že je v záznamu v katalogu v leaderu na pozici 19 mezera, zapsáno single unit. Tohle nefunguje a je to podle mě chyba transformační šablony (hledá se # místo mezery), viz první příspěvek

v případě titulu vícesvazku se issuance nemá nikdy vyplnit, proarc ale hodnoty stahuje. To je přece chyba jednoznačně...

**Comment by SykoraLukas** [comment]
Špatně jsem se vyjádřil a shrnul to celé do jedné věty (což je problém). Podle toho co jste napsal v prvním příspěvku a podle stanoviska NK navrhuji následující:

> Sporný je maximálně případ svazku vícedílné monografie.

K tomuto založte samostatné issue ať se to dá řešit samostatně, když jde o spornou věc.

> U jednotlivého svazku má být v případě, že je v záznamu v katalogu v leaderu na pozici 19 mezera, zapsáno single unit. Tohle nefunguje a je to podle mě chyba transformační šablony (hledá se # místo mezery).

Opravíme. 

> V případě titulu vícesvazku se issuance nemá nikdy vyplnit, proarc ale hodnoty stahuje. To je přece chyba jednoznačně...

Opravíme.

**Comment by kerschfilip** [comment]
Souhlasím. Pro ten svazku vícedílné monografie založím issue, kde si to budeme moct probrat mezi knihovnami, než to zadáme jako rozšíření (pokud vůbec).

Díky

**Comment by ZdenkaSera** [comment]
Vzhledem k diskusi výše a probíhajícímu vývoji odebírám štítek "návrh na rozšíření". @SykoraLukas @kerschfilip Díky :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím, mohl bys přidat v jádře i klientovi štítek s verzí v3.9 u issues, která jsou v ní zahrnuta? Moc díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Z katalogu KNAV jsem stáhla NDK monografii (čárový kód 26002101695) - issuance se nevyplní. test v KNAV a na Inovatice.

**Comment by ZdenkaSera** [comment]
NDK monografie, sysno = 001065495, aacr, katalog KNAV, test KNAV v3.9 a Inovatika  - issuance se vyplní, ale monographic

**Comment by SykoraLukas** [comment]
> NDK monografie, sysno = 001065495, aacr, katalog KNAV, test KNAV v3.9 a Inovatika - issuance se vyplní, ale monographic

Tohle opravím, tam je chyba v šabloně.

**Comment by SykoraLukas** [comment]
> @SykoraLukas Z katalogu KNAV jsem stáhla NDK monografii (čárový kód 26002101695, rda) - issuance se nevyplní. test v KNAV v3.9 a na Inovatice.

Tohle není chyba, issuance se dle sablony LoC vyplnuje jen ve chvíli, kdy marc záznam obsahuje pole 250 nebo 260. Tento záznam nemá ani jedno pole, takže se pole issuance nevyplnuje.

**Comment by ZdenkaSera** [comment]
@SykoraLukas jak jsme se dohodli v telefonu - prosíme doplňovat issuance i tam, kde se origininfo tvoří z pole 264 a potvrzuji, že issuance má být součástí každého origininfo, pokud se jich v daném objektu vytváří více díky opakování polí/podpolí. Díky.

**Comment by SykoraLukas** [comment]
Prosím o potvrzení, že pro carkod 26002101695 by to mělo vypadat takto:
![image](https://user-images.githubusercontent.com/27210823/200523133-9f2bf6d6-4557-4396-9387-27c26d124d40.png)

` <mods:originInfo eventType="publication">
        <mods:place>
            <mods:placeTerm type="text">Prag</mods:placeTerm>
        </mods:place>
        <mods:publisher>Kommissionsverlag der J. Calve'schen Universitäts-Buchhandlung Robert Lerche</mods:publisher>
        <mods:dateIssued>[1923]</mods:dateIssued>
        <mods:issuance>single unit</mods:issuance>
    </mods:originInfo>`

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ano :-)

**Comment by ZdenkaSera** [comment]
NDK monografie, a hudebnina a STT monografie stahují do issuance single unit, NDK/STT vícedílné monografie bez issuance  - za ne ok. Test v KNAV na 391*2.2.
