### ISSUE TITLE
FOXML - Import do testovacího Krameria

### ISSUE THREAD

**Issue by gmelingerova** [proarc/proarc#1432]
Při kliknutí na tlačítko **Import do testovacího Krameria** se kýžené FOXML importuje do testovacího Krameria

Přehlednější požadavky v pdf: [Foxml - ProArc verze 2.pdf](https://github.com/proarc/proarc/files/8707666/Foxml.-.ProArc.verze.2.pdf)

**Před stav** (příklad, jak je to pro server ProArcu v Jenštejně):

1. V ProArcu se vytvoří složka pro univerzálního uživatele

      - /media/vg1_data/lv1_proarc/proarc-test/work_data/users/univerzalni_uzivatel

2. V té se ručně vytvoří podsložka se jmenem “kramerius-export” (možná dodání přes konfigurační soubor) to bude ve skutečnosti symlink

      - /media/vg1_data/lv1_proarc/proarc-test/work_data/users/univerzalni_uzivatel/kramerius-export

**Postup**:

1. ProArc vytvoření tlačítka - Importovat do testovacího Krameria

      - možnost _**konfigurace názvu**_ tlačítka - my v KNAV budeme chtít to výše zmíněné (testovacího), ale někdo třeba bude chtít importovat rovnou do ostrého (tam by se pak měl ošetřit lepší přístup k username a password)

2. Po kliknutí na tlačítko se konkrétní složka konkrétního uživatele překopíruje do složky kramerius-export univerzálního uživatele.
Příklad:
      - uživatel aaaa, cesta do exportní složky titulu k4_xxxx, který chce importovat do testovacího
  /media/vg1_data/lv1_proarc/proarc-test/work_data/users/aaaaa/export/k4_xxxx

      - po překopírování to bude vypadat u univerzálního uživatele takto:
  /media/vg1_data/lv1_proarc/proarc-test/work_data/users/univerzalni_uzivatel/kramerius-export/aaaaa/export/k4_xxxx

3. Proměnná **proarcExportFolder** je složená takto: univerzalni_uzivatel/konkretni_uzivatel/export/k4_xxxx
      - v KNAV v testovacím Krameriu vytvoříme podsložku proarc-export (x/x/.kramerius4/import/proarc-export) - dodání skrz _**konfigurační soubor**_

4. Zavolání metody

      - která naplánuje nový proces (**parametrizedimport**) pomocí API - https://github.com/ceskaexpedice/kramerius/wiki/RemoteAPI

        - curl -u username:password -H "Content-Type: application/json" -d '{"mapping":{"importDirectory":"x/x/.kramerius4/import/proarc-export/proarcExportFolder","startIndexer":"true", "updateExisting":"false"}}' -X POST krameriusAdress/search/api/v4.6/processes?def=parametrizedimport

        - username, password - dodání skrz _**konfigurační soubor**_
                - vytvořil se univerzální uživatel pro import - proarcImport
                - heslo dodáme
        - importDirectory - "x/x/.kramerius4/import/proarc-export/" + proarcExportFolder
                - složeno z cesty do importního adresáře Krameria (x/x/.kramerius4/import/proarc-export/ - z _**konfiguračního souboru**_) a
                - FOXML složky v univerzálním uživately z ProArcu (proarcExportFolder)
        - volání procesu
                - krameriusAdress + "/search/api/v4.6/processes?def=parametrizedimport"
                - krameriusAdress z _**konfiguračního souboru**_             
      - Metoda - requestKrameriusImport z Merlina
        - https://github.com/jkremlacek/Merlin/blob/master/src/cz/mzk/osdd/merlin/models/Utils.java#L258

5. Upozornit uživatele zda se import povedl či nepovedl

6. Smazání překopírované složky z importního adresáře Krameria - importDirectory

Tady [automaticImportFoxml.java.zip](https://github.com/proarc/proarc/files/8707686/automaticImportFoxml.java.zip) je zjednodušený kód, který neřeší propojení disků atd.

Tady [Foxml - ProArc.pdf](https://github.com/proarc/proarc/files/8707788/Foxml.-.ProArc.pdf) je původní verze, kdyby se nepřipojovaly disky. Ale připojení/mapování disků to celé zkomplikovalo, tak dotazy či upřesnění ohledně cest a dalších věcí směřujte na pana Dudu @mduda100871.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím popsat řešení.

**Comment by ZdenkaSera** [comment]
V konfiguraci bude rozlišení instancí test/ostrý - z testovacího bude možné automaticky mazat. Rozvoj 2023.

**Comment by SykoraLukas** [comment]
Zatím implementováno u Kramerius Export, nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace/_edit#importy-do-instanci-krameria)

**Comment by ZdenkaSera** [comment]
V KNAV úspěšně otestováno zatím na testovací instanci ProArcu (Fedora) vůči testovací K5. Testy s akunrou/K7  časem.

**Comment by ZdenkaSera** [comment]
V KNAV otestováno vůči produktivní instanci K5 - v principu je funkční včetně oprávnění, zbývá test s K7.

V KNAV se ale projevila chyba uvedená  zde https://github.com/proarc/proarc/issues/1600

**Comment by ZdenkaSera** [comment]
Navrhuji k zavření - v principu je funkční (test s K5 a Fedorou). Pokud časem narazíme na potíže v kombinaci s K7 a/nebo Akubrou, otevřeme issue s chybou.

**Comment by ZdenkaSera** [comment]
Za KNAV odebírám "lokální test" a zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
