### ISSUE TITLE
NDK - Import do testovacího Krameria

### ISSUE THREAD

**Issue by gmelingerova** [proarc/proarc#1433]
Při kliknutí na tlačítko **Import do testovacího Krameria** se kýžené NDK EMONOGRAFIE importuje do testovacího Krameria

Přehlednější požadavky v pdf: [NDK - ProArc.pdf](https://github.com/proarc/proarc/files/8707940/NDK.-.ProArc.pdf)

**Postup**:
1. ProArc vytvoření tlačítka - Importovat do testovacího Krameria

      - možnost _**konfigurace názvu**_ tlačítka - my v KNAV budeme chtít to výše zmíněné (testovacího), ale někdo třeba bude chtít importovat rovnou do ostrého (tam by se pak měl ošetřit lepší přístup k username a password)

2. Překopírování složky NDK (jen emonografie!) z ProArcu (proarcExportFolder) do convertní složky Krameria
      - v KNAV v testovacím Krameriu vytvoříme podsložku proarc v:
        - convert - (x/x/.kramerius4/convert/proarc) - dodání skrz _**konfigurační soubor**_
        - convert-converted - (x/x/.kramerius4/convert-converted/proarc) - dodání skrz **_konfigurační soubor_**

4. Zavolání metody

      - která naplánuje nový proces (**ndkmets**) pomocí API - https://github.com/ceskaexpedice/kramerius/wiki/RemoteAPI
        - curl -u username:password -H "Content-Type: application/json" -d '{"mapping":{"convertDirectory":"/x/x/.kramerius4/convert/proarc/proarcExportFolder","convertTargetDirectory":"/x/x/.kramerius4/convert-converted/proarc/proarcExportFolder","ingestSkip":"false","startIndexer":"true","defaultRights":"true"}}' -X POST krameriusAdress/search/api/v4.6/processes?def=ndkmets
        - username, password - dodání skrz _**konfigurační soubor**_
                - vytvořil se univerzální uživatel pro import - proarcImport
                - heslo dodáme
        - convertDirectory - "x/x/.kramerius4/convert/proarc/" + proarcExportFolder
                - složeno z cesty do convertního adresáře Krameria (x/x/.kramerius4/convert/proarc/ - z _**konfiguračního souboru**_) a
                - NDK složky překopírované z ProArcu (proarcExportFolder)
        - convertTargetDirectory - "x/x/.kramerius4/convert-converted/proarc/" + proarcExportFolder
                - složeno z cesty do složky adresáře Krameria, která obsahuje NDK konvertované na Foxml (x/x/.kramerius4/convert-converted/proarc/ - z _**konfiguračního souboru**_) a
                - NDK složky překopírované z ProArcu (proarcExportFolder)
        - volání procesu
                - krameriusAdress + "/search/api/v4.6/processes?def=ndkmets"
                - krameriusAdress z konfiguračního souboru             
      - Metoda - requestKrameriusImport z Merlina

        - https://github.com/jkremlacek/Merlin/blob/master/src/cz/mzk/osdd/merlin/models/Utils.java#L258

5. Upozornit uživatele zda se import povedl či nepovedl

6. Smazání překopírované složky (proarcExportFolder) z convertního adresáře Krameria (convertDirectory)

7. Smazání složky, která obsahuje NDK konvertované na Foxml (convertTargetDirectory)

Tady [automaticImportNDK.java.zip](https://github.com/proarc/proarc/files/8707971/automaticImportNDK.java.zip) je zjednodušený kód, který neřeší propojení disků atd. Jak budou namapované cesty atd. řešte s panem Dudou @mduda100871, ale mělo by to +- vycházet z [Foxml Issue](https://github.com/proarc/proarc/issues/1432).

**Comment by SykoraLukas** [comment]
Obdobně jako je to u Kramerius Export, tak by bylo i u NDK export.

Bude opět muset být připojena convertní složka z Krameria.

Nutné probrat jak to prezentovat uživatelům (v rámci jednoho exportu mít možnost vybrat instanci Krameria, nebo jako je u Bagit exportu rozdělit)?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím,  mohl bys tady doplnit konfiguraci? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas A ještě - nejsou zapotřebí úpravy ve správě procesů na straně klienta?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tady ještě do třetice ke konfiguraci/testu, zkusím shrnout předchozí dotazy - díky za potvrzení či upřesnění.
- Pokud jde o instance Krameria, předpokládám, že je konfigurace společná s importem FOXML, takže to už je popsané na wiki
- Ve správě procesů se zřejmě statusy a hlášení výsledků/chyb  taky sdílí s exportem FOXML, takže je to připravené k testu; napadá mě jen ten rozdíl, že balíček by se neměl exportovat bez urn:nbn a tahle chyba by se taky měla promítat do hlášky ve správě procesů
- Jedinou změnou by tedy mělo být správné přidání možnosti exportu "NDK PSP s nahráním do Krameria" do lokální konfigurace

**Comment by SykoraLukas** [comment]
Je to jak píšeš, vše je společné, chyba chybějícího URN:NBN se zapisuje do chyb při exportu stejně jako špatný index.

Nový druh exportu je v defaulním globals.js dodávaný s buildem.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, asi přece jen něco chybí na wiki v popisu konfigurace.

- Na produktivní instanci PA máme 4.0.7-DEV-i1618, automatické importy foxml do Krameria fungují.
- Na testu je 4.1.0, konfiguraci Krameriů máme stejnou (zatím jen pro foxml, ndk jsme ještě nenastavovali), ale jádro i klient dovolují jen export na Local.
@PetrKotynek našel tyhle warningové hlášky -  export folder ale na wiki zmíněn není, jen import folder (a jen pro foxml, o ndk tam není nic)
- Missing krameriusInstance.k5test.exportFoxmlFolder in proarc.cfg
- Missing krameriusInstance.k5test.exportNdkFolder in proarc.cfg

 Prosím, co tam chybí? Díky

**Comment by SykoraLukas** [comment]
Konfigurace je [zde](https://github.com/proarc/proarc/wiki/Konfigurace#nastaven%C3%AD-instanc%C3%AD-krameri%C5%AF).

Tady dávám jen to, co vám chybí:
``` properties
# Cesta pro FOXML export, do které namapována importní složka convert Krameria 
krameriusInstance.kramerius5.exportFoxmlFolder=/Temp/ProArc/autoImport/kramerius-test/import/
krameriusInstance.kramerius7.exportFoxmlFolder=/Temp/ProArc/autoImport/kramerius-test/import/

# Cesta pro NDK export, do které namapována importní složka import Krameria 
krameriusInstance.kramerius5.exportNdkFolder=/Temp/ProArc/autoImport/kramerius-test/convert/
krameriusInstance.kramerius7.exportNdkFolder=/Temp/ProArc/autoImport/kramerius-test/convert/
```

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkujeme, vyzkoušíme.

**Comment by PetrKotynek** [comment]
pod dotaz proč toto nestačí k funkci ?  
proarc-test@proarc-dc:~/work_data$ cat proarc.cfg |grep k5test
krameriusInstances=local,k5test
#krameriusInstances=local, k5test, k5prod, k7test
krameriusInstance.k5test.title=K5 test
krameriusInstance.k5test.version=5.8.4
krameriusInstance.k5test.type=test
krameriusInstance.k5test.url=https://k4test.lib.cas.cz
krameriusInstance.k5test.urlParametrizedImportQuery=/search/api/v4.6/processes/?def=parametrizedimport
krameriusInstance.k5test.urlStateQuery=/search/api/v4.6/processes?uuid=
krameriusInstance.k5test.username=proarc_test
krameriusInstance.k5test.passwd=
krameriusInstance.k5test.exportFolder=/home/proarc-test/k4test.lib.cas.cz-import-auto
krameriusInstance.k5test.krameriusImportFoxmlFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5test.deleteAfterImport=true

**Comment by ZdenkaSera** [comment]
Není to tak, že s "příchodem" NDK bylo zapotřebí rozdělit "krameriusInstance.k5test.exportFolder"  na "exportFoxmlFolder" a "exportNdkFolder" ?

**Comment by SykoraLukas** [comment]
Ano, je to tak.

**Comment by PetrKotynek** [comment]
Dobrá, beru to jako další složky ve stejném share ??? 
do konfigu přismoleno:
krameriusInstance.k5test.exportFoxmlFolder=/home/k4test/.kramerius4/import/
krameriusInstance.k5test.exportNdkFolder=/home/k4test/.kramerius4/convert/
a hlášení. 

03-Nov-2023 12:13:38.881 WARNING [ajp-nio2-127.0.0.1-9009-exec-70] cz.cas.lib.proarc.common.kramerius.KrameriusOptions.warning Missing krameriusInstance.k5test.exportFoxmlFolder in proarc.cfg
03-Nov-2023 12:13:38.882 WARNING [ajp-nio2-127.0.0.1-9009-exec-70] cz.cas.lib.proarc.common.kramerius.KrameriusOptions.warning Missing krameriusInstance.k5test.exportNdkFolder in proarc.cfg

že by poznal neexistenci adresářů ?

**Comment by SykoraLukas** [comment]
To se zde neřeší. Restartovala se aplikace po změně konfigurace?

**Comment by PetrKotynek** [comment]
Z
Zkusil jsem 
krameriusInstance.k5test.krameriusImportFoxmlFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5test.exportFoxmlFolder=/home/k4test/.kramerius4/import-auto/import/
krameriusInstance.k5test.exportNdkFolder=/home/k4test/.kramerius4/import-auto/convert/



03-Nov-2023 12:28:23.443 INFO [ajp-nio2-127.0.0.1-9009-exec-39] org.apache.commons.configuration.AbstractFileConfiguration.reload Reloading configuration. URL is file:/home/proarc-test/work_data/proarc.cfg
03-Nov-2023 12:29:49.223 INFO [ajp-nio2-127.0.0.1-9009-exec-60] org.apache.commons.configuration.AbstractFileConfiguration.reload Reloading configuration. URL is file:/home/proarc-test/work_data/proarc.cfg
03-Nov-2023 12:29:49.248 INFO [ajp-nio2-127.0.0.1-9009-exec-60] cz.cas.lib.proarc.common.imports.ImportBatchManager.update Batch null state EXPORT_PLANNED - null
03-Nov-2023 12:29:49.263 INFO [ExportDispatcher-pool-9-thread-1] cz.cas.lib.proarc.common.imports.ImportBatchManager.update Batch 1538 state EXPORTING - null
03-Nov-2023 12:29:49.276 INFO [ExportDispatcher-pool-9-thread-1] cz.cas.lib.proarc.common.imports.ImportBatchManager.update Batch 1538 state EXPORT_FAILED - java.lang.IllegalArgumentException: Error s nakonfigurovanou cestou: /home/k4test/.kramerius4/import-auto/import/ (zkontrolujte, ze cesta existuje a mate do ni prava na cteni a zapis.
        at cz.cas.lib.proarc.common.kramerius.KrameriusOptions.getExportFolder(KrameriusOptions.java:80)
        at cz.cas.lib.proarc.common.export.ExportProcess.krameriusExport(ExportProcess.java:739)
        at cz.cas.lib.proarc.common.export.ExportProcess.start(ExportProcess.java:154)
        at cz.cas.lib.proarc.common.export.ExportProcess.run(ExportProcess.java:132)
        at cz.cas.lib.proarc.common.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

**Comment by SykoraLukas** [comment]
Takze uz by měla být instance videt. Jen je problem s tim, ze slozka budto neexistuje nebo do ni nemate pravo zapisovat.

**Comment by PetrKotynek** [comment]
nejčko to načetlo jako bez chyby

03-Nov-2023 12:46:35.850 INFO [ajp-nio2-127.0.0.1-9009-exec-37] org.apache.commons.configuration.AbstractFileConfiguration.reload Reloading configuration. URL is file:/home/proarc-test/work_data/proarc.cfg

udělalt jsem tam ty adresaře PK

**Comment by SykoraLukas** [comment]
Ještě když koukám na konfiguraci, tak chybí toto:

``` properties
# Cesta, na serveru Krameria, kde je konvertní složka
krameriusInstance.kramerius5.krameriusConvertNdkFolder=/opt/app-root/src/.kramerius4/convert/

# Cesta, na serveru Krameria, kde je zkonvertovaná složka
# Pouze pro verzi 5
krameriusInstance.kramerius5.krameriusTargetConvertedFolder=/opt/app-root/src/.kramerius4/convert-converted/
```

Cesty z pohledu Krameria. Obdoba toho, jak to je pro krameriusImportFoxmlFolder

**Comment by PetrKotynek** [comment]
pokus 1 share 
/import/ rovná se /convert/ ?  PK

proarc-test@proarc-dc:~/work_data$ cat proarc.cfg |grep .k5test.
#krameriusInstances=local, k5test, k5prod, k7test
krameriusInstance.k5test.title=K5 test
krameriusInstance.k5test.version=5.8.4
krameriusInstance.k5test.type=test
krameriusInstance.k5test.url=https://k4test.lib.cas.cz
krameriusInstance.k5test.urlParametrizedImportQuery=/search/api/v4.6/processes/?def=parametrizedimport
krameriusInstance.k5test.urlStateQuery=/search/api/v4.6/processes?uuid=
krameriusInstance.k5test.username=proarc_test
krameriusInstance.k5test.passwd=fIFr4mRB
krameriusInstance.k5test.exportFolder=/home/proarc-test/k4test.lib.cas.cz-import-auto
krameriusInstance.k5test.krameriusImportFoxmlFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5test.exportFoxmlFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5test.exportNdkFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5test.krameriusConvertNdkFolder=/home/k4test/.kramerius4/import-auto/convert/
krameriusInstance.k5test.krameriusTargetConvertedFolder=/home/k4test/.kramerius4/import-auto/convert-converted/
krameriusInstance.k5test.deleteAfterImport=true
proarc-test@proarc-dc:~/work_data$ cat proarc.cfg |grep krameriusInstances
krameriusInstances=local,k5test
#krameriusInstances=local, k5test, k5prod, k7test

**Comment by PetrKotynek** [comment]
[konfig.txt](https://github.com/proarc/proarc/files/13307368/konfig.txt)

**Comment by PetrKotynek** [comment]
[expo.zip](https://github.com/proarc/proarc/files/13331299/expo.zip)

zmena z 10 11 PK

**Comment by SykoraLukas** [comment]
Kromě výše zmíněné konfiguraci je ještě potřeba doplnit:
``` properties
# URL dotaz ke spuštění Convert
# Odlišný endpoint API pro Kramerius 5 a 7 - není třeba měnit
krameriusInstance.kramerius5.urlConvertImportQuery=/search/api/v4.6/processes/?def=ndkmets
krameriusInstance.kramerius7.urlConvertImportQuery=/search/api/admin/v7.0/processes
```

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím Tě, uprav na wiki informaci ohledně importů do Krameria - píše se tam, že fce je dostupná od  verze 4.0-dev, ale to platí jen pro FOXML. Nastavení pro NDK je ve stejném odstavci a je to matoucí. Moc díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím Tě, není ještě zapotřebí nějaká další konfigurace pro automatický import e-modelů? Po přidání ndk_psp_upload_kramerius do globals se nám možnost NDK PSP exportu pro Krameria nabízí pro NDK modely (monografie, vícedílky , periodika) a přidáním ndk_oldprint_upload_kramerius i pro STT. Ale pro e-modely to nestačí, u nich se nám teď nezobrazuje nic kromě standardního exportu pro Krameria (je to ve verzi 4.1.0/2.2.0). Díky

**Comment by SykoraLukas** [comment]
Chyběla daná hodnota v v akceptovaných exportech. Doplnil jsem. Nově bude potřeba do konfigu přidat hodnotu `ndk_sip_upload_kramerius`. Podpora až s novým buildem API.

**Comment by ZdenkaSera** [comment]
Automatický import NDK balíčku do K5 v testu KNAV OK.

**Comment by ZdenkaSera** [comment]
Přetestováno, v K5 funguje, K7 k ověření. navrhuji k uzavření, při objevených chybách otevřeme issues s referencí k tomuto.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
