### ISSUE TITLE
eMonografie - připojení epub

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1439]
Zdravím,

zkoušel jsem, jak se ProArc (3.8-DEV-BETA) zachová, pokud budu chtít k NDK Svazku emonografie připojit místo PDF EPUB. Uvnitř ProArcu se zdá všechno relativně v pořádku, vypadá to, že se .epub k metadatům i připojí, i když ve starém ani novém rozhraní není vidět:
![image](https://user-images.githubusercontent.com/57805328/170200140-14bf5e4a-95f7-4623-952b-ac54e46ee1ef.png)
(to je OK, domluvili jsme se, že časem se do nového klienta implementují stejné čtečky jako jsou teď v klientovi Krameria)

Problém je ale v NDK SIP exportu - ve složce `original` se vytvoří soubor s příponou .pdf, který nejde otevřít. 

Prosím tedy (výhledově) o nějakou revizi a umožnění přidávání souboru .epub, Když už to umí/velmi brzo bude umět používat Kramerius, rádi bychom se do toho pustili.

Díky,
FK

**Comment by SykoraLukas** [comment]
Mohu poprosit o zaslání epubu na e-mail? Nemám bohužel žádný vzorový na kterém bych to mohl vyzkoušet.

**Comment by kerschfilip** [comment]
odesláno, díky

**Comment by kerschfilip** [comment]
testováno na [v3.8](https://github.com/proarc/proarc/releases/tag/v3.8) a vypadá to v pořádku. Moc díky, issue tedy zavírám :-)
