### ISSUE TITLE
RDflow - přidání sloupce Skener

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1463]
Uvítali bychom, aby byl použitý skener, který se uvádí v úkolech, vidět tak, aby se nemuselo lézt dovnitř do Úkolu. Nejlépe, aby byl umístěn do horní levé tabulky. Pak by se dalo i filtrovat podle skeneru. Souvisí s #1355

**Comment by SykoraLukas** [comment]
Aby fungovalo, musí být shoda mezi labelem zařízení a vybranou hodnotu ze seznamu zařízení.

**Comment by SmejkalovaAnna** [comment]
Super, je to tam. Funguje to. Díky!

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
