### ISSUE TITLE
RDflow - Nefunguje Filtr ve sloupcích vztahujících se k Úkolům

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1464]
Nefunguje Filtr ve sloupcích vztahujících se k Úkolům. Tj. Dokončený úkol, Datum dok. úkolu, Dokončil úkol. Nelze filtrovat PID (uuid - to je dost důležité) ani Adresář surových skenů.
Ostatní funguje.

Testováno v jádru:
Verze: 3.8.2 - na našem testu
Verze: 3.7.3 - DC PA
Verze: 3.8.3-dev (na  Inovatice - tam je málo dat)

**Comment by SmejkalovaAnna** [comment]
funguje

**Comment by ZdenkaSera** [comment]
Zavírám vzhledem k návrhu na zavření a faktu, že bylo zahrnuto ve vydané verzi.
