### ISSUE TITLE
Opravy urn:nbn - promítnutí do resolveru - sběrné issue pro všechny fáze realizace

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1465]
Pokud dojde k opravě objektu, který už byl registrován v resolveru, je podle rozsahu a povahy oprav zapotřebí buď zneplatnit původní urn:bnbn a objektu přiřadit nové nebo vytvořit vztah mezi původním a opraveným objektem. 
Metodika: https://resolver.nkp.cz/urn:nbn:cz:nk-004hvy

**Comment by kerschfilip** [comment]
souvisí s #1384

**Comment by SykoraLukas** [comment]
Doplnit funkcionalitu na API (nové 2 endpointy - zneplatnit URN:NBN, vytvořit návaznické URN:NBN) - dle metodiky výše.

Nutné vymyslet, jak toto prezentovat uživatelům (rozbalovací menu u URN:NBN s možnostmi nové urnnbn, zneplatnit urnnbn a vytvořit návaznické urnnbn)?

**Comment by ZdenkaSera** [comment]
Návrh:
Vznikne skupina funkcí „CZIDLO“. (záměrně nepoužíváme urn:nbn, aby se to nepletlo s fcí přidělení urn:nbn)
- Bude na stejné úrovni práce s objekty jako je přidělování urn:nbn (tj. bude možné označit k opravě objekty až  na nejnižší úrovni přidělování urn:nbn)
- Bude dostupná pouze uživatelům s oprávněním (analogie např. zamykání objektů)

**„CZIDLO“ bude zahrnovat operace:**
- Nová registrace
- Následovník
- Deaktivace
- Oprava/doplnění
- Zneplatnění urn:nbn

**Comment by ZdenkaSera** [comment]
**Nová registrace**
- Zneplatnění přiděleného urn:nbn v metadatech objektu v PA
- Deaktivace téhož urn:nbn a výmaz uuid v CZIDLE
- Standardní přidělení nového urn:nbn tomuto uuid

**Použití**
- Zjištění skutečnosti, že vlastníkem dokumentu je jiná instituce, než kterou reprezentuje daný registrátor.
- Zjištění, že dokument byl registrován pod chybným typem dokumentu.
- Zjištění, že hlavní identifikační údaje jako název a autor byly chybné (nejde o překlepy, ale o záměny jmen – např. místo knihy s názvem Babička se dokument ve skutečnosti jmenuje Honzíkova cesta)

**Comment by ZdenkaSera** [comment]
**Následovník**
Podle konzultace s NK: Pro založení vazby následovníka (respektive spíše předchůdce) se má postupovat podle tohoto: https://github.com/NLCR/CZIDLO/wiki/API-v3---p%C5%99%C3%ADklady#m%C3%B3dy-registrace-1
Na API resolveru se pošle tento request:
![image](https://github.com/proarc/proarc/assets/79305516/656a2430-da1b-462a-8286-b8e842b11b87)

Tím, že bude v elementu `<urnNbn>` uvedeno jen urn:nbn předchůdce, se automaticky staré urn:nbn deaktivuje a vytvoří se nové (v módu BY_RESOLVER), které se vrátí jako odpověď na dotaz. UUID není třeba vymazávat a zůstává stejné.

**Použití**
- Sloučení dokumentů – sloučením dokumentů se rozumí stav, kdy se dvě a více odlišných intelektuálních entit spojí do jedné intelektuální entity.
- Rozdělení dokumentu – rozdělení jedné intelektuální entity do dvou nebo více intelektuálních entit.
- Oprava popisu dokumentu, která nepovede k záměně intelektuálních entit (oprava překlepů nebo chybějící části názvu).
- Signifikantně jiná digitalizace téže intelektuální entity v rámci jednoho vlastníka.
- Doskenování nebo přeskenování původního dokumentu v rámci stejné digitalizace (tedy doplnění nebo vyměnění obrazových souborů náležející k popisným metadatům v takovém případě musí být důvod vytvoření vazby na následníka zapsán v poznámce [note] requestu do resolveru)

**Comment by ZdenkaSera** [comment]
**Deaktivace**
- Deaktivace urn:nbn v čidle
- Výmaz uuid z čidla

**Použití**
- Jako samostatná se tato operace používá při trvalé ztrátě digitálního dokumentu, tj. vyžaduje ruční zadání, nepředpokládá se existence dokumentu v ProArcu

**Comment by ZdenkaSera** [comment]
**Oprava/doplnění**
- oprava (příp. výmaz) nebo doplnění např. identifikátorů, tj. bez nutnosti přeregistarce urn:nbn
- funkci bude nejspíše zapotřebí rozdělit podle typu změny
- bude zapotřebí ruční vstup uživatele, o změnu kterých dat se jedná (nejspíše výběrem typu z roletky, hodnota se pak převezme z metadat a odešle)

**Použití**
- Doplnění dosud chybějících údajů (např. identifikátor čČNB)
- Změna v údajích popisujících digitální instanci (včetně změn identifikátorů jako např. uuid)

**Comment by ZdenkaSera** [comment]
**Zneplatnění urn:nbn v PA**
- lokální funkce, která jen nastaví urn:nbn v objektu v PA jako invalid, do čidla nic neposílá
- má sloužit ke zneplatnění urn:nb přidělených ručně nebo z testovací instance čidla např. kvůli možnosti vytvoření testovacího balíčku ke kontrole VISK v NK
- objektu pak lze z produktivní instance čidla přidělit urn:nbn bez předchozího výmazu uuid

**Comment by ZdenkaSera** [comment]
Navrhuji k uzavření vzhledem ke statusu dílčích úkolů
