### ISSUE TITLE
Stahování <issuance> svazku vícedílné monografie

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1475]
Při popisu svazku vícedílné monografie je možné u elementu `<issuance>` používat dvě hodnoty: `multipart monograph` a `monographic`

v případě vícedílné monografie, která je zkatalogizována na jeden záznam, je [podle vyjádření NK](https://github.com/NLCR/Standard_NDK/issues/173#issuecomment-1130081121) preferovanou hodnotou `multipart monograph`. Nyní to ale nefunguje v ProArcu (3.8.2) spolehlivě - například [z tohoto záznamu](https://katalog.lib.cas.cz/Record/000919002#details) vznikne issuance `monographic`

Protože hodnota `multipart monograph` je preferovaná, ne vyžadovaná, musíme se nejprve shodnout, jestli a jak tento problém řešit.  

Issue navazuje na původním #1427, kde se řešilo více problémů

**Comment by ZdenkaSera** [comment]
Navrhuji dořešit jako součást podpory nových standardů v rámci projektu 2023, zatím tam zařazuji.

**Comment by ZdenkaSera** [comment]
7.9. - 
svazek vícedílné monografie - multipart_monograph
jenotlivé monografie - single unit

**Comment by ZdenkaSera** [comment]
souvisí s https://github.com/proarc/proarc-client/issues/346

**Comment by ZdenkaSera** [comment]
@SykoraLukas V issue https://github.com/proarc/proarc-client/issues/346 jsme řešili stahování issuance do NDK svazku vícedílné monografie, 7.11. domluvena shoda ohledně návrhu níže. Prosím o opravu. Děkuji. 
(Testovací data - KNAV, sysno = 000038982 se stahuje korektně podle šablony, sysno=000022647 nesplňuje podmínky a na Inovatiice se teď issuance nevyplní).

Navrhujeme, aby se zde doplňování issuance vyřešilo v kódu místo v šabloně tak, že se do modelu svazek vícesvazkové monografie bude vždy doplňovat multipart_monograph.

**Comment by ZdenkaSera** [comment]
Chová se podle domluvy výše, tj. do modelu NDK svazek vícedílné monografie se vždy doplňuje multipart monograph. Test v KNAV na v4.1.1./2.2.1.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
