### ISSUE TITLE
Podpora Uložiště Akubra

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1481]

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím tě, mohl bys vytvořit štítek "Akubra"? Zatím bych jím označila ta nová issue pana Kotýnka. Děkuju.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, nezavřeme tohle? Díky ..
