### ISSUE TITLE
Není možné přidat kódy rolí MARC 21 u autorit souvisejících se zvukem 

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1485]
Kódy rolí souvisejících se zvukem nejsou součástí seznamu v kontrolovaném slovníku k popisu role autora (např. chybí cmp=skladatel).

**Comment by katerinasirova** [comment]
Otestováno, přidáno. Můžeme zavřít.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
