### ISSUE TITLE
Chyba v transformační šabloně - umazání levostranné závorky u místa vydání

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1486]
U zvukových dokumentů se při stahování záznamu z katalogu smaže levostranná hranatá závorka u místa vydání.

**Comment by katerinasirova** [comment]
Pokud nastane první případ, pak dopisuju k místu/vydavateli tu pravou závorku, aby ten údaj jako takový dával smysl. 
Šlo by programátorsky ošetřit, že když se u těchto údajů vyskytuje jen jedna závorka, tak tu druhou na konec řetězce doplnit automaticky?

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prolézá issues - prosím, není tohle (i přes otevřené otázky) k testu? Díky.

**Comment by SykoraLukas** [comment]
Prosím o nějaké vzorové záznamy v katalogu a jak by se to u nich mělo chovat. Podle toho to vyřešíme.

**Comment by ZdenkaSera** [comment]
LJ návrh: na semináři probrat s uživateli jiných katalogů

**Comment by ZdenkaSera** [comment]
Příklady z  katalogu KNAV (na pokračování)

- sysno = 000869728 
![image](https://github.com/proarc/proarc/assets/79305516/b9f2fa39-2110-4079-939f-9648294165cd)

- sysno = 002185577
![image](https://github.com/proarc/proarc/assets/79305516/68d8fefa-07d0-4277-a47e-b57a8e8b3e04)

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, prosím, okomentovala bys tohle řešení? Díky.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, za nás to navrhuji k uzavření - jak to vidíš? Díky.

**Comment by katerinasirova** [comment]
Otestovala jsem u nás na pár příkladech, jeví se to jako OK. Zavřela bych a časem uvidíme, jestli tohle řešení vyhovuje. Za nás tedy zavřít, díky.

**Comment by tumovam** [comment]
Zavírám na základě domluvy na schůzce.
