### ISSUE TITLE
v 3.9 - genre u eMonografií

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1488]
Ve verzi 3.9 se do elementu `<genre>` předvyplňuje u svazku eMonografie hodnota `electronic_volume` a analogicky u vícedílné eMonografie `electronic_title` 

Podle standardu to ale má být `electronic volume` a `electronic title` - tedy bez pomlčky. Ve starších verzích ProArcu to tak i bylo.

Díky

**Comment by kerschfilip** [comment]
Nevím... Možná je to dokonce drobnost, protože do Krameria se to naimportuje s podtržítkem i bez něj. Zkusím to s NK nějak otevřít, aby se dodržovala jedna forma...

**Comment by SykoraLukas** [comment]
Diky

**Comment by kerschfilip** [comment]
https://github.com/NLCR/Standard_NDK/issues/182

**Comment by SykoraLukas** [comment]
Upravím dle aktualního standardu, pokud NK změní, tak to vydá v nové verzi. Tak bychom to změnili až potom se změnou standardu.

**Comment by kerschfilip** [comment]
ve verzi 3.9.1 je to u emonografií v pořádku
