### ISSUE TITLE
v 3.9 - NDK SIP Export eMonografie - pojmenování PDF/EPUB

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1489]
Ve verzi 3.9 je PDF nebo EPUB soubor ve složce original pojmenovaný jinak než v minulosti - například "oc_aba007-0000ua_monograph_unit_0001.pdf" místo původního "oc_aba007-0000ua".

Má to nějaký důvod? Pokud ne, tak myslím, že by bylo dobré se držet původního pojmenování (ale je to zase jen taková kosmetická věc, na funkčnost to nemá vliv). 

Díky!

**Comment by SykoraLukas** [comment]
Je to naschvál kvůli ePeriodikům. Nikde totiž ndk nespecifikuje, jak se mají pojmenovávat soubory, jestliže jich je více. Rozlišuji to tedy pomocí toho, na co se to pdf váže. Díky tomu to funguje jak pro články a stejně to bude fungovat i pro kapitoly. Pokud má objekt Monografie/Číslo periodika pod sebou jen jedno pdf, drží se stejná názvová konvence.

**Comment by SykoraLukas** [comment]
Dalo by se to upravit na to, že se přebírá jen to číslo a "genre" se vynechá, pokud by s tím byl velký problém. Ale takhle mi přijde, že na první pohled člověk vidí, na co se daný objekt váže.

**Comment by kerschfilip** [comment]
Dobře, to dává smysl a standardu to neodporuje, takže to může zůstat takhle. Jen mi nebylo jasné, proč ta změna :-)

**Comment by SykoraLukas** [comment]
Já to nikam nepsal, protože mě nenapadlo, že to někdo bude takhle detailně kontrovat.
