### ISSUE TITLE
Nelze založit periodikum - nelze překonat chybu - v 3.9

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1501]
V KNAV na v3.9 a na inovatice nelze založit NDK periodikum stažením z katalogu - nepovolená kombinace hodnot v hlášce odpovídá RDA, ale záznam je AACR. Chyba by měla dovolit objekt vytvořit následně na chybu upozorňovat při každém uložení. Stejná chyba je v jádře i v klientovi. Zkusila jsem založit v jádře ve v3.7.3 - bez problémů. 
**Data: NDK periodikum, zdroj katalog KNAV periodika, sysno= 000594603** (nebo 000592877). Např. sys = 000597142 založit lze.
Hláška z jádra:

![image](https://user-images.githubusercontent.com/79305516/200598272-80af1bfe-b6f8-4bd7-bc7a-758af8c2c09f.png)

Hláška z klienta:
![image](https://user-images.githubusercontent.com/79305516/200598822-00ad7e80-6c40-445f-b126-e04bdc778149.png)

**Comment by SykoraLukas** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zkusila jsem teď na inovatice v jádru - opravdu to pořád nejde.

**Comment by SykoraLukas** [comment]
Na inovatice zatím není nasazená oprava.

**Comment by ZdenkaSera** [comment]
aha - díky :-)

**Comment by ZdenkaSera** [comment]
Oba výše testované tituly (000594603 a 000592877) lze ve verzi 4.0.1 založit, takže zavírám.

Problém s chybou při převzetí pole 246 jako tile alternative  je dán specifickým případem, kdy je obsaženo podpole i. Chová se stejně v jádře starších verzí pA.
