### ISSUE TITLE
RDflow - sloupec skenner

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1504]
V RDflow přidat do filtrování záměrů sloupec Skener, který se vyplňuje z úkolu Skenování a podmínkou je stav úkolu Skenování Dokončen.

**Comment by ZdenkaSera** [comment]
Duplicitní k issue https://github.com/proarc/proarc/issues/1463

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, koukl bys na ta dvě propojená issues ke skeneru a jedno zavřel, pokud to zadání taky vnímáš jako duplicitu? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Viz výše - navrhuji k uzavření jako duplicitu k issue https://github.com/proarc/proarc/issues/1463 - je to správně? Díky.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
