### ISSUE TITLE
RDflow - filtrování

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1506]
Filtrování od začátku a bez ohledu na velikost zadaného textu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ve sloupci název funguje dobře. Problém je se sloupcem signatura - pokud obsahuje mezeru, musím za mezerou znovu kliknout do textového pole, aby šlo pokračovat ve psaní. test ve verzi 4.0.2. v KNAV

**Comment by SmejkalovaAnna** [comment]
To, co píše Zdenka, stále trvá....malá velká písmena je v pohodě.

**Comment by SykoraLukas** [comment]
Realizace v novém klientovi

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas vše viz výše funguje hezky a dobře, jediná drobnost, jestli bude @nezbedova pro, aby šlo vyhledávat i v signatuře bez ohledu na malá a velká písmena.... a bude to dokonalé :)

**Comment by SykoraLukas** [comment]
Doplněno ignorovani malych a velkych pismen u Signatury.

**Comment by SmejkalovaAnna** [comment]
Vyzkoušeno

**Comment by ZdenkaSera** [comment]
Zavírám vhledem k návrhu na uzavření.
