### ISSUE TITLE
RDflow - editace záměru přes XML při zakládání

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1508]
Při snaze editace xml se neukládá.

Zkoušeno na Katalog KNAV Monografie, Signatura, E 251

**Comment by SmejkalovaAnna** [comment]
Stále nejde...

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Lukáši mám nějaký problém, nechce se mi zobrazovat nahoře v okně nově založená NDK Vícedílná monografie, zobrazuje se v tom spodním, to je špatně.... v horník okně mi to ani nenajde, když to dám vyhledat....
![obrazek](https://github.com/proarc/proarc/assets/24409660/418fd6b2-f217-4fe5-bf2a-17160f836261)
viz:
![obrazek](https://github.com/proarc/proarc/assets/24409660/3f048d62-bc1b-4b1b-a5e6-f197104407e6)

**Comment by SmejkalovaAnna** [comment]
@SmejkalovaAnna Jinak editace XML při vytváření záměru funguje.....

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Jinak editace XML při vytváření záměru funguje.....

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Mě se tam nezpbrazí ani nově vytvořený Záměr obyčejné monografie.... nemůže být zaseklý filtr? Už se stávalo.... Zítra probereme

**Comment by SmejkalovaAnna** [comment]
@SykoraLukas Promiň Lukáši, smazala jsem historii a cookies a už to vidím všechno....

**Comment by ZdenkaSera** [comment]
@SmejkalovaAnna Aničko, díky, zatím tedy zavírám.
