### ISSUE TITLE
Crossref export - ORCID a ROR ID

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1518]
ještě doplnění k ORCID a ROR ID: bylo by potřeba, aby se tyhle identifikátory propisovaly i do exportu do Crossrefu. Tam by to mělo vypadat asi takhle (popsané je to případně [tady](https://ror.readme.io/docs/include-ror-ids-in-doi-metadata))

```xml
<contributors>
	<person_name sequence="first" contributor_role="author">
		<given_name>Martin</given_name>
		<surname>Lhoták</surname>
		<affiliations>
			<institution>
				<institution_id type="ror">https://ror.org/028sgmw18</institution_id>
			</institution>
		</affiliations>
		<ORCID authenticated="true">https://orcid.org/0000-0003-4649-6702</ORCID>
	</person_name>
</contributors>
```

Problém je trochu to, že podle NK máme ORCID vyplňovat jen jako samostatný kód, ne URL, ale v exportu do Crossreffu je potřeba, aby to mělo podobu celého toho odkazu.

_Originally posted by @kerschfilip in https://github.com/proarc/proarc-client/issues/149#issuecomment-1307322197_

**Comment by SykoraLukas** [comment]
V aktuální verzi 4.6 je pole affiliations nepodporované, musel jsem tedy změnit a předělat na novější verzi 5.3.1.
Jak pro pole ORCID tak pro pole institution_id jsou začátky odkazu předdefinované (https://ror.org/, https://orcid.org/), takže se vždy doplní jen koncovka.

**Comment by ZdenkaSera** [comment]
@SykoraLukas  @kerschfilip Tohle chápu jako připravené k testu (na našem systému) a přidávám štítek.

**Comment by kerschfilip** [comment]
otestováno, funguje. 

Díky!
