### ISSUE TITLE
v3.9/akubra prvni start na praznou repo 40 versus 4 objekty

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1525]
Stovnání chování FEDORA x AKUBRA nad "čístou" repository. PK

https://github.com/proarc/proarc/issues/1515

tomcat@bigfedo:~$ fedora-rebuild.sh

                       Fedora Rebuild Utility
                     ..........................

WARNING: Live rebuilds are not currently supported.
         Make sure your server is stopped before continuing.

Server directory is /home/tomcat/fedora/server

---------------------------------------------------------------------

What do you want to do?

  1) Rebuild the Resource Index.
  2) Rebuild SQL database.
  3) Exit

Enter (1-3) --> 2

Rebuild SQL database.

No options to set. Start rebuilding?

  1) Yes
  2) No, exit.

Enter (1-2) --> 1

Rebuilding...
Cleaning up table: doregistry
Cleaning up table: fcreporebuildstatus
Cleaning up table: modeldeploymentmap
SUCCESS: 0 objects rebuilt.
Finished.
tomcat@bigfedo:~$ fedora-rebuild.sh

                       Fedora Rebuild Utility
                     ..........................

WARNING: Live rebuilds are not currently supported.
         Make sure your server is stopped before continuing.

Server directory is /home/tomcat/fedora/server

---------------------------------------------------------------------

What do you want to do?

  1) Rebuild the Resource Index.
  2) Rebuild SQL database.
  3) Exit

Enter (1-3) --> 1

Rebuild the Resource Index.

No options to set. Start rebuilding?

  1) Yes
  2) No, exit.

Enter (1-2) --> 1

Rebuilding...
Initializing triplestore interface...
Clearing directory /home/tomcat/fedora/data/resourceIndex...
SUCCESS: 0 objects rebuilt.
Finished

proarc.storage=FEDORA

#start PA s práznou repository
systemctl start tomcat 

systemctl stop  tomcat 

tomcat@bigfedo:~$ fedora-rebuild.sh

Rebuilding...
Initializing triplestore interface...
Clearing directory /home/tomcat/fedora/data/resourceIndex...
Adding object #1: model:ndkperiodicalvolume
Adding object #2: model:oldprintmap
Adding object #3: model:oldprintvolume
Adding object #4: model:ndkmonographsupplement
Adding object #5: fedora-system:ServiceDeployment-3.0
Adding object #6: model:ndkmap
Adding object #7: model:ndkpage
Adding object #8: model:ndksheetmusic
Adding object #9: model:ndkchapter
Adding object #10: proarc:audiodevice
Adding object #11: model:ndkeperiodicalvolume
Adding object #12: model:oldprintgraphics
Adding object #13: model:oldprintmonographtitle
Adding object #14: model:ndkpicture
Adding object #15: fedora-system:ServiceDefinition-3.0
Adding object #16: model:ndkmonographvolume
Adding object #17: model:ndkeperiodical
Adding object #18: model:ndkechapter
Adding object #19: fedora-system:ContentModel-3.0
Adding object #20: model:page
Adding object #21: model:proarcobject
Adding object #22: model:ndkperiodicalsupplement
Adding object #23: model:ndkperiodical
Adding object #24: model:ndkperiodicalissue
Adding object #25: model:ndkarticle
Adding object #26: model:oldprintchapter
Adding object #27: model:ndkeperiodicalissue
Adding object #28: model:bdmarticle
Adding object #29: model:ndkemonographvolume
Adding object #30: model:oldprintsheetmusic
Adding object #31: proarc:group
Adding object #32: model:oldprintomnibusvolume
Adding object #33: proarc:device
Adding object #34: model:oldprintpage
Adding object #35: proarc:user
Adding object #36: model:ndkearticle
Adding object #37: model:ndkemonographtitle
Adding object #38: fedora-system:FedoraObject-3.0
Adding object #39: model:ndkmonographtitle
Adding object #40: model:oldprintsupplement
SUCCESS: 40 objects rebuilt.
Finished.

#reseta repo
Rebuilding...
Initializing triplestore interface...
Clearing directory /home/tomcat/fedora/data/resourceIndex...
SUCCESS: 0 objects rebuilt.
Finished.

proarc.storage=AKUBRA

#start PA s práznou repository
systemctl start tomcat 

systemctl stop  tomcat 

Initializing triplestore interface...
Clearing directory /home/tomcat/fedora/data/resourceIndex...
Adding object #1: fedora-system:ServiceDeployment-3.0
Adding object #2: fedora-system:ServiceDefinition-3.0
Adding object #3: fedora-system:ContentModel-3.0
Adding object #4: fedora-system:FedoraObject-3.0
SUCCESS: 4 objects rebuilt.
Finished.

**Comment by PetrKotynek** [comment]
Předpokládám že toto řeší 4.0.1

**Comment by SykoraLukas** [comment]
Ano
