### ISSUE TITLE
Nelze vyhledat přívazky na základě čárového kódu

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1528]
Při zakládání Záměru i Nového objektu se po zadání signatury objeví všechny záznamy s touto signaturou. Pak si mohu jeden vybrat a ten založit.

Pokud vyhledávám podle čárového kódu, tak se nejde jen hlavní dílo, přívazky se nenajdou.

Katalog Knihovna AV CR Monografie - STT - sig TG 9, č.k. 26005307061

Verze: 3.7.3 i Jádro: verze 4.0-dev - build 20230112132812

**Comment by SykoraLukas** [comment]
Toto by bylo dobré probrat s lidmi, co se starají o váš Aleph. 
dotaz do alephu je klasický, nastavení pro 
carkod: @attrset bib-1 @attr 1=5000 @attr 4=1 "%s"
signaturu: @attrset bib-1 @attr 1=5001 @attr 4=1 "%s"

Je potřeba zjistit, jestli všechny ty objekty mají vyplněné odpovídající pole, takhle se mi to zdá, že je buďto špatná konfigurace (což já nevím, protože to takhle funguje od začátku) a nebo spíše nejsou vyplněná tato pole.

Já jen sbírám odpovědi ze strany Alephu a ty zobrazuji.

**Comment by nezbedova** [comment]
@SykoraLukas Děkuji. Vyřeším to u nás.
