### ISSUE TITLE
Validování dat mimo export

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1532]
Udělat novou funkci validace (netýká se validace před exportem). Projít všechno pod objektem a na úrovni čísla, svazku monografie, mapy, grafiky, hudebniny vytvořit záznam ve správě dávek. Lze spustit na úrovni ročníku, více svazku, čísla, svazku monografie, mapy, grafiky, hudebniny. Projít celý a do logu dávky napsat seznam všech chyb.

**Comment by SykoraLukas** [comment]
Nutné definovat, co se má validovat.

Předpokládám, že základ je: 
číslo, svazek monografie, mapa, grafika a hudebnina - obsahuje stránky (ndk stránka, stránka, stt stránka)
číslo, svazek monografie, mapa, grafika a hudebnina - má planý URN:NBN identifikátor
stránky - mají vyplněný index, typ strany, číslo strany
Ndk strany - mají definovanou pozici
Index stran je souvislý vzrůstající

**Comment by luckajirku** [comment]
Ty kontroly potřebujeme spustit před tím, než URN:NBN přidělíme, abychom nepřidělovali URN:NBN něčemu, co bude mít jiné chyby. Tohle by mělo vyskočit až když se spustí export (jako je to teď).

**Comment by luckajirku** [comment]
nevím, jestli se to rozumí automaticky, ale pro jistotu - validace "obsahuje stránku, NDK stránku" by měla proběhnout i zvlášť na těch podřízených modelech - na příloze čísla, příloze monografie

**Comment by luckajirku** [comment]
u objektů s NDK stranami (číslo, svazek monografie, všechny přílohy, svazek vícedílné monografie, mapa, grafika a hudebnina) by ještě byla dobrá kontrola 
- mají definovanou represtranu, a to pouze jednu

**Comment by SykoraLukas** [comment]
Spustitelné jako novou funkci bez následného exportu a zároveň na začátku všech exportů.
Validace URN:NBN jako poslední.

Obsahem bude:
U stran:
- vyplněnost a posloupnost indexu - nepřekonatelná
- vyplněnost čísla stran - nepřekonatelná
- vyplněnost právě jedné reprezentativní strany - nepřekonatelná
- pokud je vyplněná pozice stran, nesmí být po sobě 2x pravá a 2x levá - nepřekonatelná

U objektů obsahující PDF
- kontrola přiřazeného pdf
- kontrola AACR/RDA pravidel

U zvukových dokumentů
- 1 skladba jedna napojená zvuková nahrávka
- 1 část skladby jedna napojená zvuková nahrávka
- kontrola AACR/RDA pravidel

U objektů, které obsahují strany:
- obsahují strany - nepřekovatelná
- lichý počet stran - překovatelná
- kontrola AACR/RDA pravidel

**Comment by ZdenkaSera** [comment]
Napadla mě ještě kontrola duplicitního výskytu elementu "physicalLocation" (resp. "location") - pokud je nastavené stahování signatury z katalogu do ProArcu, vytvoří se pro každou signaturu samostatný element location s vyplněnou siglou jako  physicalLocation - to jsme chtěli, aby se mohl mazat celý element location bez ručního doplňování.
 Vzhledem k existující výjimce pro opakování physicalLocation u vícedílek by to měla být spíš překonatelná kontrola (nebo nastavená podle modelů a překonatelná jen pro vícedílky?).
@luckajirku @SykoraLukas Prosím, co si o tom myslíte?

**Comment by SykoraLukas** [comment]
Můžeš uvést příklad, kdy by to mělo hlásit chybu a kdy by to mělo být v pořádku?

**Comment by ZdenkaSera** [comment]
Domlouvali jsme se telefonicky, tak jen stručnou sumarizaci: 
- "physicalLocation" by se ve všech textových dokumentech mělo vyskytovat nejvýše jednou (v dokumentech s fyzickou předlohou je povinné,  v e-bornech je RA ale také neopakovatelné v případě použití)
- výjimkou je titulová úroveň vícedílné monografie - tam lze v rámci "location" zopakovat "physicalLocation"
- u zvukových dokumentů je povinnost MA a podmínka neopakovatelnosti tam není - pokud půjde jen o upozornění, neměla by kontrola vadit ani zde @katerinasirova ?

**Comment by SykoraLukas** [comment]
Nutné updatovat Object Search schema solru na verzi 3 [dle návodu](https://github.com/proarc/proarc/wiki/Instalace#upgrade-schematu-solru)

**Comment by ZdenkaSera** [comment]
Kontrola na duplicitní location se tak úplně nepovedla. Teď probíhá při vytváření objektu a brání jeho založení, pokud se mi z katalogu stahuje více signatur. Uživatel má mít možnost objekt založit a nechtěná location vymazat. 

![image](https://github.com/user-attachments/assets/d35ad85f-f313-49ef-9137-9d8b82f14c8a)

**Comment by ZdenkaSera** [comment]
Ještě to proberu interně s kolegyněmi - jestli jim bude vyhovovat mazání hned v zakládacím okně, necháme to a počkáme na reakci ostatních knihoven. Zkusíme ještě chování v záměrech.

**Comment by SykoraLukas** [comment]
Ve verzi u nás na masteru již opraveno. Při zakládání z katalogu se chyby ignorují.

**Comment by ZdenkaSera** [comment]
Díky, Lukáši - zkusila jsme to znovu a zjistila jsem, že to nelze překonat, nevytvoří se ani zakládací okno. Na masteru se zdá ok, ale přetestujeme pořádně.

**Comment by ZdenkaSera** [comment]
**Ad duplicitní location** - první test na masteru prošel, ale zvolila jsem nesprávný katalog. Při stahování záznamu z "nihovna AV CR Monografie (base 996" se chyba "Vícenásobný výskyt elementu "Location" opakuje a záznam nezaložím (příklad: STT monografie zakládaná přes signaturu TE 380).

**Comment by SykoraLukas** [comment]
Přes starý klient to založit lze, problém je, že nový klient nepošle informaci o tom, že jsou data stažena z katalogu.

**Comment by ZdenkaSera** [comment]
Aha - jasně, testuji už jen v klientovi. Počkám na @albertoh ;-)

**Comment by SykoraLukas** [comment]
Ono to nejspíše chybí od začátku. Testuje se každý záznam, i když záznamy z katalogu by se při stažení neměly kontrolovat.

[Issue](https://github.com/proarc/proarc-client/issues/593) jsem @albertoh založil.

**Comment by SykoraLukas** [comment]
Nakonec kontrola na výskyt více location přesunuta jen do validace. Při zakládání a úpravě to již problém dělat nebude.

**Comment by SykoraLukas** [comment]
Možné znovu testovat, je nasazeno,

**Comment by ZdenkaSera** [comment]
Vícenásobné location už nebrání založení - ok, díky.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, jak velký vývoj by znamenalo umožnit validace před exportem vypnout v konfiguraci?  Po rychlých opravách problémů se strukturovanými objekty nás napadlo, že někdo může narazit na neobvyklou situaci v datech, přes kterou se s validací nedostane. Díky.

**Comment by SykoraLukas** [comment]
Otazka je, co znamena neobvykla situace - nez tady budeme neco vymyslet, rad bych tento navrh probral na schuzce.

**Comment by tumovam** [comment]
Ještě doplním komentář ze schůzky VT 8.10.2024: "Prozatím nebude možné vypnout validaci, příp. budeme řešit až nastane konkrétní situace. Odkládáme." Uzavírám, otevřeme kdyby nastalo něco "nečekaného" a budeme mít konkrétní příklad :)
