### ISSUE TITLE
v 4.0/akubra prvni beh

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1545]
Zkoušel jsem na 2 strojích i na konfiguraci s apache2 front-endem. Chování je velice podobné. V solru se objevily dokumenty.
A applikaci se nic nezobrazi. Petr Kotýnek

[8_3.zip](https://github.com/proarc/proarc/files/10918602/8_3.zip)
![solr](https://user-images.githubusercontent.com/37083676/223658108-1caad063-529a-4135-87c2-28fea8770c70.png)
![pa400dev](https://user-images.githubusercontent.com/37083676/223658191-94ff4aaf-7291-4f4d-80d0-e64ff96522e6.png)

**Comment by SykoraLukas** [comment]
Smažte prosím data z indexu a zaindexujte znovu. Již by mělo fungovat.

**Comment by PetrKotynek** [comment]
Zkusil jsem na prvnim stroji. Po vymazání se zaindexovalo a položky se objevují v 2 a 3 tím okně. Pouze se mi zdají některé operace nezvykle "táhle" na to že se ta mašina hw nudí. PK
[prvni_jeti_401.zip](https://github.com/proarc/proarc/files/10965438/prvni_jeti_401.zip)

**Comment by PetrKotynek** [comment]
67 objektu za sec +- PK

**Comment by SykoraLukas** [comment]
Co myslíte 2 a 3 oknem?

Podle diskuze s Vláďou a Pavlem je to dobrá rychlost. Jak to prosím vypadá s vytížením disku a procesoru při indexaci?

**Comment by PetrKotynek** [comment]
sprava digitalnich objektů 2 okno je tam jak dřív svítilo "Žádné položky k zobrazení" a 3 je to dole "Vyberte digitální objekt" . Když to najelo poprvé tak to celkem hučelo, viz obrázej , ale po vyprádnění Solru jedna Java 12% CPU druhá 8%. skoro volnoběh. Ale nemám tam ty správná "data" PK
 
![htop](https://user-images.githubusercontent.com/37083676/224952215-cf1bcb5b-8f78-46dc-8f6c-a65202cbe44c.jpg)

**Comment by PetrKotynek** [comment]
Druhý stroj 600 objektů asi kolem  10 sekund. 8G ram virtualka, tak už je solr trochu vidět, 60 procent CPU. PK

**Comment by PetrKotynek** [comment]
a když jsme v tom testovaní  toto také chodí:
INFO] Reactor Summary for ProArc 4.0.1:
[INFO]
[INFO] ProArc ............................................. SUCCESS [  1.409 s]
[INFO] ProArc METS JAXB Model ............................. SUCCESS [  4.688 s]
[INFO] ProArc MIX JAXB Model .............................. SUCCESS [  1.900 s]
[INFO] ProArc PREMIS JAXB Model ........................... SUCCESS [  0.971 s]
[INFO] ProArc MODS JAXB Model ............................. SUCCESS [  0.625 s]
[INFO] ProArc DESA Client ................................. SUCCESS [ 10.289 s]
[INFO] ProArc URNNBN ...................................... SUCCESS [  1.059 s]
[INFO] ProArc OAI Dublin Core JAXB Model .................. SUCCESS [  0.647 s]
[INFO] Z3950 Client ....................................... SUCCESS [  0.619 s]
[INFO] ProArc NSESSS JAXB Model ........................... SUCCESS [  0.338 s]
[INFO] ProArc AES57 JAXB Model ............................ SUCCESS [  1.278 s]
[INFO] ProArc Coding History JAXB Model ................... SUCCESS [  0.143 s]
[INFO] ProArc Foxml JAXB Model ............................ SUCCESS [  0.204 s]
[INFO] ProArc Common Library .............................. SUCCESS [ 13.141 s]
[INFO] ProArc Authentication .............................. SUCCESS [  0.301 s]
[INFO] ProArc Web Application ............................. SUCCESS [03:55 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:33 min
[INFO] Finished at: 2023-03-14T06:42:57+01:00
[INFO] ------------------------------------------------------------------------
