### ISSUE TITLE
Location - PhysicalLocation - kontrolovany slovnik

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1551]
Kontrolovat hodnoty z pole PhysicalLocation proti kontrolovatelnemu slovniku z konfigurace.

**Comment by SykoraLukas** [comment]
V klientovi vyřešene v https://github.com/proarc/proarc-client/issues/313

**Comment by ZdenkaSera** [comment]
@SykoraLukas Moc díky - udělals to rychleji než já založila issue.

**Comment by SykoraLukas** [comment]
Nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#mods---location--physicallocation)
