### ISSUE TITLE
Omezení exportu pro CEJSH - peer-reviewed + abstract

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1556]
Zdravím,

potřebovali bychom změnit podmínku, podle které se připravuje export pro CEJSH. Nyní záleží jen na tom, jestli je článek recenzovaný, nebo ne. Nově bychom potřebovali, aby byla splněna podmínka, že článek _je recenzovaný **a zároveň** má vyplněný abstrakt v angličtině_ (`<mods:abstract lang="eng">`)

V exportu jinak musí být zachována ta data co jsou teď, takže základní bibliografické údaje, překlad článku v angličtině, abstrakt a klíčová slova v angličtině. 

Děkujeme!

**Comment by kerschfilip** [comment]
Nová podmínka funguje, díky!

Ale objevil se problém: u nově vytvořených článků chybí v exportu klíčová slova. U dříve založených článků s tím problém není

**Comment by SykoraLukas** [comment]
Můžeš mi prosím poslat MARC21 tohoto záznamu? V katalogu se neukazuje a podle stažení se stáhne do nonSort hodnota "The " včetně mezery. Vypadá to tedy, že hodnota v @ind2 je špatně nastavena ale raději bych to ověřil. 

CEJSH poté vezmem nonsort a přidá za něj svou mezeru a teprve poté dá pole title a tudíž vznikne zdvojená hodnota mezery.

**Comment by kerschfilip** [comment]
Stačí takhle? http://aleph.lib.cas.cz/F/?func=direct&doc_number=002634112&local_base=AV

Člen se stáhne do nonSort i s mezerou - ale pokud se budeme držet standardu, tak je to vlastně správně. To znamená nedala by se ta mezera při CEJSH exportu nepřidávat?

**Comment by SykoraLukas** [comment]
Ano, to by byla možnost.

**Comment by kerschfilip** [comment]
Ještě jsme to jednou a pořádně přetestovali a máme teda dva problémy:

__klíčová slova__  
klíčová slova se do CEJSH exportu nedostanou v případě zakládání článku ručně, když se stáhne z katalogu, tak to funguje v pořádku u starých i nových článků.   
Důvod je v tom, co šlo mailem - podle současného pravidla v šabloně musí být u `/subject/topic` atribut `lang="eng"` nebo `"cze`", jinak se klíčová slova do exportu nedostanou.  
Problém je, že při ručním zakládání článku v novém klientovi tam ten atribut nejde dostat. Když se u klíčových slov vybere jazyk, tak se propíše k elementu `subject`, měl by se ale propsat až k `/subject/topic` 

__dvojitá mezera__
v elementu `nonSort` by měl být člen vyplněný i s mezerou, při stahování z katalogu se to stáhne správně a při použití takového toho "šoupátka" v novém klientovi se mezera taky udělá.   Prosím teda upravit export pro CEJSH (a Crossref) tak, aby mezeru nepřidával.

**Comment by kerschfilip** [comment]
Co přesně je, prosím, k testování? Koukal jsem teď na Klienta verze v2.0.2 (24.04.2023) a vypadá to, že ten atribut `lang` už se správně propisuje k `/subject/topic`

Dvojitou mezeru ale neumím vyzkoušet - export na Inovatice nezkontroluju, takže předpokládám, že musíme počkat do dalšího releasu jádra?

**Comment by SykoraLukas** [comment]
Tady šlo hlavně o ten formulář a atribut `lang`.

On je i export, ale ten vyzkoušíte až s novým releasem.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tomuhle jsme nepřidali milestone - prosím, bude ten export v nejbližším releasu zahrnut? Díky.

**Comment by SykoraLukas** [comment]
ano

**Comment by kerschfilip** [comment]
Klíčová slova jsou OK, dvojitá mezera u CEJSH exportu taky. U Crossref exportu ale bohužel ne:  v případě, že se u názvu článku vyplní element nonSort správně (bude tedy obsahovat předložku+mezeru třeba `<nonSort>The </nonSort>`) propíší se do exportu pro Crossref dvě mezery:
![image](https://github.com/proarc/proarc/assets/57805328/cbf8b7a5-5fbf-47aa-9c9e-ab7509aeac1d)

@SykoraLukas prosím o stejnou úpravu jako u exportu pro CESJH. Děkuju

**Comment by ZdenkaSera** [comment]
Tohle vypadá jako připravené, tak sem přidávám štítek prio jen pro evidenci "nutných" úkolů ve fixu posledního releasu.

**Comment by kerschfilip** [comment]
Funguje, moc díky. Zavírám
