### ISSUE TITLE
Nestahuje se ISBN recenzovaného díla

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1561]
Při stahování metadat k ečlánku z katalogu se do části relatedItem nepropisuje ISBN recenzovaného díla (pole `787` podpole `$z`), přestože v záznamu je. Nechybí, prosím, v transformační šabloně z MARCu pravidlo pro převod tohoto podpole?

Otestovat to lze napříkad na tomto záznamu: https://katalog.lib.cas.cz/KNAV/Record/002790322?sid=7357910#details

Díky za ověření!

**Comment by SykoraLukas** [comment]
Ano, toto pole v šabloně vůbec není. Mám to doplnit?

PS: palec nahoru za rovnou přiložený záznam na testovaní

**Comment by kerschfilip** [comment]
Díky, ano, prosím doplnit.

**Comment by kerschfilip** [comment]
Funguje, díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
