### ISSUE TITLE
4.0.2 akubra pokus o import dat

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1562]
Zdravím,
pokoušel jsem se naimportovat testovací data pro kauzu "timeout při expotu do Krameria" a celkem jsem narazil. PK

14. 4. 2023 10:36:48
ERROR false
x:search
RequestHandlerBase
org.apache.solr.common.SolrException: undefined field: "pagePosition"
![err_solr](https://user-images.githubusercontent.com/37083676/232031343-e2803527-561e-44ee-b17f-28a2b1f5b096.png)
[logy_144.zip](https://github.com/proarc/proarc/files/11232226/logy_144.zip)

**Comment by SykoraLukas** [comment]
Prosím o kontrolu šablony SOLRU a případný update.

Nejsem si jist do jaké verze ale přidávalo se toto pole pagePosition.

<field name="pageNumber" type="string"/>
    <field name="pageType" type="string"/>
    <field name="pageIndex" type="string"/>
    <field name="pagePosition" type="string"/>

https://github.com/proarc/proarc/blob/master/proarc-common/src/main/resources/cz/cas/lib/proarc/common/solr/schema/schema_v1.xml

**Comment by PetrKotynek** [comment]
To je ono, už to reindexoval.  Chybí mi v obou instancích field name="pagePosition" type="string" PK
