### ISSUE TITLE
Issuance periodika - continuing vs serial

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1564]
Podle šablony by se u periodik nejspíš měla jako "issuance" doplňovat hodnota "serial", "continuing" by mělo být úplně vypnuté, pokud je tohle jediné místo, které to řídí:
Revision 1.94 - Leader 07 b changed mapping from continuing to serial tmee 2014/02/21
xsl:when test="$leader7='b' or $leader7='s'">serial</xsl:when>

Na inovatice je nově založený objekt 86d2d3c8-0ffb-477b-8ade-721d8ffd6293
- zdrojem je KNAV/ sysno = 000594019 (návěští: 00000n**as** a2200000 a 4500)
- issuance:  <mods:issuance>continuing</mods:issuance>
- v novém klientovi navíc ve formuláři nelze přepsat, viz issue https://github.com/proarc/proarc-client/issues/311

Prosím o radu - co děláme  (nebo máme v datech) špatně? Děkuji.

**Comment by luckajirku** [comment]
Jen propojím na starší "probíhající" issue na klientovi, kde se řeší to samé https://github.com/proarc/proarc-client/issues/101
a související issue na standardech https://github.com/NLCR/Standard_NDK/issues/148

**Comment by SykoraLukas** [comment]
Ok, takže jestli to dobře chápu, tak to tvrdé přepisování na `continuing` bych odstranit a v šabloně poté zůstane jen: 

```
<xsl:when test="$leader7='i'">integrating resource</xsl:when>
<xsl:when test="$leader7='b' or $leader7='s'">serial</xsl:when>
```

Pokud něco `continuing` už má z dřívější doby tak to nebudeme měnit a nové už podle těchto pravidel?

Souhlas @luckajirku a @ZdenkaSera?

**Comment by ZdenkaSera** [comment]
Omlouvám se za duplicitu a děkuji za upozornění - issuse jsem sice procházela, ale je jich moc a tohle mi nezůstalo v paměti.

@luckajirku Vzhledem k vyjádření NK bych byla pro návrh @SykoraLukas Jste pro?

**Comment by luckajirku** [comment]
Samozřejmě - nové překlápět správně (tady není nic k diskusi), a ty starší - taky souhlasím, nechala bych jak jsou.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím tedy o úpravu. Děkuji oběma.

**Comment by luckajirku** [comment]
Teď jsem narazila na související problém u dalších výskytů originInfo. Pokud má periodikum více vydavatelů/míst vydání a zakládá se nám na každý originInfo, tak by se ale mělo to issuance nastavit u všech. Teď se mi to vyplní hodnotu jen v prvním výskytu, ale u těch dalších mám v issuance jako hodnotu pomlčku.

**Comment by ZdenkaSera** [comment]
S tím souvisí také stále otevřené issue https://github.com/proarc/proarc/issues/739

**Comment by ZdenkaSera** [comment]
Do periodika se jako issuance stál "serial", pole je odemčené pro změnu hodnoty. test na Inovatoice ok.

**Comment by ZdenkaSera** [comment]
Byl nahoře v zadání - sysno  000594019 v KNAV, ale tohle už je ok :-)

**Comment by SykoraLukas** [comment]
S tím, co psala @luckajirku tedy problém není?

**Comment by ZdenkaSera** [comment]
Aha - jasně, je, issuance se u periodik stále vyplňuje jen u prvního origininfo. To jsem přesunula do issue, kde se řeší obsah origninfo. Ale pokud tuhle část vyřešíš obratem tady, tím líp :-)

**Comment by SykoraLukas** [comment]
Opraveno, bude v další verzi aplikace.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
