### ISSUE TITLE
Anonymizace FOXML exportu pro Kramerius

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1573]
V KNAV bychom potřebovali, aby ve FOXML exportu pro Kramerius nebylo v poli `ownerID` uvedeno přihlašovací jméno zpracovatele dokumentu. Ideální by bylo, aby se na závěr exportu hodnota v tomto poli nahradila nějakým obecným řetězcem.

teď máme ve FOXML například tohle:
`<foxml:property NAME="info:fedora/fedora-system:def/model#ownerId" VALUE="vrb1454"/>`

Potřebovali bychom, aby to vypadalo pro všechny zpracovatele stejně, například takhle:
`<foxml:property NAME="info:fedora/fedora-system:def/model#ownerId" VALUE="ProArc"/>`

@SykoraLukas prosím jak složité by bylo tohle zavést? Díky!

**Comment by SykoraLukas** [comment]
Tohle by asi nebyl takový problém, ale problém je u importu FOXML zpět do ProArcu. Nedalo by se pak hledat podle zpracovatele (otázkou je, jestli to nyní lze)

**Comment by kerschfilip** [comment]
Zkusil jsem FOXML export z jednoho ProArcu naimportovat do jiného a stejně tak Export z Krameria naimportovat do ProArcu a vždycky to původní hodnotu `ownerId` přepsalo jménem mého uživatele. Takže to vypadá, že se podle zpracovatele po importu stejně už hledat nedá

**Comment by SykoraLukas** [comment]
Tím pádem asi není problém toto udělat. Počítej tak 1 MD.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, potřebná konfigurace bude popsaná tady nebo jen na wiki? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, zkusila jsem si na inovatice zobrazit foxml, tam k anonymizaci nedochází. K nahrazování uživatelů dojde jen při exportu. nebo na inovatice není konfig? Díéky.

**Comment by SykoraLukas** [comment]
Ano, jen při exportu. 

Zobrazení FOXML je nad živými daty, takže tam to anonymizovat nelze (zobrazí se foxml z filesystemu).

**Comment by kerschfilip** [comment]
anonymizace funguje, díky!

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
