### ISSUE TITLE
Export K4 objektu bez skenů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1574]
Ve verzi 4.0.2. jde objekt bez skenů exportovat jako K4 - v dialogu dá jádro ok odpověď, status log taky OK. Klient to přebírá, chová se stejně.

**Comment by SykoraLukas** [comment]
Toto neni chyba. Kramerius export nekontroluje strukturu - ne vše musí mít skeny. Pokud ale obsahuje strany, tak se u stran kontroluje, že obsahují požadované hodnoty.

**Comment by ZdenkaSera** [comment]
Dobře, díky. Exporty K4, archivu i NDK balíčku se chovají správně ať mají chybu ve skenech nebo ne, to je ok. Tohle bez skenů mne nikdy dřív nenapadlo zkusit. Zavírám issue.

**Comment by SykoraLukas** [comment]
Jde o to, že NDK i Archive vychází z nějakého předpisu a tedy tam na základě modelu se rozhoduje o tom, jaké může mít potomky a jestli musí mít stranu a sken. K4 nic takového nemá.
