### ISSUE TITLE
Nejde mazat v PA DC produkcni KNAV 4.0.2 Fedora

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1575]
Přikládám logy PK

zsera
Ve verzi nasazené dnes na proarc-dc-test.lib.cas.cz
nejde mazat STT ani NDK monografie. Ani Aničce ani mně (mám větší práva, tak jsem to zkusila)
Když jsem testovala, tak to šlo. Smazala jsem STT a pak tam nahrála archivebalíček.
 zkusila jsem ještě založit nový objekt a smazat ten, ale ani to nelze, takže nebude problém v chování objektů vytvořených v nižších verzích před posledním upgradem.

[log.zip](https://github.com/proarc/proarc/files/11460247/log.zip)

![obrazek](https://github.com/proarc/proarc/assets/37083676/8f346cf5-e83d-49a6-903a-83a54908df6d)
[err11_05dc.txt](https://github.com/proarc/proarc/files/11460257/err11_05dc.txt)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zkusila jsem objekt, který nešel smazat v jádře, smazat v klientovi, to se podařilo. Problém v jádře trvá.

**Comment by SykoraLukas** [comment]
Vyrešeno,  bude opraveno v další verzi.

**Comment by ZdenkaSera** [comment]
Zkoušela jsem mazat v jádře i klientovi na KNAV testovací instanci - zatím všechno ok, navrhuji uzavření.

**Comment by ZdenkaSera** [comment]
Zavírám dle domluvy ze schůzky 15. 6. 2023.
