### ISSUE TITLE
Opravy urn:nbn - fáze I - Následovník

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1588]
Část společná pro všechna issues "Opravy urn:nbn" je zde https://github.com/proarc/proarc/issues/1465

**Následovník - fáze I - na tuto variantu není žádný "workaround", vazba se nedá vytvořit ručně přes uživatelské rozhraní**

Podle konzultace s NK: Pro založení vazby následovníka (respektive spíše předchůdce) se má postupovat podle tohoto: https://github.com/NLCR/CZIDLO/wiki/API-v3---p%C5%99%C3%ADklady#m%C3%B3dy-registrace-1
Na API resolveru se pošle tento request:
![image](https://github.com/proarc/proarc/assets/79305516/3021534f-1c43-4a15-821b-4d3448002c74)

Tím, že bude v elementu <urnNbn> uvedeno jen urn:nbn předchůdce, se automaticky staré urn:nbn deaktivuje a vytvoří se nové (v módu BY_RESOLVER), které se vrátí jako odpověď na dotaz. UUID není třeba vymazávat a zůstává stejné.

**Použití**

- Sloučení dokumentů – sloučením dokumentů se rozumí stav, kdy se dvě a více odlišných intelektuálních entit spojí do jedné intelektuální entity.
- Rozdělení dokumentu – rozdělení jedné intelektuální entity do dvou nebo více intelektuálních entit.
- Oprava popisu dokumentu, která nepovede k záměně intelektuálních entit (oprava překlepů nebo chybějící části názvu).
- Signifikantně jiná digitalizace téže intelektuální entity v rámci jednoho vlastníka.
- Doskenování nebo přeskenování původního dokumentu v rámci stejné digitalizace (tedy doplnění nebo vyměnění obrazových souborů náležející k popisným metadatům v takovém případě musí být důvod vytvoření vazby na následníka zapsán v poznámce [note] requestu do resolveru)

**Comment by SykoraLukas** [comment]
Po potvrzení od Martina Řehánka je potřeba nejprve smazat uuid z původního objektu v Resolveru a následně až zavolat rozšířenou registraci nového objektu a vazbu na předchůdce.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tohle funguje, jen je v resolveru u záznamu zalogovaná chyba - prosím, podíváš se na to? 
uuid z inovatiky-masteru: 5d7b0634-8ccf-4463-a1a5-4695e0b27773 k dohledání tady https://resolver-test.nkp.cz/web/#tab2

log: https://resolver-test.nkp.cz/api/v6/resolver/urn:nbn:cz:aba007-00010m

![image](https://github.com/proarc/proarc/assets/79305516/76e061ac-4b5b-4f89-ab19-4aa132792706)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, připomeň mi - ten text, který se posílá (Úprava metadat objektu.) je někde v konfiguraci nebo napevno? Děkuju.

**Comment by SykoraLukas** [comment]
O jaké chybě se bavíme? Že nejde zobrazit záznam předchůdce? To ale není problém ProArcu, ale CZIDLA, je tam z nějakého důvodu odkaz na API verze 6.

**Comment by ZdenkaSera** [comment]
Upřesnění telefonem.
