### ISSUE TITLE
V metadatech nelze změnit/uložit siglu knihovny

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1592]
Kolegyni se povedla zajímavá chyba - u nás na testu kolegyně založila nové číslo pod ročníkem a při kontrole metadat zjistila, že nemá vyplněnou naši siglu, při snaze uložit to hází tuto hlášku:

![image](https://github.com/proarc/proarc/assets/8912422/b276fe0c-2263-4ad9-a52d-ec4943d8d6a8)

Zajímavé je, že to takto nejde u 2 čísel a další čísla už jdou uložit.

Při snaze reprodukovat chybu na inovatice jsem chtěla přepsat naši siglu v už vytvořeném záznamu čísla nebo ročníku a pokaždé to vyhodilo tuto hlášku s tím, že nejde překonat a objevuje se stále dokola. 

Když v našem testovacím PA odkliknu, že nechci uložit, tak mě to nechá uložit bez sigly tak, jak to bylo původně, ale s vyplněnou signaturou a ani to nehlásí chybu.

**Comment by SykoraLukas** [comment]
Potřebuji videt, jak vypada xml záznam (idealne z dynamickeho xml - abz se do nej propsala ta spatna sigla).

**Comment by katerinasirova** [comment]
1. dnes už to chybu na inovatice při editaci stejného souboru jako včera nehlásí, xml kopíruji, ale asi nebude k ničemu, když to funguje - vyzkoušela jsem i na jiných a dnes lze přepsat a změnu uložit:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre type="normal">issue</mods:genre>
    <mods:identifier type="uuid">074691d7-e5df-439d-b18b-4b180b70edd4</mods:identifier>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">cze</mods:languageTerm>
    </mods:language>
    <mods:location>
        <mods:physicalLocation authority="siglaADR">ABG001</mods:physicalLocation>
        <mods:shelfLocator>1908 VT 11011</mods:shelfLocator>
    </mods:location>
    <mods:originInfo>
        <mods:dateIssued>1/1908</mods:dateIssued>
    </mods:originInfo>
    <mods:recordInfo>
        <mods:recordCreationDate encoding="iso8601">20230511T110323</mods:recordCreationDate>
        <mods:recordChangeDate encoding="iso8601">20230629T084355</mods:recordChangeDate>
        <mods:descriptionStandard>aacr</mods:descriptionStandard>
    </mods:recordInfo>
    <mods:titleInfo>
        <mods:title>Hudební revue</mods:title>
        <mods:partNumber>1</mods:partNumber>
    </mods:titleInfo>
</mods:mods>

2. problém nastává ve chvíli, kdy se podaří uložit nebo založit číslo bez sigly - to potom stále hlásí tuhle hlášku u nás i na inovatice (vyřešit lze tím, že edituju XML a potom se mi hodnota ve formuláři objeví):

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.6" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre type="normal">issue</mods:genre>
    <mods:identifier type="uuid">63f898b1-783a-41af-a6a4-132041724604</mods:identifier>
    <mods:language>
        <mods:languageTerm authority="iso639-2b" type="code">cze</mods:languageTerm>
    </mods:language>
    <mods:location>
        <mods:shelfLocator>1909 VT 11011</mods:shelfLocator>
    </mods:location>
    <mods:originInfo>
        <mods:dateIssued>1909</mods:dateIssued>
    </mods:originInfo>
    <mods:recordInfo>
        <mods:recordCreationDate encoding="iso8601">20230612T100425</mods:recordCreationDate>
        <mods:recordChangeDate encoding="iso8601">20230629T085054</mods:recordChangeDate>
        <mods:descriptionStandard>aacr</mods:descriptionStandard>
    </mods:recordInfo>
    <mods:titleInfo>
        <mods:title>Hudební revue</mods:title>
        <mods:partNumber>1</mods:partNumber>
    </mods:titleInfo>
</mods:mods>

**Comment by SykoraLukas** [comment]
Potřebuji ukázku záznamu (katalog, pole, hodnota) abych mohl nasimulovat.

**Comment by katerinasirova** [comment]
Záznam nebylo vytvořený stažením z katalogu, ale ručně zadáním údajů. Problém s tím, že se sigla při vytváření čísla neuložila se bojím, že nenasimulujeme, ale potřebujeme vyřešit to, že když máš z nějakého důvodu prázdné pole pro siglu a chceš tam doplnit nějakou, tak ji to prostě neuloží a zobrazí hlášku (viz výše), která nejde překonat.

**Comment by ZdenkaSera** [comment]
Zkusila jsem to nasimulovat u nás - pod existující ročník periodika jsem si pluskem přidala číslo bez stažení z katalogu. Převzaly se mi údaje z titulu, tak jsem siglu vymazala hned v "plovoucím" formuláři a dala uložit s nevalidními daty a přejít do objektu. V editaci jsem pak ručně přidala siglu a popisovaná chyba se zobrazila.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Za mne ok, chybu při změně sigly se mi už na Inovatice nepovedlo nasimulovat. Díky.
Přidávám štítek prio kvůli zahrnutí do release-next.
