### ISSUE TITLE
Export archivu bez urn:nbn

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1594]
Exportovala jsem archiv monografie (stejně se zachovalo i při exportu vícedílné mono) bez urn:nbn - proces se spustil na pozadí, výsledkem byl status "chyba exportu" ve správě procesů a tahle hláška pod "i":

![image](https://github.com/proarc/proarc-client/assets/79305516/36df49ba-8d5a-4534-b397-aa4a9dd88e53)

V předchozí verzi (4.0.2/2.0.2) se chová takto: Dostanu hlášku

![image](https://github.com/proarc/proarc-client/assets/79305516/fe24568d-1ba6-4034-a187-dd0e59374208)

![image](https://github.com/proarc/proarc-client/assets/79305516/d4878244-dec8-400a-a795-3976b2967c38)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, je to skoro ono - zatím test u NDK mono a STT mono . Kdyby se tlačítko "přesto exportovat" zobrazovalo jen u STT, bylo by to lepší. u NDK mě to sice nepustí dál, ale trošku to mate (stačilo by to tlačítko jen zneaktivnit). U STT mi dovolilo export archivu spustit 👍

![image](https://github.com/proarc/proarc/assets/79305516/5cb482cd-ed6e-471a-bc58-5acbddb85b60)

**Comment by SykoraLukas** [comment]
@albertoh prosím upravíš chování klienta podle komentáře? U STT tisků nabízet tlačítko `Přesto exportovat`, jinak tlačítko nenabízet.

**Comment by albertoh** [comment]
Opraveno

**Comment by ZdenkaSera** [comment]
Přetestovala jsem export STT bez urn:nbn - to šlo, export doběhl ok. Vyzkoušela jsem k existující STT VD přidat další díl, přidělení urn:nbn k novému dílu bez problémů. U 2. části jsem pak urn:nbn nastavila jako invalid - export archivu hlásí chybu, takže super.

@albertoh @SykoraLukas Jediné, co bych ještě prosila opravit je uuid, u kterého export hlásí chybu urn:nbn - vždycky vypíše jen uuid úrovně vícedílky, lepší by byl ten konkrétní dílu - viz obrázek z inovatiky (nemám teď vyzkoušeno na periodikách, tam by správné uuid bylo ještě důležitější). Díky

![image](https://github.com/proarc/proarc/assets/79305516/93d7237e-e79c-4127-9b9e-48f08ec5e057)

**Comment by ZdenkaSera** [comment]
U non-STT exportu archivu bez urn:nbn se už nenabízí možnost "přesto pokračovat" - prima, díky. @albertoh

**Comment by SykoraLukas** [comment]
Opraveno, prosím o znovuotestování

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkuji, to vypadá dobře.
