### ISSUE TITLE
Převod "Stran" na NDK a zpět - nehlásí chybu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1599]
@albertoh Pokud se při spuštění převodu Stran na NDK strany nepodaří převést všechny, systém nevydá hlášení o chybě, ale sdělí, že byly úspěšně převedeny. Problém se objevil už v minulé verzi klienta, ale u nové se nepodařilo otestovat na Inovatice (tj. nedaří se tam nasimulovat chybu).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky, otestujeme ale az doma. Leda bychom zkusili na Inovatiku nahrát soubor, na kterém mi to padlo u nás a pak jej smazali, aby nezabíral prostor.

**Comment by SykoraLukas** [comment]
Zkusit to můžeme, ale nevím, zda se bude chyba opakovat ...

**Comment by ZdenkaSera** [comment]
Domluveno, test až v Knav.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tohle se chová pořád stejně, jak jsem popsala nahoře. Ale nevím, jestli nedošlo k omylu - jde o problém v klientovi, to issue jsem omylem založila v jádře.

Při testu v jádře jsem ale zjistila, že je hláška vylepšená o počet převedených stran, to je prima 👍 Jen ještě prosím kosmetiku - překlep "převýst"  opravit na "převést", Případně by i zbytek hlášky mohl být česky. Děkuji

![image](https://github.com/proarc/proarc/assets/79305516/d4d339be-14da-429b-a8bc-db6396142e75)

**Comment by SykoraLukas** [comment]
Opraveno.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Chybu na Inovatice neumím nasimulovat, tak jen prosím info - oprava se týká jen té hlášky v jádře nebo odchytávání chyby v klientovi? Děkuju.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Shrnutí, než to zapomenu :-) 
Platí v jádře i v klientovi:
- pokud proces převodu vůbec nezačne (např. nad zamčeným objektem), dostanu chybovou hlášku
- pokud proces nedoběhne do konce, dostanu hlášení, že bylo převedeno x stran z celkových y; převod pak - jako dosud - pouštím opakovaně, dokud se nepřevede všechno

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, budete k tomu vydávat i verzi klienta? S verzí 2.1.2 to opravdu nefunguje -  zkusila jsem převod stran nad zamčeným objektem. Nic se nepřevedlo, ale klient potvrdil úspěšnou akci.  Děkuju.

**Comment by SykoraLukas** [comment]
@albertoh mohl bych te poprosit o vydání verze z masteru?

**Comment by ZdenkaSera** [comment]
@SykoraLukas V klientovi se ještě asi něco nepovedlo, tam je situace stále stejná, pořád hlásí, že je vše ok bez ohledu na výsledek.

V jádře to chybu hlídá, uvedené počty jsou správně, jen prosím o překlad hlášky do češtiny. 

![image](https://github.com/proarc/proarc/assets/79305516/aa3e26d7-3d00-4f97-a446-212f540d3617)

**Comment by ZdenkaSera** [comment]
Ještě doplňuji, že se v jádře i v klientovi do seznamu možných převodů vrátily i varianty dříve vypnuté

![image](https://github.com/proarc/proarc/assets/79305516/cea18b31-0bfe-4fd3-bfc7-661b903d337a)


![image](https://github.com/proarc/proarc/assets/79305516/29d745c0-90bb-4860-8ae9-86703d40a2b8)

**Comment by SykoraLukas** [comment]
Mají zůstat vypnuté? MZK si je totiž vyžádala (Špatně naimportovali NDK a potřebovali z nich vytvořit STT strany).

**Comment by ZdenkaSera** [comment]
Aha - to jsem netušila. jasně, pokud to potřebují, musí to tam zůstat.  Díky za info.

**Comment by SykoraLukas** [comment]
Pokud teda s tím souhlasíš tak podle tvých komentářů navrhuji toto dát k testu a nového klienta dořešit v issue k tomuto.

**Comment by luckajirku** [comment]
@SykoraLukas a to máš teď z MZK nějak čerstvě? jak se to před časem řešilo tady https://github.com/proarc/proarc-client/issues/210, tak to už pak taky nechtěli ani v Brně.

**Comment by SykoraLukas** [comment]
Ano, chtěli to na nějakou historickou opravu. Ale můžeme to asi opět zrušit, pokud to již je hotové @erikamirova?

**Comment by erikamirova** [comment]
@SykoraLukas Můžete to zrušit, už bychom to neměli potřebovat. Šlo o nějakou zapomenutou věc, která nám pak dělala problémy s archivací.

**Comment by ZdenkaSera** [comment]
@SykoraLukas V KNAV převody STT stran na NDK a zpět možná využijeme při přechodu na Krameria 7. Pokud je tedy jen na nás, pak prosíme ponechat zeleně označené možnosti. Na Inovatice-masteru jsem to otestovala a je to ok (jen funkčost, chybu tam nenasimuluji) Díky.

![image](https://github.com/proarc/proarc/assets/79305516/a91fcb57-0523-4415-9d84-bd7865ea400d)

**Comment by SykoraLukas** [comment]
Řešeno v odpovídajícím issue na [klientovi](https://github.com/proarc/proarc-client/issues/424)

**Comment by ZdenkaSera** [comment]
Přetestováno v KNAV na verzi 4.1.0 - nenašla jsme protipříklad, zavírám.
