### ISSUE TITLE
chyba pri K5 autoimportu err 403

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1600]
Při automatickém importu se objevila následující chyba : 

[kra_ex.txt](https://github.com/proarc/proarc/files/12229891/kra_ex.txt)

K5 skutečně neúplně  naimportoval.

Tento chybový stav se nepodařilo zopakovat - na straně PA objevilo něco jako false-positive hlášení o chybě, která po obnově 
UI zezelenalo. Na straně K5 import proběhl. 

výchozí nastavení máme, 
krameriusInstance.k5prod.deleteAfterImport=true
a importy OK na všech testovacích instancích

Za účelem ladění byl nastaven
krameriusInstance.k5prod.deleteAfterImport=false.

Poté ingest nadále bez problému i na ostrém K5. 

Máme podezření , že K5 dostatečně rychle neodpoví na dotaz o stavu naplanovaného procesu a mezitím začne na
základě volby krameriusInstance.k5prod.deleteAfterImport=true  mazat rychleji než začne vlastní import. 
Jak v reálu probíhá komunikace na toto téma , jak rychle PA vyhodnotí případný domělý nenúspěch autoimportu.
???
děkuji PK

**Comment by PetrKotynek** [comment]
Vylitne to na 
            int status = conn.getResponseCode();

[from_kramerius.K5Importer.txt](https://github.com/proarc/proarc/files/12236381/from_kramerius.K5Importer.txt)

PK

**Comment by SykoraLukas** [comment]
poslete mi prosim na mail konfiguraci krameriusinstance.* dekuji

**Comment by PetrKotynek** [comment]
Upraveny konfigurace podle templates, vstupní URL bez koncového lomítka k zamezení zdvojení /

krameriusInstance.k5test.url=https://k4test.lib.cas.cz/ na krameriusInstance.k5test.url=https://k4test.lib.cas.cz

krameriusInstance.k5prod.url=https://kramerius.lib.cas.cz/ na  krameriusInstance.k5prod.url=https://kramerius.lib.cas.cz

PK

**Comment by PetrKotynek** [comment]
Na vsech produkcnich odkazech je
krameriusInstance.k5prod.deleteAfterImport=false
na vsech testovacich odazech je
.deleteAfterImport=true
PK

**Comment by PetrKotynek** [comment]
Která z těchto varování jsou, prosím,  závažná ? děkuji PK

Srp 09, 2023 1:37:11 ODP. cz.cas.lib.proarc.common.kramerius.KrameriusOptions warning
WARNING: Missing krameriusInstance.k7test.krameriusImportFoxmlFolder in proarc.cfg
Srp 09, 2023 1:37:11 ODP. cz.cas.lib.proarc.common.kramerius.KrameriusOptions warning
WARNING: Missing krameriusInstance.k7test.urlDownloadFoxml in proarc.cfg
Srp 09, 2023 1:37:11 ODP. cz.cas.lib.proarc.common.kramerius.KrameriusOptions warning
WARNING: Missing krameriusInstance.k7test.urlImage in proarc.cfg
Srp 09, 2023 1:37:11 ODP. cz.cas.lib.proarc.common.kramerius.KrameriusOptions warning
WARNING: Missing krameriusInstance.k7test.grantType in proarc.cfg

Pochybnost vzbuzuje především .krameriusImportFoxmlFolder viz

wiki
Cesta, na serveru Krameria, kde je importní složka
Pouze pro verzi 5
krameriusInstance.kramerius5.krameriusImportFoxmlFolder=/opt/app-root/src/.kramerius4/import/

pro K5 u nás nastaveno, asi dobře
krameriusInstance.k5test.krameriusImportFoxmlFolder=/home/k4test/.kramerius4/import-auto/
krameriusInstance.k5prod.krameriusImportFoxmlFolder=/home/kramerius/.kramerius4/import-auto-proarc-test.libj.cas.cz

a taktéž varování kolem .grantType. Bere se default  grantType=password a nebo by bylo lepší tam doplnit
krameriusInstance.k7test.grantType=password   ??? 

stavajici konfirurace testovacího K7 autoimportu
krameriusInstance.k7test.title=K7 test
krameriusInstance.k7test.version=7.0
krameriusInstance.k7test.type=test
krameriusInstance.k7test.url=https://kramerius-test.lib.cas.cz
krameriusInstance.k7test.urlLogin=https://kramerius-test-keycloak/realms/kramerius/protocol/openid-connect/token
krameriusInstance.k7test.urlParametrizedImportQuery=/search/api/admin/v7.0/processes
krameriusInstance.k7test.urlStateQuery=/search/api/admin/v7.0/processes/by_process_uuid/
krameriusInstance.k7test.username=proarc_import
krameriusInstance.k7test.passwd=*****
krameriusInstance.k7test.clientId=krameriusClient
krameriusInstance.k7test.clientSecret=*****
krameriusInstance.k7test.exportFolder=/home/proarc-test/kramerius-test.lib.cas.cz-import-auto
krameriusInstance.k7test.deleteAfterImport=true

.properties
krameriusInstance.kramerius7.title=Kramerius 7
krameriusInstance.kramerius7.version=7
krameriusInstance.kramerius7.type=test
krameriusInstance.kramerius7.url=https://k7.inovatika.dev
krameriusInstance.kramerius7.urlLogin=/auth/realms/kramerius/protocol/openid-connect/token
krameriusInstance.kramerius7.urlParametrizedImportQuery=/search/api/admin/v7.0/processes
krameriusInstance.kramerius7.urlStateQuery=/search/api/admin/v7.0/processes/by_process_id/
krameriusInstance.kramerius7.urlDownloadFoxml=/search/api/client/v7.0/items/
krameriusInstance.kramerius7.urlImage=/search/iiif/
krameriusInstance.kramerius7.username=krameriusAdmin
krameriusInstance.kramerius7.passwd=*****
krameriusInstance.kramerius7.clientId=krameriusClient
krameriusInstance.kramerius7.clientSecret=*****
krameriusInstance.kramerius7.grantType=password
krameriusInstance.kramerius7.exportFolder=/temp/proarc/autoImport/kramerius7/
krameriusInstance.kramerius7.krameriusImportFoxmlFolder=/proarc-export/
krameriusInstance.kramerius7.deleteAfterImport=true

**Comment by PetrKotynek** [comment]
Další poznatky 
1.Samotný ingest na reálné K5 může trvat nečekaně dlouho.
2. Dosáhli jsme falešné pozitivní stav, na straně K5 to doběhne PA hlásí chybu.

3.
conn.setConnectTimeout(5000);  ----> conn.setConnectTimeout(10000);

if (state.equals(KRAMERIUS_PROCESS_PLANNED) || state.equals(KRAMERIUS_PROCESS_RUNNING)) {
                TimeUnit.SECONDS.sleep(20);
            }
na 
if (state.equals(KRAMERIUS_PROCESS_PLANNED) || state.equals(KRAMERIUS_PROCESS_RUNNING)) {
                TimeUnit.SECONDS.sleep(60);
            }

Nepomohlo. 

4. HTTP 403 se prostě děje. PK

No ano, ProArc by mel cekat na komplet dokonce, ne jen import - ono to ma dve faze/dav procesy.

1) import,

2) indexace do solru

teprve az tyto dva procesy skonci, je to komplet.

Proto jsem psal nekde nize, ze by nam to Inovatika mela plne objasnit jak to vlastne napsali...

MD

a9d37f5b-1e7e-4c79-a020-2fdb17b0b123 -  je ok; ve chvíli pozitivní zpětné vazby v PA se v UI K5 ještě vůbec nedal zobrazit, indexace běžela. To jen potvrzení k naší konverzaci. 

ZS

**Comment by PetrKotynek** [comment]
![kramerius-07_false](https://github.com/proarc/proarc/assets/37083676/28b8f7de-7c3e-4827-ba39-7a391b753b1a)
![kramerius-00_ingest](https://github.com/proarc/proarc/assets/37083676/89fa8ffc-e4c2-4e1e-b33c-a6b80cf47509)

**Comment by SykoraLukas** [comment]
Je to napsané podle toho, jak to Gabča připravila. 

Po zavolání importu Krameria se dostane zpět uuid procesu, na kterém se kontroluje stav. Ano, jde jen o uuid importu, nikoli o uuid obou dvou procesu (import a indexace). Zkusím se domluvit s @pavel-stastny a @vlahoda jak kontrolovat oba dva procesy. Rovněž jak řešit agregovanou indexaci. Ale to by asi mělo vyřešit jen čekání na doběhnutí indexace. Pokud se nepletu, tak sice probíhá agregovaná indexace, ale poté skončí všechny indexace najednou, nebo se pletu, Petře (@PetrKotynek)?

**Comment by pavel-stastny** [comment]
@SykoraLukas Ono by melo stacit kontrolovat u toho hlavniho procesu jeste davkovy stav (**BATCH_STARTED**, **BATCH_FINISHED** nebo **BATCH_FAILED**)

**Comment by PetrKotynek** [comment]
ale poté skončí všechny indexace najednou Tak to nevím, to je moc Kramerius.
Spíše bych to  držel na té rovině HTTP 403 a jak z toho vybruslit.  Protože to by dosti zvedlo použitelnost i ve stávající podobě. PK

**Comment by PetrKotynek** [comment]
Dnes jsme testovali s dále upravenou verzí cituji MD abych co nejpřesnější:
V podstate jsem pridal kod, ktery osetri status 403 tak, ze se zacykli na predepsany pocet cyklu a v kazdem z tech cyklu zkontroluje opakovane status - pokud uz nedostane 403, pokracuje dal, jinak ceka.

Pokud po probehlem poctu cyklu presto bude stale status 403, melo by to cele skoncit stejnym zpusobem jako v puvodnim kodu. 

HTTP 403 jsme vyloudili po  silné zatezi.
PK

**Comment by SykoraLukas** [comment]
Změny, které popisujete jsem promítnul do hlavní branche. Kromě toho se nově chytá nejen stav procesu, ale i stav batche importu krameria, takže ukončení exportího procesu v Proarcu je až v závislosti na stavu indexace v Krameriovi.

**Comment by PetrKotynek** [comment]
Už na druhém stroji se mi 4.0.6 nepodařilo naistalovat, shodou okolností akubra, ale 405 tam běží. 
PK

21-Aug-2023 09:27:36.755 INFO [localhost-startStop-2] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/home/tomcat/apache-tomcat-8.5.84/webapps/proarc.war]
jar:file:/home/tomcat/apache-tomcat-8.5.84/webapps/proarc/WEB-INF/lib/proarc-common-4.0.6.jar!/cz/cas/lib/proarc/common/config/proarc.properties
jar:file:/home/tomcat/apache-tomcat-8.5.84/webapps/proarc/WEB-INF/lib/proarc-common-4.0.6.jar!/cz/cas/lib/proarc/common/config/akubra.properties
21-Aug-2023 09:27:43.723 INFO [hz.akubrasync.IO.thread-Acceptor] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.internal.networking.nio.NioChannel]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
        java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [com.hazelcast.internal.networking.nio.NioChannel]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1440)
                at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1428)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1267)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1228)
                at com.hazelcast.internal.networking.nio.NioNetworking.register(NioNetworking.java:220)
                at com.hazelcast.nio.tcp.TcpIpConnectionManager.createChannel(TcpIpConnectionManager.java:364)
                at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptSocket(TcpIpAcceptor.java:249)
                at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.handleSelectionKeys(TcpIpAcceptor.java:220)
                at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.acceptLoop(TcpIpAcceptor.java:172)
                at com.hazelcast.nio.tcp.TcpIpAcceptor$AcceptorIOThread.run(TcpIpAcceptor.java:150)

**Comment by PetrKotynek** [comment]
Fedorová instance také nenaběhla ( jenstejn-test ) .
Připojuji log. PK

[catalina.2023-08-21.log](https://github.com/proarc/proarc/files/12398170/catalina.2023-08-21.log)

**Comment by SykoraLukas** [comment]
Prosím o info, jak vypadá soubor $CATALINA_HOME/conf/context.xml - odpovídá konfiguraci? https://github.com/proarc/proarc/wiki/Instalace#konfigurace-tomcat

**Comment by PetrKotynek** [comment]
Nejde undeploy - deploy, překopírování waru. Naběhne po restartu tomcatu ne vlastně po stopu a startu a nebo deploy do prázného tomcatu.
A i pak se to potácí , první login neprojde pak to běží normálně ( 32G solo mašina ). Zkoušel jsem na 2 Akubrách.
 
[con_xml.txt](https://github.com/proarc/proarc/files/12405265/con_xml.txt)

Petr Kotýnek

**Comment by PetrKotynek** [comment]
K 4.0.6 upraveno
nastavil jsem 405 - 406 war switch a opět nenaběhlo. Stop / start tomcatu OK.
[catalina.zip](https://github.com/proarc/proarc/files/12407165/catalina.zip)

Tak už je to moc velký. To je případně minimální komplikace. PK

**Comment by ZdenkaSera** [comment]
@SykoraLukas Na testu nedokážeme nasimulovat dostatečně dlouhý běh, ale základní test fce je ok, tj. naimportuje do Krameria a status v ProArcu se objeví až po dokončení indexace.. Vadu na kráse to ale má - i když proces v Krameriovi je ok, dostaneme chybu, protože asi není ošetřeno zacházení s tímhle statusem:

![image](https://github.com/proarc/proarc/assets/79305516/8dae32ef-8db2-4d0f-b8a3-615324ba48e0)

**Comment by SykoraLukas** [comment]
Měl jsem překlep v kodu a chytal špatné slovo u importu do K5.

Opraveno.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Mám k tomu ještě dotaz - jaký bude text chyby, pokud indexace opravdu spadne? Zrovna se mi to nedaří nasimulovat ... Čekala bych, že tam bude BATCH_FAILED nebo něco dalšího? Ať to třeba nevracíme kvůli kosmetice :-)

**Comment by SykoraLukas** [comment]
Napsáno bude: Import do Krameria ({{instanceId}} --> {{url}}) selhal.
a Status: FAILED

**Comment by SykoraLukas** [comment]
Nerozlišuje se, jestli selhal import nebo indexace - ani v jednom případě se do úspěšně nezobrazi v Krameriovi (spadne import nebo indexace).

**Comment by ZdenkaSera** [comment]
Prima, díky, to je za nás ok.

**Comment by PetrKotynek** [comment]
Client
Version:v2.1.3 (23.08.2023)
Core
Version:4.0.7-DEV
Build:20230823132443
Revision:ebf98d35aa7b940b4a5b134bbfb34301bda68f49
RDflow:RDflow_test_2023_05_01 PERO, Desky Limb

PK

**Comment by ZdenkaSera** [comment]
@SykoraLukas @PetrKotynek Díky oběma, už je to ok.
