### ISSUE TITLE
Opravy urn:nbn - přechod na api v4

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1603]
Část společná pro všechna issues "Opravy urn:nbn" je zde https://github.com/proarc/proarc/issues/1465

Kvůli plánovaným změnám je potřeba začít podporovat CZIDLO api V4.
Pro uživatele ani knihovny se nic nemění, jen je potřeba změnit url v konfiguraci.

**Comment by SykoraLukas** [comment]
Nutná [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#urnnbn).

Pro verze do označení 4.0.x je konfigurace:
``` properties
# (2.0-4.0.x) URL kde běží služba resolveru.
urnnbn.resolver.knav.url=https://resolver-test.nkp.cz/api/v3
```

Pro verze od označení 4.1.0 je konfigurace:
``` properties
# (4.1.0) URL kde běží služba resolveru.
urnnbn.resolver.knav.url=https://resolver-test.nkp.cz/api/v4
```

Uváděno pro testovací resolver, ale pro ostrý to samozřejmě platí také.

**Comment by ZdenkaSera** [comment]
Otestováno v KNAV lokálně - je zahrnuto v poslední verzi  - vše ok.
