### ISSUE TITLE
nejde založit periodikum s více vydavateli z RDA záznamu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#1604]
Nejde založit periodikum s více vydavateli z RDA záznamu. Záznam na vyzkoušení z Alephu SVK HK: 000163920. 
Asi k tomu došlo v souvislosti se změnami v https://github.com/proarc/proarc/issues/739?
![vicevydavatelunejdezalozitperjadro](https://github.com/proarc/proarc/assets/6359479/e15a4d63-a37a-42bf-be3a-f35dd5495db2)

![vicevydavatelunejdezalozitper](https://github.com/proarc/proarc/assets/6359479/a38e3a17-5810-4a3d-8332-52c47cb0defa)

**Comment by SykoraLukas** [comment]
@luckajirku tady narážíme na problém, že podle RDA pravidel musí být vyplněno pole dateIssued pokud eventType=publication. Jesliže ale přebírám pole 3 do dateOther, tak mám pole dateIssued prázdné a tím poádem je objekt nevalidní.

**Comment by SykoraLukas** [comment]
Navrhuji teda pole 3 u eventtype=publication prebirat do dateIssued, tim se tento problem vyresi

**Comment by luckajirku** [comment]
ale to jsme se dostali zpátky tam, kde jsme to před pěti lety začali v tom issue 739 řešit. To dateOther byl návrh z NK s tím, že jim to poradili v LoC.

**Comment by SykoraLukas** [comment]
No to je prave problem s Nk, poradili něco ale už to nedoplnili do standardu.

<img width="554" alt="image" src="https://github.com/proarc/proarc/assets/27210823/4fb8bd3f-572c-4895-9bd0-d3202a26df7b">


Z toho je vidět, že pole dateIssued je pořád Mandatory i když tedy je možnost mít data roku v poli dateOther.

Můžeme to tedy doplnit tak, že publication musí mít dateIssued nebo dateOther s type=publication. Bylo by to takto v pořádku? Šablona by v případě pole 264 1 pole 3 to přebrala do <dateOther type="publication">value</dateOther>

**Comment by SykoraLukas** [comment]
Zatím jsem to udělal tak, jak jsem popsal výše. Případně můžeme udělat změny.

**Comment by ZdenkaSera** [comment]
Na schůzce jsem slíbila příklad z KNAV - perosiokum s polem 001 = 001929946 nejde založit. Přetestovala jsem dnes na 4.1.0-VISK23-beta/v2.2.0-VISK23 (12.09.2023).

V katalogu:
![image](https://github.com/proarc/proarc/assets/79305516/1616be21-bef7-450e-9d81-7340b679567d)

v ProArcu:

![image](https://github.com/proarc/proarc/assets/79305516/8fd857bc-adf6-4831-912a-5e33fd102656)

**Comment by SykoraLukas** [comment]
Již funguje.

**Comment by ZdenkaSera** [comment]
Periodikum s kombinacemi údajů výše už jde založit, otázku správného chování šablony máme na seznamu k vyjasnění se standardy.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
