### ISSUE TITLE
Nástroj na mazání "sirotků" z Fedory (Akubry?)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1609]
Zvážit výtvoření administrátorského nástroje, který umožní vyčistit databázi od zbytků po uživatelském mazání objektů
V ProArcu existuje dvojí možnost mazání objektů řízené oprávněním:
- **trvalé mazání** - zřejmě opravdu maže; smí superadmin
- **mazání**, které objekt a všechny jemu podřízené nesmaže, jen rozpojí vazby mezi nimi a nezobrazuje je v uživatelském zobrazení.  
- [ ] takové objekty lze dohledat ve "smazaných" objektech a obnovit, ale bez vazby, takže podřízené objekty lze dohledat buď individuálně podle uuid (pokud je známe) nebo např. nebo podle data smazání - v praxi se neděje a zůstávají nesmazané a bez použití
- [ ] na tento druh mazání mají oprávnění i uživatelé typu user - typicky: smažou skeny a nahradí novými ...

**Domluva na schůzce 7.9.:** pro mazání "smazaných" objektů by měla být postačující uživatelská funkce - najít ve smazaných a trvale smazat; nutno mazat po malých blocích
KNAV otestuje a popíše

**Comment by PetrKotynek** [comment]
Zkoušel jsem porovnat ostry OZC a jeho akuba klon "OZC OLD". Je velmi zvláštní , že akubra neobsahuje smazané, zatímco zdrojové úložiště dosdud poskytuje bohatou nabídku. 
Copa se děje s Fedora "D" záznamy v okamihu konverze.  A není tedy žádoucí vymazat D před případnou konverzí ?
PK

**Comment by PetrKotynek** [comment]
Oprášil jsem dotaz
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"state:\"Deleted\"",
      "indent":"true",
      "q.op":"OR",
      "_":"1706266119699"}},
  "response":{"numFound":1082,"start":0,"numFoundExact":true,"docs":[

a PA zobrazuje

![smazane](https://github.com/proarc/proarc/assets/37083676/74fab06b-331a-484a-8cbb-726dfaffc688)

**Comment by PetrKotynek** [comment]
Tak po smazání "ve smazaných" dočista,  reindexu a zpětném náhledu ve smazaných 0 a v solru 310. PK

{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"state:Deleted",
      "indent":"true",
      "q.op":"OR",
      "_":"1706270290434"}},
  "response":{"numFound":310,"start":0,"numFoundExact":true,"docs":[

**Comment by PetrKotynek** [comment]
Neúspěšné trvalé mazání opakovaně v rozmezi 2 dnů stále stejná odezva. Reindex nepomohl. PK
 
![ke_smazani](https://github.com/proarc/proarc/assets/37083676/fe4b1618-8821-4931-9b58-434a6125229e)
[onomastika_XML_A_SOLR.txt](https://github.com/proarc/proarc/files/14371782/onomastika_XML_A_SOLR.txt)
[222.zip](https://github.com/proarc/proarc/files/14371789/222.zip)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, přece jen sem přidám prio :-) s prosbou: pokud by se Ti to nepodařilo vyřešit do schůzky a pomohlo by podívat se znovu na náš systém, stavil by ses 1.3. po schůzce u @PetrKotynek? Chceme překlopit produktivní OZČ na akubru a tohle bychom napřed chtěli uzavřít. Moc díky.

**Comment by PetrKotynek** [comment]
Smazání dočista na Akubra 4.1.2 proběhlo již bez protestů. Nejprve jsem přeindexoval a poté smazal trvale nejprve dosud chybující objekt Acta onomastica a následně i zbylé objekty ve stavu jiném než Active. Bylo to 12 kousků. Solr pohled se číselně shodoval s interpretací v PA "hledat ve smazaných". Logy přikládám. PK 

cz.cas.lib.proarc.common.process.export.mets.structure.MetsElement.fillChildren Skipping object, because not found in Low-Level storage info:fedora/uuid:51a5157f-311b-4441-81f6-a088ec8ad072

[log.zip](https://github.com/proarc/proarc/files/14430932/log.zip)
[28_test_1609.txt](https://github.com/proarc/proarc/files/14430935/28_test_1609.txt)
[acta.txt](https://github.com/proarc/proarc/files/14430936/acta.txt)

**Comment by PetrKotynek** [comment]
Zkontroloval jsem oproti běžící Fedora verzi záznamy označené jako 
SEVERE: Nepodarilo se zaindexovat:  uuid:1cc11b4d-443c-46f4-b908-8290fd31024b ...
a žádný se nepodařilo najít ani konvenčně ani  pomocí risearch. Jedná se o skutežné "provozní" nekonzistence úložiště. 
Možná minimalizace poslední reindexací prostřeky FC před vlastní "konverzí" na Akubru. PK

**Comment by ZdenkaSera** [comment]
@PetrKotynek Díky moc :-) Můžeme tedy issue zavřít v souladu s diskusí na schůzce?
