### ISSUE TITLE
Převod modelu eČlánek --> NDK ečlánek (a dalších modelů periodik na eperiodika)

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1610]
Návrh na rozvoj: Umožnit převod ečlánku a "běžných" modelů periodik na jejich NDK varianty za účelem jejich archivace v LTP  

Současně bude nutné definovat zda/jak propojit skenovaná periodika s těmi e-, pokud v průběhu vydávání přešel časopis jen na elektronickou formu

**Comment by SykoraLukas** [comment]
Co myslíš tím: "běžné modely periodik"? Myslíš tyto funkce:
- NDK periodikum -> NDK ePeriodikum
- NDK Ročník -> NDK eRočník
- NDK Číslo -> NDK eČíslo
- NDK Příloha periodika -> NDK ePříloha periodika
- NDK Článek -> NDK eČlánek
- eČlánek -> NDK eČlánek

Propojení NDK Periodik a NDK ePeriodik je otázka. Já budeme řešit rozdílnosti v metadatovem popisu dle NDK?

**Comment by SykoraLukas** [comment]
Odsouhlasen návrh výše.

**Comment by SykoraLukas** [comment]
Na propojení NDK Periodika a NDK ePeriodik zakládám samostatné issue, protože to nebude jednoduché. Převody modelů vyřešíme v tomto issue a na klientovi.

**Comment by SykoraLukas** [comment]
Na API vyřešeno, testování a případné problémy budeme řešit v issue na [klientovi ](https://github.com/proarc/proarc-client/issues/563)
