### ISSUE TITLE
WorkFlow -Propojení z WorkFlow do nového klienta

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#1612]
Souvisí se zavřeným issue proarc/proarc-client#95 - nenapadlo mě zkontrolovat to opačně.

Pokud v RDflow ve Správě záměrů chci vytvořit nový Záměr, tak se nepřepnu do nového klienta, ale zůstanu v jádru.

**Comment by SykoraLukas** [comment]
Nutná konfigurace:

```properties
## (4.1.1) Url cesta k novému klientovi
proarc.client.url=https://proarc-master.inovatika.dev/
```

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.

**Comment by SykoraLukas** [comment]
Asi nechápu kde je problém, teď jsem to zkoušel u nás na testovacím serveru a tam mi to funguje bez nutnosti se znovu logovat do klienta. Můžeš prosím vyzkoušet?

**Comment by ZdenkaSera** [comment]
Zkusila jsem místo Aničky neb tady teď není.
- Když se na inovatice přihlásím do api (https://proarc.inovatika.dev/ nebo https://proarc-akubra.inovatika.dev/ - chovají se stejně) a kliknu na tlačítko "Klient", vyskočí mi nevyplněné přihlašovací okno do klienta - to má zřejmě @SmejkalovaAnna na mysli
- pokud ale už počítám s RDF v klientovi, funguje to takto: přihlásím se do klienta, odtud přejdu tlačítkem do záměrů a zpátky do klienta se dostanu přes ikonu domečku "home" - všechno bez dodatečného přihlašování

**Comment by ZdenkaSera** [comment]
@albertoh @SykoraLukas Znovu otevírám toto issue a prosím o radu, proč se propojení jádro-klient chová v KNAV odlišně od Inovatiky, je to pro rutinní provoz zásadní. Děkuji.

- na Inovatice jsem v jádře ((https://proarc.inovatika.dev/) a pracuji se záměry. Kliknu na "klient" a otevře se mi nové okno s klientem (https://proarc-master.inovatika.dev/) - nemusím se znovu přihlašovat. Pokud v jádře znovu kliknu na tlačítko "Klient", skočím do již otevřeného okna klienta, tj. neotevírá se další.
- v KNAV se po každém kliknutí na tlačítko "Klient" v jádře otevírá nové okno klienta a pokaždé vyžaduje přihlášení uživatele

@SmejkalovaAnna pro info

**Comment by albertoh** [comment]
Toto je opravdu divne... Jedine co mi napada, jestli nepracujes v anonymnem rezimu?

**Comment by ZdenkaSera** [comment]
Nene, v obou případech testuji v chromu v běžném režimu.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, aktualizace k přepínání mezi jádrem a klientem:
- z klienta do jádra se pomocí tlačítka přepnu bez nutnosti znovu se přihlašovat - to je ok
- při přechodu z jádra do klienta mi sice vyskočí přihlašovací okno, ale když je nevyplním a kliknu rovnou na některou z funkcí na hlavní liště, zavolám si patřičné okno/dialog a můžu pokračovat v práci - jde tedy jen o potlačení zobrazování přihlašovacího okna
- 
![image](https://github.com/proarc/proarc/assets/79305516/426ba4c2-4c7f-4a41-90a5-3e49884b100b)

**Comment by ZdenkaSera** [comment]
Ješě doplňuji - test lokálně na verzi 4.1.4/2.2.3

**Comment by ZdenkaSera** [comment]
Tohle zavírám - problém s přihlašováním brzy odpadne díky úplnému přechodu do klienta, tak tím neztrácejme čas. @SmejkalovaAnna @nezbedova
