### ISSUE TITLE
PA 3.6.1 - Nevytvoří se nový objekt

### ISSUE THREAD

**Issue by HamacekLukas** [proarc/proarc#1615]
Při zakládání nového objektu se objekt nezaloží - bez chybového hlášení. Konzole hlásí následující chybu.
Záznam jsme prošli a nenašli nic, co by vytvoření objektu bránilo.
Zkusili jsme záznam náš i z NK.
[https://katalog.npmk.cz/records/ffd2d986-42dd-4412-a81c-2ca6f514d9ee](https://katalog.npmk.cz/records/ffd2d986-42dd-4412-a81c-2ca6f514d9ee)
cnb001969879

Řešení ve starších issues jsem prošel bez výsledku.
Díky předem za navedení k výsledku.

![proarc-konzole](https://github.com/proarc/proarc/assets/145666308/a7c0e039-6e5a-42f7-9f69-ff0650b9835f)

**Comment by SykoraLukas** [comment]
Pracujete ve verzi z října roku 2020. Nejprve si upgradujte ProArc na [nejnovější verzi](https://github.com/proarc/proarc/releases/tag/v4.0.6) a zkuste to v ní (nikde nemáme nasazené takto staré verze, takže to nelze ani vyzkoušet a pokusit se o replikaci problému).

**Comment by ZdenkaSera** [comment]
@HamacekLukas Prosím, jak naložíme s tímto issue - není k uzavření? Děkuji.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
