### ISSUE TITLE
PREMIS: eventType `deletion`

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1616]
Prosím v NDK SIP exportu v PREMIS u jednotlivých stran (složka amdsec) doplnit eventType "deletion"

**Comment by SykoraLukas** [comment]
Nutna konfigurace https://github.com/proarc/proarc/wiki/Konfigurace#ndk-export

**Comment by SykoraLukas** [comment]
K testu ve Visk23

**Comment by kerschfilip** [comment]
tohle podle mě fungovalo, ale než jsem to stihl zavřít, tak v návaznosti na #1665 se mi teď v 4.1.3 negeneruje ani eventType deletion, ale ani části amdsec, které tam dřív byly.

v konfiguraci máme `export.ndk.premis.eventType.deletion=true`

**Comment by ZdenkaSera** [comment]
Máme už na produktivní instanci (4.1.5/2.2.4) - všimla jsem si, že míste "deletion" se generuje text "deletetion". 
![image](https://github.com/proarc/proarc/assets/79305516/aa8b91f2-f2f2-4178-86a2-61bf69da9970)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, tohle by mohla být drobnost do příští verze - je tam jen ten překlep :-) Díky.

**Comment by SykoraLukas** [comment]
Bude v příští verzi.

**Comment by kerschfilip** [comment]
@SykoraLukas omluvám se, ještě je tam drobný problém, kterého jsem si předtím nevšiml: Event digitalizace (capture/digitization) a event smazání původních skenů (deletion/PS_deletion) mají stejnou hodnotu premis:eventIdentifierValue:

```xml
<premis:eventIdentifierValue>digitization_001</premis:eventIdentifierValue>
```

Prosím u toho eventu mazání to nějak změnit. Ve vzorových balíčcích NK je to např. postprocessingdata_001

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
