### ISSUE TITLE
Akubra / HTTP Status 500 při hromadném testování 

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1617]
Při malém zátěžovém testu práce v systému s Akubrou se nám povedlo vytvořit přes 40 eČlánků během 30 minut, následně se systém dostal do stavu, kdy při kliknutí na jakýkoliv objekt na obrazovce Hledat vyskočila chyba. Stejně tak se nedalo ani založit nový objekt. Pomohl až restart solru, tomcatu a reindexace objektů. 

Obě chyby přikládám, @PetrKotynek prosím o logy.
[HTTP Status 500 – zalozeni objektu.txt](https://github.com/proarc/proarc/files/12781780/HTTP.Status.500.zalozeni.objektu.txt)
[HTTP Status 500 – kliknutí na objekt v Hledat.txt](https://github.com/proarc/proarc/files/12781781/HTTP.Status.500.kliknuti.na.objekt.v.Hledat.txt)

Díky za pomoc!

**Comment by PetrKotynek** [comment]
logy
[ozc.zip](https://github.com/proarc/proarc/files/12781836/ozc.zip)
PK

**Comment by PetrKotynek** [comment]
Pro ucenenější náhled připojuji solr logy a paměťový kontex

[solr_log.zip](https://github.com/proarc/proarc/files/12802734/solr_log.zip)


/usr/lib/jvm/java-11-openjdk-amd64/bin/java -server -Xms128m -Xmx2g -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+UseLargePages -XX:+UseHugeTLBFS -Xlog:gc*:file=/media/vg1-lv1/index/solr-8-data/logs/solr_gc.log:time,uptime:filecount=9,filesize=20M -Dsolr.jetty.inetaccess.includes= -Dsolr.jetty.inetaccess.excludes= -Dsolr.log.dir=/media/vg1-lv1/index/solr-8-data/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -XX:-OmitStackTraceInFastThrow -XX:OnOutOfMemoryError=/opt/solr-8/bin/oom_solr.sh 8983   -Xss256k



top - 13:15:40 up 36 days, 19:23,  1 user,  load average: 0,06, 0,06, 0,07
Tasks: 223 total,   1 running, 222 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,7 us,  0,3 sy,  0,0 ni, 98,9 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Mem :  15997,0 total,    410,9 free,   8306,4 used,   7279,6 buff/cache
MiB Swap:  16382,0 total,  16381,5 free,      0,5 used.   7352,6 avail Mem

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   1475 proarc-+  20   0 8005712   1,9g  14384 S   0,7  11,9 510:24.42 java
 521973 proarc    20   0 8015112   1,8g  11748 S   1,0  11,4  37:29.76 java
 521253 proarc-+  20   0 7932948   1,5g  16816 S   0,7   9,9  19:50.39 java
 520944 solrtest  20   0   17,0t 440760  61560 S   1,0   2,7  34:17.33 java
 389114 bind      20   0  752508  68996  11100 S   0,0   0,4   1:06.61 named

**Comment by SykoraLukas** [comment]
Přepsáno aby se nepoužíval HazelCast. Snad to pomůže.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky.

**Comment by PetrKotynek** [comment]
Výborně, předpokládám , že počkáme na ten konsolidační release po PA schůzce PK

**Comment by kerschfilip** [comment]
Při dalším testování (v.4.1.1) se problém už neprojevil. Díky!
