### ISSUE TITLE
Update záznamu ve zdrojovem katalogu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1619]
Národní muzeum si objednalo rozšíření o novou funkci. Update záznamu v katalogu - poslání odkazu o zdigitalizovém objektu přímo do záznamu ve Verbisu + zapsání uuid tohoto objektu.

**Comment by SykoraLukas** [comment]
Nutná konfigurace: https://github.com/proarc/proarc/wiki/Konfigurace#oai

**Comment by SykoraLukas** [comment]
Předpokladem fungování je katalog Verbis s aktivanou editací přes API. Nutnost nového uživatel se speiciálním oprávněním.
Pokud uživatel tyto pole  z konfigurace vyplněné nemá nebude mu funkce fungovat.

V klientovi to bude omezené jen pokud to bude mít uživatel zapnuto v konfiguraci a zároveň pokud se jedná o model číslo periodika, svazek monografie, zvukový dokument, fonografický váleček, grafika, mapa nebo hudebnina.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, tohle je hotové a otestované? Z NM sem nikdo moc nechodí, tak se o tohle issue asi nemá kdo postarat. Děkuji.

**Comment by SykoraLukas** [comment]
Funkci, muzeme zavrit.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
