### ISSUE TITLE
STT strany

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1620]
Umožnit STT stranám stejná pole jako u NDK strany.

Vychází z issue na klientovi: https://github.com/proarc/proarc-client/issues/233

**Comment by ZdenkaSera** [comment]
V jádře je k dispozici ve formuláři, ukládá se do metadat. (Export  a import do K7 zatím nevyzkoušen)

**Comment by ZdenkaSera** [comment]
@erikamirova Eriko, dávám tady návrh na uzavření s tím, že v rámci issue https://github.com/proarc/proarc-client/issues/233 se otestuje včetně importu do K7 - ok? Díky.
