### ISSUE TITLE
OriginInfo - rozdělení do 2

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1622]
V záznamu AACR máme jednoznačné údaje o vydavateli (katalog KNAV, sysno=000025951), origininfo se rozdělí; test na inovatika-master
![image](https://github.com/proarc/proarc/assets/79305516/79a9494a-3485-4972-a8b2-4bfb7c2e8200)

![image](https://github.com/proarc/proarc/assets/79305516/6f3819b5-9930-4389-ab5d-1cb7f85d4507)

Nestalo se to v souvislosti s datem vydání v závorkách? Pro tento záznam to funguje správně (KNAV, sysno = 000753767)
![image](https://github.com/proarc/proarc/assets/79305516/5d181bc1-ead1-4b4f-9be8-fec3a8e43b31)

(řešilo se v https://github.com/proarc/proarc/issues/1266 a https://github.com/proarc/proarc/issues/1267)

**Comment by ZdenkaSera** [comment]
Nebude to problém jen data v závorce, v tomto případě (copyright)  se origininfo taky rozpadá (KNAV sysno = 001824180)
![image](https://github.com/proarc/proarc/assets/79305516/5050dc36-321f-46ea-8103-bdea3c0f4d55)

**Comment by SykoraLukas** [comment]
Tady je otázka, jestli se to chová jako chyba nebo ne. 
Protože:
z pole 008 se bere první hodnota a pouze pokud je shodná s hodnotou v poli 260 tak se založí jen jednou. Pokud jsou ale hodnoty rozdílné (v závorce, s prefixem c) tak se založí element 2x. 

Máme tedy dělat kontrolu, že jsou číselně stejné (bez ohledu na závorky a prefix c), v takovém by se založil jen jednou a jen v případě, že je hodnota číselná jiný by se založilo více elementů?

**Comment by SykoraLukas** [comment]
Vyřešeny závorky. Nutné ještě vyřešit pokud datum má jinou než číselnou hodnotu (např. c2014). K tomu ale založím nové issue.

**Comment by SykoraLukas** [comment]
Druhý komentář řešen samostatně zde: https://github.com/proarc/proarc/issues/1648
