### ISSUE TITLE
Opravy urn:nbn - fáze II - Nová registrace uuid

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1626]
Část společná pro všechna issues "Opravy urn:nbn" je zde https://github.com/proarc/proarc/issues/1465

**Nová registrace** - tento typ opravy lze provést manuálně přes uživatelské rozhraní resolveru, proto fáze II
- Zneplatnění přiděleného urn:nbn v metadatech objektu v PA
- Deaktivace téhož urn:nbn a výmaz uuid v CZIDLE
- Standardní přidělení nového urn:nbn tomuto uuid

**Použití**
- Zjištění skutečnosti, že vlastníkem dokumentu je jiná instituce, než kterou reprezentuje daný registrátor.
- Zjištění, že dokument byl registrován pod chybným typem dokumentu.
- Zjištění, že hlavní identifikační údaje jako název a autor byly chybné (nejde o překlepy, ale o záměny jmen – např. místo knihy s názvem Babička se dokument ve skutečnosti jmenuje Honzíkova cesta)

**Comment by ZdenkaSera** [comment]
Ve verzi v4.1.1./2.2.1 na testu KNAV ok, zkontrolováno v resolveru.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
