### ISSUE TITLE
Opravy urn:nbn - fáze II - Deaktivace urn:nbn

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1627]
Část společná pro všechna issues "Opravy urn:nbn" je zde https://github.com/proarc/proarc/issues/1465

**Deaktivace** - tento typ opravy lze provést manuálně přes uživatelské rozhraní resolveru, proto fáze II
- Deaktivace urn:nbn v čidle
- Výmaz uuid z čidla

**Použití**
- Jako samostatná se tato operace používá při trvalé ztrátě digitálního dokumentu, tj. vyžaduje ruční zadání, nepředpokládá se existence dokumentu v ProArcu

**Comment by SykoraLukas** [comment]
Jak má být toto propojeno na ProArc, když se nepředpokládá existence objektu v ProArcu? Spustím Funkci a jako jeden z parametrů zadám URN:NBN, které chci v Czidle zneaktivnit? Na data v ProArcu tedy toto nemá žádný vliv.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Ano, přesně tak. V ProArcu už data nemusíme mít, ale potřebujeme se zbavit záznamu v čidle. Jde to sice udělat ručně, ale člověk musí znát uživatele a heslo do čidla ... tady se o tyhle údaje postará konfigurace ProArcu. Díky.

**Comment by ZdenkaSera** [comment]
Ve verzi v4.1.1./2.2.1 na testu KNAV ok, zkontrolováno v resolveru.

Text "Deactivated" by mohl být v CS, pokud mám CS nebo CS-EN verzi klienta, ale zatím to nerozporuji.

![image](https://github.com/proarc/proarc/assets/79305516/4d49bb46-32ad-4a1a-81de-f7ed0eb95181)

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
