### ISSUE TITLE
Opravy urn:nbn - fáze II - Oprava/doplnění

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1628]
Část společná pro všechna issues "Opravy urn:nbn" je zde https://github.com/proarc/proarc/issues/1465

**Oprava/doplnění** - fáze II
- oprava (příp. výmaz) nebo doplnění např. identifikátorů, tj. bez nutnosti přeregistarce urn:nbn
- funkci bude nejspíše zapotřebí rozdělit podle typu změny
- bude zapotřebí ruční vstup uživatele, o změnu kterých dat se jedná (nejspíše výběrem typu z roletky, hodnota se pak převezme z metadat a odešle)

**Použití**
- Doplnění dosud chybějících údajů (např. identifikátor čČNB)
- Změna v údajích popisujících digitální instanci (včetně změn identifikátorů jako např. uuid)

**Comment by ZdenkaSera** [comment]
Vzhledem k tomu, že do resolveru posíláme pouze povinné údaje, tento nástroj zatím nebudeme využívat, je možno jej použít pouze k modifikaci nepovinných údajů (dáno vlastnostmi api reolveru)

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
