### ISSUE TITLE
Chyba při exportu NDK PSP u zvukových dokumentů

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1641]
Při spuštění NDK PSP exportu zvukového dokumentu (export do FOXML proběhl OK) se zobrazí tato hláška:
![image](https://github.com/proarc/proarc/assets/8912422/2e6df0a8-a11e-4156-a259-8795a2248ce6)

Chybějící URN:NBN je u uuid NDK Skladba  s názvem Allegretto (je vidět na PRT SCN pod hláškou).

Dle DMF není URN:NBN na této úrovní povinné. A tato snaha o export se ani nezobrazí ve správě dávek.

Vyzkoušeno na ostré instalaci, kde si ještě kvůli možným opravám držíme verzi PA tuto: Klient Verze: v2.1.3 (23.08.2023), Jádro Verze: 4.0.6 (Build:20230819102108).
Stejně se chová i na testu, kde máme verzi tuto: Klient Verze:v2.2.0 (06.11.2023), Jádro Verze:4.1.0 (Build:20231031164042).

**Comment by katerinasirova** [comment]
Vyzkoušeno, prošlo to, ale jestli jsou tam všechny soubory, to nezkontroluji u vás na testu. Kdy je v plánu vydání verze? Potřebujeme exportovat NDK PSP balíčky a poslat je do NK ČR z VISKu z loňského roku. Díky za rychlou opravu.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, prosím Tě, je tohle ok v té verzi vydané po Tvém posledním výše zmíněném testu (tj. v 4.1.1./2.2.1)? Lukáš se pustil do oprav chyb, tak kdybyste lokálně ještě našli problém, prosím, napiš. Moc díky.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
