### ISSUE TITLE
Tlačítko "Klient" v jádře je napojené na Inovatiku

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1643]
Tlačítko v jádře sloužící k přepnutí do klienta je napojené na inovatiku-master.  Je jen zapomenutý kousek "hardcodu" a nebude nutné cestu konfigurovat, bude se tvořit z adresy jádra - je to tak? (Prokliknutí z klienta na záměry v jádře funguje správně). Děkuji.

![image](https://github.com/proarc/proarc/assets/79305516/7716c183-d5d9-4896-b260-b1ae93f2d9f3)

**Comment by SykoraLukas** [comment]
Je nutné konfigurovat. Klient může běžet na jiné adrese, takže by nebylo, jak adresu zjistit.

https://github.com/proarc/proarc/wiki/Konfigurace#nov%C3%BD-klient

**Comment by ZdenkaSera** [comment]
Ok, díky, Vycházela jsem ze situace u nás, kdy jsou adresy jádra a klienta vzájemně odvoditelné, ale to asi nemusí platit obecně.

**Comment by ZdenkaSera** [comment]
Po nastavení konfigurace ok, zavírám.
