### ISSUE TITLE
Chybné OCR při načtení archivního balíčku do ProArcu

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1646]
Pokud načtu do ProArcu archivní balíček NDK svazku monografie s NDK přílohou monografie, převezme se k příloze OCR od hlavního díla (berou se txt znovu od začátku). Můžu dodat testovací archivní balíček. Při načtení téhož jako NDK balíčku je to ok. (Testováno v KNAV na v2.2.1 (18.01.2024)/4.1.1-SNAPSHOT (20.2.2024).)

**Comment by ZdenkaSera** [comment]
Jen pro info doplňuji - stejná monografie s několika přílohami načtená jako exportní dávka pro Kramerius (tj. importovaná s profilem NDK Monografie Kramerius) je v pořádku.

Při načítání se ale v klientovi objevila chyba  - https://github.com/proarc/proarc-client/issues/502

**Comment by SykoraLukas** [comment]
Prosím o zaslání testovacího balíčku.

**Comment by ZdenkaSera** [comment]
Odkaz na data mailem.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně na 4.1.2./2.2.1 - OCR u přílohy monografie načtené jako archivní balíček je správně. Díky.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
