### ISSUE TITLE
Mezera za členy v `<nonSort>` pro CEJSH

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1647]
Potřebujeme ošetřit problém vznikající při exportech pro CEJSH. Za členem vyplněným v elementu `<nonSort>` se má ve většině případů psát mezera, existují ale i případy, kdy tam být nemá. U starších dat stejného titulu vytvořených v KNAV ale mezera někdy není i v případech, kdy tam být má. 

Pro možnost exportovat data celého titulu bylo navrženo řešení:
- najde mezera na konci a pokud tam je, tak se odstraní
- všude se potom během exportu mezera nakonec hodnoty v `<nonSort>` doplní - ale s jednou výjimku, kterou je francouzský člen _L'._
  - Ten bude končit apostrofem, ale pravděpodobně to může být zapsané jako [APOSTROPHE ](https://www.fileformat.info/info/unicode/char/0027/index.htm)nebo [ACUTE ACCENT ](https://www.fileformat.info/info/unicode/char/00b4/index.htm).
- Příklad článků, kde mezera za `<nonSort>` být má: https://aleph.lib.cas.cz/F/?func=direct&doc_number=002835362&local_base=AV
- Příklad článků, kde mezera za `<nonSort>` být nemá: https://aleph.lib.cas.cz/F/?func=direct&doc_number=001107013&local_base=AV

Díky!

**Comment by SykoraLukas** [comment]
@kerschfilip asi máme problém. Zrovna to co jsi poslal za ukázku, kde nemá být mezera za nonSort je totiž pravá horní uvozovka, takže tam by podle toho, co jsi napsal závorka být měla. Nebo to mám toto přidat ještě jako další znak, za který nedávat mezeru?

https://www.fileformat.info/info/unicode/char/2019/index.htm

**Comment by kerschfilip** [comment]
@SykoraLukas prosím přidej tu pravou horní uvozovku taky mezi znaky, za kterými nemá být mezera. Děkuju

**Comment by kerschfilip** [comment]
otestováno, funguje, moc děkujeme!
