### ISSUE TITLE
Solr - logovani zmen objektu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1650]
Vytvořit nové jádro Solru, do kterého se budou logovat změny o objektech a z těchto dat se následně bude moci dělat statistika. 

Ukládané informaci: User, datum, pid, stream, provedená operace.

Je potřebná konfigurace v akubra.cfg
```
# Searching core (for Searching index, that replaced Fedora's Resource index)
solrSearchHost=http://localhost:8983/solr/searchCore

# Logging core (for Logging index, that stores logs about objects)
solrLogHost=http://localhost:8983/solr/loggingCore

```
Kromě toho je potřeba přidat nové jádro do Solru a nakopírovat do něj [požadované schéma](https://github.com/proarc/proarc/blob/development/proarc-common/src/main/resources/cz/cas/lib/proarc/common/solr/schema/log_schema_v1.xml).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tímto jsi mi připomněl, že jsem nezaložila issue ke statistikám :-) - tak tady https://github.com/proarc/proarc/issues/1651

**Comment by PetrKotynek** [comment]
Udělal jsem si homebrew Proarc 412dev a zkušebně jsem přidal loggingCore do Solru a vypadá to zatím OK. PK
[vysledek.txt](https://github.com/proarc/proarc/files/14520950/vysledek.txt)

**Comment by PetrKotynek** [comment]
Testovano na 3 instancich. Pozor nestačí vytvořit loggingCore ale je nutno i "otočit" Solr. 2 x neporošlo /restart Solru/ a jednou se chytlo z běhu. PK
Jádro Verze:4.1.3 Build:20240313133102
