### ISSUE TITLE
Správa procesů - zrušit i pozastavit exportní proces

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1658]
API pro https://github.com/proarc/proarc-client/issues/453

Bylo by možné přidat do správy procesů tyto funkce?

pozastavit běžící exportní proces
zrušit běžící exportní proces
zrušit / smazat exportní proces, který je ve frontě

**Comment by SykoraLukas** [comment]
Bohužel po analýze jsem došel k závěru, ze exportní proces pozastavit nelze. Lze ho zastavit a poté spustit od začátku.

Tedy budou 2 nové funkce:
- Zastavit běžící exportní proces
- Zrušit naplánovaný exportní proces

Prosím o vyjádření, kdo má mít oprávnění na tyto funkce.

**Comment by kerschfilip** [comment]
Podle mě by bylo fajn, kdyby mohl běžný uživatel zastavit/zrušit své procesy a admin i procesy ostatních.

**Comment by SykoraLukas** [comment]
Tohle bych jen doplnil: 
- uživatel své procesy
- Admin procesy své organizace
- Superadmin všechny procesy

**Comment by katerinasirova** [comment]
Za nás souhlasím.

**Comment by SykoraLukas** [comment]
Odsouhlaseno, možné vyvíjet.
