### ISSUE TITLE
 Výmaz uživatele z ProArcu

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1659]
API pro https://github.com/proarc/proarc-client/issues/393

Přidat možnost výmazu uživatele z ProArcu

- Nová funkce v administraci
- Definovat, za jakých podmínek lze uživatele smazat
  - Pokud uživatel nemá objekty
  - Pokud uživatel objekty má, je nutné nejprve objekty převést na nového uživatele (#1657)
- Analyzovat dopady na data, kde se uživatl vyskytuje ("živá" v ProArcu, importovaná z Krameria nebo archivu ..)
- Oprávnění na výmaz - superadmin nebo superadmin s dodatečným dedikovaným oprávněním ?

**Comment by SykoraLukas** [comment]
Prosím o vyjádření, k otázkám:
- oprávnění:
má to mít jen superadmin nebo kdokoli (superadmin, admin), který má dodatečné oprávnění?

**Comment by ZdenkaSera** [comment]
V KNAV jsme se shodli, že by toto oprávnění měl mít pouze superadmin. Díky.

**Comment by katerinasirova** [comment]
Za nás také raději jen superadmin.

**Comment by ZdenkaSera** [comment]
Reimportovaná data se budou v ProArcu přiřazovat uživateli, který je importuje.
