### ISSUE TITLE
NDK PSP v info_*.xml atribut "type" element "checksum" hodnota "md5"

### ISSUE THREAD

**Issue by bezverec** [proarc/proarc#1660]
ProArc v NDK PSP generuje v souborech info_.xml, atributu "type", elementu "checksum" hodnotu "MD5" velkými písmeny. Podle xsd šablony pro soubor info_*.xml by se mělo uvádět "md5" malými písmeny. Upozornila nás na to Národní knihovna.

Otestované to mám v ProArcu 4.0.3 a v MZK 4.0.7-DEV, z obou verzí je md5 velkými písmeny.

**Comment by ZdenkaSera** [comment]
Vyzkoušela jsem na monografii ve verzi 4.1.2. - tam je to opravené podle standardu. @SykoraLukas Prosím, můžeš potvrdit tuhle opravu jako kompletně hotovou? Děkuji.
![image](https://github.com/proarc/proarc/assets/79305516/e9ca1728-3acd-484d-a37e-239fdd58917b)

**Comment by hosak** [comment]
Prosím o kontrolu. V Hradci používáme verzi PA 4.1.3 a pořád nám PA exportuje checksum "MD5" místo "md5".

**Comment by bezverec** [comment]
U nás je to teď md5.

Jádro 4.1.3, klient 2.2.2, model NDK Číslo:
![4 1 3](https://github.com/user-attachments/assets/763a1009-3ec0-4b1f-a70a-4433458faa83)

Jádro 4.1.6, klient 2.2.4, model STT monografie:
![4 1 6](https://github.com/user-attachments/assets/0d46f478-1f0c-47d4-87e6-48532e6e9793)

**Comment by hosak** [comment]
Omlouvám se, pochybení je na naší straně. Kontroloval jsem balíček z instance PA, která ještě běžela na starší verzi, než naše aktuální produkční. Ta už produkuje vše, jak má (obrázek dole). Děkuji za reakci a prosím o zavření.
 
![image](https://github.com/user-attachments/assets/7b4dd251-5400-4fe6-ae66-096e17e6ccdd)

**Comment by bezverec** [comment]
V pořádku, zavírám.
