### ISSUE TITLE
Podpora Solr9

### ISSUE THREAD

**Issue by mduda100871** [proarc/proarc#1662]
Zdravím,

na wiki, v sekci instalace Solru, se píše:

https://github.com/proarc/proarc/wiki/Instalace#solr

že vývoj probíhá proti verzi 8.11, což je dnes poměrně zastaralá záležitost.

Jak je to s podporou Solru řady 9? Rád bych při přechodu na Akubru už použil aktuální Solr...

Díky, MD

**Comment by albertoh** [comment]
Melo by to fungovat bez problemu. Nevidim nic v kodu ani v schema.xml, ktere by tomu branilo.
Ted jsem lokalne zkusil instalovat SOLR 9.5 a pouzil jsem existujici core, a muzu hledat bez problemu.
Kazdopadne radsi pockame az se vrati Lukas, a zmenime verzi v kodu pro jistotu

**Comment by SykoraLukas** [comment]
Také si myslím, ze nic nebrání použití Solr 9. V kódu by žádná závislost na určité verzi být neměla. Jakmile se vrátím z dovolené tak otestuji, momentálně však u sebe nemám pc.

**Comment by mduda100871** [comment]
Ještě otázka - co podpora SolrCloudu?

Teď se s tím aktuálně potýkám i v K7, z pohledu robustnosti by to i v ProArcu asi davalo smysl...

MD

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, na schůzce 26.4. jsme se domluvili, že ověříš solrcloud. Pak prosíme o info do tohoto issue. Děkujeme.

**Comment by ZdenkaSera** [comment]
Zavírám po domluvě s @PetrKotynek
