### ISSUE TITLE
amd_mets v NDK SIP neobsahuje OBJ_001

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1665]
V rámci vedlejšího metsu pro každou stranu (amd_mets) negeneruje verze 4.1.3 část pro OBJ_001, přestože v jiných částech PREMIS je na tuto část odkazováno. 

V komplexním validátoru (v.2.4) to způsobuje následující chyby:

```
amd_mets_aba007-00012e_0001.xml: v mets:amdSec nenalezen ani jeden element 'mets:techMD[@ID="OBJ_001"]' v souboru amd_mets_aba007-00012e_0001.xml

amd_mets_aba007-00012e_0001.xml: OBJ_002: /mets:techMD/mets:mdWrap/mets:xmlData/premis:object: nenalezen očekávaný povinný element 'premis:linkingEventIdentifier'

amd_mets_aba007-00012e_0001.xml: Chybí odkaz (relatedObject) z archivní kopie (ID=OBJ_002) na primární sken (ID=OBJ_001)

amd_mets_aba007-00012e_0001.xml: Objekt 'OBJ_002' se odkazuje se na neexistující Objekt identifikátorem typu 'ProArc_URI' a hodnoty 'info:fedora/uuid:3b12e3dd-a64c-4eb5-a67d-70c8ce9b0d80/RAW'
```

**Comment by SykoraLukas** [comment]
Soubor amd_sec poslán @kerschfilip ke kontrole. Pokud bude v pořádku, bude potřeba lokálně otestovat na relevantních datech.

**Comment by kerschfilip** [comment]
Tohle je OK, prochází to i validátorem ve verzi 2.4.2

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
