### ISSUE TITLE
Rozdílné stahování polí 100 a 700 se stejným prvním indikátorem (rozdíl v namePart type)

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1666]
Při zpracování orientálních dokumentů jsme narazili na to, že jednočlenná jména zapsaná do polí 100 a 700 se stahují různě, i když mají stejný první indikátor.

**Mělo by platit:**
První indikátor: indikátor formy jména
0 Jméno se uvádí pod rodným/křestním jménem
1 Jméno se uvádí pod příjmením
3 Jméno se uvádí pod jménem rodiny (rodu)

**Příklad:** uložen pod uuid=55ec2dd8-91a3-4987-b6dd-338331568702 na masteru (katalog NKP(base SKC), vyhledáno podle name = 'Phags ba shes rab kyi pha, nutno změnit siglu v location - ABB030 není povolená)

V katalogu:
- **1000**  |a [Nágárdžuna], \|d činný 2. století \|7 jn20010525103 \|4 aut
- **7000** |a Śākyasena \|4 trl \|4 edt

V metadatech:
![image](https://github.com/proarc/proarc/assets/79305516/55fe8ea8-fcdd-470c-9289-0558b8fa3cb9)
![image](https://github.com/proarc/proarc/assets/79305516/e34a2e68-64fa-4a93-9f97-05149eeed9c9)

**Comment by luckajirku** [comment]
Teď to vezmu úplně z jiného konce, ale kde se vzalo ve standardu to given? Procházela jsem si šablony (namátkově i starší a ještě starší) na webu LOC, a zatím jsem nikde na given nenarazila, všude se ind. 0 i 1 překlápí do personal.

**Comment by ZdenkaSera** [comment]
@luckajirku Personal je nad tím a to je tam vždycky, to je ok (kromě něj pak na stejné úrovni corporate nebo conference). Given resp. Family je o úroveň níž jako bližší určení, jen jsem tady úroveň type personal vynechala jako bez problémů funkční. 
![image](https://github.com/proarc/proarc/assets/79305516/d5a1780e-1845-4609-8f0f-ddb963123375)

![image](https://github.com/proarc/proarc/assets/79305516/2662f752-3595-42dd-ba58-6d0fcd75cf53)

**Comment by ZdenkaSera** [comment]
@luckajirku Ještě dodatek -  asi jsem Tě špatně pochopila, Tys možná neřešila můj zápis, ale opravdu to, kde to upřesňování pomocí namePart vzala NK. V tom případě jen dodám, že v tomhle případě nerozporujeme standardy :-)

**Comment by ZdenkaSera** [comment]
@luckajirku Aha - tak já zkusím vyhledat další příklady; snad najdu něco, kde ta pole budou zpracovaná stejně. Díky.

**Comment by luckajirku** [comment]
Příklad, jak se v 700 chová Toyen (s ind. 0 a vyplněným podpolem d, končícím čárkou):

mods:
 <mods:name type="personal">
        <mods:namePart type="family">Toyen</mods:namePart>
        <mods:namePart type="date">1902-1980</mods:namePart>

<span>

zdrojový marc:
<html>
<body>

700 | 0 |   | \|a Toyen,  \|d 1902-1980  \|7 jk01132839  \|4 edt
-- | -- | -- | --



</body>
</html>

**Comment by ZdenkaSera** [comment]
Ano, já jsem v pátek zkoušela hledat další příklady - roli hraje čárka za jménem v podpoli a. Jen se mi nepodařilo najít záznamy, kde by pole 100 a 700 byla pro srovnání nastavena stejně (a v obou bylo jméno bez čárky, ideálně jednoslovné). Než to zavřu, ještě zkusím něco najít, Díky.

**Comment by luckajirku** [comment]
Tady mi přijde, že to není úplně OK - že se při převodu MARC-MODS sloučí ind. 1 a 0, a pak se to následně rozsekává na jméno/příjmení podle čárky a ProArc už neví, že tam byl původně ind. 0 a podle čárky za jménem z toho udělá příjmení.
Jinak by to s 0 ind. mělo udělat namepart bez type.
Snad během dneška budu mít ještě nějaké příklady.

**Comment by luckajirku** [comment]
pár příkladů:

### **_100 0 v podpoli a s čárkou_**

**a, d**
000020083 1000  L $$aPlatón,$$d427 př. Kr.-347 př. Kr.$$7jn19981001996$$4aut
<mods:name usage="primary" type="personal">
        <mods:namePart type="given">Platón</mods:namePart>
        <mods:namePart type="date">427 př. Kr.-347 př. Kr</mods:namePart>

000059939 1000  L $$aKosmas,$$dasi 1045-1125$$7jk01061961$$4aut

**a, c, d**
000019879 1000  L $$aTomáš Akvinský,$$csvatý,$$d1225-1274$$7jn19981002237$$4aut
<mods:name usage="primary" type="personal">
        <mods:namePart type="given">Tomáš Akvinský</mods:namePart>
        <mods:namePart type="termsOfAddress">svatý</mods:namePart>
        <mods:namePart type="date">1225-1274</mods:namePart>

### **_100 0 v podpoli a bez čárky_**

**a**
000009893 1000  L $$aFaustus$$711564$$4aut
<mods:name usage="primary" type="personal">
        <mods:namePart type="given">Faustus</mods:namePart>
**a**
000048696 1000  L $$aHiroši Akijama$$4aut
<mods:name usage="primary" type="personal">
        <mods:namePart type="given">Hiroši Akijama</mods:namePart>

**a b, c**
000459750 1000  L $$aSalomoun$$bIII.,$$ckrál izraelský$$789792$$4aut
<mods:name nameTitleGroup="1" usage="primary" type="personal">
        <mods:namePart type="given">Salomoun</mods:namePart>
        <mods:namePart type="termsOfAddress">III., král izraelský</mods:namePart>
       
### **_700 0 v podpoli a s čárkou_**

**a, d**
000023094 7000  L $$aHoméros,$$d8. stol. př. Kr.$$tIlias.$$lNěmecky$$7aun2011667703
<mods:name type="personal">
            <mods:namePart>Homéros,</mods:namePart>
            <mods:namePart type="date">8. stol. př. Kr</mods:namePart>
        
**a, c, d**
000024488 7000  L $$aTereza,$$cmatka,$$d1910-1997$$7jn19981001824$$4aut
<mods:name type="personal">
        <mods:namePart type="family">Tereza</mods:namePart>
        <mods:namePart type="termsOfAddress">matka</mods:namePart>
        <mods:namePart type="date">1910-1997</mods:namePart>

### **_700 0 v podpoli a bez čárky_**

**a  b, c, d**
000066579 7000  L $$aBenedikt$$bXVI.,$$cpapež,$$d1927-2022$$7jn20000604572$$4aui

<mods:name type="personal">
        <mods:namePart>Benedikt</mods:namePart>
        <mods:namePart type="termsOfAddress">XVI., papež</mods:namePart>
        <mods:namePart type="date">1927-2022</mods:namePart>
       
**a**
000117037 7000  L $$aNeprakta$$7jo2005274105$$4ill
<mods:name type="personal">
        <mods:namePart>Neprakta</mods:namePart>

**a**
000223492 7000  L $$aNguyen Xuan Thoi$$4aut
<mods:name type="personal">
        <mods:namePart>Nguyen Xuan Thoi</mods:namePart>

**a**
000461685 7000  L $$aVojta z Brodu$$4trl
<mods:name type="personal">
        <mods:namePart>Vojta z Brodu</mods:namePart>

**Comment by SykoraLukas** [comment]
Pochopil jsem tak, že je rozhodující hodnota indikátoru1 +  jestli se vyskytuje čárka už na úrovni transformační šablony.

Uvádím příklady jak si myslím, že by se to mělo chovat (neuvádím převod jiných polí než pole a).

### 100 0 v podpoli a s čárkou
000020083 1000 L $$aPlatón,$$d427 př. Kr.-347 př. Kr.$$7jn19981001996$$4aut
```
<mods:name usage="primary" type="personal">
    <mods:namePart type="family">Platón</mods:namePart>  -- je před čárkou, proto family
</mods:name>
```

000019879 1000 L $$aTomáš Akvinský,$$csvatý,$$d1225-1274$$7jn19981002237$$4aut
```
<mods:name usage="primary" type="personal">
    <mods:namePart type="family">Tomáš Akvinský</mods:namePart> -- je před čárkou, proto family
</mods:name>
```

### 100 0 v podpoli a bez čárky

000009893 1000 L $$aFaustus$$711564$$4aut
```
<mods:name usage="primary" type="personal">
    <mods:namePart>Faustus</mods:namePart> -- neobsahuje čárku, neuvádí se typ
</mods:name>
```

000048696 1000 L $$aHiroši Akijama$$4aut
```
<mods:name usage="primary" type="personal">
    <mods:namePart>Hiroši Akijama</mods:namePart> -- neobsahuje čárku, neuvádí se typ
</mods:name>
```

000459750 1000 L $$aSalomoun$$bIII.,$$ckrál izraelský$$789792$$4aut
```
<mods:name nameTitleGroup="1" usage="primary" type="personal">
    <mods:namePart>Salomoun</mods:namePart> --neobsahuje čárku, neuvádí se typ
</mods:name>
```


### 700 0 v podpoli a s čárkou
000023094 7000 L $$aHoméros,$$d8. stol. př. Kr.$$tIlias.$$lNěmecky$$7aun2011667703
```
<mods:name type="personal">
    <mods:namePart type="family">Homéros</mods:namePart> -- je před čárkou, uvádí se type family
</mods:name>
```

000024488 7000 L $$aTereza,$$cmatka,$$d1910-1997$$7jn19981001824$$4aut
```
<mods:name type="personal">
    <mods:namePart type="family">Tereza</mods:namePart> -- je před čárkou, uvádí se type family
</mods:name>
```

### 700 0 v podpoli a bez čárky
000066579 7000 L $$aBenedikt$$bXVI.,$$cpapež,$$d1927-2022$$7jn20000604572$$4aui
```
<mods:name type="personal">
    <mods:namePartBenedikt</mods:namePart> -- bez čárky, bez uvedení typu
</mods:name>
```

000117037 7000 L $$aNeprakta$$7jo2005274105$$4ill
```
<mods:name type="personal">
    <mods:namePartNeprakta</mods:namePart> -- bez čárky, bez uvedení typu
</mods:name>
```

000223492 7000 L $$aNguyen Xuan Thoi$$4aut
```
<mods:name type="personal">
    <mods:namePartNguyen Xuan Thoi</mods:namePart> -- bez čárky, bez uvedení typu
</mods:name>
```

000461685 7000 L $$aVojta z Brodu$$4trl
```
<mods:name type="personal">
    <mods:namePartVojta z Brodu</mods:namePart> -- bez čárky, bez uvedení typu
</mods:name>
```

Pro pole 100 i 700 s ind1 tedy platí:
pokud ind1 = 0 nebo ind1 = 1 -> `<mods:name type="personal">`
pokud ind1 = 3 -> `<mods:name type="family">`

bez ohledu na indikator se rozlisuje carka v subfield a
pokud subfield a carku neobsahuje -> `<mods:namePart>{{value}}</mods:namePart>`
pokud subfield a carku obsahuje -> `<mods:namePart type="family>{{valuePredCarkou}}"</mods:namePart><mods:namePart type="given">{{valuePoCarce}}</mods:namePart>`

**Comment by SykoraLukas** [comment]
Můžu poprosit @ZdenkaSera  a @luckajirku o vyjádření do další schůzky?

**Comment by ZdenkaSera** [comment]
Děkuji -omlouvám se za pozdní reakci, byly bychom tohle chtěli probrat interně, ale zatím to není uzavřené. Pravidla, jak je Lukáš rozepisuje, mají logiku (i když některé z vybraných příkladů by sváděly k jiné interpretaci :-)). Za KNAV navrhuji vývoj zahrnout do verze podle plánu výše a pokud v praxi narazíme na zřejmý rozpor, issue otevřeme.  

@luckajirku @katerinasirova Nejste proti?

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
