### ISSUE TITLE
Pole 130 se nestahuje do metadat

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1667]
Unifikovaný název u anonymních děl zapsaný v poli 130 se nestahuje (analogické pole 240 u ostatních děl se stahuje bez problémů).

**Příklad**: katalog Knihovna AV ČR monografie, sysno=002304729, na masteru uloženo pod uuid = 74a5a605-a47c-4e5e-a5c6-253c5b214f27

V katalogu:
![image](https://github.com/proarc/proarc/assets/79305516/374682a7-fd35-4bd4-900a-8c838361e413)

V metadatech jen název z pole 245:
![image](https://github.com/proarc/proarc/assets/79305516/0e7784ce-31ea-4052-932a-637b0cee0e08)

**Comment by SykoraLukas** [comment]
Ideálně by to tedy mělo vypadat takto?

`<mods:titleInfo>
        <mods:title>Průvodce architekturou</mods:title>
    </mods:titleInfo>
    <mods:titleInfo type="uniform">
        <mods:title>Grammar of architecture</mods:title>
    </mods:titleInfo>`

**Comment by ZdenkaSera** [comment]
Bráno podle standardu se domnívám, že ano.

Jen pro info a doplnění: Při stahování z pole 240 se ještě přidává nameTitleGroup="1", což standard nezná. Dokud jsi neposlal tenhle příklad, nenapadlo nás to rozporovat. V šabloně jsem souvislost zatím nehledala, ale nikde nám to nevyskočilo jako chyba, tak navrhuji na tu 240 v této souvislosti zatím nesahat a jen přidat 130 podle Tvého vzoru. Děkuji.

![image](https://github.com/proarc/proarc/assets/79305516/65bb6f30-a7f5-4efd-ae76-0747ec73c91d)

**Comment by SykoraLukas** [comment]
Ten atribut je doplněn šablonou (důvod neznám).

Můžeš prosím přidat i ukázku záznamu s unifikovanym názvem z 240? Díky

**Comment by ZdenkaSera** [comment]
Díky za průzkum. Ukázka 240 výše je z monografie z katalogu KNAV, sysno = 002894988.
Ty dva zápisy v polích 130 a 240 se od sebe liší jen v indikátorech, ale standard - pokud to správně chápu - je vůbec nebere v úvahu : 
![image](https://github.com/proarc/proarc/assets/79305516/5172262d-4660-4248-93a8-0288f761aea8)

![image](https://github.com/proarc/proarc/assets/79305516/30cda938-598f-4800-ae6d-2c2e39dfd0ad)

**Comment by ZdenkaSera** [comment]
Nenašli jsme protipříklad, zdá se ok - díky, zavírám.
