### ISSUE TITLE
pojmenování vstupních souborů

### ISSUE THREAD

**Issue by bezverec** [proarc/proarc#1670]
Zpracováváme skeny z více zdrojů, názvová konvence nebývá stejná. Některé názvy se zdají strojově čitelné, ale při ingestu vstupních souborů ProArc načte jen 1. sken. Příkládám ukázku - viz screenshoty níže. Zajímalo by mě, jestli je tohle technicky možné vylepšit, nebo je to prostě pojmenované nečitelně a musím si na to dávat pozor?  

Vstupní soubory (ukázka pojmenování)
![proarc-import-soubory](https://github.com/proarc/proarc/assets/25476976/6e2ca315-c3ad-4170-bc16-5f1931865fdf)
Po importu dávky je v proarc_import jen 1 sken
![proarc-import-ingest](https://github.com/proarc/proarc/assets/25476976/01093bab-bea5-468f-b85c-9866ec620422)
Analogicky se v rozhraní objeví jen
![proarc-import-rozhrani](https://github.com/proarc/proarc/assets/25476976/703fb8b0-575a-49a2-994e-99a1d112e6f6)
Tohle je ProArc 4.1.3, stávalo se to ale i u starších verzí.

**Comment by SykoraLukas** [comment]
Problém je, ze tečkami se oddělují koncovky souboru. Musíte číselnou řadu oddělit jinak než tečkou například - nebo _. Tím, ze už před číselnou řadu dáváte tečky tak se to pro ProArc tváří, ze je jen jeden soubor s hromadou různých koncovek a správně nečte jen jeden soubor.

**Comment by bezverec** [comment]
Rozumím. Zajimálo mě, jestli je možné tu tečku nebo jiné znaky navíc nějakým způsobem ignorovat (třeba nastavením v konfiguráku), protože na ni zapomínám :) Já se domluvím s producentem skenů jestli je možné to změnit. Nebo si to snad už zapamatuji. Díky.
Issue je jinak možné zavřít jako vyřešené.

**Comment by SykoraLukas** [comment]
Chápu co potřebujete, bohužel žádná taková konfigurace zatím není implementovaná. Pokud toto nechcete vznést jako návrh na vývoj pro příští rok, uzavřel bych.

**Comment by bezverec** [comment]
Ok, momentálně na tom netrvám. Zavírám.

**Comment by bezverec** [comment]
# Import: tečka v názvu souboru sloučí stránky do jednoho objektu a zbytek zahodí bez varování

Hodilo by se nám zvážit tohle vyřešit. Znovu proto otevírám issue.

## Popis

Když název skenu obsahuje tečku i jinde než před příponou, ProArc všechny takové
soubory sloučí do **jediného objektu**. Dávka doběhne do stavu `LOADED`, netváří se
nijak chybově a **v logu není žádné varování** — jen se místo N stránek naimportuje
jedna a zbývající soubory zmizí.

Typicky to potká **signatury**, kde je tečka běžná součást zápisu: `57.993-3`,
`60.046-1`. Pro knihovní provoz je to nepříjemné právě proto, že takový název je
přirozený a nikoho nenapadne, že je problematický.

## Reprodukce

Do importní složky dát dva shodné TIFFy, lišící se jen v názvu:

| složka | soubory | ProArc vytvoří |
|---|---|---|
| A | `57.993-3_0001.tif`, `57.993-3_0002.tif` | **1 objekt** |
| B | `57-993-3_0001.tif`, `57-993-3_0002.tif` | 2 objekty |

Jediný rozdíl je tečka vs. pomlčka. Ve variantě A obsahuje dávka jednu položku
(`57.993-3_0001.tif`), druhý soubor v ní není vůbec — ani jako chyba, ani jako
nezpracovaný soubor.

Ověřeno přes `POST /rest/v2/import/batch` (pole `estimateItemNumber`) i následným
výpisem položek dávky `GET /rest/v2/import/batch/item?batchId=…`.

**Názvů složek se to netýká** — složka `57.993-3` se soubory `strana_0001.tif`,
`strana_0002.tif` se naimportuje správně jako 2 objekty.

## Příčina

`cz.cas.lib.proarc.common.process.imports.ImportFileScanner.getName(File)` hledá
**první** tečku v názvu, ne poslední:

```java
String name = file.getName();
int i = name.indexOf('.');                      // <- první tečka
return i > 0 ? name.substring(0, i) : name;
```

Z bajtkódu 5.0.7:

```
1: invokevirtual  // Method java/io/File.getName:()Ljava/lang/String;
6: bipush  46                                   // '.'
8: invokevirtual  // Method java/lang/String.indexOf:(I)I
...
19: invokevirtual // Method java/lang/String.substring:(II)Ljava/lang/String;
```

Návratová hodnota slouží jako **klíč pro seskupování souborů** do `FileSet`ů
v `ImportFileScanner.getFileSets(List<File>)`:

```java
String key = repairFilename(getName(file));
FileSet fs = map.get(key);
if (fs == null) { fs = new FileSet(key); map.put(key, fs); }
fs.getFiles().add(new FileEntry(file));
```

Pro `57.993-3_0001.tif` i `57.993-3_0002.tif` tedy vyjde klíč `57`, oba soubory
spadnou do téhož `FileSet`u a vznikne jeden objekt. Jeden soubor se použije jako
předloha, druhý se nikam nezařadí, protože se nehodí na žádný očekávaný datastream.

Volající cesta: `FileSetImport.isImportable` / `estimateItemNumber` / `load`
→ `ImportFileScanner.getFileSets(…)` → `getName(…)`.

## Očekávané chování

Název by se měl odvozovat od **poslední** tečky, tedy skutečné přípony:

```java
int i = name.lastIndexOf('.');
return i > 0 ? name.substring(0, i) : name;
```

Pak `57.993-3_0001.tif` → `57.993-3_0001` a každý sken je vlastní objekt.

Kdyby změna nebyla možná kvůli zpětné kompatibilitě (např. kvůli názvům typu
`sken.ocr.txt`, kde se přípona skládá ze dvou částí), pak by import měl aspoň
**nahlásit**, že do jednoho `FileSet`u spadlo víc souborů, které nelze zařadit —
místo aby je tiše zahodil.

## Dočasné řešení

Přejmenovat soubory tak, aby tečka byla jen před příponou (`57.993-3` → `57-993-3`
nebo `57_993-3`). Konfigurací to obejít nejde — `getName` je statická metoda bez
jakéhokoli konfiguračního vstupu.

## Poznámka k dopadu

Nejde jen o nepohodlí. Protože dávka skončí jako `LOADED` a nic nehlásí, může
projít celým zpracováním a chybějící stránky se odhalí až při kontrole nebo při
NDK exportu — a u dávek s desítkami stránek nemusí být na první pohled poznat,
kolik jich chybí.

**Comment by SykoraLukas** [comment]
Kvůli zpětné kompatibilitě a možnosti, že některé knihovny používají koncovky se 2 tečkami u ocr, alto a zvukových souborů bych byl proti změně chování.

Navrhuji udělat kontrolu po načtení do FileSetu, že kazdý fileset obsahuje maximálně jeden tiff soubor. Nevýhodou však je mírné zpomalení procesu načítání.

**Comment by bezverec** [comment]
To by mohlo být fajn řešení. My máme takto archivovaných spoustu skenů, tak by se nám to hodilo i za cenu zpomalení, pokud nebude drastické.

**Comment by kerschfilip** [comment]
Ze schůzky 30. 7.: Kontrolu po načtení ve FileSetu by měla být konfigurovatelná. Knihovna, která ji nepotřebuje ji může mít vypnutou a tím se vyhnout zpomalení. Defaultně bude vypnutá.

**Comment by bezverec** [comment]
Perfektní. Díky.
