### ISSUE TITLE
Po upgradu na AKUBRU nefungují exporty a přidávání/zobrazení PDF

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1671]
Po upgradu úložiště na Akubru nám ProArc běží normálně, je možné v něm běžně pracovat, ale nefungují exporty. Chybová hláška:

```
org.w3c.dom.DOMException: WRONG_DOCUMENT_ERR: A node is used in a different document than the one that created it.
    at org.apache.xerces.dom.ParentNode.internalInsertBefore(Unknown Source)
    at org.apache.xerces.dom.ParentNode.insertBefore(Unknown Source)
    at org.apache.xerces.dom.CoreDocumentImpl.insertBefore(Unknown Source)
    at org.apache.xerces.dom.NodeImpl.appendChild(Unknown Source)
    at cz.cas.lib.proarc.common.process.export.mets.MetsUtils.xPathEvaluateNode(MetsUtils.java:489)
    at cz.cas.lib.proarc.common.process.export.mets.MetsUtils.getModel(MetsUtils.java:508)
    at cz.cas.lib.proarc.common.process.export.mets.structure.MetsElement.getElement(MetsElement.java:657)
    at cz.cas.lib.proarc.common.process.export.mets.structure.MetsElement.getElement(MetsElement.java:652)
    at cz.cas.lib.proarc.common.process.export.Kramerius4Export.getElement(Kramerius4Export.java:353)
    at cz.cas.lib.proarc.common.process.export.Kramerius4Export.validate(Kramerius4Export.java:667)
    at cz.cas.lib.proarc.common.process.export.Kramerius4Export.exportPid(Kramerius4Export.java:525)
    at cz.cas.lib.proarc.common.process.export.Kramerius4Export.export(Kramerius4Export.java:217)
    at cz.cas.lib.proarc.common.process.export.ExportProcess.krameriusExport(ExportProcess.java:739)
    at cz.cas.lib.proarc.common.process.export.ExportProcess.start(ExportProcess.java:152)
    at cz.cas.lib.proarc.common.process.export.ExportProcess.run(ExportProcess.java:130)
    at cz.cas.lib.proarc.common.process.export.ExportDispatcher$ExceptionHandlingTask.run(ExportDispatcher.java:136)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
```

**Comment by SykoraLukas** [comment]
Pošlete mi prosím FOXML objektů, které nejdou exportovat.

**Comment by PetrKotynek** [comment]
[foxml.txt](https://github.com/proarc/proarc/files/15481121/foxml.txt)

**Comment by PetrKotynek** [comment]
[dissemination.xml.txt](https://github.com/proarc/proarc/files/15481136/dissemination.xml.txt)

**Comment by PetrKotynek** [comment]
29-May-2024 09:02:38.148 INFO [ajp-nio2-127.0.0.1-8009-exec-8] cz.cas.lib.proarc.webapp.server.rest.RestException$DigitalObjectNotFoundExceptionMapper.toResponse null
	cz.cas.lib.proarc.common.storage.DigitalObjectNotFoundException: PID: uuid:5962d183-14cc-4a25-b7dd-213989866d58, dsId: RAW, no content
[err_raw.txt](https://github.com/proarc/proarc/files/15481169/err_raw.txt)

**Comment by kerschfilip** [comment]
Ještě přikládám NDK přílohu s ečlánky, kterou jsme dělali včera dopoledne (ještě před upgradem), byla k ní připojená PDF a z ProArcu jsme ji normálně dostali. Teď udělat export pro Krameria nejde a v klientovi a jádře to vypadá, jakoby k článkům žádná PDF přidána nebyla. Znovu PDF přidat nejdou a to ani k již založeným ečlánkům ani k nově vytvořeným. 
[nkd_priloha_s_eclanky_dd3e0c98-ff5b-43c1-b300-701af1c31269.xml.txt](https://github.com/proarc/proarc/files/15481198/nkd_priloha_s_eclanky_dd3e0c98-ff5b-43c1-b300-701af1c31269.xml.txt)

**Comment by SykoraLukas** [comment]
Takže u žádných článků nejsou vidět PDFka?

**Comment by kerschfilip** [comment]
U žádných. Všude to vypadá takhle:
![image](https://github.com/proarc/proarc/assets/57805328/c409d0d0-1967-4003-9a48-0e7a28679028)

**Comment by PetrKotynek** [comment]
[akubra.cfg.txt](https://github.com/proarc/proarc/files/15481650/akubra.cfg.txt)

PK

**Comment by PetrKotynek** [comment]
[proarc.cfg.txt](https://github.com/proarc/proarc/files/15481699/proarc.cfg.txt)
PK

**Comment by SykoraLukas** [comment]
Ty cesty definovane v akubra.cfg exitují, jsou pod uživatelem, pod kterým běží proarc a proarc na ně má právo?

**Comment by PetrKotynek** [comment]
Jiste owner :
drwxr-xr-x   3 proarc ugrpproarc   18 31. kvě  2017 ..
drwxr-xr-x 258 proarc ugrpproarc 8192 25. úno  2016 datastreamStore
drwxr-xr-x   3 proarc ugrpproarc   33 24. dub  2015 fedora-xacml-policies
drwxr-xr-x 258 proarc ugrpproarc 8192 12. úno  2016 objectStore
drwxr-xr-x   5 proarc ugrpproarc   64  3. led 16.33 resourceIndex


drwxr-xr-x   2 proarc ugrpproarc

drwxr-xr-x   2 proarc ugrpproarc

**Comment by PetrKotynek** [comment]
Pri vcerejsim prvnim indexu OK, dnes pár kusu
SEVERE: Nepodarilo se zaindexovat:
uuid:c7f87a4c-89f4-4a37-8ae9-729bd133107f - /home/proarc/fedora/data/objectStore/2a/info%3Afedora%2Fuuid%3Ac7f87a4c-89f4-4a37-8ae9-729bd133107f
uuid:39e62066-ad38-4485-906d-22be087ec943 - /home/proarc/fedora/data/objectStore/39/info%3Afedora%2Fuuid%3A39e62066-ad38-4485-906d-22be087ec943
uuid:c851679e-dd27-4cf5-8e3d-bf75eccaed75 - /home/proarc/fedora/data/objectStore/2a/info%3Afedora%2Fuuid%3Ac851679e-dd27-4cf5-8e3d-bf75eccaed75
uuid:3bfebc01-75ef-498e-81a8-e93a0fbef984 - /home/proarc/fedora/data/objectStore/39/info%3Afedora%2Fuuid%3A3bfebc01-75ef-498e-81a8-e93a0fbef984
uuid:c8a6cde8-9d66-46f3-a05c-004aec72d720 - /home/proarc/fedora/data/objectStore/2a/info%3Afedora%2Fuuid%3Ac8a6cde8-9d66-46f3-a05c-004aec72d720
uuid:3c591afd-b1e8-4f19-bb1e-2b0c45937da2 - /home/proarc/fedora/data/objectStore/39/info%3Afedora%2Fuuid%3A3c591afd-b1e8-4f19-bb1e-2b0c45937da2

**Comment by PetrKotynek** [comment]
[log4.zip](https://github.com/proarc/proarc/files/15483571/log4.zip)
[lomitko.txt](https://github.com/proarc/proarc/files/15483574/lomitko.txt)
PK

FK:

    exporty, které předtím nefungovaly, teď proběhnou bez problému
    u eMonografií vidím i PDF
    u eČlánků ale PDF nevidím a nemůžu ani nové přidat.

**Comment by PetrKotynek** [comment]
[HTTP Status 500.txt](https://github.com/proarc/proarc/files/15483634/HTTP.Status.500.txt)

**Comment by SykoraLukas** [comment]
jaky je rozdil v konfiguraci proarc.cfg na testu a na produkci?

**Comment by SykoraLukas** [comment]
Jeste poprosim o fomxl eMonografie, kde je vse videt a o foxml eClanku, kde neni videt nic.

**Comment by kerschfilip** [comment]
> Jeste poprosim o fomxl eMonografie, kde je vse videt a o foxml eClanku, kde neni videt nic.

Příklad článku (PDF se ale v klientovi ani jádře neukazuje u žádného, co jsem zkoušel):  
[article_foxml.xml.txt](https://github.com/proarc/proarc/files/15483877/article_foxml.xml.txt)

Příklad eMonografie - naopak jsem zatím nenašel, že by byl někde problém. Funguje to v klientovi i jádře:
[emono_foxml.xml.txt](https://github.com/proarc/proarc/files/15483875/emono_foxml.xml.txt)

**Comment by SykoraLukas** [comment]
Ten article soubor nema zadne info o tom, ze by mel mit nejaky RAW stream. Ma jen MODS, DC a RELSEXT.

**Comment by kerschfilip** [comment]
pardon, moje chyba - to je jeden z těch, ke kterým teď potřebujeme PDF připojit a nejde to.

Tady u toho určitě PDF je, ale neukazuje se: [article_rawstream_foxml.xml.txt](https://github.com/proarc/proarc/files/15483982/article_rawstream_foxml.xml.txt)

**Comment by kerschfilip** [comment]
@SykoraLukas po dalším testování potvrzuju, že problém se týká jen ečlánků. NDK emonografie i NDK eČlánky jsou v pořádku + opravdu nemají na rozdíl od ečlánků datastream ID="PREVIEW"
