### ISSUE TITLE
Propsání issue a matrix number z úrovně Zvukový dokument do nižších úrovní

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1672]
Je možné přidat pole `identifier` s type "issue number" a type "matrix number" mezi ta, která se při generování automatické struktury u zvukových dokumentů propisují do dalších úrovní (Skladba, Část skladby)? Při zpracování gramodesek se tak ušetří mnoho práce.

**Comment by SykoraLukas** [comment]
Ano, není problem.
