### ISSUE TITLE
WorkFlow - napojení objektu podzáměru

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1688]
Automaticky vytvořit propojení mezi objekty založených z WorkFlow. Pokud zakládám objekt z podzáměru, najdu jeho záměr (rodiče) a zkusím najít Digitální objekt k tomuto záměru. Pokud existuje, nově zakládaný objekt z podzáměru se rovnou připojí k objektu záměru.

**Comment by nezbedova** [comment]
Otestováno, funguje. Děkuji.

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
