### ISSUE TITLE
Po přechodu na Akubru se zpomalilo připojování (nahrávání) pdf k objektům

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1694]
Po převodu instance pro zpracování e-modelů na Akubru se výrazně (cca 5x) zpomalilo nahrávání pdf k objektům. Vzniklo podezření, že stav může souviset s generováním datastreamu PREVIEW. Prosím, podívali byste na možnost zlepšení? Děkuji.

**Comment by PetrKotynek** [comment]
Ty stažené logy z 12tého jsem mezitím smazal.
Ale ty stroje jsou srovnatelné, vlatně ten jenstejn-test ( Fedora ) má 16 GB , OZC má 32 GB. 
Prostředí systém, Java, Tomcat shodné.  Disky srovnatelne. PK

http://localhost:9080/fedora/get/icon:application_pdf/PREVIEW

sOfDateTime=2021-11-09T13%3A47%3A22.87Z HTTP/1.1" 200 781
127.0.0.1 - - [11/Jun/2024:17:11:04 +0200] "GET /fedora/get/icon:application_pdf/PREVIEW HTTP/1.1" 200 17244
127.0.0.1 - - [11/Jun/2024:17:11:04 +0200] "GET /fedora/objects/uuid:92c707db-df4a-4422-989b-eee0d86e948d/datastreams/PREVIEW/content


uuid:92c707db-df4a-4422-989b-eee0d86e948d, dsID: RAW, altIDs: , dsLabel: P093Zalewska.pdf.pdf, versionable: false, MIMEType: application/pdf, formatURI: null, dsLocation: uploaded://1049, controlGroup: M, dsState: A, checksumType: null, checksum: null, logMessage: fkdigi)


package cz.cas.lib.proarc.common.storage.akubra; 

             if ("URL".equals(contentLocationType.getTYPE())) { // bdmArticle has URL link to icons in Fedora, in Akubra we have to ignore it - http://local.fedora.server/fedora/get/icon:application_pdf/PREVIEW
                                        this.data = null;
                                        break;
                                    } else {
                                        if (ref != null) {

**Comment by SykoraLukas** [comment]
Zpomalení je kvůli tomu, že se pro modely eNDK nově generuje i náhled z pdf, který se dříve negeneroval. Můžeme ho opět zrušit pokud chcete, ale způsobí to, že objekty s PDF nahranými do Krameria nebudou mít své náhledy.

**Comment by kerschfilip** [comment]
OK, díky za vysvětlení. V tuhle chvíli náhledy likvidovat nechceme. Budeme to chvíli sledovat a kdyby se ukázalo, že přidávání PDF trvá opravdu příliš dlouho a způsobuje problémy při práci, museli bychom se zamyslet nad tím, jak to řešit. Teď issue zavírám.
