### ISSUE TITLE
Návrh: dump konfigurace PA

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1696]
(než bude on-line editor konfigurací)

1. Dump proarc.cfg jako active.cfg, očištěno o komentáře, duplicity. Pevná struktura a pořadí. Lze podhodit jako konfig pro další kolo.    

2. Pro admina+ výpis v UI/PA bez hesel včetně použitých default hodnot. sponzoruje ZS

PK

**Comment by ZdenkaSera** [comment]
Zatím je issue jako otázka, zda a) je realizovatelné, b) má význam(lze řešit z časového pohledu vhledem k https://github.com/proarc/proarc/issues/1656. Děkujeme.

**Comment by SykoraLukas** [comment]
a) realizovatelné to je, ale nejedná se o jeden soubor (proarc.cfg se odkazuje i na jiné soubory)
b) někomu to může pomoci
c) není součástí #1656 ani se s tím nepočítalo.

Dávám návrh na rozšíření na příští rok, ale je potřeba vymyslet, jak to zobrazit uživateli, když se využívá několik souborů (proarc.cfg, proarc.cfg.template, akubra.cfg, profile.xxx.cfg)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Díky reakci, zbytek nechám na @PetrKotynek. O issue https://github.com/proarc/proarc/issues/1656 jsem se zmínila proto, že vývojem tam plánovaným se práce s konfigurací možná zpřehlední, nedomnívala jsem se, že tohle je součástí.

**Comment by SykoraLukas** [comment]
Ještě otázka, tohle issue je myšlené na konfiguraci API nebo klienta? Issue #1656 je vázané na konfiguraci klienta, s konfigurací API se nic neděje.

**Comment by ZdenkaSera** [comment]
To je vlastně pravda, moje chyba, potřebuju dovolenou - já tohle chápu primárně jako problém API.

**Comment by PetrKotynek** [comment]
Ano, to je další věc Api klienta. Takže nejenom to co už uteklo do samostatných .cfg
Díky PK
