### ISSUE TITLE
Chyba při importu metadat při založení nového objektu

### ISSUE THREAD

**Issue by katerinasirova** [proarc/proarc#1698]
Při importu metadat ze Souborného katalogu to hodí chybovou hlášku - viz obrázek:
<img width="689" alt="Snímek obrazovky 2024-07-02 v 11 41 57" src="https://github.com/proarc/proarc/assets/8912422/5f25a8f7-0b61-44e6-b538-78ad3aaf55af">

Importuji záznam ze SKC, pole 001: nkc20233526888. Chybu to hodí na obou instancích PA: test (Klient: verze v2.2.4 (11.06.2024)Jádro: verze 4.1.5 - build 20240611083748) i ostrý (Klient: verze v2.1.3 (23.08.2023)Jádro: verze 4.0.6 - build 20230819102108)
Problém je v tom, že ji nelze překonat, jen zavřít a poté se metadata neimportují a je nutné ruční vyplnění.

**Comment by katerinasirova** [comment]
Dobře, v Souborném katalogu s tím nic neudělám, to jim jen můžu napsat, aby opravili. Přišla jsem na to náhodou, když jsem testovala, jestli nám už funguje stahování ze SKC. Pokud se shodneme, že by hláška neměla být překonatelná a že by se měly stahovat jen validní záznamy, pak můžeme issue rovnou zavřít.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, zajímalo mě to, tak jsem se na to v mezičase koukala - tenhle zápis copyrightu v RDA je podle katalogizátorů jediný správný, ale nepovinný (prý byla povinnost používat pro copyright pole 264_4 národní interpretací zrušena).
Myslím si, že máme tedy na výběr 2 možnosti:

1. pole vůbec nestahovat
2. pokud chceme zachovat věrnost záznamu v katalogu, tak upravit stahování - pak by asi mělo přijít sem - co myslíš?
![image](https://github.com/proarc/proarc/assets/79305516/651fee4a-c9d8-4b92-80df-471de0362677)

**Comment by katerinasirova** [comment]
@ZdenkaSera díky - koukala jsem do DMF, kde tohle jako možnost uvedená je - tak je na nás, jak se k tomu postavit.V principu mi nevadí ani jedna možnost, jde mi o to, že tohle by neměl být problém kvůli kterému nám nepůjde záznam stáhnout. 
Copyright máme zrovna u zvukových dokumentů docela dost a někdy je to jediné datum, které se tam vyskytuje. 
Takže za MKP stáhnout, s možností to kdykoli smazat. 
Jde o vyjádření ostatních, jak se k tomu postavit - @erikamirova, @luckajirku, ostatní z KNAV - co vy na to?

**Comment by luckajirku** [comment]
@katerinasirova já to pořád nějak nechápu. Když je ind. 4, tak by to eventtype vytvořit mělo, s hodnotou "copyright", čili by neměl být null, ne?

**Comment by ZdenkaSera** [comment]
Kontroly vypnuty při stažení z katalogu, pak nutí uživatele doplnit/opravit data  (propojit s issue v klientovi).

**Comment by ZdenkaSera** [comment]
Odebírám štítek k diskuzi, domluva ze schůzky 4.9. viz výše.

**Comment by SykoraLukas** [comment]
Vyřešeno vypnutím validace při stažení z katalogu, ve formuláři poté je nutné opravit validační chyby.

**Comment by ZdenkaSera** [comment]
Díky, zakládací okno lze vytvořit a po úpravě dat objekt uložit (test na Katčině záznamu nkc2023352688). Kontrola ostatních údajů se zdá tímto vypnutím nedotřená 👍, přetestujeme lokálně.

Bude třeba dořešit správný zápis a stahování copyrightu pro RDA i AACR.

**Comment by ZdenkaSera** [comment]
@katerinasirova Katko, tohle navrhuji k zavření s tím, že data jdou do zakládacího okna stáhnout a v něm upravit, aby šel založit objekt. 
Správný zápis copyrightu do metadat se bude řešit https://github.com/proarc/proarc/issues/1648.
Pokud jsem něco přehlédla a nesouhlasíš, prosím, napiš. Díky.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
