### ISSUE TITLE
Akubra / Chybí datastream AUDIT

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1700]
V objektech vytvořených na Akubře chybí ve FOXML datastream AUDIT. Tím se tato složka nedostává ani do archivních balíčků. 

V objektech vytvořených před upgradem na Akubru datastreamy zůstávají a propisují se i do archivních balíčků.

Potřebovali bychom, aby struktura archivních balíčků byla konzistentní:

1.  je možné zajistit, aby se i na Akubře AUDIT do FOXML propisoval?
1. Je možné nějak AUDIT doplnit k již vytvořeným objektům?

Díky!

**Comment by SykoraLukas** [comment]
Datastream Audit byl zrušen při přechodu na Akubru. Sloužil k logovani změn objektu, který se nové zapisuje do solru. Generovala ho Fedora samotná, takže přechodem se Akubru se negeneruje, jen u objektu, co jsou z Fedory je stále k dispozici, ale nijak se už s nim nepracuje.

**Comment by kerschfilip** [comment]
OK, to mi nějak uniklo :/ 

takže stejné informace, které obsahoval AUDIT (kdo s jakým objektem kdy manipuloval), se teď dají dohledat v solru?

**Comment by SykoraLukas** [comment]
Ano přesně tak. ProArc ten audit pokud ho má, tak jen "konzervuje" pro případně použití. Jinak mu k ničemu není. Vyžadovala ho pouze Fedora, proto se generoval.

**Comment by kerschfilip** [comment]
Díky moc za rychlé vysvětlení.

Prosím mrkni teda, až to půjde, na prioritní issue https://github.com/proarc/proarc/issues/1175. Složku AUDIT používá náš interní nástroj pro kontrolu struktury archivního balíčku před zabalením do bagitu. Když tam teď není, moc to nefunguje... K tomu abychom mohli používat bagit export přímo v ProArcu potřebujeme ale dořešit právě tohle issue. Děkuju!
