### ISSUE TITLE
Nelze pracovat s objekty exportovanými jako FOXML z Krameria

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1701]
Chtěli jsme přetestovat opravy a následné procesy s FOXML vyexportovanými z Krameria a naimportovanými do ProArcu na verzi 4.1.6/2.2.4 s Akubrou.
- Test zatím na jednoduchých monografiích - obě byly do Krameria (K5) importovány jako FOXML, jedna se Stranami, druhá s NDK stranami.
- Do PA zpětně importovány bez problémů s profilem "Import NDK monografie"
- Z PA je nelze znovu exportovat, není možné je (na úrovni objektu) smazat

Po domluvě s @SykoraLukas posílám testovací data mimo issue

**Comment by SykoraLukas** [comment]
Co je přesně profil Import NDK monografie? Jakou má kodovou hodnotu dle konfigurace? Není to totiž název podle dodávané konfigurace, takže to jste si museli přejmenovat nějaký jiný profil a nemám tedy tušení, jak to importujete.

**Comment by ZdenkaSera** [comment]
Omlouvám se za vágní formulaci, neopsala jsem název profilu z instance. Zde správný název profilu + konfig:
profile.ndk_monograph_kramerius_import.label=Kramerius NDK Monografie

**Comment by SykoraLukas** [comment]
Opraveno v issue #1330. Nasazeno na inovatiku k testování.

**Comment by ZdenkaSera** [comment]
Díky za opravu i uložení testovacích dat - nahrání, převod stran na NDK strany, export pro Krameria i výmaz na úrovni objektu byly  bez problémů.
Neuvědomila jsem si, že při absenci raw streamu neudělám archiv - to je ok, mám ale dojem, že jsme někde řešili, jak naložit s takovou "neúplností". Až najdu issue, dám sem odkaz. Jinak ok, další testy lokálně.

**Comment by ZdenkaSera** [comment]
Přetestováno lokálně v KNAV na v 4.2.0/2.3.0 - export FOXML z K5; NDK monografie/periodikum, už to funguje, s objekty se dá pracovat. (Jen nám zůstávají v PA ty importované v předchozí verzi, ty uživatelsky nelze vymazat ).

A ještě dotaz: tyhle "poznámky" tam mají zůstat nebo byly Tvoje pracovní a jsou tam zapomenuté? Díky :-)
Na úrovni ročníku nám v modsu přibylo toto (překlep imporován ->> importován)
![image](https://github.com/user-attachments/assets/e62ab5f9-98dd-42e9-a3b2-f97514fcf765)

Na úrovni stránky toto:
![image](https://github.com/user-attachments/assets/deadcde8-e095-410c-b47c-bd471946556e)

**Comment by SykoraLukas** [comment]
Toto byla jen má poznámka. Opraveno a nasazeno.

**Comment by ZdenkaSera** [comment]
Test až lokálně na masteru nejsou data k importu.

**Comment by ZdenkaSera** [comment]
Přetestováno znovu lokálně na verzi 4.2.3-SNAPSHOT/v2.3.2 - importy NDK monografií a periodik fungují, lze přihrát data k existujícímu nadřazenému objektu a přepsat metadata nově nahrávaným souborem (u periodika na úrovni titulu i výtisku). Issue zavírám, díky.

Nově se objevily potíže s validacemi (solrem) objektů, které byly do Krameria importovány se "stranami" - založíme nové issue.
