### ISSUE TITLE
Chybějící UUID STT Stran v NDK PSP

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1702]
V NDK exportu u Starých tisků chybí v hlavním METSu části dmdSec pro jednotlivé STT strany. V důsledku toho se do NDK PSP nedostanou UUID stran, se kterými pracuje ProArc, a při importu do Krameria si Kramerius vytvoří vlastní UUID.

@SykoraLukas je prosím nějaký důvod, proč dmdSec pro strany v hlavním metsu chybí, respektive vadilo by něčemu, kdyby se to tam doplnilo? 

Přijde mi, že současný stav může způsobovat, že v digitální knihovně budou strany pod jiným identifikátorem než v ProArcu/nějakém úložišti, aniž by o tom uživatelé věděli...

**Comment by SykoraLukas** [comment]
Podle kodu se do NSK PSP exportu doplnil jen dmdSec pro NdkPage. Můžeme doplnit i pro STT stranu.

**Comment by kerschfilip** [comment]
Funguje, moc děkuju!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
