### ISSUE TITLE
Přidat mapování `dateOther` do DC

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1705]
Na základě tohoto issue https://github.com/NLCR/Standard_NDK/issues/213 prosím přidat mapování elementu `<mods:dateOther>` do Dublin Core - do `<dc.date>`.

V některých standardech zatím tato informace chybí, ale postupně bude doplněna. 

Podle upřesnění NK je element `<dateIssued>` povinný jen v případě výskytu pole `264_1 $c`, v případě, že se v `264` vyskytuje jiný indikátor, pak `<dateIssued>` povinné není a má se využít `<dateOther>` nebo `<copyrightDate>`.  
Z toho mi vyplývá, že povinnost u `<dateIssued>` by měla být (minimálně pro použití v ProArcu) snížena na MA.

**Comment by kerschfilip** [comment]
funguje, moc díky!!

**Comment by ZdenkaSera** [comment]
Zavírám dle pravidla ze schůzky 30.5.2024 (návrh na zavření + nemá štítek „lokální test“)
