### ISSUE TITLE
Úprava chování exportu při výběru více objektů

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#1709]
Pokud v UI vyberu více objektů a spustím nad nimi export, tak se v současné době do správy procesů založí jen jeden proces a vše probíhá pod ním. Pokud tedy dojde k chybě, smažou se všechny již proběhlé exporty, pod touto dávkou a exporty následujících označených PIDů již neprobíhají.

Nově se bude chovat tak, že pro každý označený objekt se založí vlastní proces a výsledek jednoho označeného objektu nemá žádný vliv na ostatní procesy. Pokud by tedy do chyby spadl jeden, ostatní se budou i dále exportovat. Poté bude stačit opravit jen ten chybný objekt a ten znovu vyexportovat.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Hezké 😊 Zkusím na masteru, tak asi nadělám trochu binec v exportních adresářích ...

**Comment by ZdenkaSera** [comment]
Na masteru vypadá ok, lokálně otestovat s chybnými objekty/dalším druhem exportů

**Comment by ZdenkaSera** [comment]
@SykoraLukas Tady jsem si bohužel nenapsala, na čem jsem to testovala, takže buď jsme udělala chybu nebo se něco změnilo, zjistila jsem problémy při lokálním testu
- [ ] na masteru jsem exportovala vícedílku uuid:02bf5d3d-92b5-43ae-859b-28346e9592a0 - export je ve správě procesů pod uui na úrovni titulu, což by bylo ok, pokud by jedna ze dvou částí nebyla bez skenů
- [ ] pokud pustím na úrovni VD validaci. ve správě procesů jsou dva záznamy - to je ok
![image](https://github.com/user-attachments/assets/3ca21f0c-0916-4066-aa85-1444288c41a7)

**Comment by SykoraLukas** [comment]
Doplněna validace i v případě Kramerius Exportu.

Tím jsou vyřešeny body:
- Zatím se zdá, že při exportu objektu (1 nebo více zároveň) pro Krameria neproběhne kontrola před exportem, pokud objekt nemá skeny.
- na masteru jsem exportovala vícedílku uuid:02bf5d3d-92b5-43ae-859b-28346e9592a0 - export je ve správě procesů pod uui na úrovni titulu, což by bylo ok, pokud by jedna ze dvou částí nebyla bez skenů
- 1. test: v horním okně jsem vybrala 2 monografie a pustila export pro Krameria - správně se ve správě procesů ukázaly 2 řádky, ale neproběhla validace - ani jeden z objektů neměl skeny (pokud spustím jednotlivě validaci mimo export, ukáže to). Export zde ale proběhne i při samostatném spuštění, takže asi jde spíš jen o chybu validace, ne hromadného spouštění

**Comment by ZdenkaSera** [comment]
Test na masteru vypadá dobře, díky. Budeme sledovat za běžného provozu.

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
