### ISSUE TITLE
Ve verzi 2.3.1/4.2.1 nelze exportovat archivní/NDK PSP balíčky strukturovaných objektů

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1717]
Lokálně v KNAV končí exporty periodik, vícedílných monografií a objektů s přílohou chybou, která se objevila původně na masteru při exportu více objektů - PA nerozliší začátek nového objektu a očekává pokračování indexu

![image](https://github.com/user-attachments/assets/d911682a-d563-4214-a8e7-775b25c163ae)

Na masteru jsem teď otestovala na vícedílné monogafii  (bf0a2918-77fb-4e54-b91b-391d376db86b) - bez problémů. Přílohu neotestuji kvůli chybě nahlášené zde https://github.com/proarc/proarc/issues/1718, přidělovat jí ručně urn:nbn nechci.

**Comment by SykoraLukas** [comment]
Na masteru je již novější verze, kde je chyba opravena.

**Comment by ZdenkaSera** [comment]
Na masteru přetestováno na VD a na monografii s přílohou - oboje ok, díky. Nutný lokální test.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV, zavírám.
