### ISSUE TITLE
Na masteru nelze exportovat archiv monografie s přílohou - vyžaduje urn:nbn na úrovni přílohy

### ISSUE THREAD

**Issue by ZdenkaSera** [proarc/proarc#1718]
Příklad na masteru: monografie 24bba0e3-e886-4286-a9f1-3c003837b6b9 s přílohu ef8e80cc-1b78-47c5-aef8-5892b58a8fb9
Chyba exportu:

![image](https://github.com/user-attachments/assets/ba60c429-d894-46ce-9de4-831f1ce7a827)

**Comment by SykoraLukas** [comment]
Opraveno, již není vyžadováno. Vzhledem k pravidlům CZIDLA to vyžadování u Přílohy monografie byla chyba.

**Comment by ZdenkaSera** [comment]
Příloha už nevyžaduje urn:nbn ->> lze vytvořit archiv monografie s přílohou. Chyba očekávaného navazujícího indexu v příloze se při exportu neobjevila, takže na masteru ok. Díky.

**Comment by ZdenkaSera** [comment]
Otestováno lokálně v KNAV, zavírám.
