### ISSUE TITLE
K7 autoimport všechny endpointy na jednom URL

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#1730]
Naše hlavní URL z pohledu PA autoimportu:
krameriusInstance.kramerius7.url=https://kramerius-test.lib.cas.cz
A login máme reálně  na jiné adrese: 
https://kramerius-test-login.lib.cas.cz/auth/realms/kramerius/protocol/openid-connect/token

aktuáně se v urlLogin očekává pouze jako doplněk k adrese krameriusInstance. .url
krameriusInstance.kramerius7.urlLogin=/auth/realms/kramerius/protocol/openid-connect/token

Bylo by možno zadat například: 
krameriusInstance.kramerius7.urlLogin=https://kramerius-test-login.lib.cas.cz/auth/realms/kramerius/protocol/openid-connect/token  ?
Nevím, má smysl i u jiných parametrů ? PK

**Comment by SykoraLukas** [comment]
Je možné změnit přímo urlKeycloaku

````properties 
## URL adresa na keycloak, pokud je jiná než na které běží Kramerius API (musí být přístupná ze serveru ProArcu)
krameriusInstance.kramerius7.urlKeycloak=urlAdressKeycloak
````


Ve vašem případě to tedy je

````properties 
krameriusInstance.kramerius7.urlKeycloak=https://kramerius-test-login.lib.cas.cz

**Comment by PetrKotynek** [comment]
Ano doplnil jsem  .urlKeycloack PK

**Comment by PetrKotynek** [comment]
po  změne 
krameriusInstance.kramerius7test.urlLogin=/auth/realms/kramerius/protocol/openid-connect/token
krameriusInstance.kramerius7test.urlLogin=/realms/kramerius/protocol/openid-connect/token

OK
