### ISSUE TITLE
Přílišné vytěžování SOLRu

### ISSUE THREAD

**Issue by kerschfilip** [proarc/proarc#1733]
od posledního releasu ProArcu se v KNAV potýkáme se značným zpomalením a v posledních dvou týdnech, kdy kolegyně zpracovávaly rozsáhlejší tituly, jsme se dostali na hranu použitelnosti ProArcu právě kvůli jeho rychlosti.
 
Velmi dlouho trvá načítání obrazovek v úložišti v klientovi, ukládání změn v editaci a zejména reindexace objektů. Např. indexace monografie o 350 stranách, která nám v srpnu trvala cca 5 minut, nyní zabere hodiny. Tenhle problém se objevuje, ať se indexace spouští z klienta nebo starého rozhraní.

---

Hlavni problem vidime v tom, ze jakmile se spusti reindexacni proces, dostane se Solr pod tezkou palbu dotazu - kazdou vterinu se ten proces pta. Je to videt v logu.

Problem je pravděpodobně v tom, že dotaz obsahuje zastupnou hvezdicku, coz nuti jadro Solru aplikovat regularni vyrazy => vyrazne zpomaleni vyhodnocvani dotazu.

**Comment by SykoraLukas** [comment]
Opraveno.
- Pokud se jedná o reindexaci, zrušeny hiererchická indexace při každé úpravě strany
- Zrušena zástupná hvězdička u pidu/ů.
- Pokud je uveden seznam pidů, na které se dotazuji omezen počet výsledků na počet pidů (dříve maximální hodnota 10 000).

**Comment by SykoraLukas** [comment]
Nasazeno na Inovatiku, panu @PetrKotynek  posílám mailem k lokálnímu testu v KNAV. Vyjde v oficiální verzi příští týden s opravou dalších chyb.

**Comment by PetrKotynek** [comment]
Nasazeno na 5 instancich v KNAV zatim OK. PK

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10.
