### ISSUE TITLE
Rozšířené vyhledávání - hledání názvu podle 100% shody

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#1734]
V pokročilém hledání klient vyhledává **Název** podle částečné shody, což je pro práci mnohdy hodně matoucí a nepříjemné. 

Když např. v Pokročilém hledání zadám dotaz _Reading for Good Health_ a dokonce i specifikuji, že má jít o model eČlánek, PA najde mnoho výsledků, ne však konkrétní eČlánek. První příklad: 
<img width="613" alt="vyhl1" src="https://github.com/user-attachments/assets/7a839fe5-5c89-4a41-8f8c-c4b283181a2b">

Zdá se, že hledá podle částečné shody, ne 100% shody. 

PA hledá všechny objekty, které obsahují alespoň jeden ze zadaných výrazů. I například členy, předložky, spojky. Druhý příklad:
<img width="597" alt="vyhl2" src="https://github.com/user-attachments/assets/86727cf5-d0c7-401d-abf2-245caee1fe30">

Vyhledávání pomocí uvozovek mi nefunguje, proto prosíme o opravu, **aby se v Pokročilém vyhledávání hledalo podle 100% shody** celého řetězce dotazu. 

@albertoh lze u UUID zachovat vyhledávání podle částečné shody (řešili jsme zde: https://github.com/proarc/proarc/issues/1614) a u Názvu podle 100% shody, nebo musíme sjednotit? 

Děkuji

**Comment by SykoraLukas** [comment]
Je potřebná změna konfigurace solru.

Nejjednodušší způsob je postupovat podle návodu https://github.com/proarc/proarc/issues/1734
Pozn: Musí se změnit jak soubor managedSchema tak soubor solrConfig, do kterého se přidala podpora pro správné abecední řazení.

Aktuální schema je object_schema_v5.xml zatím dostupné v development branch, po releasu i v master branch.

**Comment by tumovam** [comment]
Otestováno na masteru. Zdá se v pořádku. Děkujeme, @SykoraLukas

**Comment by SykoraLukas** [comment]
Zavírám na základě label na schůzce 2024.12.10
