### ISSUE TITLE
Kopírování objektu (NDK Číslo Periodika)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#188]
```
Funkce pro zkopírování objektu - jeden(nebo více duplikátů např 12 pro 
měsíčník)
Kopírují se popisná metadata a přiděluje se nové UUID.
```

Original issue reported on code.google.com by `pavel.ko...@incad.cz` on 20 Jun 2014 at 10:53

**Comment by SykoraLukas** [comment]
Zkopírují se metadata objektu (bez identifikátorů `UUID` a `URN:NBN` a bez elementu `PartNumber`) a objekt se napojí na rodiče původního objektu. Label zkopírovaného objektu bude ve tvaru `?,rok`

**Comment by krizovj** [comment]
Funguje to!

Ale vždycky když to číslo zkopíruju, tak mě to vyhodí z toho časopisu a označí mi to první časopis v úložišti.

Takže takhle. Jsem v Živě a vyberu číslo, pak kliknu na Zkopírovat objekt.
![kopirovani](https://user-images.githubusercontent.com/21309201/67262893-a6b2e080-f4a6-11e9-93a4-2036fb178280.jpg)

No a pak to chvíli něco dělá a najednou řekne, že vytvořil objekt a vykopne mě z toho časopisu ven. Což je trochu otravné:
![kopirovani2](https://user-images.githubusercontent.com/21309201/67262915-b4686600-f4a6-11e9-8834-d9590911bac8.jpg)
