### ISSUE TITLE
Změna jazyka u typu stran v Editoru připojených objektů po přesunu stránky

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#223]
```
Když v Editoru připojených objektů změním přesunem pořadí stránek a 
dám Uložit, zobrazí se typy stran v levém okně pod Popis v AJ, po Obnovit 
pak už jsou zase česky. Ničemu to nevadí, jen pro info:-).

```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 7 Sep 2014 at 11:11

**Comment by SykoraLukas** [comment]
Prosím @luckajirku mohla bys zkontrolovat zda se to ještě děje? Děkuji

**Comment by luckajirku** [comment]
Teď to funguje trochu jinak:-). Primárně se tam zobrazují ty typy v AJ. A pokud změním typ strany v Editoru připojených objektů, v tom levém sloupci se změní na tu volbu z rolátka. Např. mám tam typ strany "blank", vpravo v metadatech to přeuložím na Prázdná strana (blank) - čili ten český popis - a to mi tam zůstane.

**Comment by luckajirku** [comment]
Ono mezitím došlo v popisu typů stran ke změně viz dole v #309

**Comment by luckajirku** [comment]
To nebyl problém, to bylo jen pro info. Zda stále trvá, nevím, nemáme kde testovat.

**Comment by nezbedova** [comment]
Názvy stran zůstávají stejné tj. v češtině a v závorce je angličtina.
