### ISSUE TITLE
Rozbalování čísel ve Správě digitálních objektů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#229]
```
Ve Správě digitálních objektů by se hodilo mít i možnost ve stromu 
rozbalit čísla v jednom ročníku až na úroveň stran najednou (a nemuset 
to rozklikávat číslo po čísle).

```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 14 Sep 2014 at 8:58

**Comment by nezbedova** [comment]
Bude vyřešeno ve verzi 3.4
Je nutné rozbalovat vše na úroveň strany.

**Comment by jkremlacek** [comment]
Přidáno. V popisku funkce uvedeno upozornění o možné zátěži systému touto funkcí.

**Comment by pokorsky** [comment]
@nezbedova: Nutno otestovat na větších datech (proarc-test v KNAV) a zdokumentovat (#561).
@jkremlacek: Díky za příspěvek!

**Comment by pokorsky** [comment]
Má smysl mít akci i v horní tabulce, kde není co rozbalovat? Přijde mi to matoucí a zbytečné. V toolbaru ani v menu bych nepřidával oddělovač. Akce může zůstat ve skupině jako akce Smazat.

**Comment by jkremlacek** [comment]
Akci jsem přidával do prostřední lišty, ale položky jsou mezi nimi sdílené, proto se zobrazila i v horní liště.

Nabízí se možnost definování výčtu pro typ lišty a podle ní poté přidávat položky lišty - viz následující commit do branch-e.
