### ISSUE TITLE
OOM a pád prohlížečů na Windows při procházení skenů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#236]
```
Při intenzivním procházení skenů (stovky až tisíce) v obrazovkách 
Příprava metadat nebo Editor připojených objektů dojde k vyčerpání 
paměti a pádu prohlížeče Firefox i Chrome.

Prohlížeče drží v paměti všechny obrázky, které uživatel prošel.

Reprodukovatelné pouze na platformě Windows. Na Linuxu (Ubuntu) je paměť 
uvolňována správně správcem paměti (garbage collector).

Použití 64-bit Chrome zdá se jen oddálí vyčerpání paměti.

Dočasným řešením je občasné obnovení celé stránky v prohlížeči.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 7 Oct 2014 at 5:45

**Comment by luckajirku** [comment]
Chrome 54, 32-bit. Win 7, 64-bit 
Už se nám nepodařilo prohlížeč shodit, i když velikost při prohlížení obrázků narůstá stále. Př. barevné skeny A4, cca 1800, velikost procesu narůstá z počátečních 150 MB na 720 MB, s každým obr. cca o 200-400KB. Problém asi zůstává, ale těch skenů by bylo třeba proklikat opravdu tisíce, a k tomu v normálním provozu docházet nebude.

**Comment by pokorsky** [comment]
V tom případě issue zavírám. Díky.
