### ISSUE TITLE
Import - načtení: chyba v přepnutí na přípravu metadat

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#260]
```
Po načítání souborů v obrazovce "Import-Výběr adresář ..." někdy 
nedojde k automatickému přepnutí do obrazovky "Import-Příprava metadat pro 
načtení do úložiště". Automaticky se přepne asi třetina z 
importovaných souborů. Dvě třetiny zůstanou ve stejné obrazovce a další 
postup je přes Historii.
```

Original issue reported on code.google.com by `nezbed...@knav.cz` on 14 Nov 2014 at 8:45

**Comment by luckajirku** [comment]
Nevím, jak v Jenštejně, ale u nás se to nepřepíná čím dál častěji. Rozhodně to už není ani ta třetina - téměř vždy zůstáváme po načtení v obrazovce Import - Výběr adresáře...; jen výjimečně se to po načtení přepne samo do Přípravy metadat. 
Jinak popisujeme v Chromu, takže pro nás ani neplatí závěr z issue 331.

**Comment by pokorsky** [comment]
Našel jsem kde je problém. Za určitých okolností sice byly jednotlivé stránky označeny jako načtené, ale celková dávka byla stále ve stavu načítání. Problém se objevoval podle toho, jestli systém stačil označit dávku jako načtenou dostatečně rychle. Opraveno.
