### ISSUE TITLE
Dokumentace navigace v hierarchii titulu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#267]
```
Přidat uživatelskou dokumentaci navigace v hierarchii objektů. Popis změn 
viz. issue 247.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 27 Nov 2014 at 1:00
* Blocked on: #247

**Comment by nezbedova** [comment]
Změna byla zapracována do dokumentace.
https://docs.google.com/document/d/1V0tGe7-lLQDCHVoKaB29qVKx4sFJO7LmCoX_OnGaYYg/edit#
