### ISSUE TITLE
Dokumentace volitelného editoru dig. objektu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#268]
```
Přidat uživatelskou dokumentaci akce Náhled viz. issue 187.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 27 Nov 2014 at 1:07
* Blocked on: #187

**Comment by nezbedova** [comment]
Tuto úpravu lze nalézt na https://docs.google.com/document/d/1V0tGe7-lLQDCHVoKaB29qVKx4sFJO7LmCoX_OnGaYYg/edit#, strana 25.
