### ISSUE TITLE
Dokumentace historie importů

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#273]
```
Přidat popis změn historie importů v uživatelské dokumentaci. Viz. issue 
265, issue 269, issue 270, issue 271, issue 272.
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 4 Dec 2014 at 1:03
* Blocked on: #265, #269, #270, #271, #272

**Comment by nezbedova** [comment]
V dokumentaci lze provedené změny nalézt na straně 6.
https://docs.google.com/document/d/1V0tGe7-lLQDCHVoKaB29qVKx4sFJO7LmCoX_OnGaYYg/edit#
