### ISSUE TITLE
Možnost načíst více dávek naráz

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#279]
```
Možnost načíst více dávek naráz - například označených
```

Original issue reported on code.google.com by `pavel.ko...@incad.cz` on 15 Jan 2015 at 12:50

**Comment by nezbedova** [comment]
Lze obejít. Když se začne dávka načítat, dát pokračovat, zvolit další dávku a takto je postupně poslat do fronty.

**Comment by luckajirku** [comment]
Tam šlo o to, aby se to právě nemuselo klikat po jedné. Issue pochází z doby, kdy se popisovalo velké množství dávek a tohle posílání k načtení po jedné jednak zdržovalo, a druhak to byl trochu opruz:-). Ale nevím, jestli se teď někdo s tímhle potýká, asi spíš ne.

**Comment by pavelkocourek** [comment]
Schuzka 13.5.2019
