### ISSUE TITLE
K4 export kapitol

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#289]
```
Přidat mapování NDK kapitoly na model Krameria. Nyní export končí chybou 
viz. 
https://groups.google.com/d/msgid/proarc-users/521d07ab-f418-4ca4-8927-60a1df752
598%40googlegroups.com?utm_medium=email&utm_source=footer
```

Original issue reported on code.google.com by `pokor...@gmail.com` on 25 Feb 2015 at 3:37

**Comment by pavelkocourek** [comment]
Kubo, v hlasování si tomu dal 10 .. používáte to?

**Comment by jkremlacek** [comment]
Je tu vůle to používat. Nicméně bez podpory K4 exportu by to zbytečně blokovalo zpracované dokumenty v ProArc-u (nebylo by jak dostat do Krameria, vzhledem k tomu, že PSP export použít nejde kvůli absenci OCR), takže zatím se to nepoužívá.

**Comment by indrakm** [comment]
MZK 25.5.2019

**Comment by krizovj** [comment]
Šlo by totéž i s články?

**Comment by SykoraLukas** [comment]
Nejspíš ano, zjistím do příštího týdne jestli to nemá nějaká omezení.

**Comment by krizovj** [comment]
Zkusila jsem vytvořit záznam monografie s dvěma kapitolami (731566e1-660b-4c53-92e9-dfab40e122bf) a číslo s články (1a3748e4-4425-4436-a4b0-86907ead9a14). Exporty pro Kramerius u obou dokumentů proběhly, takže zavírám. 

Zkoušela jsem to naimportovat do Krameria a v jádru jsou kapitoly vidět, ale v klientovi ne. Zadám na to issue, čekalo se, jak má přesně vypadat element part u článků a kapitol: https://github.com/proarc/proarc/issues/1098 a https://github.com/NLCR/Standard_NDK/issues/117
