### ISSUE TITLE
Paginace ob stranu

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#294]
```
V obazovce Import - Příprava metadat při popisu více stran umožnit 
aplikaci ob jednu stranu (nebo výběr každé druhé strany).
Použití: Při popisu číslovaných listů, kdy se používá číslování 
1v, 1r, 2v, 2r... nebo levých stran knihy, které nemají číslované pravé 
strany např. jednostranné strojopisy se číslují 1, 1a, 2, 2a... 
```

Original issue reported on code.google.com by `nezbed...@knav.cz` on 26 Apr 2015 at 6:10
* Blocking: #322

**Comment by pokorsky** [comment]
Přesunuté komentáře z issue #322 

od @nezbedova 
Myslím si, že u popisu stran je pojem "Aplikovat včetně první sterany" zavádějící. Dávám k posouzení, zda to nenahradit výrazem "Aplikovat od první strany" a do nápovědy "Aplikovat od první označené strany na každou další podle Aplikovat na" 
Osobně bych si to nechala trvale zaškrtnuté (s možností odškrtnutí), protože mi přijde logičtější paginovat od označené (tedy od první) strany. Jak to vidí ostatní?

od @luckajirku 
Mně spíš přijde zavádějící "Aplikovat od první strany":-), to "včetně" je na místě. Ale asi bych tam rovnou přidala to "označené", ne až do nápovědy. (Akorát - ale tohle bude asi čistě jen můj problém:-) - s tím včetně je to trochu kostrbaté, jakože aplikujeme strany, ne čísla... Hm, vyhodila bych to Aplikovat (stejně to je nad tím - Aplikovat na:) a nechala tam jen "včetně první označené strany".)

Automaticky zaškrtnuté bych to nenechala, to mi zas přijde logičtější, když si označím deset stran a chci to použít na každou druhou, že mi to tak načísluje strany 2, 4, 6, 8, 10, a ne 1, 3...

od @pokorsky
Mně `Aplikovat včetně první strany` a `Aplikovat od první strany` přijde významem stejné. Jinak tohle si klidně odhlasujte. Možná by pomohlo napsat do nápovědy ty 2 rozdílné řady na ukázku (1, 3, ... / 2, 4, ...).

**Comment by nezbedova** [comment]
To je dobrý nápad dát ukázky do nápovědy. 

Aplikovat včetně první strany a Aplikovat od první strany není to samé. Aplikovat včetně první strany znamená 1, 2, 4, 6. Aplikovat od první strany znamená 1, 3, 5, 7. Těžko se hledá výstižný výraz, navrhuji text: "Od první vybrané strany".

V nápovědě by mohl být text: "Při zaškrtnutí bude paginovat od první vybrané strany, např. 1, 3, 5,...".

Dále souhlasím s: "Automaticky zaškrtnuté bych to nenechala, to mi zas přijde logičtější, když si označím deset stran a chci to použít na každou druhou, že mi to tak načísluje strany 2, 4, 6, 8, 10, a ne 1, 3...".

**Comment by luckajirku** [comment]
V tom prvním příkladu by mělo být 2, 4, 6, ne 1, 2, 4, 6. 
Ale jinak tohle chápu teda přesně obráceně:-). Když zvolím každou 2. stranu "od první strany", očekávám načíslování stran 2, 4, 6; když zvolím "včetně první strany", očekávám 1, 3, 5, 7. 
Těžko říct, jestli to půjde nějak rozumně naformulovat...

**Comment by katerinasirova** [comment]
V MKP to chápeme stejně jako v Hradci: tedy když zvolíme každou druhou stranu (od první strany), tak očekáváme 2, 4, 6. Při označení včetně první strany čekáme číslování 1, 3, 5, 7.

**Comment by luckajirku** [comment]
Tak nenecháme to, jak to je a nedoplníme jen tu nápovědu o oba příklady? 

Aplikovat včetně první strany a na každou další podle "Aplikovat na", např. při označení stran 1 až 6 a volbě "každou 2. stranu" budou hodnoty použity pro strany 1, 3, 5. (Při nezaškrtnuté volbě pak pro strany 2, 4, 6.)

Ještě nápovědu u combo boxu "Aplikovat na" by bylo dobré změnit na: Vyberte, na které strany se aplikují vybrané hodnoty.

Ale jinak nám přijde, že to to zaškrtávátko spíš komplikuje:-), že bez něj by to bylo jasnější a použitelné ve všech případech.

**Comment by nezbedova** [comment]
Když "včetně" znamená výběr jen jedné strany a ne celé řady. Tedy 1, 2, 4, 6... Zkusme ještě hledat lepší popisek. Nemá angličtina nějaký specializovaný výraz? 
Když nebude zaškrtávátko nebude možné začít číslovat od strany 1r.
Pokud má někdo ještě nějaké nápady nebo připomínky, prosím, aby je sem napsal. Myslím si, že během zítřka je třeba toto issues vyřešit.

**Comment by luckajirku** [comment]
Můžete prosím popsat, jak docílíte toho, aby vám to načíslovalo při jedné akci strany 1, 2, 4, 6? Když označím prvních 6 stran a dám číslovat každou druhou, tak při zaškrtnutém mi to načísluje strany 1, 3, 5, při nezaškrtnutém stranu 2, 4, 6. Nějak tomu nerozumím.

**Comment by nezbedova** [comment]
To právě nejde, ale při použití "včetně" bych to očekávala. Asi nic lepšího nenajdeme.

**Comment by luckajirku** [comment]
Aha, tak takhle to nechápeme. 
Jinak ještě k tomu "Když nebude zaškrtávátko nebude možné začít číslovat od strany 1r. " - na to přeci stačí posunout tu označenou oblast o jednu stranu. Nebo vám jde o to, aby nebylo třeba tu stejnou oblast vybrat víckrát, že si vyberete jednou a pak dáte číslovat levé a pak pravé? Tak jako jo, akorát to půjde využít jen ve Vazbách, kde to po akci zůstává označené, ale v Importu se to po aplikaci odznačí, takže stejně musíte označit strany, na které se to má aplikovat, znovu.

**Comment by nezbedova** [comment]
Necháme  "Aplikovat včetně první strany".
Napověda k roletce Aplikovat na: "Vybrat, kterým označeným stranám bude přiděleno číslo/typ."
Nápověda k zaškrtávátku: "Přiřadí číslo/typ první označené straně a na každou další podle "Aplikovat na"
Dále prosím schovat v roletce výběry pod "na každou 8. stranu". To znamená, že vidět bude jen prvních osm řádků, k výběru ostatních se bude používat šoupátko po straně. Netrvám přesně na 8 řádcích, jen to chci kratší.

**Comment by pokorsky** [comment]
Nápověda opravena. Maximální výška menu comboboxu je nastavena stejně pro všechny formuláře (např. typy stran). Jestli se menu správně vykresluje, tak bych to neměnil. Jistě by šlo použít třeba i [počítadlo/spinner](https://en.wikipedia.org/wiki/Spinner_(computing)).

**Comment by luckajirku** [comment]
Prosim oprav jen tu formulaci, at je to cesky: "Přiřadí číslo/typ první
označené straně a každé další podle "Aplikovat na"

**Comment by pokorsky** [comment]
opraveno

**Comment by nezbedova** [comment]
Děkuji za opravu  p. Jirků. Tolikrát jsem to opravoval a četla, že jsem chybu přehlédla. 
Pokud nejde výše nastavit jen pro tuto roletku, tak nic neměnit.
