### ISSUE TITLE
Metadata - editovatelné xml

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#296]
```
V souvislosti s nefunkčním editorem MODS-plný bychom uvítali možnost 
přímé editace xml.


```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 29 Apr 2015 at 7:03

**Comment by pokorsky** [comment]
XML je nyní editovatelné. Editor podporuje historii změn undo (ctrl+z) a redo (ctrl+y), automaticky ukončuje XML elementy (po napsání `<mods:part>` se automaticky doplní `</mods:part>`).

Při ukládání proběhne validace podle MODS schema. Pokud je UUID odstraněno uživatelem, tak jej systém doplní, tak jako některé další povinné elementy podle NDK a typu objektu. Výsledné XML je vygenerováno systémem, takže výsledek vždy používá prefix `mods:` pro všechny elementy. XML komentáře jsou při uložení odstraněny.

Pokud je MODS vložen jako `<modsCollection>`, tak se uloží jen první element `<mods>`.

Editor rozpozná chybně uzavřené elementy a označí je červeně.
