### ISSUE TITLE
Nová katalogizační pravidla RDA

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#298]
```
Je potřeba zohlednit nová katalogizační pravidla RDA, která se začnou 
používat od 1. 5. 2015. Záznam vytvořený podle RDA se pozná podle toho, 
že má v poli LDR na pozici 18 hodnotu i, zatímco záznam vytvořený podle 
starých pravidel AACR2R má na pozici 18 hodnotu a.
Záznamy vytvořené podle nových pravidel mají jiný obsah některých polí 
a také obsahují některá nová pole, takže při jejich stahování do 
ProArcu bude potřeba použít jinou transformační šablonu.
Pro záznamy vytvořené podle AACR2R je potřeba dále používat původní 
transformační šablonu.
```

Original issue reported on code.google.com by `slapakov...@gmail.com` on 30 Apr 2015 at 1:38

**Comment by pokorsky** [comment]
Díky za odkaz na šablonu. Bude potřeba ji upravit, protože je založena na mnohem starší verzi 1.76. Se šablonou bude nejspíš potřeba upravit i formuláře podle nové verze NDK a export.

Termín zatím nebyl stanoven. Bude lepší se obrátit s dotazem na https://groups.google.com/d/forum/proarc-users, kde komunikaci sleduje i koordinátor projektu Martin Lhoták.

**Comment by SykoraLukas** [comment]
Upravit formulář metadat tak, aby pole mods:descriptionStandard byl combobox s možnými hodnotami "aacr" a "rda". Povinnost u tohoto pole opravit z O na MA. Ve specifikaci aktualizace https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.3dy6vkm

Upravit formulář pro zápis událostí do originInfo:eventType. Možnost vybrat hodnotu z comboboxu. Povinnost pole je M. Ve specifikaci https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.2s8eyo1

Upravit formulář pro zápis autorit do pole physicalDescription:form. Opět možnost řešeno comboxem. Ve specifikaci https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.17dp8vu

Vytvořit kontrolní metody, které budou kontrolovat vypleněná pole originInfo a physicalDescription proti vybraným pravidlům. V případě, uživatel vyplní špatné hodnoty, bude na to při ukládání upozorněn a uložení neproběhne dokud uživatel nevyplní správné hodnoty.

**Comment by pokorsky** [comment]
Přidáno.
