### ISSUE TITLE
MARC: stahování konspektu pole 072

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#303]
```
Ze záznamu v MARCu se nestahuje pole 072 - konspekt.
```

Original issue reported on code.google.com by `slapakov...@gmail.com` on 13 May 2015 at 9:44

**Comment by slapakovai** [comment]
Funguje to správně, promiň. To jenom v tom formuláři se to zobrazuje na různých místech, takže mě to trochu zmátlo. Issue se může uzavřít.
