### ISSUE TITLE
Při změně na English zůstávají typy stran v češtině (ProArc na KDJ)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#309]
```
V ProArcu na KDJ při změně jazyka na English zůstanou jednotlivé typy 
stran v češtině (jak v Import - příprava metadat, tak ve Správě 
digitálních objektů i v Editoru připojených objektů). Vše ostatní se 
přeloží, refresh nepomáhá.
Dělá to jen u nás - ve verzi, co je v Incadu, je to v pořádku.


```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 22 Jun 2015 at 8:51

**Comment by luckajirku** [comment]
Ty anglické výrazy za to jsou dobrý nápad, to by se určitě hodilo, kdyby to bylo u všech typů v závorce uvedeno. Ale zároveň bychom byli rádi, kdyby se v ČJ přejmenovaly ty zmíněné matoucí typy, aby bylo jasné, o co jde. Nemyslím, že se musíme držet NDK pravidel za každou cenu, když tam jsou nelogičnosti, stejně se tohle využívá jen při samotném zpracování. Rádi bychom předělali české popisky:

FrontJacket z Reprezentativní obálka na "Přední strana přebalu" - resp. "Přední strana přebalu (FrontJacket)"
Cover z Obálka na "Desky vcelku" - resp. "Desky vcelku (Cover)"

Prosím o Jenštejn o vyjádření.

**Comment by nezbedova** [comment]
S opravou českých výrazů a s doplněním anglických výrazů dle návrhu souhlasíme.

**Comment by pokorsky** [comment]
Tady je ukázka typů se závorkami. Moc přehledné mi to nepřijde. Nechávám to na zvážení.

![pagettypeswithbrackets](https://cloud.githubusercontent.com/assets/1336737/9545904/3d99dee6-4d8e-11e5-917c-6c60b5c0d6d0.png)

**Comment by nezbedova** [comment]
Je tam toho dost, ale pokud to pomůže s upřesněním popisu, tak s tím 
nemám problém.
MN

Dne 28.8.2015 v 14:23 pokorsky napsal(a):

**Comment by luckajirku** [comment]
Je toho dost, ale za nás ano. V combo boxu je to ok - a v těch tabulkách stran si může uživatel případně zúžit sloupec a vidět jen ten začátek...

**Comment by pokorsky** [comment]
Změněno na verzi se závorkami.
