### ISSUE TITLE
Defaultní nastavení skeneru u nové dávky po přepnutí do jiné obrazovky a zpět zmizí

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#311]
Při spuštění ProArcu je skener nastavený defaultně, pokud je na výběr 
jen jeden (issue #190). Stává se ale, že při přepnutí do jiné obrazovky 
(ať už se po načtení přepne samo do přípravy metadat nebo ručně 
přepneme do Historie nebo Nový objekt a Hledat) je pak při dalším 
přepnutí zpět do Nová dávka už nutno skener vybrat ručně. I když ho 
ale vyberu ručně, tak při dalším přepnutí jinam a zpět zas zmizí a je 
ho třeba nastavit znovu.

Mám pocit, že se to chová různě v závislosti na tom, z jaké první 
obrazovky po přihlášení do Nová dávka jdu:
- pokud se přihlásím do "prázdného" ProArcu, při prvním kliknutí na 
Nová dávka tam skener je, při přepnutí jinam a zpět už je třeba ho 
nastavit. Stejně tak pokud po přihlášení vstupuju přímo do Historie / 
Nový objekt / Hledat, tak pak při prvním kliknutí na Nová dávka tam 
skener je nastavený, při dalším přepnutí jinam a zpět už zmizí. 
Pomáhá refresh přes F5 - a potom už skener drží i při přepínání. 
- ALE když se přihlásím rovnou do Import - Výběr adresáře, tak je 
skener nastavený a drží pořád i při následném přepínání.

To je teda v Chromu, ve FF se to chová ještě hůř (FF nás ale tak 
netrápí):
- přihlášení do Import - Výběr adresáře - skener je, po přepnutí 
jinam a zpět zmizí
- přihlášení do Import - Výběr adresáře - pokud tam ještě kliknu na 
Nová dávka, skener zmizí 
- po refreshi tam sice skener taky nastaví, ale po přepnutí jinam a zpět 
zmizí
- při přihlášení do prázdného ProArcu a kliknutí na Nová dávka skener 
nastavený je, po přepnutí jinam a zpět zmizí

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 2 Jul 2015 at 11:22

**Comment by pokorsky** [comment]
Skener se nastavoval jen při prvním načtení všech skenerů. Totéž se týká importních profilů #323. Opraveno, nastavení zůstane i po přepnutí z jiné obrazovky.
