### ISSUE TITLE
MARC: stahování dat z 260c a 008 do date issued

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#312]
```
Pro upřesnění k diskusi kolem stahování dat z 260c a 008 do date issued. 
Prověřovali jsme to dnes na různých záznamech - a je to tak, že se to 
nestáhne VŽDY dvakrát, ale:

- pokud se údaj v 008 liší od údaje ve 260c (např. v 008 je 1926, ve 260c 
[1926]), tak pak se vytvoří  date issued dvakrát - výskyt z podpole 260c je 
s prázdným encoding 1926 a ten z 008 jako [1926] s encoding MARC.

- pokud jsou údaje ve 260c a v 008 naprosto shodné, pak se opravdu vytvoří 
jen jeden date issued s prázdným enconding, tedy z 260c.



```

Original issue reported on code.google.com by `jirku.lu...@gmail.com` on 10 Jul 2015 at 7:40

**Comment by luckajirku** [comment]
Je toto už dáno k řešení v Krameriovi, jak bylo dohodnuto na schůzce? Asi IŠ? V issues to nikde nevidím, ale nevím, jestli jste to třeba neřešili přímo na schůzce vývoj. týmu Krameria...

**Comment by slapakovai** [comment]
Čekáme na podklady k analýze obsahu pole 008. Má nám je poslat firma, která nám spravuje Clavius.

**Comment by luckajirku** [comment]
Ale ta analýza se má týkat možných chyb ve vašich vstupních datech, ne? Pro úpravu vyhodnocování/zobrazování v K5 je snad směrodatné, jaké hodnoty MAJÍ BÝT v MARC21 v poli 008 na těch pozicích a jak převádějí do mods. A to je dané, nevím, jaký vliv by na to mohly mít výsledky analýzy. Asi úplně nevidím důvod, proč s nadhozením tohoto problému čekat.

**Comment by slapakovai** [comment]
Už na schůzce jsme se dohodli s Pavlem Kocourkem, že se nejdřív udělá analýza.

**Comment by luckajirku** [comment]
Ano, to se dohodlo, ale podle zápisu měl být výpis zajištěn do 31.07.

**Comment by slapakovai** [comment]
Z Alephu ho mám už dávno, ale ten Clavius moc neovlivním. Dala bych jim čas ještě tak týden. Snad to po dovolených bude lepší. A kdyžtak tu analýzu uděláme jenom z Alephu.

**Comment by slapakovai** [comment]
Zatím mám jenom data z Alephu, z Clavia je asi v brzké době nedostanu. V poli 008, pozice 7-10 a 11-14 jsou v našem Alephu číslice, písmeno "u" a znaky "-", "^", "|". Tyto znaky doplňuje Aleph sám jako výplňové, pokud na ty pozice katalogizátor nic nenapíše.

**Comment by luckajirku** [comment]
Dobře, takže už víte, jak vypadají vaše data a kde si co dát před digitalizací v 008 do pořádku. Je tedy možné teď zadat issue do Krameria?

**Comment by slapakovai** [comment]
Založila jsem issue https://github.com/ceskaexpedice/kramerius/issues/302 na Krameriovi.
