### ISSUE TITLE
MARC: stahování údajů z pole 787

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#313]
```
Údaje z pole 787 se nestahují. Podle mapování z marcu do modsu by se měly 
konvertovat do elementu RelatedItem.
Testovací záznam: 
http://aleph.lib.cas.cz/F/?func=direct&doc_number=001888953&local_base=AV
```

Original issue reported on code.google.com by `slapakov...@gmail.com` on 10 Jul 2015 at 2:20

**Comment by pokorsky** [comment]
@slapakovai: Ivano, tohle má přijít jen do nového formuláře, issue #321, nebo i do eČlánku? Jaké mají být popisy polí, nápověda nebo počet opakování?

V relatedItem bude i první strana článku, issue #318.

Kompletní popis titulu už je v MODS nadřazených objektů takového článku. Je opravdu nezbytné tyto údaje opakovat u článku? K4 i CEJSH export se k nadřazenému titulu dostanou.

**Comment by slapakovai** [comment]
Má to přijít do obou formulářů k cejshi.
Popisy polí do zjednodušeného formuláře jsou ve specifikaci, do dlouhého formuláře jsou podle názvů elementů.
Povinnost vyplnění jsem doplnila do specifikace.
Počet opakování jednou ve formuláři s možností opakování.

Nápověda pro elementy:
Title: "Název recenzovaného díla. Odpovídá poli 787$t"
Name: " Autor recenzovaného díla ve tvaru: "Příjmení, Jméno". Odpovídá poli 787$a
Publisher: "Vydavatel recenzovaného díla ve tvaru: "město : nakladatelství, rok vydání". Odpovídá poli 787$d."

Nejedná se o popis titulu, ve kterém je článek. Je to popis titulu, na který je ta recenze (recenzovaného dokumentu).

**Comment by pokorsky** [comment]
relatedItem přidán do obou formulářů upravena nápověda a přípony povinnosti vyplnění.
