### ISSUE TITLE
Interpunkce z pole 245

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#316]
```
Interpunkce z pole 245, podpole $a a $b se v některých případech při 
konverzi zachová, někdy se smaže a vždycky se doplní ":".

Za mě by bylo nejlepší zachovat interpunkci z MARCu a nic automaticky 
nedoplňovat, ale to je jen první návrh. Budu ráda, když se k tomu 
vyjádří paní Jirků nebo kdokoliv další.
```

Original issue reported on code.google.com by `slapakov...@gmail.com` on 14 Jul 2015 at 12:05

**Comment by slapakovai** [comment]
Paní Jirků: takže pro vás by bylo lepší nic neměnit, nebo umazávat i to "="?

**Comment by luckajirku** [comment]
Vzhledem k tomu, že jste issue založila vy, by bylo dobré, kdybyste si přečetla všechny komenty a nejprve sama doplnila informace. Už je to bez vaší reakce dost dlouho. Shrnu to, pokud je to potřeba. 

1. Píšete "Interpunkce z pole 245, podpole $a a $b se v některých případech při 
konverzi zachová, někdy se smaže a vždycky se doplní ":"." V jakých případech toto nastává? A nastává to vůbec, nemyslíte tím jen to zobrazení v ProArcu ve Správě digitálních objektů nebo pak v K5? 

2. "Chybí odkaz na Aleph data". Můžete dát alespoň jeden konkrétní příklad, kdy se interpunkce zachová a jeden, kdy se smaže? 

3. Píšete "Za mě by bylo nejlepší zachovat interpunkci z MARCu a nic automaticky 
nedoplňovat" - z jakého důvodu by pro vás bylo nejlepší zachovat interpunkci?

**Comment by slapakovai** [comment]
Jenom jsem se ptala na to, co přesně požadujete. Protože jsme to probíraly i jinde než v tomhle issue a já přesně nevím, jestli jsme se na něčem dohodly. Jestli si to dobře pamatuji, tak jste také chtěla nějakou změnu.

Ad 1. ano, doplňování ":" dělá jenom ProArc a to nás při zpracování mátlo, protože jsme ho používali poprvé. Takže tuhle část není potřeba řešit.

Ad 3. protože když se celý obsah podpole b konvertuje do elementu subTitle (i přes to, že to subtitle není), tak s interpunkcí je aspoň knihovníkům jasné, co v tom elementu je. A kdyby se data posílala někam dál, tak by případně podle interpunkce bylo možné rozpoznat, co v tom elementu je.

**Comment by luckajirku** [comment]
Už jsem k tomu všechno napsala výš - nic nepožaduji, jen bych byla pro zvážit i automatické odmazávání rovnítka, ale sama si nejsem jistá, počítám, že to tak LoC nemá v šabloně bezdůvodně. Nevím, co si o tom myslí ostatní "proarcové" knihovny... 
Co jsem se ptala v knihovnách, které zpracovávají v jiných systémech, tak většinou v tomhle používají LoC šablonu tak, jak je (tedy maže se automaticky: .:,;/][, zůstává "="), tři knihovny odmazávají vše včetně rovnítka. 

No, knihovníkům (resp. části knihovníků) to z interpunkce jasné bude, o co jde. Ale netvoříme to jen pro knihovníky, ale taky (hlavně?) pro normální uživatele. Jinak když tam necháme interpunkci, tak 1. budete mít ten samý problém, co jste teď měla v ProArcu - budete se v některých místech v Krameriovi divit, že máte interpunkci zdvojenou (protože se vám v K4/5 přidá ve zobrazení automaticky). 2. Nebude si uživatel myslet, že je interpunkce součástí toho pole? A nebude to pak nechávat jako součást názvu (podnázvu...) třeba při tvorbě citace? To si tak trochu říkám i u toho rovnítka, že ho tam může mást.

Ale asi bych to teď neřešila a držela se šablony, kterou používají téměř všichni. Úprava šablony se řešila v issue #301 a uzavřelo se to s tím, že se nebude měnit. 
Pokud bylo tohle issue otevřené kvůli problému, který ve skutečnosti neexistuje, tak bych ho uzavřela.

**Comment by pokorsky** [comment]
> Ad 1. ano, doplňování ":" dělá jenom ProArc a to nás při zpracování mátlo, protože jsme ho používali poprvé. Takže tuhle část není potřeba řešit.

Ivano, tohle je záležitost LoC XSLT, ne ProArcu.

**Comment by slapakovai** [comment]
Ano, souhlasím, že issue můžeme uzavřít beze změn.
