### ISSUE TITLE
Formulář eČlánek: první stránka článku

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#318]
První stránka článku do elementu part extent by se měla stahovat z pole 
773$q, hodnota za "<"
Příklad: 
http://aleph.lib.cas.cz/F/?func=direct&doc_number=001804419&local_base=AV

Original issue reported on code.google.com by `slapakov...@gmail.com` on 14 Jul 2015 at 12:19

**Comment by slapakovai** [comment]
A je tedy možné, aby se 1. stránka z pole 773$q stahovala do mods/part/extent?

**Comment by pokorsky** [comment]
Možné to je, ale jaký je důvod to ukládat nestandardně? Proč nelze použít pole `mods/relatedItem/part/extent`, aby to fungovalo i pro ostatní případy? Pro formulář eČlánek by se pak mohla zobrazovat místo `mods/part/extent` editovatelná pole `mods/relatedItem/part/extent`.

**Comment by slapakovai** [comment]
Jo, to by bylo nejlepší, mohl bys to tak prosím předělat.

**Comment by pokorsky** [comment]
`part/extent` přesunut do `relatedtem` ve formuláři.
