### ISSUE TITLE
Feature requests: Mazání dat z úložiště, import PSP balíčku, import FOXML

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#320]
```
Dobrý den,

výhledově bychom velice ocenili následující funkce:

1) Možnost mazat data z fedory přímo z proarcu
Mazat je ručně na disku se neodvážím a diskový prostor bohužel není 
nafukovací, takže dříve nebo později to budeme potřebovat.

2) Možnost importovat PSP balíček do proarcu
Souvisí s bodem 1. Abychom mohli data smazat z proarcu, musí existovat 
možnost tam již vyexportovaná data znovu naimportovat k případným 
opravám nebo dalšímu zpracování.

3) Možnost importovat foxml
Výhledově budeme určitě chtít konvertovat starší data do standardu NDK, 
tedy do PSP formátu. Ta data v té době už určitě budou v K4, takže 
předpokládám, že bude jednodušší implementovat import foxml do proarcu, 
než řešit problematické formáty jako Sirius K3.

Podotýkám, že tady bude nejspíš problém v několika věcech:
- Ve FOXML jsou grafická data odkazována z imageserveru (respektive mohou 
být, ale u nás bez výjimky jsou)
- K4 foxml odkazuje (alespoň nepřímo) pouze UC verze obrazových souborů, 
bude k nim tedy potřeba přidat ještě jejich MC verze
- starší data nemají ALTO xml, takže jej také bude třeba doplnit

Možná by to šlo vyřešit tak, že by se do proarcu ručně naimportovala 
dávka obsahující standardní tiffy a jejich ALTO a OCR txt a k ní se 
přiřadila metadata naimportovaná z FOXML?
```

Original issue reported on code.google.com by `Michal.S...@gmail.com` on 5 Aug 2015 at 9:20

**Comment by pokorsky** [comment]
Děkuji za návrhy.
> 1) Možnost mazat data z fedory přímo z proarcu

Tato funkce by byla možná po implementaci archivační funkcionality plánované pro další verzi. Zatím je Fedora brána jako archiv, kde nechtěné smazání není žádoucí. Mazaným objektům je jen nastaven příznak `Deleted`.

> 2) Možnost importovat PSP balíček do proarcu

Toto není v plánu. Exportem do PSP se ztratí spousta údajů. Opět by mělo být řešeno chystanou archivační funkcionalitou. Rozšířený PSP balík.

> 3) Možnost importovat foxml

FOXML je jen obálka, podobně jako METS. Bylo by potřeba definovat co je obsahem a jak tento obsah namapovat. Asi nejjednodušší by bylo vytvořit konverzní nástroj, který by z takových dat vytvořil archivační balík a ten pak v případě potřeby načíst do ProArcu. V podstatě to co popisujete v posledním odstavci.

Nejsem si jistý podobou K3 dat. V K4 skoro určitě nemáte uložené skeny v TIFF, ale jen nějakou ztrátově komprimovanou podobu v JPEG nebo JPEG2000. Validní NDK PSP přímo z K4 FOXML tedy udělat nepůjde.

**Comment by pokorsky** [comment]
Mazání je implementováno jako issue #453.

**Comment by slapakovai** [comment]
Import balíčků bude řešen v: https://github.com/proarc/proarc/issues/451
