### ISSUE TITLE
Nový formulář CEJSH článek

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#321]
Prosím o vytvoření nového zjednodušeného formuláře CEJSH článek.
Návrh elementů:
https://docs.google.com/document/d/1iwjK5Ti0vPvLA2sIdBJhSeUiGFPZx_GQ1eG4GfdT6wU/

Formulář by měl fungovat pro model article, stejně jako formulář 
ečlánek.
V menu metadata bude položka "formulář" pro ečlánek, ten se také bude 
zobrazovat jako první. Potom položka "zjednodušený formulář" pro CEJSH 
článek.

Original issue reported on code.google.com by `slapakov...@gmail.com` on 7 Aug 2015 at 9:23

**Comment by pokorsky** [comment]
Připravil jsem k otestování formulář podle požadavků. Do dokumentu jsem přidal komentáře k nedostatečné specifikaci nebo nerealizovatelným bodům. Formulář není pro model article, ale **model:bdmarticle** - eČlánek

Osobně toto řešení s jednoduchým a ještě jednodušším formulářem pro jeden model digitálního objektu nedoporučuji. Uživatele to jen zmate a pokud použije nejjednodušší formulář na převzatý záznam z katalogu, tak se mu tam začnou objevovat nesmyslné hodnoty. Zbytečně to navíc komplikuje správu formulářů.
