### ISSUE TITLE
Podpora starých tisků

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#322]
Tento úkol zastřešuje implementaci zpracování starých tisků.

Specifikace 
https://docs.google.com/document/d/1cmV1LqlZGepNDZEPmTcOpqHaaI0L5wwxq6jj73eHG_M/edit?usp=sharing

Original issue reported on code.google.com by `pokor...@gmail.com` on 11 Aug 2015 at 2:48
* Blocked on: #120, #294, #323

**Comment by nezbedova** [comment]
Myslím si, že u popisu stran je pojem "Aplikovat včetně první sterany" zavádějící. Dávám k posouzení, zda to nenahradit výrazem "Aplikovat od první strany" a do nápovědy "Aplikovat od první označené strany na každou další podle Aplikovat na" 
Osobně bych si to nechala trvale zaškrtnuté (s možností odškrtnutí), protože mi přijde logičtější paginovat od označené (tedy od první) strany. Jak to vidí ostatní?

**Comment by luckajirku** [comment]
Mně spíš přijde zavádějící "Aplikovat od první strany":-), to "včetně" je na místě. Ale asi bych tam rovnou přidala to "označené", ne až do nápovědy. (Akorát - ale tohle bude asi čistě jen můj problém:-) - s tím včetně je to trochu kostrbaté, jakože aplikujeme strany, ne čísla... Hm, vyhodila bych to Aplikovat (stejně to je nad tím - Aplikovat na:) a nechala tam jen "včetně první označené strany".) 

Automaticky zaškrtnuté bych to nenechala, to mi zas přijde logičtější, když si označím deset stran a chci to použít na každou druhou, že mi to tak načísluje strany 2, 4, 6, 8, 10, a ne 1, 3...

**Comment by pokorsky** [comment]
Poslední 2 komentáře patří do issue #294. Mně `Aplikovat včetně první strany` a `Aplikovat od první strany` přijde významem stejné. Jinak tohle si klidně odhlasujte. Možná by pomohlo napsat do nápovědy ty 2 rozdílné řady na ukázku `(1, 3, ... / 2, 4, ...)`. Jen prosím buď otevřete issue #294 nebo zadejte novou.
