### ISSUE TITLE
"Uloženo" v Import - vybrat nadřazený digitální objekt

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#325]
Taková drobnost, která ale může být pro začínající uživatele matoucí - najdu nadřazený objekt, dám "vybrat", problikne "Uloženo". (Uživatel si může myslet, že už má hotovo.) Když pak dám Uložit dávku, problikne zase Uloženo. Chápu, že je v prvním případě uložena volba, ale vzhledem k tomu, že je tam pak ještě možnost uložení, bylo by lepší, kdyby to psalo nevím třeba Objekt vybrán. V angličtině to je OK, tam se to liší (Select => Saved => Import), matoucí to je jen v češtině (Vybrat => Uloženo => Uložit).

**Comment by nezbedova** [comment]
Souhlasím. Navrhuji "Vybráno". = Po kliknutí na "Vybrat" problikne v horní části obrazovky obdélníček s hláškou "Vybráno" místo "Uloženo".

**Comment by pokorsky** [comment]
Změněno na `Výběr uložen.` a `The selection saved.`.
