### ISSUE TITLE
STT formuláře - atribut typeOfResource/manuscript

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#326]
Vypadá to, že se atribut typeofResource/manuscript přidává automaticky do všech objektů vytvořených ve formuláři STT Svazek monografie a STT Příloha monografie. Což ale není úplně dobře.

U objektů vytvářených stažením záznamu by se měl myslím doplňovat pouze, když:

" </xsl:if>
<xsl:if test="$leader6='d' or $leader6='f' or $leader6='p' or $leader6='t'">
<xsl:attribute name="manuscript">yes</xsl:attribute>
</xsl:if> "

A v nových prázdných objektech by nemělo být automaticky zvoleno "yes", ale prázdno.

**Comment by luckajirku** [comment]
Hm, nevím, jak to tam zkopírovat, aby se to nezobrazovalo takhle divně. Mělo by to dávat "manuscript", když jsou v LDR na těchto pozicích tyto hodnoty: 
$leader6='d' or $leader6='f' or $leader6='p' or $leader6='t'

**Comment by pokorsky** [comment]
Specifikace STT říká, že atribut manuscript="yes" má být vždy. Tedy 
neřídí se podle LoC XSLT. Asi je to logické, protože kdo nechce založit 
STT Svazek, tak založí NDK Svazek.

JP

**Comment by luckajirku** [comment]
Jenomže manuscript nerovná se STT. A atribut manuscript můžeš použít i u novodobých dokumentů (rukopisy, vlastně asi i strojopisy...)

**Comment by pokorsky** [comment]
Netvrdím, že by se `manuscript` rovnal STT. Jen říkám, že specifikace STT, přidává manuscript bez rozlišení. Nikdo to zatím nerozporoval.

Pro případ, že je potřeba řídit manuscript podle LoC, tak by byla možnost využít NDK Svazek. Ty formuláře jsou kromě atributu manuscript stejné. Pak ale v historii nerozlišíš svazky STT od NDK. Pro Kramerius to neplatí. Pro ten jsou oba objekty exportovány jako `model:monograph`.

Jestli se má `manuscript` v STT chovat jinak, tak se prosím dohodni s @nezbedova. Je potřeba popsat jak má vypadat pole ve formuláři a jak se má chovat MODS při založení prázdného záznamu a při převzetí záznamu z katalogu (asi podle LoC). Nyní se za všech okolností přidává `<typeofResource manuscript="yes">text</typeofResource>`.

**Comment by luckajirku** [comment]
Tak ono nebylo co rozporovat, ve specifikaci je jen "Přidat typeResource@manuscript=”yes”" - a z toho není jasné, jestli se bude přidávat vždy automaticky, nebo jen za určitých okolností. 
Jinak specifikaci můžu jen prohlížet, když mi tam povolíš návrhy nebo aspoň komentáře, tak to tam dopíšu.

**Comment by pokorsky** [comment]
Při implementaci jsem to četl přesně tak, jak je to tam napsáno :smile:. Přístup přidán. Jinak o větší přístup může snadno požádat kdokoli přímo v GC dokumentu.

**Comment by luckajirku** [comment]
Je to tam. Jde o to, že to není kosmetická záležitost, tímhle bychom si do metadat zanášeli opravdu chyby (a nebo bychom museli pak poctivě odmazávat ručně, co by se automaticky doplnilo, a to je nesmysl :-)).

**Comment by nezbedova** [comment]
Souhlasím se změnou dle návrhu LJ.

**Comment by pokorsky** [comment]
@nezbedova: Dobře, upravíte tedy specifikaci?

Není mi jen jasné, k čemu teď budeme mít samostatné objekty STT svazek + příloha, když se popisná metadata zpracovávají naprosto stejně jako NDK svazek + příloha. Jediný rozdíl byl v atributu manuscript a ten jsme mohli přidat jako volitelný k NDK. STT strana se liší rozsahem typů stran a povinných datastreamů, tam samostatný objekt dává smysl.

Jediný přínos vidím v možnosti filtrovat STT ve vyhledávání a STT blokuje NDK export, protože nemusí mít všechna data (ALTO, OCR).

**Comment by nezbedova** [comment]
P. Jirků mi psala, že to do specifikace již napsala.

Původně jsem chtěla pouze přidat nové typy stran. Postupně se došlo až k 
samostatnému formuláři. Filtrování i blokace jsou důležité. Také, pokud 
se nepletu, by bylo možné podle potřeby upravit formulář tak, aby 
splňoval nároky popisu STT, ikdyž by to bylo v rozporu s NDK.

Dne 28.8.2015 v 16:04 pokorsky napsal(a):

**Comment by pokorsky** [comment]
Ve specifikaci je to zatím jen jako návrh. Budete chtít k tomu poli ve formuláři přidat nějakou nápovědu? Jak to bude s atributem manuscript u STT Strana? Ptal jsem se tam v komentáři.

Pokud se to filtrování hodí, tak to nebyla zbytečná práce. S většími úpravami formuláře už nepočítám. Do teď je nikdo nepožadoval, ale ano, ta možnost tam je.

Můžete mi tady nebo do specifikace přidat permalinky na záznamy starých tisků, abych to mohl ověřit?  Díky.

**Comment by nezbedova** [comment]
https://aleph22.lib.cas.cz/F/8JQXC6GABSKUCY1NJVXLBIPGIJUEVKCFVKCI9DKQN36ALKYMYH-01015?func=full-set-set&set_number=018764&set_entry=000001&format=999

https://aleph22.lib.cas.cz/F/8JQXC6GABSKUCY1NJVXLBIPGIJUEVKCFVKCI9DKQN36ALKYMYH-01321?func=full-set-set&set_number=018766&set_entry=000001&format=999

https://aleph22.lib.cas.cz/F/8JQXC6GABSKUCY1NJVXLBIPGIJUEVKCFVKCI9DKQN36ALKYMYH-01933?func=full-set-set&set_number=018770&set_entry=000001&format=999

**Comment by nezbedova** [comment]
Navrhuji nápovědu "Rukopis". 
Myslím si, že manuscript u STT Strana je zbytečný.
Ano, šlo o možnost úprav do budoucna.

**Comment by pokorsky** [comment]
Všechny 3 odkazy se transformují bez `@manuscript`, což se podle LDR zdá být správně.
`typeOfResource@manuscript` se nyní nepřidává, pokud jej nepřidá sama šablona. Platí pro všechny STT objekty.

**Comment by luckajirku** [comment]
Jen by to chtělo ještě otestovat na rukopisu, příklad teď bohužel nedám, máme tenhle víkend odstavený Aleph.

**Comment by nezbedova** [comment]
https://aleph22.lib.cas.cz/F/6J9E9JS1RXFC5Y3UNBN4J3YVNRECHGHUPXDFF2JVIEXISDT2U6-04043?func=item-global&doc_library=KNA01&doc_number=001038677&year=&volume=&sub_library=KNAV

**Comment by luckajirku** [comment]
Hm, tady asi narazíme. Jinak tady se "rukopis" (počítám z 245 h) dostává do physicalDescription/form - authority gmd. 

<mods:physicalDescription>
        <mods:form authority="marcform">print</mods:form>
        <mods:form authority="gmd">rukopis</mods:form>
        <mods:extent>1 list : malba zlacená na papíře.</mods:extent>
    </mods:physicalDescription>

**Comment by luckajirku** [comment]
Takže buď ještě upravit šablonu, aby se "manuscript" vytvořil i případě, že to v LDR není, ale je v 245 $h "[rukopis]", nebo šablonu nechat jak je a dávat to tam ručně, když tam ta možnost teď je (nakonec těch rukopisů nebude tolik, aby to nešlo uhlídat, ne?)

**Comment by nezbedova** [comment]
Souhlasím. V případě rukopisu se to zaškrtne ručně, opravdu jich není tolik.
