### ISSUE TITLE
STT - cz ekvivalent pro typ strany BackCover

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#327]
Bylo domluveno, že typy stran, které v ProArcu existují, zůstanou i pro STT a jen se přidají nové. Ale BackCover je v NDK jako "Zadní desky" - a v STT jako "Zadní deska vazby". Mělo by to to být co nejvíc sjednocené, navíc to vypadá divně i v rámci STT, když je tam pro FrontCover "Přední desky", ale pro BackCover "Zadní deska vazby".

**Comment by pokorsky** [comment]
Tohle je na @nezbedova. Typy jsou podle tabulky ve [specifikaci](https://docs.google.com/document/d/1cmV1LqlZGepNDZEPmTcOpqHaaI0L5wwxq6jj73eHG_M/edit?usp=sharing) z 201508024 a diskuze na [proarc-users](https://groups.google.com/d/msg/proarc-users/DhCKrpz7FFE/hS3RCpnvBQAJ). Nejspíš s tím bude souviset issue #309. Tam stále chybí vyjádření z Jenštejna.

Dokud tady nebudou typy stran odsouhlaseny, tak už je znovu měnit nebudu.

**Comment by luckajirku** [comment]
S 309 to nesouvisí, tyhle dva typy jsou jasné.

**Comment by nezbedova** [comment]
Opravila jsem to. Pro NDK i STT stejný výraz "Zadní desky".

**Comment by pokorsky** [comment]
Změněno.
