### ISSUE TITLE
STT - Kopírování údajů z STT Svazek monografie do STT Příloha monografie

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#329]
Bylo by dobré, aby se i u STT kopírovaly některé údaje ze svazku do přílohy monografie, stejně jako je to u NDK (s tím, že tady nebudeme mít identifikátory ččnb, isbn...), aby nedocházelo při ručním kopírování ke zbytečným chybám. Určitě:

- všechny titleInfo bez type včetně subelementů title, subtitle
- všechny language
- všechny physicalDescription/form
- všechny dateIssued

+ přidat DateCreated? Nebo i něco dalšího? Co na to Jenštejn?

**Comment by pokorsky** [comment]
Z Jenštejna se zatím nikdo nepřidal jako [watcher](https://github.com/proarc/proarc/watchers) projektu. Je potřeba na ně odkázat pomocí @nezbedova nebo použít Assignee, aby přišel mail.

**Comment by luckajirku** [comment]
Assignee nepřidám, mám asi jen Read.

**Comment by pokorsky** [comment]
Aha. Assignee může přidat asi jen vlastník projektu. Granularita práv pro nastaveních issues není v podstatě žádná. Pak tedy používat odkazy pomocí `@` viz. [Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by nezbedova** [comment]
Souhlasím s kopírováním podle NDK. Nic dalšího mne nenapadá.

**Comment by pokorsky** [comment]
Udělal jsem to stejně jako v případě NDK monografické přílohy v issue #240.
Kopírují se

- všechny titleInfo bez @type včetně subelementů title, subtitle
- všechny language
- identifikátory typu ccnb a isbn. Platné i neplatné.
- všechny physicalDescription/form
- všechny dateIssued
