### ISSUE TITLE
STT - Řazení modelů 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#330]
Řazení modelů, kdy jsou STT modely před NDK, asi není úplně ideální. Přeci jen novodobých dokumentů se bude zpracovávat víc (alespoň u nás). Vyhovuje to KNAV takhle, jak je to v beta verzi nebo byste byli pro změnu řazení? Viděla bych to na:
NDK
STT
e-článek ... 
K4
Prosím o vyjádření @nezbedova

**Comment by pokorsky** [comment]
Řazení skupin modelů závisí na pořadí pluginů v `proarc.cfg`. Každá instalace to může mít podle vlastní potřeby. STT jsem dal na začátek jen pro testovací účely.
