### ISSUE TITLE
testovací - automatické přepnutí po načtení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#331]
V testovací ProArcu
Po načtení nových souborů nedojde k automatickému přepnutí obrazovky z "Import - výběr adresáře" na "Import - příprava metadat". Musí se přes historii, což je nepraktické.

**Comment by nezbedova** [comment]
Chyba se objevuje při použití Mozily. U Google chrom, to je v pořádku.
Zavírám.

**Comment by pokorsky** [comment]
Pokud přepnutí ve Firefoxu neproběhne, tak je to chyba. Podporujeme oba prohlížeče. Asi to bude duplikát issue #260.
