### ISSUE TITLE
nový formulář pro cejsh článek

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#332]
Šlo by přidat zjednodušený formulář pro cejsh článek do seznamu nových objektů při jejich zakládání? Takhle je to docela dost klikání, když se musí založit nejdřív ečlánek a potom se přes metadata prokliknout na zjednodušený formulář.

**Comment by pokorsky** [comment]
Bez zásadnějších úprav klienta ne. Jak píšeš, tak je to seznam nových objektů, ne nových formulářů. Řešením je samostatný objekt s vlastním formulářem.
