### ISSUE TITLE
cejsh - údaje o autorech

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#333]
Prosím udělat podle zadání ve specifikaci:
"name part zopakovat třikrát jednou nazvat „Křestní jméno“ a přednastavit type given, type nezobrazovat ve formuláři, podruhé nazvat „Příjmení“ a přednastavit type family, type nezobrazovat ve formuláři, potřetí nazvat „Šifra nebo autorství redakce“ bez atributu type"

Jestli to nejde, tak dovysvětlit proč - ten komentář ve specifikaci nebyl dostatečný. (V Orbeonu to takhle normálně funguje, takže by to mělo jít.)

Pokud to opravdu nepůjde, tak bude potřeba dopřeložit to, co zůstalo anglicky, včetně nabídky v roletce a dopsat jinou nápovědu. To bych oboje udělala já.

**Comment by pokorsky** [comment]
V tom případě doporučuji používat Orbeon. Ten formulář jistě ukládal data do vlastního XML schema, ne do univerzálního MODS.

Jde o to, že výsledkem obou formulářů má být nyní MODS záznam, ale tvůj formulář očekává transformaci navíc. Elementy `mods/name/namePart` by se musely transformovat na 3 speciální elementy (Jméno, Příjmení, Šifra nebo autorství redakce). Tomu ale zase nebude rozumět ten původní formulář.

Řešením je samostatný objekt s vlastním formulářem a vlastní XSL transformací při načítání a ukládání z a do MODS. U převzatých záznamů MARC21 z katalogu to ale stále může dělat problémy. Viz. issue #321. To Orbeon neřešil nejspíš vůbec.

**Comment by slapakovai** [comment]
Ok, díky za vysvětlení. Teď už tomu rozumím, proč to nejde.
Takže já se podívám na ty překlady z angličtiny a pošlu ti je.

**Comment by slapakovai** [comment]
family - "příjmení"
given - "křestní jméno"
termsOfAddress - odstranit pryč

nameParts - znovu jako "Údaje o autorech"
Type - "Typ jména"
namePart - "Jméno"

U Type je nápověda, kde je family a given, takže v nápovědě taky prosím změnit do češtiny a termsOfAddress odstranit.

Nápověda u namePart - prosím změnit poslední odstavec na: "Pokud nelze rozlišit křestní jméno a příjmení, nepoužije se typ jména a jméno se zaznamená v podobě jaké je do jednoho pole Jméno."

**Comment by pokorsky** [comment]
Nepřidala jsi popis do dokumentu.

Upraveno.

**Comment by slapakovai** [comment]
Popis přidán do dokumentu.
