### ISSUE TITLE
cejsh - rozsah článku

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#334]
Dát do samostatného rámečku, takhle u údajů o recenzi je to matoucí. Já vím, že to je v jednom elementu, ale vůbec to nepatří k sobě.

**Comment by pokorsky** [comment]
Vůbec nerozumím požadavku. O jaký formulář se jedná? O jaké údaje se jedná? A co nepatří k sobě? Jestli jde o zjednodušený jednoduchý formulář, tak prosím upravit i specifikaci. Mimochodem rozsah článku tam samostatný rámeček má. Díky.

**Comment by slapakovai** [comment]
Jedná se o zjednodušený formulář cejsh. Údaje o rozsahu článku. tzn. první a poslední stránka článku. Tyto údaje nepatří k údajům o recenzi. Potřebovala bych to ve dvou rámečcích i když se jedná o jeden element.

**Comment by pokorsky** [comment]
Jestli správně rozumím jde o opakování `mods/relatedItem`. Je to stejný problém jako issue #333. Tady jsi navíc nepopsala, jak by se ty 2 opakování měly rozlišit. Nějaký atribut? Bez samostatného digitálního objektu to bude problém. Proč nemůže být eCejshČlánek?

**Comment by slapakovai** [comment]
Jde mi o to, jestli by elementy relatedItem/part/extent/start a relatedItem/part/extent/end mohly být v jednom samostatném rámečku pro rozsah článku.
A elementy relatedItem/name, relatedItem/originInfo a relatedItem/titleInfo by mohly být ve druhém rámečku pro údaje o recenzi.

**Comment by pokorsky** [comment]
Mohly, pokud bude samostatný objekt eCejshČlánek. Viz. můj předchozí komentář.

**Comment by slapakovai** [comment]
Bude se případně řešit v budoucnu, pokud se rozhodneme udělat ze zjednodušeného CEJSH formuláře samostatný objekt.
