### ISSUE TITLE
šířka rámečků ve formulářích

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#335]
Šlo by nějak udělat, aby všechny rámečky ve formulářích byly stejně široké? Zlepšila by se tím přehlednost při vyplňování a formuláře by byly mnohem přívětivější pro čtení.

**Comment by pokorsky** [comment]
Rámečky určitě roztáhnout půjdou. Stejně široké asi nikdy nebudou, protože jsou do sebe i několikrát vnořené (MODS).

O které formuláře by se jednalo? V případě CEJSH to můžu udělat hned, pokud jde o ostatní formuláře, tak by jsi měla oslovit ostatní uživatele na https://groups.google.com/d/forum/proarc-users. Tohle nechci rozhodovat za ty, co formuláře používají.

**Comment by slapakovai** [comment]
Tak to prosím udělej v případě cejsh - zjednodušený i složitý formulář. Roztáhnout vnější rámečky na šířku toho nejširšího a vnořené rámečky vždycky co nejširší, co se dovnitř vejde.

**Comment by nezbedova** [comment]
Já jsem také pro rámečky stejné šíře.

**Comment by luckajirku** [comment]
My bychom byli raději, kdyby se to nechalo, jak to je. Sice by to bylo na pohled hezčí, ale na druhou stranu právě ta odlišná šířka zlepšuje to, na co se poukazuje v zadání - přehlednost při vyplňování. Totiž jak tam vznikají ty "zuby", tak člověk při procházení dlouhého formuláře jasně vidí, kde mu končí jeden element atd. a začíná další, když budou (v rámci možností) stejné, tak se to slije...

**Comment by slapakovai** [comment]
Právě proto bych to chtěla vyzkoušet aspoň na jednom formuláři - jak se s tím bude pracovat.
Možná by tedy pro přehlednost bylo dobré udělat větší mezery mezi rámečky jednotlivých elementů? Co si o tom myslíte?

**Comment by nezbedova** [comment]
Širší mezery prodlouží délku formuláře. My většinu záznamů taháme z Alephu, doplňujeme toho jen málo.

**Comment by slapakovai** [comment]
Sjednotit šířku formulářů jen ve formuláři pro ečlánek. Ostatní zatím nechat tak, jak jsou.

**Comment by pavelkocourek** [comment]
Přesunuto : šířka rámečků ve formulářích (#335) #32
