### ISSUE TITLE
cejsh - typ názvu

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#336]
Prosím změnit na české typy:
Abbreviated - Zkrácený
Alternative - Variantní
Translated - Přeložený
Uniform - Unifikovaný
Pokud to jde zvolit pouze pro formulář na články, tak stačí typy variantní a přeložený.

**Comment by pokorsky** [comment]
Ano, jde to omezit na články. Předpokládám, že jde o zjednodušený jednoduchý formulář.

**Comment by slapakovai** [comment]
Ano, ta issues, která mají v názvu cejsh se týkají zjednodušeného formuláře.

**Comment by pokorsky** [comment]
Pak je asi lepší uvádět odkaz na původní issue #321. Tím se to taky automaticky prolinkuje.

Změněno.
