### ISSUE TITLE
prázdný formulář

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#338]
Když se přidá nový formulář do existující struktury, nic se tam nevyplní a neklikne se na uložit, tak tam stejně zůstane jako nevyplněný formulář. Je to tak správně? Myslím, že pokud se neklikne na uložit, tak by tam neměl zůstávat.

**Comment by luckajirku** [comment]
To se snad chová pořád stejně a nikdo s tím problém nemá.
Ve struktuře přes plus vyberete objekt, v nápovědě máte "Přidat nový digitální objekt", takže přidá objekt. Pod "Uložit" je nápověda "Uložit změny", takže když nic nezměníte a nekliknete na uložit, zůstane vám váš původní objekt. 
Když zakládáte nový mimo strukturu, zase dáte "vytvořit nový objekt", a tam zase stejně - Uložit = "uložit změny" do předtím vytvořeného objektu.

**Comment by slapakovai** [comment]
Jenom se snažím eliminovat co nejvíc chyb, které mohou začít vznikat ve chvíli, kdy ProArc začnou používat nekvalifikovaní uživatelé. A to že tam zůstane prázdný formulář, který jde exportovat, považuju za chybu. Navíc ta chyba vznikne strašně snadno.

**Comment by pokorsky** [comment]
Ano, kliknutím na akci Nový objekt vznikne nový objekt. To není chyba, ale vlastnost. Není pravda, že by se nic nevyplňovalo. Kromě identifikátoru se například kopírováním z nadřazených objektů předvyplňují některé údaje u některých objektů (vydání, přílohy, ...), vzniká RDF vazba mezi objekty, .... Pokud uživatel nechce nový objekt zakládat, tak na akci jednoduše neklikne. Nechtěné objekty je možno smazat. Akce Uložit ukládá skutečně jen změny, tak jak je popsáno v nápovědě tlačítka.

Stále je možnost napsat kvalitní návod pro nekvalifikovaného uživatele. Ať už "nekvalifikovaný" znamená co chce.
