### ISSUE TITLE
cesh - typ obsahu článku

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#339]
Lze výběr v roletce nastavit pro každý formulář jinak? Jestli ano, tak prosím pro cejsh článek nastavit tyto hodnoty (u nových píšu i anglické překlady a konstanty):

hlavní článek
zpráva
recenze
úvodník - editorial - Editorial
obálka - cover - Cover
obsah - table of contents - TableOfContents
reklama
nekrolog - obituary - Obituary
medailonek - biographical portrait - BiographicalPortrait
rejstřík
tiráž - colophon - Colophon
rozhovor - interview - Interview
anotace - annotations - Annotations
abstrakt
bibliografie
nespecifikován

Jestli to nejde pro každý formulář zvlášť, tak prosím přidat ty nové hodnoty.

**Comment by pokorsky** [comment]
Ano lze. Současné typy elementu genre nejsou lokalizované (pouze česky), ale i to je nyní možné.

Minimálně `table of contents` je konstanta z NDK, není nová. Nevím odkud čerpáš své konstanty, ale bylo by dobré, kdyby syntaxí odpovídaly těm z NDK.

Popis typů prosím přidej do tvé specifikace viz. issue #321.

**Comment by pokorsky** [comment]
Dosud žádná reakce. Přidáno do zjednodušeného formuláře.

**Comment by slapakovai** [comment]
Já jsem jenom připsala, které hodnoty chci nově do combo boxu ve formuláři oproti těm, které tam už byly nastavené. Takže tím jsem myslela to, že jsou nové.
Syntaxí nemůžou odpovídat těm z NDK, když tam není dodržována jednotná syntaxe. Takže jsem se držela syntaxe, kterou jsme si dohodli už u typů stránek.
Jak moc velký problém je to s tou syntaxí?
Přidáno do dokumentu se specifikací.

**Comment by slapakovai** [comment]
A anglicky to tam nepotřebuji, stačí mi to česky. Jenom jsem si nebyla jistá, jestli to někde nemáme přeložené.
