### ISSUE TITLE
vyhledávání záznamu

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#341]
Když vyhledávám záznam pro stažení z katalogu knav, tak mi to někdy nevrátí žádné výsledky, bez ohledu na to, jestli hledám podle názvu, autora nebo sysna.
Např. http://aleph.lib.cas.cz/F/?func=direct&doc_number=001920957&local_base=AV
http://aleph.lib.cas.cz/F/?func=direct&doc_number=001920693&local_base=AV

**Comment by pokorsky** [comment]
Hledání zobrazuje pouze to, co v tomto případě Aleph Z39.50 vrátí. A pokud jiné dotazy do stejného katalogu fungují, tak problém bude nejspíš na straně katalogu. Doporučuji kontaktovat administrátora katalogu.
