### ISSUE TITLE
nonSort není součástí popisu objektu eČlánek

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#343]
V popisu objektu (všude, kde je název objektu) se nezobrazuje element nonSort, takže pak název není celý. Prosím opravit.

**Comment by pokorsky** [comment]
Předpokládám, že je řeč o objektu eČlánek. `titleInfo/nonSort` pro popis eČlánku nebyl v issue #284 nikým požadován.  Popis objektu se používá jen pro tabulku vyhledávání, kde asi důležitý není. Přidám.

**Comment by pokorsky** [comment]
Narazil jsem na související problém s Dublin Core. Popis pro NDK článek i ostatní typy je v tomto zavádějící. V tabulce  není jasné, jestli se pro každou část titleInfo (title, subTitlte, partName, partNumber) má založit vlastní dc:title nebo jestli se mají elementy spojit do jednoho dc:title a jak. V NDK se s nonSort pro DC nepočítá. Kdyby ano, tak je jasné, že minimálně elementy nonSort + title by se měly spojit do jednoho dc:title.

Myslím, že správný postup by měl být podle LoC šablony MODS->DC, která spojuje mods:titleInfo do jednoho dc:title následovně:
nonSort + ` ` + title + `: ` + subTitle + `, ` + partNumber + `, ` + partName

Dává to takto smysl?

**Comment by slapakovai** [comment]
Jedná se o všechny objekty, nejenom o článek. Všude, kde se v ProArcu zobrazuje název uloženého objektu, tak tam není ten element nonSort na začátku.

Ano, dává to smysl.

Jenom mi není jasná jedna věc. Když to všechno spojíme do jednoho dc:title, tak potom zanikne hlavní funkce toho elementu nonSort? To znamená, že už se ty znaky z nonSort nebudou vylučovat z řazení v případě rejstříků nebo jakéhokoliv řazení podle abecedy?

**Comment by pokorsky** [comment]
NDK nonSort neřeší. Zatím to nikdo nepožadoval. Myslím, že u spousty objektů to nedává ani smysl (ročník, ...).

> Jenom mi není jasná jedna věc. Když to všechno spojíme do jednoho dc:title, tak potom zanikne funkce toho elementu nonSort?

Dublin Core žádné nonSort neřeší. Doporučuji nastudovat [zde](http://dublincore.org). Chceš-li řešit řazení, tak nerozumím proč plnit nějaký rejstřík záznamy v DC, když máš k dispozici MODS.

**Comment by pokorsky** [comment]
nonSort je přidán ve zjednodušeném formuláři eČlánku a je nyní součástí popisu objektu i DC.
