### ISSUE TITLE
cejsh - role autora

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#344]
Pro zjednodušený formulář prosím přidat k autorovi ještě navíc combo box role autora - popis jsem přidala do specifikace:
- Role nazvat “Role”, M
    - ponechat jako součást rámečku se jménem autora
    - type přednastavit hodnotu code a nezobrazovat ve formuláři
    - authority přednastavit hodnotu marcrelator a nezobrazovat ve formuláři
    - v combo boxu hodnoty: “autor aut, recenzent rev, překladatel trl, ilustrátor ill”.

**Comment by pokorsky** [comment]
změna formuláře z issue #321

**Comment by pokorsky** [comment]
Přidáno.
