### ISSUE TITLE
stahování záznamů z ANL

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#345]
Šla by přidat možnost stahovat záznamy i z databáze ANL, stejně jako jdou stahovat ze souborného katalogu?

**Comment by pokorsky** [comment]
Pokud je báze přístupná přes Z39.50 nebo XServer, tak ano. Je to záležitost [konfigurace](https://github.com/proarc/proarc/wiki/Konfigurace#aleph---z3950).
