### ISSUE TITLE
Propojení na bázi autorit

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#346]
Dlouhodobě je jako úkol zadáno zajistit propojení autorů na autoritní bázi a stahování údajů z této báze.
Bude se to řešit až v další fázi. Jenom to sem píšu, abychom na to nezapoměli.

**Comment by jkremlacek** [comment]
Vyžaduje změnu NDK standardu.

**Comment by krizovj** [comment]
A co by se ve standardu mělo změnit?

**Comment by jkremlacek** [comment]
Namísto údajů o autorovi by se měl uvést pouze identifikátor autora.

**Comment by krizovj** [comment]
To asi úplně nechápu teda. Do elementu name se v posledním standardu přidal element "nameIdentifier" (RA), kam je možné uvést Číslo národní autority. Myslel jste tím, že by tam byl jenom tenhle element? A co když ten autor v databázi národních autorit nebude? Tak je stejně potřeba tam ty údaje vypsat ručně.

**Comment by jkremlacek** [comment]
Pokud by nebyl v databázi, tak by se tam měl doplnit, aby byl jeden zdroj dat.

**Comment by luckajirku** [comment]
@jkremlacek tenhle předpoklad vychází z ideální představy, ne z reálné situace v knihovnách. V Národních autoritách není a nebude vše, ne všechny nově vytvořené autority se do Prahy posílají. Část autorit (někteří regionální autoři apod.) bude jen v lokální bázi té které knihovny.

**Comment by krizovj** [comment]
Přesně to jsem chtěla napsat. A navíc, když to není v autoritách, tak než se to tam přidá, může to zabrat i několik dní.

Právě na to propojení s databází AUT dělám zadání, myslela jsem že by to mohlo fungovat trochu jako stahování záznamů z katalogu.

**Comment by jkremlacek** [comment]
Pak by alespoň stálo za zvážení nastavení povinnost vzájemným vyloučením (pokud je jedna hodnota vyplněna, pak druhá nesmí být vyplněna), tedy:
pokud vyplním nameIdentifier, tak už nevyplňuji jméno/příjmení/... a  
pokud vyplňuji jméno/příjmení/..., tak nevyplňuji nameIdentifier

Jde o to, že mít nameIdentifier i jméno/příjmení/... vyplněné zároveň je redundance dat. Tak jako potomky objektu odkazuji pouze přes uuid a nevyplňují u čísla údaje o ročníku.

**Comment by luckajirku** [comment]
Nechápu, takže zobrazení autoritních údajů tam, kde by bylo v modsu uvedeno číslo autority, by se pak v Krameriovi dělo pouze propojením na NA???

**Comment by jkremlacek** [comment]
Přesně tak.

**Comment by luckajirku** [comment]
Takže budeme závislí na aktuální funkčnosti báze v NK.

**Comment by krizovj** [comment]
Přesně tak...

**Comment by luckajirku** [comment]
A to chceme?

**Comment by krizovj** [comment]
Já to určitě nechci

**Comment by luckajirku** [comment]
A počítá s tím zobrazovací šablona v Krameriovi? Jako mně to nepřijde rozumné. A jsou tu dvě věci. Jednak stažení údajů z autorit při práci s prázdnou šablonou, když autoritní údaje nestáhnu ze záznamu. Druhá věc pak bylo to propojení na autority kvůli autorským právům, které by se nějakým způsobem mohlo dít online, ale...

**Comment by krizovj** [comment]
Nevím, jestli to dělá i někdo z ostatních, ale pokud posíláme data do databází (záznamy článků), tak bude na funkčnosti databází NK závislý nejen Kramerius, ale taky ty databáze. 
Myslela jsem, že při tom propojení se prostě stáhne autoritní záznam do proarcu, jako je to když stahuju celý záznam z katalogu.

**Comment by ZdenkaSera** [comment]
@krizovj Můžeme tohle zavřít? Díky.

**Comment by krizovj** [comment]
@ZdenkaSera řekla bych, že ano. Konkrétní věci se asi vyřeší v jednotlivých issues.
