### ISSUE TITLE
cejsh - relatedItem/name

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#347]
Když ve zjednodušeném formuláři nevyplním autora recenzovaného díla, do metadat se přesto vyplní tohle:
<mods:relatedItem>
<mods:name type="personal"/>
Šlo by to udělat tak, že když se autor nevyplní, tak se neuloží element name?

**Comment by pokorsky** [comment]
Něco  ti tam chybí. Element vypadá následovně
```xml
<mods:relatedItem>
  <mods:name type="personal"/>
</mods:relatedItem>
```
Jelikož požaduješ `name@type="personal"` přednastavit, ale neukazovat, tak já pak na serveru nepoznám, jestli je atribut chtěný nebo ne. Tohle by chtělo opět samostatný objekt, abych to rozlišil. Něco s tím zkusím udělat.

**Comment by slapakovai** [comment]
Bude se případně řešit v budoucnu, pokud se rozhodneme udělat ze zjednodušeného CEJSH formuláře samostatný objekt.
