### ISSUE TITLE
zvýraznění polí M 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#348]
V testovacím ProArcu (a následně do nové verze STT a CEJSH) prosím červeně zvýraznit pole "Physical location - M" a "Shelf Locator - M" v rámečku "Location - MA" a zrušit červené zvýraznění pole "Language - R" v rámečku" Language of Cataloging - R"

**Comment by pokorsky** [comment]
Popis pravidel pro červenání je v issue #297. Jinde než pro instalaci CEJSH to zapínat nehodláme. Jak psala Ivana jinde, je to pomoc pro nekvalifikované uživatele což se snad Jenštejna netýká. Alespoň dříve byla shoda, že barevné formuláře nechceme. Na testovacím serveru to bylo zapnuto jen pro ověření.

Pokud chcete, aby byla některá další pole vyžadována/povinná při uložení, tak prosím vypište, kterých formulářů a jejich polí se to má týkat. Verze ProArcu je jen jedna. Každý si může aktivovat rozšíření/pluginy (STT, CEJSH, NDK, K4, DESA) podle svého uvážení v rámci vlastní instalace.

**Comment by nezbedova** [comment]
Děkuji za upřesnění. Máme všechna povinná pole, která potřebujeme.

Dne 9.9.2015 v 15:42 pokorsky napsal(a):

**Comment by pokorsky** [comment]
To jsem rád :smile: V tom případě to zavírám
