### ISSUE TITLE
DC title společný pro MODS titleInfo/*

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#352]
Narazil jsem na problém s mapováním elementů MODS titleInfo/* do Dublin Core title související s issue #343. Popis pro NDK článek i ostatní typy je v tomto zavádějící. V tabulce není jasné, jestli se pro každou část titleInfo (title, subTitlte, partName, partNumber) má založit vlastní dc:title nebo jestli se mají elementy spojit do jednoho dc:title a jak. V NDK se s nonSort pro DC nepočítá. Kdyby ano, tak je jasné, že minimálně elementy nonSort + title by se měly spojit do jednoho dc:title.

Správný postup by měl být podle LoC šablony MODS->DC, která spojuje mods:titleInfo do jednoho dc:title následovně:
nonSort + ` ` + title + `: ` + subTitle + `. ` + partNumber + `. ` + partName

**Comment by luckajirku** [comment]
výtah z NDK specifikace, ať je to přehledně na jednom místě:

PERIODIKA

TITUL PER.:
title => dc:title
subTitle => dc:title
partNumber => dc:description
partName => dc:description

ROČNÍK PER.:
partNumber => dc:description

ČÍSLO PER.:
title => dc:title
subTitle => dc:title
partNumber => dc:description
partName => dc:description

VNITŘNÍ ČÁST PER.:
title => dc:title
subTitle => dc:title
partNumber => dc:title
partName => dc:title

PŘÍLOHA PER.:
title => dc:title
partNumber => dc:description
partName => dc:title

MONOGRAFIE

VÍCESVAZKOVÁ MON.:
title => dc:title
subTitle => 0
partNumber => 0
partName => 0   

SVAZEK MON./KARTOGRAF./HUDEBNINA:
title => dc:title
subTitle => dc:title
partNumber => dc:description
partName => dc:description

VNITŘNÍ ČÁST MON.:
title => dc:title
subTitle => dc:title
partNumber => dc:title
partName => dc:title

PŘÍLOHA MON.:
title => dc:title
partNumber => dc:description
partName => dc:title

**Comment by pokorsky** [comment]
Díky. Upravím DC tak, že kde NDK definuje mapování na dc:title, tak tam dc:title vznikne spojením MODS titleInfo subelementů podle LoC s výjimkou těch, které mají být mapovány na dc:description. Hodnoty pro dc:description se nadále spojovat nebudou.

**Comment by pokorsky** [comment]
Upraveno.
