### ISSUE TITLE
Akce Katalog: zachování Location při aktualizaci metadat stažením jiného/aktualizovaného záznamu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#353]
Když budeme nahrazovat stávající metadata novými stažením jiného/opraveného záznamu přes akci Katalog, bylo by dobré zachovat Location z původního, pokud tam byl. Když pominu to použití u článků, tak se bude akce používat v případě potřeby nahrazení záznamem s kvalitnějším popisem nebo třeba v případě MKP by myslím mohli akci dobře využít pro znovustažení těch samých záznamů jako původně, až bude v ProArcu šablona upravená pro záznamy podle RDA. 

Když teď stáhnu záznam z jiného katalogu, dostanu tam zároveň s popisem cizí siglu/y a signaturu/y, což není žádoucí. Když stáhnu opravený záznam z vlastního katalogu (tedy ten samý záznam, který se stáhl původně) => v případě jednoho exempláře to bude ok, ale mohou tam být také signatury dupláků, které se nedigitalizovaly, a bude je zas třeba odmazávat a ponechat tam jen tu, která tam už byla.

Nenapadá nás případ, kdy by bylo při přepisu záznamu třeba změnit i tohle - exemplář, který se zdigitalizoval, zůstává stejný.

**Comment by slapakovai** [comment]
Já při zpracování článků sigly a signatury moc neřeším, takže za mě ok. Co na to Jenštejn?

**Comment by pokorsky** [comment]
Kterých objektů by se to mělo týkat? Mě tohle nepřijde moc rozumné. Lucko, tohle se může jednou hodit tak, jak popisuješ a někdo další zase bude očekávat uložení kompletního nového záznamu. Akce Katalog z #299 byla zamýšlena hlavně pro nové objekty založené v editoru Vazeb. Identifikátory UUID a URNNBN se zachovávají proto, že byly přiděleny až v ProArcu. Nebyly součástí původně převzatého záznamu.

**Comment by nezbedova** [comment]
U nás stahujeme data z RD nebo Alephu. Případné změny opravíme ručně.

**Comment by svetlym** [comment]
Z konzultace s kolegyněmi vyplynulo, že se nás tohle týkat nebude. V Proarcu totiž máme úplnější záznamy než v knihovním systému, takže znovustažením bychom degradovali kvalitu metadat.

(To je samozřejmě špatně, ale holt spolupráce s katalogizací byla taková, jaká byla. Výhledově každopádně budeme doplňovat záznamy v knihovním systému o to, co máme v Proarcu, nikoliv naopak.)

**Comment by pavelkocourek** [comment]
Schuzka 13.5.2019

**Comment by ZdenkaSera** [comment]
@luckajirku Prosím, nechcete se k tomuhle vrátit v rámci rozvoje?

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuji, My to občas používáme, ale není to tak časté. Zítra se ještě domluvím s kolegyněmi a případně issue navrhneme k uzavření.

**Comment by ZdenkaSera** [comment]
Na základě diskuse výše + potvrzení v DC KNAV zavírám.
