### ISSUE TITLE
V editoru digi dat/Média se arch./user copy (jp2) stahují s příponou bin

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#354]
Při stahování archivních a uživatelských kopií (jp2) v Editoru digi dat / Média se nám obrázky stahují s příponou .bin, ne .jp2. Po stažení a přejmenování je soubor ok.

(V Import - Příprava... se jak archivní, tak uživatelské kopie stahují normálně jako .jp2. Stažení Originál/tiff se zdá být bez problémů jak v importu, tak v úložišti.)

Chrome 45, FF 40, (IE 11)

**Comment by pokorsky** [comment]
Tyto koncovky přiděluje úložiště Fedora Commons automaticky podle mime type stahovaného obsahu  a `image/jp2` podle všeho nemá ve své databázi. Řešením je přidat registraci do souboru `${FEDORA_HOME}/server/config/mime-to-extensions.xml`
```xml
  <mime-mapping>
    <mime-type>image/jp2</mime-type>
    <extension>jp2</extension>
  </mime-mapping>
```
U TIFFu problém nenastává, protože `image/tiff` je v souboru registrován. V případě importní dávky je původní soubor k dispozici, takže je jméno správně.

**Comment by pokorsky** [comment]
Přidán popis do [wiki instalace](https://github.com/proarc/proarc/wiki/Instalace#fedora-commons).
