### ISSUE TITLE
RDF: datové schéma

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#355]

**Comment by lucka-pavlova** [comment]
Model je aktualizovaný.

**Comment by pokorsky** [comment]
Můžeš sem prosím přidat odkaz na dokument? Jestli je to ta prezentace, tak tam ještě chybí aktualizace WF_TASK. Díky

**Comment by lucka-pavlova** [comment]
link na GDoc (https://docs.google.com/presentation/d/1pdurzFFr8YV0YmGAk2Dd_26bG6P_6qDNYnmNZR8FUuY/edit#slide=id.p)

Ok, WF_TASK chyby - znovu to otevřu
