### ISSUE TITLE
cejsh: pole pro title a subtitle jako text area

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#357]
Prosím o předělání políčka pro elementy Title a Subtitle na pole typu text area o výšce 3-4 řádky.
Ve všech formulářích.

**Comment by pokorsky** [comment]
U všech formulářů ani není pole title. Dohoda je zatím na změně pro oba formuláře CEJSH.

**Comment by pokorsky** [comment]
Platí to i pro sekci relatedItem?

**Comment by slapakovai** [comment]
ano, i pro relatedItem

**Comment by pokorsky** [comment]
Změněno.
