### ISSUE TITLE
Nápověda při hodnotě delší než je délka pole

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#359]
Když je ve formuláři (NDK, STT, jinde jsem to nekontrolovala) vyplněna hodnota delší než je pole, tak se při najetí myši nezobrazí v bublině nápověda, ale ta vyplněná hodnota. Je to úmyslně?

**Comment by pokorsky** [comment]
Ano to je standardní vlastnost polí formulářů. Stejně by se to mělo chovat i v předchozí verzi.
