### ISSUE TITLE
Dokumentace CEJSH

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#360]
Přidat uživatelskou dokumentaci pro CEJSH.

**Comment by slapakovai** [comment]
Přidány kapitoly 1.2.4 Editor digitalizovaných dat, 1.2.4.1 Načtení nového digitálního obsahu a 2.8 Připojení plného textu v digitální podobě k již vytvořeným metadatům.

Do kapitoly 2.11 Export objektu doplněn cejsh export, do kapitoly 1.2.1 Editor metadat doplněn eČlánek.

Doplněn popis nových tlačítek zjednodušený formulář a náhled do všech relevantních kapitol.
