### ISSUE TITLE
zmizely některé náhledy stran

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#361]
Po roztažení okna ze zmenšeného na plné se ztratily malé náhledy v prostředním sloupci. Nepomohlo ani znovunačtení.
![chyba_chybi_obrazky](https://cloud.githubusercontent.com/assets/13831946/10013987/5a6a2364-6116-11e5-8657-25cc658caccf.jpg)

**Comment by pokorsky** [comment]
Nenapsala jste o jaký prohlížeč se jedná. Opravdu nepomohlo ani obnovení celé stránky?
Prohlížím si stejnou importní dávku ve Firefoxu 26 a Chromu 44 a na nic podobného jsem nenarazil.

**Comment by nezbedova** [comment]
Ve Firefoxu. Nepomohlo.

**Comment by pokorsky** [comment]
Ve Firefoxu jaké verze? Jelikož jste dávku teď uložila, tak s tím už nic nenadělám. Ale obnovení celé stránky pomůže.
Tohle je zřejmě nějaký náhodný vykreslovací problém prohlížeče. Pokud na to nenarazíte opakovaně, tak s tím nic nenadělám.

**Comment by nezbedova** [comment]
Teď to zkouším na další knize v Google Chrom. Jakýkoliv posun zmešení nebo zvětšení způsobí chybu ve vykreslování. Myslím si, že už se to jednou, velmi dávno, řešilo. Načíst data znovu nepomůže. Pomůže jen opětovné načtení celé stránky, které to hodí do základu.

**Comment by pokorsky** [comment]
Nechávám issue otevřené. Uvidíme, jestli na to někdo další také narazí. Já to reprodukovat nedokážu. Prosím ověřte, že nemáte zapnuté rozšíření v prohlížeči nebo nějakou antivirovou kontrolu síťové komunikace. Ověřte také, jestli máte dostatek místa na disku pro cache prohlížeče. Díky.

**Comment by luckajirku** [comment]
U některých dávek se nám to stává taky, když se to roztáhne hodně. Při zúžení prostředního sloupce (tak max. na šířku 4 a míň skenů) už nám tam pak jsou ale zase vidět všechny. 
Chrome 45

**Comment by pokorsky** [comment]
@nezbedova: Můžete to prosím otestovat s novou verzí 3.2?

**Comment by nezbedova** [comment]
Můžete, prosím, nasadit novou verzi na testování na https://sluzby.incad.cz/proarc/#import:%7B%22type%22:%22CONTENT%22%7D ?

**Comment by nezbedova** [comment]
Prostřední sloupec s náhledy funguje dobře. Ale zlobí krajní. Zkoušela jsem to v Mozile i a Google Chrom na dvou PC, protože můj stařičký notebook má se zobrazováním ProArcu trochu problémy - dlouho načítá.
Výsledek je stejný.
![proarc_3 1_1](https://cloud.githubusercontent.com/assets/13831946/19837683/80d0075c-9ebf-11e6-9831-a9bd1befd446.jpg)

**Comment by pokorsky** [comment]
Díky, v tom případě to můžeme uzavřít.
To co ukazujete dále je problém velmi malého okna. Pokud sloupce příliš zmenšíte, tak se začnou vykreslovat tímto způsobem. Podle dřívější dohody toto neřešíme, protože v produkci všichni používají dostatečně velké monitory a optimalizovat na přenosná zařízení není náš cíl.
