### ISSUE TITLE
změna názvu tlačítka

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#363]
V obrazovce "Historie - Uloženo" a "Chyba ukládání" přejmenovat tlačítko "Úložiště" na "Vazby".

**Comment by pokorsky** [comment]
Tlačítko se přidávalo loni v prosinci jako issue #272 jako akce "otevřít v úložišti". Navrhovaný název "Vazby" už mi přijde jako odklon od původního záměru, otevřít objekt  v úložišti. Nebylo by lepší upřesnit jen popis akce "Otevře nadřazený objekt označené importní dávky."?

**Comment by luckajirku** [comment]
Pro nás je "Úložiště" ok. 
Ten popis už jsme řešili, že je trochu zavádějící, u monografií to odpovídat bude (pokud to teda uživatel prvně neuloží špatně a pak hned nepřesune do jiného objektu), ale u periodik už nemusí (většinou tam, kam se to prvně uložilo, zůstane jen část dávky a zbytek se rozřadí do jiných objektů).
"Otevře nadřazený objekt, kam byla importovaná dávka uložena"? tím si asi taky nepomůžeme... 
Nebo to vysvětlit v dokumentaci?

**Comment by nezbedova** [comment]
Po kliknutí na "Úložiště" dojde k přepnutí do obrazovky "Editor připojených objektů". Do této obrazovky se ze "Správa digitálních objektů" dostaneme kliknutím na tlačítko "Vazby". Zdálo se mi to matoucí.

**Comment by pokorsky** [comment]
To ano, ale "Správa digitálních objektů" je správou v rámci úložiště i podle zařazení v menu. Je tedy zřejmé, že se pracuje nad úložištěm. Naproti tomu akce ve správci importů, které jsou mimo úložiště, je tato informace podstatná. Mělo by to naznačit, že se neotevře importní dávka (adresář), ale to, co je uloženo v úložišti.

Nejlepší by zřejmě bylo zobrazit seznam importovaných objektů a na každém umožnit přechod na objekt v úložišti. To by řešilo co popisuje @luckajirku.

Pokud toto vysvětlení stačí, tak navrhuji issue uzavřít.

**Comment by nezbedova** [comment]
Vysvětlení stačí. Děkuji.
