### ISSUE TITLE
Změna velkého písmene u modelů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#364]
V roletce s modely změnit velká písmena na malá u "NDK Příloha Periodika" a u "NDK Příloha monografie"

**Comment by pokorsky** [comment]
Opravdu chcete vše změnit na malá písmena? "ndk příloha periodika", "ndk příloha monografie". Proč jen u těchto názvů?

**Comment by nezbedova** [comment]
Vyjádřila jsem se nepřesně.
Prosím změnit "NDK Příloha Periodika" na "NDK Příloha periodika" a "NDK Příloha Monografie" na "NDK Příloha monografie".

**Comment by pokorsky** [comment]
Opraveno.
