### ISSUE TITLE
problikávání obrazovky ve FF 41

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#365]
V obou verzích u uživatelů Nezbedová a Polednová v obrazovkách Nová dávka a Historie není stabilizován obraz. Obraz "poskakuje", problikává informace "Načítám údaje".

**Comment by slapakovai** [comment]
Pod mým přihlášením se ProArc chová úplně stejně. Pořád problikává obrazovka, nejde na nic kliknout a nabídku menu nelze otevřít.

**Comment by luckajirku** [comment]
Nám se nic takového neděje - v testovacím ani v ostrém.

**Comment by pokorsky** [comment]
V obrazovce historie importů se žádné změny dlouho nedělaly. Problém se objevuje v nové verzi FF 41.0.1. Ve starší verzí FF nebo v Chromu vše funguje.

FF z nějakého důvodu neustále posílá stejný dotaz na server.

**Comment by pokorsky** [comment]
Ověřil jsem, že problém je v nekompatibilní změně Firefoxu ve verzi 41 https://www.fxsitecompat.com/en-US/docs/2015/urlutils-hash-no-longer-decodes-fragment.

Podle popisu na http://stackoverflow.com/questions/32840678/gwt-in-firefox41-repetitively-encodes-token-in-url/32907566#32907566 je dočasným řešením následující nastavení:
1. V adresním řádku FF napsat "about:config".
2. Nastavení "dom.url.getters_decode_hash" změnit na hodnotu "true" pomocí kontextového menu.

Problém by měl být opraven v poslední verzi GWT (>2.7.0). To ale pro verzi ProArc 2.1 není možné, protože to bude vyžadovat důkladné otestování.

**Comment by pokorsky** [comment]
Opraveno bez nutnosti upgradu GWT.
