### ISSUE TITLE
alto xsd v3

### ISSUE THREAD

**Issue by Jenyk** [proarc/proarc#367]
Import nové dávky, která obsahuje alto soubory s odkazem na XSD definici verze 3, padá na chybě "Cannot find the declaration of element 'alto'."

Ten samý soubor s odkazem na verzi 2 projde bez problému.
Počítá se s podporou xsd verze 3?

alto s v3 obsahuje: 
`<alto xmlns="http://www.loc.gov/standards/alto/ns-v3#" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-inn
stance" xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v3# http://www.loc.gov/alto/v3/alto-3-0.xsd">`

v2:
`<alto xmlns="http://www.loc.gov/standards/alto/ns-v2#" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/standards/alto/ns-v2# http://www.loc.gov/standards/alto/alto-v2.0.xsd">`

**Comment by pokorsky** [comment]
Ano, import validuje vstupní ALTO podle verze 2.0 a používá lokálně uložené schema. Validace v druhém případě prošla, protože jste použil očekávaný namespace `xmlns="http://www.loc.gov/standards/alto/ns-v2#" ` a nepoužil jste žádné nové elementy nebo atributy z verze 3.0. Použité ALTO je vlastně ve verzi 2.0 kromě hlavičky.

Technicky s validací 3.0 není problém, ale verze ALTO 2.0 je výslovně uvedena ve specifikaci NDK periodika 1.5, kterou momentálně podporujeme a teď jsem kontroloval, že se na tom nic nezměnilo ani v nové specifikaci [periodika 1.6, odstavec 1.3](http://www.ndk.cz/standardy-digitalizace/dmfperiodika16) vydané 21.9.2015. 

Výsledný balík PSP s ALTO 3.0 by nyní také neprošel NDK validátorem. Je to tedy spíše dotaz na NDK.

**Comment by Jenyk** [comment]
Ok, díky za vysvětlení.
