### ISSUE TITLE
Nefunkční build

### ISSUE THREAD

**Issue by Jenyk** [proarc/proarc#369]
Maven při buildu nenajde některé knihovny.
Repozitář http://developer.k-int.com/maven2/ už neexistuje, ale podle https://github.com/geonetwork/core-geonetwork/issues/1173 se dá najít na http://maven.k-int.com/content/repositories/releases/
Dál maven nenajde knihovny javax.media:jai* :
`[ERROR] Failed to execute goal on project proarc-common: Could not resolve dependencies for project cz.cas.lib.proarc:proarc-common:jar:2.0-p1: The following artifacts could not be resolved: javax.media:jai_core:jar:1.1.1_01, com.sun.media.jai.codec:jai_codec:jar:1.3.1_03: Could not find artifact javax.media:jai_core:jar:1.1.1_01 in proarc.repository (http://mvnrepo.archivacni-system.googlecode.com/git)`

V pom.xml jsou uvedené repozitáře z google code, které jsou už přesunuté na github. To asi nevadí (repozitáře na google code zdá se zatím fungují).

**Comment by pokorsky** [comment]
Aktuální vývoj verze 2.1 probíhal nyní na branch cejsh, kde je plně aktualizovaný POM po přechodu na GitHub. Branch master bude aktualizována v rámci vydání příští týden.

Pouze závislosti na JAI je nutné instalovat ručně (`mvn install:install-file`) z důvodu licence. JARy jsou součástí instalačního WAR.
