### ISSUE TITLE
Import, Nová dávka - upozornění při načítání dávek do fronty

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#370]
Když po spuštění načítání dávky dám Pokračovat a chci poslat do fronty další dávku, vyhodí to "Upozornění" s hláškou v AJ "The import batch is still loading!" - asi by to mělo být česky.

**Comment by pokorsky** [comment]
Moje chyba. Tohle vzniklo opravou issue #260. Ta hláška se objeví opravdu jen v případě zavření okna s progresem, pokud dávka stále běží. Upozornění stačí zavřít. Import v každém případě běží dál.

**Comment by pokorsky** [comment]
Opraveno, varování se nezobrazuje.
