### ISSUE TITLE
RDF: UI specifikace

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#372]
Popsat UI workflow (záměry, úkoly, materiály, parametry, ... ) v [dokumentu](https://docs.google.com/presentation/d/1vTVu13VENd6HvuIqlHNOWiwIssI0-zmM0YiM9GIJbqI/edit?usp=sharing) podle issue #350.

**Comment by luckajirku** [comment]
Proč se nebude zavádět stav úkolu Čeká na opravu? Jaká je idea u úkolů, které váznou na opravě - že zůstane stav Probíhá a napíše se to dočasně do poznámky? Ono by bylo šikovné, kdyby tam ten stav byl přímo a věci k opravě šly vyfiltrovat...

**Comment by luckajirku** [comment]
2. Nejsem si úplně jistá, jak s některými typy prací vzhledem k vazbě záměru na předlohu. U monografií, kde předloha=titul to bude bez problémů, ale u periodik... Jsou tam práce, které se vztahují k titulu, ne jen ke konkrétní předloze. Třeba exporty, importy nebudu dělat po předlohách, ale až bude titul komplet. A je jich víc takových.  
Půjdou nějaké práce udělat nad celou skupinou záměrů nebo je to vždycky jen pro 1 záměr? Typicky import do Krameria...
V KNAV budou exporty, archivace atp. opravdu probíhat na předloze? 
Tyhle práce se vztahují (některé úplně a některé je tak prostě výhodnější dělat) k titulu:
Rekatalogizace 
Číslo ČNB
(URN:NBN)
Export do NDK
Validace
Import do Krameria
Aktualizace bib.záznamu v Alephu (856+911)
Aktualizace v SK

**Comment by luckajirku** [comment]
U čeho přesně se použije stav Zrušen? Resp. jaký stav se použije u úkolů, které se u některých předloh dělat nebudou (a je to tak OK), použiju taky Zrušen? Nebo budu muset mít x profilů udělaných tak, aby tam vždycky všechny ty procesy byly?

**Comment by luckajirku** [comment]
Můžu do jakéhokoli následujícího úkolu dopsat poznámku, i když není ještě na řadě? Třeba při přípravě dokumentu instrukce pro skenování nebo popis (parametry nestačí), nebo při kontrole instrukce pro následné opravy?

**Comment by luckajirku** [comment]
U Úkolu je, že "Priorita se bere z Jobu a je RO". Nechápu pak, proč je přímo v úkolu. Dávalo by smysl, aby byla uvedená někde v hlavičce záměru. Nebo pokud má být na úrovni Názvu/Pracovníka/Stavu, co patří k úkolu, pak bych to aspoň přejmenovala na Priorita záměru, aby to nebylo matoucí. Na druhou stranu by možná bylo šikovné, kdyby se nejdřív převzala z jobu, ale dala by se případně u jednotlivých úkolů upravit. Ale tak to asi nejdřív bylo a pak se to zavrhlo?

**Comment by pavelkocourek** [comment]
Probereme to na pondělní schůzce

**Comment by lucka-pavlova** [comment]
Stav úkolu "Čeká na opravu" zatím není v Demu, ale výhledově s ním počítáme. Z hlediska logiky procházení úkolů je shodný se stavem "Čeká na předchozí", ale pro přehlednost je lepší mít ho samostatně.

**Comment by lucka-pavlova** [comment]
Vazba záměru na předlohu je jednou z možností, které se snažíme zprovoznit nejdřív, protože je to asi nejčastější scénář. Z hlediska datové struktury a logiky aplikace je pro záměr potřeba, aby měl nějaký "Předmět zpracování" a úkoly, které se ho týkají. Není nutné, aby to byla zrovna předloha, může to být třeba Dig.dokument a podmnožina úkolů kolem něj.
MOhla byste stručně popsat scénáře, které u Vás můou nastat. Stačí jeden odstavec, já bych je pak zkusila zapsat do RDFlow, abychom vyzkoušeli jestli se tam vejdou.

**Comment by lucka-pavlova** [comment]
Stav "Zrušen" bude použit pro Záměry a úkoly, které se záměrně dělat nebudou.

**Comment by lucka-pavlova** [comment]
Vynechání úkolu pro konkrétní záměr oproti profilu. Profil slouží jako šablona úkolů, které se mají založit ke konkrétnímu záměru. Je to spíš zjednodušení, abyste nemuseli zadávat ručně pro každý záměr stejnou sadu úkolů. Ve chvíli, kdy je záměr vytvořený, už existuje nezávisle a úkoly v něm jde samostatně editovat. Tj. některé označit jako zrušené, přidat poznámku, změnit parametry apod. 
Nový profil má smysl vytvářet pokud danou sadu úkolů používáte často.

**Comment by lucka-pavlova** [comment]
Priorita zpracování je u záměru, protože předpokládám, že spěchá celé zpracování daného dokumentu ne jen dílčího úkolu. Do Úkolů je vytažená, aby bylo možné podle ní filtrovat a třídit, např.  pro operátory, kteří si můžou zobrazit svoje úkoly a dát si je seřadit podle priority. Určitě by měla být jako sloupec v tabulce úkolů, ve formuláři je spíš pro info, v lavičce záměru by mohla zapadnout, tak je samostatně, ale není to podmínka.

**Comment by luckajirku** [comment]
ad Priorita - takhle jak je to tam uvedené jen jako "Priorita", je to matoucí - uživatel má dojem, že jde o prioritu pouze konkrétního úkolu (testováno na lidech:-)). Filtrování by se hodilo, ale právě i tak, že půjdou vyfiltrovat  konkrétní úkoly, které spěchají. Předpoklad, že vždy spěchá zpracování celého dokumentu, neodpovídá úplně praxi. Ano, rámcově víme, který dokument je třeba zpracovat hned, a co může počkat. Ale pak je taky někdy potřeba změnit prioritu u jednotlivých úkolů - typicky jde třeba o opravy. Nebo příklad - mám záměr s nižší prioritou, mám naskenováno, popsáno, po předloze se začne shánět čtenář. Chci urychlit kontrolu a opravy, ke kterým potřebuju předlohu, takže zvýším prioritu u úkolů, ke kterým tu předlohu ještě potřebuju, a udělá se to přednostně, aby se mohla vrátit. Na následující úkoly (exporty, validace, importy...) už ale není třeba spěchat, takže tam zas může zůstat původní priorita ze záměru.

**Comment by luckajirku** [comment]
Stav "Zrušen" - ono to evokuje spíš stav, kdy se s úkolem začne a pak z nějakého důvodu se nedokončí a nakonec dělat nebude. Ale ok, díky za vysvětlení.

**Comment by lucka-pavlova** [comment]
ad Priorita: , Aha, tenhle scénář mě napadl. Pak má určitě smysl mít možnost zvednout prioritu jednotlivého úkolu.
ad "Zrušen" - Možná by stačilo lepší pojmenování.

**Comment by luckajirku** [comment]
Další dotaz:-). K čemu slouží ty materiály v úkolu, jak se využijí? Myslím jak je využije uživatel-pracovník při plnění úkolu, ne systém.

**Comment by luckajirku** [comment]
Správa záměrů, Správa úkolů - "Typ úkolu" bych nechala jen jako Úkol (pod typem úkolu jako normální uživatel nečekám název, ale "lehký", "těžký":-))

Ve správě úkolů je "Pracovník", ve správě záměrů pak u úkolu "Kdo" - sjednotila bych to na pracovníka. (Nebo můžeme předělat i typ úkolu a stav a mít tam jen výstižné "Co", "Kdo" a "Jak")

**Comment by luckajirku** [comment]
Bylo by možné mít u některých parametrů (napadá mě Barevnost u Skenování, ale třeba by se to hodilo i jinde) na výběr hodnoty v comboboxu nebo bude nutné to vždy vypisovat? 
Že by v profilu byl přednastavený jen název parametru, hodnota by zůstala prázdná, protože se vybírá pro konkrétní záměr až během procesu.
Hodnoty pro Barevnost by pak byly např.: 
- barevně
- v šedi
- desky barevně, zbytek v šedi 
- desky a mapy barevně, zbytek v šedi
- rozhodnout podle testovacích skenů 
- komplikované (viz pozn.)
atp.

**Comment by pokorsky** [comment]
> Bylo by možné mít u některých parametrů (napadá mě Barevnost u Skenování, ale třeba by se to hodilo i jinde) na výběr hodnoty v comboboxu nebo bude nutné to vždy vypisovat?

Ano bude to možné pomocí definice valueMap v XML profilu workflow.

> Správa záměrů, Správa úkolů - "Typ úkolu" bych nechala jen jako Úkol ...

Zatím nerozhodnuto.

> K čemu slouží ty materiály v úkolu, jak se využijí? Myslím jak je využije uživatel-pracovník při plnění úkolu, ne systém.

Tohle by měla @lucka-pavlova dopsat do dokumentace. Vysvětlení pojmů záměr, úkol a materiál, pokud to tam ještě není.

**Comment by lucka-pavlova** [comment]
komplexně je vyřešeno, samostatné úpravy budeme zadávat jako samostatné issue
