### ISSUE TITLE
RDflow: Pravidla pro sestavení "Vizitky záměru"

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#373]
Pravidla pro sestavení Job.Label.

**Comment by pavelkocourek** [comment]
Typ dokumentu se rozlišuje podle pole FMT

Periodikum (FMT=SE)
- hlavní název : podnázev
- upřesnění dopsané zpracovatelem

Monografie (FMT=BK)
- hlavní název : podnázev, Autor???, rok vydání

Hudebniny (FMT=???) - doplní MKP
- hlavní název : podnázev, ???

**Comment by luckajirku** [comment]
"upřesnění dopsané zpracovatelem" bude i u monografií. Jak u periodik, tak u monografií bude třeba mj. do vizitky dopsat signaturu zpracovávané předlohy (podle signatury se hledá na regále, název atd. většinou na hřbetu ani není).
Signaturu by taky bylo dobré přidat i do materiálu/předloha.

**Comment by pokorsky** [comment]
FMT je nestandardní MARC pole. Lze se na to spoléhat?

@pavelkocourek co znamená "upřesnění dopsané zpracovatelem"?

**Comment by nezbedova** [comment]
V DC KNAV momentálně žádné vylepšení vizitky nepotřebujeme. Informace získáváme z Materiálu Bibliografický záznam.
