### ISSUE TITLE
RDF: Implementace XML modelu workflow

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#374]
Implementace profilů podle issue #368.

**Comment by pokorsky** [comment]
Návrh [schema](https://gist.github.com/pokorsky/0d1caf687a1268d19db7).

**Comment by lucka-pavlova** [comment]
Prosím přidej do schématu task/blocker a task@refName Díky!

**Comment by lucka-pavlova** [comment]
Demo [XML definice] (https://gist.github.com/lucka-pavlova/8c0ea7629d970b11c969)

**Comment by lucka-pavlova** [comment]
Do schematu a XML definice přidat k elementu  step atribut optional (boolean), který bude sloužit k "Přidat krok".

**Comment by lucka-pavlova** [comment]
Oprava [RDFlow – XML](https://docs.google.com/spreadsheets/d/1NkueAFCCwIL109-wxAAupcGmRYHNNcfntWOycBlHcbc/edit#gid=0)  pomocí komentářů a následného nahrazení.
Task name přeložit do angličtiny
Opravit překlepy.

**Comment by luckajirku** [comment]
Společně s MKP jsme přeložili/upravili naše práce, v dokumentu je to vše v komentářích (jak návrhy na změnu, tak OK tam, kde to může zůstat jak je). Jsou úpravy jak v task name, tak někde i v českém názvu (to Lucko prosím taky uprav, díky).

Kde není žádný komentář, jde o práce KNAV, ty je potřeba ještě upravit.

**Comment by lucka-pavlova** [comment]
Opravila jsem všechno podle komentářů, až na jeden imageEditing, prosím koukněte na to. Díky!

**Comment by lucka-pavlova** [comment]
Aktualizovala jsem [XML definici] (https://gist.github.com/lucka-pavlova/8c0ea7629d970b11c969)

**Comment by lucka-pavlova** [comment]
Pokud budete mít čas a náladu doplňte prosím českou nápovědu, anglický název a anglickou nápovědu. Text je možné upravovat přímo v buňce. Oblast jsem podbarvila zeleně. Díky!

**Comment by pokorsky** [comment]
Přidán typ hodnoty parametru `param@type`.

```xsd
    <xs:attribute name="type" type="tns:valueTypeDefinition" default="STRING"/>

    <xs:simpleType name="valueTypeDefinition">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DATETIME"/>
            <xs:enumeration value="NUMBER"/>
            <xs:enumeration value="STRING"/>
        </xs:restriction>
    </xs:simpleType>
```

**Comment by pokorsky** [comment]
Přidán typ pro prezentaci hodnoty parametru v UI  `param@displayType`.

```xsd
    <xs:simpleType name="displayTypeDefinition">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CHECKBOX"/>
            <xs:enumeration value="COMBOBOX"/>
            <xs:enumeration value="DATETIME"/>
            <xs:enumeration value="SELECT"/>
            <xs:enumeration value="TEXT"/>
            <xs:enumeration value="TEXTAREA"/>
        </xs:restriction>
    </xs:simpleType>
```
