### ISSUE TITLE
RDF: Definice algoritmu procházení úkolů

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#375]
Podle jakého klíče bude sestavena posloupnost úkolů a jak budou postupně zpouštěny ke zpracování. Jak zaznamenáme závislosti a opravy.

**Comment by lucka-pavlova** [comment]
Vzájemné závislosti úkolů (stepů) na sobě jsou definovány v xml definici profilu pomocí elementu job/step/blocker. Element blocker je v rámci stepu opakovatelný, tj. jeden úkol může být závislý na několika předchozích. Kontrola závislostí probíhá vždy v rámci jednoho Záměru. 
Pro každý úkol je pravidelně přepočítáván stav. Pokud je jeho blocker v "nedokončeném" stavu  (tj. čeká, připraveno, probíhá), pak je úkol ve stavu "Čeká". 
Ve chvíli kdy jsou všechyny blockery daného úkolu "dokončené" (resp. nejsou v záměru založené), změní se stav úkolu na "Připraven".

**Comment by lucka-pavlova** [comment]
Je potřeba domluvit chování, ve chvíli, kdy je stav blockeru "Zrušen". Myslim, že by měl blokovat dál, protože po zrušeném skenování není jak upravovat skeny apod.

**Comment by lucka-pavlova** [comment]
Ve chvíli, kdy je stav úkolu "Dokončen" už se jeho stav dále nemění. I když se vrámci záměru jako oprava objeví úkol, který je uveden mezi blockery.

**Comment by pokorsky** [comment]
Definuj prosím ještě závislost na stav záměru. Když jsou všechny úkoly hotové nebo zrušené, tak se záměr asi může automaticky zavřít jako `Hotový`. Co když uživatel označí záměr jako `Hotový/Zrušený`. Mají se označit i neuzavřené úkoly? Jak?

Boudou se kontrolovat vyplněné parametry nebo materiály?

Budou se nějak omezovat úpravy uzavřených úkolů nebo záměrů?

**Comment by lucka-pavlova** [comment]
**Když je stav záměru změněn na Zrušen:**
pak je u jeho "nedokončených" úkolů také změněn stav na Zrušen.

**Comment by lucka-pavlova** [comment]
**Navrhuju, aby stav úkolu "Dokončen" byl konečný a nešel změnit**, protože spouští změnu stavu návazných úkolů. Pokud bude potřeba oprava dané práce, bude založen další úkol.

**Comment by lucka-pavlova** [comment]
Já myslím, že když jsou v záměru pouze úkoly ve stavu "Dokončen", může být záměr označen jako "Hotový". Ale to je spíš otázka na @luckajirku a @nezbedova

**Comment by lucka-pavlova** [comment]
V XML definici uvádíme u parametrů také, jestli je povinný **task/param@required**, takže bysme hohli kontrolovat při změně stavu úkolu na "Dokončen", že povinné parametry jsou vyplněné.

**Comment by lucka-pavlova** [comment]
Po přidání "optional" kroku do Záměru by měly být přečítány stavy ostatních kroků  a ty, které mají nový krok jako blocker, by měli být dány do stavu "čeká"(ze stavu připraven nebo probíhá)

**Comment by pokorsky** [comment]
@lucka-pavlova: Přidání nového kroku bylo definováno v issue #387. Pokud se to má chovat jinak, tak na to prosím založ samostatné issue.

Navrhuji toto issue po doplnění dokumentace uzavřít. Na čem byla shoda, tak je implementováno. Nezavřel jsem to dřív jen proto, že je to označeno jako dokumentace a přiřazeno na tebe.

**Comment by lucka-pavlova** [comment]
Je popsáno v rámci [dokumentace workflow.xml] (https://docs.google.com/document/d/1EXj8NssLLufGGqRrs3xEcHuWBOmh7aByMVSVph8dK6E/edit#)
