### ISSUE TITLE
Validace - uvedení počtu objektů za "Vše v pořádku"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#376]
Při validaci (ať už v Import - příprava metadat nebo v Editoru připojených objektů) se ukazuje v průběhu stav, kolik už je zkontrolováno (20/50), v případě nevalidních se ukáže počet i na konci. Nemohl by se ten počet na konci ukázat i v případě, že je vše ok, za hláškou Vše v pořádku?

**Comment by pokorsky** [comment]
Přidáno.
