### ISSUE TITLE
Souběžné registrace URN:NBN - možnost volby registrátora přímo v UI

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#378]
Potřebovali bychom mít možnost souběžných registrací URN:NBN pro různé registrátory přímo v UI, bez nutnosti měnit proarc.cfg vždy ve chvíli, kdy je třeba registrovat pro jinou knihovnu.

**Comment by SykoraLukas** [comment]
Upraveno pro možnost výběru z více registrátorů.

Po najetí na požadovaný model a kliknutí na tlačítko URN:NBN se objeví okno, tak jako dosud. V tomto okně nově přibyla možnost zvolit resolver, ve kterém se vybraný objekt bude regostrovat.

![image](https://user-images.githubusercontent.com/27210823/68518706-6e284a80-028d-11ea-8118-5c428e5ce834.png)

Aby se přidali další registrátoři do tohoto seznamu, je nutné přidat v konfiguračním souboru do pole  'urnnbn.resolvers' další položky, tak jako to funguje u katalogů (ukázka konfigurace [zde](https://github.com/proarc/proarc/wiki/Konfigurace#urnnbn))

**Comment by luckajirku** [comment]
Testoval tohle někdo v reálu? @nezbedova ? My teď zrovna děláme jen naše věci, takže to neotestujeme.

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
