### ISSUE TITLE
RDF: Vzorové případy zpracování jednotl. druhů dokumentů (KNAV)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#381]
Připravit vzorové případy zpracování jednotlivých druhů dokumentů za KNAV.

**Comment by nezbedova** [comment]
Podle původní domluvy jsem to poslala e-mailem 23.10. Přidávám to i sem.
Monografie

1)Vypůjčím si monografii, odešlu ji do RD a předám ji na skenování. Během skenování se zjistí, že jsou některé strany nerozřezané. Kniha se odešle do vazárny na rozřezání. Po jejím vrácení se pokračuje ve skenování. Po naskenování se zpracovává v Bookrestoreru, následně se přidá OCR a popisná metadata v ProArcu. Nakonec se zveřejní v K4.

2) U jedné monografie se skenuje obálka a obrázky v barvě a ostatní v šedi.

3) K monografie, která se skenuje na Treventusu se dodělávaji desky, přídeští a předsádka na Zeutchelu (se stejnými parametry).

4) Celá monografie je naskenovaná a zpracovaná v Bookrestoreru. Při tvorbě popisných metadat v ProArcu zjistím, že chybí strany. Popis dokončím do fáze připojení k nadřazenému objektu. Monografii vrátím k doskenování. Následně  se zpracuje v Bookrestoreru. V ProArcu připojím strany, kam patří. Celé exportuji a posílám do K4.

**Comment by lucka-pavlova** [comment]
1)	Nemáte uvedený typ práce  “Příprava”. Má být součástí profilu?
2)	Počítám, že přidám typ práce “Rozvázání předlohy”, jako volitelný krok. Mám přidat i “Svázání předlohy”? Budete to chtít evidovat?
3)	Napadlo mě, že bychom mohli rozdělit Skenování na “Skenování knižního bloku” a “Skenování obálky atd.”, které by pak mohly mít v parametrech různé skenery a případně i jiné parametry. A vystupovali by jako samostatné kroky, které by případně mohl dělat i jiný pracovník.

**Comment by nezbedova** [comment]
Toto jsme vyřešily e-mailem. Přípravu nepotřebujeme. A skenování je již rozděleno.

**Comment by pokorsky** [comment]
@nezbedova: Je tedy nějaký důvod proč issue necháváte otevřené?
