### ISSUE TITLE
Mezery v zobrazení Informace o titulu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#382]
Nový objekt - zobrazení "Informace o titulu" 
U názvů elementů/atributů je mezera za levou závorkou místo před ní: Jméno: Personal( usage...), Form( marcform), Předmět( czenas)... 
A pak je zvláštně mezera za levými uvozovkami - usage=" primary", encoding=" marc"
Pokud to není schválně, tak to vypadá divně (teda vypadá to divně tak jako tak:-)).

**Comment by krizovj** [comment]
Tím myslíš tyhle mezery? 
![image](https://user-images.githubusercontent.com/21309201/55145099-670b5c80-5142-11e9-8431-47b14c43ffd1.png)

**Comment by luckajirku** [comment]
jj

**Comment by SykoraLukas** [comment]
Opraveno, omylem puhnuto do #381

**Comment by nezbedova** [comment]
Opraveno. Mezery nejsou. Navrhuji zavřít.

![obrazek](https://user-images.githubusercontent.com/13831946/96676693-3a471780-136e-11eb-87d4-337a8d1c8ce2.png)

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
