### ISSUE TITLE
RDflow:UI Form Záměr Tab. úkolů - možnost editace pole pracovník přímo v tabulce

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#383]

**Comment by lucka-pavlova** [comment]
#371

**Comment by nezbedova** [comment]
Nevím, zda to potřebuje někdo jiný. U nás došlo postupem času ke změnám, kdy pole Pracovník v úkolech nepotřebujeme editovat. Pracujeme s roletkou Uživatelé.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
