### ISSUE TITLE
RDflow:UI “Rostoucí” poznámka

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#386]
Formulář Záměr pole Poznámka bude mít rostoucí velikost v závislosti na obsahu.

**Comment by pokorsky** [comment]
Poznámka musí mít momentálně fixní velikost kvůli chybě ve SmartGWT 4.0.

**Comment by pavelkocourek** [comment]
Přesunuto : RDflow:UI “Rostoucí” poznámka (#386) #31
