### ISSUE TITLE
RDF: Přidání kroku do existujícího záměru

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#387]
Do existujícího záměru bude možno přidat jednotlivé kroky. 
Ve formuláři Záměr nad tabulkou Kroků se bude v kontextovém menu (pravé tlačítko myši) nabízet položka "Přidat krok", která se dál rozbalí do seznamu "typů práce" použitelných pro daný profil.
Nabídka bude sestavena ze všech typů práce použitých v profilu (včetně "skrytých").
Pro "skryté stepy" přibude do XML definice step atribut "optional=true/false". Takto označené stepy nebudou založeny automaticky s profilem, ale budou se nabízet v seznamu pro přidání.

**Comment by lucka-pavlova** [comment]
Sepsat možnosti oprav a jak je řešit

**Comment by luckajirku** [comment]
ad sepsání možností oprav - naše jsou (zatím jen rozpracované) tady https://docs.google.com/document/d/1RYpoA6H2o0wlHQZf8eSzhw2ci7CsXhcsPWTZXT8rg4Y/edit

**Comment by pokorsky** [comment]
Úkol lze přidat pomocí kontextového menu.
