### ISSUE TITLE
RDflow: Statistiky

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#390]
Z RDFlow bude možno exportovat statistiky:
Přehled prací dle dokumentu
Přehled prací  dle pracovníka za období
Statistika počtu dokumentů v jednotlivých fázích zpracování
Statistika práce podle pracovníka a období

**Comment by pavelkocourek** [comment]
Hlavní menu > Statistiky 
Uživatel dostane dialog pro zadání parametrů
Výstup se uloží jako csv do adresáře Exports
Připravit Select do DB a ten následně parametrizovat [LP]
UUID / Pracovník / Rozmezí / Fáze zpracování

**Comment by lucka-pavlova** [comment]
1. verze Statistiky práce podle pracovníka a období, zatím bez lokalizace:
*select t.owner_id,t.type_ref ,p.param_ref, COUNT(t.id) as pocetUkolu, SUM(p.value_number) as soucetHodnot from proarc_wf_task t left outer join proarc_wf_parameter p on t.id = p.task_id
where p.value_number is not null and t.state = 'FINISHED' and t.timestamp > '2015-01-01' and t.timestamp < '2015-12-31'
group by t.owner_id,t.type_ref ,p.param_ref;*

**Comment by lucka-pavlova** [comment]
Popis [Statistiky práce podle pracovníka a období] (https://docs.google.com/document/d/1N3BWAhQ_6JzDhqbMOnR-tjuuRDh4a5RgBSmOI3KZSF4/edit#) bude na GDocs.

**Comment by lucka-pavlova** [comment]
Popis [Statistiky počtu úkolů a počtu souborů podle skeneru za období](https://docs.google.com/document/d/1QsMPaRx-SPb30SydlhpMKfkGm8dg8sCd1GhpUvL-GOs/edit#) bude popsána na GDocs

**Comment by lucka-pavlova** [comment]
Popis [Statistiky podletypu úkolu a stavu] (https://docs.google.com/document/d/1NL8OloJoXYIP5PChRTfA2HdFlPp7kvR1W66cxWo-p4A/edit#heading=h.r510komponkf) bude popsána na GDocs.

**Comment by nezbedova** [comment]
Za Digitalizační centrum nám vyhovuje to, co bylo naplánováno na začátku. Tedy:
Přehled prací dle dokumentu
Přehled prací dle pracovníka za období
Statistika počtu dokumentů v jednotlivých fázích zpracování
Statistika práce podle pracovníka a období

**Comment by pavelkocourek** [comment]
@MartinRumanek  ověř prosím, jestli splňuje

**Comment by pavelkocourek** [comment]
Uzavírám z KNAV (ML,MN) ... pokud během testování bude další požadavek, navážeme na toto Issue.
