### ISSUE TITLE
RDF:UI Form Záměr Tab. úkolů - otevření detailu úkolu

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#391]
Detail úkolu bude otevřen dvojklikem na řádku daného úkolu nebo pomocí kontextového menu.

**Comment by pokorsky** [comment]
Úkol lze otevřít dvojklikem, enterem a z kontextového menu. Pokud úkol není načten v rámci pravé tabulky úkolů, tak se zobrazí jen v pravých formulářích.
