### ISSUE TITLE
Při aktualizaci metadat přes fci Katalog se nezachová URN:NBN

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#392]
Při aktualizaci metadat přes funkci Katalog hlásí systém při pokusu o přepis: "... Přidělené URN:NBN nelze odstranit! ... Chcete přesto pokračovat?" Po překonání hlášky však urn:nbn z MODS zmizí, i když by se podle #299 i podle textu hlášky mělo zachovat.

**Comment by pokorsky** [comment]
Umazání URN:NBN je chyba. Upravil bych ještě tu zavádějící hlášku z `Přidělené URN:NBN nelze odstranit!` na `Přidělené URN:NBN nebude odstraněno!`. Znamená to, že jednou uložené URN:NBN nepůjde smazat ani přepsat, pouze zneplatnit.
