### ISSUE TITLE
prazdny export NDK

### ISSUE THREAD

**Issue by psenickam** [proarc/proarc#393]
Pri exportu pro NDK vznikne pouze prazdny adresar s logem ze vse probehlo v poradku. Export probehne behem par vterin, ale bez dat.

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<exports xmlns="http://proarc.lib.cas.cz/xml/common/export/v1/">
    <export>
        <begin>2015-11-12T11:06:28.827+01:00</begin>
        <end>2015-11-12T11:06:45.787+01:00</end>
        <status>OK</status>
        <inputPid>uuid:000242ad-ed42-43a5-be78-377476b0ca3c</inputPid>
    </export>
</exports>

**Comment by pokorsky** [comment]
Protože ten ročník  neobsahuje nic co by šlo zabalit jako NDK PSP.

**Comment by psenickam** [comment]
v proarcu jsou ale vsechna data. vse je zalozeno jako ndk titul periodika, ndk rocnik, ndk vytisk. jsou naimportovane soubory se stranami vcetne alto xml a txt. proc to tedy neni mozne zabalit pri exportu nako ndk psp. a jaka je pripadna naprava?

**Comment by pokorsky** [comment]
Podle toho uuid:000242ad-ed42-43a5-be78-377476b0ca3c, které jste uvedl jako vstup exportu, se jedná o ročník. Nevidím tam napojené žádné výtisky pouze stránky. Nikde není URNNBN. Tohle neodpovídá specifikaci NDK.
