### ISSUE TITLE
URN:NBN pro jiného registrátora

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#394]
Máme v ProArcu zpracované kroniky, které nejsou naše. Pro NDK export jim potřebujeme přidělit URN:NBN, ale jako registrátor by neměla být KNAV. Prosím o radu jak to máme udělat.

**Comment by pokorsky** [comment]
Nastavit podle https://github.com/proarc/proarc/wiki/Konfigurace#urnnbn po domluvě s NKP. Není nutný restart.
