### ISSUE TITLE
RDF: doplnit nápovědu k Dávka v BCS-2 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#396]
V úkolu Skenování doplnit nápovědu u povinného údaje Dávka v BCS-2.

**Comment by pokorsky** [comment]
nutno doplnit ve workflow.xml

**Comment by nezbedova** [comment]
Zjišťovala jsem, co znamená BCS-2. Pokud to je název softwaru, dodávaného ke skenerům Bookeye, tak to nemůže být povinná položka pro všechny.

**Comment by lucka-pavlova** [comment]
Ve workflow.xml je popis Dávky BCS-2 přesně podle informací v Definice XML, tj.
<param name="param.scan.BcsBatch" required="true" type="STRING" displayType="TEXT" >
            <title lang="cs">Dávka v BCS-2</title>
            <hint lang="cs">Název dávky v BCS-2</hint>
            <title lang="en">BCS-2 Batch name</title>
            <hint lang="en">BCS-2 Batch name</hint>
        </param>
Pokud je potřeba to nějak upravit, prosím změňte v Definice XML.
