### ISSUE TITLE
RDF - nesprávné úkoly v profilu Hradec - monografie 

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#397]
V profilu Hradec - monografie se automaticky založí místo našich ty původní úkoly KNAV. Raději bychom testovali na těch svých úkolech, když už jsme to poměrně detailně připravili včetně parametrů...

**Comment by nezbedova** [comment]
Tak tohle jsem právě také zjistila.
M

 V profilu Hradec - monografie se automaticky zaloĹľĂ­ mĂ­sto naĹˇich ty

**Comment by pokorsky** [comment]
Na testu je použito testovací [workflow.xml](https://gist.github.com/pokorsky/fe2688cf0e98e3374a08). Pokud se změní, tak není problém ho přidat.

**Comment by lucka-pavlova** [comment]
Aktualizovala jsem workflow.xml. Už by to mělo být ok.

**Comment by lucka-pavlova** [comment]
Opraveno.
