### ISSUE TITLE
RDF: nejde vytvořit KNAV monografie

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#398]
V RDF .Nejde vytvořit nový záměr s profilem  KNAV Monografie. Starší záznam jde editovat.

**Comment by pokorsky** [comment]
Chyba ve workflow.xml. Pokus o nastavení číselné hodnoty na prázdnou hodnotu. Např. `<setParam paramRef="param.scan.numberOfScans"></setParam>`. Je potřeba parametr buďto nenastavovat nebo tam napsat validní číslo.

**Comment by lucka-pavlova** [comment]
workflow.xml opraveno

**Comment by nezbedova** [comment]
Při pokusu o založení KNAV monografie se mi objevila hláška: "Nevalidní parametr param.scan.numberOfScans. Není číslo !"

**Comment by pokorsky** [comment]
@lucka-pavlova: Je to tedy opravené nebo ne? Přidej prosím odkaz na revizi.

**Comment by lucka-pavlova** [comment]
opraveno
