### ISSUE TITLE
RDflow: Stejná pole pro úkol skenování a skenování příloh

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#400]
V úkolech Skenování a Skenování příloh by měla být na vyplnění stejná pole na stejných místech.

A také mi vadí a zdržuje mě, že musím použít šoupátko pro zobrazení dalších údajů, které jsou dole pod poznámkou.

**Comment by pokorsky** [comment]
pole jsou uživatelsky definovatelná ve workflow.xml. Pokud je parametrů více, tak nelze zobrazit všechny najednou. Pokud máte návrh na jiné rozložení strany, tak ho prosím napište. Aktuální zobrazení bylo odsouhlaseno na schůzkách.

**Comment by nezbedova** [comment]
Nemyslím si, že by na nějaké schůzce bylo odsouhlaseno, že Skenování a Skenování obálek bude mít jiné parametry.
Navrhuji:
Změnšit Poznámku o jeden řádek.
Rozdělit pole do tří sloupců po řadách:
1.ř. Počet skenů - Skener - Datum
2ř. DPI - Barevnost - Formát

Pro KNAV nepotřebujeme "Dávka v BCS-2", takže prosím, aby Ti, kteří jej používají, napsali, kam by jej zařadili, abychom to vyladili pro všechny.

**Comment by lucka-pavlova** [comment]
Definice jednotlivých úkolů a profilů je popsána v workflow.xml, které je generováno z dokumentu [ "Definice XML"] (https://docs.google.com/spreadsheets/d/1NkueAFCCwIL109-wxAAupcGmRYHNNcfntWOycBlHcbc/edit#gid=0). Dokument je nasdílen všem ke kontrole a komentářům. České a anglické názvy jsou sdíleny i pro přímou editaci. Hradec názvy polí a změny v parametrech už udělal.  Za KNAV jsem nakonec musela jazykové ekvivalenty doplnit sama, pokud vám můj text nebude vyhovovat můžete ho změnit. Stejně je tomu i u paramtrů. Ve chvíli kdy budou provedeny změny v Definici XML, úřenesu je i na stranu serveru.

**Comment by lucka-pavlova** [comment]
Pokud se popis a parametry skenování budou pro KNAV a Hradec výrazně lišit, můžeme nadefinovat dva odlišté typy práce, které mají různé paramtry.

**Comment by luckajirku** [comment]
To bych byla pro udělat to odlišně. Ale říkalo se předtím, že ty stejné úkoly mají být jen jednou. Tak pokud to půjde, budeme samozřejmě radši. Pro nás třeba je to označení dávky v BCS nutnost, naopak jiné, které jsou důležité pro KNAV, bychom tam mít nemuseli. Nejen u skenování, ale i úprava skenů - tam třeba jsou pro nás vcelku nesmyslné ty checkboxy narovnání/otočení... apod.

**Comment by lucka-pavlova** [comment]
Samorřejmě, že je výhodnější, když stejné práce budou definovány jen jednou. Ale pokud se jejich náplň mezi organizacemi výrazně liší, nemá smysl je násilně sjednocovat. Takže jsem pro založit task, který se bude jmenovat třeba task.hradec.scan a zobrazeno bude "Skenování". Ok? @luckajirku

**Comment by nezbedova** [comment]
"pole jsou uživatelsky definovatelná ve workflow.xml. Pokud je parametrů více, tak nelze zobrazit všechny najednou. Pokud máte návrh na jiné rozložení strany, tak ho prosím napište. Aktuální zobrazení bylo odsouhlaseno na schůzkách."
Jenže nebylo vyřešeno issues #366. Proto to u nás nesedí.

**Comment by pokorsky** [comment]
Odsouhlaseným zobrazením jsem měl na mysli rozložení obrazovky (vlevo tabulka, vpravo formulář úkolu pod ním parametry a pod nimi materiály). Pokud budete přidávat větší počet parametrů pro daný úkol, tak logicky nepůjde všechny zobrazit najednou a nějakou část pravé strany musíme udělat šoupací.  Čím menší monitor, tím je toho samozřejmě méně vidět. Na schůzce jsem navrhoval použití záložek, ale to jsme zamítli, protože by to zdržovalo při procházení úkolů. Současné rozložení je kompromisem a vyžaduje větší monitor. V dalších verzích může být změněno podle zkušeností z praxe.

Skenování a Skenování obálek jsou uživatelsky definované úkoly ve workflow.xml. Ty nepotřebujete mít nikým schválené a můžete si je měnit dle libosti.

> Zmenšit Poznámku o jeden řádek.

To můžu, ale podle issue #386 jste chtěli poznámku co největší. Tak teď nevím.

> Rozdělit pole do tří sloupců po řadách...

To lze také. 3 sloupce pak budou platit pro parametry všech typů úkolů. Současná definice parametrů ve workflow.xml byla optimalizována na 2 sloupce. Pokud se ale shodnete, tak přidám ten 3. sloupec. Jen už nám nezbývá moc času.

**Comment by luckajirku** [comment]
Za nás je přidání 3. sloupce úplně OK. Malé monitory bych neřešila, právě na digi většinou všichni mívají dostatečně velké.  
Co se týká poznámky, tu bych nezmenšovala, pro nás je potřebná, ale tady se asi neshodneme.

**Comment by luckajirku** [comment]
ad "Skenování a Skenování obálek jsou uživatelsky definované úkoly ve workflow.xml. Ty nepotřebujete mít nikým schválené a můžete si je měnit dle libosti."
- ještě se vrátím k tomuhle. Psala jsem to včera už Lucce do mailu, ale hodím to sem. V parametrech se zřejmě lišit budeme i u těch společných úkolů. A může se stát (a stane se), že časem to bude potřeba odlišit i u dalších úkolů, které do té doby vypadaly, že budou shodné... Nevím, jestli by to něčemu vadilo, kdyby se všechny úkoly zavedly pro každou knihovnu (resp. ne pro každou, ale pro ty, co mají dost odlišné worklfow - zvlášť KNAV a my(+MKP)). Je hezké napsat, můžete měnit dle libosti, ale pokud to pak máme používat všichni, tak to tak úplně neplatí. A navíc mít něco společné, něco rozdělené, je to trochu nesystémové... Byl by to problém, kdyby tam všechny ty úkoly byly takhle zvlášť rovnou jasně - task.knav.scan... a task.hradec.scan...?

**Comment by nezbedova** [comment]
3. sloupec zpřehlední práci. Jsem doma na 15´ monitoru a se zobrazováním nemám problém.

"To můžu, ale podle issue #386 jste chtěli poznámku co největší." Ale tam není co největší poznámka, ale rostoucí. Nyní má poznámka 6 řádků. Nestačily by 4?  @luckajirku

**Comment by luckajirku** [comment]
Mám pocit, že i víc než 6. Ale zatím neroste - až poroste, může mít klidně 4.

**Comment by nezbedova** [comment]
Dobře. Nyní beze změn. Až poroste, tak jen 3 řádky, aby bylo vidět dolů.

**Comment by lucka-pavlova** [comment]
Záleží spíš na Vaší dohodě. Jestli chcete mít definice workflow úplně oddělené, z logiky aplikace je to bez problémů možné.

**Comment by pokorsky** [comment]
Přidal jsem 3. sloupec parametrů a textová pole jsem roztáhl pro každý sloupec. Výšku formuláře lze nyní měnit.

> ještě se vrátím k tomuhle. Psala jsem to včera už Lucce do mailu, ale hodím to sem. V parametrech se zřejmě lišit budeme i u těch společných úkolů. A může se stát (a stane se), že časem to bude potřeba odlišit i u dalších úkolů, které do té doby vypadaly, že budou shodné... Nevím, jestli by to něčemu vadilo, kdyby se všechny úkoly zavedly pro každou knihovnu (resp. ne pro každou, ale pro ty, co mají dost odlišné worklfow - zvlášť KNAV a my(+MKP)). Je hezké napsat, můžete měnit dle libosti, ale pokud to pak máme používat všichni, tak to tak úplně neplatí. A navíc mít něco společné, něco rozdělené, je to trochu nesystémové... Byl by to problém, kdyby tam všechny ty úkoly byly takhle zvlášť rovnou jasně - task.knav.scan... a task.hradec.scan...?

Pak to nejsou společné úkoly a měly by být definovány samostatně. Základní instalace obsahuje prázdné workflow.xml bez úkolů a záměrů. Je na každém, aby si obsah workflow definoval. @lucka-pavlova připravuje ukázkové workflow, od kterého se každá instalace může libovolně odchýlit. Nemusí z něj použít třeba vůbec nic. Na druhou stranu je rozumné z tohoto workflow alespoň vycházet.

Jelikož máme jen jeden testovací server, tak workflow obsahuje jakýsi kompromis. V produkčním nasazení asi není pro identifikátory typu `task.knav.*` důvod. Parametry lze ubrat nebo přidat bez ovlivnění ostatních institucí.

**Comment by nezbedova** [comment]
"Výšku formuláře lze nyní měnit." 
To byl výborný nápad. Dokonce to i po posunutí drží tvar při přepínání. Takže teď je jedno, jak velká je poznámka.

**Comment by nezbedova** [comment]
Pole parametrů pro jednotlivé úkoly se zadávají v xml. Lze je přizpůsobovat jednotlivým knihovnám. Řadí se za sebou. Nelze vynechat pozici vlevo nahoře a začínat až vpravo.
