### ISSUE TITLE
RDF: neočekávaná chyba při editaci materiálů hotového/zrušeného záměru

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#401]
Při snaze o editaci materiálů hotového nebo zrušeného záměru vyhodí systém pro uživatele nesrozumitelnou hlášku Neočekávaná chyba.

**Comment by pokorsky** [comment]
O který záměr se jedná? ID nebo alespoň název?

**Comment by luckajirku** [comment]
Řekla bych, že se jedná o všechny, kde změníš stav záměru na hotový nebo zrušený, co jsem tak zkoušela. Třeba ID 27. Když chci editovat Fyzickou jednotku, dopsat třeba BC apod., při snaze o uložení to vyhodí neočekávanou chybu. Chtělo by to odpovídající hlášku.

**Comment by pokorsky** [comment]
Problém je v tom, že záměr 27 je zavřený. Pro zavřené záměry nelze ukládat změny materiálů, úkolů ani parametrů. Hláška v popisu chyby je zatím bohužel anglicky a není ve formě validace.

**Comment by luckajirku** [comment]
Že je to u zavřených (hotových/zrušených) záměrů píšu od začátku:-). A je mi jasné, že je to tak v pořádku, že to nejde editovat. Jde mi o změnu té hlášky - aby to místo neočekávané chyby vyhodilo hlášku ve smyslu, že to nelze editovat, protože je záměr ve stavu hotový/zrušený.

**Comment by nezbedova** [comment]
Také preferuji češtinu, ale doplněná hláška v aj stačí.

**Comment by pokorsky** [comment]
Přidána lokalizace a přehlednější hláška.
