### ISSUE TITLE
RDflow: Změna priority během práce

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#402]
Hodilo by se nám, kdyby po změně priority během trvání záměru se tato priorita promítla do všech nehotových úkolů.

**Comment by nezbedova** [comment]
Vyřešeno jiným způsobem práce. Toto už není potřeba. Zavírám.

**Comment by nezbedova** [comment]
Nepoužíváme zobrazení jednotlivých úkolů. Sledujeme jen záměry.

**Comment by nezbedova** [comment]
V KNAV vyřešeno jiným způsobem. Pokud potřebujeme něco upřednostnit, změníme Prioritu ve vizitce. Po přidání (odkrytí) sloupce ve Správě záměrů lze vyfiltrovat záměry podle pole Priorita.

**Comment by ZdenkaSera** [comment]
Vzhledem ke komentáři @nezbedova zavírám.
