### ISSUE TITLE
RDF: sloupec Profil v úkolu zobrazuje místo profilu task name

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#403]
Když přidám v úkolech sloupec Profil, zobrazí se tam místo profilu task name.

**Comment by pokorsky** [comment]
To je správně. Název profilu je ve sloupci úkol.

**Comment by luckajirku** [comment]
V tom případě by asi nebylo od věci popřemýšlet nad lepším pojmenováním. Stejně tak jako Profil v materiálu. Takhle je tam 3x Profil a pokaždé znamená něco jiného... Z pohledu programátora asi OK, ale pro normálního uživatele to bude matoucí.

**Comment by pokorsky** [comment]
V tabulce záměrů je jediný sloupec obsahující slovo `profil` ve svém názvu. Prosím o neprogramátorský návrh změny názvu sloupce `Profil`. Je potřeba, aby byl název co nejkratší. V případě potřeby lze přidat ke sloupci nápovědu do bubliny.

V tabulce materiálů navrhuji změnit sloupec `Profil` na `Materiál`.

**Comment by lucka-pavlova** [comment]
Navrhuju přejmenovat sloupec Profil, který obsahuje "task name" na "Sysname úkolu".

**Comment by luckajirku** [comment]
Já bych tam nechala klidně taskname, ale hlavně nechápu tam moc jeho smysl, k čemu by ho uživatel mohl použít. Pro něj je snad název ve sloupci Úkol. Každopádně bych ten sloupec skryla.
O tom Materiálu jsme se bavili už na schůzce, ale pořád lepší Materiál (na který si asi uživatel zvykne) než ten zavádějící Profil.

**Comment by pokorsky** [comment]
`Sysname úkolu` určitě ne.
`taskname` bych bral, ale to bude zase svádět k zadávání chyb na lokalizaci.
Ano, lidský název úkolu je ve sloupci Úkol. Taskname je identifikátor profilu úkolu ve workflow.xml, který je editovatelný uživatelem a protože taskname je jediný povinný a jedinečný údaj, který nelze měnit, tak je potřeba jej zobrazit, aby v případě nějaké uživatelské chyby šlo jednoznačně identifikovat problém podle workflow.xml. Ve výchozím stavu je sloupec **skrytý**.

**Comment by nezbedova** [comment]
Jmenovaný sloupec mám skrytý. Jako název mne napadá jen "id.xml" s bublinou "Identifikátor profilu úkolu ve workflow.xml".

**Comment by luckajirku** [comment]
OK, s tím skrytím jsem si neuvědomila, že tam máme tu novinku s pamatováním nastavení sloupců.

**Comment by pokorsky** [comment]
`XML ID` se mi líbí. Krátké a jasné.

**Comment by pokorsky** [comment]
Názvy upraveny na XML ID a Materiál.
