### ISSUE TITLE
založení nového objektu s již existujícím uuid

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#404]
Když v ProArcu v úložišti chci založit nový objekt (NDK Periodikum) s již existujícím uuid a stáhnout si data z katalogu, tak se mi před PID ukáže vykřičník a napíše hlášku "Object already exists!", která nejde překonat.
Pokud zakládám pouze objekt s již existujícím uuid, bez stažení metadat z katalogu, tak to normálně funguje.
Tahle chyba se mi děje pouze v instalaci proarc-ozc, ve zkušebním proarcu to normálně funguje.

Máme někde něco špatně nastaveného u té konkrétní instalace?

**Comment by pokorsky** [comment]
To je vlastnost. Smazané objekty nelze znovu zakládat se stejným uuid. Je to z důvodu ochrany, kdyby někdo omylem smazal existující hierarchii objektů, aby šlo data obnovit. Takový objekt je nutné odstranit přímo z úložiště nebo změnit jeho stav na Active. Obojí lze nyní udělat jen nástroji pro administraci úložiště Fedora.

**Comment by slapakovai** [comment]
Ale my jsme ten objekt (periodikum) nesmazaly. V ProArcu nikdy neexistoval. Existuje jenom v Krameriovi a chceme k němu přidat další ročníky, takže je potřeba založit titul se stejným uuid. Jak to teda máme udělat?

**Comment by pokorsky** [comment]
Bez nějaké konkrétní informace, jako je ten problematický PID, k tomu nemůžu víc napsat.

**Comment by slapakovai** [comment]
uuid:719be951-4eb0-11e1-9043-005056a60003
A chtěly jsme k tomu stáhnout záznam z našeho katalogu periodik se sysnem: 000592270

**Comment by pokorsky** [comment]
Pro uuid:719be951-4eb0-11e1-9043-005056a60003 byl založen objekt NDK periodikum uživatelem melichova dne 2015-12-11 13:52:12. Nyní je ve stavu smazáno. Objekt byl smazán 2015-12-11 14:56:09 uživatelem melichova. Není tedy pravda, že by v úložišti nikdy neexistoval.

Periodikum jsem vrátil zpět do aktivního stavu.
