### ISSUE TITLE
RDF: Filtry pro Úkoly

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#405]

**Comment by lucka-pavlova** [comment]
Navrhuju, aby se filtrování ve sloupcích Stav, Pracovník a Priorita chovalo stejně jako ve sloupci Úkol, tj. aby bylo možné pomocí checkboxů vybrat několik hodnot.

**Comment by lucka-pavlova** [comment]
@luckajirku @nezbedova

**Comment by nezbedova** [comment]
Souhlasím.

**Comment by lucka-pavlova** [comment]
Bylo by dobré zprovoznit i filtr ve sloupci "Záměr" v tabulce Úkolů.

**Comment by nezbedova** [comment]
Nevím, zda Vám dobře rozímím. Myslíte, že by i u sloupce záměr byla zaškrtávátka? S tímto filtrem procuji tak, že si záměry seskupím a pak v nich hledám. Takže nevím.

**Comment by pokorsky** [comment]
Filtry přidány.

Seskupení záměrů vypnu, protože pro větší počet úkolů by to bylo paměťově neúnosné. Textový filtr tady dává smysl.

**Comment by nezbedova** [comment]
Zapsala jsem do textového filtru Anatomia. Dobře mi to vyfiltrovalo dva záměry. Ale nemohu se z toho dostat. Smazala jsem Anatomia, dala Obnovit nad tabulkou. Stále mám jen dva záznamy. Dala jsem obnovit celou stránku a zase nic. Buďto dělám něco špatně, ale to by se mělo zapsat do návodu. Nebo je tam někde chyba.

**Comment by nezbedova** [comment]
A ty dva stejné záznamy tam jsou i po založení nového záměru a ikdyž chci hledat něco nového podle nového slova.
