### ISSUE TITLE
RDF: Kontrola povinných parametrů až při dokončení

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#406]
ProArc vyžaduje vyplněné parametry při uložení úkolu, i když je ve stavu probíhá, tj. parametry nemusejí být ještě známé, např.: počet skenů. Navrhuji, aby parametry, které jsou "required", byly povinné až pro převod úkolu do stavu Dokončen. 
Zároveň bych při "dokončení" vyžadovala vyplněné pole Pracovník.

**Comment by lucka-pavlova** [comment]
@luckajirku @nezbedova

**Comment by nezbedova** [comment]
Ano souhlasím. Je to pohodlnější něž u skenů vyplŇovat 0.

**Comment by pokorsky** [comment]
Parametry i pracovník jsou nyní povinné jen pokud je stav úkolu přepnut na Dokončen.
