### ISSUE TITLE
RDF: po filtrování podle názvu nelze obnovit celou tabulku Správa záměrů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#408]
Zapsala jsem do textového filtru Anatomia. Dobře mi to vyfiltrovalo dva záměry. Ale nemohu se z toho dostat. Smazala jsem Anatomia, dala Obnovit nad tabulkou. Stále mám jen dva záznamy. Dala jsem obnovit celou stránku a zase nic. Odhlásila jsem se a zase přihlásila. Žádná změna. Buďto dělám něco špatně, ale to by se mělo zapsat do návodu. Nebo je tam někde chyba.

**Comment by nezbedova** [comment]
A ty dva stejné záznamy tam jsou i po založení nového záměru a ikdyž chci hledat něco nového podle nového slova.

**Comment by pokorsky** [comment]
Textové filtry je potřeba potvrdit buďto pomocí Enter nebo kliknutím na trychtýř vlevo vedle hlaviček filtrů. Tohle je schválně, aby se tabulka nenačítala po každém napsaném písmenu.

Obnovit slouží pro znovunačtení naposled potvrzeného filtru.

**Comment by nezbedova** [comment]
Myslím si, že mám dost zkušeností s různými programy, ale tohle mne nenapadlo. Rozhodně to hned jdu připsat do uživatelské dokumentace.
