### ISSUE TITLE
RDflow:Úkol: Stav "Čeká", když "blocker" je "optional"

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#410]
Zdá se, že PrArc vyhodnotí stav stepu jako "Čeká" i ve chvíli , kdy blocker daného stepu je optional, tj. není v rámci záměru vůbec založen. Tj. Všechny stepy v záměru jsou potom ve stavu "Čeká". Blokovat by měl ale pouze "existjící nedokončený step".
Příklad: Profil KNAV Monografie

**Comment by pokorsky** [comment]
Opraveno.
