### ISSUE TITLE
Automatické vyplňování signatury a čárového kódu

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#411]
Do nově zakládaného objektu a do nově zakládaného záměru automaticky vyplňovat (stahovat) signaturu a čárový kód z registru digitalizace.

**Comment by pavelkocourek** [comment]
LS Zjistí, zdali lze údaje přenést v rámci RDFlow. Následně se rozhodne, jak bude řešeno.

**Comment by nezbedova** [comment]
@SykoraLukas Automatické vyplnění nutně potřebujeme pro zvýšení efektivity práce.

**Comment by zabak** [comment]
Není to náhodou už vyřešené?

**Comment by nezbedova** [comment]
@zabak Není to vyřešené. 

Požadavek na stažení z RD je z 7 Jan 2016, kdy se zakládaly objekty v PA z RD, protože se stáhl přesně ten záznam, který byl zdigitalizován. Myslím si, že to bylo kvůli periodikům, ale jistá si nejsem. 

Takže je třeba ho aktualizovat. 

Z Alephu se ani signatura ani č. k. nestahují do PA. Do RD se nějakým způsobem stahují. Hodně by ulehčilo práci, pokud by se stahovaly tyto údaje i do PA a nemusely se zapisovat ručně.

**Comment by nezbedova** [comment]
Doplnění.

Požadavek na stažení z RD trvá, protože se využije při automatickém stahování záznamů z RD do ProArcu

**Comment by nezbedova** [comment]
Tento požadavek má i MZK a MUO

V MZK mají tyto informace v poli 996. (Verbis)
V MUO je mají v poli 980. (Verbis)
V KNAv je máme jako součást bibliografického záznamu - jednotky - všeobecné informace 1 a 2. (Aleph)

**Comment by nezbedova** [comment]
V MZK funguje stahování.
Pro KNAV a pro MUO je potřeba upravit šablonu MARC a MODS.

**Comment by luckajirku** [comment]
Obávám se, že tohle šablona nevyřeší, že přímo z jednotek v Alephu to přes Z39.50 nepůjde. Tam je asi cesta dostat to nejdřív z jednotek do MARCu do těch devítistovek a odtamtud pak přes šablonu do MODSu.

**Comment by zabak** [comment]
Upřesním: v MZK máme Aleph. Pole 996 má nadefinované i KNAV a další knihovny s Alephem, jde o automaticky generované pole pro potřeby portálu Knihovny.cz, které obsahuje informace o exemplářích. Toto pole je možné dostat i do Z39.50. Je ale nutné si nastavit speciální Z39.50 profil, který se nepoužívá na sdílenou katalogizaci, protože nikdo nebude chtít stahovat pole 996.

**Comment by zabak** [comment]
Konfigurace Z39.50 v Alephu, která předává i pole 996:

V $data_tab příslušné xxx01 knihovny je soubor tab_fix, který obsahuje příslušný fix, který vytváří pole 996 z jednotek.
V našem případě se fix jmenuje CPK

V $alephe_tab/tab_base.lng je příslušná knihovna nadefinovaná jako databáze.
V našem případě 
MZK01CPK

V $alephe_tab/z39_server/
je soubor, který musí mít přesně syntaxi názvu dle názvu databáze, v našem případě:

z39_server_MZK01CPK.conf

v něm je (mimo jiné) tato definice
out-record-syntax USMARC
out-record-expand Z39_SERVER
out-record-fix CPK

Položka out-record-fix obsahuje jméno fixu ze souboru tab_fix,

Po vytvoření definičního souboru restartovat z39.50 server. Pokud je v Z39.50 serveru nadefinováno i vyhledávání přes čárový kód (atribut 1063), tak lze funkčnost otestovat například takto:

yaz_client localhost:9991/MZK01CPK
na příkazové řádce po připojení klienta k serveru zadat třeba:
>f @attr 1=1063 $barcode
(místo "$barcode" dát hledaný čárový kód)

a pokud je potvrzeno vyhledání setu s příslušným počtem záznamů, zadat třeba
> show 1

zobrazený bib. záznam by měl obsahovat pole 996

**Comment by SykoraLukas** [comment]
@mzkgalanda prosím o doplnění záznamu pro testování.

Prosím @nezbedova, @luckajirku, @erikamirova můžeme do transformační šablony z OAIMARCU do MODS přidat stahování pole čárového kódu? Pokud ano, je potřeba přesně definovat, z jakého pole se má hodnota brát.

**Comment by luckajirku** [comment]
My to nepotřebujeme, ale pokud se to zavede, asi by nám to nemělo nijak vadit. 996 v Alephu používáme jen pro CPK, přes Z39.50 ho nastavené nemáme, takže by se nemělo co stáhnout.

**Comment by nezbedova** [comment]
Nově vznikla potřeba automaticky stahovat signaturu z pole 535g (lokace).

Zatím si to sem píši jako poznámku pro další prozkoumání a rozpracování.

**Comment by erikamirova** [comment]
@SykoraLukas Jestli to dobře chápu, tak chceš nějaký MZK záznam k testování. Tady je báze MZK01 https://vufind.mzk.cz/Record/MZK01-001785432/Details#tabnav a MZK03 https://vufind.mzk.cz/Record/MZK03-001064748/Details#tabnav

**Comment by SykoraLukas** [comment]
Nutné aby KNAV donastavila svůj katalog - přidat pole 996 do záznamů, které vrací katalog.

**Comment by ZdenkaSera** [comment]
K tomuto issue doplníme požadavky v souvislosti s předběžně plánovanou červnovou schůzku k RDFlow. Plánovaný způsob využívání registru digitalizace prochází v KNAV revizí.

**Comment by ZdenkaSera** [comment]
@luckajirku @erikamirova @katerinasirova @zabak Prosím, je pro některou z vašich knihoven v tomto issue něco k řešení? V KNAV jsme nastavili stahování signatury a čárových kódů z katalogu do ProArcu - je tam něco k ladění, ale v zásadě je pro nás toto issue vyřešené, požadavek ohledně registru digitalizace už není relevantní)
Děkuji za zpětnou vazbu.

**Comment by erikamirova** [comment]
@ZdenkaSera Za MZK je vše v pořádku a nic k tomu nemáme.

**Comment by luckajirku** [comment]
@ZdenkaSera za nás platí, co jsem psala loni https://github.com/proarc/proarc/issues/411#issuecomment-1072467484

**Comment by katerinasirova** [comment]
Za nás nemám, co k doplnění. Používat velmi pravděpodobně nebudeme.

**Comment by ZdenkaSera** [comment]
Při nastaveném stahování signatury z katalogu se pro každou signaturu vytváří samostatný element location, ale nevyplňuje se do nich sigla. ta je vyplněná jen v prvním výskytu. Není to jen nastavením v KNAV, zkoušela jsem se stejným výsledkem na inovatice-masteru s daty MZK (kat. Z39.50 MZK01, sysno = 000841744). @SykoraLukas Mohla by se sigla dotáhnout vždycky? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Děkujeme za přidání katalogu KNAV přes Z39.50. Vyzkoušela jsem na masteru - sigla se už doplňuje do všech elementů Location, to je prima, díky.

První Location ale zůstává bez signatury (tj. location, které se zakládá vždycky s vyplněnou siglou a povinnou signaturou) - není sice problém ten element odmazat, ale nedala by se první signatura vložit už tam?

![image](https://github.com/proarc/proarc/assets/79305516/25259310-fc95-4bf9-9d3a-a1e43d80ea0e)

**Comment by ZdenkaSera** [comment]
@SykoraLukas Moje poslední poznámka ohledně první location bez signatury pořád platí - dám sem štítek "chyba", abychom se na to nezapomněli podívat (tj. jestli to jde upravit). @SmejkalovaAnna

**Comment by SykoraLukas** [comment]
Jaký záznam stahujete a odkud?

**Comment by ZdenkaSera** [comment]
Inovatika-master, sysno=000381238, Knihovna AV CR Monografie (base 996) - záznam má dvě jednotky (tj. 2 čárové kódy) na téže signatuře ->> v PA se navrhuje 3x místo uložení: 1x bez signatury (vždy jako první v pořadí ve formuláři) a pak 2x se signaturou, zde se stejnou.

**Comment by ZdenkaSera** [comment]
Při stahování záznamů přes Z39.50 v KNAV funkční, signatury a čárové kódy se stahují do záměrů i objektů. Děkujeme.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, řešení je ok, jen se ptám, než přidám poznámku k issue ohledně rozšířených kontrol. Location je neopakovatelný element, při stahování z katalogu se ale vytváří pro každou signaturu. Pokud zpracovatel omylem nesmaže všechny kromě jedné, není to (zatím) kontrolováno.
- Nebylo by možné duplikovat jen shelf locator v rámci téhož location? Mohlo by to být přehlednější díky  kompaktnějšímu zobrazení.  Jen dotaz, případnou změnu by musely odsouhlasit i ostatní knihovny, které to už používají, abychom jim nerozbili proces. Děkuji.

**Comment by SykoraLukas** [comment]
Ano, to by šlo pokud to je podle pravidel. Otázka ale je v tom, jestli se to má dít jen po stažení z katalogu nebo i po ruční úpravě. 
Mohla bys k tomu založit nové issue, protože se mi to zdá jako jiné issue než bylo původní?

**Comment by ZdenkaSera** [comment]
Díky - koukla jsem do standardu jen na monografie  - neopakovatelný je ve skutečnosti element physicalLocation (location ale tím pádem taky neb physicalLocation je povinné). Shelf locator omezený není, ale i tak mně nenapadá situace, kdy by jedna konkrétní předloha byla na dvou signaturách. Nicméně standard se k tomu podle mého nevyjadřuje. Založím tedy issue k diskusi, případně je pak zavřeme.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
