### ISSUE TITLE
CEJSH export - úprava tvorby zipu

### ISSUE THREAD

**Issue by pavelkam** [proarc/proarc#413]
Desklight, přes který se do CEJSH importují data, vyžaduje, aby byl v zipu jako první v pořadí soubor import.properties. Dál má taky neurčitý problém s momentálně použitou addFolder metodou ze zip4j knihovny. To se dá obejít nahrazením metodami setRootFolderInZip a addFiles, které při importu problém nedělají.
Při použití natvrdo zadaných souborů pak úprava writeZip vypadá nějak takhle:

void writeZip(File pkgFile, File packageFolder) throws ZipException {
    ZipFile zipFile = new ZipFile(pkgFile);
    ZipParameters zipParameters = new ZipParameters();
    zipParameters.setEncryptionMethod(Zip4jConstants.ENC_METHOD_STANDARD);
    zipParameters.setCompressionMethod(Zip4jConstants.COMP_DEFLATE);
    zipParameters.setCompressionLevel(Zip4jConstants.DEFLATE_LEVEL_NORMAL);

    File propertiesFile = new File("import.properties");
    zipFile.addFile(propertiesFile, zipParameters);

    ArrayList<File> filesToAdd = new ArrayList<File>();
    filesToAdd.add(new File("imports_new/p0.xml"));
    filesToAdd.add(new File("imports_new/p1.xml"));

    zipParameters.setRootFolderInZip("imports_new/");
    zipFile.addFiles(filesToAdd, zipParameters);
}

**Comment by pokorsky** [comment]
Pokusil jsem se vypsat obsah zipu různými nástroji i standardním java.util.zip.ZipFile a všechny vrací obsah v požadovaném pořadí
```
import.properties
imports_new/
imports_new/p0.xml
```
Je k dispozici zip, který toto pořadí nesplňuje? Jakým nástrojem/knihovnou `Desklight` načítá zip?

**Comment by pavelkam** [comment]
Informace o pořadí v zipu je vše, co z vývojářů Desklightu vypadlo, na knihovnu se zeptám, ale asi to bude s odpovědí zase na dlouho. K uvedenému postupu jsem došel experimentálně na základě toho.
Přikládám dva zipy vytvořené zip4j knihovnou. Funkční, který Desklight přečte, vytvořený daným postupem a nefunkční, vytvořený addFolder metodou.
[funkcni.zip](https://github.com/proarc/proarc/files/115698/funkcni.zip)
[nefunkcni.zip](https://github.com/proarc/proarc/files/115699/nefunkcni.zip)

**Comment by pokorsky** [comment]
Aha, už to vidím. Problém není v pořadí souborů, ale v samostatném záznamu adresáře `imports_new/`. Očekává se pouze seznam souborů. K tomu by měl navrhovaný fix stačit. Díky.

**Comment by pokorsky** [comment]
Opraveno.
