### ISSUE TITLE
"Neočekávaná chyba" při zakládání nového ročníku/čísla... u NDK periodika, v. 3.0

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#415]
Ve verzi 3.0 nám nejde založit u NDK periodika nový ročník, nové číslo atd. - háže to neočekávanou chybu.

exception

java.lang.NullPointerException
	cz.cas.lib.proarc.common.mods.ModsStreamEditor.addPid(ModsStreamEditor.java:135)
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkIdentifiers(NdkMetadataHandler.java:371)
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.checkBeforeWrite(NdkMetadataHandler.java:359)
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.write(NdkMetadataHandler.java:408)
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadataAsXml(NdkMetadataHandler.java:273)
	cz.cas.lib.proarc.common.object.DigitalObjectManager.createDigitalObject(DigitalObjectManager.java:171)
	cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.newObject(DigitalObjectResource.java:210)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	java.lang.reflect.Method.invoke(Method.java:597)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$TypeOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:185)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)
...

Transport error - HTTP code: 500 for URL: ...
Status: -90
Query: { "operationType":"add", "dataSource":"DigitalObjectDataSource", "data":{ "model":"model:ndkperiodicalvolume", "parent":"uuid:0172af7c-4d7b-401c-84cc-a4b857dc6b2b", "_operationType":"add", "_dataSource":"DigitalObjectDataSource", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "requestId":"DigitalObjectDataSource$62727", "useStrictJSON":null, "fallbackToEval":false, "lastClientEventThreadCode":"MUP8", "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "bypassCache":true, "showPrompt":true, "originalData":{ "model":"model:ndkperiodicalvolume", "parent":"uuid:0172af7c-4d7b-401c-84cc-a4b857dc6b2b" }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"DigitalObjectDataSource", "data":{ "model":"model:ndkperiodicalvolume", "parent":"uuid:0172af7c-4d7b-401c-84cc-a4b857dc6b2b" }, "requestId":"DigitalObjectDataSource$62727", "useStrictJSON":null, "fallbackToEval":false, "lastClientEventThreadCode":"MUP8", "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "bypassCache":true, "showPrompt":true, "originalData":{ "model":"model:ndkperiodicalvolume", "parent":"uuid:0172af7c-4d7b-401c-84cc-a4b857dc6b2b" } }, "isRestRequest":true, "dataFormat":"json", "$85o":1453817054634, "useHttpProxy":null }

**Comment by pokorsky** [comment]
Připravím build s opravou.

**Comment by pokorsky** [comment]
Opraveno.

**Comment by mduda100871** [comment]
Ahoj,

jen se chci zeptat, kdy odhadujes vydani buildu? V Jenstejne na me tlaci, abych provedl upgrade...

Diky, Martin

**Comment by pokorsky** [comment]
Připravil jsem [build](https://github.com/proarc/proarc/releases/tag/v3.0.1) s opravou. Verzi bych vydal pokud se nedomluvíme na dalších opravách (cejsh, ...).

**Comment by mduda100871** [comment]
Diky, stahnu, nainstaluji a Ivana otestuje na testovaci vetvi v Jenstejne. Pak da vedet, zda-li nasla nejaky problem...

M.
