### ISSUE TITLE
řazení výsledků vyhledávání

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#416]
Bylo by možné přidat řazení výsledků vyhledávání ve správě digitálních objektů podle abecedy ve sloupci popis?
Když máme v ProArcu více objektů, se kterými opakovaně pracují různí uživatelé, tak už to začíná být docela nepřehledné.

**Comment by pokorsky** [comment]
Přidávám mou emailovou odpověď pro @jkremlacek ohledně možností řazení.
> obávám se, že tahle issue nemá momentálně snadné řešení. Ve SmartGWT je důležité jaký zdroj dat se používá, bez ohledu na nastavení widgetu. Jelikož tady se načítají data vzdáleně po stránkách, tak není možné použít lokální sort (jen v případě dostatečně krátkého výsledku), ale řazení musí být podporováno na straně serveru, což v případě fedory 3 není samozřejmé. Jako index se používá buďto rdbms nebo resource index. Je tedy potřeba zjistit, jestli jsou výsledky všech druhů dotazů řaditelné a jaká by byla výpočetní náročnost.

Ještě dodám, že v případě filtrů `Naposledy vytvořené/editované` další řazení nedává smysl. Jednalo by se tedy o filtry `Dotaz` a `Rozšířený dotaz`. Možná bude rozumnější odložit funkcionalitu řazení až na přechod z fedory 3 a použití lepšího indexu.

**Comment by SykoraLukas** [comment]
Nutné nejprve nasadit Fedoru 4

**Comment by pavelkocourek** [comment]
Přesunuto : řazení výsledků vyhledávání (#416) #30
