### ISSUE TITLE
Přidat zjednodušený formulář pro ročník a číslo

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#417]
Z redakcí vzešel požadavek přidat zjednodušený formulář i pro ročník a číslo. Jednalo by se o přeložení názvů polí a zmenšení počtu zobrazovaných elementů.

**Comment by SykoraLukas** [comment]
Je to ještě relevantní, když se budou v letošní mroce dělat eDokumenty podle NDK? @krizovj

**Comment by krizovj** [comment]
Myslím si že ne, asi by to bylo navíc...
