### ISSUE TITLE
Údaje o autorech

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#423]
Ve zjednodušeném formuláři pro eČlánek prosím přidat ještě jednou pole typ jména a jméno tak, aby tam rovnou pro jednoho autora bylo políčko pro jméno i pro příjmení.
Šlo by případně přednastavit u prvního výskytu typ jména na hodnotu "jméno" a u druhého výskytu na hodnotu "příjmení"?

**Comment by krizovj** [comment]
Už to nechceme
