### ISSUE TITLE
opakování jazyku klíčových slov

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#424]
Je možné ve zjednodušeném formuláři pro eČlánek opakovat jazyk klíčových slov tak, aby se při přidání nového pole pro další klíčové slovo zopakoval jazyk z toho předcházejícího?

**Comment by pokorsky** [comment]
Momentálně ne.

**Comment by pavelkocourek** [comment]
Přesunuto : opakování jazyku klíčových slov (#424) #29
