### ISSUE TITLE
rozsah článku vyjmout z obdélníčku recenze na

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#425]
Ve zjednodušeném formuláři pro eČlánek prosím vyjmout pole první a poslední stránka článku z obdélníčku "Recenze na". Pro všechny uživatele z redakcí je to matoucí.

**Comment by SykoraLukas** [comment]
Stále aktuální? Pokud ano, prosím více popsat (z tohoto zápisu jsem toho moc nepochopil)

**Comment by krizovj** [comment]
Bylo to myšleno pro ten náš nestandardizovaný eČlánek. Až bude kompletní verze ProArcu s elektronickými publikacemi, tak tam už to bude v pohodě, ptž to bude podle standardu. 
Ale tady šlo o to, že v tom modelu pro eČlánek, který zatím používáme, byla pole pro rozsah stran článku úplně nesmyslně v elementu relatedItem. Přitom ve standardech je to v elementu "part-extent-start-end", ale my tenhle celý element máme kdo ví proč v relatedItem, takže to spíš vypadá, že jde o rozsah stran souvisejícího dokumentu.
