### ISSUE TITLE
vyhledávat jako první NDK periodikum

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#426]
Pro instalaci proarc-ozc prosím nastavit v menu-hledat, aby se rovnou vyhledávalo NDK Periodikum místo eČlánku.
S Martinem Dudou se nám to nepodařilo nastavit.

**Comment by pokorsky** [comment]
Pořadí lze upravit jen částečně změnou pořadí pluginů v proarc.cfg. Pořadí v rámci jednoho pluginu je pevně dané a lze změnit jen pro všechny. Pořadí je navíc shodné pro filtr hledat i zakládání nového objektu.
