### ISSUE TITLE
zobrazení originálu v editoru digitalizovaných dat

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#427]
V editoru digitalizovaných dat prosím nastavit, aby se jako první zobrazoval originál místo náhledu. Jedná se o instalaci proarc-ozc.

**Comment by pokorsky** [comment]
Nutno probrat a schválit s vývojovým týmem. Tato možnost není konfigurovatelná. Ovlivní všechny.

**Comment by slapakovai** [comment]
Schváleno vývojovým týmem.

**Comment by jkremlacek** [comment]
Upraveno, výchozí hodnotou je originál.

**Comment by MartinRumanek** [comment]
Jste si jistí? Když je originál TIFF, tak ten se neumí v náhledu zobrazit - budete muset zase ručně přepínat na volbu náhled.

![Imgur](http://i.imgur.com/hcOUq5J.png)

**Comment by slapakovai** [comment]
Vývojový tým už jednou schválil, že s tím souhlasí. Ale jestli se k tomu chce ještě někdo znovu vyjádřit, tak může do 14. 6.
Nejlepší by bylo mít to buď konfigurovatelné nebo ještě lépe tak, aby si ProArc zapamatoval poslední nastavení uživatele a to tam bylo vybráno i při příštím přihlášení. Bylo by to možné?

**Comment by luckajirku** [comment]
Vývojový tým schválil změnu zobrazení originálu v Editoru digitalizovaných dat, o tom, že se to stejně bude chovat i v Import - příprava... jsme se myslím vůbec nebavili. Ale jasně, logiku to má. 
Ale neschvalovali jsme to s vědomím, že se zjednodušením zpracování článků s vkládáním PDF naopak zkomplikuje práce všem ostatním s "normální" digitalizací. Originál TIFF máme přeci u všeho nově digitalizovaného. Tohle bych nepouštěla, dokud se to nevyřeší nějak rozumně. Pamatování posledního nastavení uživatele/stanice by pro nás bylo OK, pokud je to možné.

**Comment by nezbedova** [comment]
Souhlasím s Lucií Jirků.

**Comment by jkremlacek** [comment]
Upraveno, jako výchozí položka se zobrazuje poslední vybraná na dané stanici.

**Comment by pokorsky** [comment]
Výchozí pohled je stále náhled. Prohlížeč si pamatuje poslední nastavení pro každý typ objektu nezávisle pro import a pro úložiště.

**Comment by slapakovai** [comment]
Když nahraju nové pdf, tak se zobrazení zase samo přepne z originálu na náhled. Měl by být pořád zachovaný originál i když přidávám nové pdf.

**Comment by jkremlacek** [comment]
Vytváření náhledů a thumbnail-ů u digital-born dokumentů je experimentální vlastnost https://github.com/proarc/proarc/pull/524#discussion_r118989476, která momentálně není zadokumentována a z kódu není možné vyčíst jaká externí aplikace má být pro tento účel použita, popsanou chybu tedy nejsem schopný zreplikovat.

Pro vyřešení bude zapotřebí buď

- doplnění dokumentace této vlastnosti spolu s informací jaké aplikace třetí strany mají být použity

nebo
- poskytnutí konfigurace (odpovídající segment `proarc.cfg` + objekt v úložišti `icon:IMID`) spolu s potřebnými aplikacemi (muselo by být nejspíš řešeno mimo Github, kvůli autorským právům)

**Comment by slapakovai** [comment]
Zkoušeli jsme to s jakýmkoliv PDF a vždy se to chovalo stejně špatně. Poprosím Martina Dudu, aby vám poslal tu konfiguraci.

**Comment by pokorsky** [comment]
Založil jsem #608. Jinak lze nastavení vyčíst z toho komentáře a BornDigitalDisseminationHandler.java.

> doplnění dokumentace této vlastnosti spolu s informací jaké aplikace třetí strany mají být použity

Cokoli co konvertuje třeba 1. stranu PDF na obrázek. ImageMagick, ... jako import.thumbnail.processor.

`icon:IMID` pro ověření funkcionality není potřeba. Ve zkratce pro PDF stačí založit objekt s PID="icon:application_pdf", který bude mít povinný datastream DC a nějaký obrázek v THUMBNAIL, případně PREVIEW.

**Comment by mduda100871** [comment]
konfigurace a objekt ikony v priloze...

MD

[proarc.cfg.zip](https://github.com/proarc/proarc/files/1329272/proarc.cfg.zip)
[icon_application_pdf.xml.zip](https://github.com/proarc/proarc/files/1329274/icon_application_pdf.xml.zip)

**Comment by MartinRumanek** [comment]
> Zkoušeli jsme to s jakýmkoliv PDF a vždy se to chovalo stejně špatně. Poprosím Martina Dudu, aby vám poslal tu konfiguraci.

Bylo opraveno (funguje to už i pro PDF)
