### ISSUE TITLE
Možnost smazat přiložené pdf

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#428]
V editoru digitalizovaných dat  prosím přidat možnost smazat přiložené pdf. Pokud ho k metadatům přiložím omylem, tak ho teď nemůžu nijak odebrat.

**Comment by pokorsky** [comment]
Momentálně lze nahradit jiným PDF nebo smazat celý objekt.

**Comment by slapakovai** [comment]
schváleno vývojovým týmem
Mazání s varovnou hláškou.

**Comment by jkremlacek** [comment]
Přidána funkce pro smazání přiloženého pdf dokumentu. V GUI je umístěna vedle ikony pro nahrání nového dokumentu.

![dbogui](https://cloud.githubusercontent.com/assets/9445927/24401604/524948ec-13b5-11e7-982f-b05a3486450a.png)

**Comment by pokorsky** [comment]
Přidáno. Díky za patch.
