### ISSUE TITLE
Přidání modelu STT Vícedílná monografie

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#430]
Prosím přidat model STT vícedílná monografie. Do dokumentace jsem to zapsala do komentáře.
model:oldprinttitle
- objekt s MODS podle NDK Vícedílná monografie

**Comment by jkremlacek** [comment]
Přidáno, pouze jsem model pojmenoval `model:oldprintmonographtitle`, aby bylo zachováno jednotné označení vzhledem k NDK variantě, která má označení `model:ndkmonographtitle`

**Comment by pokorsky** [comment]
Přidáno. Díky!

@nezbedova: Nezapomeňte prosím zdokumentovat nový model v dokumentaci #561.

**Comment by pokorsky** [comment]
@jkremlacek: PR nešlo přeložit. To vypadá na nějaký MS editor.
```
[ERROR] proarc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintMonographTitleForm.java:[1,1] illegal character: '\ufeff'
[ERROR] proarc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/mods/oldprint/OldPrintMonographTitleForm.java:[17,9] class, interface, or enum expected
```
