### ISSUE TITLE
Lepsi zabezpeceni prihlasovani / odolnost proti slovnikovym utokum apod.

### ISSUE THREAD

**Issue by mduda100871** [proarc/proarc#431]
Dostavame se do situace, kdy vznika potreba zpristupnit rozhrani ProArcu volne do internetu pro moznost vzdalenych pristupu. Zakladnim bezpecnostnim prvkem je samozrejme dostatecne silne heslo a dale vyuziti protokolu https, ktery ochrani citliva data proti odposlechu "cestou".

Toto nicmene neni odolne proti utokum silou typu slovnik apod. Castecne lze tomuto celit pomoci iptables (bruteforce), ale pro protokol http(s) to neni uplne to prave, protoze moderni prohlizece jsou schopne ve velmi kratkem case otevrit hodne spojeni z jedne IP a regulovani frekvence spojeni na urovni iptables muze byt kontraproduktivni pro "legalni" provoz.

Do jiste miry by nam mohlo pomoci zavedeni technologie Captcha v prihlasovacim formulari ProArcu, nejlepe i s moznosti whitelistu IP adres, pro ktere se Captcha nepouzije/nezobrazi (napr. IP z rozsahu organizace, ktera ProArc provozuje).

Je to samozrejme jen jeden ze stupnu zabezpeceni, ktery by bylo dobre dale kombinovat napr. s aplikaci typu fail2ban (na urovni OS), ktera bude prubezne parsovat prislusne logy a pokud v nich "uvidi" podezrelou aktivitu (v tomto pripade opakovane neuspesne prihlasovani, ktere indikuje potencialni slovnikovu utok), "zarizne" z inkriminovane IP adresy pristup na urovni iptables na jasne definovanou dobu, napr. jeden den.

Bylo by dobre vyse uvedene nepodcenovat a vyssimu zabezpeceni venovat pozornost, protoze kazdy den vidim na serverech, ktere jsou vystavene do internetu, pokusy o utok. Navic, jak je znamo, tak mnoho uspesnych utoku byva i z vnitrku organizace. ProArc bude obsahovat potencialne citliva data, ktera jsou chranena Autorskym zakonem a urcite neni zadouci, aby doslo k jejich kompromitaci.

Duda

**Comment by jkremlacek** [comment]
duplikat #539
