### ISSUE TITLE
Řazení podle indexu stránky

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#432]
V obrazovce Import - příprava metadat pro načtení do úložiště přidat u sloupce Index možnost "Seřadit podle čísla indexu".
Příklad: STT monografie  TB 180 má nepravidelné řazení stran s textem, obrázky a prázdných stran. Strany s textem mají jiné číslování než ty s obrázky. Popisovat po jednotlivých stranách je časově náročné (856 str.) Nejsnadnějším postupem je vybrání jednotlivých stran (např. ilustrací) a jejich hromadný popis. Právě při takových výběrech může dojít k nechtěnému posunu myší a tím i k přeskupení stran. Všechny vybrané se seřadí na poslední označené místo. Pro nápravu této chyby je nutné stránky ručně naposunovat na původní místo.
Velice by nám pomohlo, pokud by byla možnost srovnání stran podle čísla indexu.

**Comment by luckajirku** [comment]
Tohle bychom taky uvítali.

**Comment by nezbedova** [comment]
Nebo přesun neuskutečnit, pokud ho neuložím. Jak tomu je při přesunu stran ve Vazbách.

**Comment by nezbedova** [comment]
Nahrazeno issues #459
