### ISSUE TITLE
LoC MARC/MODS: jazyk klíčových slov

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#433]
Při stahování metadatového záznamu z Alephu se u volně tvořených klíčových slov z pole 653 nedoplňuje jazyk klíčového slova. Takže se to pak špatně exportuje do CEJSHe.
Pravděpodobně bude potřeba to doplnit do transformační šablony z MARCu do MODSu.

Jazyk klíčových slov se rozezná podle 2. indikátoru:
- v poli 653 s indikátory 0_ jsou česká klíčová slova
- v poli 653 s indikátory 09 jsou anglická klíčová slova

Příklad:
http://aleph.lib.cas.cz/F/?func=direct&doc_number=001704913&local_base=AV

**Comment by luckajirku** [comment]
Řekla bych, že je to takhle v pořádku. Pokud KNAV používá v tomto poli nestandardně druhý indikátor 9 (standardně je "nedefinován"), nezdá se mi šťastné kvůli tomu měnit (už tak komplikovanou) šablonu, kterou používají i další knihovny.
Mám pocit, že to v KNAV vzniklo z používání 9 v 650, 655 atd. - ale pro pole 653 jsem nikde takové doporučení nenašla, pouze v interních pokynech KNAV ke katalogizaci.
Pokud se mýlím, tak se omlouvám, ale prosím IŠ o odkaz na nějaký dokument, kde by toto bylo jako platné doporučení NK.

**Comment by slapakovai** [comment]
Nemýlíte se, je to interpretace KNAV. Nicméně bez toho nebude správně fungovat odesílání dat do CEJSHe. Takže se potřebuji dohodnout na nějakém kompromisu.
Používáte v SVK HK ten druhý indikátor v poli 653?

**Comment by melichova** [comment]
Prosíme LJ o vyjádření.

**Comment by luckajirku** [comment]
Ne, druhý indikátor nepoužíváme. Při katalogizaci se řídíme platnými standardy a nevytváříme si vlastní pravidla, která by případně v budoucnu mohla dělat problém, pokud se na národní úrovni ustanoví použití daného indikátoru atd. jiným způsobem. Ale jinak používáme předmětová hesla, a i u starých záznamů, kde byla původně klíčová slova, je nahrazujeme předmětovými hesly. Klíčová hesla používáme pouze výjimečně u článků v případě, že opravdu nelze jinak.

**Comment by pokorsky** [comment]
Existuje tedy dokument v KNAV popisující tato pravidla, na který se lze odkázat?
Jaký je očekávaný výsledek mapování? Z popisu není jasné na které MODS elementy/atributy se má jazyk mapovat a jaké hodnoty použít. Předpokládám, že to bude `mods/subject/topic@lang`.
Má se jazyk vyplnit vždy nebo jen v případě `09`? Pokud začneme jazyk vyplňovat vždy, tak to ovlivní ostatní NDK objekty, jejichž formuláře s jazykem nepočítají (NDK jej nevyžaduje) a neočekávají, že pro kombinaci 0_ se má použít čeština.  S jazykem nepočítá ani základní formulář eČlánku.

Jinak mapování pole 653 se už jednou řešilo v issue #185 podle požadavků @slapakovai. Je tam následující komentář:

> 653 09 i 653 0_ by mělo být oboje mapováno jako subject/topic rozdíl je 
jenom v jazyku toho klíčového slova a ten stejně nemáme jak převést do 
modsu.

**Comment by slapakovai** [comment]
Ano, existuje: http://www.lib.cas.cz/podpora/data/pokyny-ke-katalogizaci-RDA+CPK-2015.doc.
Ano, bude to mods/subject/topic@lang.
V případě 653 0_ se má doplnit hodnota cze, v případě 09 hodnota eng. Kdyby byly v poli 653 jiné indikátory, tak nedoplňovat nic.

Pro základní formuláře je potřeba ke každému opakování topic přidat i výběr jazyka. Ve formulářích ndk jazyk není povinné vyplňovat, ale když se stáhne z Alephu, tak tam ničemu nevadí.

653 0_ by měly mít všechny české knihovny stejné - čeština

**Comment by pokorsky** [comment]
Díky. Ještě počkám jestli nebude někdo rozporovat mapování `653 0_ => topic@lang='cze'`.

Pokud se mají měnit formuláře, tak na to prosím zadej samostatnou issue a popiš, kterých se to týká a jaké popisky polí očekáváš.

**Comment by slapakovai** [comment]
A když se nebudou měnit formuláře, tak to tam bude vidět jako stažená data, která ale ve formuláři nepůjdou upravit?

**Comment by pokorsky** [comment]
ano

**Comment by slapakovai** [comment]
založeno issue #445 pro úpravu základního formuláře.

**Comment by pokorsky** [comment]
Hotovo.
