### ISSUE TITLE
LoC MARC/MODS: jazyk abstraktu

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#434]
Při stahování metadatového záznamu z Alephu se u abstraktu nestáhne jeho jazyk. Takže se to pak špatně exportuje do CEJSHe.
Pravděpodobně bude potřeba to doplnit do transformační šablony z MARCu do MODSu.
Jazyk abstraktu je v MARCu v poli 520, podpole 9.

Příklad:
http://aleph.lib.cas.cz/F/?func=direct&doc_number=001704913&local_base=AV

**Comment by luckajirku** [comment]
Nějak se toho nemůžu dopátrat. V MARC21 je druhý indikátor vždy nedefinován, podpole 9 tam nikde nefiguruje. Našla jsem k tomu pouze jeden zodpovězený dotaz v katpol (http://katdotaz.nkp.cz/zobraz.phtml?id=423), ten se týká anotací v 520. Podle něj to ale v případě anotace vypadá takto - druhý indikátor 9 a podpole 9 je pouze u cizojazyčného textu, nikoli českého:
520 2#  |a Český text
520 29  |a English text |9 eng

Ve vašem záznamu to ale vypadá takto - indikátor 9 i podpole 9 je použito i u českého textu:
520 39  |a Český text |9 cze
520 39  |a English text |9 eng

Můžu IŠ poprosit o odkaz na platné doporučení NK k používání druhého indikátoru a podpole 9, kterým se při popisu řídí? Děkuji.

**Comment by slapakovai** [comment]
Podpole $9 je standartní podpole pro jazyk abstraktu podle NK. To, že ho používáme i u češtiny nijak neovlivňuje to, že se ten jazyk má stáhnout.
Je potřeba to doplnit do transformační šablony, protože LOC toto podpole nepoužívá, takže v jejich transformační šabloně není.

**Comment by melichova** [comment]
Podle NK bylo podpole $9 v poli 520 schváleno pro zápis jazyka. Viz http://katdotaz.nkp.cz/zobraz.phtml?id=423

**Comment by pokorsky** [comment]
Změněno. Pokud existuje podpole $9, tak se jeho hodnota přidá do `abstract@lang`.
