### ISSUE TITLE
chyba při přidání více klíčových slov

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#435]
Při přidávání více než deseti klíčových slov se plus pro jejich přidávání změní na šedivé a další klíčová slova už nejdou přidávat. Když potom založím další metadatový záznam, tak k němu jde přidat pouze jedno klíčové slovo a potom se plus změní na šedivé. Když se umaže jedno klíčové slovo v prvním záznamu, tak potom jde ve druhém přidat.

**Comment by pokorsky** [comment]
Pro opakování je nastaven limit standardně na 10. To je důvod neaktivního tlačítka `+`. Pokud bude potřeba, tak může být pro dané pole nebo skupinu polí zvýšen nebo snížen. Záleží na dohodě.

Problém s opakováním v novém záznamu opravím. Ověřeno na formuláři eČlánek.

**Comment by pokorsky** [comment]
Dočasné řešení: neaktivního tlačítka se lze zbavit obnovením celé stránky po založení nového objektu.

**Comment by slapakovai** [comment]
Můžeš prosím zvýšit limit u klíčových slov na 30.

**Comment by pokorsky** [comment]
Pro který formulář? 30 opakování formuláře Subject s 5 poli mi přijde nepoužitelné. Tohle by se mělo řešit v samostatném issue.

**Comment by pokorsky** [comment]
Opraveno.

**Comment by melichova** [comment]
Založeno issue https://github.com/proarc/proarc/issues/440
