### ISSUE TITLE
Hláška při automatickém odhlášení

### ISSUE THREAD

**Issue by ghost** [proarc/proarc#437]
Při neaktivitě v  "Editoru digitalizovaných dat" mě ProArc automaticky odhlásí. Když se ale vrátím k práci a chci přidat plný text, tak je mi to umožněno, nicméně přidání pdf se nedokončí a zobrazí se chyba 403, která nejspíš znamená, že jsem odhlášená. 
Prosím tedy, aby tak jako v jiných editorech i v "Editoru digitalizovaných dat" po automatickém odhlášení vyskakovalo přihlašovací okno.

**Comment by pavelkocourek** [comment]
Přesunuto : Hláška při automatickém odhlášení (#437) #28
