### ISSUE TITLE
CEJSH - přidání DateIssued do parametrů

### ISSUE THREAD

**Issue by ghost** [proarc/proarc#441]
Pro potřeby exportu do Cejshe bychom potřebovali do MODSu článku přidat do parametrů navíc datum vydání čísla, to jest element DateIssued z úrovně čísla.

**Comment by SykoraLukas** [comment]
O jaký článek se jedná? Jde o článek k eDokumentům, které se budou letos implementovat?

**Comment by krizovj** [comment]
Ano, jde o ečlánky, které se budou nahrazeny těmi novými podle NDK standardu
