### ISSUE TITLE
RDF: Po přidání "kroku" se nezmění stav závislých kroků na "Čeká"

### ISSUE THREAD

**Issue by lucka-pavlova** [proarc/proarc#442]
Přidala jsem krok "Rozřezání stránek" pomocí kontextového menu - Přidat krok. Protože jde oo blocker pro skenování, měl by se změnit stav skenování z "připraveno" na "čeká". Ale skenování zůstává pořád připraveno, tj. asi se nepřepočítává stav při přidání nového kroku? Nebo se nepočítá, že by se mohlo stát, že se mění z připraveno na čeká?

**Comment by pokorsky** [comment]
Tohle zdá se nebylo požadováno (issue #387) nebo aspoň nemůžu dohledat popis. Nyní se stav nově přidaného kroku řídí jen existencí blokerů přidávaného kroku v xml. "Rozřezání stránek" žádné blokery nemá, je tedy ve stavu založeno se stavem  READY.

Jestli to dobře chápu, tak by se mělo kontrolovat:
1. existence a stav blokerů přidávaného kroku. Podle toho bude stav nového kroku WAITING nebo READY
2. existence a stav úkolů závislých na novém kroku. Pokud nejsou zavřené, tak změnit jejich stav na WAITING.

Co v případě, že závislé kroky jsou již vyřešeny (FINISHED, CANCELED)? Bude si je operátor přidávat postupně sám podle potřeby? Teď to tak je.

Dále je potřeba uvážit hloubku závislosti. Co když mám definici  K1(FINISHED)->K2(FINISHED)->K3(STARTED) a přidám opravu K1? Má K2 zůstat FINISHED a K3 přejít na WAITING?

**Comment by nezbedova** [comment]
V KNAV závislé kroky nepoužíváme. Možná by se to hodilo někomu dalšímu, ale vyžadovalo by to revizi možnosti blokování. Byl tam nějaký problém s automatickým záznamem, chyběly tabulky s chybovými hláškami. A na víc si nevzpomenu.

**Comment by ZdenkaSera** [comment]
Podle rozhodovací tabulky k rozšíření je prioritou pro MZK.

**Comment by ZdenkaSera** [comment]
@erikamirova Není tohle k uzavření vzhledem k tomu, že RDFlow nepoužíváte?

**Comment by erikamirova** [comment]
@ZdenkaSera Za MZK ano. :)
