### ISSUE TITLE
Identifikátor DOI a UUID

### ISSUE THREAD

**Issue by melichova** [proarc/proarc#447]
Ve zjednodušeném formuláři pro ečlánek přibylo políčko pro editování UUID. Toto pole v popisu zadání vůbec nebylo, mělo tam být pouze pole pro zápis DOI. Bylo by možné zápis UUID úplně odstranit, anebo alespoň znepřístupnit pro editaci? Je potřeba, aby byl primárně vyplněn "typ identifikátoru" DOI a prázdné pole pro "identifikátor". Viz popis zadání https://docs.google.com/document/d/1ks9jW1v_T1mRJE7KpLUkUdUPibRSueIjbNnzEU9fyic/edit

**Comment by pokorsky** [comment]
Já myslím, že formulář přesně odpovídá dohodnutému zadání viz bod 2 a diskuze s Ivanou v komentářích dokumentu. 2 pole typ a hodnota a roletka s typy, kde DOI je na prvním místě. UUID je povinný identifikátor každého objektu.

Různé stavy editace jednotlivých opakování současné formuláře neumožňují. Pro UUID přidělené objektu by to dávalo smysl, ale pak by byl identifikátor UUID needitovatelný ve všech formulářích. Totéž platí pro schování polí s UUID objektu.

**Comment by slapakovai** [comment]
V zadání je jasně popsáno, že chceme přidat pole pro element mods/identifier/@type="doi". Nikde jsme se tam nebavili o přidání editovatelného uuid.

Druhou část komentáře moc nechápu. Editovat uuid přece nemůže jít nikde, už z podstaty toho identifikátoru.

**Comment by pokorsky** [comment]
`mods/identifier/@type="doi"` je jen způsob uloženi v XML. Cituji z dokumentu popis zjednodušeného formuláře:
> - celý ten rámeček identifikátory by měl být opakovatelný, tzn. měl by jít přidat pluskem.
> - název prvního políčka: Typ identifikátoru
> - obsahuje roletku s výběrem typů identifikátorů
> - hodnota DOI na prvním místě
> - název druhého políčka: Identifikátor

V komentáři jsem upozornil na:
> je potřeba přidat celý formulář identifikátorů.

Ivana Šlapáková
> Mohlo by tam teda být jenom jedno pole pro výběr typu identifikátoru a druhé pole pro zápis toho identifikátoru?

Jan Pokorsky
> Dobře, platnost bude vynechána.

Ivana Šlapáková
> takže připisuji do popisu, jak se mají jednotlivá pole jmenovat

UUID je součástí všech MODS formulářů s identifikátory od první verze. Mě tohle přijde jasné dost.
