### ISSUE TITLE
Ikona - náhled

### ISSUE THREAD

**Issue by melichova** [proarc/proarc#448]
V Editoru digitalizovaných dat se po výběru možnosti "ikona" zobrazí náhled a při výběru "náhled" se zobrazí ikona. Uživatelé nám hlásili, že je to zmatečné. Je možné to opravit?

**Comment by pokorsky** [comment]
Toto byl ale požadavek KNAV pro prezentaci v K5. Náhled pro eČlánek má obsahovat statickou ikonu pro PDF a ikona je ikona vygenerovaná z první strany PDF. Doporučuji přepnout přiblížení na 100%. Doporučuji konzultovat s M. Dudou.

**Comment by slapakovai** [comment]
Honzo, mohl bys nám prosím poslat odkaz na dokument, kde jsou sepsané tyto požadavky nebo zadání od KNAV. Abychom si mohli ujasnit, co a proč bylo požadováno.

**Comment by pokorsky** [comment]
To bude asi jednodušší když se v KNAV domluvíte s Martinem Dudou. Jinak
můžeš projít zápisy na GC a issues. Implementovalo se to před rokem v rámci
CEJSH.

**Comment by melichova** [comment]
Bylo by možné to udělat pro uživatele srozumitelnější a nezobrazovat výrazy z Krameria? Zachovat je jen při exportu do Krameria a při zpracování použít termíny, které jsou srozumitelné uživatelům?

**Comment by pokorsky** [comment]
Otázka je pro kterého uživatele. Primární určení aplikace bylo a snad ještě je zpracování digitalizace pro Krameria podle NDK.

Návrhy tohoto charakteru by se měly řešit s ostatními na proarc-users nebo v rámci vývojových schůzek.
