### ISSUE TITLE
Zobrazování "part name" z formuláře NDK číslo ve sloupci "popis"

### ISSUE THREAD

**Issue by ghost** [proarc/proarc#449]
Je možné nastavit, aby se "part name" z formuláře NDK číslo zobrazovalo ve sloupci "popis"? V případě zpracování i mimořádných čísel, která jsou samostatně číslovaná, se nám najednou objeví např. dvě čísla 1 a není jednoznačné o jaké číslo jde...
Zároveň jsem si uvědomila, že v tomto případě při exportu do CEJSH vzniknou dva stejně pojmenované soubory - nebude to problém?
Děkuji.

**Comment by pokorsky** [comment]
Pojmenování souborů bylo definováno v zadání z knav. Popis čísla v názvu souboru nehraje žádnou roli.

Definice popisu objektu daného modelu většinou určuje vývojový tým zástupců knihoven. Současný popis NDK čísla je tvořen jako "partNumber, dateIssued".

**Comment by slapakovai** [comment]
Možná si s Terkou moc nerozumíte. Bylo by potřeba přidat hodnotu z elementu partName z úrovně čísla do popisu v editoru připojených objektů a v tabulce ve správě digitálních objektů. Mezi hodnotu z partNumber a dateIssued.
Znázornila jsem to tady: https://drive.google.com/open?id=0B3h-WdvT09AdWHJHbm9XS0RjaVk

**Comment by slapakovai** [comment]
Zároveň by bylo potřeba přidat do názvu souboru při exportu pro cejsh partName bez speciálních znaků, diakritiky a mezer. Šlo by to přidat? Kolik hodin práce by to zabralo?

**Comment by pokorsky** [comment]
Já myslím, že si rozumíme. Na tvém obrázku je popis podle předchozího [komentáře](https://github.com/proarc/proarc/issues/449#issuecomment-214736571). Je tedy potřeba takovou změnu popisu NDK čísla dohodnout s vývojovým týmem.

Pokud jde o název souboru, tak je potřeba jasně definovat jak má vypadat. Jen partName? Z jakého objektu? Co když není vyplněno? Jedná se o cejsh nebo crossref? Tohle by mělo být řešeno jako samostatný problém.

**Comment by slapakovai** [comment]
Přidat až úplně nakonec popisu.

**Comment by ZdenkaSera** [comment]
Požadavek zatím zavírám - v zobrazení stromu v novém klientovi je i partname, viz obrázek. Případné problémy s duplicitními názvy souborů pro cejsh bychom řešili jinde.

![image](https://user-images.githubusercontent.com/79305516/221154829-adcfc18b-266a-45f3-b373-c4202262c826.png)
