### ISSUE TITLE
import dat z Krameria 4

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#451]
Návrh na vývoj:
Umožnění importu dat z Krameria 4. Balíček pro K4, který umí ProArc vyexportovat, by měl ProArc umět i přijmout zpátky. Např. pro účely úpravy metadat.

**Comment by pokorsky** [comment]
"Přijmout zpátky" by bylo potřeba definovat.  Data exportovaná pro K4 jsou většinou jen podmnožinou původních, takže původní stav z nich obnovit nelze. Je nějaký důvod proč nepoužít funkcionalitu archivace k obnovení dat pro editaci?

**Comment by slapakovai** [comment]
Data nejsou z ProArcu, ale odpovídají foxml z Krameria.
Data z Krameria do archivace.
Úprava metadat, doplnění stran,...

**Comment by slapakovai** [comment]
MZK udělá analýzu a dodá popis.
