### ISSUE TITLE
Velká pdf - externě referencovaná

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#452]
Velká pdf by měla být externě referencovaná.
Podrobnosti upřesní M. Duda.

**Comment by mduda100871** [comment]
Upresneni - velka pdf by mela byt externe referencovana pri ingestu do fedory. Pri konverzi metadat a importu clanku (pdf) ze systemu eprints se ukazalo, ze od urcite velikosti (cca 15~20MB) binarniho datastreamu se importni proces hrouti a nepomahalo ani pridavani pameti na heapu.

Je totiz potreba uvazit, ze pri vkladani binarniho obsahu do datastreamu uvnitr foxml se tento musi jeste predem zakodovat do base64, tudiz jeho objem o neco naroste. Hledat presnou hranici objemu, od ktere ingest selhava je problematicke, tudiz jsem zvolil jinou strategii - vsechny pdf (a take jpeg-y coby nahledy a thumbnaily) jsem presunul do vyhrazeneho externiho adresare a do prislusnych importnich foxml (do datastreamu) jsem pridal pouze externi referenci s tim, ze pri ingestu se binarni obsah (pdf) presune/zkopiruje do repozitare. Binarni obsah je tedy referencovan pouze pri ingestu, nikoliv trvale. Fedoru je samozrejme nutne nakonfigurovat tak, aby povolila ingest binarniho obsahu z externiho adresare.

Priklad:
...
   <foxml:datastream ID="IMG_THUMB" STATE="A" CONTROL_GROUP="M" VERSIONABLE="false">
      <foxml:datastreamVersion ID="IMG_THUMB.0" MIMETYPE="image/jpeg" CREATED="2014-04-23T02:23:07.614Z">
         <foxml:contentLocation REF="file:///home/k4test/.kramerius4/allowed/datastreamStore/acta_onomastica/2006/47/1/0c6fedcb-ca6b-11e3-95de-001b21187a68_img_thumb.jpg"
                                TYPE="URL"/>
      </foxml:datastreamVersion>
   </foxml:datastream>
   <foxml:datastream ID="IMG_PREVIEW" STATE="A" CONTROL_GROUP="E" VERSIONABLE="false">
      <foxml:datastreamVersion ID="IMG_PREVIEW.0" MIMETYPE="image/jpeg" CREATED="2014-04-23T02:23:07.614Z">
         <foxml:contentLocation REF="http://local.fedora.server/fedora/get/icon:application_pdf/PREVIEW"
                                TYPE="URL"/>
      </foxml:datastreamVersion>
   </foxml:datastream>
   <foxml:datastream ID="IMG_FULL" STATE="A" CONTROL_GROUP="M" VERSIONABLE="false">
      <foxml:datastreamVersion ID="IMG_FULL.0" MIMETYPE="application/pdf" CREATED="2014-04-23T02:23:07.614Z">
         <foxml:contentLocation REF="file:///home/k4test/.kramerius4/allowed/datastreamStore/acta_onomastica/2006/47/1/0c6fedcb-ca6b-11e3-95de-001b21187a68_private.pdf"
                                TYPE="URL"/>
      </foxml:datastreamVersion>
   </foxml:datastream>
...

**Comment by MartinRumanek** [comment]
>Pri konverzi metadat a importu clanku (pdf) ze systemu eprints se ukazalo, ze od urcite velikosti (cca 15~20MB) binarniho datastreamu se importni proces hrouti a nepomahalo ani pridavani pameti na heapu.

Prosím o upřesnění, který importní proces se hroutí. Děje se to v samotném Proarcu nebo v Krameriu? Máte k dispozici log chyby (+ verzi Fedory)?

> Je totiz potreba uvazit, ze pri vkladani binarniho obsahu do datastreamu uvnitr foxml se tento musi jeste predem zakodovat do base64, tudiz jeho objem o neco naroste. 

Ano, base64 má overhead 33%, ale Kramerius si s velkými FOXML bez problému poradí. 
Limitem je Fedora, která přes SOAP službu zařízne FOXML větší jak 128 MB (což odpovídá cca 96 MB PDF),

Tento limit je možné zdvojnásobit, stačí přidat do souboru `{$fedora_home}/server/config/spring/web/jaxws.xml` následující řádky:
```
  <cxf:bus>
    <cxf:properties>
          <entry key="org.apache.cxf.stax.maxTextLength" value="268435456" />
    </cxf:properties>
  </cxf:bus>
```

**Comment by slapakovai** [comment]
Prosím @mduda100871 o napsání odpovědi.

**Comment by mduda100871** [comment]
Hrouti se/hroutil ingest primo ve Fedore. Ten muj prispevek vyse souvisel s ProArcem neprimo, spise jako upozorneni na tento problem. Ingest jsem provadel primo nastroji Fedory, nicmene pokud bych provadel import techto FOXML primo v Krameriovi, tak by upadl i importni proces Krameria, protoze pod nim by upadl ingest Fedory. Kramerius sam o sobe je v tom nevinne.

O te moznosti nastaveni jsem nevedel, dobry tip. Nicmene problem to jen obecne oddaluje. U starsi verze Fedory ingesty padaly urcite na radove mensich objemech, jak jsem psal vyse. Pokud pisete, ze je limit 128M, tak se to mozna tyka posledni verze z rady 3. Nemam aktualni prehled.

Ve svem reseni problemu jsem to prave obesel externi referenci.

MD

**Comment by MartinRumanek** [comment]
> U starsi verze Fedory ingesty padaly urcite na radove mensich objemech, jak jsem psal vyse. Pokud pisete, ze je limit 128M, tak se to mozna tyka posledni verze z rady 3. Nemam aktualni prehled.

To co jsem psal se týká nejnovější Fedory (3.8.1), klidně to vyzkouším i na starší. 
____
Samozřejmě Proarc externě referencované PDF generovat může, ale jak sami píšete:
> Fedoru je samozrejme nutne nakonfigurovat tak, aby povolila ingest binarniho obsahu z externiho adresare.

\+ pokud je instalace Fedory oddělená od Krameria je nutné mít odkazovaný binární obsah ve sdíleném adresáři (do kterého vidí Kramerius i Fedora). Některé instalace na to nemusí být připravené.

Další problém je, že cesty k externím referencím musí být nejspíše absolutní, při přesunu dat do jiného adresáře to bude problémové.

____
 > Nicmene problem to jen obecne oddaluje.

Nemyslím si, že se tím problém jenom oddaluje. Pokud se chystáme v budoucnu přejít na Fedoru 4, tak ta má úplně jiné API a omezení platit nebude.

**Comment by SykoraLukas** [comment]
Nutné nejprve nasadit Fedoru 4
