### ISSUE TITLE
barevná škála ikony vygenerované z pdf

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#454]
Při převodu pdf do ikony vznikne obrázek s barevnou škálou CMYK. Kramerius ale zobrazuje jenom obrázky s barevnou škálou RGB. Prosím o změnění barevného režimu.
Víc informací kdyžtak může poslat Martin Duda, už testoval nějaké řešení.

**Comment by pokorsky** [comment]
Generování ikon je konfigurovatelné pomocí proarc.cfg.

**Comment by slapakovai** [comment]
Zkoušeli jsme to nastavit a vůbec nám to nešlo. Můžeš nám prosím přesně napsat, jaký parametr se má přidat do konfiguračního souboru pro převod ze cmyk do rgb.
Nebylo by lepší to opravit hromadně v nové verzi, aby si to každá knihovna nemusela opravovat ve své instalaci zvlášť?

**Comment by pokorsky** [comment]
Bohužel nepíšeš co jste zkoušeli nastavit.

Konfigurace záleží na použitém externím nástroji pro konverzi a nastavení je nejspíš závislé také na zdrojových PDF. V tomto případě jde předpokládám o ImageMagick. Doporučuji přečíst např. [convert-cmyk-pdf-to-rgb-jpeg-or-png](http://stackoverflow.com/questions/18243340/imagemagick-convert-cmyk-pdf-to-rgb-jpeg-or-png-and-preseerve-colors) a zkoušet konverzi nejdříve mimo ProArc.

Pokud není problém s přenosem parametrů z proarc.cfg (viz. nastavení import.thumbnail.processor a parametry procesoru), pak není co opravovat.
