### ISSUE TITLE
Hodnota normalPage se neukládá do xml

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#455]
V elementu mods:part s atributem type se neukládá hodnota normalPage.
Ostatní hodnoty se ukládají.

V Krameriovi 5 to způsobuje špatné načítání náhledů.
Příklady jsou v issue https://github.com/ceskaexpedice/kramerius/issues/346

Prosím ostatní knihovny, aby otestovali, jestli se jich tento problém také týká. Dále prosím Martinu Nezbedovou, aby se přidala přesný popis toho, kdy situace nastává.

**Comment by slapakovai** [comment]
Reakce z FSV UK:
zkusila jsem tu normal page a taky se mi vygenerováná defaultně neprojeví v xml. Až když přegeneruju a uložím, tak se to v xml projeví.
ProArc 5.2.0, revision: bfc9

**Comment by nezbedova** [comment]
Po hromadném popisu stran se v xml ukáží čísla stran, ale přednastavený typ strany není vyplněný. Po zaškrtnutí políčka u i typu strany se typ strany vyplní.

**Comment by pokorsky** [comment]
Nevidím důvod proč ukládat informaci, že je něco normální. Současný stav šetří místo. 90% stran je normálních. Pokud vím, tak Kramerius s tímto nikdy neměl problém. Ta hodnota tam být může, ale nemusí. Nejspíš šlo o chybu v dané verzi Krameria.

**Comment by nezbedova** [comment]
Dobrý den,

v K5 client se špatně (nebo vůbec) zobrazují strany pokud není normal 
page označena. Viz Chyba1. V K4 client to vypadá jako v Chyba2.
Pokud uložím normal page, zobrazuje se to správně, viz. 
https://kramerius.lib.cas.cz/client/index.vm?q=Lid%C3%A9+Charty+77&page=doc&start=&rows=#pid=uuid:e9515a90-6aab-4674-87e9-2b63a187897d

Takže to opravdu je chyba Krameria?

Martina Nezbedová




Dne 26.4.2016 v 13:12 pokorsky napsal(a):

**Comment by slapakovai** [comment]
Dohodli jsme se, že se hodnota normalPage bude vyplňovat a ukládat u všech normálních stran podle pravidel pro popis periodik: http://goo.gl/wXgJDF

**Comment by pokorsky** [comment]
Podle těchto pravidel ale strana nemá žádný MODS.
