### ISSUE TITLE
Editor připojených objektů - přesun nechtěně přesunutého objektu zpět

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#457]
V editoru připojených objektů přesunu tažením myši stránku, číslo apod. V tu chvíli se objeví tlačítko Uložit, a s dalšími editory nelze do uložení pracovat. Uložím, kliknu na nějakou stránku a mám např. Metadata a náhled zpátky. 
Ale když je to nechtěný přesun a přesunu objekt hned zase zpět na místo, kde byl předtím, bez uložení té špatné volby, tak už se tlačítko Uložit neobjeví, ale druhý/třetí sloupec zůstane prázdný. Je třeba dát Obnovit nebo jít přes šipky v hierarchii jinam a zase se vrátit, aby šlo pracovat s dalšími editory.

**Comment by pokorsky** [comment]
Akce Obnovit nebo znovuotevření editoru je správná cesta jak se změny zbavit. Přesouvat zpět je zbytečné.
