### ISSUE TITLE
Hodnotu normalPage neukládat do xml ani při ručním vyplnění

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#458]
Hodnotu normalPage neukládat do xml ani při ručním vyplnění.
Důvod: aby nevznikala situace, že se při ručním vyplnění hodnota uloží a při hromadném neuloží.
Hodnotu normalPage prosím ponechat rozbalovací nabídce.
detaily viz https://github.com/proarc/proarc/issues/455

**Comment by jkremlacek** [comment]
Při očíslování mohou vzniknout dva následující segmenty foxml: [-zde-](https://gist.github.com/jkremlacek/fcd11ed108d18ff6029776519f071b00). Při manuálním vyplnění tedy navíc vzniká atribut `type` uzlu `mods:part` s hodnotou `NormalPage`.

Pokud požadavek na úpravu chápu správně, pak je žádoucí verze vznikající při automatickém číslování ve všech případech?

Dále ponecháním normalPage v rozbalovací nabídce je myšlena která nabídka při editaci metadat? 
(viz obrázek)

![dropdown_normalpage](https://cloud.githubusercontent.com/assets/9445927/23022499/7403f528-f451-11e6-8fdc-05f0a630efb9.png)

**Comment by nezbedova** [comment]
Ano.  Žádoucí je verze vznikající při automatickém číslování ve všech případech.
Ve všech model musí zůstat NormalPage jako typ strany. Tak, jak to máte na obrázku to je správně. To je kvůli tomu, aby byla možnost opravy případné chyby.

**Comment by jkremlacek** [comment]
Upraveno, pageType se nyní zaznamenává do foxml pouze pro hodnoty různé od NormalPage.

**Comment by MartinRumanek** [comment]
Nejde to vyřešit ještě před exportem (ve frontendu/při ukládání z něj)?

Toto řeší pouze NDK export, navíc je ošetřená jenom metoda setMetadataAsJson, ale už ne setMetadataAsXML.
