### ISSUE TITLE
Změna umístění stran jen po potvrzení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#459]
Z jednání vývojového týmu vzešel požadavek na úpravu funkčnosti v obrazovce Import - příprava metadat pro načtení do úložiště".
Po přesunu jednotlivých stran uložit tyto změny pomocí použití tlačítka "Uložit" jako tomu je ve Vazbách. 
Tlačítko "Uložit" umístit na horní lištu za  "Validovat", také stejně jako tomu je ve Vazbách. Při nepotvrzení změn nechat původní (poslední potvrzené) rozložení stran.

Toto issues nahrazuje issues  #432 a  #436.

**Comment by pokorsky** [comment]
Nová implementace umožňuje změnit pořadí buďto v tabulce nebo v seznamu ikon. SmartGWT neumožňuje změnu pořadí před uložením zobrazit v tabulce i seznamu ikon současně. Po první změně jsou ostatní komponenty (tabulka/ikony, formulář) blokovány dokud uživatel neuloží změnu nebo nezruší změnu pořadí akcí Obnovit. Toto odpovídá editoru Vazby.
