### ISSUE TITLE
hromadné vytváření objektů (čísel)

### ISSUE THREAD

**Issue by jakubblecha** [proarc/proarc#460]
Měli bychom zájem o novou funkci hromadného vytváření objektů v cestě: úložiště/ vazby/ editor připojených objektů/ nový. Kromě stávající možnosti tvorby jediného objektu, by pak nově bylo možné vytvořit najednou např. 80 ndk čísel.

K tomu se následně váže hromadné (automatické) doplnění metadat těmto objektům. Za nás by se předně mělo jednat o Part number a Date. Představujeme si vložení funkce (historického) kalendáře, v němž zvolíme rok, dále označíme dny v týdnu, kdy noviny vycházely a proarc datování sám dokončí.

**Comment by pokorsky** [comment]
Pro generování řady čísel podle dnů v týdnu bude potřeba přidat další vstupní údaje:
- počáteční číslo řady
- počáteční datum
- konečné datum (při nevyplnění se použije 31.12.)

Akce bude součástí tlačítka `Nový`, kde pro NDK číslo přibude submenu s možnostmi `Vytvořit` a `Vytvořit více...`.

**Comment by pokorsky** [comment]
Implementováno. Přidáno omezení, že konečné datum musí mít stejný rok jako počáteční datum.

**Comment by luckajirku** [comment]
Datum od má u roku výběr 1900-2020, ale Datum do jen 1995-2020.

**Comment by pokorsky** [comment]
Minimální rok výběru v kalendáři sjednocen na 1900 pro `Datum do`. Ručně lze zadat hodnoty i mimo tento rozsah.
