### ISSUE TITLE
oprava a upgrade náhledů

### ISSUE THREAD

**Issue by jakubblecha** [proarc/proarc#461]
V sekci Import-příprava metadat pro načtení do úložiště správně nefunguje zoom náhledu snímků. Když zvolím např. Příblížení 200%, objeví se pouze výřez obrázku, zpravidla pravá strana, a neexistuje možnost zobrazit ostatní části.

S tím souvisí návrh na vylepšení náhledů vložením možnosti výběru zón, které mají být přibližovány. Např. při hromadném zpracování novin se zaměřujeme pouze na záhlaví a zápatí jednotlivých stránek. Velmi by nám tedy usnadnilo práci, kdybychom nemuseli každou stránku zvlášť zoomovat, ale viděli jen to podstatné.

**Comment by luckajirku** [comment]
ad návrh na vylepšení náhledů - to už je v issue #215

**Comment by pokorsky** [comment]
Problém se zvětšením obrázku lze reprodukovat nezávisle na použitém prohlížeči.

**Comment by pokorsky** [comment]
Vyřešeno
