### ISSUE TITLE
Nekonečný sroll při slučování

### ISSUE THREAD

**Issue by jakubblecha** [proarc/proarc#462]
Při slučování (přesouvání) objektů z Editoru připojených objektů do Editoru nadřazených objektů se aplikace po každém přesunu obnovuje. Třebaže naposledy editovaný adresář (čísla) ve stromové struktuře úložiště zůstane označen, musí k němu operátor vždy znovu rolovat myší. Při zpracování několika desítek čísel najednou je to zbytečný čas navíc. Dalo by se nějak dosáhnout toho, že se po obnovení aplikace zobrazí stejné místo ve struktuře?

**Comment by krizovj** [comment]
Platí to pořád? Případně, v čem je přesně problém? Asi jsem to úplně přesně nepochopila...

**Comment by pavelkocourek** [comment]
Přesunuto : Nekonečný sroll při slučování (#462) #27
