### ISSUE TITLE
RDF: možnost založení prázdného záměru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#463]
Při zakládání nového záměru přidat možnost založení prázdného záměru, který si ručně vyplním. 
Určeno pro zakázky, kdy předloha není v RD ani SKC např. kroniky.

**Comment by nezbedova** [comment]
Můžeme si tuto možnost nastavit v našem xml? Pokud ne, počítá se s ní do verze 3.3?

**Comment by pokorsky** [comment]
Ne, pro verzi 3.3 jsme se na tom v rámci periodik nedohodli.
