### ISSUE TITLE
Profil pro staré tisky

### ISSUE THREAD

**Issue by LenkaDamborska** [proarc/proarc#464]
Dobrý den, rádi bychom vyzkoušeli Proarc zhlediska zpracování starých tisků. Defaultní profil nám funguje dobře, ale u profilu pro staré tisky nejdou automaticky konvertovat tify. Měl s tím už někdo podobný problém? Možná děláme chybu v nastavení profilu. Díky.

**Comment by pokorsky** [comment]
To je velice obecně položený dotaz. Bez popisu použité konfigurace a případné chybové hlášky.

**Comment by Jenyk** [comment]
Nastavení profilu pro staré tisky máme podle https://github.com/proarc/proarc/wiki/Konfigurace#importn%C3%AD-profily

Konverze je nastavená přes kakadu a u hlavního profilu funguje, ale u starých tisků proarc místo konverze křičí "java.io.FileNotFoundException: Missing archival JP2: ....ac.jp2"

Zkoušel jsem nastavení pro proces konverze zkopírovat i do profile.oldprint.cfg, ale nic to nezměnilo.

**Comment by pokorsky** [comment]
Na wiki je jen základní ukázka. Podle FileNotFoundException to vypadá, že nemáte správně nastavený proces konverze a import se snaží jen dohledat soubory `.ac.jp2`. Máte nastaveno `import.ndk_archival.processor`?

**Comment by Jenyk** [comment]
Právě. 
import.ndk_archival.processor nastavené máme, celá konfigurace vypadá takhle: https://gist.github.com/Jenyk/4ab9908e998db8a9bb28a85335284f23

Pro defaultní profil funguje a pro staré tisky ne, ani když jsem to stejné nastavení zkopíroval i do profile.oldprint.cfg

**Comment by pokorsky** [comment]
V konfiguraci profilu žádnou chybu nevidím. Předpokládám, že profile.oldprint.cfg je ve stejném adresáři jako proarc.cfg. Zkusil jsem konfiguraci použít a procesor se načetl.

Kromě FNFE není žádná jiná hláška v `TOMCAT/logs/proarc*.log`?
Můžete ještě popsat verzi ProArcu, java, tomcat, OS?

**Comment by Jenyk** [comment]
Tohle je celý log, co se toho týká:

Aug 10, 2016 9:40:41 AM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Aug 10, 2016 9:40:43 AM cz.cas.lib.proarc.common.imports.TiffImporter consume
SEVERE: /data/proarc/users/proarc_1/import/Episoda3/MC_287337b0-5042-11e3-8cdc-005056827e51_0001.tif
java.io.FileNotFoundException: Missing archival JP2: /data/proarc/users/proarc_1/import/Episoda3/MC_287337b0-5042-11e3-8cdc-005056827e51_0001.ac.jp2
	at cz.cas.lib.proarc.common.imports.TiffImporter.importArchivalCopy(TiffImporter.java:229)
	at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:105)
	at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSetImport.java:115)
	at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSets(FileSetImport.java:96)
	at cz.cas.lib.proarc.common.imports.FileSetImport.start(FileSetImport.java:83)
	at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:210)
	at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:181)
	at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)


profile.oldprint.cfg je ve stejném adresáři a má stejná práva jako proarc.cfg
Verze ProArcu je 3.1, Tomcat 7.0.64 v Debianu 8 v dockeru, který běží v Centosu 7
Verze javy: 1.7.0_80

Vám tedy načtení obrázku včetně konverze v profilu oldprint proběhne bez problému?

**Comment by pokorsky** [comment]
Podle logu se vůbec nepoužije procesor s kdu_compress, ale pouze se hledá soubor podle koncovky a ten byl nenalezen. Znovu jsem to ověřoval a stejně nastavený profil mi funguje. Ani z KNAV nejsou hlášeny žádné potíže s profily.

Problém by mohl být ve verzi javy. Jelikož do verze 3.1 je používána Fedora Commons 3.5, a ta vyžaduje  Sun/Oracle JRE 1.6 (ne openjdk), tak i ProArc byl vyvíjen a testován pro stejnou verzi.

Dokončuji verzi 3.2, kde je vyžadována Fedora 3.8.* a java 1.8 a profily opět fungují.

**Comment by jkremlacek** [comment]
Vyřešili jsme problém s načítáním profile.oldprint.cfg souboru způsobeným nejspíš chybným kódováním souboru.

Při načítání ovšem dostáváme chybu ohlášenou v issue 473. Model s id "model:oldprintpage" si proarc při inicializaci do fedory sám nezavede a na wiki není popsáno jakým způsobem zavádět nové modely. Je někde k dispozici dokumentace pro zavádění nových modelů?

**Comment by pokorsky** [comment]
Kódování .cfg souborů by mělo být standardní UTF-8. Tohle by se mělo projevit snad jen při zobrazení textů v UI.

Popis nastavení pluginů je pouze v odkazovaném proarc.cfg.template. Díky za upozornění, přidám to na wiki.
