### ISSUE TITLE
Import ALTO selže

### ISSUE THREAD

**Issue by FoxKyong** [proarc/proarc#465]
ProArc mi jaksi nechce importovat ALTO. Podle chyby to vypadá, že neprojde validací, ale validní by mělo být. Jakou verzi ALTO ProArc vlastně bere? Je jich už dost, tak nevím, jestli to není jenom kvůli tomu, že mám použitou jinou, než zvládne importovat, ale v dokumentaci jsem nenašel nikde, jaké verze ALTO ProArc podporuje. ALTO mám ve verzi 2.0.

Tady je výpis chyby:
`/data/proarc/users/radim/import/000144300/proarc_import/000.foxml cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:2bbb0903-4aee-4709-97ce-c6d69ff62c34, file:/data/proarc/users/radim/import/000144300/000.ocr.xml at cz.cas.lib.proarc.common.ocr.AltoDatastream.importAlto(AltoDatastream.java:66) at cz.cas.lib.proarc.common.imports.TiffImporter.importOcr(TiffImporter.java:195) at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:107) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSetImport.java:115) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSets(FileSetImport.java:96) at cz.cas.lib.proarc.common.imports.FileSetImport.start(FileSetImport.java:83) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:210) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:181) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: org.xml.sax.SAXParseException; systemId: file:/data/proarc/users/radim/import/000144300/000.ocr.xml; lineNumber: 1; columnNumber: 936; cvc-pattern-valid: Value '' is not facet-valid with respect to pattern '([a-zA-Z]{1,8})(-[a-zA-Z0-9]{1,8})*' for type 'language'. at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.processOneAttribute(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.processAttributes(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source) at org.apache.xerces.impl.xs.XMLSchemaValidator.startElement(Unknown Source) at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) at org.apache.xerces.jaxp.validation.StreamValidatorHelper.validate(Unknown Source) at org.apache.xerces.jaxp.validation.ValidatorImpl.validate(Unknown Source) at javax.xml.validation.Validator.validate(Validator.java:124) at cz.cas.lib.proarc.common.ocr.AltoDatastream.isAlto(AltoDatastream.java:78) at cz.cas.lib.proarc.common.ocr.AltoDatastream.importAlto(AltoDatastream.java:59) ... 13 more `

**Comment by pokorsky** [comment]
ProArc validuje ALTO ve verzi 2, tak jak je požadováno v NDK specifikaci. Konkrétně je použito schema 2.1, které by mělo být zpětně kompatibilní s 2.0.
