### ISSUE TITLE
Běh proArc s MPTTripleStore

### ISSUE THREAD

**Issue by jdobiasovsky** [proarc/proarc#468]
Dobrý den,
zvažujeme v NTK používání proArc pro náš kramerius. Ale naše fedora repository používá jako resource index MPTTripleStore a ne Mulgara (kvůli OAI provideru, viz. [wiki krameria](https://github.com/ceskaexpedice/kramerius/wiki/Instalace#nastaven%C3%AD-implementace-resource-indexu)). 

V případě že bychom byli nuceni změnit použitý resource index, tak nebude fungovat OAI provider a všechno, co si sklízí NTK by Kramerius přestal sklízet.

Je možné nějakým způsobem používat i MPTrippleStore?

**Comment by pokorsky** [comment]
Rozhodně Vám doporučuji použít samostatnou instanci Fedory pro ProArc. 
Fedora 3 neumožňuje oddělit data pomocí schema nebo něčeho podobného. Po 
kompletaci hierarchie datových objektů použijete export v daném formátu 
(Kramerius nebo NDK) a tato data pak importujete do Krameria.

Obecně je dobré mít ProArc na vlastním serveru, protože zpracování skenů 
je hodně náročné na zdroje. PostgreSql lze sdílet.

**Comment by pokorsky** [comment]
Ještě bych přidal, že nová verze Krameria pro OAI resource index nepotřebuje a využívá SOLR.
