### ISSUE TITLE
Neošetřený stav při neexistujícím modelu ve fedoře

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#473]
V případě kdy ve fedoře neexistuje proarc-em požadované model-id, dojde k vyhození NullPointerException.

Chyba je nejspíš v DigitalObjectHandler.java v metodě getPlugin():

_models.find(modelId)_ při neexistujícím modelu vrátí null na který je následně voláno _.getPlugin()_ vyvolávající zmíněnou vyjímku.

**Comment by pokorsky** [comment]
proarc při startu kontroluje existenci modelů v úložišti a případně je obnoví. proarc tyto meta objekty nikdy nemaže.  Pokud model zmizel zásahem mimo aplikaci, tak  je výjimka NPE přijatelný výsledek.

Můžete popsat o jaké model-id jde a případně kroky jak takovou situaci navodit?

**Comment by pokorsky** [comment]
Aha už tuším jak to nastalo. Předpokládám, že to souvisí s issue #464 a profilem starých tisků. Řešením je tedy aktivace pluginu oldprint, který daný model automaticky dodá.
