### ISSUE TITLE
Sloupce ve správě záměrů

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#474]
Selhává mi opakované zobrazení/skrytí sloupců: Vytvořeno, Změněno, Financováno, Poznámka (které jsou defaultně skryty)

Chybu je možné replikovat (např. na položce "Změněno") následovně:
- otevřít Správu záměrů (adresa /#workflow:{"type":"JOBS"})
- v položce "Název" kliknout pravým tlačítkem myši
- v menu vybrat sloupce a kliknout "Změněno" (sloupec se zobrazí a objeví se u položky zaškrtnutí)
- znovu kliknout (sloupec zmizí, vůči výchozímu stavu ale zůstane v prvním řádku tabulky jeho buňka pro omezení výběru)
- znovu kliknout (zmizí buňka v horním řádku)
- další kliknutí již nic neudělá (intuitivně bych očekával, že bude znovu možné sloupec zobrazit)

**Comment by pokorsky** [comment]
Prosím uvádějte verzi ProArcu a pro problémy týkající se UI také verzi prohlížeče.

Testoval jsem s poslední verzí ProArc 3.2-20161020002940 a Chrome 53.0.2785.143 m (64-bit) a sloupec Změněno se objeví a zmizí společně s filtrem po každém kliknutí v kontextovém menu sloupce Název.

**Comment by jkremlacek** [comment]
ProArc: 3.1-Build: 20161020134423 a Mozilla Firefox 49.0-2.fc24 64-bit

**Comment by pokorsky** [comment]
S Firefoxem 49.0 vše funguje také. Zkusil jsem i verzi 3.1. Doporučuji vypnout případné pluginy a rozšíření prohlížeče.  Zkuste také verzi 3.2, kde je nejnovější verze knihovny SmartGWT, která komponentu tabulky implementuje.

**Comment by jkremlacek** [comment]
V release sekci jsem našel jako latest verzi 3.1, stejně tak mezi tagy je 3.1 poslední. Kde mohu stáhnout verzi 3.2?

**Comment by pokorsky** [comment]
3.2 je ve fázi testování. [Odkaz](https://drive.google.com/open?id=0B5jmv1ZaUMw8Z0ZQVTRFWVVWRkE) byl poslán zatím jen  do konference [proar-users](https://groups.google.com/d/forum/proarc-users).

**Comment by jkremlacek** [comment]
Nastavuji si u sebe verzi 3.2, bylo by možné tuto verzi dát k dispozici i zde do repozitáře, aby nebyla dostupná pouze zastaralá verze?

**Comment by pokorsky** [comment]
Takže to můžeme zavřít. Připravovaná verze 3.2 je nyní v [branche development](https://github.com/proarc/proarc/tree/development).
