### ISSUE TITLE
Progressbar importu

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#475]
Na verzi 3.2-SNAPSHOT se špatně zobrazuje progressbar načítání skenů v rámci importu.

Při načítání většího množství souborů (v případě testu 121) se ukazatel zasekne na nějakém čísle (v případě testu na 3) a dále se neaktualizuje. Po dokončení načítání neproběhne automatické přesměrování na stránku s přípravou metadat. 

Dále je také špatně nastavený rozměr progressbar-u viz screenshot:

[http://www.image-share.com/upload/3352/248.png](http://www.image-share.com/upload/3352/248.png)

Vyzkoušeno na:
Firefox 49.0-2.fc24 64bit
Chrome 54.0.2840.59 64bit

**Comment by pokorsky** [comment]
Díky, tohle už se řeší jako issue #470.
