### ISSUE TITLE
UI: Editor digitalizovaných dat nezobrazuje obrázky

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#476]
Při načtení editoru "problikne" obrázek editovaného skenu a dál zobrazí prázdnou plochu v oblasti náhledu.

Obrázek je možné zobrazit přepnutím měřítka na: 
"Vyplnit na šířku" / "Vyplnit na výšku" nebo po sobě přepnout dvě rozdílná přiblížení 
a poté zpět na výchozí "Přizpůsobit panelu". 

Při načtení následujících/předchozích stran se obrázek opět nezobrazí.

Vyzkoušeno na:
Firefox 49.0-2.fc24 64bit
Chrome 54.0.2840.59 64bit

**Comment by pokorsky** [comment]
Tohle bude souviset s issue #461. Obrázek lze načíst kliknutím na Obnovit.

**Comment by luckajirku** [comment]
V chrome 53.0.2785.143 tohle nastává jen v kombinaci Přizpůsobit panelu - Náhled, jiné kombinace jsou ok.

**Comment by nezbedova** [comment]
V Editoru připojených objektů - náhled- přizpůsobit panelu - "obnovit" nepomáhá. U ostatních druhů náhledů to funguje. Stejný problém je u STT monografie v obrazovce Import - Příprava metadat pro načtení do úložiště. Po "obnovit" naskočí první soubor.

**Comment by pokorsky** [comment]
Vyřešeno v rámci issue #461. Obrázky nesmí být centrovány.
