### ISSUE TITLE
Tomcat 8: problem s verzi jax-rs knihoven

### ISSUE THREAD

**Issue by mduda100871** [proarc/proarc#477]
Ahoj,

provedl jsem kompletni upgrade prostredi pro otestovani vyse uvedene verze snapshotu, takze:
- fedora 3.8.1
- tomcat 8 distribucni (Debian Jessie)
- java 8 (Oracle 1.8.0_112-b15)
- PostgreSQL 9.4 distribucni (Debian Jessie)
- apache 2.4 distribucni (Debian Jessie)

snazil jsem se postupovat dle navodu. Vsechno funguje (az na samotny proarc), fedora bezi a normalne komunikuje (vyhledava objekty, vraci jejich obsah atd.) - data a index jsem prenesl z verze 3.5 a provedl novy rebuild databaze.

Dle doporuceni jsem smazal endorsed/ adresar (resp. zrusil jsem v CLASSPATH cestu na predchozi verze knihoven). Po nainstalovani proarc.war se tento rozbali (dle ocekavani, predchozi verze tam rozbalena neni - nova instance tomcatu) a objevi se v admin rozhrani tomcatu mezi spustenymi aplikacemi. Nicmene, kdyz na nej pristoupim standardnim zpusobem prostrednictvim prohlizece jako bezny uzivatel, vypadne chybove hlaseni (misto prihlasovaciho dialogu) a v detailech je vyjimka - viz screenshot.

![proarc-test-exception-01](https://cloud.githubusercontent.com/assets/8750622/19682368/8f7462a0-9aad-11e6-8e44-b9e1ccb1eac1.png)
![proarc-test-exception-02](https://cloud.githubusercontent.com/assets/8750622/19682369/8f74d44c-9aad-11e6-8a58-3fbfa62c2019.png)
![proarc-test-exception-03](https://cloud.githubusercontent.com/assets/8750622/19682414/d1ad48a8-9aad-11e6-9a3f-9316da8697b1.png)
![proarc-test-variables-04](https://cloud.githubusercontent.com/assets/8750622/19682566/83f2d64a-9aae-11e6-9ede-6b8e718c9068.png)

Tak nevim, kde by jeste mohl byt problem...

MD

**Comment by pokorsky** [comment]
Rebuild databáze ani indexu není potřeba.

Ano, podle hlášek se jax-rs 1 nějakým způsobem dostává před verzi 2. Testoval jsem s Tomcat 7 a na podobný problém jsem nenarazil.
Mělo by se jednat o následující jary:
* javax.ws.rs-api-2*-sources.jar
* jersey-core-1.*-sources.jar
Podle screenshotů toho víc nezjistím . Chce to prohledat filesystém, logy a zkontrolovat konfiguraci, jestli tam není nějaká zapomenutá cesta. Jestli si dobře pamatuji, tak v KNAV je kombinovaná konfigurace produkčního a testovacího tomcatu.

**Comment by mduda100871** [comment]
V tom pripade to vypada, ze je vinikem fedora, nasel jsem knihovnu:

apache-tomcat8/webapps/fedora/WEB-INF/lib/jsr311-api-1.0.jar

ktera by mela prave obsahovat JAX-RS 1 jak jsem dohledal na netu....

MD

**Comment by pokorsky** [comment]
Martine, to určitě není ono. webapps/fedora/WEB-INF/* je oddělená classpath, kterou proarc nesdílí. Sdílí se tomcat/lib a potom záleží na konfiguraci tomcatu. Např. loaders v catalina.properties.

Zkusil jsi logovat classloading? `-verbose:class`

**Comment by mduda100871** [comment]
Podarilo se mi to obejit nasledujicim zpusobem - do Catalina/localhost jsem pridal soubor proarc.xml s timto obsahem:
...
<?xml version="1.0" encoding="UTF-8"?>
<Context path="/proarc">
    <Resources>
        <PreResources
            base="/home/proarc-test/proarc-classes"
            className="org.apache.catalina.webresources.DirResourceSet"
            webAppMount="/WEB-INF/classes"/>
        <PreResources
            base="/home/proarc-test/proarc-lib/javax.ws.rs-api-2.0.1.jar"
            className="org.apache.catalina.webresources.JarResourceSet"
            webAppMount="/WEB-INF/classes"/>
    </Resources>
</Context>
...
 Dale jsem vytahl z aplikace knihovny a tridy do separatnich adresaru a ted to funguje...

Logovat classloading zkusim...

**Comment by mduda100871** [comment]
Takze jsem vratil puvodni nastaveni (bez proarc.xml) a nastavil logovani. Vygrepoval jsem z logu obe knihovny a nikde v ceste krome v proarcu a fedore se neobjevuje - v priloze zip archiv logu. Ani v catalina.properties neni v ceste starsi verze. Je tam pouze lokalni uprava do lib/ adresare uzivatele proarc-test, kde je ale pouze jdbc postgresu.

[catalina.out.tar.gz](https://github.com/proarc/proarc/files/552804/catalina.out.tar.gz)

![loader-path-01](https://cloud.githubusercontent.com/assets/8750622/19719904/387c847c-9b6c-11e6-9483-eba82f6eae38.png)


ted tedy uz nevim, ceho se chytit...

**Comment by pokorsky** [comment]
Tak podle logu se pro fedoru načte správně jax.rs 2, ale pro proarc jax.rs 1. 

```log
[Loaded javax.ws.rs.core.Application from jar:file:/home/proarc-test/apache-tomcat8/webapps/fedora/WEB-INF/lib/javax.ws.rs-api-2.0-m10.jar!/javax/ws/rs/core/Application.class]
[Loaded javax.ws.rs.core.Application from jar:file:/home/proarc-test/apache-tomcat8/webapps/proarc/WEB-INF/lib/jersey-core-1.17.1.jar!/javax/ws/rs/core/Application.class]
```
Problém je skutečně ve změně sestavení classpath v Tomcat 8 viz. https://issues.apache.org/bugzilla/show_bug.cgi?id=57129. Dřívější verze Tomcatu seřadily soubory v adresáři podle abecedy. Jelikož proarc používá fedora-client, tak se jax.rs 1 nelze zbavit. Přepsat knihovnu na jax.rs 2 zato nestojí, protože fedora 3 je ukončena.

V případě Tomcat 8 je tedy nutné `javax.ws.rs-api-2.0.1.jar` z `webapps/proarc/lib` dostat na classpath před `webapps/proarc/lib`. 

Podle https://tomcat.apache.org/tomcat-8.0-doc/config/resources.html je potřeba definovat
```xml
<Resources>
  <PreResources className="org.apache.catalina.webresources.FileResourceSet"
                base="${catalina.base}/webapps/proarc/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar"
                webAppMount="/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar" />
</Resources>
```
a podle https://tomcat.apache.org/tomcat-8.0-doc/config/context.html je možné obsah uložit do
  1. `$CATALINA_BASE/conf/[enginename]/[hostname]/proarc.xml`
  2. nebo přímo do aplikace `/META-INF/context.xml`

Martine můžeš zkusit tu druhou možnost do `webapp/proarc/META-INF/context.xml`? Jestli to bude fungovat, tak bych to přidal do proarc.war. Jinak doplním konfiguraci na wiki.

**Comment by mduda100871** [comment]
Rozbalil jsem proarc.war, pridal do META-INF/context.xml nasledujici obsah:
```
<?xml version="1.0" encoding="UTF-8"?>
<Context>
    <Resources>
        <PreResources className="org.apache.catalina.webresources.FileResourceSet"
            base="${catalina.base}/webapps/proarc/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar"
            webAppMount="/WEB-INF/lib/javax.ws.rs-api-2.0.1.jar" />
    </Resources>
</Context>
```
 zabalil zpatky, nainstaloval a spustil. Nyni to funguje bez problemu zda se - prihlasil jsem se:
![login-01](https://cloud.githubusercontent.com/assets/8750622/19747166/6d1c836c-9bda-11e6-83da-f59613f66fa0.png)

Dam echo Ivane, aby to zkouseli...

**Comment by pokorsky** [comment]
Přidáno. Tomcat 7 sice loguje do `catalina.out` 
```
Oct 31, 2016 10:20:07 AM org.apache.tomcat.util.digester.Digester endElement
WARNING:   No rules found matching 'Context/Resources/PreResources'.
```
protože element `<PreResources>` nezná, ale to by nemělo ničemu vadit.
