### ISSUE TITLE
ProArc 3.2 - editace xml v editoru připojených objektů

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#481]
V editoru Metadata upravím xml, dám uložit, a zůstanu v editaci xml. 
Když si ale na editaci xml přepnu v editoru připojených objektů ve druhém/třetím sloupci, po uložení upraveného xml mě to hodí do formuláře. Je to tak schválně?

**Comment by krizovj** [comment]
Není to náhodou stejný problém jako tady? https://github.com/proarc/proarc/issues/556

**Comment by luckajirku** [comment]
Řekla bych, že jo. Netuším, proč Ivana zakládala další issue, když už to tady popsané bylo,

**Comment by pavelkocourek** [comment]
Přesunuto : ProArc 3.2 - editace xml v editoru připojených objektů (#481) #26
