### ISSUE TITLE
UI: Filtrování ID záměru

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#482]
Při filtrování ve správě úkolů je možné nastavit sloupci ID a ID záměru parametry "je null" nebo "není je null" (chyba překladu, stejně tak samotná volba filtrování je v české lokalizaci označena jako "filter using").

Zadání těchto filtrů vyvolá neočekávanou chybu, při zobrazení detailů chyby se objeví E404.

Dále vrácení filtru na "obsahuje (default)" chybu neodstraní (obnovení seznamu ji znovu vyvolá) a je třeba zadat do pole ID nějakou hodnotu, teprve poté se chyba znovu nevyvolá.

Vyzkoušeno na:
Firefox 49.0-2.fc24 64bit
Chrome 54.0.2840.59 64bit

**Comment by pokorsky** [comment]
Kontextové menu ve filtrech je nová funkce SmartGWT. Odtud pochází také ty překlady. Pokusím se toto menu vypnout, protože tyto možnosti nejsou implementovány. Stejné menu jsem našel v záměrech, úkolech a historii importů.

ID záměru je klíč. Nastavíte-li ho na null, tak server správně vrátí 404(not found).

**Comment by pokorsky** [comment]
Menu zrušeno. HTTP 404 je akceptována jako prázdný list.
