### ISSUE TITLE
Import - Nefunkční přeskakování v polích číslo strany

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#483]
V obrazovce Import - příprava metadat pro načtení do úložiště v prvním sloupci vlevo dole - Metadata po zadání čísla (písmena) do pole "Číslo strany" a entru (nebo kliknutím na "Uložit") dojde k přepnutí na další soubor, problikne kurzor v poli "Číslo strany" a zmizí. Pro další zápis je nutné najet kurzorem do pole "Číslo strany" .
Mozilla Firefox 49.0.2
Microsoft Edge

**Comment by pokorsky** [comment]
Vyřešeno společně s issue #461.
