### ISSUE TITLE
Jazyk katalogizace změna povinnosti

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#485]
Při zakládání Nového objektu je u pole Language of Cataloging označení R - nepovinné pole, ale pole se chová jako M. Objevuje se hláška o nevyplnění.

**Comment by pokorsky** [comment]
Týká se všech NDK a odvozených formulářů. Podle specifikace by mělo být pole R, tedy nepovinné.

**Comment by pokorsky** [comment]
Díky za patch. Opraveno.
