### ISSUE TITLE
Aleph XServer: XSL transformace vytvoří nevalidní "issuance"

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#486]
Při vytváření nového objektu z aleph-u (zkoušeno z Aleph NKP a Aleph MZK01) dostávám chybu: "Failed to create digital object!"

(např. titul "Brasil" s modelem NDK svazek monografie u Aleph NKP a "Benátky" s modelem NDK svazek monografie u Aleph MZK01)

Logy serveru hlásí: 

Value '' is not facet-valid with respect to enumeration '[continuing, monographic, single unit, multipart monograph, serial, integrating resource]'. It must be a value from the enumeration.

(kompletní výpis logu: https://codeshare.io/ampmk5)

Bylo mi řečeno, že element "issuance" nemusí být vždy v alephu vyplněn, nicméně proarc v tu chvíli titul nenačte, případně neumožní načtení s následným vynucením opravy hodnoty elementu.

Edit:

Chyba se hlásí i u titulů, kde issuance vyplněné je. (např.: ISBN 978-80-87169-34-6 v Aleph MZK01) Titul má vyplněné pole v MARC21: "250 	|a 1. vyd. ", které by mělo odpovídat poli issuance podle MODS.

**Comment by pokorsky** [comment]
Podle [mapování](http://www.loc.gov/standards/mods/mods-mapping-3-5.html) se pole 250 nepoužívá pro plnění elementu `<issuance>`. K tomu je potřeba použít Leader/07.

Problém je zřejmě v použití katalogu Aleph přes XServer, který vrací OAIMARC. První [transformace](https://www.loc.gov/standards/marcxml/xslt/OAIMARC2MARC21slim.xsl) OAIMARC->MARXML vytvoří v MARCXML
```xml
    <leader>       22      4500</leader>
    <controlfield tag="LDR">-----nam-a22------a-450</controlfield>
```
z OAIMARC
```xml
    <fixfield id="LDR">-----nam-a22------a-4500</fixfield>
```
a následná transformace MARXML->MODS pak selže, protože nepočítá s nevalidní hodnotou leader$07=2. Výsledkem je nevalidní `<issuance/>`

Při použití Z39.50 by tento problém neměl nastat.
Testoval jsem http://aleph.nkp.cz/F/?func=direct&doc_number=002380122&local_base=NKC.

**Comment by jkremlacek** [comment]
Potvrzuji, že při Z39.50 chyba nenastává. Chyba je pouze u XServer-u.

**Comment by pokorsky** [comment]
Upravil jsem LoC OAIMARC/MARC21 XSLT. Katalog připojený přes protokol XServer by měl fungovat.
