### ISSUE TITLE
GWT: Dropdown menu neplatné hodnoty

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#487]
Ve správě zařízení při nastavení libovolné hodnoty ze seznamu "Capture device - MA" pokus o uložení vyvolá chybu: 

> Can not deserialize value of type cz.cas.lib.proarc.mix.CaptureDeviceType from String "TRANSMISSION_SCANNER": 
> value not one of declared Enum instance names: [transmission scanner, digital still camera, reflection print scanner, still from video] 
> at [Source: {"ImageCaptureMetadata":{"GeneralCaptureInformation":{"imageProducer":{"value":"MZK"},"captureDevice":{"value":"TRANSMISSION_SCANNER"}},"ScannerCapture":{"scannerManufacturer":{"value":"4DigitalBooks"}}}}; line: 1, column: 112] 
> (through reference chain: cz.cas.lib.proarc.mix.Mix["ImageCaptureMetadata"]->cz.cas.lib.proarc.mix.ImageCaptureMetadataType["GeneralCaptureInformation"]->cz.cas.lib.proarc.mix.GeneralCaptureInformation["captureDevice"]->cz.cas.lib.proarc.mix.TypeOfCaptureDeviceType["value"])

Edit: Stejná chyba nastává při vytváření objektu, který nemá v metadatech vyplněnou položku, která má být obsazena hodnotou enum (v následujícím případě issuance)

viz:

com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type cz.cas.lib.proarc.mods.IssuanceDefinition from String "MONOGRAPHIC": value not one of declared Enum instance names: [integrating resource, serial, monographic, multipart monograph, single unit, continuing]

stacktrace: https://codeshare.io/2p6rVa

Stejně tak chybu vyvolá změna položky s enum hodnotou při editaci metadat, chyba tedy nejspíš bude v GWT.

Použitý prohlížeč: Mozilla Firefox 49.0.2 64bit

**Comment by pokorsky** [comment]
Bylo vyřešeno v rámci issue #480.
