### ISSUE TITLE
Export NDK PSP starého tisku

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#488]
Při exportu starého tisku jako NDK PSP vyskočí chyba:

Caused by: java.lang.IllegalStateException: Unsupported model: model:oldprintpage

Podle Ing. Petra Žabičky by staré tisky měly být exportovatelné jako NDK PSP balíček, nicméně z chyby jsem pochopil, že proarc tuto funkcionalitu neposkytuje.

Export report: https://codeshare.io/GkpDA2

**Comment by pokorsky** [comment]
V požadavcích KNAV na staré tisky (#322) NDK export nebyl. Hlavním důvodem bylo chybějící OCR. Akce `NDK PSP Export` proto není na objektech STT * monografie dostupná. Podle chybové hlášky předpokládám, že jste přidal STT stranu pod NDK titul, což není správný postup jak zpracovat svazek starých tisků.

Pokud máte zájem o tento druh exportu, tak můžete tento požadavek navrhnout vývojovému týmu.
