### ISSUE TITLE
UI: Nefunkční přepnutí jazyku rozhraní

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#492]
Jazyk gui zůstává na výchozí hodnotě (čeština nebo angličtina v případě použití "?locale=en") i po pokusu o přepnutí do druhého jazyku.

Vyzkoušeno na:
Firefox 49.0-2.fc24 64bit
Chrome 54.0.2840.59 64bit

**Comment by pokorsky** [comment]
Opraveno.
