### ISSUE TITLE
Chyba při manuální tvorbě objektu - MODS issuance

### ISSUE THREAD

**Issue by jdobiasovsky** [proarc/proarc#493]
Dobrý den,
přešli jsme na verzi 3.2 a při ukládání dokumentu zobrazí tato chyba:

com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type cz.cas.lib.proarc.mods.IssuanceDefinition from String "MONOGRAPHIC": value not one of declared Enum instance names: [integrating resource, serial, monographic, multipart monograph, single unit, continuing]
 at [Source: {"mods":{"genre":{"value":"volume"}.

Jedná se o rozbalovací menu Issuance. Zkoušel jsem vybrat možnosti monographic, single unit a multipart monograph pokaždé s různými obdobami hlášky. Pokud se v rozbalovacím menu vybere prázdné pole, tak uložení dokumentu (s upozorněním na neplatná data, pole je vyžadováno) proběhne.

**Comment by pokorsky** [comment]
Díky, tohle uteklo při testování. Problém lze jednorázově obejít pomocí XML editoru. Vydáme verzi 3.2.1 s opravou.

**Comment by pokorsky** [comment]
Opraveno.
