### ISSUE TITLE
Při odstranění objektu z úložiště se data nesmažou z Fedory

### ISSUE THREAD

**Issue by jdobiasovsky** [proarc/proarc#497]
Dobrý den,
zjistili jsme že pokud v proarcu odstraníme položku ve správě digitálních objektů z úložiště `menu --> úložiště --> hledat --> odstranit` tak na serveru data zůstanou. 

V administrátorském rozhraní `localhost:8080/fedora/admin` jsou objekty vidět, jejich stav je pouze změněn na "Deleted (D)". Takže se musí mazat manuálně přes toto rozhraní.

Lze nějak nastavit fedoru aby objekty přímo mazala a ne je jenom označovala za smazané? Jde nám hlavně o šetření místa, protože na serveru který používáme ke zpracovávání skenů do Krameria není až tak velká kapacita úložiště.

**Comment by pokorsky** [comment]
Od verze 3.2 lze objekty odstranit úplně i pomocí webového klienta. Viz. požadavek v issue #453.
