### ISSUE TITLE
Zapamatování naposledy vybraného modelu

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#499]
Při odhlášení by si měl ProArc zapamatovat naposledy vybraný model - např. NDK Periodikum, který si uživatel vybral.

**Comment by pokorsky** [comment]
O který formulář konkrétně jde?

**Comment by slapakovai** [comment]
Primárně nám šlo o úložiště - hledat.

**Comment by luckajirku** [comment]
Za nás určitě ne.

**Comment by krizovj** [comment]
K tomu bych tedy měla dotaz. Co se tam zobrazuje vlastně teď? Když zapnu ProArc, tak mi to v úložišti (hledat) vypíše jen články. A mě by zajímalo na základě čeho? Je to proto, že jsem jako poslední objekt založila článek?

**Comment by luckajirku** [comment]
Nabídne se ten model, který máte na prvním místě v seznamu. My takhle máme NDK Per, a STT máme odsunuté na konec, protože je nepoužíváme, a e-články, K4 atp. tam nemáme vůbec. V testovacím incadím když se povídáte, jsou zase na prvním místě STT...

**Comment by krizovj** [comment]
Takže teoreticky by to šlo udělat tak, že se jen prohází pořadí modelů v seznamu?

**Comment by luckajirku** [comment]
Určitě. Jen myslím, že úplně popřehazovat po jednotlivých modelech to nejde, že se mají zachovat ty skupiny a v nich hierarchie, ale dá se popřeházet pořadí skupin (začínat třeba NDK vícedílná monografie), ale třeba mě Lukáš opraví.

**Comment by jkremlacek** [comment]
Sice byl zmíněn Lukáš, ale dovolím si ho zastoupit. Pořadí skupin je momentálně možné určit pomocí pořadí jejich definice v konfiguračním souboru. V rámci skupiny, jak bylo zmíněno, pořadí momentálně měnit nejde. 

Co se týče tohoto issue, tak konfigurovatelnost pořadí v rámci skupiny by neřešila stav, kdy v rámci jedné instalace ProArc-u pracuje více zpracovatelů na různých modelech. (zpracovatel A řeší mapy a chce první mapy a zpracovatel B řeší monografie a chce první monografie)

**Comment by krizovj** [comment]
My jsme to právě chtěli proto, že v jedné instalaci ProArcu zpracováváme jen periodika, takže vždycky potřebujeme periodika. Až přibudou monografie, tak stejně bude lepší mít tam periodika, ptž když udělám záznam monografie, tak už většinou není potřeba se k němu vracet. 
Ale když zpracovávám periodikum na články, tak se pořád vracím k tomu stejnému periodiku. 
Takže pokud nikdo nechce to řešení, že by se zobrazoval poslední vyfiltrovaný model, tak se to vyřeší tímhle. Jako první máme model eČlánek, který není podle standardu, ale až se udělají ty elektronické publikace tak se tenhle model zruší, a na první místě bude NDK periodikum. Tím by to mělo být (alespoň pro nás) vyřešené.

**Comment by jkremlacek** [comment]
Mám tedy připravené řešení pomocí tickboxu, v UI vypadá následovně:

![remembermodel](https://user-images.githubusercontent.com/9445927/38562080-fe3b8252-3cd9-11e8-8fb8-584c5148fc92.png)

Bohužel jej není možné "nalepit" úplně na pravou stranu seznamu modelů (gwt třídí ovládací prvky do tabulky)

Po zakliknutí `zapamatovat` a `hledat` se uloží model do paměti prohlížeče a při příštím otevření (případně F5) se nastaví jako výchozí hodnota.

**Comment by nezbedova** [comment]
Za nás také souhlasíme.
