### ISSUE TITLE
RDFlow - Přidat sloupec do Správa úkolů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#503]
Do obrazovky "Správa úkolů" přidat sloupec "Detail", který bude možné zvolit jako u " Správa záměrů". A hodily by se i sloupce "Rok", Ročník" a "Číslo". Je to nutné pro rychlé rozpoznání úkolů u podzáměrů.

**Comment by nezbedova** [comment]
Přehled možností přidání sloupců:

![obrazek](https://user-images.githubusercontent.com/13831946/123037908-c8890700-d3ef-11eb-8fc9-fd60d62f9b3d.png)

**Comment by nezbedova** [comment]
Správu úkolů nepoužíváme. Zvolili jsme jiný systém práce. Navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě labelu.
