### ISSUE TITLE
RDFlow nestahují se metadata 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#504]
Po založení KNAV Periodika  "Materiál - Fyzická jednotka" pomocí Vybraného katalogu se kromě zdroje nestahují žádné další informace (sigla, signatura..... ).

**Comment by pokorsky** [comment]
Co myslíte tím nestahují? Můžete to popsat konkrétněji?

**Comment by luckajirku** [comment]
Ono se stahují, ale jsou jen v xml. Bylo by potřeba, aby se to hodilo i do formuláře. 
Pole 001 = recordIdentifier
Sigla = physicalLocation
Signatura = shelfLocator

**Comment by pokorsky** [comment]
Pokud jde o extrakci metadat ze staženého MODS, tak dohoda z minulé verze byla jen na čárovém kódu `m:identifier[@type='barcode' and not(@invalid)]`. V této verzi se zatím nic dalšího neplánovalo. Jestli je na tom shoda, tak ty tři pole můžu přidat.

**Comment by MartinRumanek** [comment]
Bylo implementováno.
