### ISSUE TITLE
RDFlow - periodikum zrušení povinnosti vyplnění počtu skenů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#506]
U profilu pro periodika by nemělo být povinné vyplňovat pole "Počet skenů" nebo by to mělo jí překonat.
Nyní se tam nic neukládá viz. #505

**Comment by pokorsky** [comment]
Povinost vyplnění si definujete sama ve workflow.xml. Dodala jste definici

```xml
<task name = "task.scan">
    ....
    <param name="param.scan.numberOfScans" required="true" type="NUMBER" >
    ....
```
Pole je tedy povinné.
