### ISSUE TITLE
RDFlow Periodika blokátory

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#507]
U "Nadzáměru" jde dokončit úkol (skenování), ikdyž u všech jeho  "Podzáměrů" není tento úkol dokončen. 
Chybí blokátor.

**Comment by pokorsky** [comment]
Závislost úkolů z různých záměrů nebyla požadována. Dohodli jsme se na blokování záměrů jako celku. Viz. [zadání](https://docs.google.com/document/d/1kSnV_sh8Ps05QJUGo6lAdmtbXwA01aeBE-DjnP9pBOE/edit?usp=sharing).
