### ISSUE TITLE
RDflow - signatura v tabulce Správa záměrů

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#508]
Se zavedením sloupce Signatura jsme se (myslím) dohodli, že se zruší doplňování signatury na počátek názvu (#384). Teď se tam signatura pořád automaticky doplňuje.

**Comment by pokorsky** [comment]
Ano, je to tak. Změním to.

**Comment by pokorsky** [comment]
Vyřešeno. Signatura se automaticky nepřidává.
