### ISSUE TITLE
RDflow zobrazení signatur ve Správě záměrů

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#509]
Děje se taková zvláštní věc. Zapnu si sloupec Signatura, vidím ho prázdný. Ve chvíli, kdy v záměru, ve kterém jsem, vyplním pole Signatura a uložím, v tabulce správy záměrů se ve sloupci Signatura objeví nejen tahle, ale i signatury dalších záměrů. Když signaturu v tom konkrétním záměru odmažu a dám uložit, vlevo v tabulce se zas signatury (všechny) přestanou ukazovat.

**Comment by pokorsky** [comment]
Výše popsané chování nejsem schopen reprodukovat. V mém případě se signatura uloží a zobrazí se správně v tabulce záměrů. Ve formuláři materiálu, ale zůstává hodnota původní. V konzoli prohlížeče je následující chyba:
```
Exception: com.google.gwt.core.client.JavaScriptException: (TypeError) : _3.selectString is not a function
ConsoleLogger.java:32 TypeError: _3.selectString is not a function
    at _3.isc_RestDataSource_transformResponse (ISC_DataBinding.js:3180)
    at Izl_g$.g5d_g$ [as transformResponse_0_g$] (DataSource.java:4943)
    at Izl_g$.Lzl_g$ [as transformResponse_0_g$] (WorkflowMaterialDataSource.java:201)
```

**Comment by pokorsky** [comment]
Přidána oprava transformace JSON. Snad to vyřeší i ten původní problém.
