### ISSUE TITLE
RDflow - možnost ručně změnit datum (admin)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#510]
Potřebovali bychom mít pro admina možnost změnit datum vytvořeno/změněno ručně.
Vím, že to vypadá divně, a že by to měl generovat systém - ale teď máme třeba dost věcí rozpracovaných, které od ledna nasázíme do RDflow, kde ale je potřeba zachovat data z předchozích tabulek, minimálně proto, aby nám seděly statistiky.
Nebo jak tohle budete řešit v Jenštejně @nezbedova?

**Comment by nezbedova** [comment]
U nás začneme "načisto". Skenují tenké tituly, žádný nezůstane rozdělaný přes Nový rok. Pro tituly, které jsou již naskenované, vytvořím nový profil, takže se začne od grafických úprav. U STT použiji poznámku, kam zapíši stav.

**Comment by pokorsky** [comment]
Obecně tohle (vytvořeno/změněno ručně) do systému nepatří a jsem proti takové účelové změně. Je to informace o záznamu. Loni jsem navrhoval samostatné sloupce pro datum začátku a ukončení záměru. Bylo to odmítnuto jako zbytečné.

**Comment by slapakovai** [comment]
Za mě je možné issue uzavřít.

**Comment by nezbedova** [comment]
Souhlasím s uzavřením issues.
