### ISSUE TITLE
Nelze načíst profil Archivace

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#511]
Po výběru Profilu Archivace nelze použít tlačítrko "Načíst adresář" a tím načíst archivační balíček. Ze všech podsložek balíčku funguje toto tlačítko jen u "RAW", ale načíst nelze, objeví se chyba:

media/vg1-lv1/proarc-test/work_data/users/nezbedova/import/archive_de81872f-1beb-47e5-a107-44d1352127ac_1/de81872f-1beb-47e5-a107-44d1352127ac/RAW/proarc_import/page_0001_e48dda69-90c9-464b-8f01-8a0a02b1a5c2.foxml java.io.FileNotFoundException: Missing archival JP2: /media/vg1-lv1/proarc-test/work_data/users/nezbedova/import/archive_de81872f-1beb-47e5-a107-44d1352127ac_1/de81872f-1beb-47e5-a107-44d1352127ac/RAW/page_0001_e48dda69-90c9-464b-8f01-8a0a02b1a5c2.ac.jp2 at cz.cas.lib.proarc.common.imports.TiffImporter.importArchivalCopy(TiffImporter.java:229) at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:105) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSetImport.java:115) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSets(FileSetImport.java:96) at cz.cas.lib.proarc.common.imports.FileSetImport.start(FileSetImport.java:83) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:210) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:181) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) 

Je to u verze 3.2.1

**Comment by pokorsky** [comment]
Podle chybové hlášky se pokoušíte importovat  podadresář RAW nějakého archivačního balíku. To by fungovat nemělo, protože RAW neobsahuje JP2 soubory.

**Comment by nezbedova** [comment]
Zkusila jsem to, protože nic jiného nefunguje.

**Comment by nezbedova** [comment]
Doplnění:
ve verzei: 3.2.1 jsem u vybraného titulu zadala export: Archivace a vyexportovala tak balíček archive_92d82187-55b8-4717-9330-6e92dc4e9b0d. Ten jsem nahrála na FTP. Tím se tento adresář objevil v obrazovce Import - Výběr adresáře s digitalizovanými daty pro přípravu metadat. Zadala jsem Profil Archivace. Po označení adresáře archive_92d82187-55b8-4717-9330-6e92dc4e9b0d zůstalo tlačítko "Načíst adresář" nefunkční (zamlžené). Rozbalila jsem soubor archive_92d82187-55b8-4717-9330-6e92dc4e9b0d a v něm jsem označila soubor 92d82187-55b8-4717-9330-6e92dc4e9b0d. Tlačítko "Načíst adresář" zůstalo nefunkční (zamlžené). Postupně jsem vyzkoušela všechny vnořené soubora a Tlačítko "Načíst adresář" se prosvítilo a bylo funkční jen u souboru RAW (viz výše), což není správně.
Balíček, na kterém jsem testovala jsem Vám zaslala přes FileSender.

**Comment by pokorsky** [comment]
Díky za balík. Po rozbalení a přesunutí do proarc adresáře import, výběru importního profilu `Archive` a kliknutí na adresář `archive_92d82187-55b8-4717-9330-6e92dc4e9b0d` nebo podadresář `92d82187-55b8-4717-9330-6e92dc4e9b0d`, je tlačítko `Načíst adresář` aktivní. Testováno v prohlížečích Chrome i Firefox. Zkusil jsem to i na testovacím serveru sluzby.

Dohledal jsem algoritmus co rozpoznává archivní balík. Ten hledá v daném adresáři nebo v některém přímém podadresáři soubor `mets.xml`. Pokud se vám tlačítko aktivuje jen na adresáři `RAW`, který obsahuje jen tiff soubory a žádný mets.xml, pak nepoužíváte profil pro archivaci. 

Problém musí být v konfiguraci vašich importních profilů. Ujistěte se, že seznam profilů obsahuje identifikátor `profile.default_archive_import`. Viz. [proarc.cfg.template](https://github.com/proarc/proarc/blob/master/proarc-common/src/main/resources/cz/cas/lib/proarc/common/config/proarc.properties) z wiki Konfigurace.

**Comment by pokorsky** [comment]
S tímto importním balíkem pak souvisí issue #519.

**Comment by SykoraLukas** [comment]
Řešeno přes mail s @nezbedova a panem Dudou. Chyba v konfiguraci proarc.cfg nalezena a opravena.
