### ISSUE TITLE
Chyba při paginování 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#512]
Verze 3.2.1
Při hromadné paginaci stran se zvoleným číslem (např. 1) označí vybraný sken a pak až se čísluje od začátku výběru.
Příklad: Najedu na poslední číslovanou stranu (např. 20), kliknu. Pak označím všechny předchozí strany, které chci číslovat (např. všech 20, až ke straně 1). Nastavím Editovat čísla stran _ Číslo od _ 1. Strana 20 dostane číslo 1, a strany 1 až 19 dostanou čísla 2-20.
V předchozí verzi se čislovalo automaticky "odshora"

**Comment by pokorsky** [comment]
Problém lze zatím obejít označením řady shora.

**Comment by pokorsky** [comment]
Podle http://forums.smartclient.com/forum/smart-gwt-technical-q-a/242318-listgrid-getselectedrecords-returns-records-in-unexpected-order je toto pořadí výběru v tabulce vlastnost a ne chyba SmartGWT. Bude potřeba výběr řádků seřadit před hromadnou paginací.

**Comment by nezbedova** [comment]
Ale v předchozích verzi to šlo tak, jak jsem uvedla a to nám vyhovovalo.

**Comment by pokorsky** [comment]
Přidal jsem podporu seřazení vybraných řádků i pro ostatní tabulky, kde se používá hromadný výběr (importy/metadata, vazby, hledání v úložišti).
