### ISSUE TITLE
CrossRef: export při chybějící úrovni číslo nebo ročník

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#513]
Při exportu do CrossRefu se mi objeví chyba: "Nothing to export!"
Jedná se o titul Knihy a dějiny.
Chyba je pravděpodobně způsobena chybějící úrovní NDK číslo.

Pokud jsou články řazeny přímo pod úroveň ročníku, jako tady u Knihy a dějiny, měl by být při jejich exportu parametr "issue" pro šablonu prázdný a parametr "publication_date" předaný z úrovně ročníku.
Pokud by v hierarchii chyběla úroveň ročníku, bude při exportu prázdný předávaný parametr "volume".

**Comment by pokorsky** [comment]
Problém je nedostatečně popsán. Založil jsem si NDK Periodikum (Knihy a dějiny) + NDK Ročník (2001) + eČlánek(vyplněn jen titul). Crossref export skončil bez chybové hlášky.

Tohle je výsledek z `batch_0000.xml`. Element `<issue>` je správně vynechán a `<publication_date>` obsahuje správně rok vydání. Kde je problém?
```xml
<?xml version="1.0" encoding="utf-8"?>
<doi_batch xmlns="http://www.crossref.org/schema/4.3.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.crossref.org/schema/4.3.6 http://www.crossref.org/schemas/crossref4.3.6.xsd" version="4.3.6">
    <head>
        <doi_batch_id>1c522d3f-9c57-4a54-b7d8-cd009768cc44</doi_batch_id>
        <timestamp>201701231221</timestamp>
        <depositor>
            <depositor_name>Knihovna AV ČR, v. v. i.</depositor_name>
            <email_address>xxx@knav.cz</email_address>
        </depositor>
        <registrant>Knihovna AV ČR, v. v. i.</registrant>
    </head>
    <body>
        <journal>
            <journal_metadata>
                <full_title>Knihy a dějiny</full_title>
                <abbrev_title>Knihy a dějiny</abbrev_title>
                <issn media_type="print">1210-8510</issn>
            </journal_metadata>
            <journal_issue>
                <publication_date media_type="print">
                    <year>2001</year>
                </publication_date>
                <journal_volume>
                    <volume>1</volume>
                </journal_volume>
            </journal_issue>
        </journal>
    </body>
</doi_batch>
```

**Comment by pokorsky** [comment]
Ivano na schůzce jsi říkala, že export je v pořádku. Je to tak?

**Comment by slapakovai** [comment]
Ve verzi 3.2 už funguje. Zavírám issue.
