### ISSUE TITLE
Úprava hlavičky mets - ROLE ="ARCHIVIST"

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#515]
Provést takovou úpravu, aby v hlavičce souborů <mets:metsHdr> byly údaje o vlastníkovi <mets:agent ROLE ="ARCHIVIST" ...>

**Comment by nezbedova** [comment]
Projeví se tato oprava i c souboru info.xml v hodnotě <creator>?

**Comment by SykoraLukas** [comment]
Ano, nová verze ProArcu 3.4 již nemá nastavenou defaulní hodnotu "Proarc", ale používá hodnotu nastavenou v konfiguračním souboru v poli "export.ndk.agent.creator".
