### ISSUE TITLE
Záznam události u EVT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#517]
V adm_mets u EVT zaznamenávat v <premis:eventType> i události: capture, migration, derivation, deletion.

**Comment by nezbedova** [comment]
Dle akceptačního protokolu pro VISK7 v roce 2016 to je méně závažný nedostatek, který přímo nebrání dlouhodobému uchování dat, ale má se vzít do úvahy při dalším zpracování.

**Comment by SykoraLukas** [comment]
e verzi 3.3 se generují pouze 3 eventy (capture/digitalization, migration/MC_creation a capture/XML_creation). Popisek těchto eventů (označováno jako eventDetail např.: capture/digitalization) se skládají ze 2 částí (eventType = např.: capture a detail = např.: digitalization, oddělené lomítkem). V exportovaném NDK balíčku se uvádí obě tyto hodnoty - eventType i eventDetail. ProArc ale jako eventType nastavuje napevno hodnotu "derivation". Potom se stává, že eventType = derivation ale eventDetail = capture/digitalization. Což je špatně, neboť eventDetail má je upřesnit eventType. Proto jsem nejprve opravil tuto chybu.
![image](https://user-images.githubusercontent.com/27210823/29285988-ba99fdae-8130-11e7-880d-382df876c8e9.png)

Kromě těchto 3 událostí je potřeba doplnit ještě zbylé 2 eventy, které je možné generovat. Jedná se o derivation/UC_capture a capture/TXT_creation. Hodnoty všech eventů vychází ze standardů NDK. Rozšířil jsem generování NDK balíčku o tyto 2 eventDetaily.

Ve 2 odstavcích výše používám slovo event - ve skutečnosti se jedná o eventDetaily, neboť se skládají jak z eventTypu tak detailu.

**Comment by SykoraLukas** [comment]
Specifikaci k tomuto bodu zda: https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.5j2bhfwz01qu

**Comment by pokorsky** [comment]
Přidáno.
