### ISSUE TITLE
Proarc vyhazuje HTTP 500 v případě lokální kompilace

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#521]
V případě, že zkompiluji zdrojové soubory a následně nasadím aplikaci, tak dostávám:

https://gist.github.com/jkremlacek/bba8df49216f8aa3c3140a97c469854c

(s tím, že back-end funguje dál - fedora loguje komunikaci s proarc-em, není možné pouze přistoupit na front-end)

pokud je použit předsestavený .war release 3.2.1 nebo 3.3 beta, tak chyba nenastává. Kompilace probíhá vpořádku bez chyb.

Zvláštní stav nastává, pokud je ke zkompilování použit s2i, který vyprodukuje funkční .war, ovšem pokud je na výsledném docker obraze (obsahuje systém na kterém proběhla kompilace) kompilace spuštěna znovu, tak vyprodukuje nefunkční .war .

Kompilaci jsem zkoušel na systému s Ubuntu 16.04LTS a Fedora 24 (kde výsledný .war nefungoval) a CentOS 7 (viz předposlední odstavec)

**Comment by fstepanovsky** [comment]
Nepodařilo se mi zreplikovat, dále nerelevantní, pokud problém opět nastane, může se issue otevřít.
