### ISSUE TITLE
Špatný text v logu u chyby souboru ALTO

### ISSUE THREAD

**Issue by mjtecka** [proarc/proarc#523]
https://github.com/proarc/proarc/blob/6336d460f58c001c4cf3906daa465d7f8de7bb89/proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/TiffImporter.java#L198

Je:
 originalFilename + config.getPlainOcrFileSuffix()).toString());
mělo by asi být:
 originalFilename + config.getAltoFileSuffix()).toString());

**Comment by jkremlacek** [comment]
Zkontrolováno, opraveno.
