### ISSUE TITLE
Rozšíření konfigurace katalogu Aleph - XServer

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#525]
Proarc momentálně neumožňuje vyhledávání záznamů pomocí nezkrácené signatury (parametr sig).

Navrhujeme upravit AlephXServer.java, aby z konfiguračního souboru proarc.cfg bylo možné načítat nové a případně měnit stávající parametry pro vyhledávání.

V rámci zachování kompatibility by toto nastavení konfiguračního souboru bylo nepovinné, tedy v případě neuvedení by vyhledávání přes Aleph bylo bezezměny (barcode, ccnb, issn, isbn, signature).

Edit: Čekáme na vyjádření, zda-li můžeme začít s implementací.

**Comment by pavelkocourek** [comment]
Určitě. SIG bude další položkou comba.
Prosím ostatní uživatele, aby případně navrhli ještě další pole.

**Comment by slapakovai** [comment]
Jenom upozorňuju, že teď je u každého zdrojového katalogu jiné nastavení z jakých polí se dá hledat. Tedy nejen barcode, ccnb, issn, isbn, signature. Tak aby se to tím nějak nerozbilo.

**Comment by jkremlacek** [comment]
Pokud myslíte jiné typy katalogu (Z39.50, OAI ...), tak ty zůstanou bezezměny - jejich konfigurace je oddělená.

**Comment by pokorsky** [comment]
Zdokumentováno viz. https://github.com/proarc/proarc/wiki/Konfigurace#aleph---xserver
@jkremlacek díky za patch.
