### ISSUE TITLE
Možnost importu jpg/jp2

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#526]
Při importu dat do Proarc-u je nyní možné načítat pouze .tiff (+ .jp2). V MZK jsou některá data dostupná pouze ve formátu .jpg nebo .jp2 .

Nabízí se několik možností řešení:

1. konverze vstupního souboru na .tiff (problém se zachováním kvality při konverzi), který bude následně zpracován současným importním procesem (+ problém, kdy v RAW nebude uložen původní sken ale jeho zkonvertovaná verze)

2. konverze a zpracování vstupního souboru podle typu:
- jpg: 
konverze na .jp2 pro NDK_ARCHIVAL a NDK_USER, uložení .jpg do datastream-u FULL a RAW (datastream RAW by neměl jednotný formát - možná komplikace při dalším zpracování) + změna velikosti pro PREVIEW ,THUMBNAIL
- jp2:
změna velikosti pro NDK_ARCHIVAL a NDK_USER, uložení .jp2 do RAW (opět problém s rozdílným formátem) + konverze na .jpg pro PREVIEW, THUMBNAIL a FULL

Čekáme na vyjádření, která varianta by byla vhodnější, případně jiné řešení.

**Comment by pavelkocourek** [comment]
víte zda-li bude při konverzích dostatečná kvalita pro NKD? (validace obrazových souborů)

**Comment by jkremlacek** [comment]
Pokusíme se sestavit reprezentativní vzorek dat, která máme ve zmíněných formátech a na nich ověříme, zda-li bude dodržen požadavek na kvalitu.

**Comment by nezbedova** [comment]
Na možnost použití formátu jpg je již založené  issues 89.

**Comment by jkremlacek** [comment]
Pokud bychom import jpg/jp2 řešili připojením na stávající proces importu (viz varianta 1), pak konverze by byly řešeny následovně:

- **jpg malé** - GraphicsMagick (`gm convert -compress none`)
- **jpg velké** (mapy, řádově stovky MB) - VIPS (`batch_image_convert`)
- **jp2** - Kakadu (`kdu_expand`)

Všechny výše zmíněné konverze jsou bezeztrátové (ověřeno pomocí `gm compare -metric PSNR`, která vracela hodnotu inf pro všechny barevné složky).

Zbývalo by tedy rozhodnout, který typ souboru by se ukládal do datastreamu RAW (podle definice má obsahovat původní digitální obsah objektu). Intuitivně se nabízí uložit původní verzi (tj. jpg/jp2) - došlo by tím i k úspoře místa na úložišti, ovšem nevím, zda-li se jinde nepočítá s tím, že RAW bude vždy obsahovat tiff.

**Comment by jkremlacek** [comment]
Po merg-i do hlavní větve bude potřeba do wiki přidat ukázku nastavení procesů v `proarc.cfg `:

```
#------------------------------ Nastaveni konvertoru pro JPEG a JPEG 2000

import.jpg_small_convertor.processor=conv_sjpg
import.jpg_large_convertor.processor=conv_ljpg
import.jp2_convertor.processor=conv_jp2

processor.conv_sjpg.type=gm
processor.conv_sjpg.exec=gm
processor.conv_sjpg.arg=convert
processor.conv_sjpg.arg=-compress
processor.conv_sjpg.arg=none

processor.conv_ljpg.type=batch_image_convert
processor.conv_ljpg.exec=batch_image_convert
processor.conv_ljpg.arg=tiff

processor.conv_jp2.type=kdu_expand
processor.conv_jp2.exec=kdu_expand
```

**Comment by pokorsky** [comment]
Datastream RAW nemusí obsahovt TIFF. Jen je potřeba správně nastavit MIME type datastreamu.

Použité nástroje by měly být zdokumentovány na wiki. Alespoň odkazy jak instalovat a seznam parametrů. Díky

**Comment by jkremlacek** [comment]
Přidáno do [wiki](https://github.com/proarc/proarc/wiki/Konfigurace#konverze-vstupn%C3%ADch-obrazov%C3%BDch-dat).

**Comment by pokorsky** [comment]
Jen pro úplnost doplním i zde. Byla implementována varianta 2, tedy originální obrázek se v systému neuloží a jako původní sken se použije nově vytvořený TIFF. Pak už se pokračuje podle daného profilu jako dosud (NDK nebo něco jiného). Konfigurace je popsána na [wiki](https://github.com/proarc/proarc/wiki/Konfigurace#konverze-vstupn%C3%ADch-obrazov%C3%BDch-dat-bez-origin%C3%A1lu-tiff).

**Comment by nezbedova** [comment]
Zkusila jsem do testovací verze 3.4-beta nahrát jpg a jp2. Proces proběhne, ale v obrazovce Import- Příprava metadat se nezobrazí náhledy skenů.
Testováno v Mozille.

**Comment by jkremlacek** [comment]
V ostatních typech obrazových dat obrázky jsou nebo jsou také prázdné?

**Comment by nezbedova** [comment]
Tiff se mi nahraje.

**Comment by jkremlacek** [comment]
Špatně jsem formuloval dotaz: V rámci nahrání jpg/jp2 je prázdný pouze náhled, nebo i ostatní typy obrázků? (archivní kopie apod.)

**Comment by nezbedova** [comment]
Nevidím nic. PrScn posílám e-mailem v příloze.

**Comment by jkremlacek** [comment]
Skeny se nezpracují, protože není nastaven konvertor jpg/jp2 v `proarc.cfg`.

Uživatel by každopádně neměl být v tomto případě přesměrován do přípravy metadat, opravím aby namísto toho byla vyhozena chyba.

**Comment by mduda100871** [comment]
Nastaveno v testovaci instanci ProArcu.

MD

**Comment by jkremlacek** [comment]
V případě chybějící definice konvertoru v `proarc.cfg` je nyní vyvolána chyba namísto původního přesměrování do přípravy metadat.
