### ISSUE TITLE
Kontrola repozitáře pomocí Travis CI

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#527]
Vzhledem k nemalému množství externích závislostí by bylo dobré zvážit nasazení Travis CI do repozitáře, aby bylo možné snadno ověřit, že je kód sestavitelný na konkrétní konfiguraci systému a procházejí všechny testy.

Příkladem je knihovna SmartGWT, kde jsou z webu isomorphic náhodně odebírány starší buildy a již dvakrát byla smazána verze, kterou využívá Proarc - automatická pravidelná kontrola pomocí Travis CI by tento problém nalezla a ohlásila.

konkrétní issue spojené s tímto problémem: #522, #521, commit 34e2f53.

**Comment by pavelkocourek** [comment]
Prima, zkusme/te to.

**Comment by jkremlacek** [comment]
Aplikace musí být autorizována vlastníkem repozitáře https://github.com/orgs/proarc/people , požadavek jsem právě nechal odeslat.

Co se týče nasazení, tak se jedná o zásah do master větve, kterou chtěl mít pod kontrolou @pokorsky . Je tedy třeba rozhodnout, kdo provede nasazení.

**Comment by pokorsky** [comment]
Jakube jestli tomu dobře rozumím, tak současný `travis.yml` pouze spustí `mvn install` a `test`.
Ohledně SmartGWT by bylo potřeba spustit `mvn com.isomorphic:isc-maven-plugin:1.1.1:install` s patřičnými parametry viz. README. To určitě nechceme dělat v rámci základního `mvn install`.

Potom jde o některé knihovny, které nejsou v žádném repository a nemáme oprávnění je do veřejné repository přidávat. Ty bychom tam potřebovali dostat jiným způsobem.

CI by se hodil i protesty PR. Přidávám @MartinRumanek pro info.

**Comment by MartinRumanek** [comment]
Ten travis.yml co je teď od Kuby na moravianlibrary je jenom testovací.

Instalace SmartGWT pluginu se dá zadefinovat v sekci `before_install`.

Knihovny se dají hodit do speciální branch (případně repository, to by bylo asi lepší) na GitHubu v pom.xml se pak se zadefinuje repository nějak takto:
```
<repository>
  <id>proarc-mvn-repo</id>
    <url>https://raw.github.com/proarc/proarc/mvn-repo/</url>
    <snapshots>
           <enabled>true</enabled>
    </snapshots>
</repository>
```

Částečně by se na Travisu daly rozběhat i integrační testy nad Fedorou. Travis umí pustit docker kontejner (a docker image pro Fedoru už máme). Nicméně Travis neumí připojit datové volumy, takže se nedá pracovat s externě referencovanými soubory. Na podobný problém narazil Kuba tady https://github.com/proarc/proarc/issues/560.

**Comment by pokorsky** [comment]
No github repository máme na https://github.com/proarc/proarc.mvnrepo, ale nevidím jak to řeší problém s oprávněním šíření takového kódu. A bez toho to asi nemá smysl. Myslím, že největší problém byl se závislostmi img-support. To by šlo obejít nahrazením za ImageMagic i když by to byla další povinná platformní závislost.

To není dostupný ani java.temp folder nebo jde čistě o fedora ingest? Podle komentářů k jiným platformám by temp fungovat měl.

CI server by se určitě pro více vývojářů hodil. Dřív jsem měl zprovozněný neveřejný Jenkins.

**Comment by MartinRumanek** [comment]
Aha, problém je s licencí. Myslel jsem, že veřejným repository myslíš maven central a něco podobného.

Dalo by se to obejít nějakým skriptem např. takto https://github.com/moravianlibrary/s2i-proarc/blob/master/assemble#L25-L38 (dávné pokusy s MZK Openshiftem).

>To není dostupný ani java.temp folder nebo jde čistě o fedora ingest? Podle komentářů k jiným platformám by temp fungovat měl.

Ano, jde čistě jen o Fedora ingest. Teda za situace kdyby se Fedora spouštěla jako Docker image (Travis ty docker volume neumí https://github.com/travis-ci/worker/issues/171).  Možná to jde řešit jinak, nemám s tím zkušenost.

> CI server by se určitě pro více vývojářů hodil. Dřív jsem měl zprovozněný neveřejný Jenkins.


S tím jsem si taky kdysi hrál. Má těch možností víc, ale musel by ho někdo udržovat...

**Comment by pokorsky** [comment]
> Dalo by se to obejít nějakým skriptem např. takto https://github.com/moravianlibrary/s2i-proarc/blob/master/assemble#L25-L38 (dávné pokusy s MZK Openshiftem).

Ano tohle jsem přesně myslel. V tom případě použití Travis CI nic nebrání. Povolil jsem přístup ke git repository.

**Comment by jkremlacek** [comment]
Ukázalo se že některé testy nedostatečně čistí DB před spuštěním. Chyba se projevovala selháváním testů na Travis CI, kde docházelo ke spouštění testů v jiném pořadí než na lokálním systému.

Chyba je řešena v rámci #720.
