### ISSUE TITLE
GUI - rozlišení oddílů v rámci formuláře

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#529]
Jednotlivé oddíly formulářů (např.: editace metadat, editace zařízení) jsou ohraničeny jednotně barvou `rgb(22, 95, 167)` a jsou umístěny s malým rozestupem - vizuálně splývají. 

Bylo by vhodné zvážit barevné - případně jiné rozlišení oddílů, aby bylo zřetelnější, který prvek patří do kterého oddílu a zároveň byl formulář přehlednější.

**Comment by pavelkocourek** [comment]
Přesunuto : GUI - rozlišení oddílů v rámci formuláře (#529) #24
