### ISSUE TITLE
Jméno uživatele musí mít minimálně 5 znaků (?)

### ISSUE THREAD

**Issue by mjtecka** [proarc/proarc#530]
Zkoušel jsem v "menu"->"Uživatelé"-> "Nový" vytvořit uživatele "jdoe":

![image](https://cloud.githubusercontent.com/assets/11203453/23840280/53dfeb38-07a4-11e7-914a-82b37b5656ef.png)

Dostával jsem hlášku "neplatná hodnota". Podařilo se mi nicméně vytvořit uživatele "jodoe" a "jdoed" => uživatelské jméno vypadá být omezeno na minimum 5 znaků?

Tooltip nicméně říká, že uživatelské jméno musí odpovídat šabloně [a-z][a-z0-9]* ...

**Comment by FoxKyong** [comment]
Taky mám ten problém. Uživatelské jména vytváříme normálně podle jména a krátší nejdou, tak se musí nahrazovat.

**Comment by jkremlacek** [comment]
Kontrola uživatelského jména je provedena pomocí [regulárního výrazu](https://github.com/proarc/proarc/blob/master/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/UsersView.java#L207) "[a-z][a-z0-9]{4,}", text nápovědy tedy neodpovídá.

Pokud je potřeba umožnění kratších uživatelských jmen, pak je buď nutné schválení úpravy vývojovou skupinou, nebo vytvoření vlastního forku a nahrazení čísla ve složených závorkách požadovanou minimální délkou uživatelského jména - 1

**Comment by FoxKyong** [comment]
Tak to by schválit mohli, tohle se celkem hodí a je to lepší, než mít zrovna omezení na minimální délku tak veliké, když jsou normálně jména s délkou 3 znaky.

**Comment by slapakovai** [comment]
Já s tím nemám problém, prosím ostatní členy vývojového týmu o vyjádření.

**Comment by nezbedova** [comment]
Souhlasím s navrhovanou změnou.

**Comment by luckajirku** [comment]
za nás OK

**Comment by jkremlacek** [comment]
Požadovaná délka uživatelského jména snížena na 3 znaky. Upravena nápověda, aby odpovídala požadavkům.

**Comment by slapakovai** [comment]
Po konzultaci s M. Dudou navrhujeme za KNAV, aby minimální počet znaků v uživatelském jméně i v hesle byl konfigurovatelný správcem. Pokud nebude délka uživatelského jména konfigurovatelná, tak je potřeba zachovat současnou minimální délku 5 znaků.
Prosím o přeprogramování.

**Comment by jkremlacek** [comment]
V rámci tohoto issue jsem opravil text nápovědy, aby odpovídal požadavku na délku uživatelského jména.

Konfigurovatelnost požadované délky uživatelského jména/hesla je složitější úprava, která bude vyžadovat upřesnění v případě, že o ní bude vývojový tým stát. 

Mezi upřesňujícími požadavky by určitě mělo být:

- chování aplikace v případě již existujícího účtu s nevalidním username
(př: spuštění aplikace s min. délkou username 3, vytvoření uživatele a následné spuštění aplikace s min. délkou username 5 - uživateli s délkou username 3 se nepůjde přihlásit, protože nesplňuje nové požadavky a stejně tak nemá možnost si uživatelské jméno změnit)
- stejný případ pro heslo

Případná implementace by také nevyhnutelně znamenala malé zpomalení přihlášení (před přihlášením by si aplikace musela zjistit jaká je požadovaná délka jména a hesla)

**Comment by MartinRumanek** [comment]
Tooltip upraven, Původní issue je tímto vyřešené. Konfigurovatelná délka hesla/loginu se řeší v jiném issue https://github.com/proarc/proarc/issues/539
