### ISSUE TITLE
Není možné odstranit uživatele

### ISSUE THREAD

**Issue by mjtecka** [proarc/proarc#531]
V aplikaci není možné odstranit uživatele (ani když jsem přihlášený jako "proarc").

... nebo jsem alespoň takovou možnost nenašel.

(ProArc 3.2.1)

**Comment by MartinRumanek** [comment]
To je schválně, Proarc je archivační systém a mazat uživatele, kteří mají zpracované balíky není vhodné. 

Pokud by se mělo něco na ten způsob implementovat, tak navrhuji něco jako zablokování uživatele (znemožnění přihlášení). Zda je tato funkcionalita potřebná, nechám zvážit výojový tým.

**Comment by mjtecka** [comment]
Díky za odpověď:-)

Přijde mi to neintuitivní a líbilo by se mi, kdybych na to byl při tvorbě nových uživatelů nějak jemně upozorněn... člověk si testuje funkcionalitu a najednou má spoustu falešných uživatelů a nemůže se jich (jednoduše) zbavit ;-)

Nějaká funkcionalita "blokování", nebo bych tomu spíš říkal "deaktivace", kdy by se uživatel přesunul vyjmul z aktivních uživatelů a přesunul do skupiny neaktivních uživatelů by mi celkem dávala smysl - řekl bych, že uživatelé se budou měnit a s už neaktivními bude potřeba něco udělat. Bylo by taky asi fajn mít možnost rozlišit mezi aktivními a neaktivními uživateli. A deaktivovaný uživatel by teda měl mít možnost se zase aktivovat... pokud by se tedy do téhle problematiky stálo za to nějak víc pouštět.
