### ISSUE TITLE
STT export METS balíku

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#532]
Pro import STT zpracovaných v ProArc-u do Krameria MZK současné řešení v podobě exportu do K4 balíku nestačí, protože na imageserver-u MZK jsou skeny uchovávány v jediné kopii ve formátu jp2.

Export do K4, který ProArc momentálně nabízí, exportuje datastream-y full, thumb a preview s obsahem v elementu binaryContent.

Pro zpracování tohoto balíku by byl tedy nutný další nástroj, který by vzal export skenů, konvertoval je do jp2, podle signatury z FOXML je uložil na imageserver a do FOXML uložil cestu k obrázku na imageserver-u do patřičných datastreamů.  

Jako jednodušší varianta se nabízí umožnění exportu METS balíku, jako je tomu u NDK modelů. Pro zpracovaní tohoto balíku je již připravený proces pro umístění na imageserver a uložení do krameria a nebylo by tedy nutné vytvářet mírně upravený duplikát tohoto procesu.

**Comment by SykoraLukas** [comment]
Implementováno ve [verzi 3.5.6](https://github.com/proarc/proarc/releases/tag/v3.5.6)
