### ISSUE TITLE
RDflow - možnost měnit výšku a šířku sloupců

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#533]
Umožnit ručně měnit výšku a šířku sloupců všude v RDflow, stejně jako je to v Import-Příprava metadat pro načtení do úložiště.
ProArc by si měl pamatovat nastavení pro konkrétního uživatele i po odhlášení.

**Comment by pokorsky** [comment]
Nastavení je uloženo v rámci daného prohlížeče.

**Comment by nezbedova** [comment]
Zkusila jsem do testovací verze 3.4-beta nahrát jpg a jp2. Proces proběhne, ale v obrazovce Import- Příprava metadat se nezobrazí náhledy skenů.
Testováno v Mozille.

**Comment by MartinRumanek** [comment]
Prosím, ke kterému issue tento komentář patří? V tomto se řeší něco jiného.

**Comment by nezbedova** [comment]
Omlouvám se. Patří to do: Možnost importu jpg/jp2 #526. Připsala jsem to tam.
