### ISSUE TITLE
přidání PDF k dalším modelům

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#534]
Prosím o přidání modelu eMonografie, ke kterému bude možnost připojovat plný text ve formátu pdf.
Formulář pro metadata bude stejný jako NDK Svazek monografie.
Připojení plných textů ve formátu pdf bude probíhat stejně jako u eČlánku - nahráním souboru v editoru digitalizovaných dat.
Nebude možné dělat NDK export pro tento model.

**Comment by nezbedova** [comment]
O tento model bychom také měli zájem.

**Comment by slapakovai** [comment]
Na rozmyšlení pro ostatní instituce je:
jaké všechny modely by měly takto fungovat - např. vícesvazková monografie, číslo periodika, ročník periodika, příloha,...

**Comment by zdenekhruska** [comment]
Dobrý den, 
v MZK určitě uvítáme všechny tyto modely:
- číslo periodika
- ročník periodika 
- příloha
- vícesvazková monografie

**Comment by nezbedova** [comment]
Dobrý den,
    od 3. 7. do 21. 7. mám dovolenou. V případě potřeby se, prosím, obracejte na p. Polednovou (tel. 286 851 955, e-mail: 
polednova@knav.cz), která mne v té době bude zastupovat.



Děkuji za pochopení

S pozdravem

Martina Nezbedová
    
    
    -- 
Mgr. Martina Nezbedová
Digitalizační centrum
Knihovna AV ČR, v. v. i.
9. května 26
250 73 Jenštejn
Tel: 286 851 955
E-mail: nezbedova@knav.cz

**Comment by SykoraLukas** [comment]
Bude řešeno vrámci naového standardu NDK eDokumenty.
