### ISSUE TITLE
Nepřepnutí do základního okna  Uložiště- Hledat

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#537]
Při akci Vybrat nadřazený objekt se při uložení nepřepne okno do základního pohledu Úložiště hledat, stále tam visí název vybraného objektu a pod tím tlačítko zrušit.

**Comment by nezbedova** [comment]
Tato chyba zpomaluje práci. Ve starších verzích fungovalo automatické přepnutí. Viz. #105

**Comment by SykoraLukas** [comment]
Bude to takhle vyhovovat?
![issue 537](https://user-images.githubusercontent.com/27210823/36900167-754f2d20-1e22-11e8-834f-ca0e5ed86029.gif)

**Comment by SmejkalovaAnna** [comment]
Jasně, to vypadá tak, jak by asi mělo.
