### ISSUE TITLE
Vybrat nadřazený objekt - Zrušit - chybná hláška

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#538]
Pokud vyberu v základním okně Vybrat nařazený objekt, vyberu ho, ale neuložím a požiji tlačítko Zrušit pod názvem vybraného objektu, objeví se hláška Uloženo a nepřepne se okno do základního nastavení Úložiště - hledat.

**Comment by SykoraLukas** [comment]
Jakou verzi ProArcu prosím používáte? V nové verzi (3.3) se tato chyba po nasimulování vašeho postupu již neprojevuje.

**Comment by SmejkalovaAnna** [comment]
mame jeste tu starou, 3.3 budeme mit asi pristi tyden, tak ja pockam...

Anna Smejkalova




Dne 24.5.2017 v 10:32 SykoraLukas napsal(a):

**Comment by SykoraLukas** [comment]
@SmejkalovaAnna pořád se chyba projevuje?

**Comment by SmejkalovaAnna** [comment]
Už se neobjeví Uloženo, ale po klepnutí na Zrušit stejně nezmizí okýnko Nadřazený objekt - vyberte atd. s tlačítkem Zrušit. Čekala bych, že to zmizí celé, aniž bych musela zas dávat Uložiště - Hledat.

**Comment by SykoraLukas** [comment]
Tlačítko zrušit zde není ve smyslu odejít, ale slouží k následujícímu účelu.
Mám NDK Svazek monografie, která má napojený nadřazený objekt. Pokud chci toto napojení zrušit, najdu v okně **Hledat** požadovaný NDK Svazek Monografie a kliknu na **Nadřazený objekt**. Poté kliknu na tlačítko **Zrušit**, které mi zruší vazbu mezi NDK Svazkem Monografie a NDK Vícesvazkovou Monografií. Aby se tato změna (zrušení napojení) uložila, musím ještě kliknout na tlačítko uložit.

**Comment by SmejkalovaAnna** [comment]
Ahá,  tak to jsem vážně netušila. To je zajímavá informace, v tom případě zavřete issue a nechte to, jak je.
