### ISSUE TITLE
Zvýšení bezpečnosti při přihlašování

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#539]
Přidat možnost konfigurace minimální délky hesla při přihlašování.
Přidat captchu při přihlašování.

**Comment by MartinRumanek** [comment]
Minimální délka hesla je určitě rozumná. Ale captchu nedoporučuji, ta už je překonaná - je uživatelsky nepřívětívá a přínos k bezpečnosti je sporný.

**Comment by pokorsky** [comment]
Souhlas, captcha bych v rámci tohoto issue neřešil. Prosím zvažte jestli je
konfigurovatelnost jen minimální délky hesla skutečně nezbytná. Původních 5
znaků bylo myslím dostatečných.

Výhodou delšího jména je i jistá samopopisnost v generovaném balíku, který
by měl jít do LTP.

Kombinací příjmení a jména se lze na 5 znaků snadno dostat.

On May 20, 2017 09:12, "Martin Rumanek" <notifications@github.com> wrote:

Minimální délka hesla je určitě rozumná. Ale captchu nedoporučuji, ta už je
překonaná - je uživatelsky nepřívětívá a přínos k bezpečnosti je sporný.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/proarc/proarc/issues/539#issuecomment-302856195>, or mute
the thread

**Comment by MartinRumanek** [comment]
Ano, obecně je lepší se držet principu "konvence má přednost před konfigurací". 

Do konfigurace patří ideálně pouze věci, které se skutečně liší mezi institucemi. Bezpečný Proarc předpokládám chtějí všechny instituce, takže pokud chcete prodloužit délku hesla, udělejme to pro všechny instalace stejně.

pozn.: Tato politika by byla vynucována pouze pro nově vytvořená hesla.

**Comment by slapakovai** [comment]
Náš správce chce jít co nejbezpečnější cestou, takže proto chceme zvýšit minimální délku hesla. Na druhou stranu nechceme používání ProArcu ztížit ostatním institucím - proto ta konfigurovatelnost.
Ad captcha - to se musí vyjádřit Martin, proč ji tam chtěl a jestli je to nutné.
Prosím @mduda100871 o vyjádření k issue.

**Comment by mduda100871** [comment]
Zdravim,
rad bych upozornil, ze tato iniciativa rozhodne nevzesla z me strany, ale naopak jsem byl dotazan na muj nazor. Pokud je mi znamo, tak cely problem/spor vyvolal pozadavek nektere knihovny, ze chteji mit moznost kratsiho uzivatelskeho jmena (napr. 3 znaky) nez pet znaku. Nasledne se diskuse prenesla i na hesla. Muj nazor je takovy, ze cim kratsi delka jmena/hesla, tim vetsi riziko, ze to nekdo prolomi slovnikovym utokem. Zejmena pokud ProArc vystavujeme v pripade OZC do internetu.

Proto jsem se vyjadril v tom smyslu, ze bych nesel u jmena pod pet (resp. osm) znaku a u hesla pod osm znaku. Take jsem doporucil uvazit vicestupnovou autentizaci, napr. pomoci jednorazoveho kodu zaslaneho mailem nebo sms. Po tomto vyjadreni se strhl odpor ve smyslu, ze takto "komplikovane" prihlasovani bude uzivatele otravovat (no jasne, chceme to bezpecne, ale nechce se nam pro to neco obetovat).

Jako kompromisni jsem tedy navrhl kombinaci moznosti konfiguracniho nastaveni (propertou) delky jmena/hesla s nejakou pevne danou dolni hranici u jmena (napr. prave ty pozadovane tri znaky) a u hesla pet znaku. Toto nasledne doplnit prave napr. captchou (rozhodne na ni netrvam, prosim nepodsouvat mi neco, co jsem nerekl, dekuji), ktera by byla aktivovana napr. po prvnim neuspesnem pokusu o prihlaseni.

Dalsi alternativou (v kombinaci se silnejsimi hesly) je nasazeni banovaciho nastroje, napr. fail2ban, ktery parsuje systemove logy na pokusy o opakovane neuspesne prihlaseni a v pripade pozitivniho nalezu, zablokuje zdrojou IP utocnika na predem definovany cas. Protoze ProArc zrejme pouziva vlastni autentizacni mechanismus, bylo by asi potreba napsat prislusny modul/regularni vyraz pro fail2ban, aby prislusnemu logu "rozumel".

Vyssi level ochrany muze take predstavovat shibboletizace ProArcu, nicmene si nejsem jisty, zda-li to v tomto lokalnim nasazeni dava smysl.

Muj zaver - uzivatele si nejprve musi ujasnit, co vlastne chteji (po tom minulem jednani o tom zacinam pochybovat), zda-li vyssi bezpecnost, nebo neprimereny komfort.

Vic k tomu nemam v teto chvili co dodat, MD

**Comment by MartinRumanek** [comment]
>  Protoze ProArc zrejme pouziva vlastni autentizacni mechanismus, bylo by asi potreba napsat prislusny modul/regularni vyraz pro fail2ban, aby prislusnemu logu "rozumel".

Toto je snadné a přitom účinné řešení, v případě potřeby můžeme příslušný log drobně upravit :-)

> Vyssi level ochrany muze take predstavovat shibboletizace ProArcu, nicmene si nejsem jisty, zda-li to v tomto lokalnim nasazeni dava smysl.

Shibboletizaci Proarcu by ocenila i MZK, původní Medit jsme měli připojený na hesla z domény (sice přes LDAP, ale to je jedno). Nicméně implementace něčeho takového není jednoduchá a teď na to asi není prostor.
______
Aktuálně bych nejradši šel vámi navřzenou cestou - delší heslo a fail2ban.

login: 5 znaků (login není tajná informace, ale existují jiné argumenty proč mít login delší a popisnější)
heslo: 8 znaků

Není důvod to dávat do property. Všechny instituce chtějí mít proarc bezpečný a 5 znaků je už dnes málo. Kromě toho je možné přihlašovací formulář opravit tak, aby bylo heslo zapamatovatelné v prohlížeči.

**Comment by mduda100871** [comment]
Z me strany neni asi zasadni problem. Na serveru uz mam fail2ban nasazeny, ale banuju jen pokusy o prolamovani ftp a ssh (to nevystavuji ven, ale kvuli pripadnym internim pokusum o prulom). Modul do fail2ban bych byl asi schopen spachat i sam, jen budu potrebovat vedet, kam a v jakem tvaru ProArc loguje pokusy o chybna prihlaseni abych na to fail2ban nasmeroval.

Pozitiva maji samozrejme i sva negativa, takze je potreba napr. uvazit, k jakemu mnozstvi nepodarenych pokusu o prihlaseni budeme tolerantni, nez podezrelou IP zabanujeme. Zmateny uzivatel je schopen vygenerovat v kratke dobe relativne hodne neuspesnych pokusu, takze dostane banan a bude cekat. To jak dlouho bude cekat nez se jeho IP znovu uvolni, je opet nutne nejak nastavit - treba hodina/den/tyden. Prilis maly interval nedava moc smysl (ano zneprijemni to zivot robotum, ale zatizi to vyznamne fail2ban a potazmo server pri dos), prilis dlouhy povede k tomu, ze spravce bude muset zasahovat rucne a muze se stat, ze uzivatel bude mit banan cely vikend i kdyz chtel pracovat (napriklad).

Kramerius je shibboletizovany, takze by ten kod z nej mozna sel jen prevzit a priohnout. Ale asi na to opravdu v teto chvili neni cas a prostredky....

MD

**Comment by FoxKyong** [comment]
Tu kratší délku uživatelského jména jsme navrhovali my, protože používáme uživatelské jména všude jako jméno uživatele, čili v případě třech znaků to je "jan" třeba. A pokud chcete delší, tak ta konfigurovatelnost by se asi hodila. Je to celkem běžná věc u spousty systémů - konfigurovatelnost složitosti hesla a případně jména. Což teda asi i odráží to, co bylo zmíněno - "co se liší mezi institucemi". Tady se ProArc používá pouze v lokální síti a není na něho přístup přes internet. Uvažoval jsem, že jestli se ta délka se nezmění, že to opravím sám, ale pak to zase bude oprava v každé verzi. Což už se pak neslučuje s jednoduchou správou. Já preferuji vždy co maximální konfigurovatelnost, každý vždy může mít u něčeho různé požadavky v různých podmínkách.
Už v Krameriovi teď máme taky pár změn, které nejsou konfigurovatelné a musím je provést po každém upgradu odznova.

**Comment by MartinRumanek** [comment]
@mduda100871 
> Modul do fail2ban bych byl asi schopen spachat i sam, jen budu potrebovat vedet, kam a v jakem tvaru ProArc loguje pokusy o chybna prihlaseni abych na to fail2ban nasmeroval.

Proarc momentálně pokusy o přihlášení nijak neloguje, musí se to doplnit. Stačilo by vám to takto?

```
09-Jun-2017 09:51:35.318 INFO [http-nio-8080-exec-1] cz.cas.lib.proarc.authentication.ProarcLoginServlet.doPost Login Failed, proarc, 127.0.0.1
09-Jun-2017 09:51:49.297 INFO [http-nio-8080-exec-5] cz.cas.lib.proarc.authentication.ProarcLoginServlet.doPost Login Successful, proarc, 127.0.0.1
09-Jun-2017 09:51:52.638 INFO [http-nio-8080-exec-10] cz.cas.lib.proarc.authentication.ProarcLoginServlet.doDelete Logout Successful, proarc, 127.0.0.1
```

**Comment by pokorsky** [comment]
Není zrovna tohle dosažitelné pomocí valve v tomcatu? Nebo tam není vidět
username?

On Jun 9, 2017 08:54, "Martin Rumanek" <notifications@github.com> wrote:

@mduda100871 <https://github.com/mduda100871>

Modul do fail2ban bych byl asi schopen spachat i sam, jen budu potrebovat
vedet, kam a v jakem tvaru ProArc loguje pokusy o chybna prihlaseni abych
na to fail2ban nasmeroval.

Proarc momentálně pokusy o přihlášení nijak neloguje, musí se to doplnit.
Stačilo by vám to takto?

09-Jun-2017 09:51:35.318 INFO [http-nio-8080-exec-1]
cz.cas.lib.proarc.authentication.ProarcLoginServlet.doPost Login
Failed, proarc, 127.0.0.1
09-Jun-2017 09:51:49.297 INFO [http-nio-8080-exec-5]
cz.cas.lib.proarc.authentication.ProarcLoginServlet.doPost Login
Successful, proarc, 127.0.0.1
09-Jun-2017 09:51:52.638 INFO [http-nio-8080-exec-10]
cz.cas.lib.proarc.authentication.ProarcLoginServlet.doDelete Logout
Successful, proarc, 127.0.0.1

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/proarc/proarc/issues/539#issuecomment-307321831>, or mute
the thread

**Comment by MartinRumanek** [comment]
@pokorsky  Máš pravdu, v AccessLogu to jde vidět, vypadá to takto:

127.0.0.1 - - [09/Jun/2017:10:47:41 +0200] "POST /proarc/proarclogin HTTP/1.1" 403 1978
127.0.0.1 - - [09/Jun/2017:10:47:57 +0200] "POST /proarc/proarclogin HTTP/1.1" 200 2171
127.0.0.1 - - [09/Jun/2017:10:48:16 +0200] "DELETE /proarc/proarclogin HTTP/1.1" 204 -

Přijde ti to tak lepší? Username tam není, ale pro fail2ban stejně nebude potřeba.

**Comment by pokorsky** [comment]
Pokud to splňuje  požadovaný účel, tak bych totéž neimplementoval. Tohle je hotové a připravené.

**Comment by pavelkocourek** [comment]
Bude řešeno se Správou uživatelů

**Comment by ZdenkaSera** [comment]
V KNAV jsme došli k závěru, že naše současné zabezpečení je postačující.

**Comment by ZdenkaSera** [comment]
Na schůzce vývojového týmu 7.11.2023 se rozhodlo o uzavření issue bez realizace.
