### ISSUE TITLE
Export ze systému

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#54]
```
Pridat moznost exportu zpracovanych udaju na lokalni disk (server) s moznosti 
pojmenovat exportni adresar (napr. Soudobe_dejiny_01). Zaroven mit moznost 
zalozit pri exportu podadresare (jpg, txt...) + samostatne xml k titulu, 
rocniku pripadne vytisku.
```

Original issue reported on code.google.com by `psenic...@gmail.com` on 19 Apr 2013 at 9:03

**Comment by nezbedova** [comment]
Archivační balíček obsahuje 
    ALTO (METS ALTO soubory)
    AUDIT (Historie změn)
    FOXML (Kopie FOXML z úložiště Fedora)
    FULL (Img)
    NDK_ARCHIVAL (Img)
    NDK_USER (Img)
    PREVIEW (Img)
    RAW (Img - původní skeny)
    RELS-EXT (popis vazeb RDF)
    TEXT_OCR (Txt)
    THUMBNAIL (Img)

mets.xml (metadatový popis objektu)

Je ještě potřeba samostatný export v jpg?

**Comment by jkremlacek** [comment]
Issue je staré 5 let, rok a čtvrt zpět padl dotaz, zda je stále aktuální bez odpovědi. 

Má někdo konkrétní zájem o tento enhancement nebo je možné issue zavřít?
