### ISSUE TITLE
Kopírování metadat z nadřaz. objektu při vytvoření NDK Svazek mon. pod NDK Vícedílná mon.

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#540]
Bylo by dobré, kdyby se při vytvoření objektu NDK Svazek monografie pod založeným NDK Vícedílná monografie do svazku zkopírovala metadata z vícedílky. (Bylo by to jednodušší než do každého svazku znovu stahovat metadata vícedílky z katalogu.)

**Comment by nezbedova** [comment]
Souhlasím. To by bylo šikovné.

**Comment by nezbedova** [comment]
Jde o stejné řešení jako u NDK Periodikum, když se pod titulem založí nový výtisk (pod ročníkem).
Tuto funkčnost bychom uvítali u i STT Vícedílná monografie.

**Comment by nezbedova** [comment]
Jde o stejné řešení jako je u NDK Periodikum, při založení NDK Výtisku.
Tuto funkčnost bychom uvítali i u STT Vícedílná monografie.

**Comment by jkremlacek** [comment]
@nezbedova Nevím, zda jsem popis pochopil správně, neboť se mi nedaří překopírování u NDK Periodika provést. Můj postup je:

1. Otevřu `Editor připojených objektů` u objektu typu `NDK Ročník` (objekt **A**)
2. Vytvořím `NDK Číslo` (objekt **B**) pomocí `Nový` -> `NDK Číslo` -> `Vytvořit`
3. U objektu **B** očekávám metadata z objektu **A**, nicméně tam nejsou

Co je potřeba provést jinak?

**Comment by nezbedova** [comment]
Ročník je jen taková výplň, nejsou u něj skoro žádné údaje.
Probíhá to takto:
1. Založím NDK Periodikum stažením z katalogu/RD
2. Otevřu "Editor připojených objektů" přidám NDK ročník => z NDK Periodikum se mi propíší informace do polí NDK Ročník
3. Pod NDK Ročník přidám NDK Číslo =>z z NDK Periodikum se mi propíší informace do NDK Čísla

U NDK Vícedílná monografie a STT Vícedílná monografie by to mělo probíhat takto:
1. Založím NDK (STT) Vícedílná monografie stažením z katalogu/RD (Záznam mohu upravit)
2. Otevřu "Editor připojených objektů" přidám NDK (STT) Svazek monografie => propíší se mi údaje z NDK (STT) Vícedílná monografie (pokud jsem upravovala, tak to upravené)

Moc informací tam není, ale kopírovat titul, autor, nakladatel, místo vydání, siglu je zdlouhavé.

**Comment by jkremlacek** [comment]
Děkuji za vysvětlení, nedošlo mi, že se metadata mohou propsat i z periodika do čísla (pokud jsou spojené skrze ročník).

**Comment by jkremlacek** [comment]
Ještě jeden problém: Podle standardu NDK http://www.ndk.cz/standardy-digitalizace/dmf_mono_13 obsahuje vícesvazková monografie: `titleInfo`, `originInfo`, `genre` a `identifier`.

Zmíněná sigla se nicméně vyskytuje v poli `location`, tj. z vícedílné monografie nejde převzít.

Co se týče indentifikátorů, tak má se nějaký z nich přenášet?

**Comment by SykoraLukas** [comment]
Mohl bych poprosit paní @nezbedova  a paní @luckajirku o vyjádření?

**Comment by luckajirku** [comment]
No ono to není úplně stejné jako u PER (FYI to se řešilo v #124). U PER kopírujeme jen vybrané elementy, tady  potřebujeme, aby se do svazku MON zkopírovalo vše.  
Další postup je pak takový, že zatímco na úrovni vícedílky zůstanou ty údaje všechny (např. stránkování obou svazků atp.), na úrovni jednotlivých svazků pak odmazáváme to, co se vztahuje k jinému než právě popisovanému svazku, upravíme signaturu atd. Pokud máme hodně dílů, tak nyní to znamená založit objekt vícedílky a pozakládat každý svazek zvlášť a do každého znovu a opět stahovat z katalogu metadata vícedílky. Pokud bude fungovat kopírování, tak založíme objekt vícedílky a pak pod ním  budeme jednoduše zakládat jednotlivé svazky bez nutnosti stahovat metadata z katalogu (s tím, že se pak musí nepatrně upravit, ale ušetří to čas a i eliminuje chyby - riziko stažení jiného záznamu z katalogu u některého svazku).
Jediný problém, který jsme řešili, jak potom s ččnb u těch jednotlivých svazků. Ale to už je problém nás při popisu, co tam necháme, nastavení kopírování se to netýká.

**Comment by SmejkalovaAnna** [comment]
Já v tom tom teda úplně nemám jasno. Já osobně bych to nechala tak, jak to je. V NDK Vícedílná monografie je těch údajů tak málo, že si myslím, že je lepší je do každého svazku extra stáhnout z katalogu, kde mám jakž takž jistotu, že jsou opravdu ty konkrétní údaje pro dannou knihu. Doteď jsem chápala uzel Vícedílná monografie jen jako zastřešující element pro NDK Svazek monografie, který nenese zásadní informace.... Nevím, jestli jsem to tedy dostatečně pochopila....

**Comment by luckajirku** [comment]
Hm, tak to byl můj omyl, že jsem vycházela z bib záznamu. 
Takže jedna věc je, že opravdu v ProArcu nezkopírujeme do jiného objektu něco, co v tom nadřazeném není:-(. Druhá věc je, jestli to, jak jsou metadata v NDK/STT vícedílce osekaná na minimum, je dobře...
