### ISSUE TITLE
Testy - Selhává OldPrintPageMapperTest

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#541]
Selhává  [první assert](https://github.com/proarc/proarc/blob/development/proarc-common/src/test/java/cz/cas/lib/proarc/common/object/oldprint/OldPrintPageMapperTest.java#L125) v testGetPageTypeLabel(), namísto anglické verze "Front Endpaper" dostává text české lokalizace "Přední předsádka".

Ve frontendu se chyba neděje, při přepnutí do anglické lokalizace jsou texty typu stránky v angličtině.

**Comment by jkremlacek** [comment]
Edit: Přesunuto do forku z proarc/development

**Comment by pokorsky** [comment]
Přidáno, díky.
