### ISSUE TITLE
xml editor nezůstává vybraný

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#556]
Když se v editoru připojených objektů pohybuji mezi jednotlivými články a mám otevřená metadata v xml zobrazení, tak nezůstává vybrané zobrazení xml. Vždy po překliknutí na další článek se mi zase otevře v metadatovém formuláři a musím opět vybrat xml.
Bylo by možné si zapamatovat tu volbu? U ostatních nabídek ten výběr zůstane zapamatovaný.

**Comment by MartinRumanek** [comment]
> U ostatních nabídek ten výběr zůstane zapamatovaný.

Nejsem si úplně jistý touto větou. Jaké ostatní nabídky zůstanou zapamatovány? 
______
Může to být implementováno obecně u všech modelů? 

Například u ročníků: překliknu se  na další ročník, zůstává vpravo XML editor (nebudu muset znovu vybírat XML editor jako v obrázku). Když ale vyberu katalog, tak po překliknutí se vracím zpět do klasického formuláře.

![Imgur](http://i.imgur.com/8cJ55OA.gif)

**Comment by slapakovai** [comment]
Když si v nabídce "metadata" vyberu "zjednodušený formulář" a v editoru připojených objektů se proklikávám mezi články, tak se mi metadata pořád zobrazují ve zjednodušeném formuláři. Když si v nabídce "metadata" vyberu "formulář" a překlikávám se mezi články, tak mi tam zůstane vybraný pořád formulář.
Ale když si v nabídce "metadata" vyberu "XML" a překliknu na další článek, tak se mi metadata zobrazí ve formuláři a musím znovu kliknout na "XML".

Ano, může to být u všech modelů obecně.

Katalog je speciální volba, která má jiný účel, než prohlížení metadat, takže se chová jinak.

**Comment by SykoraLukas** [comment]
Duplicitní issue s #481.
