### ISSUE TITLE
mizí zaškrtnutá hodnota Peer Review z metadatového formuláře

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#557]
Při zpracování metadat eČlánků mizí po uložení hodnota z výběru Peer Review. Děje se to ve formuláři i ve zjednodušeném formuláři.

Popis situace:
vyplním metadata
zakliknu hodnotu "recenzovaný článek" nebo "nerecenzovaný článek"
uložím metadata
zaškrnutá hodnota v poli Peer Review zmizí a už není vidět, že je vybraná
pokud metadatový formulář znovu otevřu, tak zaškrnutá hodnota Peer Review v daném poli jenom problikne a opět zmizí

V xml je hodnota zaznamenaná správně, ale ve formuláři není vidět. Lze zařídit, aby tam byla vidět stále? V předchozích verzích se toto nestávalo. Chybu jsme zaznamenali až po nasazení verze 3.3.

**Comment by slapakovai** [comment]
Můžu se zeptat, kdy opravíte tuhle chybu? Domluvili jsme se, že by to mělo být opravené ve verzi 3.4.

**Comment by pokorsky** [comment]
V XML editoru je hodnota vidět. Problém musí být ve formuláři na klientu. Možná problém komponenty Field.RADIOGROUP?

**Comment by pokorsky** [comment]
Opraveno.
