### ISSUE TITLE
editace xml eČlánku nefunguje

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#558]
Pokud si stáhnu z katalogu metadata k eČlánku, edituji xml toho článku a chci ho uložit, tak mi vyskočí chyba:
"Column:37 Line:63 cvc-complex-type.2.4.b: The content of element 'mods:detail' is not complete. One of '{"http://www.loc.gov/mods/v3":number, "http://www.loc.gov/mods/v3":caption, "http://www.loc.gov/mods/v3":title}' is expected."

Tato chyba vyskočí v případě editace jakéhokoliv elementu v celém xml.
Pokud přidám do xml nový element, tak mi vyskočí ta samá chyba.

**Comment by MartinRumanek** [comment]
Nedaří se mi to zreplikovat, děje se to u všech e-článků, nebo je problémový jeden konkrétní?


Pravděpodobně je z katalogu načtený nevalidní MODS (je to možné?). Prosím napište mi identifikátor/katalog problémového článku (nebo aspoň kopii MODS).

**Comment by slapakovai** [comment]
Zkoušeli jsme to s více záznamy. Postup navození chyby:
1. případ - špatné chování
stáhnu záznam článku z katalogu
odmažu nějaký element ve formuláři nebo edituji nějaký element ve formuláři
uložím bez problému
edituji xml
xml nelze uložit - napíše to tu chybu

2. případ - správné chování
stáhnu záznam článku z katalogu
odmažu nějaký element v xml
uložím bez problému
edituji xml
xml lze uložit

3. případ - správné chování
stáhnu záznam článku z katalogu
nic nemažu ani needituji ve formuláři
edituji xml
xml lze uložit

**Comment by MartinRumanek** [comment]
Díky, na základě tohoto popisu se mi to podařilo nasimulovat.

**Comment by SykoraLukas** [comment]
ve verzi 3.5.7 již funguje správně
