### ISSUE TITLE
editace xml NDK objektů nefunguje, pokud jsou k nim připojené objekty na nižší úrovni

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#559]
Pokud chci editovat xml NDK Periodika nebo NDK Ročníku, tak neproběhne uložení. Vyskočí správně hláška "Uložením dojde ke změně metadat pouze u tohoto objektu, metadata připojených objektů zůstanou beze změny!", ale po potvrzení nedoběhne ukládací proces a zůstane zvýrazněné tlačítko Uložit.
Když metadata změním ve formuláři, tak hláška taky vyskočí a uložení proběhne správně.

**Comment by jkremlacek** [comment]
Hláška byla chybně předložena uživateli. Uložení takového XML selhalo a pouze mělo dojít k informování uživatele o chybě.

Po změně tedy bude uživatel dotázán zda chce i tak pokračovat s uložením (s možností Ano/Ne, stejně jako v metadatovém formuláři).

**Comment by jkremlacek** [comment]
Implementováno.
