### ISSUE TITLE
Testy - selhávají testy související s fedorou

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#560]
Fedora (běžící v dockeru na adrese `localhost:8080/fedora`) je nastavena pomocí junit.properties

```
proarc-common.FedoraTestSupport.url = http://localhost:8080/fedora
proarc-common.FedoraTestSupport.user = fedoraAdmin
proarc-common.FedoraTestSupport.passwd = fedoraAdmin
```

Hlášení výsledku testů vypíše:

````
RemoteStorageTest.testDatastreamEditorRewriteControlGroup:602 » DigitalObject ...
RemoteStorageTest.testDatastreamEditorWriteReference_External:545 » DigitalObject
RemoteStorageTest.testDatastreamPurge:203 » DigitalObject PID: uuid:33085b6e-8...
RemoteStorageTest.testIngestPage:153 » DigitalObject PID: uuid:d2296bdf-eb69-4...
FedoraGroupDaoTest.testAddNewGroup:90 » IllegalState group:testAddNewGroup
FedoraUserDaoTest.testCreateRemoteUser:97 » IllegalState user:testRemoteUser
````

Z logu fedory jsou zvláštní vyjímky typu:

`org.fcrepo.server.errors.HttpServiceNotFoundException: [FileExternalContentManager] returned an error.  The underlying error was a java.io.FileNotFoundException  The message was  "/tmp/junit2472696893745659382/junit2501420942714439329.tmp (No such file or directory)"  .  
`

Není možné, že by testy vyžadovaly přístup souborového systému mezi fedorou a systémem, na kterém běží testy?

[Kompletní výpis logu fedory](https://gist.github.com/jkremlacek/ce810648cd6601dd3a9c1e7eb5aa268f)

**Comment by pokorsky** [comment]
Omlouvám se, ale té otázce nerozumím. Jak Fedora, v tomto případě úložiště Akubra, tak webserver přístup k souborovému systému vyžadují. Ať už pro uložení objektů, tak pro dočasné soubory. Totéž se týká testů. Některé soubory používají.

Zatím jsem narazil na problém na Windows 10, kde nefunguje mazání objektů a dostávám výjimky z Akubry. Na Linuxu jsem se s ničím podobným zatím nesetkal.

**Comment by pokorsky** [comment]
Zrovna první hláška bude v pořádku. Objekt `icon:application_pdf` je potřeba importovat ručně.
```
org.fcrepo.server.errors.ObjectNotInLowlevelStorageException: Object not found in low-level storage: icon:application_pdf
```
Pro srozumitelnější chybové hlášky je potřeba nakonfigurovat `WebApplicationExceptionMapper` viz. wiki Instalace.

**Comment by jkremlacek** [comment]
Bylo to myšleno tak, že Fedora a systém na kterém běží testy sdílí jeden souborový systém / je provázaný symlinky.

Tedy je možná situace, že si nepředávají soubory přes síťovou vrstvu, ale pouze cestu k souboru (tak jako tomu je například v případě importu obrázků, kdy aplikace proarc-u a fedory musí mít přístup k souboru přes souborový systém.

**Comment by MartinRumanek** [comment]
První 4 testy ti selhávají určitě z těch důvodu, které píšeš.

Pro hladký průběh poslední dvou testů musíš mít nakonfigurovaný `WebApplicationExceptionMapper` o kterém píše Honza. Proarc na to bohužel interně spoléhá (https://github.com/proarc/proarc/blob/5d0742a71d945258198a4924a7703c2248f1e631/proarc-common/src/main/java/cz/cas/lib/proarc/common/fedora/RemoteStorage.java#L226-L226)
