### ISSUE TITLE
Chybné zobrazení u výběru obrázku

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#566]
V obrazovce Import - Příprava metadat pro načtení do úložiště se po výběru řádku v levém sloupci nezobrazí v prostředním sloupci vybraný obrázek. V pravém sloupci se objeví správný náhled. V prostředku je výběr "nad obrazovkou". Děje se tak při výběru většího rozsahu, např. z obr 1 chci obr 200.

**Comment by MartinRumanek** [comment]
Nedaří se mi to zreplikovat, ani ve větším rozstahu (500 stran). Prosím, jakou máte verzi prohlížeče?

Děje se to ještě někomu?

**Comment by slapakovai** [comment]
Prosím @nezbedova o doplnění detailů o prohlížeči.

**Comment by nezbedova** [comment]
Mozilla Firefox. Vyzkoušela jsem to i v Googlu a dělá to také. Na pracovní schůzce byl problém předveden M. Rumánkovi.

**Comment by pavelkocourek** [comment]
Přesunuto : Chybné zobrazení u výběru obrázku (#566) #23
