### ISSUE TITLE
LZW komprese

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#567]
Do ProArcu nejdou načíst obrázky s LZW kompresí. Nevím, zda to je chyba nebo to byl záměr.

**Comment by jkremlacek** [comment]
Externí demo aplikace Kakadu nepodporuje převod tiff (komprimován pomocí LZW) -> JP2, takže nejspíš kvůli tomu. 

[zdroj](https://groups.google.com/forum/#!topic/islandora/OOL_HeK3zpw)

Nejjednodušší bude pomocí nástroje ImageMagick obrázky převést na variantu bez komprese, které ProArc načte.

**Comment by mduda100871** [comment]
Zdravim,

nas Kakadu kodek je zkompilovany s podporou libtiff, ktera by mela podporovat lzw kompresi - screenshot:

![kdu_compress-01](https://user-images.githubusercontent.com/8750622/29018685-5602e4a2-7b5c-11e7-9d27-246cad52b6e9.png)

MD

**Comment by jkremlacek** [comment]
V tom pripade musi prochazet konverze tiff -> jp2.

Původní dotaz bohužel neobsahuje detail chybové hlášky (stejně tak duplicitní issue), nicméně v případě použití dema je chyba následující:

```
proarc_1  | Aug 07, 2017 8:26:31 AM cz.cas.lib.proarc.common.imports.TiffImporter consume
proarc_1  | SEVERE: /usr/local/tomcat/.proarc/users/dufkaj/import/Testing_batch/Jirka Dufka/Zk-0000.751/01.tif
proarc_1  | java.io.IOException: /usr/local/tomcat/.proarc/users/dufkaj/import/Testing_batch/Jirka Dufka/Zk-0000.751/proarc_import/01.NDK_ARCHIVAL.jp2
proarc_1  | exit: 255,
proarc_1  | out: Kakadu Error:
proarc_1  | The simple TIFF file reader in this demo application can only read uncompressed
proarc_1  | TIFF files.  This has nothing to do with Kakadu itself, of course.  If you
proarc_1  | would like to read compressed TIFF files, however, it should be sufficient to
proarc_1  | re-compile this application with the symbol "KDU_INCLUDE_TIFF" defined, and
proarc_1  | link it against the public-domain LIBTIFF library.
```

kdy skutečně kolabuje pouze externí proces kakadu, nikoli komponenta proarcu. Bude tedy potřeba získat chybovou hlášku od zadavatele issue @nezbedova (např. zopakováním importu), aby bylo možné určit, co selhalo.

**Comment by pokorsky** [comment]
Chybová hláška by měla být dostupná v historii importů.

On Aug 7, 2017 11:02, "Jakub Kremláček" <notifications@github.com> wrote:

V tom pripade musi prochazet konverze tiff -> jp2.

Původní dotaz bohužel neobsahuje detail chybové hlášky (stejně tak
duplicitní issue), nicméně v případě použití dema je chyba následující:

proarc_1  | Aug 07, 2017 8:26:31 AM
cz.cas.lib.proarc.common.imports.TiffImporter consume
proarc_1  | SEVERE:
/usr/local/tomcat/.proarc/users/dufkaj/import/Testing_batch/Jirka
Dufka/Zk-0000.751/01.tif
proarc_1  | java.io.IOException:
/usr/local/tomcat/.proarc/users/dufkaj/import/Testing_batch/Jirka
Dufka/Zk-0000.751/proarc_import/01.NDK_ARCHIVAL.jp2
proarc_1  | exit: 255,
proarc_1  | out: Kakadu Error:
proarc_1  | The simple TIFF file reader in this demo application can
only read uncompressed
proarc_1  | TIFF files.  This has nothing to do with Kakadu itself, of
course.  If you
proarc_1  | would like to read compressed TIFF files, however, it
should be sufficient to
proarc_1  | re-compile this application with the symbol
"KDU_INCLUDE_TIFF" defined, and
proarc_1  | link it against the public-domain LIBTIFF library.

kdy skutečně kolabuje pouze externí proces kakadu, nikoli komponenta
proarcu. Bude tedy potřeba získat chybovou hlášku od zadavatele issue
@nezbedova <https://github.com/nezbedova> (např. zopakováním importu), aby
bylo možné určit, co selhalo.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/proarc/proarc/issues/567#issuecomment-320623365>, or mute
the thread

**Comment by mduda100871** [comment]
Kouknul jsem do logu a opravdu je tam hlaska o demu - to je zajimave. Podporu libtiff v kakadu mame od pocatku, co jsme zakoupili licenci. Specialne kvuli tomu jsem upravoval makefile zdrojaku kakadu...

![kakadu-error-01](https://user-images.githubusercontent.com/8750622/29022485-ca591be8-7b69-11e7-8326-7dbdbbf15639.png)

MD

**Comment by jkremlacek** [comment]
Pak jedině zkontrolovat proměnné v proarc.cfg, zda-li jsou správně nastavené na překompilovanou verzi.

Jedná se o záznamy:

```
KDU_HOME=/usr/kakadu
KDU_EXEC=${KDU_HOME}/bin/kdu_compress
KDU_LIBPATH=${KDU_HOME}/bin
```

**Comment by mduda100871** [comment]
Konfigurace:

![proarc cfg-01](https://user-images.githubusercontent.com/8750622/29022874-682334a2-7b6b-11e7-84df-9622c5322088.png)

binarka je v systemove ceste pouze jedna v /usr/local/bin (viz screenshot zavislosti vyse).

Asi to zkusim tedy cele zavolat rovnou z prikazove radky.

MD

**Comment by mduda100871** [comment]
no uz to mozna vidim, problem bude asi v KDU_LIBPATH kde je cesta, ktera neobsahuje libtiff...

**Comment by nezbedova** [comment]
Doplňuji hlášku, ať to je úplné:
Nejprve vyskočí hláška "Zpracování skenů" Zpracování selhalo: Importní dávku nelze načíst!.
Po kliknutí na "Pokračovat" - Neočekávaná chyba! :-(

Detaily: /media/vg1-lv1/proarc-test/work_data/users/nezbedova/import/lzw/proarc_import/0001.foxml java.io.IOException: /media/vg1-lv1/proarc-test/work_data/users/nezbedova/import/lzw/proarc_import/0001.NDK_ARCHIVAL.jp2 exit: 255, out: Kakadu Error: The simple TIFF file reader in this demo application can only read uncompressed TIFF files. This has nothing to do with Kakadu itself, of course. If you would like to read compressed TIFF files, however, it should be sufficient to re-compile this application with the symbol "KDU_INCLUDE_TIFF" defined, and link it against the public-domain LIBTIFF library. at cz.cas.lib.proarc.common.imports.TiffImporter.processJp2Copy(TiffImporter.java:265) at cz.cas.lib.proarc.common.imports.TiffImporter.importArchivalCopy(TiffImporter.java:217) at cz.cas.lib.proarc.common.imports.TiffImporter.consume(TiffImporter.java:105) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSet(FileSetImport.java:115) at cz.cas.lib.proarc.common.imports.FileSetImport.consumeFileSets(FileSetImport.java:96) at cz.cas.lib.proarc.common.imports.FileSetImport.start(FileSetImport.java:83) at cz.cas.lib.proarc.common.imports.ImportProcess.start(ImportProcess.java:210) at cz.cas.lib.proarc.common.imports.ImportProcess.run(ImportProcess.java:181) at cz.cas.lib.proarc.common.imports.ImportDispatcher$ExceptionHandlingTask.run(ImportDispatcher.java:121) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by mduda100871** [comment]
Tak libtiff knihovna lzw podporuje, overil jsem to utilitou tiffcp. Makefile kakadu je upraveny (pred kompilaci samozrejme) - screenshot:

![makefile-01](https://user-images.githubusercontent.com/8750622/29027813-87fe1528-7b82-11e7-96c5-c6af5e2f9618.png)

Kdyz vyexportuji systemove promenne - screenshot:

![env-01](https://user-images.githubusercontent.com/8750622/29027920-ed0d65d6-7b82-11e7-805a-6f3503bc527e.png)

a spustim konverzi z radky, koncim stejnou chybou hlaskou. Takze to zase vypada asi na nejaky bug Kakadu...

MD

**Comment by jkremlacek** [comment]
Nejsem si jisty jestli proarc.cfg neoverridne pro aplikaci systemove promenne, tj mozna nastava to, ze se k proarc-u nedostane systemova promenna 

`KDU_LIBPATH=/usr/lib/x86_64-linux-gnu`

ale zustane tam

`KDU_LIBPATH=${KDU_HOME}/lib`

mozna by mohlo pomoct tuto hodnotu natvrdo zadat do proarc.cfg

**Comment by mduda100871** [comment]
Jasne, ale muj test vyse probehl primo v prikazove radce, mimo ProArc...

**Comment by MartinRumanek** [comment]
Zkuste ještě do libs přidat parametr ltiff
```
LIBS = -lm -lpthread -ltiff
```
Pak by snad LZW mělo fungovat.

**Comment by mduda100871** [comment]
parametr ltiff mam v makefile pro coresys:
![coresys-01](https://user-images.githubusercontent.com/8750622/29311912-9afe5f52-81b3-11e7-8340-8a65f4f58cb9.png)

takze ho zkusim pridat i do apps a managed a znovu prekompiluji. Nicmene pokud vypis zavislosti ldd vypise, ze dynamicka knihovna libtiff je znama (viz screenshot vyse), tak bych predpokladal, ze ji kakadu pouzije...

**Comment by mduda100871** [comment]
Tak jsem to vsechno znovu zkompiloval a porad stejny problem. Pridal jsem "-ltiff" do:

apps/make/Makefile

![apps-make-01](https://user-images.githubusercontent.com/8750622/29363122-05102a8e-828f-11e7-8287-19b8b8cee2ac.png)

a do managed/make/Makefile

![managed-makefile-01](https://user-images.githubusercontent.com/8750622/29363154-273be5bc-828f-11e7-929f-809b8b237676.png)

zavislosti jsou splnene:

![kdu_compress-ldd-01](https://user-images.githubusercontent.com/8750622/29363237-7c56b6bc-828f-11e7-84a7-a62e5e5acf76.png)

a dle dokumentace prilozene ke zdrojakum:

![doc-01](https://user-images.githubusercontent.com/8750622/29363290-b258b85a-828f-11e7-9add-a909836a2a2b.png)

by to melo vsechno stacit, ale nestaci. Prolezl jsem diskuse a vsude se tvrdi to same (dokonce sam autor kakadu):

https://groups.yahoo.com/neo/groups/kakadu_jpeg2000/conversations/topics/6684

Je jeste nekde nekdo (v MZK?) nahodou, kdo ma licenci Kakadu, ma to zkompilovane proti libtiff a funguje mu podpora LZW?

MD

**Comment by mduda100871** [comment]
Tak SLAVA, podarilo se mi to snad zlomit :)

Zrada byla v tom, ze makro KDU_INCLUDE_TIFF se musi pridat do CFLAGS kompilatoru, takze:

![cflags-01](https://user-images.githubusercontent.com/8750622/29364609-55325b9a-8294-11e7-8d1f-f7a9d15e50c1.png)

Nasadim do ProArcu a uvidime. Z radky konverze probehne bez nadavek.

MD

**Comment by jkremlacek** [comment]
@mduda100871 Funguje už konverze i v rámci ProArcu v pořádku?

**Comment by mduda100871** [comment]
Prozatim nemam informaci, zda-li to uz Jenstejn zkousel...

**Comment by nezbedova** [comment]
Otestováno a funguje.

**Comment by jkremlacek** [comment]
Vyřešeno. Chyba byla v externí aplikaci.
