### ISSUE TITLE
Přidání dalších jazyků 

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#568]
V elementu Languages - M do roletky Languages - M
prosím přidat 

Name	                  Language   Type	        Autority
Starořečtina (–1453)	  grc	            code 	        ISO 639-2-B
Řečtina (1453–)          gre	            code 	        ISO 639-2-B
Hebrejština                heb	            code 	        ISO 639-2-B

**Comment by pokorsky** [comment]
Přidáno. Díky za patch.
