### ISSUE TITLE
Přidání možnosti dpi u zařízení

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#569]
V obrazovce Správa zařízení doplnit do rámečku "Maximum Optical Resolution - M" do roletky "Optical Resolution Unit - M" možnost volby "dpi".

**Comment by jkremlacek** [comment]
Tyto hodnoty jsou součástí MIX standardu [viz](https://github.com/proarc/proarc/pull/570) - tedy přidání dpi by znamenalo jeho porušení.

Bude tedy potřeba najít jiné řešení, které vyhovuje tomuto standardu

**Comment by nezbedova** [comment]
Poraďte mi, prosím, jak tedy získám tyto údaje. Domnívala jsem se, že optické rozlišení skeneru se udává v dpi. Jak z toho dostanu cm nebo in?

**Comment by jkremlacek** [comment]
Maximální optické rozlišení by mělo být vypočítatelné následovně: 
1. Necháme si vytvořit sken bez oříznutí -> šířku skenu označíme `xMax`, výšku skenu označíme `yMax` (obě v pixelech)
2. Vypočítáme `xMax / dpi` - hodnota X Optical Resolution (v in.)
3. Vypočítáme `yMax / dpi` - hodnota Y Optical Resolution (v in.)

(mělo by odpovídat skenovací ploše skeneru)

**Comment by nezbedova** [comment]
Děkuji a zavírám.
