### ISSUE TITLE
Přebírání údajů z RDflow do Archive balíčku

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#571]
Přidat do archivačního balíčku údaje o skeneristech a zpracovatelích z RDflow. Potřebujeme mít informaci o typu úkolu a pracovníkovi, který daný úkol dokončil a kdy.

**Comment by pavelkocourek** [comment]
Doplnit informaci kam v METS mají být údaje zapsány

**Comment by krizovj** [comment]
@SykoraLukas  šlo by to dát do archivního balíčku buď do audit nebo do description? do METS bych to asi nedávala...

**Comment by SykoraLukas** [comment]
Byla by možnost vytvořit soubor na úrovni mets.xml s názvem workflow_info.xml, kde by byly vyexportované informace z Rdflow (Úkol, datum dokončení, kdo dokončil). Stačilo by to takhle @tumovam, @nezbedova? Do složek audio a description bych to nepletl. Ty jsou na jiné věci.

**Comment by tumovam** [comment]
@SykoraLukas nejsem si úplně jistá, co s tím. Bylo by to volitelné, nebo by se "workflow_info" exportovalo do všech archivních balíčků?

**Comment by SykoraLukas** [comment]
Pokud by se našlo UUID objektu proarcu v rdflow, tak by se exportovalo. Pokud by se nenašlo, tak by žádný soubor nebyl.

**Comment by tumovam** [comment]
Jo, to dává smysl. Tak dobře, takhle by to snad mohlo být.

**Comment by nezbedova** [comment]
Souhlasím.

**Comment by ZdenkaSera** [comment]
Problém trvá u VD.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, zavírám to - testovalas to v březnu (tj. na v 3.7.3), Tohle zřejmě jiná knihovna nebude řešit.
