### ISSUE TITLE
Přidání nových typů stan do STT

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#573]
Navrhuji přidat do roletky s typy stran pro modely STT:
Dodatek
Notový zápis
Impresum 

A v této roletce změnit slovo "Normální strana" na "Strana". Pokud to neovlivní ostatní modely, tam je nutné zachovat NDK standard "Normální strana".

**Comment by LenkaDamborska** [comment]
V MZK se přimlouváme ještě za 2 další typy stran pro STT:
Kalibrační tabulka
Pouzdro

**Comment by SykoraLukas** [comment]
Vyřešno v rámci #814. Kvůli systémovému omezení bylo nutné spojit seznam typů stran NDK a STT. Protože NDK obsahuje více typů stran než STT nevidím v tomto spojení žádný problém, který by porušoval standard NDK.
