### ISSUE TITLE
špatná hodnota v elementu genre

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#575]
Při použití zjednodušeného formuláře pro eČlánek si můžu vybrat typ obsahu anotace. V elementu genre se mi vyplní type="annotations". Správně by tam mělo být vyplněno type="annotation". Prosím o opravu.

**Comment by pokorsky** [comment]
@slapakovai: Toto není bug. Viz. požadavek v issue #339.

**Comment by slapakovai** [comment]
Ok, tak to označení klidně změň.

**Comment by pokorsky** [comment]
Jde také o to, že od roku 2015 může být vytvořena spousta objektů s genre/@type='annotations'. Pokud se hodnota neřídí žádným standardem a specifikovala jsi ji sama, tak bych ji neměnil. V opačném případě co s existujícími objekty? Zdokumentuješ takovou změnu nebo se budou existující objekty opravovat?

**Comment by slapakovai** [comment]
Lze nějak zjistit, kolik objektů v proarc-ozc obsahuje element genre with type="annotatitons"?

**Comment by MartinRumanek** [comment]
Musel by se na to udělat skript.

**Comment by slapakovai** [comment]
Tak zatím radši počkáme s tou změnou a budeme to řešit teprve až a pokud tenhle typ článku přibude ve standardu NDK.
Issue nechávám otevřené.

**Comment by SykoraLukas** [comment]
Jak tohle vyřešit, když již existuje standard? @slapakovai  @krizovj

**Comment by krizovj** [comment]
No, to se asi může zavřít a zatím nechat tak, jak to je. Ptž ve standardu ani tahle hodnota není. Takže bych to udělala asi tak, že se to vyřeší, až se budou dělat nové formuláře pro eborny a zatím se to může zavřít? Šlo by to?
