### ISSUE TITLE
ProArc 3.3 problém s importem

### ISSUE THREAD

**Issue by sylviekriz** [proarc/proarc#576]
Dobrý den,
máme problém s importem dat do systému. Po přihlášení do účtu Jakuba Bjačka, Jakuba Blechy i admin proarc: data (TIF, JP2, OCR) ve složce pod názvem periodika (ld_1951_ii) jsme nahráli přes WinSCP do složky Import. Zdá se, že se nevytvořily náhledy a nezobrazuje se to na webu http://proarc.fsv.cuni.cz/proarc/. 
Napadá Vás, v čem může být chyba? 
Ve WinSCP má Jakub Bjaček u této složky jiná práva než jsou u dat nahraných loni kolegou před aktualizací verze... Může to být příčina?

Děkujeme za pomoc při vyřešení problému.
S pozdravem,

Sylvie Křížová a Jakub Bjaček
FSV UK

**Comment by MartinRumanek** [comment]
Ano, může být problém v právech. Do importního adresáře musí mít uživatel pod kterým běží Proarc právo zápisu.

**Comment by sylviekriz** [comment]
Můžete to prosím zkontrolovat u mého účtu a účtu kolegy Jakuba Bjačka a případně práva doplnit?
Děkujeme!

**Comment by MartinRumanek** [comment]
Správce vašeho proarcu je @Jenyk (Honza Holman), určitě se vám na to rád podívá.

**Comment by Jenyk** [comment]
Zkontroluju to

**Comment by Jenyk** [comment]
Změnil jsem vlastníka a nový adresář už je v ProArcu vidět. 
Problém s právy u nových adresářů jsme kdysi řešili s pí. Soškovou a došli jsme k závěru, že nejjednodušší je nastavit si ve WinSCP uživatele proarc a nahrávat soubory k importu pod tímto uživatelem. Můžete to vyzkoušet?

**Comment by MartinRumanek** [comment]
To je jedno řešení, druhé by bylo nastavit si ve winscp umask (https://winscp.net/eng/docs/ui_permissions).

Issue zavírám, není to chyba aplikace.
