### ISSUE TITLE
RDFlow  - Vytvoření nového objektu z RDFlow

### ISSUE THREAD

**Issue by MartinRumanek** [proarc/proarc#577]
Do obrazovky „Správa záměrů“ přibude tlačítko „Vytvořit nový objekt“ (umístěno nahoře v liště, vedle tlačítek zakládání záměru/podzáměru). Po kliknutí na toto tlačítko je v Proarcu založený nový objekt. 

Uživateli vyskočí modální dialogové okno s hláškou „Objekt založen“ (okno je nutné potvrdit).

V definici profilů (workflow.xml) bude možné definovat zpracovávané modely z Proarcu.

**Comment by pokorsky** [comment]
Implementováno. Podle PR chybí wiki dokumentace, tak issue nechávám otevřenou

**Comment by slapakovai** [comment]
Tlačítko jsem nenašla, nelze otestovat.

**Comment by pokorsky** [comment]
Předpokládám, že je potřeba upravit Vaši workflow.xml konfiguraci a přidat element jobs/element. Viz úvodní popis tady nebo ukázkové [workflow.xml](https://gist.github.com/MartinRumanek/1763e83f0b7b826d1f02a0c5cab8f027#file-workflow-xml) z PR #578. Jak už bylo řečeno, popis na wiki bude doplněn.

**Comment by MartinRumanek** [comment]
Doplnil jsem popis na wiki (https://github.com/proarc/proarc/wiki/Popis-workflow.xml#definice-profilu-zpracov%C3%A1n%C3%AD-job), musíte si do workflow.xml dopsat definici modelu .

**Comment by krizovj** [comment]
Tlačítko už jsme našli, ale nefunguje (je šedivé). XML je upravené, Ivana vám ho posílala 17. 10. kvůli zkontrolování. 

Není jasné, jak vytvořit podzáměr. Když chci vytvořit nový záměr (periodikum), tak to po mě chce vybrat model (ročník, číslo, přílohu). Když jeden z nich vyberu, objeví se formulář, který je vyplněný z předchozího ročníku (neobnoví se, aby byl prázdný, i když jsem předchozí formulář vyplnila a NEuložila). Zároveň hází chybovou hlášku: "Not found! PID: 5, 5" (číslo se mění podle počtu vytvořených záměrů). 

Na stránce Správa záměrů není ze seznamu jasné, o který model jde (v tabulce jsou pouze tyto údaje: název (čeho?), stav, profil, uživatel a priorita). Není jasné, zda jsou to záměry, nebo podzáměry a pod co případně ty podzáměry patří.

**Comment by MartinRumanek** [comment]
Podívám se na to, tlačítko se musí povolit nad konkrétním profilem (profil se vybírá při vytváření záměru). XML tedy mám, nad jakým profilem vám tlačítko zůstává zašedlé?

______
Další část popisovaných problémů patří do https://github.com/proarc/proarc/issues/602.

Formulář se řeší pouze pro úroveň záměru, podzáměry se nijak neřešily. Při vytváření záměru není model až tak podstatný, nikam se neukládá (a proto to není v tabulce), slouží to pouze k zobrazení správného editačního formuláře.

> Zároveň hází chybovou hlášku: "Not found! PID: 5, 5" (číslo se mění podle počtu vytvořených záměrů).

Vyzkouším to.

**Comment by krizovj** [comment]
Šlo o profil e-periodika K4, k jinému profilu nám ani záměr vytvořit nešel, takže nevím, jestli by tlačítko pro jiný profil fungovalo.

Pokud v tabulce není uvedený model, tak nelze poznat, o co jde. Záměr se jmenuje pořád stejně (název periodika), i když je to ročník, číslo, nebo příloha periodika. Takže sice vím, k jakému periodiku záměr patří, ale už nevím, o co přesně jde, jestli je to ročník a který nebo jestli je to číslo a které.

![spravazameru](https://user-images.githubusercontent.com/21309201/32828620-ec080bbc-c9ef-11e7-8382-79268d5a2c1f.jpg)

**Comment by MartinRumanek** [comment]
Po kliknutím pravého tlačítka se dá zapnout zobrazování dalších sloupců: například rok, ročník, sigla. To by vám pomohlo?

**Comment by krizovj** [comment]
Pokud se v tom sloupci zobrazí číslo ročníku a číslo čísla, tak by nám to stačilo. Když si ty sloupce teď zobrazím, tak jsou ale prázdné. Ale ještě bychom potřebovali, kdyby to bylo možné, nějak rozlišit, jestli je to příloha. Máme tam teď totiž tři modely: ročník, číslo a příloha periodika. Ale v tabulce, i když tam budou sloupce ročník a číslo, tak nijak nezjistím, že je to příloha. Kdyby tam šel přidat ještě jeden sloupec, který by se jmenoval třeba "příloha" a pokud by nešlo o přílohu, tak by byl prázdný. Pokud by to byla příloha, tak by tam mohlo být klidně jenom "příloha". Že jde o přílohu jde zjistit z MODSu z elementu "genre", kde je, když je to příloha, uvedeno buď příloha k ročníku nebo příloha k číslu.

Ještě jsem si všimla, že se ve formuláři automaticky negeneruje uuid a také mi, i přestože formulář uložím, nejde zobrazit xml.

**Comment by MartinRumanek** [comment]
> Ještě jsem si všimla, že se ve formuláři automaticky negeneruje uuid a také mi, i přestože formulář uložím, nejde zobrazit xml.
Samotný záměr UUID nemá, je to jenom záměr, nikoliv objekt v úložišti. U kterého modelu se vám nedaří zobrazit XML? Nedaří se mi to zreplikovat.

**Comment by MartinRumanek** [comment]
> Pokud se v tom sloupci zobrazí číslo ročníku a číslo čísla, tak by nám to stačilo. Když si ty sloupce teď zobrazím, tak jsou ale prázdné. Ale ještě bychom potřebovali, kdyby to bylo možné, nějak rozlišit, jestli je to příloha. 

Workflow v návrhu bohužel počítá pouze s rokem, ročníkem a číslem (viz formulář fyzické jednotky). Je to prázdné protože se to aktuálně z metadat nijak nepřenáší - nebylo to požadováno. Je to podobné přenášení identifikátorů z issue https://github.com/proarc/proarc/issues/504. Pokud mi povíte, které elementy to v MOSD jsou tak přenášení doplním.

S přílohou by to bylo složitější, musel by se měnit model workflow. Musíte přílohu skutečně vést jako záměr? Přijde mi to spíš jako součást většího celku - není lepší ji vést jako podzáměr?

**Comment by krizovj** [comment]
Nevidím xml u ročníku ani u čísla ani u té přílohy. Když formulář vyplním a uložím, objeví se "uloženo", ale když si z formuláře překliknu do xml, tak se zobrazí prázdná stránka.

**Comment by krizovj** [comment]
Teď jsem se do toho zamotala. 
Mělo by to nakonec fungovat tak (teď myslím v případě e-článků), že založím v RDFlow jako záměr periodikum. Následně buď kliknu na tlačítko "vytvořit nový objekt", čímž vytvořím záznam tohoto periodika v úložišti nebo kliknu na jiné tlačítko, které tam zatím není a které by mělo propojit toto periodikum s nějakým již existujícím v úložišti. 
Následně už budu v úložišti zakládat ročníky a čísla a přílohy, na základě čehož mi budou vznikat v RDFlow automaticky podzáměry (ročník, číslo, příloha) a v RDFlow už nic ručně zakládat nemusím. A v RDFlow jak je tabulka se správou záměrů, tak předpokládám, že spodní tabulka bude pro podzáměry. 
Je to tak správně? 
Pokud ano a bude to tak, že co záměr, to periodikum a ostatní budou automaticky vytvářené podzáměry, pak musíme ještě znovu upravit xml :) Ptž v něm máme modely pouze u profilu K4 a ještě k tomu nám mezi nimi chybí model pro periodikum.

**Comment by nezbedova** [comment]
Ve "Správě záměrů" lze založit pouze K4 monografii, kterou už nepoužíváme! Nutně! potřebujeme mít v roletce alespoň NDK svazek monografie a STT svazek monografie. A postupně i další modely.

**Comment by MartinRumanek** [comment]
Tyto modely jsou konfigurovatelné ve workflow.xml (https://github.com/proarc/proarc/wiki/Popis-workflow.xml#definice-profilu-zpracov%C3%A1n%C3%AD-job). Aktuálně ve vašem workflow.xml nevidím nadefinovanou ani tu K4 monografii (poslala jste mi prosim aktuální soubor?).

Pro NDK svatek a STT svazek monografie bude začátek jobu vypadat takto:
```
<job name="KNAVMonografie">
         <!-- *** Vytvarene modely *** -->
        <model pid="model:ndkmonographvolume" />
        <model pid="model:oldprintvolume" />
        <!-- *** Lokalizace *** -->
        <title lang="cs">KNAV monografie</title>
        <title lang="en">KNAV Monograph</title>
        <hint lang="cs">Zpracování Monografie KNAV</hint>
        <hint lang="en">KNAV Monograph workflow</hint>
....
```

**Comment by nezbedova** [comment]
Na https://github.com/proarc/proarc/wiki/Popis-workflow.xml#definice-profilu-zpracov%C3%A1n%C3%AD-job je v příkladu jen model pid="model monograph" 
V příkladovém xml to není vůbec. 
Jak to udělat, že to má být model pid, to jsem zjistila, ale kde zjistit, co tam doplnit, to jsem nevěděla. Pokud mám v metadatové části nabídku s STT Svazek monografie, tak kde mám najít, že to je "oldprintvolume" ? Prosím přidat tuto informaci do návodu. 
V souboru, který jsem Vám poslala to nebylo. Vyřešila jsem to s M.Dudou, protože to spěchalo.

**Comment by nezbedova** [comment]
Prosím o doplnění informací o dalších modelech pro <model pid="model: ???" />

**Comment by SykoraLukas** [comment]
Seznam modelů udělán na [wiki ](https://github.com/proarc/proarc/wiki/RDflow:-podporovan%C3%A9-modely)a vytvořen na něj odkaz z [komponenty RDflow](https://github.com/proarc/proarc/wiki/RDflow)

**Comment by SykoraLukas** [comment]
Opraveno ukázkové [workflow.xml](https://github.com/proarc/proarc/wiki/Popis-workflow.xml)
