### ISSUE TITLE
Maximální velikost nahrávaných souborů

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#583]
Bylo by možné kontrolovat při nahrávání souborů do ProArcu maximální velikost toho souboru a když bude překročena ta velikost, tak napsat chybovou hlášku.
Nejde o kontrolu u hromadných importů, ale jenom u nahrávání souborů.
Maximální velikost by měla být konfigurovatelná pro každou instalaci samostatně.

**Comment by pokorsky** [comment]
Určitě to lze pokud to vývojový tým schválí. Momentálně je limit pevně stanovený na [1GB](https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/server/rest/DigitalObjectResource.java#L1124-L1127). Totéž na [klientovi](https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/UploadFile.java#L215).

**Comment by SykoraLukas** [comment]
Nutné nejprve nasadit Fedoru 4

**Comment by pavelkocourek** [comment]
Schuzka 13.5.2019
