### ISSUE TITLE
Možnost vložit existující UUID při vytváření nového výtisku ( čísla )

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#584]
Při zakládání výtisku ve Vazbách, není možné vložit manuálně UUID ( při opravách potřebuji vložit stávající UUID z Krameria ). Generuje se nové UUID. Prosím o vložení tlačítka do metadatového formuláře výtisku ve Vazbách , kde bych mohla zvolit možnost manuálně vložit UUID. Defaultně by bylo nastavené nové UUID, ale aby bylo možné ho manuálně přepsat nebo změnit.  Ručně ho mohu zadat při vytváření výtisku v postupu Uložiště => Nový objekt, ale musím pak vypsat všechny povinné položky ve formuláři, protože vytisk ještě není navázán na ročník a titul.

**Comment by nezbedova** [comment]
Ve vazbách do rozbalovacího menu Nový přidat ke všem akcím "Vytvořit s parametry" (PID)

**Comment by jkremlacek** [comment]
Menu pro vytváření nových objektů ve Vazbách by tedy vypadalo následovně:

![menu](https://user-images.githubusercontent.com/9445927/30746056-b52f0c88-9fa8-11e7-88af-49ddc2116e02.jpg)

položky menu (NDK Periodikum, ...) by byly i nadále "kliknutelné" a vytvořily by daný objekt s vygenerovaným UUID. 

Najetím myší na položku menu se rozbalí podmenu obsahující "Vytvořit s parametry" - kliknutím na něj se objeví dialogové okno:

![dialog](https://user-images.githubusercontent.com/9445927/30746061-baa04b78-9fa8-11e7-8616-55c691705ac5.jpg)

které po vyplnění vytvoří daný objekt se specifikovaným UUID.
(pole pro UUID je před odesláním kontrolováno, zda obsahuje validní UUID formát)

Prosím o potvrzení, zda tato varianta implementace vyhovuje.

**Comment by nezbedova** [comment]
Tato varianta implementace nám vyhovuje.

**Comment by jkremlacek** [comment]
Navrhovanou implementaci jsem rozšířil o volbu "Vytvořit" v podmenu, aby byla konzistentní vůči současné implementaci podmenu u NDK Číslo, které již obsahovalo volby "Vytvořit" a "Vytvořit více..."

Podmenu tedy nyní u každé položky obsahuje "Vytvořit" a "Vytvořit s parametry...", u položky NDK Číslo obsahuje "Vytvořit", "Vytvořit s parametry..." a "Vytvořit více..."

**Comment by MartinRumanek** [comment]
Bylo implementováno.
