### ISSUE TITLE
Přidat možnou autoritu "gmd" do <mods:form>

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#587]
Ve specifikaci aktualizace NDK se jedná o bod 1. (https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.30j0zll)

Upravit formulář metadat tak, aby pole <mods:form> byl combobox s možnými hodnotami "marcform" a "gmd".

**Comment by pokorsky** [comment]
Přidáno.
