### ISSUE TITLE
Přidání elementu <name> k periodiku

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#588]
Ve specifikaci aktualizace NDK se jedná o bod 3. (https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.3znysh7)

Upravit formulář titulu periodika a ročníku tak, aby se dalo zaznamenat <mods:name>, <mods:namePart>, <mods:role>, <mods:roleTerm> a <dc:creator>.

**Comment by pokorsky** [comment]
Přidáno.

**Comment by krizovj** [comment]
Vyhodí hlášku "neplatná data", pokud není vyplněn element name (i položky označené jako R). Vypadá to, že celý element "name" je brán jako povinný, i když je označený jako R.
