### ISSUE TITLE
Přidat možnou hodnotu "Konspekt" do <mods:subject>

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#594]
Upravit formuláře metadat tak, aby bylo možné zaznamenat do mods:subject klasifikační údaje věcného třídění podle Konspektu:

1. Předělat pole "Authority" v sekci "Subject" ma combobox

Možné hodnoty comboboxu: 
- czenas
- eczenas
- Konspekt

Specifikace zde: https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.4d34og8

**Comment by pokorsky** [comment]
Přidáno.
