### ISSUE TITLE
Obsazení hodnot polí katalogu

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#597]
**Postup na zopakování chyby:**

Menu > Workflow > Nový Záměr
* Dropbox `Pole:` bude obsazený hodnotami

a následně

Menu > Úložiště > Nový Objekt
* Dropbox `Pole:` nebude obsazený hodnotami

**Popis:**

Chyba se vyskytne v každém formuláři používajícím katalogy (úložiště a poté workflow, úložiště a poté katalog objektu atd.)

Katalog je pokaždé načítán pomocí:

```
/rest/v1/bibliographies?id=aleph_mzk01&_operationType=fetch&_textMatchStyle=exact&_componentId=isc_DynamicForm_4&_dataSource=BibliographyDataSource&isc_metaDataPrefix=_&isc_dataFormat=json
```

,kde je návratová hodnota JSON objekt s polem katalogů, kde každý má pole s jednotlivými fieldy katalogu. I v případě chyby, kdy se fieldy nezobrazí, je ovšem JSON objekt obsahuje, půjde tedy o chybu obsazení ListBoxu, nikoli o jejich získání z backendu. 

Edit: Chyba se vyskytuje už ve verzi 3.2

**Comment by pokorsky** [comment]
Problém bude v použití [setAutoFetchData(true)](https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/CatalogBrowser.java#L210) v kombinaci s [addDataArrivedHandler(catalogHandler)](https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-webapp/src/main/java/cz/cas/lib/proarc/webapp/client/widget/CatalogBrowser.java#L220). V případě druhého vykreslení jsou data již načtena, catalogHandler se nezavolá a pole se nepřidají.

**Comment by SykoraLukas** [comment]
Uzavírám díky opravě v Autoritách.
