### ISSUE TITLE
Chybí kontrola typu souboru při dávkovém importu JPG/JP2

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#599]
Na systémech Windows je běžné vytváření souborů s náhledy obrázků `thumbs.db`. ProArc v rámci zpracování importní dávky tyto soubory akceptuje jako obrazová data a selže až v rámci konverze tiff -> jp2 na chybě externího procesu Kakadu.

Řešením sice je vypnutí generování souboru na každé stanici zpracovatele, nicméně v případě použití sdíleného úložiště, už není možné 100% garantovat, že adresář neotevře někdo jiný a tím do něj zavede soubor s náhledy.

Nabízí se tedy elegantnější řešení v rámci aplikace zavedením nepovinné položky `blacklist` konfiguračního souboru, kde by bylo možné vyjmenovat názvy souborů, které mají být v rámci importu ignorovány a vyřazeny z importní dávky.

**Comment by pokorsky** [comment]
Znamená to, že https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/TiffImporter.java#L161-L169 vrací chybný MIME type v případě thumbs.db? Pokud ano, pak by to chtělo přehodnotit implementaci getMimetype nebo findTiff. V [javadocu](http://docs.oracle.com/javase/8/docs/api/java/net/URLConnection.html#getFileNameMap--) je odkaz na content-types.properties. V novějších verzích javy existuje [Files.html#probeContentType](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#probeContentType%28java.nio.file.Path%29), ale nezkoušel jsem. Nebo by šlo použít https://github.com/proarc/proarc/blob/fd6149e39492baf7a3a40169f36e420a218497cc/proarc-common/src/main/java/cz/cas/lib/proarc/common/imports/InputUtils.java#L63.

**Comment by jkremlacek** [comment]
Chyba nastala v Importerech JPG/JP2, kde po zavolání consume() nedošlo ke kontrole typu souboru a aplikace se pokusila konvertovat nekompatibilní typ do formátu Tiff.

**Comment by pokorsky** [comment]
V pořádku. Blacklist tedy není potřeba. Je to oprava issue #526.

**Comment by pokorsky** [comment]
Opraveno.
