### ISSUE TITLE
Volba přístupových práv K4 exportu

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#600]
Momentálně je možné v konfiguračním souboru nastavit default policy pro export do krameria pomocí:

`export.kramerius4.policy`

Navrhujeme rozšíření v podobě vyskakovacího okna po zvolení `Export` > `Export pro Kramerius 4`, kde uživatel bude moci změnit zvolenou policy pomocí tickboxu / drop-down listu. 

Default policy by zůstala zachována, aby si každá instalace mohla zvolit tu variantu, která odpovídá většině zpracovaných dokumentů.

**Comment by jkremlacek** [comment]
Rozšíření bylo implementováno. V MZK se bude nasazovat v rámci vlastní větve, protože je tato funkcionalita požadována. 

Pokud mají ostatní instituce o toto rozšíření zájem, tak je možné jej po schválení zavést do hlavní vývojové větve.

Změna nastavení `proarc.cfg` není vyžadována. Po kliknutí na `Exporty` > `Export pro Kramerius 4` se zobrazí okno:

![exportsettings](https://user-images.githubusercontent.com/9445927/32273914-bc1baecc-bf04-11e7-96f2-b6a51377a36d.png)
(tlačítko OK má automaticky focus, takže stačí zmáčknout enter, pokud `policy:public` vyhovuje)

**Comment by krizovj** [comment]
Nám by se to asi docela hodilo, ale půjde pak případně v Krameriovi normálně ta viditelnost nastavit zpátky? Aby to tam neudělalo chaos.

**Comment by jkremlacek** [comment]
V Krameriovi bude možné přístupová práva měnit i po této změně.
