### ISSUE TITLE
Automatické vybrání hodnoty aacr/rda

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#605]
Když založím nový metadatový objekt a nevyberu z roletky Pravidla popisu ani jednu hodnotu, tak se při uložení automaticky vybere a uloží aacr. Bylo by možné, aby se automaticky vybíralo rda? Nově založené objekty jsou vždy zpracované podle rda.

**Comment by pokorsky** [comment]
Souhlas, RDA by mělo být preferováno.

**Comment by pokorsky** [comment]
Formulář by také neměl umožnit vkládat vlastní text. Zvažte při načtení záznamu, kde hodnota není nastavena, zobrazit aacr. Původní záznamy tak byly vytvářeny.

**Comment by slapakovai** [comment]
Souhlasím, že vlastní text by neměl být možný.

Myslíš při stažení záznamu z katalogu? Jestli ano, tak tam by vždycky měla být nastavená nějaká hodnota. K tomu by se asi měli vyjádřit i ostatní. Takže prosím o komentáře, hlavně @luckajirku

**Comment by slapakovai** [comment]
Stejně tak ve zjednodušeném formuláři pro ečlánek by se měla automaticky ukládat hodnota rda a ne aacr. Tam je to hodně důležité, vzhledem k tomu, že ta hodnota nejde editovat ve formuláři.

**Comment by MartinRumanek** [comment]
RDA je nyní preferováno, místo roletky (combo) se používá přepínač (radio).
