### ISSUE TITLE
Test 3.4 - nelze exportovat modely NDK

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#606]
V testovací verzi 3.4 nelze provádět NDK export. Vyzkoušeno u Výtisku, periodika, monografie.
Výsledek validace:
Error- missing role. Please insert value in proarc.cfg into export.ndk.agent.creator and export.ndk.agent.archivist

**Comment by SykoraLukas** [comment]
@mduda100871 konfiguračním souboru ProArcu je nutné nastavit hodnoty NDK_Creator a NDK_Archivist. 

Návod na konfiguraci zde: https://github.com/proarc/proarc/wiki/Konfigurace#ndk-export

**Comment by mduda100871** [comment]
Nastaveno 16.10.2017, dle doporuceni pouzita SIGLA ABA007

MD
