### ISSUE TITLE
Zdokumentovat konfiguraci pro upload PDF

### ISSUE THREAD

**Issue by pokorsky** [proarc/proarc#608]
Doplnit dokumentaci konfigurace pro vytváření náhledů a thumbnail-ů u digital-born dokumentů o popis  podle https://github.com/proarc/proarc/pull/524#discussion_r118989476.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, prosím, je tahle konfigurace na wiki úplně popsaná nebo v ní něco chybí? Děkuju za kontrolu a případné doplnění.

**Comment by ZdenkaSera** [comment]
Zavírám vhledem k návrhu na uzavření, který nikdo nerozporoval.
