### ISSUE TITLE
Přidání rdamedia a rdacarrier do zjednodušeného formuláře pro ečlánek

### ISSUE THREAD

**Issue by slapakovai** [proarc/proarc#609]
Do zjednodušeného formuláře pro ečlánky prosím přidat pole pro výběr rdamedia a automatické doplnění rdacarrier.
Jedná se o element physicalDescription, subelementy authority, form a type.
Nové pole prosíme přidat mezi pole Identifikátory článku a Názvové údaje.

Celý element physicalDescription se bude jmenovat Fyzický popis, element Form se bude jmenovat Typ média.

Ideálně bychom si to představovali tak, že si v roletce Typ média (element form, hodnota rdamedia) vyberu hodnotu, podle ní se mi vyplní v modsu i elementy authority a type. Zároveň se v modsu automaticky vyplní i typ nosiče (element form, hodnota rdacarrier) a type a authority. Hodnoty jsou vždy 1:1, takže by to mělo jít.

Hodnoty v roletce Typ média by měly být: "bez média, počítač, jiný". Bez možnosti zapsat vlastní hodnoty.

Např. když vyberu v elementu form hodnotu bez média, tak se automaticky doplní authority - rdamedia a type - media a automaticky se vyplní i druhý element form s hodnotou svazek, authority - rdacarrier a type - carrier.

Automaticky vybírané hodnoty pro všechny elementy:
[Fyzický popis.xlsx](https://github.com/proarc/proarc/files/1328793/Fyzicky.popis.xlsx)

Doufám, že jsem to popsala dostatečně srozumitelně. Dost blbě se to popisuje. Kdyžtak mi napište, jestli to mám popsat ještě nějak jinak.

**Comment by SykoraLukas** [comment]
Jaké povinnosti mají elementy (physicalDescription, authority, form) mít? Kromě zmíněné autority rdamedia mají být na výběr i hodnoty gmd a marcform? Rdacarrier asi být nemusí, když se bude doplňovat automaticky, že?

**Comment by slapakovai** [comment]
Žádné jiné hodnoty nemají být na výběr.
Povinnosti:
physicalDescription M
authority MA
form M

**Comment by SykoraLukas** [comment]
Celá tahle issue se týká pouze zjednodušeného formuláře nebo i normálního? Povinnosti udělám stejné v obou formulářích, a jak ty hodnoty? V nezjednodušeném mají být na výběr i hodnoty marcform a gmd?

**Comment by slapakovai** [comment]
Celé tohle issue se týká jenom zjednodušeného formuláře. 
V normálním formuláři nám vyhovuje všechno tak, jak to tam je a není potřeba nic měnit.

**Comment by SykoraLukas** [comment]
Ale mít jeden element ve 2 formulářích s různými povinnostmi je špatně. Takže je předělám i u normálního formuláře.

**Comment by slapakovai** [comment]
ok, takže by to mělo mít stejné povinnosti i v ostatních ndk formulářích

**Comment by slapakovai** [comment]
Každopádně ten omezený výběr a automatické vyplňování chceme jenom ve zjednodušeném formuláři.

**Comment by MartinRumanek** [comment]
Implementováno.
