### ISSUE TITLE
Vícedílná monografie - eventType

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#611]
Ve formuláři pro NDK Vícedílné monografie chybí možnost vybrat "eventType" v elementu originInfo. Podle NDK je tento údaj povinný.

**Comment by pokorsky** [comment]
Přidáno. @SykoraLukas popiš prosím tuto změnu v dokumentu NDK upgrade a pak zavři issue.

**Comment by SykoraLukas** [comment]
Změna doplněna do dokumentu [NDK upgrade](https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.2s8eyo1)
