### ISSUE TITLE
Povinnost elementů ve formulářích podle NDK

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#612]
Ve formulářích v ProArcu se u některých polí liší povinnost oproti NDK:

**Všude**
- všude, kde je subelement "descriptionStandard" (v elementu recordInfo) u něj není vyjádřena povinnost a v NDK je MA

**Periodikum**
_Titul_
- titleInfo/ partNumber (mělo by být MA a je R)

_Číslo_
- titleInfo/ partNumber (mělo by být M a je MA)
- originInfo (mělo by být MA a je R)
- name/ type (mělo by být M a je MA)
- name/ namePart (mělo by být M a je MA)
- name/ role/ roleTerm/ authority (mělo by být M a je MA)
- abstract (mělo by být RA a je R)

_eČlánek_
- name/ namePart /type (mělo by být R a je MA)

**Monografie**

- originInfo-dateIssued-point (mělo by být M a je MA)

_Vícedílná monografie_
- originInfo (mělo by být M a je MA)

_Příloha monografie_
- name/ type (mělo by být M a je MA)
- name/ namePart (mělo by být M a je MA)
- physicalDescription/ form/ authority (mělo by být MA a je M)
- Abstract (mělo by být RA a je R)

**Comment by pokorsky** [comment]
@krizovj: Řeší tato oprava issues 144-197? Pokud ano, můžete je zavřít a v komentáři uvést odkaz na toto issue?

**Comment by krizovj** [comment]
Řeší pouze částečně, vypisovala jsem pouze nesrovnalosti v povinnosti polí, u starších issues jsou ještě uvedeny chybějící pole. Mám to všechno doplnit sem, ať je to na jednom místě a ta issues zavřít a odkázat z nich sem?

**Comment by pokorsky** [comment]
Ano. Myslím, že ty issues by se měly vyřešit v rámci RDA a upgradu na poslední verzi NDK metadat. Už několikrát jsme se dohodli, že je vývojový tým projde a označí to, co je ještě aktuální a nutné pro úplný popis. Pokud jde o chybějící pole, tak snad už žádná nejsou. Návrhy úprav formulářů nikdo nerozporoval (https://groups.google.com/forum/#!topic/proarc-users/4cDys1bxVy4, https://groups.google.com/forum/#!topic/proarc-users/VouxdUCbH2w). Díky.

**Comment by krizovj** [comment]
Níže jsem doplnila všechno, co bylo navíc v těch starších issues. Nyní lze uzavřít issues 144-153, 174, 179 a 197. Já je bohužel uzavřít nemůžu.

**Všude**
•	"descriptionStandard" – není vyjádřena povinnost, podle NDK má být MA
**Periodikum**
_Titul_
•	titleInfo/ partNumber (mělo by být MA a je R)
•	relatedItem – chybí 
•	identifier – chybí možnost ISBN a sysno
_Ročník_
•	partNumber (mělo by být M a je MA)
•	dateIssued – přidat možnost opakování (není možné zapsat rozsah let)
_Číslo (Výtisk)_
•	titleInfo/ partNumber (mělo by být M a je MA)
•	originInfo (mělo by být MA a je R)
•	name/ type (mělo by být M a je MA)
•	name/ namePart (mělo by být M a je MA)
•	name/ role/ roleTerm/ authority (mělo by být M a je MA)
•	abstract (mělo by být RA a je R)
•	Identifier – chybí možnost sysno
_eČlánek (také NDK článek)_
•	name/ namePart /type (mělo by být R a je MA)
•	Identifier – chybí možnost sysno a oclc
_Příloha periodika_
•	physicalDescription/ form/ authority (mělo by být R/MA a je M)
•	abstract (mělo by být RA a je R)
•	Identifier – chybí možnost sysno a oclc
•	typeOfResource – sjednotit popisy typu příloh – některé jsou v češtině, některé v angličtině
**Monografie**
_Svazek monografie_
•	originInfo-dateIssued-point (mělo by být M a je MA)
•	relatedItem – chybí 
•	Identifier – chybí možnost sysno a oclc
_Vícedílná monografie_
•	originInfo (mělo by být M a je MA)
_Příloha monografie_
•	name/ type (mělo by být M a je MA)
•	name/ namePart (mělo by být M a je MA)
•	physicalDescription/ form/ authority (mělo by být MA a je M)
•	Abstract (mělo by být RA a je R)
•	typeOfResource – sjednotit popisy typu příloh – některé jsou v češtině, některé v angličtině
•	Identifier – chybí možnost sysno a oclc
_Vnitřní část monografie_
•	Identifier – chybí možnost sysno a oclc
•	Subject/ geographic (mělo by být MA a je R)
**Kartografický dokument**
•	relatedItem – chybí 
•	Identifier – chybí možnost sysno a oclc
**Hudebnina**
•	relatedItem – chybí 
•	Identifier – chybí možnost sysno a oclc

**Comment by pokorsky** [comment]
Jsou tyhle změny v souladu s poslední NDK specifikací a ověřeny proti existujícím formulářům nebo jen posbírány z těch starých issues? Proč nebyly uvedeny ve výše zmíněném dokumentu, když se v létě připravoval? Např. `relatedItem` je RA a umožňuje vnořit celý MODS záznam znovu. To už pak bude docela komplexní formulář. Navíc to zatím nikdo k popisu nepožadoval.

**Comment by krizovj** [comment]
Ano, jsou v souladu s poslední NDK specifikací a jsou ověřeny ve formulářích. Chtěl jste ta starší issues uzavřít, tak jsem z nich vypsala všechno, co bylo navíc. Pokud nikdo nechce přidat relatedItem, tak to asi není potřeba. Bylo to ve starších issues požadováno a ve formulářích jsem to nenašla, tak jsem to přepsala sem, aby se mohla ta issues uzavřít. Pokud to nikdo nechce, tak asi není důvod to řešit, ale u těch issues nebylo žádné vysvětlení, že to nikdo nechce a není to vlastně potřeba. Takže se omlouvám a můžu relatedItem klidně vymazat. Já jsem původně kontrolovala pouze povinnosti polí, vše ostatní je tedy ze starých issues.

**Comment by luckajirku** [comment]
RelatedItem bych se nevzdávala. Teď nám to dělá bordel např. když je v MARCu pole 700, 710, 711 s podpolem t, tak se vytvoří x dalších výskytů name, které pak odmazáváme, protože takhle nedávají smysl. A byly by i další případy z jiných polí, kde by se to mělo překlopit právě do relatedItem.
A jinak třeba u starých tisků pro údaje z 510 - jsou povinné i u minimálního záznamu a měly by být i v MODS.

**Comment by SykoraLukas** [comment]
Element <mods:relatedItem> je řešen jako samostatný issue #640.

**Comment by SmejkalovaAnna** [comment]
V nové verzi 3.4 - beta mi hází u čísla, ročníku i titulu hlášku Neplatná data pokud nemám vyplněné povinné podpoložky Name Part a Role - authotity, ale nadřazená položka NAME je MA.

**Comment by MartinRumanek** [comment]
Kouknul jsem do zdrojových kódu a jde o to, že ty jednotlivé položky formulářů jsou docela hloupé a neví, že jsou součástí většího celku, který nemusí být povinný.

Jakmile má atribut 'required', tak je vyplnění vynucováno. Tento atribut se může u těchto podsložek vypnout s tím, že popisek zůstane. Stačilo by vám to?

**Comment by krizovj** [comment]
Já myslím, že u elementu "name" se to může u všech těch podpoložek vypnout u modelů ročník, číslo a titul periodika i klidně svazek monografie, ptž v žádném z těch modelů není element "name" povinný. 

Jinak u toho čísla, když nevyplním M položky, tak některé to označí a některé ne:
![cislo](https://user-images.githubusercontent.com/21309201/33473916-a7bad2f6-d678-11e7-8d6d-d0afb2dc7b82.jpg)

**Comment by tumovam** [comment]
Ve formuláři pro **Přílohu periodika** se stále liší povinnost.
- nyní: physicalDescription - form - authority - **M**
- podle NDK: physicalDescription - form - authority - **R/MA**

**Comment by tumovam** [comment]
Podle NDK **_Svazek monografie_** je atribut **Point** elementu <dateIssued> povinný (**M**). Neplatí ale, že by každá monografie měla "start" a "end". Když se v ProArcu vyplní **Date** (**M**) v elementu <dateIssued> a dá se Uložit, ProArc napíše chybovou hlášku: 
![neplatna data](https://user-images.githubusercontent.com/31240271/36154365-838b68da-10d1-11e8-90c3-000539897de8.PNG)
Chápu, že podle NDK u **Point** musí zůstat povinnost vyplnění **M**, ale chybová hláška je matoucí, když monografie nemá rozmezí dat vydání předlohy. Nebylo by možné tuto chybovou hlášku odstranit?

**Comment by SykoraLukas** [comment]
Na schůzce ProArcu bylo vysvětleno, že pole physicalDescription (authority) musí mít povinnost M, vzhledem k tomu, že dochází ke kontrole RDA pravidel. Pokud by se toto pole nevyplnilo, nelze kontrolovat RDA pravidla. 

Poslední koment od @tumovam je shodný s #706

**Comment by tumovam** [comment]
Ano, poslední komentář sem asi nepatří, bylo na něj založeno nové issue #706
