### ISSUE TITLE
 testovací 3.4 - u STT chybí nastavení založení podle RDA

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#636]
U STT svazek monografie chybí roletka "Zvolte pravidla popisu".

**Comment by jkremlacek** [comment]
Nejedná se o chybu. Požadavek na přidání `Description Standard` byl pouze pro NDK modely viz https://github.com/proarc/proarc/issues/590.

Pokud má být toto pole přidáno i pro STT modely, tak je potřeba napsat seznam všech modelů, kterých se to týká.

**Comment by nezbedova** [comment]
Toto pole by mělo být i u STT. Týká se to STT Vícedílná monografie a STT Svazek monografie.

**Comment by jkremlacek** [comment]
Pouze se ujistím, že u STT Vícedílná monografie má být `Description Standard` také? Ptám se, protože u NDK Vícedílné monografie přítomný není.

**Comment by nezbedova** [comment]
krizova@knav.cz Projevily se změny z AACR na RDA v polích, která jsou ve formuláři NDK Vícedílná monografie? Zapisuje se do metadat záznam o AARC/RDA?
Pokud ano, tak to potřebujeme u NDK i STT Vícedílných monograií.
Pokud ne, stačí to STT Svazek monografie.

**Comment by krizovj** [comment]
Ve standardu pro záznam vícesvazkové monografie údaj o pravidlech vůbec není uveden. Nebyl ani v předchozí verzi. Takže by to mělo stačit pro svazek.

**Comment by nezbedova** [comment]
Myslela jsem, zda to je u NDK Vícedílná monografie.

**Comment by krizovj** [comment]
Není
