### ISSUE TITLE
chybova hlaska pri exportu

### ISSUE THREAD

**Issue by dikeckert** [proarc/proarc#641]
Pri nekterych exportech do K4 se objevi neocekavana chyba.
Export probehne, v Proarc logu pouze:
Oct 12, 2017 5:38:17 AM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level
Oct 12, 2017 8:52:42 AM edu.harvard.hul.ois.jhove.JhoveBase init
SEVERE: Testing SEVERE level

**Comment by jkremlacek** [comment]
Neočekávaná chyba má možnost zobrazit detaily chyby. Pokud je to možné zreplikovat, tak prosím přidejte tento záznam. 

Bez dalších detailů mě pouze napadá možnost, že server vrátil 501 Request Timeout, protože export trval už moc dlouho a klient nedostal v limitu odpověď.

**Comment by MartinRumanek** [comment]
Pokud tomu rozumím dobře, tak export proběhne v pořádku až do konce.

Je to určitě způsobené starým JHovem, nenašel jsem zdrojové kódy staré verze, ale podle dekompilátoru tam takový výpis je

```
this._logger.severe("Testing SEVERE level");
```
Čert ví co to tam dělá,... Investigovat to zatím nebudu, protože v aktualizované verzi JHove to už není - a ta bude součástí verze 3.4. (https://github.com/proarc/proarc/issues/638)
