### ISSUE TITLE
testovací 3.4 - NormalPage formulář zmizí po načtení

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#645]
V importu / doEditoru po načtení dat zmizí metadatový formulář, pokud je model NormalPage nebo jiný z něj odvozený (STT, ...). 

Formulář se znovu zobrazí v případě, že dojde ke změně velikosti okna prohlížeče.

Chyba je způsobená work-around-em použitým kvůli jiné chybě v SmartGWT, viz https://github.com/proarc/proarc/pull/613.

**Comment by jkremlacek** [comment]
V rámci testování v MZK se podařilo objevit bizardní bug při připojování naskenovaných stránek k rodiči: 

![glitchedimport](https://user-images.githubusercontent.com/9445927/32611044-d0fe8e2a-c564-11e7-97d4-1397d9ba15c3.png)

opraveno odstraněním volání draw. Aby se zamezilo zároveň i předchozí chybě, tak musí být výška note nastavena hard-coded hodnotu, aby note přesáhl dolní hranici stránky.

**Comment by MartinRumanek** [comment]
To stejné se stane i v případě Vícedilné monografie, kde je ten formulář taky krátký.
