### ISSUE TITLE
Nejvyšší úroveň vícesvazkové monografie - chybějící element language v DC

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#651]
U vícesvazkových monografií se v případě záznamu nejvyšší úrovně nepřevede do DC element language, i když v MODSu je. 
Potřebovali bychom v DC element language kvůli stahování dat z ČDK do Europeany.

**Comment by MartinRumanek** [comment]
Můžete prosím dodat příklad MODsu, ze kterého se to nepropíše? 

V případě, že je jazyk uvedený jako code, tak se element propisuje, např z:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<mods:mods version="3.5" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xlink="http://www.w3.org/1999/xlink">
    <mods:genre>volume</mods:genre>
    <mods:identifier type="uuid">d8c14bcd-e0f7-4134-94b2-3722d9122995</mods:identifier>
    <mods:language objectPart="translation">
        <mods:languageTerm authority="iso639-2b" type="code">eng</mods:languageTerm>
    </mods:language>
    <mods:part type="volume"/>
    <mods:recordInfo>
        <mods:recordCreationDate encoding="iso8601">20171115T161553</mods:recordCreationDate>
        <mods:recordChangeDate encoding="iso8601">20171115T161704</mods:recordChangeDate>
        <mods:descriptionStandard>rda</mods:descriptionStandard>
    </mods:recordInfo>
    <mods:typeOfResource>text</mods:typeOfResource>
</mods:mods>
```

se vyrobí DC i s language:
```
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
  <dc:type>text</dc:type>
  <dc:type>volume</dc:type>
  <dc:type>model:ndkmonographvolume</dc:type>
  <dc:identifier>uuid:d8c14bcd-e0f7-4134-94b2-3722d9122995</dc:identifier>
  <dc:language>eng</dc:language>
</oai_dc:dc>
```

**Comment by krizovj** [comment]
Ale v tomhle příkladu jde o svazek monografie (v elementu genre je uvedeno volume), já myslím nejvyšší úroveň vícesvazkové monografie. U té je v MODSu v elementu genre uvedeno title.

Například: Listář k dějinám školství kutnohorského (https://kramerius.lib.cas.cz/search/handle/uuid:4c8a8d80-6575-4338-abb4-438b117c0cb5)
V MODSu je element language uvedený jako code:

<mods:language>
<mods:languageTerm authority="iso639-2b" type="code">cze</mods:languageTerm>
</mods:language>

ale v DC element language chybí:
https://kramerius.lib.cas.cz/oaiprovider/request?verb=GetRecord&metadataPrefix=oai_dc&identifier=uuid:4c8a8d80-6575-4338-abb4-438b117c0cb5

Nemohlo by to být tím, že element language není pro tuto úroveň uvedený ve standardu NDK? I když není v NDK, tak bychom ho tam potřebovali mít kvůli té Europeaně.

**Comment by MartinRumanek** [comment]
Aha, v té nejvyšší úrovni není. 

> Nemohlo by to být tím, že element language není pro tuto úroveň uvedený ve standardu NDK? I když není v NDK, tak bychom ho tam potřebovali mít kvůli té Europeaně.

Ano, proto tam nebyl. Ale přidat ho můžeme.

**Comment by krizovj** [comment]
Tak to by bylo super. Bude opakovatelný, jako je u jiných záznamů? V některých případech tam totiž musí být uvedeno více jazyků.

**Comment by MartinRumanek** [comment]
Ano, byl by opakovatelný. Jedna věc je převádění elementu z MODS do DC, to je snadno přidatelné.

 Druhý problém je, že language vůbec uvedený ve vícesvazkové monografii? Vadí to?

**Comment by krizovj** [comment]
Domluvila jsem se s NK, že by to měli přidat do standardu a mělo by to být do konce roku. Musejí to ještě otestovat. Ve standardu to bude jako doporučené, nebude to povinný element, ale aspoň že tam bude.

**Comment by krizovj** [comment]
Už je to přidáno v aktualizovaném standardu pro monografie. U nejvyšší úrovně vícesvazkové monografie je přidán element language jako volitelný.

http://www.ndk.cz/standardy-digitalizace/DMFmonografDok_13.pdf

**Comment by krizovj** [comment]
Nešlo by to přidat do nějaké brzké aktualizace? Hodilo by se nám to kvůli předávání dat do Europeany.

**Comment by SykoraLukas** [comment]
Ano, bude přidáno v brzké době.
