### ISSUE TITLE
Typ stránky: Obálka

### ISSUE THREAD

**Issue by hartmanova-mkp** [proarc/proarc#657]
V MKP opravdu velmi postrádáme typ stránky "Obálka", který tam dříve byl a nyní po aktualizaci na verzi 3.4.-shapshot ji již v nabídce nemáme. Je to nějaká chyba na naší straně, nebo byl tento typ stránky z nějakého důvodu z nabídky odstraněn záměrně?
Pokud byl odstraněn záměrně, rádi bychom se přimluvili za jeho opětovné zařazení do nabídky - máme obálky u zhruba každého třetího dokumentu.

**Comment by MartinRumanek** [comment]
Obálka byla v rámci issue https://github.com/proarc/proarc/issues/309 přejmenována na Desky vcelku (cover). Viz komentář https://github.com/proarc/proarc/issues/309#issuecomment-133331873

**Comment by MartinRumanek** [comment]
Je to tak v pořádku? Je issue možné zavřít?

**Comment by hartmanova-mkp** [comment]
Koukala jsem na to. Za nás nemůžu říct, že by to byl ideální stav, ale už jsme s tím začali pracovat - to máme z toho, že jsme jeli tak dlouho v jedné verzi... :)
Je tedy možné issue zavřít.
