### ISSUE TITLE
Problem s prazdnym obsahem OCR datastreamu

### ISSUE THREAD

**Issue by mduda100871** [proarc/proarc#658]
Zdravim,

narazili jsme na celkem neprijemny problem, ktery vznika ve vyrobe, ale dopad se projevi vetsinou az v prezentacni vrstve, tedy Krameriovi. A souvisi zrejme take uzce s Fedorou.

Pokud ma OCR na vstupu do ProArcu 0B (opravdu je prazdny, zadna mezera, nic, nulova velikost), tak pri exportu z ProArcu (primo pro Krameria, nikoliv NDK, i kdyz tam ten problem bude take, setkal jsem se s tim uz nekolikrat i jinde v jinych knihovnach - validatorem NK prazdne OCR projde) ma prislusny datastream, kam se uklada OCR, ve FOXML "prazdno" mezi elementy, tedy presne takto: `<foxml:binaryContent></foxml:binaryContent>`.

Tento stav zapricini to, ze selhava ingest na urovni samotne Fedory - vypadne NullPointerException, zrejme v tom hraje roli xml parser, ktery Fedora pouziva. Overil jsem to primo na urovni Fedory (mimo Krameria) ingestem prostrednictvim jejich shell skriptu.

No a aby to nebylo tak jednoduche, tak ingest selhava ve Fedore verze 3.8.1, na verzi 3.5 takto prazdny element projde. Jine kombinace verzi jsem nezkousel.

Pokud do datastreamu ve FOXML doplnim rucne OCR s mezerou zakodovanou do base64, tak ingest projde bez problemu.

Nyni tedy vznika otazka co s tim? Dle meho nazoru by tento stav mela resit uz vyroba, nikoliv prezentace, protoze takto prazdnych elementu muze byt mnoho nahodne a to nemuze resit Kramerius (musel by kontrolovat obsah datastreamu pro OCR a pripadne modifikovat...coz je v rozporu s tim, ze prezentacni vrstva by nemela modifikovat data/metadata).

Reseni, ktera me napadaji:
- pri exportu z ProArcu do FOXML vypustit datastream kompletne, pokud je OCR prazdne, nebo
- pri exportu doplnit v base64 kodovani mezeru do datastreamu v pripade, ze je OCR prazdne, nebo
- nejak jinak....

A jeste jedna "zajimava" vec. Pokud provedu ve Fedore verze 3.5 export digitalniho objektu (v archivnim modu), tak Fedora do prazdneho OCR dastreamu doplni sama blank znaky...

MD

**Comment by MartinRumanek** [comment]
Myslím, že je obecně dobrá bestpractice aby textové soubory končili newline znakem (viz např. posix http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206)

Proarc by mohl kontrolovat, jestli je poslední znak nový řádek a pokud ne, tak ho přidá. To by mohlo fungovat, ne?

**Comment by mduda100871** [comment]
Presne neco takoveho jsem mel na mysli. V tomto kontextu je znak noveho radku na stejne urovni jako mezera...rekl bych. Takze ano.

MD

**Comment by svetlym** [comment]
Jak mezera, tak newline, jsou v rámci textového přepisu významové znaky. V tomhle případě to nejspíš ničemu vadit nebude, ale zní mi to jako jedna z těch věcí, kdy si člověk hodiny láme hlavu, odkud se mu v datových souborech bere tenhle znak, když ve zdrojových datech není...

Prázdný XML element by měl být validní, takže chyba je na straně Fedory. Pokud to není možné opravit ve Fedoře a je potřeba workaround, tak bych se ho snažil udělat tak, aby neměnil uložená data data - tzn. Kramérius by měl "oslashovat" prázdný XML element před tím, než ho pošle do Fedory a zase ho "odslashovat", když ho vytahuje ven.

Další věc je, že to není nutně jen problém OCR souborů, ale obecně jakéhokoliv prázdného elementu v XML. Když to obejdete newline characterem, problém to nemusí vyřešit a ten další výskyt nejspíš někdo obejde jinak...

**Comment by mduda100871** [comment]
Neni sporu o tom, ze problem je na strane Fedory. Opravu Fedory ale nikdo resit nebude, i vzhledem k tomu, ze rada 3 je mrtva a pochybuji, ze nekdo tady ma ambice forkovat a udrzovat dal zdrojaky.

Nicmene jsem zasadne proti tomu, aby tento problem resila prezentacni vrstva (to neznamena, ze nebudu prehlasovan).

Resime konkretni problem OCR, nikoliv obecne validitu prazdneho xml tagu, a to jeste v exportnim profilu specialne pro Krameria. Pokud by mel Kramerius opravovat FOXML (on to totiz dostava v tomto konkretnim pripade ve FOXML "uvnitr"), tak to znamena vyznamny narust rezie pri importech u vetsich instanci aplikace.

Spise bych se klonil k tomu, aby export proste neobsahoval vubec OCR datastream, pokud je nulovy.

MD

**Comment by mduda100871** [comment]
Vlastne jeste doplneni. On to nebude problem jen exportu ve FOXML pro Krameria, ale take u NDK balicku, ktere budou obsahovat nulove OCR. A teprve interni konvertor Krameria z toho bude sestavovat FOXML - tady by mozna naopak bylo misto, kde to Kramerius resit ma. 

Takze mame dilema...co na to vyvojari?

MD

**Comment by jkremlacek** [comment]
Podle mě nejde o chybu na straně ProArc-u - ocr zasílá dál, tak jak ho dostalo (0 B velikost). Na místě by spíš bylo, aby i ostatní nástroje uměly přijmout nulové ocr, tak jako ProArc.

Další věc je, že příští rok by Kramerius měl přecházet na Fedoru 4, kde se daná chyba už nemusí vůbec vyskytovat.

Zvláštní ovšem je, že Fedora ProArc-u nulové ocr zvládne, ale Fedora Krameria už ne, přičemž obě jsou v3, je tedy možné, že nejde o bug Fedory, ale pouze o problém s nastavením, bylo by možné poskytnout log NPE chyby při ingestu?

**Comment by MartinRumanek** [comment]
Chtěl bych vidět ten log z Fedory, stejně jako @jkremlacek 

> Spise bych se tedy klonil k tomu, aby export proste neobsahoval vubec OCR datastream, pokud je nulovy.

To se zase úplně nelíbí mě, protože se ztrácí informace, že OCR nad daným dokumentem proběhlo. Např. v MZK takové dokumenty cíleně hledají a chybějící OCR postupně doplňují. Navíc co se stane v tomto případě s alto.xml? Pokud bude OCR prázdné neuloží se taky?

Pokud je to chyba Fedory, tak by OCR textový formát měl mít takový obsah, aby ho Fedora byla schopna ingestnout. Nějaké workaroundy na stranu Krameria rozhodně nepatří (taky nerozumím tomu jak by  oslashování a odslashování mělo fungovat).
Prázdný řádek mi pořád přijde jako případné validní řešení.

**Comment by mduda100871** [comment]
Napada me nyni jedine k tomu zvladnuti - neprobiha import do Fedory ProArcu pomoci externi reference OCR? Nebo ProArc nejprve sestavi FOXML a pak ho teprve preda Fedore k ingestu?

Protoze vsechny instance Fedory (pod ProArcem a pod Krameriem) jsem instaloval ja a zadne nestandardni zmeny v konfiguraci jsem nedelal, mate na mysli tedy napr. "deaktivaci" validace pri parsovani xml?

Fedora 4 - ano, ale nez bude realne nasazena do provozu, to muze trvat treba i rok. Tento problem nas pali ale uz ted.

Co znamena NPE log? Mate na mysli log Fedory?

MD

**Comment by jkremlacek** [comment]
Ano, myslel jsem log chyby, kterou vyhodi Fedora.

**Comment by svetlym** [comment]
> taky nerozumím tomu jak by oslashování a odslashování mělo fungovat

Například tak, že se při sestavování FOXML před uložením do Fedory obsah elementů ozávorkuje a při čtení zase odzávorkuje. Takže vstupní FOXML bude mít <element></element>, ve Fedoře bude uloženo <element>()</element> a když si nechám foxml vyexportovat, tak v něm bude opět <element></element>.

Samozřejmě pokud je to možné vyřešit nastavením Fedory, tak to je mnohem lepší řešení (pokud teda cenou za to nebude vypnutí validace XML).

**Comment by mduda100871** [comment]
Cerstve aktualni log Fedory v priloze - testovano na 3.8.1.

MD

[fedora.log.zip](https://github.com/proarc/proarc/files/1506125/fedora.log.zip)

**Comment by mduda100871** [comment]
A jeste log z Krameria...

[sterr.err.zip](https://github.com/proarc/proarc/files/1506143/sterr.err.zip)

**Comment by mduda100871** [comment]
Kdyz se ted na ten log divam s odstupem, tak si rikam, zda-li to nakonec nebude znamy problem s Tomcatem 8 a nevalidni http hlavickou...

**Comment by MartinRumanek** [comment]
Je to bug přímo ve Fedoře, který není možné obejít konfigurací.

 https://github.com/fcrepo3/fcrepo/blob/master/fcrepo-server/src/main/java/org/fcrepo/server/storage/translation/handlers/FOXMLContentHandler.java#L472
V případě prázdného elementu se nezavolá metoda characters, nenastaví se m_elementContent a později při konverzi do base64 (https://github.com/fcrepo3/fcrepo/blob/master/fcrepo-server/src/main/java/org/fcrepo/server/storage/translation/handlers/FOXMLContentHandler.java#L589) 
to vyhodí NullPointerException.

Můžeme to opravit, ale to už nemá smysl. Nějaké workaroundy do Krameria taky nedávají smysl (Kramerius by měl vracet co je ve Fedoře). Za mě je optimální řešení jeden newline v případě prázdného OCR (ten znak sám o sobě nějaký význam nemá).

**Comment by mduda100871** [comment]
Souhlasim s @MartinRumanek, resime jen OCR, kde nevidim osobne z hlediska fulltextoveho vyhledavani problem v tom, ze v prazdnem OCR je pouze newline.

MD

**Comment by mduda100871** [comment]
Jen doplnim, ze by bylo fajn, pokud nebudou nejake zasadni namitky od ostatnich, ktere by to nasmerovaly nekam jinam, aby oprava jeste spadla do stavajici bety a vysla pak v oficialnim buildu...

MD

**Comment by svetlym** [comment]
Ještě mám k tématu jeden dotaz:

To, že někdo smazal importní adresář před přiřazením nadřazeného objektu, a tedy před importem do Fedory, se nám nestalo poprvé. Díky tomu v historii importů máme několik položek, které nejdou odstranit a kliknutí na ně vyhodí chybu a zapíše ji do logu. Je možné se jich nějak zbavit?
