### ISSUE TITLE
E-články: zjednodušený formulář a formulář

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#662]
Bylo by možné u e-článků ve zjednodušeném a normálním formuláři sjednotit seznam typů článků (genre/type=)? Posílám seznam položek, které by měly být v obou formulářích a dvě poslední položky bychom potřebovali přidat, zatím nejsou ani v jednom z formulářů:

- zpráva
- obsah
- reklama
- abstrakt
- úvod
- recenze
- věnování
- bibliografie
- úvodník
- předmluva
- hlavní článek
- rejstřík
- nespecifikován
- obálka
- nekrolog
- medailonek
- tiráž
- rozhovor
- anotace
- titulní list (nově)
- adresář (nově)

**Comment by krizovj** [comment]
Bylo by možné, aby se ty dva nové typy (titulní list a adresář) pak v MODSu přeložily takto?
titulní list = title page
adresář = directory

**Comment by jkremlacek** [comment]
Vyhovovalo by abecední uspořádání? (s tím, že `nespecifikován` by zůstalo na konci seznamu)

**Comment by krizovj** [comment]
Rozhodně vyhovuje
