### ISSUE TITLE
Úprava hlavičky mets souboru organization

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#666]
Dle vyjádření NK máme:
- v hlavičce mets souboru <mets:metsHdr> je chybně vyplněn údaj o tvůrci balíčku <mets:agent ROLE="CREATOR" TYPE="ORGANIZATION"> - uvedena je hodnota „ProArc“ zatímco předepsaná hodnota dle standardu má představovat kód instituce (či firmy) - správná hodnota tedy odpovídá „ABA007“

Můžeme to někde nastavit?

**Comment by SykoraLukas** [comment]
Mohl bych se zeptat, kdy proběhl export?
Hodnota "ProArc" byla nastavena ve staré verzi, v nové verzi se nastavuje hodnota CREATOR a hodnota ARCHIVIST v konfiguračním souboru viz #515. Nyní by při exportu již měla být nastavena hodnota ABA007, jak @mduda doplnil do konfiguračního souboru.

**Comment by nezbedova** [comment]
21. 11. 2017

**Comment by MartinRumanek** [comment]
V testovací verzi se chyba neprojevuje (v3.4-beta). Konfigurace je popsaná zde
https://github.com/proarc/proarc/wiki/Konfigurace#ndk-export

**Comment by SykoraLukas** [comment]
Mohla byste mi prosim poslat balicek, ktery jste odesilala na testovani, na mail lukas.sykora@accenture.com? Zkusim podrobneji zanalyzovat. Dekuji

**Comment by nezbedova** [comment]
Poslala jsem jeden úplně nový s jedním výtiskem, ve kterém jsou čtyři strany.
A ten, který jsme posílali ke kontrole, pošlu za chvilku. Je dost velký.

**Comment by SykoraLukas** [comment]
Po prozkoumani balicku jsem zjistil, ze stale exportujete z proarcu verze 3.3. V info o proarcu by mela byt informace ze jde o verzi 3.3. Dal by se vyexportovat balik z testovaciho serveru, kde je nasazena 3.4 beta verze?

**Comment by nezbedova** [comment]
Jak strará data to mohou být? Nebo chcete nový import a export?

**Comment by nezbedova** [comment]
Nově založený a vyexportovaný balíček z testovací verze ProArcu. Jak jsem spěchala, vzala jsem první čtyři soubory netušíc, že jsou to jen desky a prázdné strany.
