### ISSUE TITLE
NDK  - Změna specifikace v info.xml

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#667]
V souboru info.xml je chybně uvedena verze specifikace v elementu <metadataversion>
Je tam 1.5 a má být 1.6

**Comment by SykoraLukas** [comment]
Z jaké verze proběhl export? Ve verzi 3.4 by již mělo být opraveno.

Info o verzi Proarcu, ze které proběhl export najdete v souborech amd_mest pod elementy: 
<premis:creatingApplicationName>
<premis:creatingApplicationVersion>
<premis:dateCreatedByApplication>

**Comment by SykoraLukas** [comment]
Bylo exportováno z verze 3.3. V nové verzi 3.4 je toto již opraveno.
