### ISSUE TITLE
Načtení zvukových souborů

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#677]
Vytvořit importní profil pro načtení zvukových dokumentů - gramofonové desky. Vychází ze [specifikace](https://docs.google.com/document/d/1IQ-cdMfPb59gkLyt5ygxNjSRkXfYlSgThqo_48M-uTI/edit).

**Comment by svetlym** [comment]
Jak to vypadá s releasem verze obsahující načítání zvukových souborů?
