### ISSUE TITLE
Nefunguje přidělení URN:NBN po založení nového dokumentu pod zadaným uuid

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#682]
Když při vytváření nového objektu ručně zadám uuid a následně mu zkusím přidělit URN:NBN, výsledný dialog Registrace URN:NBN obsahuje jen text "Žádné položky k zobrazení". V logu k tomu nic není (zkoušel jsem to hned po restartu a poslední záznam v logu je "Server startup in XY ms").

**Comment by jkremlacek** [comment]
Přidělení URN:NBN se chová stejně i v případě, že je UUID vygenerované náhodně.

Popisovaná situace spíš bude souviset s tím, že je objekt prázdný / nemá připojené potomky (nejspíš až po stranu, zkusil jsem vytvořit periodikum a pod něj připojit prázdný ročník a nastala stejná situace).

Děje se chyba i v případě, že pod objekt se specifikovaným UUID připojíte strany?

**Comment by svetlym** [comment]
První chyba nastala poté, co kolegyně nejdříve vytvořila nový objekt (periodikum) pod novým uuid a kompletně jej zpracovala a pak přišla s tím, že je to další ročník periodika, které bylo zpracované v Siriovi a máme ho už naimportované do K5. Nejdřív zkoušela poeditovat identifikátor uuid přímo v metadatech ročníku (viz další dvě související issues), což nešlo. Pak jsme vytvořili nový objekt (periodikum) pod uuid existujícího periodika a pod něj přeřadili už zpracované podobjekty (tj. nově zpracovaný ročník). K výsledku nejde přidělit URN:NBN.

Já jsem to pak ještě pro jistotu zkoušel na testovací verzi proarcu s nastaveným testovacím resolverem. Tam jsem žádné podobjekty nevytvářel, zkoušel jsem přidělení pro samostatný kořenový objekt (periodikum).

**Comment by svetlym** [comment]
Problém přetrvává i ve verzi 3.4.2. Je to docela nepříjemné, nemůžeme přidávat nově naskenované ročníky k periodikům zpracovaným původně pro K3. Zpracovávat to celé znovu by bylo velmi pracné, má to desítky ročníků - nehledě na to, že i tak bychom asi chtěli zachovat původní uuid.

**Comment by svetlym** [comment]
Po znovuvytvoření celé struktury nám to funguje, zřejmě jde o podobný problém jako u #744.

Každopádně díky za spolupráci, problém je vyřešen.
