### ISSUE TITLE
Zadávání uuid při vytváření nového objektu

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#683]
Enhancement: Při zadávání uuid by mělo stačit vložit uuid (číslo) bez nutnosti přidat prefix "uuid:". Je to sice napsané v tooltipu na input boxu, ale je to natolik neintuitivní, že se uživatelům nelze divit, když si toho nevšimnou.

S tím souvisí: Pokud uživatel zadá string v chybném formátu, měl by mu vyskočit dialog s informací, co udělal špatně a jak to má být správně. Momentálně se nedozví nic, takže nutně musí mít pocit, že to nefunguje.

**Comment by jkremlacek** [comment]
**ad odezva:**
Ve kterém editoru nedochází k žádné zpětné vazbě v případě zadání špatného UUID? V _editoru připojených objektů_ se pole označí s hláškou `Neplatná hodnota` a stejně tak v _Úložiště > Nový objekt_. 

**ad podrobnější hláška + prefix:**
Mrknu na to, jak by to šlo udělat.

**Comment by svetlym** [comment]
Tohle se netýká editoru, ale zakládání nového objektu s uživatelsky zadaným uuid. Je tam na to speciální input box.

**Comment by jkremlacek** [comment]
Špatně jsme se pochopili - editorem myslím "stránku" na které zakládání provádíte, protože nový objekt se specifikovaným UUID je možné založit na více místech.

**Comment by svetlym** [comment]
Menu -> Nový objekt

**Comment by jkremlacek** [comment]
A máte aktuální verzi ProArc-u?

V případě, že zkusím zadat nevalidní UUID, tak dostávám hlášku o neplatné hodnotě spolu s grafickým označením: 

![createobjectinvalid](https://user-images.githubusercontent.com/9445927/35803778-5189a8a4-0a75-11e8-93ed-89de567825c5.png)

**Comment by svetlym** [comment]
Aha, ono je to v tooltipu ikonky s vykřičníkem, toho jsme si s kolegyní nevšimli. Ostatně té nápovědy v tooltipu editboxu jsem si taky všiml až po delším zkoumání.

Moje poznámka se týkala také toho, že "Neplatná hodnota" není moc informativní zpráva. Je to lepší než nic, ale nepomůže to uživateli s tím, proč je neplatná a jak to má spravit. Lepší by bylo něco jako "Neplatná hodnota. Identifikátor musí začínat "uuid:" (respektive ještě lepší by bylo, kdyby ten prefix "uuid:" nebyl potřeba).

A ten dialog by ideálně měl vyskočit hned po odeslání požadavku, ne až po najetí myší na červený vykřičník.

**Comment by jkremlacek** [comment]
S tím souhlasím, pouze jsem se ujišťoval, jestli není nějaký editor i bez této základní hlášky, kdy by si uživatel nemusel být jistý funkčností systému.

**Comment by jkremlacek** [comment]
Implementováno. Při chybně zadaném UUID nyní vyskočí okno s podrobnostmi chyby.

Rozšíření detekuje:
- přítomnost prefixu `uuid:`
- přítomnost neplatných znaků
- neplatnou délku
- počet pomlček
- špatnou délku jednotlivých segmentů oddělených pomlčkami

Ukázka hlášení:
![invaliduuidvalidation](https://user-images.githubusercontent.com/9445927/35967930-b01b27b8-0cc2-11e8-8033-8fc93c04e941.png)

**Comment by jkremlacek** [comment]
Před zavedením změn do hlavní větve bych poprosil členy vývojového týmu o vyjádření, zda souhlasí s úpravou (případně je připomínkovali).

**Comment by svetlym** [comment]
Perfektní, díky.

S úpravou rozhodně souhlasím.

**Comment by nezbedova** [comment]
S úpravou souhlasím.
