### ISSUE TITLE
Změna uuid u existujícího objektu

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#684]
Když uživatel zkusí změnit uuid objektu v editoru metadat (klikne do editboxu, vloží nové uuid, dá uložit), tak se stane to, že objektu zůstane původní uuid a nové uuid se přidá jako další položka. Objekt pak má dva identifikátory uuid, což by rozhodně nemělo nastat.

- bylo by hezké, kdyby uuid změnit šlo (samozřejmě jen v případě, že objekt nemá přiřazeno URN:NBN, protože to je s uuid svázané). Teď to jde udělat jen založením nového objektu a přesunem podřazených objektů pod něj (což je teda v zásadě ok, nedělá se to až tak často).

- pokud měnit uuid existujícímu objektu nepůjde, tak by uuid vůbec nemělo jít editovat (input box by měl být disabled).

- určitě by nemělo jít přidat druhé uuid (nemělo by to výt vůbec v nabídce identifikátorů, nebo by měl pak uživatel alespoň dostat dialog s oznámením, že objekt může mít jen jedno uuid).

**Comment by svetlym** [comment]
Nevím, jestli se tohle dá považovat za enhancement - pokud jde takhle vyrobit nevalidní PSP (jako že objekt s vícero uuid, předpokládám, validní nebude), tak je to určitě bug.

V opačném případě to nemá moc velkou prioritu - uživatel to může sám opravit, když se mu to náhodou stane.

**Comment by SykoraLukas** [comment]
Nejde zakázat vytvořit druhé uuid, protože se muze stat, že uživatel potřebuje zadat uuid, které je již neplatné.

Tedy jedno uuid je platné a všechny ostatní (které zadá uživatel), se převedou do stavu neplatné.
