### ISSUE TITLE
Archivní balíček PDF (export)

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#687]
Potřebovali bychom, aby bylo možné vyexportovat archivní balíček pro PDF. Už je v nových standardech NDK pro elektronické publikace:
Podkapitola 2.3 Definice AIP balíčku: http://www.ndk.cz/standardy-digitalizace/dmf_eborn_perio

Obsah balíčku:

- info.xml - údaje o vzniku balíčku
- original (složka)
- hlavni_METS.xml
- soubor MD5

Zatím není nutné toto issue řešit, dávám ho sem jen, aby se na to nezapomnělo. Musíme počkat na aktualizaci standardu, kvůli možnosti rozdělení PDF do více částí. Zatím je podle standardu možné mít v balíčku pouze jedno PDF na číslo (máme je rozdělené na články).

**Comment by tumovam** [comment]
Skládaná periodika: https://old.ndk.cz/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf
- 2.2 Definice SIP balíčku _(... složka  může  obsahovat  více souborových  formátůpro  jednu  intelektuální  entitu  a  více  souborů  stejného  formátu  pro  jednu intelektuální entitu)_
- 2.3 Definice SIP balíčku v případě že jsou doskeny zpracované jako obrazy

**Comment by kerschfilip** [comment]
ve verzi 3.9.1 je možné exportovat NDK balíček a archivní balíček ePeriodik. 

narazil jsem jen na tři nedostatky (asi?)
- v NDK balíčku má mít kořenový element METS `TYPE: electronic_coll_journal`, jestli to teda chápu správně. Teď je tam `electronic_periodical`:
![image](https://user-images.githubusercontent.com/57805328/207364689-4cff9495-b1de-4049-a78b-5e9dcc7a4372.png)
- `genre` u ePeriodik má být s podtržítkem (viz #1488), takže to má být např. `<mods:genre>electronic_title</mods:genre>`, teď je tam `<mods:genre>electronic title</mods:genre>` - pozor u eMonografií to nechat bez toho podtržítka :)
- na rozdíl od eMonografií má v SIP balíčku existovat složka `amdsec` s technickými a administrativními metadaty. Ta tam teď není a navrhuju to dořešit spolu s tímhle issue: https://github.com/proarc/proarc/issues/1428

**Comment by ZdenkaSera** [comment]
Dávm k uzavření. @kerschfilip

**Comment by kerschfilip** [comment]
Já bych přeci jen poprosil o opravu toho, co jsem psal výše, @SykoraLukas. Respektive takhle:

- prosím opravit ten `mets` `TYPE` na `electronic_coll_journal` (teď je `electronic_periodical` - to je hodnota ze standardu pro [elektronická periodika](https://standardy.ndk.cz/ndk/standardy-digitalizace/DMF_ebornperiodika_2.3.pdf), ale my to implementujeme podle standardu pro [skládaná periodika](https://standardy.ndk.cz/ndk/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf))
- `genre` u ePeriodik má být s podtržítkem, ale počkal bych, jak to NK sjednotí, abychom to pořád nepředělávali tam a zpět... my to teď exportovat nebudeme a o nikom jiném, kdo by o to teď hned stál, nevím (kdyžtak se prosím ozvěte)
- složku `amdsec` bych řešil v rámci issue o technických metadatech

**Comment by SykoraLukas** [comment]
Bod 1) a 2) je hotový.

**Comment by kerschfilip** [comment]
Bod 1 a 2 je hotový a otestovaný. Díky. Bod 3 vyřešíme jinde.
