### ISSUE TITLE
ProARc 3.4-Gama nelze spustit

### ISSUE THREAD

**Issue by mduda100871** [proarc/proarc#688]
Zdravim,

zkusil jsem nainstalovat vyse uvedenou verzi standardnim postupem, ale start aplikace selze. V cataline vypadnou vyjimky - viz screenshot v priloze.

MD

![proarc-test-error-01](https://user-images.githubusercontent.com/8750622/35904244-b4f82a64-0be2-11e8-8de1-56ae3ffc5404.png)

**Comment by SykoraLukas** [comment]
Právě jsem tuto verzi nasadil na testovací server v Incadu. 
Stačilo smazat původni warko a rozbalenou složku, nahrát novou nové warko, rozbalit ho a restartovat tomcat. ProArc v pořádku naběhl.
Mohl bych vás požádat o více informací? Děkuji

**Comment by mduda100871** [comment]
Presne timto zpusobem vzdy postupuji. Zastavim tomcat, smazu war + rozbaleny war, nahraji novy war a spustim tomcat.

Vic informaci nemam, pouze ten vypis logu. Predchozi verze ProArcu tam bezela bez problemu, v konfiguraci jak aplikace, tak tomcatu se nic nemenilo (pouze vymena war balicku popsanym postupem vyse).

Jeste jsem to otestoval tak, ze jsem smazal/odinstaloval aplikaci a spustil pouze tomcat. Nasledne jsem jiz bezicimu kontejneru "podstrcil" aplikaci do adresare webapps/ a v druhe konzoli sledoval catalina log - po rozbaleni aplikace se v logu objevily opet vyse uvedene vyjimky. Ve vypisu bezicich procesu OS se to tvari, ze aplikace bezi (jsou napr. navazane konexe do databaze), ale nereaguje.

MD

**Comment by MartinRumanek** [comment]
Podle toho stacktrace to vypadá, že je nějaký problém s contextem aplikace, viz stacktrace zdrojáky Tomcatu https://apache.googlesource.com/tomcat/+/a63bf3a4b62dec78e71a6354e0a33770d4f87dc7/java/org/apache/catalina/webresources/DirResourceSet.java#241

Zkuste context.xml vyměnit za
https://github.com/proarc/proarc/blob/master/proarc-webapp/src/main/webapp/META-INF/context.xml

Mělo by to pomoci.

**Comment by mduda100871** [comment]
Ted to funguje, problem byl v tom, ze context.xml dodany ve war balicku obsahuje nastaveni base="${catalina.home}/...", kdyz to zmenim na bas="${catalina.base}/..." tak to funguje. Je mozne, ze to je specifikum tvorby jednotlivych instanci tomcatu v Debianu, v kazdem pripade predchozi distribucni balicky ProArcu s tim problem nemely.

MD

Funkcni context.xml - screenshot v priloze

![proarc-context-01](https://user-images.githubusercontent.com/8750622/35922232-4eff0f62-0c1d-11e8-8b86-ed9847bc2be2.png)

**Comment by SykoraLukas** [comment]
Děkujeme za informaci. Nyní je již context ve warku opraven.
