### ISSUE TITLE
Test verze 3. 4 gama - Chyba při zakládání NDK Svazek monografie ve vazbách

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#694]
V obrazovce Editor připojených objektů nelze pod NDK Vícedílná monografie založit NDK Svazek monografie.
![obrazek](https://user-images.githubusercontent.com/13831946/36098142-16aa6d84-0ffe-11e8-8c51-abd2e590c0ad.png)

**Comment by SykoraLukas** [comment]
Jde založit Ndk svazek monografie v sekci "Nový objekt" a ten poté napojit na ndk vicedilna monografie? 

Vyzkouseno na testovacim serveru v Incadu. Zalozit model v editoru vazeb lze. 

Co se zobrazi pokud otevrete detaily teto chyby?

**Comment by nezbedova** [comment]
NDK Svazek monografie nejde založit jako "Nový objekt"
![obrazek](https://user-images.githubusercontent.com/13831946/36134667-8a795c10-1086-11e8-90c5-3760e2638516.png)

**Comment by nezbedova** [comment]
Při zakládání ve vezbách jsem zkusila jsem místo RDA zaškrtnout AACR, ale stejně to nejde.
Chybová hláška:

HTTP Status 500 - org.glassfish.jersey.server.ContainerException: cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:c6a59dc9-f146-4cb1-b19a-b94ff85979ba, dsId: BIBLIO_MODS

type Exception report

message org.glassfish.jersey.server.ContainerException: cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:c6a59dc9-f146-4cb1-b19a-b94ff85979ba, dsId: BIBLIO_MODS

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:c6a59dc9-f146-4cb1-b19a-b94ff85979ba, dsId: BIBLIO_MODS
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)

root cause

org.glassfish.jersey.server.ContainerException: cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:c6a59dc9-f146-4cb1-b19a-b94ff85979ba, dsId: BIBLIO_MODS
	org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278)
	org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260)
	org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)

root cause

cz.cas.lib.proarc.common.fedora.DigitalObjectException: PID: uuid:c6a59dc9-f146-4cb1-b19a-b94ff85979ba, dsId: BIBLIO_MODS
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadataAsJson(NdkMetadataHandler.java:296)
	cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.updateDescriptionMetadata(DigitalObjectResource.java:913)
	sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)

root cause

com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type cz.cas.lib.proarc.mods.IssuanceDefinition from String "multipart_monograph": value not one of declared Enum instance names: [integrating resource, serial, monographic, multipart monograph, single unit, continuing]
 at [Source: {"mods":{"genre":{"value":"volume"},"identifier":{"value":"c6a59dc9-f146-4cb1-b19a-b94ff85979ba","type":"uuid"},"recordInfo":{"recordCreationDate":{"value":"20180212T135651","encoding":"iso8601"},"recordChangeDate":{"value":"20180212T135651","encoding":"iso8601"}},"typeOfResource":{"value":"text"},"version":"3.5","titleInfo":{"title":{"value":"Parametrický model"},"partNumber":{"value":"pokus"},"partName":{"value":"1"}},"name":{"namePart":{"type":"family","value":"Novák"},"role":{"roleTerm":{"value":"aut","type":"code","authority":"marcrelator"}}},"originInfo":{"eventType":"publication","issuance":"multipart_monograph","place":{"placeTerm":{"type":"TEXT","authority":"marccountry","value":"Praha"}},"publisher":{"value":"U nás"},"dateIssued":{"point":"start","value":"2018"}},"language":{"languageTerm":{"authority":"iso639-2b","type":"code","value":"cze"}},"physicalDescription":{"form":{"value":"print"}},"location":{"physicalLocation":{"authority":"siglaADR","value":"ABA007"},"shelfLocator":{"value":"K 2690"}},"part":{"type":"volume"}},"rdaRules":"false"}; line: 1, column: 606] (through reference chain: cz.cas.lib.proarc.common.mods.ndk.RdaModsWrapper["mods"]->cz.cas.lib.proarc.mods.ModsDefinition["originInfo"]->java.lang.Object[0]->cz.cas.lib.proarc.mods.OriginInfoDefinition["issuance"]->java.lang.Object[0])
	com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
	com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1374)
	com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:925)
	com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:194)
	com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:126)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:340)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:340)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
	com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
	com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:357)
	com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1165)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:146)
	com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeSetAndReturn(ObjectIdReferenceProperty.java:75)
	com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeAndSet(ObjectIdReferenceProperty.java:68)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3789)
	com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2833)
	cz.cas.lib.proarc.common.mods.ndk.RdaNdkMapper.fromJsonObject(RdaNdkMapper.java:48)
	cz.cas.lib.proarc.common.object.ndk.NdkMetadataHandler.setMetadataAsJson(NdkMetadataHandler.java:294)
	cz.cas.lib.proarc.webapp.server.rest.DigitalObjectResource.updateDescriptionMetadata(DigitalObjectResource.java:913)
	sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.securedContent(ProarcAuthFilter.java:72)
	cz.cas.lib.proarc.authentication.ProarcAuthFilter.doFilter(ProarcAuthFilter.java:50)
	cz.cas.lib.proarc.webapp.server.EditorServletConfiguration.doFilter(EditorServletConfiguration.java:96)

note The full stack trace of the root cause is available in the Apache Tomcat/8.0.14 (Debian) logs.

**Comment by nezbedova** [comment]
Zjistili jsme, že se chyba projevuje jen u některých předloh. Zkusili jsme K 2717 a tu jsme jako "nový objekt" založili.
Ve vazbách se nám podařilo založit NDK Svazek monografie pod titul Věda v Československu. uuid:cfb4e928-e18e-4b53-be40-36cceda10b1c

**Comment by nezbedova** [comment]
Pokusy jsem zjistila, že k chybě dojde při stažení nebo zapsání do pole Origin Place Term.

**Comment by SykoraLukas** [comment]
Záznam nešel založit, protože v katalogu, ze kterého se stahuje záznam není vyplněno, podle jakého standardu je záznam vytvořen. Doplnil jsem tedy podmínku, aby v takových případech byla automaticky nastavena hodnota AACR. Uživatel ji poté může přepnout pomocí Raddiobuttonu nahoře v záznamu.
