### ISSUE TITLE
Nápovědní bubliny

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#700]
U issue #170, #171, #173, #175, #180, #186, #196, #198 se vyskytují tyto připomínky:
- extent - unit - chybí popis
- date issued - qualifier  - chybí popis questionable
- date issued - qualifier  - chybí popis inferred

Vzhledem k tomu, že tyto hodnoty nejsou ve specifikaci uvedené, poprosil bych vás o definování popisku k těmto polím. Vše ostatní z těchto issue již mám opravené. Paní @nezbedova mohl bych vás poprosit? Děkuji moc

**Comment by SmejkalovaAnna** [comment]
Tak Extent - Unit - ta položka tam vůbec už nemá být, takže to okýnko z formuláře můžete odmazat, 
 U date issued - qualifier - zrušte z nabídky questionable, zůstane tam jen Approximate a Inferred. K tomu inferred dejte bublinu - " Odvozený nebo dopočítaný údaj ".
