### ISSUE TITLE
Tučné označení s vykřičníkem při nevyplnění všech povinných polí

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#703]
Pokud se stáhnou některé informace do nepovinných polí a nejsou vyplněná Mandatory podpole, měl by proArc při ukládání tyto podpole označit s vykřičníkem. Konkrétně mi teď nehlásit chybu v Name MA - v podpoli Name Parts M - Role M (nebyla vyplněná). Zahlásil mi to až validátor.

**Comment by SykoraLukas** [comment]
Tohle jsme vypnuli na základě připomínky @krizovj v issue #612 ze dne 1.12.2017. Bohužel nelze udělat, aby každý to měl jinak.

**Comment by SmejkalovaAnna** [comment]
Nene to nezavírejte, to neni to samé jako issue #612, tam slo o to, ze to hlásí povinnost kdyz nadřazená položka neni vyplněná. Tohle je ale případ, kdy nadřazená ( nepovinná ) položka je vyplněná a pod ní povinná vyplněná není - musí to hlásit chybu. Teď je hlášení vypnuté ať je nadřazená - nepovinná vyplněná nebo ne. Hlásil mi chybu Validátor, že položka chybí.

**Comment by krizovj** [comment]
A šlo by to udělat tak, že pokud si toho elementu "name" nebudu vůbec všímat, ptž je nepovinný a nechci ho třeba vyplňovat, tak pokud prostě do toho elementu "name" nic nenapíšu, tak mi to nebude hlásit žádné chyby? 
A pokud ho začnu vyplňovat a vyplním ho špatně, tak by mi to teprve mělo říct, že mi v tom elementu něco chybí. 
Chtěli jsme to vypnout kvůli redakcím, kde si zpracovávají články sami, aby je to nemátlo, že tam mají chybu a přitom tam vlastně chyba není, ptž celý ten element není povinný, jen jeho některé části. 

Pokud to nejde takhle, tak to prosím znovu zapněte, ptž by to vedlo k chybám.

**Comment by jkremlacek** [comment]
Jen pro ujasnění, bavíme se o situaci:

![mandatoryfieldinma](https://user-images.githubusercontent.com/9445927/36837888-dc6fd6e8-1d3d-11e8-8fc7-4d335e8fa3f4.png)

kdy očekáváte, že pole `Name Part -M` a všechna pole v `Role - M` budou označena chybou v případě pokusu o uložení? (jelikož jsou vyplněna pole `Type - MA` - resp. stačilo by vyplnit jedno z nich aby došlo k označení povinných polí)

**Comment by krizovj** [comment]
Přesně, prostě pokud před uložením do elementu name nic nenapíšu, tak mě to neupozorní (ptž ten element je MA), ale pokud tam vyplním třeba jen jméno a příjmení a zapomenu na "role", tak by mě to už upozornit mělo, ptž by si to mělo všimnout, že se ten element "name" pokouším vyplnit.

**Comment by SykoraLukas** [comment]
Navrhovaná změna (označení vykřičníkem nevyplněných polí) udělat nelze. Jde o omezení smartGwt. 

Dá se však udělat, že vyskočí informační hláška, která informuje o chybějících polích. Ty ale nebudou označeny červeným vykřičníkem.

**Comment by jkremlacek** [comment]
Na úpravě pracuji, zdá se, že jsem našel způsob jak smartGwt naučit podmíněné povinnosti pole.

**Comment by SmejkalovaAnna** [comment]
Skvělé, doufejme, že to bude fungovat :)))
