### ISSUE TITLE
Mods: language - pole Object Part - chybně vyplněné

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#704]
Při stažení údajů z registru se propsal do pole Object Part  údaj "summary od subtitle" což neodpovídá ničemu ve specifikaci.

**Comment by SmejkalovaAnna** [comment]
A validátor na tom hází chybu

**Comment by SykoraLukas** [comment]
Mohl bych poprosit o více informací, abych si to mohl nasimulovat? Z jakého registru a jaký záznam?

**Comment by SmejkalovaAnna** [comment]
Stáhla jsem si údaje z registru digitalizace ke knížce  ( NDK Monografie ) Důkazy objevů: fotografie ve vědě v letech 1839-1939, sig. E 81260 nebo č.kód 26001800671. A do pole Object Part se natáhl údaj "summary od subtitle". Což neodpovídá metadat. standardu - hlásil mi to zas Validátor.

**Comment by SykoraLukas** [comment]
Zde se nejedná o chybu ProArcu. ProArc používá [transformační šablonu](https://github.com/LibraryOfCongress/MarcMods3.5xsl/blob/master/MARC21slim2MODS3-5.xsl) z MARC21 do MODsu vydanou v roce roce 2014.

Přímo v šabloně je i uvedena hodnota "summary or subtitle". 
![image](https://user-images.githubusercontent.com/27210823/36889455-4e664cf2-1dfa-11e8-94f3-d0bf3232c7c0.png)

Pole Language by v MARCu mělo být pole 041 (pokud jsem se správně zorientoval v šabloně). Podle katalogizačního záznamu by tedy mělo být vše v pořádku.
![image](https://user-images.githubusercontent.com/27210823/36889671-50c9f92a-1dfb-11e8-8da0-1de702ce4091.png)

Co hlásí validátor za chybu?

**Comment by SykoraLukas** [comment]
Po přezkoumání NDK Standardu jsem přišel na to, že ve specifikaci je skutečně uvedena hodnota.
![image](https://user-images.githubusercontent.com/27210823/36889828-f6d4ef8c-1dfb-11e8-9a43-88680b697900.png)
 Opravím transformační šablonu a poté by to už mělo být v pořádku.

**Comment by SykoraLukas** [comment]
Takhle už to je v pořádku, že?
![image](https://user-images.githubusercontent.com/27210823/36890862-d283d306-1dff-11e8-8165-5d67cb38b16c.png)

**Comment by SmejkalovaAnna** [comment]
Vypadá to v pořádku, podle všeho jsou tam možný asi 4 hodnoty, ale nevím, která, co přesně znamenají, asi by to věděla Jana křížová. Nicméně to takhle asi bude v pořádku.

**Comment by SykoraLukas** [comment]
Nyní se stáhne hodnota "summary", nikoliv hodnota "summary or subtitle"
