### ISSUE TITLE
NDK Svazek monografie_ dateIssued - point x date

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#706]
Podle NDK **_Svazek monografie_** je atribut **Point** elementu dateIssued povinný (M). Neplatí ale, že by každá monografie měla "start" a "end". Když se v ProArcu vyplní Date (M) v elementu dateIssued a dá se Uložit, ProArc napíše chybovou hlášku a požaduje vyplnit i **Point**:

![obrazek](https://user-images.githubusercontent.com/31240271/36674893-bc8ab04c-1b07-11e8-9c3e-9ab47bb2fe51.png)

![obrazek](https://user-images.githubusercontent.com/31240271/36675244-c075bf52-1b08-11e8-81d0-68cec47407f5.png)

Chápu, že podle NDK u **Point** musí zůstat povinnost vyplnění M, ale chybová hláška je matoucí, když monografie nemá rozmezí dat vydání předlohy. Nebylo by možné tuto chybovou hlášku odstranit?

**Comment by SykoraLukas** [comment]
Pokud nastane situace, že monografie nemá rozsah, potom je nutné napsat do Národní knihovny, aby tuto situaci zahrnuly do specifikace. Tedy změnit povinnost na MA.

Hláška se odstranit může, ale nedoporučoval bych to. Je to kontrola, že jsou vyplněné všechny nutná pole, tak jak udává specifikace.

**Comment by SmejkalovaAnna** [comment]
Připojuji kompletní Mets k případu, kdy hlášku přeskočím a pokračuji v uložení: 
[mets_aba007-00003s.zip](https://github.com/proarc/proarc/files/1761636/mets_aba007-00003s.zip)

**Comment by SmejkalovaAnna** [comment]
Mets pro případ, kdy je Point vyplněné: 
[mets_aba007-00003t.zip](https://github.com/proarc/proarc/files/1761643/mets_aba007-00003t.zip)

**Comment by SmejkalovaAnna** [comment]
S Janou Křížovou jsme se shodli, že proArc z nějakého důvodu nezapíše v případě nevyplněného Point povinnou položku dc:date do mets i když je Date v ProArcu vyplněné. Posím Lukáši prověřte to.

**Comment by krizovj** [comment]
Standard se možná měnit bude, ale určitě to nebude hned a nemůžeme mít do té doby nevalidní záznamy.

**Comment by jkremlacek** [comment]
Vytváření `dc:date` je podmíněno přítomností hodnoty v `Point`.

V PR #707 je připravená úprava, která tuto podmínku ruší. @SykoraLukas nevím, jestli je kvůli něčemu nutná, pokud je a úprava by to rozbila, tak PR zavři.

**Comment by SykoraLukas** [comment]
Tuto změnu tam měl již Honza, aby zabránil tvoření elementu dc:date pokud není vyplněno pole Point. Pokud si úpravu přejete, je možná, nic by se nemělo rozbít. 

Ještě zbývá vyřešit, co s chybovou hláškou. Pokud se odstraní, odstraní se i červené označení textu Point s vykřičníkem. Bohužel nelze odsranit jen chybovou hlášku, aby zbylo ztučnění textu. Jde o omezení smartGwt.

Navrhuji tam chybovou hlášku nechat, aby byl uživatel vždy upozorněn. I přesto však bude hodnota date doplněna do DubkinCoru
