### ISSUE TITLE
Možnost volby zobrazované první strany v Krameriovi

### ISSUE THREAD

**Issue by GoogleCodeExporter** [proarc/proarc#71]
```
V obrazovce Import-připravit metadata pro import vytvořit možnost označení 
jednotlivé stránky, která se bude v Krameriovi zobrazovat jako náhled 
celého titulu. Bez označení jí standardně bude titulní strana. 
```

Original issue reported on code.google.com by `daneck...@knav.cz` on 27 Sep 2013 at 1:51

**Comment by nezbedova** [comment]
Řešení a závěr je v issues 304.

**Comment by pokorsky** [comment]
Issue #304 nic neřeší a je navíc zavřeno. Tato issue je ve stavu onHold. Čeká se na nový NDK standard.

**Comment by jkremlacek** [comment]
NDK standard už umožňuje volbu reprezentativní strany, implementace je možná.

**Comment by SykoraLukas** [comment]
Implementováno v rámci nového standardu. Pokud je zájem o vybrání reprezentativní strany, nastaví se v elementu genre hodnota reprePage.
