### ISSUE TITLE
Efektivnější práce v průběhu Exportu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#711]
Možnost pokračování v další práci během exportu. Stejně jako je to u Importu - lze klepnout na Další a pokračovat v jiné práci v ProArcu zatímco se dávka importuje na pozadí - tak by bylo možné taky klepnout na tlačítko Další a Export by běžel na pozadí. Až by doběhl Export, tak by vyběhla hláška Hotovo + druh Exportu ať bych byla aktuálně v jakémkoliv okně PA.

**Comment by zabak** [comment]
Proč je to znovuotevřené?

**Comment by nezbedova** [comment]
Omlouvám se. Nejspíš nějaká chyba. Pokud bych otevírala, napsala bych proč.
