### ISSUE TITLE
Úprava hlášení o dokončeném Exportu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#712]
Prosím o úpravu hlášení, když se dokončí příslušný Export. Bylo by fajn, kdyby se objevila POKAŽDÉ hláška Dokončeno + druh Exportu. Díky.

**Comment by SykoraLukas** [comment]
Tedy v případě NDK PSP exportu se zoobrazí okno "NDK export proběhl úspěšně". Šlo by to takhle?

**Comment by nezbedova** [comment]
Ano. To by nám vyhovovalo.

**Comment by SykoraLukas** [comment]
Implementováno v rámci #711.
