### ISSUE TITLE
Chybí element Physical Description - Form - Type

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#714]
Podle RDA chybí ve formuláři NDK Monografie ve Physical Description - Form element Type MA s výběrem "media" nebo "carrier". Prosím prověřit i u ostatních modelů....

**Comment by SykoraLukas** [comment]
Pole type je záměrně needitovatelné. Doplňuje se automaticky podle vybrané hodnoty v elementu Physical Description - Authority. Vychází to ze [specikace ](https://docs.google.com/document/d/1cWvwfk9bVpTGfeSwQOKfDQlbIyEkJEL-LcMU6bmQL1A/edit#heading=h.17dp8vu).

**Comment by SmejkalovaAnna** [comment]
Ahá, takže tam je, jen není vidět. Možná by bylo fajn, aby tato pole byla alespon viditelna, pokud si otevřu prázdný formulář. Pokud si stahuju záznam z katalogu nebo registru, tak se mi tam ta pole objeví, ale pokud mám prázdný, tak ne.....

**Comment by SykoraLukas** [comment]
Ono se to pole vytvori v okamziku ulozeni, tedy kdyz mate prazdny formular a vyplnite ho a nasledne ulozite tak kdyz se pote podivate na ty toto pole, tak uz je vyplnene

**Comment by SmejkalovaAnna** [comment]
Dobrá dobrá
