### ISSUE TITLE
Nesprávné barvy po importu TIF

### ISSUE THREAD

**Issue by black23** [proarc/proarc#721]
Přešli jsme z Meditu, jsem tedy v ProArc nováček. Pracujeme převážně s born digital dokumenty, které vznikají v Adobe InDesign, případně prochází ScanTailorem. Medit nikdy problémy neměl. ProArc bohužel při importu zmutuje barvy, viz https://prnt.sc/iq2gfx. Odstranil jsem komprimaci LZW i barevný profil, který byl přítomen. Ale situace zůstala stejná. Pokusná konverze v Imagemagick proběhla naprosto bez problémů a barvy jsou korektní. Jsou někde uvedeny specifikace, které musí TIF na vstupu splňovat? Neuvažuje se, že by konverze probíhala například zmíněným Imagemagickem? Je to robustní nástroj, dlouhodobě se rozvíjející a podporovaný.
Informace o zdrojovém TIF: https://prnt.sc/iq2h6p

**Comment by black23** [comment]
Ještě přikládám vzorový TIF, který způsoboval výše popsané.
[sample.zip](https://github.com/proarc/proarc/files/1824834/sample.zip)

**Comment by mjtecka** [comment]
Zkoušel jsem (ze zvědavosti;-) importovat ten sample.tif ... ukázalo, že ten samotný soubor je nejspíš poškozený (je ho jenom část), ale zároveň se mi **nepodařilo** reprodukovat tu chybu s barevností...
![proarc-badtif](https://user-images.githubusercontent.com/11203453/37655868-b2e1724c-2c46-11e8-82c9-7938ced3dcfd.png)

Mám totiž taky tif, který se mi špatně načítá:

![proarc-badtif2](https://user-images.githubusercontent.com/11203453/37656061-42712f74-2c47-11e8-9b31-dd201b1596e9.png)

Náš soubor je tu: 
[modra4.tif.zip](https://github.com/proarc/proarc/files/1829377/modra4.tif.zip)

@black23: Mohl byste prosím zkontrolovat jestli ten váš soubor opravdu dělá problémy a případně sem dát ten původní pokažený? Zajímalo by mě, jestli mají něco společného s tím naším...

**Comment by luckajirku** [comment]
@mjtecka - s těmi modrorůžovými skeny jsme kdysi měli problém taky, @pavelkocourek nevzpomeneš si, jak to přesně bylo? Nějak byla poškozená metadata, špatně nastavená transparentnost, projevilo se to při konverzi z tiffu. V ProArcu ještě v náhledech byla barevnost v pořádku, ale při plném rozlišení se to ukázalo...

**Comment by mjtecka** [comment]
Mě se ten obrázek nejdřív vůbec nedařilo naimportovat kvůli tomu, že jsem používal OpenJDK Javu... někde jsem se pak dočetl, že ta má problémy právě s transparentností (i když přesný mechanismus toho co se děje nechápu a zase tak moc jsem to nezkoumal). Když jsme nahradili OpenJDK Oracle Javou, obrázek se naimportoval, al špatně - jak je vidět v tom náhledu.  

Nicméně nevím, jestli je to stejný problém, jako má @black23...

**Comment by pavelkocourek** [comment]
Vzpomínám li si dobře  (nenašel jsem to už bohužel v mailech), tak při konverzi se projevovala chyba v alfa kanálu, který řeší transparentnost/průhlednost. Výsledkem byly ty růžovky.
Některý z těch editorů metadata v obrazovém souboru přepsal nebo úplně vynechal.

**Comment by black23** [comment]
@mjtecka Záměrně jsem poslal jen část stránky, takže to se naimportovalo správně. Proč se neprojevila ta chyba s barevností mi není úplně jasné. Přikládám další. Původně jsem myslel, že problém s barevným profilem, který soubor obsahoval. Ale tím to nebylo, protože problém přetrval. Na tu transparentnost jsem také myslel, ale žádný nástroj mi její přítomnost neprokázal a záměrně vkládaná rozhodně nebyla. Nicméně, jak jsem psal Imagemagick tu konverzi udělá naprosto bez problémů. Takže problém vidím v řetězci úkonů při konverzi v ProArcu. V čem spočívá však stále netuším.
[001.test.zip](https://github.com/proarc/proarc/files/1851904/001.test.zip)

**Comment by jkremlacek** [comment]
Po dohodě vývojového týmu bude vyřešeno umožněním použití externího konvertoru, implementace v rámci https://github.com/moravianlibrary/proarc/issues/12.

**Comment by mjtecka** [comment]
@black23 Díky za další vzorek. Issue už je sice zavřené, nicméně... i tenhle soubor se mi naimportoval barevně správně.

**Comment by black23** [comment]
@mjtecka Divné. Nicméně díky podpoře externích konverzních nástrojů s tím problém pravděpodobně skutečně nebude. Osobně se domnívám, že v našem případě nešlo o problém s transparentností. To jsem kontroloval. Spíš jsem sázel na barevný profil, ale ani ten se mi nepotvrdil. Na každý pád děkuji za Váš test.
