### ISSUE TITLE
Element "note"

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#723]
Do elementu "note" se stahují údaje z polí 5XX z MARCu. Kromě toho se do jednoho elementu "note" stahují taky údaje z pole 245, $c s atributy "type=statement of responsibility" a "altRepGroup=00". Pokud ale není v MARCu toto podpole vyplněno, tak se v ProArcu vyrobí prázdný element "note" s těmito dvěma atributy:

<mods:note type="statement of responsibility" altRepGroup="00"></mods:note>

Validátor to pak hlásí jako chybu, ptž ten element je prázdný: 

![noteprazdna](https://user-images.githubusercontent.com/21309201/37602253-415c14b6-2b8c-11e8-96ee-44d9bcd5556b.jpg)

Problém je, že u NDK svazek monografie to není ve formuláři vůbec vidět, že v tom elementu "note" něco je (i když jsou to jen atributy). Je to vidět jen v XML a pak ve validátoru když hodí chybu. Ale z formuláře to nejde zjistit.

![note2](https://user-images.githubusercontent.com/21309201/37601965-a1e4793c-2b8b-11e8-8069-f558c342b504.jpg)

Šlo by to udělat tak, že pokud v MARC záznamu nebude 245, $c vyplněno, tak by se v ProArcu ta poznámka s těmi atributy vůbec nevytvořila? Ale samozřejmě pokud tam budou vyplněna 5XX pole, tak z nich by se ty elementy "note" tvořit měly. 

Pokud je to nepochopitelné, tak dejte vědět.

**Comment by SmejkalovaAnna** [comment]
Stejnou chybu hlásí Validátor v Periodiku na úrovni Titulu.

**Comment by luckajirku** [comment]
V šablonách LoC (3.6) je vytvoření poznámky podmíněno existencí 245 $c, jestli se dobře dívám.

**Comment by krizovj** [comment]
No, to by asi tak mělo být, ale teď to vypadá, že to tak asi nefunguje. V MARC záznamu to podpole c nebylo a přesto se tam ten element note vytvořil.

**Comment by jkremlacek** [comment]
V ProArc-u byla momentálně podmínka vytvoření `mods:note` pouze existence pole 245. Oprava podmínku rozšíří o kontrolu přítomnosti $c s tím, že by se měla promítnout do všech modelů.

**Comment by krizovj** [comment]
Super, děkujeme :)

**Comment by SmejkalovaAnna** [comment]
Super, děkujeme, dejte vědět, co nejdřív, kde je ke stažení tahle opravená verze, abychom ji mohli nasadit jako ostrou....

**Comment by jkremlacek** [comment]
Ostrou verzi musí vydat @SykoraLukas, vyřídím mu, že je zájem o verzi 3.4.2.

**Comment by SykoraLukas** [comment]
Vydam opravenou o vikendu, v pondeli ji bude mozne nasadit
