### ISSUE TITLE
NDK příloha dle AACR - "neplatná data" u eventType

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#727]
Při zakládání NDK přílohy periodiky (resp. i přílohy monografie) se zakliknutým AACR vyskakuje chyba u OriginInfo / eventType, který se ale vyplňuje u RDA a tady být nemá. Což ProArc ví, protože když ho zkusím u AACR vyplnit, tak mi napíše "EventType musí být prázdný, pokud descriptionStandard = "AACR"", ale když ho nevyplním, tak ho po mně vyžaduje...

**Comment by jkremlacek** [comment]
Chyba je hlášena, protože je porušena podmínka M polí v MA oddílu. Pokud je vyplněné nějaké pole v MA oddílu, tak se kontrolují všechny M pole v něm. 

V Place - MA -: Type - M je výchozí hodnota TEXT, pokud ji nepřepnete na prázdnou hodnotu, tak ji kontrola vyhodnotí jako vyplněné pole v MA oddílu a spustí se výše zmíněná kontrola.

**Comment by luckajirku** [comment]
Problém těchto hlášek je, že jakmile se lidi naučí nějaké věci ignorovat, protože vědí, že to je v pořádku a mají to ignorovat, tak postupně otupí a začnou to ignorovat i tam, kde ta hláška má smysl. Není nějaká cesta, jak tyhle věci ošetřit jinak?

**Comment by SmejkalovaAnna** [comment]
Chlapi, Vy jste psali  k jednomu issue, kde jsme toto nedávno řešili, že zkoušíte přeprogramovat ty formuláře tak, aby pokud nadřazená nevyplněná nepovinná položka a v ní jsou vnořené povinné, to nehlásilo chybu, že ty povinné nejsou vyplněné.... jak jste na tom?

**Comment by jkremlacek** [comment]
Vámi zmíněné issue je #703, které je už součástí verze 3.4.1 a právě kvůli jeho implementaci (a korektnímu fungování) vzniklo toto issue.

**Comment by luckajirku** [comment]
V tom issue píšete "zdá se, že jsem našel způsob jak smartGwt naučit podmíněné povinnosti pole." - když už se smartGwt učí, nemůže se naučit i brát ohled na použitá pravidla? Když mám záznam v aacr a systém to ví, že je to aacr, proč by mi měl nutit povinnost to vyplnit, jako by to bylo v rda?

**Comment by jkremlacek** [comment]
Dané issue bylo založené na problém M polí v MA oddílech, který ta implementace řeší. Rozdílná povinnost M pole v případě rda/aacr tam zmíněna nebyla.

**Comment by jkremlacek** [comment]
Připravím opravu pro `Event Type`, dobudoucna bych ale doporučoval přepracovat podmínky povinností polí (např. jak jsem nastínil o post výše), hromadění podobných vyjímek komplikuje udržitelnost kódu.
