### ISSUE TITLE
Verze 3.4.2 - nefunguje uložení čísla a zjednodušeného formuláře ečlánku

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#732]
Ukáže třeba "uloženo", ale vlevo v seznamu článků (čísel) je pořád otazník a prostě se to neuloží. A když něco povinného chybí, tak nevyhodí hlášku "Neplatná data", ale jen označí vykřičníkama ty elementy a stejně se to neuloží. A pak se to úplně zasekne a když třeba překliknu na vedlejší článek nebo cokoliv, tak se nic nestane, nenačítá rozbalovací menu pro jazyky apod. 

Btw (ne)uložený článek nejde pak ani smazat. A další - příloha periodika (na úrovni přílohy čísla i na úrovni přílohy ročníku) nejde založit vůbec, neudělá to nic, ani ty otazníky.

![eclanek](https://user-images.githubusercontent.com/21309201/37955813-ebf6c54c-31a9-11e8-98a3-c66acc5e2c00.jpg)
![eclanek2](https://user-images.githubusercontent.com/21309201/37955820-eeb2a45e-31a9-11e8-9130-d757d09cfd3a.jpg)

**Comment by SykoraLukas** [comment]
Opraveno, otestoval jsem na založení modelů: Periodikum, Ročník, Číslo, eČlánek, Vícesvazek a svazek a funguje.

**Comment by krizovj** [comment]
Díky, vyzkoušíme. 
U čísla a ečlánku ještě zůstala u elementu "name" ta věc, že to ukazuje chybu, když nevyplním "role". 
U čísla je to name/role/authority a u ečlánku name/role/authority a name/role/type. 
Pořád to ukazuje chybu, i když ten element "name" vůbec nevyplním. Šlo by to ještě upravit?

**Comment by SykoraLukas** [comment]
Nerozumím tomu co myslíte, mohla byste to popsat podrobněji? Děkuji

**Comment by SykoraLukas** [comment]
Mohl bych vás poprosit o nové issue k poslednímu příspěvku @krizovj ? Děkuji
