### ISSUE TITLE
Verze 3.4.1 - Validátor hází chybu

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#734]
Validátor nám hází tuhle chybu:
![vystrizek](https://user-images.githubusercontent.com/21309201/37968644-0b5046f0-31cf-11e8-9ec2-7425eca93556.PNG)

Jde o stejnou chybu jako tady: https://github.com/proarc/proarc/issues/666
Ale dělá to verze 3.4.1. Ale původně to verze 3.4.1 nedělala, tedy alespoň na testovacím ProArcu. Pak jsme nasadili na ostrý ProArc verzi 3.4.2, která ale má nějaké chyby (https://github.com/proarc/proarc/issues/732), tak jsme dali do ostrého verzi 3.4.1 a ta dělá výše popsaný problém.

**Comment by jkremlacek** [comment]
Jenom projistotu se zeptám, v `proarc.cfg` máte zadefinované výše zmíněné položky (export.ndk.agent.creator a export.ndk.agent.archivist)?

**Comment by SmejkalovaAnna** [comment]
To nehází validátor to hází ProArc při exportu NDK a nevyexportuje to ten balík

**Comment by SykoraLukas** [comment]
Export vyžaduje vyplněné pole *creator* a *archivist*. Vzhledem k tomu, že tyhle pole se liší knihovna od knihovny, je nutné je definovat v konfiguračním souboru. 

Na testovacím serveru jste vám to fungovalo, protože tam se nastavila tato hodnota creator a hodnota archivist již při verzi 3.4. alfa. (Tuším, že to byl říjen). 

Prosím poproste Martina Dudu, aby doplnil konfigurační soubor o toto: https://github.com/proarc/proarc/wiki/Konfigurace#ndk-export. Pak by to již mělo fungovat.

**Comment by krizovj** [comment]
Díky, díky, už jsme na to přišli a jde to :)
