### ISSUE TITLE
Verze 3.4.2 Upravení povinností polí formuláře pro ečlánek

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#735]
Ještě bych měla jednu věc. Jde o to podmíněné hlášení chybějících elementů. Ve formuláři pro ečlánek doplňujeme rozsah stran do elementu relatedItem. Ale bohužel v relatedItem je povinný element "title" a "publisher" a když se nevyplní, tak hlásí chybu. Šlo by tady udělat výjimku, aby  to tu chybu neukazovalo? Ptž my tam doplňujeme pouze ten rozsah stran.

**Comment by jkremlacek** [comment]
Samotná pravidla povinností NDK formulářů spolu s RDA/AACR jsou poměrně komplikovaná. Přidávání takovýchto výjimek bude jen zhoršovat udržitelnost kódu a stejně tak budou pro ostatní zpracovatele matoucí. Dle mého názoru by NDK formuláře měly být fixovány pouze na NDK standard, co se týče povinností polí.

**Comment by krizovj** [comment]
Chápu a myslíte, že by šlo z toho elementu relatedItem vyhodit ven element "Extent"? Jako je to u formuláře NDK článek? 
Takhle:
![image](https://user-images.githubusercontent.com/21309201/38023795-7e5d6998-3283-11e8-8c2c-a4780988d372.png)
A nechat tam ten element relatedItem? 
Formulář pro ečlánek totiž není podle NDK standardu, už ho máme déle a v té době ještě standard pro ečlánek nebyl (vznikl na konci roku 2017). Budeme to upravovat až s úpravami ProArcu pro elektronické publikace.

**Comment by SykoraLukas** [comment]
Vzhledem k tomu, že eČlánek nejspíše zanikne, neboť ho nahradí novější model pro eČlánek, který bude podle specifikace NDK, tak to nemá smysl opravovat. V současné verzi to není, v příští vyjdou Gramofonové desky podle NDK a hned v další je plánována aktualizace Standardu NDK.

**Comment by krizovj** [comment]
Dobře, díky, zavírám.
