### ISSUE TITLE
RDA záznamy - neodmazává se interpunkce u údajů z MARC pole 264

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#736]
Při stažení RDA záznamu (na rozdíl od těch AACRkových) se automaticky neodmaže interpunkce tam, kde by se odmazat měla (place/placeTerm, publisher). 
Když se dívám na konverzní šablonu, tak tam je "chopPunctuation" pro údaje z pole 260 (AACR), ale pro ty z 264 (RDA) to tam zřejmě chybí.

**Comment by SykoraLukas** [comment]
Na jakém záznamu jsi to zjistila? Abych mohl otestovat, že je to správně opravené? Stačí nějaké id a z jakého katalogu to je.

**Comment by luckajirku** [comment]
V testovacím incadím si najdi dnes nově založené NDK per. Východní Čechy nebo NDK svazek mon. Rukopis Kralodvorský, i Zelenohorský.

**Comment by luckajirku** [comment]
Tak šablonu si máme upravovat sami.

**Comment by luckajirku** [comment]
Tohle je třeba opravit v naší šabloně.
