### ISSUE TITLE
úložiště/hledat - vybraný model po uložení stran do objektu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#737]
Po uložení stran k objektu se automaticky přepne na úložiště/hledat na úvodní volbu - tedy pokud máme nahoře model NDK per., ukáží se periodika, i když jsme ukládali do monografie. Nebylo by možné, aby se nabídl právě použitý model?

**Comment by luckajirku** [comment]
To bude asi jiný případ. Jestli to správně chápu, tam bylo třeba dát zapamatovat, čili defaultně mám periodika, dám zapamatovat monografie, hodí mě to pak po refreshi nebo novém přihlášení na monografie. Ale o to mi nejde. Jde mi o to, aby základní nabídka zůstala jak je, ale při ukládání do monografie, kdy to samo přehodí do úložiště, si to chytře našlo ten právě použitý model. A jinak v tom úložišti, pokud tam půjdu normální cestou, bude nastaven model defaultně.

**Comment by krizovj** [comment]
Jo aha, ok.

**Comment by pavelkocourek** [comment]
Přesunuto : úložiště/hledat - vybraný model po uložení stran do objektu (#737) #22
