### ISSUE TITLE
Problém s exportem periodik

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#740]
Zjistil jsem, že přestože periodika exportujeme po ročnících, v exportu jsou PSP balíky pro jednotlivá čísla. Exportní adresář vypadá takhle:

155f03f5-4521-4fd5-97ab-4581342d00f8
/abg001-0005i0
/abg001-0005i1
/abg001-0005i2
/abg001-0005i3
/abg001-0005i4
/abg001-0005i5
/abg001-0005i6
/abg001-0005i7
/abg001-0005i8
/abg001-0005i9
/abg001-0005ia
/abg001-0005ib
/abg001-0005ic
/abg001-0005id
/abg001-0005ie
/abg001-0005if
/abg001-0005ig
/abg001-0005ih
/abg001-0005ii
/abg001-0005ij
/abg001-0005ik
/abg001-0005il
/abg001-0005im
/abg001-0005in
/abg001-0005io
/abg001-0005ip
/proarc_export_status.log

Problém je v tom, že některá periodika obsahuí stránky, které nejsou pod žádným číslem, ale rovnou pod ročníkem. Tyto stránky pak v exportu nejsou. Narazili jsme teď dokonce na ročník periodika, který nemá vůbec žádná čísla a všechny strany jsou přímo pod ročníkem. Ten pak v exportu nemá vůbec nic.

V logu je k tomu hromada těchto warningů:

```
WARNING: Missing page type resource for NormalPage locale cs
Apr 19, 2018 11:57:02 AM cz.cas.lib.proarc.common.mods.ndk.NdkPageMapper getPage
TypeLabel
```

Je správně, že se nám vytváří PSP balíky pro jednotlivá čísla místo jednoho PSP pro celý ročník? Pokud ano, jak vyřešit problém se stranami, které nejsou pod žádným číslem?

**Comment by nezbedova** [comment]
ProArc je postupně upravován tak, aby odpovídal současným standardům NDK. Nyní to je http://www.ndk.cz/standardy-digitalizace/dmf_periodika_1-7-1
PSP balíček = 1 adresář pro jedno číslo periodického dokumentu. Viz. str. 15
Samostatné strany se přímo pod ročník již nedávají, protože nesou jen informaci o straně (číslo a typ). Strany vždy musí být zařazena pod výtiskem.

**Comment by svetlym** [comment]
Aha, díky za informaci.

V tom případě by ale ProArc měl před exportem uživateli oznámit, že pod periodikem má volné strany, o které exportem přijde. Teď to hodí jen nic neříkající warningy do logu.

Založím na to novou issue.
