### ISSUE TITLE
Nepovolit export periodika, když jsou strany přímo pod ročníkem

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#741]
Paroarc nesmí povolit export periodika, pokud jsou strany přímo pod periodikem. Exportují se pouze čísla a tyto strany by tedy v exportu nebyly a uživatel by se o tom vůbec nedozvěděl - v logu se k tomu objeví pouze warningy:

'''
WARNING: Missing page type resource for NormalPage locale cs
Apr 19, 2018 11:57:02 AM cz.cas.lib.proarc.common.mods.ndk.NdkPageMapper getPage
TypeLabel
'''

ze kterých těžko někdo vyvěští, co se stalo a co to znamená.

Viz také isssue #740.

**Comment by jkremlacek** [comment]
Nebylo by lepší vytvořit sadu omezujících pravidel pro připojování podobjektů, aby vůbec nemohl nastat stav, kdy uživatel vytváří "nepovolenou" vazbu mezi objekty.

Vytvořil by se whitelist (seznam povolených vazeb), který by byl kontrolován v momentě, kdy uživatel ukládá vybraného rodiče. V případě že by vazba ve whitelist-u nebyla (např při pokusu o připojení stránek pod stránku, anebo právě stránky pod periodikum), tak by se vazba neuložila a uživatel by byl upozorněn hláškou "Nepovolená vazba mezi objekty: \*model rodiče\* -> \*model potomka\*".

**Comment by svetlym** [comment]
Souhlasím, to by bylo lepší.

Jen tu hlášku bych napsal trochu víc polopaticky, třeba: "Podle specifikace NDK objekt typu *model potomka* nemůže být vložen do objektu typu *model rodiče*".
 
(Pro uživatele je podstatná nejen informace, že to nejde, ale také proč to nejde).

**Comment by nezbedova** [comment]
Také souhlasím.

**Comment by luckajirku** [comment]
To je určitě dobrý nápad, teď jde v podstatě cokoli založit kdekoli. Jen Třeba u modelu NDK Příloha periodika to bude muset brát v potaz i to, jestli je to příloha k ročníku nebo k číslu...

**Comment by jkremlacek** [comment]
Abychom zbytečně nenaráželi během testování na příliš omezující pravidla, tak jsem vytvořil [seznam](https://docs.google.com/spreadsheets/d/1bkSaNm7RjG3pfOI41sDqwRwSO9A7aYYOh1bGxNMjsT4/edit?usp=sharing) se všemi povolenými vazbami, co mě napadly. Pokud si všimnete, že v seznamu nějaké chybí, tak jej sem prosím napište a doplním ho.

**Comment by luckajirku** [comment]
Strana pod NDK Příloha periodika
Strana pod NDK Příloha monografie

**Comment by luckajirku** [comment]
Strana pod STT Příloha monografie

**Comment by luckajirku** [comment]
A jde tam dát omezení podle typu přílohy periodika? Ono je to nešťastné, že je jeden model pro přílohu čísla i ročníku a odlišuje se to jen v "genre", ale bylo by fajn, pokud se teď nastavují pravidla, kdyby šlo omezit i tohle - aby nešla udělat příloha ročníku pod číslem a příloha čísla pod ročníkem.

**Comment by jkremlacek** [comment]
Jít by to mělo, ale taková kontrola už by musela probíhat na serveru - tj. ty "jednoduché" model-model by mohl kontrolovat už klient u uživatele, ale ty "složitější" na bázi obsahu metadat by se musely nejdřív poslat na server a ten by požadavek zamítl.

Nemění to ale tu jednoduchou kontrolu, takže se může nezávisle na sobě udělat kontrola podle seznamu a poté přidělat ta pokročilá kontrola podle metadat.

**Comment by luckajirku** [comment]
Tak super, pro nás tím líp:-).
Ještě k whitelistu, nejsem si jistá těmi stranami pod kapitolou. Přímo pod kapitolou žádné strany nejsou, ty jsou uložené pod svazkem a v kapitole v part/extent je jen uvedeno, na které straně začíná a končí.

**Comment by nezbedova** [comment]
@luckajirku Kapitola je "oddělovač"?

**Comment by luckajirku** [comment]
@nezbedova nechápu asi přesně otázku

**Comment by nezbedova** [comment]
Kapitolu začlením mezi strany? To znamená, že strany se nedávají pod kapitolu jako pod výtisk?

**Comment by luckajirku** [comment]
Takhle to pak vypadá, když si otevřete kapitolu, přímo pod ní nic uloženého není.
![kapitoly](https://user-images.githubusercontent.com/6359479/41397808-9e1deec8-6fb5-11e8-995d-b7e3a23fe888.png)

**Comment by luckajirku** [comment]
A v part/extent v popisu kapitoly pak uvedete od-do index stran 
![kapitola2](https://user-images.githubusercontent.com/6359479/41398096-7d6471d8-6fb6-11e8-9588-ade9e33bd1fb.png)

**Comment by nezbedova** [comment]
Děkuji.
