### ISSUE TITLE
Ve verzi 3.4.2 nejdou uložit kapitoly

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#742]
Ve verzi 3.4.2 kliknutí na tlačítko "Uložit" při editaci kapitoly vůbec nic neudělá. Kapitola se neuloží, ve struktuře se pořád jmenuje "?". V logu k tomu nejsou žádné chybové hlášky ani warningy.

Zkoušeli jsme to v ostré i testovací verzi proarcu (obojí updatnuto na verzi 3.4.2). Po revertnutí na verzi 3.4.1 problém zmizel.

**Comment by SykoraLukas** [comment]
Toto by již mělo být opraveno verzí 3.4.3. Tato verze vyšla právě kvuli stejnemu problemu u čísla.

**Comment by SykoraLukas** [comment]
Verze 3.4,3 [zde](https://github.com/proarc/proarc/releases/tag/v3.4.3)

**Comment by svetlym** [comment]
Aha, já jsem podle https://github.com/proarc/proarc/wiki měl za to, že nejnovější release je 3.4.2.

**Comment by SykoraLukas** [comment]
Děkuji za upozornění. Aktualizuji wiki

**Comment by svetlym** [comment]
Ve verzi 3.4.3 to funguje, vyzkoušeno.
