### ISSUE TITLE
Vlastnické údaje na úrovni vícedílky při stažení "cizího" bib záznamu

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#745]
Ve formuláři pro vícedílku na úrovni titulu vidíme/můžeme editovat jen údaje, které jsou ve standardu. Na pozadí (v xml) jsou pak ale údaje z celého bib záznamu. Do xml ale zpravidla nelezeme a tak může dojít k tomuhle - když se stahuje záznam z SK nebo jiného katalogu, sem se stáhnou vlastnické údaje (fyzické předlohy i záznamu) z původního záznamu. Upravujeme je až na úrovni svazku, ale tady na té vyšší úrovni to (na pozadí v xml) zůstává neopravené. Dopadne to pak třeba takhle - stažení záznamu NK z SKC při zpracování předlohy HKG001: http://www.digitalniknihovna.cz/svkhk/periodical/uuid:819ab68e-9617-4aa6-9405-55c5b7bf3ddc - na úrovni titulu se ukazuje místo uložení NK, v jednotlivých svazcích už správně HKG001.
Že je současný standard v případě vícedílek špatně udělaný, to víme (issue k tomu -https://github.com/NLCR/Standard_NDK/issues/48), ale zatím je třeba na to dávat pozor a případně opravovat v xml, pokud byste u vícedílek stahovali záznamy odjinud.

**Comment by PavlinaKocisova** [comment]
Řešení je k diskuzi všech praktikujících organizací, nikoliv pouze NK. Nicméně, svůj názor jsem do příslušného vlákna již vložila. https://github.com/NLCR/Standard_NDK/issues/45

**Comment by luckajirku** [comment]
tady nejde ani tak o issue 45, jako o issue 48, ostatně to nahoře i uvádím.

**Comment by ZdenkaSera** [comment]
@luckajirku Není tohle vyřešené s novým standardem pro vícedílky, který bude mít v ProArcu plnou verzi formuláře? Viz issue NDK Vícesvazková monografie https://github.com/proarc/proarc-client/issues/345

**Comment by ZdenkaSera** [comment]
@luckajirku navrhuji tohle zavřít, jen na to issue https://github.com/NLCR/Standard_NDK/issues/45 ohledně neplatných ččnb upozornit na schůzce k ProArcu a dát do zápisu ze schůzky -  ok?

**Comment by luckajirku** [comment]
@ZdenkaSera zatím jsme vícedílky pořádně netestovali, takže neřeknu a teď řešíme akutní věci. Jestli není třeba to nutně pozavírat, dej tomu klidně nějaký label "ležák" a projdu to, až bude volněji (leden to jistí:-)). Stejně tak i to issue k hudebninám.

**Comment by ZdenkaSera** [comment]
@luckajirku Děkuju, nějak to tedy označím, aby úplně nezapadlo - nejde o to zavírat za každou cenu, jen na mne vykukují věci, kde si nejsme jistá statusem.

**Comment by ZdenkaSera** [comment]
Otestovat s novými standardy.

**Comment by ZdenkaSera** [comment]
@luckajirku Navrhuji tohle k uzavření - obě zmíněná issues https://github.com/NLCR/Standard_NDK/issues/45 a https://github.com/NLCR/Standard_NDK/issues/48 jsou už zavřená a na úrovni vícedílky je v nové verzi standardů formulář rozšířený. OK?

**Comment by tumovam** [comment]
Zavírám na základě domluvy na schůzce.
