### ISSUE TITLE
MARCtoMODS zdvojení originInfo

### ISSUE THREAD

**Issue by jkremlacek** [proarc/proarc#747]
Při transformaci dat z alephu: 
https://gist.github.com/jkremlacek/d13286b142434bf89c127cc470747866
vzniká element originInfo dvakrát

```
<originInfo>
    <place>
        <placeTerm type="code" authority="marccountry">xr-</placeTerm>
    </place>
    <dateCreated encoding="marc">1786</dateCreated>
    <issuance>monographic</issuance>
</originInfo>
<originInfo eventType="production">
    <place>
        <placeTerm type="text" />
    </place>
    <publisher />
    <dateOther type="production">1786</dateOther>
</originInfo>
```

Přičemž u prvního selže RDA kontrola - v rámci kódu transformační šablony totiž odpovídá generování originInfo pro AACR.

Dle mého názoru by generování AACR varianty originInfo mělo obsahovat kontrolu na daná pole a jinak AACR variantu originInfo negenerovat, tedy do šablony doplnit:
```
<!-- originInfo 250 and 260 -->
<xsl:if test="marc:datafield[(@tag=260 or @tag=250)]">
```

**Comment by SykoraLukas** [comment]
Mohl bys z toho udelat PR do celeho proarcu?

**Comment by jkremlacek** [comment]
Done - https://github.com/proarc/proarc/pull/813
