### ISSUE TITLE
Neprojde vytvoření nového digitálního objektu pro výstřižky podle staženého záznamu 

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#748]
Zdravím,

snažíme se zprovoznit zpracování výstřižků v ProArcu a nedaří se nám po stažení záznamu z našeho knihovního systému vytvořit nový digitální objekt.

Chybová hláška po kliknutí na "Vytvořit nový objekt" je:

```
Failed to create digital object.

RDA rules: [Element: dateIssued nesmí být prázdný, pokud eventType: null!]
```

V logu proarcu k tomu není žádná hláška.

Záznam stažený z našeho knihovního systému (vykopíroval jsem html z proarcu, jako plain text by to asi nebylo moc čitelné):

```
<table xmlns:xlink="http://www.w3.org/1999/xlink">

<tbody><tr>
<td colspan="2"><b>Informace o titulu</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Titul</div>
</td><td>Poslední koncert</td>
</tr>


<tr>
<td colspan="2"><b>Jméno:
            Personal(
            usage=" primary")
        </b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Name Part:
            family</div>
</td><td>Fleszarowa-Muskat</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Name Part:
            given</div>
</td><td>Stanisława</td>
</tr>

<tr>
<td colspan="2">
<div style="margin-left: 1em">Role</div>
</td>
</tr>

<tr>
<td>
<div style="margin-left: 2em">Role Term:
            Code(
                marcrelator)
        </div>
</td><td>aut</td>
</tr>



<tr>
<td width="300pt"><b>Typ zdroje</b></td><td>text</td>
</tr>

<tr>
<td colspan="2"><b>Origin Information</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Vydání</div>
</td><td>monographic</td>
</tr>


<tr>
<td colspan="2"><b>Jazyk</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Language Term:
            Code(
                ISO639-2B)
        </div>
</td><td>cze</td>
</tr>


<tr>
<td colspan="2"><b>Fyzický popis</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Form(
                marcform)
        </div>
</td><td>print</td>
</tr>


<tr>
<td width="300pt"><b>Abstract:
            Summary</b></td><td>Výstřižky televizních kritik.</td>
</tr>

<tr>
<td width="300pt"><b>Poznámka:
            Statement of Responsibility(
            altRepGroup=" 00")
        </b></td><td>Stanisława Fleszarowa-Muskat</td>
</tr>

<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td colspan="2">
<div style="margin-left: 1em">Jméno:
            Personal</div>
</td>
</tr>

<tr>
<td>
<div style="margin-left: 2em">Name Part</div>
</td><td>Zajíc, Jan</td>
</tr>



<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>1975</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>forma: soubor výstřižků</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>nosič: papír</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>televizní inscenace (o nich)</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>televizní kritiky</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>úroveň zpracování: jednoduchá</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>výstřižky</td>
</tr>


<tr>
<td colspan="2"><b>Předmět</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Téma(
            lang=" cze")
        </div>
</td><td>způsob vydávání: monografie</td>
</tr>


<tr>
<td colspan="2"><b>Location</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Physical Location</div>
</td><td>ABG001</td>
</tr>


<tr>
<td colspan="2"><b>Informace o záznamu</b></td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">descriptionStandard</div>
</td><td>aacr</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Record Content Source(
                marcorg)
        </div>
</td><td>ABG001</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Record Creation Date(
            encoding=" marc")
        </div>
</td><td>171201</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Record Change Date(
            encoding=" iso8601")
        </div>
</td><td>19800101000000.0</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Identifikátor záznamu(
            source=" CZ-PrMKP")
        </div>
</td><td>2302296</td>
</tr>

<tr>
<td>
<div style="margin-left: 1em">Origin of Record</div>
</td><td>Converted from MARCXML to MODS version 3.5 using MARC21slim2MODS3.xsl
                (Revision 1.98 2018/02/09, ProArc patch 14.704 2018/03/02)</td>
</tr>

<tr>
<td colspan="2">
<div style="margin-left: 1em">languageOfCataloging</div>
</td>
</tr>

<tr>
<td>
<div style="margin-left: 2em">Language Term:
            Code(
                ISO639-2B)
        </div>
</td><td>cze</td>
</tr>



</tbody></table>
```

OAI našeho knihovního systému je (nastavení v proarc.cfg):

```
# OAI
# (2.1) povinné URL OAI serveru
catalog.oai.url=http://web2.mlp.cz/cgi/oai
# (2.1) povinné označení katalogu
catalog.oai.type=OAICatalog
# (2.1) název katalogu zobrazený uživateli
catalog.oai.name=Koniáš
# (2.1) povinný OAI metadata prefix pro data ve formátu http://www.loc.gov/stand
catalog.oai.metadataPrefix=marc21
# (2.1) nepovinný prefix identifikátoru, který se přidá před hodnotu vyplněnou u
catalog.oai.identifierPrefix=oai:www.mlp.cz:
# (2.1) povolená pole: id
catalog.oai.fields=id
# (2.1) název pole zobrazený uživateli
catalog.oai.field.id.title=Identifikátor
```

Testovaný identifikátor je: 2302296

V čem by mohl být problém?

PS: Výstřižky plánujeme zpracovávat jako NDK periodikum (každou obálku jako číslo), to ale s problémem nesouvisí - vytvoření nového objektu neprojde nehledě na to, jaký model vybereme a jde pouze o vytvoření nového digitálního objektu.

**Comment by jkremlacek** [comment]
V tomto případě je důležitý MARC záznam:
https://gist.github.com/jkremlacek/066b831f3579b72994d7c9765d1edc6b

ProArc upozorňuje na porušení pravidel RDA/AACR, kdy chybí údaj v dateIssued (protože není vyplněná hodnota v eventType).

Podle transformační šablony se hodnota **dateIssued** získává z **264|c** nebo **260|c** ani jedno pole v záznamu vyplněné není, stejně tak jako **eventType** (**264**), který by případně povinnost dateIssued upravoval.

Bude tedy potřeba nejdříve upravit záznam v katalogu, aby splňoval RDA/AACR pravidla.

**Comment by luckajirku** [comment]
Tak podle 008 je to neznámé datum. Těžko říct, co s tím, každopádně ale když píšete, že to chcete zpracovat tady jako periodikum, přitom bib záznam je monografický... Asi by byla na místě nejdřív konzultace s katalogizací.

**Comment by luckajirku** [comment]
S tím teda, že na pozici 7-10 v 008 byste ale stejně měli mít ještě uuuu.

**Comment by svetlym** [comment]
Děkuji za odpovědi.

Předal jsem to týmu zodpovědnému za vývoj našeho knihovního systému, bude asi chvíli trvat, než se k tomu dostanou.

Poprosím zatím tuto issue nezavírat, možná k tomu budeme mít ještě nějaké otázky.

**Comment by svetlym** [comment]
Přišlo mi vyjádření od správce našeho knihovního systému:

> Dobrý den,
> tak jsem dělal různé pokusy a zdá se, že ProArcu vadí písmenko "n" na 6. pozici v poli 008, 
> čili jde o sedmý znak neboli "Typ data/Publikační status". To "n" znamená neznámé datum 
> (což je fakt, pokud vím, tak u souborů výstřižků rok vydání normálně nemáme). Když tam 
> dám písmenko, které značí, že datum znám, například "s", tak se objekt vytvoří a ani tam 
> nemusím dávat na to "uuuu" na pozice 7-10. Jenomže tohle by asi bylo zase špatně z 
> hlediska katalogizačních pravidel. Na druhé straně když v ProArcu vyberu model "NDK Článek"
> místo toho periodika, tak naopak můžu v Marcipánu klidně nechat to "n", tohle ProArcu nevadí.

Rozumím tomu dobře, že u periodik je nutno znát datum vydání a bez toho záznam není platný,
zatímco u článků to nutné není?

Existuje případně nějaký způsob, jak vytvořit periodikum s tím, že datum vydání není známo?

**Comment by MartinRumanek** [comment]
Povinnost se řídí polem 264, jak psal @jkremlacek . Ve vašem záznamu to pole není.

Toto pole je povinné, viz doporučení pro periodika https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/katalogizacni-politika/minimalni-zaznam-rda-marc21-pro-textove-serialove-zdroje

Další zdroje k RDA jsou tady https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/katalogizacni-politika/rda

Pokud není katalogizační záznam podle standardu, nemusí transformační šablona do MODS fungovat.

**Comment by svetlym** [comment]
Výstřižky už jsme vyřešili, děkuju za pomoc.
