### ISSUE TITLE
Problém při seskupení

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#750]
Když použiji v okně Správa digitálních objektu  - Uživatel/Seskupení, tak se sice seskupí tituly podle uživatele, ale pokud klepnu už na jiný titul, neoznačí se mi a nenačte se mi do spodní nabídky jeho struktura. Atˇklepnu na cokoliv, dole se mi objeví úplně něco jiného.... myslím, že je problém s prohlížečem, protože kdyz zavřu všechny okna a vymažu historii a cash pamět a z novu se pak přihlásim do PA, tak to už funguje normálně (až do chvíle než opět použiji Seskupit, pak se problém opakuje). Problém je i v Mozzile i v Chome...nicméně nevím, co s tim

**Comment by SmejkalovaAnna** [comment]
U Monografií neseskupuje vůbec

**Comment by MartinRumanek** [comment]
> U Monografií neseskupuje vůbec

U monografií máš asi víc dokumentů, je to možné?

Je to nějaká chyba týkající se SmartGWT (frontend), chová se to dost nevypočitatelně - občas se to seskupí občas ne. S přibývajícími počty uživatelů/dokumentů je to problémovější. 

Druhá chyba (proklik do spodní nabídky) se mi nepodařila replikovat vůbec.

Je to kritická funkcionalita? Já bych to nejradši v tabulce zakázal, z podobných důvodů je zakázáno řazení. Oprava by byla celkem náročná (ve SmartGWT je to špatně zdokumentováno), možná to ani opravit dobře nejde.

Místo toho můžeš použít filtr na uživatele.

**Comment by MartinRumanek** [comment]
Seskupování není možné aktuálně implementovat nad větším počtem záznamů. Z podobných důvodů je zakázáno řazení sloupců (neumí to Fedora Repository).

**Comment by SmejkalovaAnna** [comment]
No tam je hromada dokumentů... ale bylo by to fajn, kdyby byla nejaká možnost si to seřadit podle uživatele... jak je tam toho hodně, tak se v tom špatně hledaj záznamy od jednoho uživatele....ještě to projdu to seskupování... teď jsem si našla svoje záznamy v Hledání ale našlo mi to jen záznamy z roku 2016 a 2017 ( v ostý verzi 3.4.1 )....je to divný, ještě to odzkoušim....
