### ISSUE TITLE
Nezapíše se do xml typ pravidel popisu při přeuložení formuláře

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#752]
Při opakovaném přeuložení formuláře, nezůstane zaškrtnutý typ pravidel popisu, který se mi stáhne při stažení metadat.  Zřejmně se to ani neuloží do XMl, protože mi házel i validator upozornění, že to tam chybí...

**Comment by MartinRumanek** [comment]
V dalším release bude opraveno.
