### ISSUE TITLE
RDflow - nabídka Vytvoření nového záměru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#759]
Pokud chci vytvořit nový záměr, vyberu si ve "Vybrat profil". Kliknu na roletku "Vytvořit nový záměr" a ta mi nabídne pouze "K4 Monografie", jejíž formulář se mi následně objeví. Do tohoto formuláře se vyplňuje jinak a hlavně autor se vyplní do poznámky místo do "autora". Potřebuji formulář NDK.

**Comment by MartinRumanek** [comment]
Odpověď je ve vedlejším issue https://github.com/proarc/proarc/issues/577#issuecomment-394949027

Vyzkoušteje to prosím, issue potom zavřeme.

**Comment by nezbedova** [comment]
<model pid="model:ndkmonographvolume" /> mi nefunguje. Přikládám xml
[RDflow_test_2018_14.txt](https://github.com/proarc/proarc/files/2096975/RDflow_test_2018_14.txt)

**Comment by MartinRumanek** [comment]
Díky za nahlášení chyby a přiložené XML. Chyba byla opravena a její oprava bude součástí další verze.

**Comment by nezbedova** [comment]
Ostatní modely jsem nezkoušela. Také by bylo dobré dát seznam modelů k ukázkovému xml.

**Comment by nezbedova** [comment]
Pošlete mi, prosím, odkaz na seznam modelů, které se mohou použít.
