### ISSUE TITLE
RDflow přednastavení zaškrtnutí

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#760]
Co přidat do xml níže, aby byl checkbox zaškrtnutý a případně šel ručně odškrtnout? Nechci to obcházet změnou na "Bez LZW".
<param name="param.imageProcessing.komprese" type="NUMBER" displayType="CHECKBOX" >
			<title lang="cs">LZW komprese</title>
			<hint lang="cs">LZW komprese</hint>
			<title lang="en">LZW komprese</title>
			<hint lang="en">LZW komprese</hint>
		</param>

**Comment by nezbedova** [comment]
Je to <input checked="" type="checkbox">. Ale KAM to mám připsat?

**Comment by MartinRumanek** [comment]
Checkbox se dá přidat pod task jako další parametr, např. to může vypadat takto.

```
    <task name = "task.chooseTitle">
        <title lang="cs">Výběr titulu</title>
        <hint lang="cs">Výběr titulu k digitalizaci. </hint>
        <hint lang="en">Choice of Title</hint>
        <param name="param.chooseTitle.param" type="NUMBER" displayType="CHECKBOX" >
            <title lang="cs">Test</title>
            <hint lang="cs">Test</hint>
            <title lang="en">Test</title>
            <hint lang="en">Test</hint>
        </param>
	<setMaterial materialRef="material.physicalObject" way="INPUT" />
    </task>
```
_____
Bohužel defaultní zaškrtnutí stávající worfklow neumí.
____
> Je to input checked="" type="checkbox"
> Ale KAM to mám připsat?

Tyto parametry workflow nesedí na schéma, odkud je máte? To je někde v dokumentaci/issues?

**Comment by nezbedova** [comment]
V dokumentaci to není. Checkbox si přidat umím. Pokud to stávající workflow, zadám tam "tif s LZW".
