### ISSUE TITLE
RDflow - automatické vyplnění uživatele

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#763]
V úkole po změně stavu na "Dokončen" automatiky vyplnit uživatele, který je přihlášený.

**Comment by MartinRumanek** [comment]
To RDFlow neumí, nyní je možné pouze přiřadit pevného pracovníka ke konkrétnímu stepu (na který je pak návázán úkol) takto:

```
<step taskRef="task.chooseTitle">
            <worker>proarc</worker>
</step>
```

**Comment by nezbedova** [comment]
Ve které verzi to bude umět? Myslím si, že to je jeden z požadavků na automatizaci.

**Comment by MartinRumanek** [comment]
Když se vymyslí další konfigurační direktiva, tak to půjde.

**Comment by SykoraLukas** [comment]
Naimplementováno
