### ISSUE TITLE
RDflow Chybová hláška

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#766]
Nemohu přijít na chybu v xml. Po nahrání dle validátoru validního [RDflow_test_2018_12.txt](https://github.com/proarc/proarc/files/2089897/RDflow_test_2018_12.txt) do test ProArcu se objeví hláška:

![obrazek](https://user-images.githubusercontent.com/13831946/41231304-f16ed950-6d82-11e8-958c-e3ed0ab34766.png)

**Comment by nezbedova** [comment]
Log od M. Dudy

**Comment by nezbedova** [comment]
Omlouvám se.
Se mi to tady nějak zbláznilo.

**Comment by nezbedova** [comment]
Provedla jsem opravu wf.valuemap.dpi a param.scan.underlay a param.scanOfCover.underlay

**Comment by nezbedova** [comment]
A nic. Chyba tam je stále.

**Comment by jkremlacek** [comment]
Vyjma zmíněných chyb tu vidím ještě param.scan.underlay.

**Comment by jkremlacek** [comment]
Bylo by možné nasdílet aktuální xml? Podíval bych se do interních chyb.

**Comment by nezbedova** [comment]
Poslední zkoušená verze 
[RDflow_test_2018_13.txt](https://github.com/proarc/proarc/files/2091007/RDflow_test_2018_13.txt)

A log od M. Dudy 
[proarc.2018-06-11.log.zip](https://github.com/proarc/proarc/files/2091009/proarc.2018-06-11.log.zip)

**Comment by jkremlacek** [comment]
Při načítání vyletí chyba: 
Undefined ID "wf.valuemap.underlay.color"

**Comment by nezbedova** [comment]
Opravila jsem "wf.valuemap.underlay.color"
Teď čekám na další narhání.

**Comment by jkremlacek** [comment]
Provedl jsem kontrolu původního xml a chybu mi vyhodil i validátor nad schématem - nejde tedy o bug.

Testováno [zde](http://www.utilities-online.info/xsdvalidation/).

**Comment by nezbedova** [comment]
Opravila jsem "wf.valuemap.underlay.color"
Teď čekám na další narhání.

**Comment by nezbedova** [comment]
Verze RDflow_test_2018_13.txt jsem testovala. Validátor mi chybu nehlásil. Neposílám p. Dudovi nic, co by mi neprošlo validátorem, který mám od Vás k dispozici.

Nejde o bug. Potřebuji to zprovoznit.

**Comment by jkremlacek** [comment]
Můžete mi prosím poslat odkaz na nástroj, kterým provádíte kontrolu? Je možné, že obsahuje chybu, protože pomocí nástroje, který jsem odkazoval výše, je chyba nalezitelná.

**Comment by nezbedova** [comment]
Používám Notepad++, který mi doporučila Lucka Pavlová.
xsd jsem měla staré bez modelu. Pak jsem si stáhla na základě odkazu  Vašeho kolegy z issues #578. S tím jsem porovnávala RDflow_test_2018_13.txt. Pokud se to dělá tak, že se to do  http://www.utilities-online.info/xsdvalidation/#.Wx9yUIoyWpo kopíruje do připravených oken.

**Comment by jkremlacek** [comment]
Zkoušel jsem Notepad++ a skutečně obsahuje chybu, kdy hlásí validní xml i při neexistujícím ID. 

V rámci [odkazu](http://www.utilities-online.info/xsdvalidation/#.Wx-B1xx9hhF) který jsem posílal probíhá validace tak, že:
1. do levého sloupce vložíte workflow.xml
2. do pravého sloupce vložíte xsd schema
3. kliknete na Validate XML against XSD 
4. v dolní části se poté zobrazí buď červeně chyba, anebo zeleně potvrzení validity

**Comment by nezbedova** [comment]
V Notepad++  bylo RDflow_test_2018_13.txt
![obrazek](https://user-images.githubusercontent.com/13831946/41279691-7afa4ab0-6e2d-11e8-82b0-8b3bb0cfa0d5.png)
