### ISSUE TITLE
Verze 3.4.4 export NDK bez URN:NBN

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#767]
Situace:
Nepřidám URN:NBN. Zadám NDK export. Vyběhne hláška, že chybí URN:NBN. Dám OK. Proběhne export, ve kterém je pouze log.
V minulé verzi to bylo nastavené tak, že pokud nebylo přidáno URN:NBN, objevila se hláška a export neproběhl.
Prosím opravit tak, jak to bylo v minulé verzi.

**Comment by MartinRumanek** [comment]
Zkusil jsem si vygenerovat testovací volume monografie bez urn:nbn ve verzi 3.4 a chová se to přesně tak (export jenom s logem).


Exportuje se jenom část balíčku, které urn:nbn obsahují, jakmile to narazí na první úroveň, která urn:nbn vyžaduje (issue nebo volume) tak je vyhozená výjimka a export končí. Funguje to tak od roku 2014. Samozřejmě je ale možné, že se pletu.

Nepamatujete si prosím v jaké verzi se to chovalo jinak?

Pokud si nemůžete nechat přidělit URN:NBN, můžete ho přidat uživatelsky (jakoukoliv hodnotu), tak jako je popsáno v podobném issue https://github.com/proarc/proarc/issues/208

**Comment by nezbedova** [comment]
Nevím, v jaké verzi se to tak chovalo. Bylo to velmi pohodlné. Pokud jsem nepřidělila urn:nbn, tak export neproběhl, takže jsem to nemusela nikde hledat a mazat.

**Comment by SykoraLukas** [comment]
Takovéto chování ProArcu v žádné verzi od 3.3 jsme nenašli. Vždy proběhne export a pokud je neuspěšný, vypadne jen adresář s logem, že export nebyl úspěšný a odůvodnění (nejčastěji chybějící URN:NBN). 

Takto vypadá neúspěšný export z verze 3.3.
![image](https://user-images.githubusercontent.com/27210823/41656655-0822cc32-7491-11e8-8c1f-b1d09d21913e.png)

**Comment by nezbedova** [comment]
Já jsem našla v dokumentaci s popisem NDK balíčku u MetsContext toto:

D"ále je tu metoda, která se použije v obou případech:
setOutputPath - nastavuje cestu, kam se budou výsledné PSP balíčky ukládat
setAllowMissingURNNBN - povolí/zakáže export elementů v případě, že nemají URNNBN"

Jestli se to nenastavuje někde u nás.

**Comment by SykoraLukas** [comment]
Mohl bych se zeptat na zdroj těchto informací?

**Comment by nezbedova** [comment]
https://docs.google.com/document/d/19qSzmX0fF5Wdii1VbrwpurxBVqcUhzxP4X5Ku0MdSz8/edit#

**Comment by MartinRumanek** [comment]
To je zajímavý dokument. Jsou tam popsány přímo metody ze zdrojového kódu, nejsou to konfigurační direktivy - ale dá se to využít a konfigurační direktivu z toho udělat.

O té metodě jsem věděl, ale když se to povolí, tak to nebude vypisovat žádnou chybovou hlášku - import proběhne naprosto bez chyb (ani v logu).
Název balíčku budé potom složen z UUID a ne URN:NBN. Je to dostačující?

**Comment by nezbedova** [comment]
Není to dostačující.
Ověřila jsem si u kolegyň, že to tak opravdu bylo. A uvítáme, když to tak bude znovu.
Pokud nezadám urn:nbn a kliknu na NDK export tak export nezačne, ale objeví se tabulka, která se objevuje, když kliknu na urn:nbn, ale nebudou tam :-) , ale budou tam :-(  Zavřu ji. Přidělím a pak až po kliknutí na NDK export začne probíhat NDK export.

**Comment by nezbedova** [comment]
Do které verze se počítá s touto opravou?

**Comment by SykoraLukas** [comment]
Pokud při neúspěšném exportu budeme mazat neúspěšně vyexportovaný balík, ztratí se s tím i log. Prosím o rozhodnotí @mduda100871, zda je to v pořádku.
