### ISSUE TITLE
Verze 3.4.4 nelze přesunout stránky z STT monografie do STT kapitoly

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#768]
Po pokusu přesunout strany z STT svazek monografie do STT kapitola se objevila hláška

![obrazek](https://user-images.githubusercontent.com/13831946/41351361-68af49ac-6f16-11e8-93a5-b2336eb5e4d4.png)

**Comment by jkremlacek** [comment]
Připojení stran pod kapitolu souvisí s https://github.com/proarc/proarc/issues/741#issuecomment-383876571 

Pravidla hierarchie jsou momentálně stejné jak pro NDK modely, tak STT.

Je potřeba, aby v rámci vývojového týmu vznikla shoda, jestli strana smí nebo nesmí být pod kapitolou, případně zda strany smí být pod kapitolou pouze pro STT.

**Comment by nezbedova** [comment]
Zkusila jsem to zadat správně podle NDK, ale to,co zobrazuje Kramerius (klient starý, modrý i nejnovější bílý) je hrůza.
V pondělí je formátový výbor, zeptám se tam.

**Comment by nezbedova** [comment]
Už vím, kde je chyba. Monografie rozdělená do kapitol vypadá  takto v ProArcu
![obrazek](https://user-images.githubusercontent.com/13831946/41464298-1717d002-709a-11e8-8f95-35abb75bef47.png)
A takto v Krameriovi
![obrazek](https://user-images.githubusercontent.com/13831946/41464338-38d2198c-709a-11e8-8f18-b65638031556.png)
STT vypadá v ProArcu takto:
![obrazek](https://user-images.githubusercontent.com/13831946/41464365-55ce5ce4-709a-11e8-95cc-ef6f140518f1.png)
A v Krameriovi takto:
![obrazek](https://user-images.githubusercontent.com/13831946/41464393-7546d6a0-709a-11e8-8630-ff5573a31581.png)
Kdy pod kapitolou A nejsou žádné strany.

**Comment by MartinRumanek** [comment]
Aha, takže problém je, že s těmito indexy neumí pracovat K4Export. Na to se zřejmě při implementaci https://github.com/proarc/proarc/issues/753 zapomnělo

K4Export s kapitolou neproběhne ani na podobně zpracované monografii podle NDK standardu.

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, prosím, mohla by ses na tohle podívat? Díky.

**Comment by nezbedova** [comment]
@ZdenkaSera Není to aktuální.

**Comment by ZdenkaSera** [comment]
@nezbedova Děkuji, s dovolením tedy zavírám.
