### ISSUE TITLE
Dotaz – články a kapitoly

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#770]
Mám jeden dotaz, z čeho ProArc vyrábí strukturální metadata v metsu v NDK balíčku, když jsou metadatové popisy udělané na úroveň článku nebo kapitoly? Aby Kramerius věděl, které stránky patří do které kapitoly/článku?
![structlink](https://user-images.githubusercontent.com/21309201/41537025-8996347e-7307-11e8-9cb4-6a3759e0eee5.jpg)

Přijde mi, že jediný údaj, z kterého se to může brát je MODS element part/extent/start a end, když se tam napíše index stránky?
Podle standardu MODS není zcela jasné, jaké číslo se tam má vyplnit – jestli index stránky nebo skutečné číslo stránky v reprezentaci.  Ale myslím, že logicky by tam mělo být skutečné číslo stránky, ptž ten údaj se zobrazuje a uživatel neví, co je index a bude pro něj matoucí, že na skenu je nějaké číslo a v metadatech jiné. A to ještě nemluvím třeba o generátoru citací, v citaci by určitě měla být skutečná čísla stránek a ne indexy. 
Tak by mě jen zajímalo, podle čeho ProArc ta strukturální metadata vyrobí? Zkoušela jsem udělat pod monografií záznamy kapitol a vyplnila jsem tam skutečná čísla stránek a nešel vyexportovat NDK export. Když jsem to přepsala na indexy stránek, tak už to šlo vyexportovat normálně.

Pokud jsem to vysvětlila nepochopitelně, tak se omlouvám a dejte vědět a já to zkusím vysvětlit znova.

**Comment by krizovj** [comment]
https://github.com/NLCR/Standard_NDK/issues/61

**Comment by MartinRumanek** [comment]
Ano, proarc využije si načte indexy z part/extent/start a part/extent/end.

Index je umělý (číslovaný od jedničky) - tak jak jsou stránky v editoru vazeb - to co je v metadatech se nijak do úvahy nebere (pageIndex ani pageNumber). Takže teď bys měla vyplňovat index. 

> Ale myslím, že logicky by tam mělo být skutečné číslo stránky, ptž ten údaj se zobrazuje a uživatel neví, co je index a bude pro něj matoucí, že na skenu je nějaké číslo a v metadatech jiné. A to ještě nemluvím třeba o generátoru citací, v citaci by určitě měla být skutečná čísla stránek a ne indexy.

Můj skromný názor je, že MODS stejně není vhodný pro uživatele, klientské aplikace (a snad i generátor citací) si můžou teoreticky na základě indexu natáhnout MODS konkrétní stránky a zobrazit co je potřeba. Index je lépe strojově zpracovatelný, structmap je fajn, ale např. součástí SIP balíčku u eMonografií vůbec není (tam je pouze MODS).

**Comment by krizovj** [comment]
No, teoreticky možná, ale prakticky o tom pochybuju.
Tak třeba Kramerius klient K5 zobrazuje prostě to, co je v MODSu, v Digitální knihovně se údaj o rozsahu stran kapitoly pro jistotu nezobrazuje vůbec a úplně nejvíc nejnovějšího klienta Krameria taky ne (u něj vlastně ani nevím, jestli už vůbec umí zobrazovat kapitoly). Myslím, že to asi nebude vůbec tak jednoduché, že si ten klient u všech stránek nejdřív podle indexu najde to správné číslo stránky a to teprve zobrazí. 
Ten generátor citací už je nastavený a stahuje si údaje normálně z MODSu. Nenapadá mě jiné místo odkud by je mohl stahovat. A taky nevím, jak by to ten generátor a vlastně i Kramerius dělal u článků v PDF? A celkově u PDF. U našich ečlánků to sice vyplňujeme od začátku na blbý místo (nevím ani moc proč), ale píše se tam normální číslo stránky.
A jak se to tedy bude dělat u těch emonografií? Kde vezme klient a generátor záznam té stránky v tom PDF, aby zjistil a zobrazil uživateli správné číslo stránky, když v MODSu bude jen index stránky v PDF? Záznam stránky v PDF přece neexistuje... Takže u emonografií a eperiodik se budou prostě zobrazovat pro články a kapitoly nesmyslná čísla stránek?
A u těch emonografií a současných eperiodik snad ta strukturální mapa bude, nějaká by tam být měla, aby Kramerius věděl, která kapitola (článek) je na kterých stranách a přitom nezobrazoval nesmyslné údaje (index). Podle mně by teda bylo řešení napsat ten index do ProArcu prostě jinam a použil by se pro zobrazení, ale nikde by se nezobrazoval.

**Comment by MartinRumanek** [comment]
Kramerius klient se dá upravit - výhodou by bylo, že by to fungovalo i pro staré dokumenty. Ale máš pravdu, že pro PDF to není řešení, to je dobrá připomínka, já si to neuvědomil.

V SIPU fakt ta strukturální mapa není, je součástí METsu a ten se tam vůbec nepoužívá. Kramerius by to poznal z MODSu stejně tak jak to teď dělá Proarc. 

Není jednoduché uložit něco jinam a neztratit to, dle mě by to mělo být nadále v MODsu, jen je teda potřeba pro to najít správné místo.

MODS strany už oboje obsahuje:
```
    <mods:part>
        <mods:detail type="pageIndex">
            <mods:number>1</mods:number>
        </mods:detail>
        <mods:detail type="pageNumber">
            <mods:number>[1]</mods:number>
        </mods:detail>
    </mods:part>
```
part/extent je opakovatelný a obsahuje volitelný unit (https://www.loc.gov/standards/mods/userguide/part.html#extent), to by se mohlo použít, vypadalo by to potom v kapitole takto:

https://www.loc.gov/standards/mods/userguide/part.html#extent
```
<part>
  <extent unit="pageIndex">
     <start>1</start>
     <end>2</end>
   </extent>
   <extent unit="pageNumer">
      <start>[1]</start>
      <end>[2]</end>
   </extent>
</part>
```

**Comment by krizovj** [comment]
Tohle jsem jako první navrhovala právě taky (v tom issue na NDK GitHubu), že by tam byl element extent dvakrát. Prý tam být ale nemusí, ptž údaje o struktuře jsou v strukturální mapě. Tak jsem právě myslela, že by se ten index napsal v ProArcu někam ještě jinam a z toho údaje by se vyrobila ta mapa no. 
Ale takhle, že by se ten element opakoval mi to taky přijde nejjednodušší. Ale mohlo by to být bez toho "pageNumber", ptž ten údaj v pageNumber je vždycky s nějakými závorkami a podobně a to taky nechci aby se zobrazovalo:

<part>
  <extent unit="pageIndex">
     <start>1</start>
     <end>2</end>
   </extent>
   <extent>
      <start>1</start>
      <end>2</end>
   </extent>
</part>

Může se taky stát, že tam žádné číslo stránky nebude - třeba u obálky. A bude tam jen index.

Šlo by to takhle? Pochopila jsem z toho, že by teda v podstatě stačilo přidat do ProArcu atribut "unit" a naučit Kramerius, aby se v záznamu díval na pageIndex a podle toho složil ty kapitoly (články) a čísla z toho druhého elementu extent by zobrazil. A pro ty si bude sahat taky generátor - teda už je takhle nastavený (ještě si to potom ověřím, aby ho nezmátl ten atribut unit=pageIndex).

**Comment by luckajirku** [comment]
@krizovj Teď se v tom trochu ztrácím - to "Může se taky stát, že tam žádné číslo stránky nebude - třeba u obálky. " se ale netýká snad NDK. Tam číslo strany (i fiktivní, dopočítané) musí být všude.

**Comment by krizovj** [comment]
No, v záznamu stránky být to číslo musí (i když by bylo třeba dopočítané), ale já myslím teď záznam článku. A tam bych ta dopočítávaná čísla stránek nedávala, jako aby tam bylo třeba [4] nebo 4a nebo tak. Tak buď by se tam napsalo normálně 4, i když by to na té předloze vytištěné nebylo a nebo bych tam nedávala nic a v tom záznamu by byla pouze čísla indexu.
