### ISSUE TITLE
Články a kapitoly - připojení metadat ke skenům

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#774]
Chtěli bychom doplňovat k naskenovaným a zpracovaným časopisům a později i monografiím záznamy článků a kapitol. 

Kapitoly už dělají třeba v MLP nebo v SVKHK. Příklady:
http://kramerius4.mlp.cz/search/handle/uuid:c7ab4f0a-2152-4d08-8b82-342072d4054b  (MLP-teď zrovna nefunguje)
http://kramerius.svkhk.cz/search/handle/uuid:b9b8bc67-c5ab-4831-808c-c1dc3f0b3758   (SVKHK)

Souvisí s těmito issues:
https://github.com/proarc/proarc/issues/770
https://github.com/NLCR/Standard_NDK/issues/61

Problém je, z čeho ProArc vyrobí strukturální mapu v NDK balíčku? Tedy jak jdou články za sebou a na kterých stránkách jsou. Každá stránka má pageNumber = číslo stránky a pageIndex = pořadí stránky.
V příkladech výše je to vyřešeno tím, že se do elementu part/extent/start a part/extent/end píše pageIndex první a poslední stránky. A tenhle údaj se pak zobrazuje i v Krameriovi. Shodli jsme se na tom, že je to blbost a že uživatele nezajímá, že článek začíná na indexu například 10, když skutečné číslo stránky (vytištěné v předloze) je 8.
Takže, šlo by to udělat tak, že by se do ProArcu přidal ještě jeden element part/extent a přidal by se k němu volitelný unit "pageIndex"? Takže by to v ProArcu vypadalo třeba nějak takhle? 
![rozsahstran](https://user-images.githubusercontent.com/21309201/42035166-9604eb78-7ae2-11e8-8e54-aa386376ca7d.jpg)

Takže když by byl vyplněn "pageIndex", tak by se v Krameriovi rozsah stran prostě nezobrazil a když by bylo vyplněno číslo stránky ("pageNumber"), tak by se to v Krameriovi zobrazilo. 

V MODSu stránky jsou totiž uvedeny oba údaje, takže když vyplníme  buď jen pageIndex, nebo jen pageNumber, tak by neměl být problém složit z toho strukturální mapu, tedy zjistit řazení a rozložení článků po stranách? Samozřejmě, že pokud budu vyplňovat "pageNumber", tak tam musí být úplně ten stejný údaj jako v MODSu stránky (tedy se závorkami, písmeny apod.). 
Šlo by to takhle? 

Ještě je tedy problém s tím, když je na jedné stránce více článků, tak je potřeba, aby to nevadilo, když budu mít ve dvou článcích uvedeno stejné číslo.

Níže ještě info, co šlo a nešlo vyexportovat z ProArcu:

Články, u nichž byla uvedena čísla stránek (pageNumber) - nešel ani jeden export (K4 a NDK)
Články, u nichž byla uvedena čísla indexu (pageIndex) - podařil se K4 export, ale nešel naimportovat do Krameria

Potřebovali bychom, aby fungoval i K4 export, i NDK export. 

Pokud je na vysvětlení něco nejasného, tak dejte vědět.

**Comment by krizovj** [comment]
No, takhle je to pro nás na zpracování nejlepší. Když tam bude jen index, tak v Krameriovi to číslo nebude, což bychom chtěli, ptž není potřeba, aby se u obálky časopisu zobrazovalo, že to strana [1a]. Nemusí tam být zobrazeno nic. Proto bychom tam napsali ten index, aby Kramerius věděl, na kterou to patří stránku, ale aby nezobrazoval to, co nechceme. 
Naopak když budeme chtít, aby ty stránky byly v Krameriovi zobrazené, tak vyplníme "pageNumber" a čísla stránek se zobrazí a zároveň se to podle nich srovná správně za sebou. Aby se vždy prostě vyplnilo pouze jedno. 

No, pro ty časopisy by to být mělo. Potřebujeme ty články zpracovávat tenhle rok a do konce roku by ty záznamy měly být v Krameriovi. A náš Kramerius to prostě zpracovat neumí, no. Umí to jen testovací. A nevím, jestli to do konce roku už bude umět. Radši bych to neriskovala.

**Comment by krizovj** [comment]
Myslím si, že NDK balíčky neumí kvůli tomu, že nemá image server. Jestli to má ještě nějaký další důvod, tak ho ví pan Duda.

**Comment by MartinRumanek** [comment]
Kramerius by měl umět naimportovat NDK balíčky i bez imageserveru - obrázky se zkonvertují jako interní datastream do Fedory

**Comment by krizovj** [comment]
Tak už bychom to prý nepotřebovali i pro K4 export, ale stačí pro ty NDK balíčky.

**Comment by SykoraLukas** [comment]
Formulář vyřešen takto:

![image](https://user-images.githubusercontent.com/27210823/48698639-e1056500-ebe7-11e8-9284-cd8e10cdf007.png)

![image](https://user-images.githubusercontent.com/27210823/48698671-f67a8f00-ebe7-11e8-9407-80119989f870.png)

**Comment by krizovj** [comment]
Tak jsem to prozkoumala a vypadá to, že ProArc vyrábí strukturální mapy v NDK balíčku podle těch čísel, která jsou v záznamu článku uvedena jako první. 

Takže u tohoto článku se strukturální mapa vyrobí správně a tím pádem i zobrazení v Krameriovi bude správné (asi, to teď zrovna zkouším):

![partok](https://user-images.githubusercontent.com/21309201/67261855-c47e4680-f4a2-11e9-85ae-833ee5693da5.jpg)

A u tohoto záznamu to bude blbě, ptž je na prvním místě partNumber:

![partblby](https://user-images.githubusercontent.com/21309201/67261925-1cb54880-f4a3-11e9-897a-0bbb63fc11c7.jpg)

Bylo by potřeba, aby ProArc složil tu strukturální mapu vždy podle pageIndex. Když bude v záznamu článku/kapitoly jak pageNumber, tak pageIndex, měl by si vzít ty údaje, které jsou uvedeny v pageIndex. Pokud tam bude jen jeden element part, tak použije to, co má...

**Comment by SykoraLukas** [comment]
Brát pouze z pageIndex (pokud ho nenajdu, brát z pageNumber). Pokud není uveden typ, použít první výskyt
