### ISSUE TITLE
Chybějící metadata v CEJSH exportu

### ISSUE THREAD

**Issue by MartinRumanek** [proarc/proarc#778]
@krizovj 
CEJSH – v exportu do CEJSHe se nezobrazují některá metadata – česká klíčová slova, český abstrakt, rozsah stran, u některých se číslo nezařadí do struktury časopisu.

**Comment by krizovj** [comment]
My jsme ale nechtěli do toho exportu nic nového. Tahle metadata tam dříve byla, ale pak vyšla nová verze ProArcu a ta metadata už tam nebyla. Ta šablona se právě nijak neměnila...

**Comment by MartinRumanek** [comment]
Ano, šablone se nijak neměnila od 15. září 2015, stejně jako se nijak nezasahovalo do exportů Cejshe.

Není možné, že se změnila některé pole v MODSu? (např. při přechodu na RDA)

**Comment by MartinRumanek** [comment]
\+ Pošli mi prosím MODS toho eČlánku, případně i vyšší úrovně, pokud je v nich něco zajímavého (ten abstrakt nebo nějaké jiné chybějící informace). Díky.

**Comment by krizovj** [comment]
Posílám MODS jednoho článku z Filosofického časopisu, kterému taky posíláme záznamy do CEJSHe:
https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:757dda6a-7ed7-4e42-a7ec-18a2eb9bada7/streams/BIBLIO_MODS

**Comment by melichova** [comment]
Výměna šablon se nepotvrdila. Potvrdilo se však to, že to souvisí s RDA, resp. s přidáním elementu do zjednodušeného formuláře pro e-články Physical description/fyzický popis. Problém se projeví u záznamů, které byly vytvořeny ve staré verzi ProArcu, kde ještě toto pole pro zápis nebylo. Po nasazení nové verze je toto pole automaticky prázdné a to způsobuje problém při exportu do CEJSHe - chybí české abtrakty, klíčová slova a hlavně rozsah stránek. - Toto se týká záznamů, které byly vytvořeny ve Zjednodušeném formuláři pro model E-článek ve verzi 3.3(asi) a starší.
Divné však je, že chybí české abtrakty, klíčová slova a hlavně rozsah stránek i u záznamů, které sice byly vytvořené, resp. stažené ve verzi starší, do normálního Formuláře modelu E-článek z katalogu Aleph, kde byly vytvořené podle RDA a tyto hodnoty se v ProArcu vyplní - zaškrtnutí RDA, a vyplněný element Physical description. Přesto však víše uvedené chybějící údaje exportní XML do CEJShe neobsahuje.

**Comment by melichova** [comment]
MODS periodika: https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:719be951-4eb0-11e1-9043-005056a60003/streams/BIBLIO_MODS
MODS ročník: https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:978723f5-4bde-49a2-86ec-f6717a415bf7/streams/BIBLIO_MODS
MODS číslo: https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:66b98633-b2ce-4204-95f2-887d55c88595/streams/BIBLIO_MODS
MODS článku, který byl nově vytvořený: https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:0474188c-91e2-451b-bfe0-50509c9d5d39/streams/BIBLIO_MODS
MODS článku, který byl stažený: https://kramerius.lib.cas.cz/search/api/v5.0/item/uuid:a1b8dfba-8da6-47cd-bd96-715fd815dc14/streams/BIBLIO_MODS

**Comment by krizovj** [comment]
Pořád platí i v testovací verzi 3.5.6 a už bychom to potřebovali opravit, aby se to nemuselo doplňovat ručně...

**Comment by pavelkocourek** [comment]
3.4.1. správně, ve vyšší chybí pole. Crossref má prázdný export
Schůzka 20.3.

**Comment by PetrKotynek** [comment]
Doplnění pro jistotu: tohle se kopíruje při upgrade :
proarc.work.prev/WEB-INF/classes/cz/cas/lib/proarc/common/export/cejsh/cejsh_journals.xml
proarc.work.prev/WEB-INF/classes/cz/cas/lib/proarc/common/export/crossref/cejsh_journals.xml
asi takto 
unzip proarc.war
cp -r ~/tmp/proarc.work.prev/WEB-INF/classes/cz/cas/lib/proarc/common ~/tmp/proarc.work/WEB-INF/classes/cz/cas/lib/proarc
zip -v -9 -r ../proarc.war ./*
zip -v -9 -r ../proarc.war.hack.beta-3.5.6.18.03.2019 ./*
[cejsh.zip](https://github.com/proarc/proarc/files/2987699/cejsh.zip)
Petr

**Comment by SykoraLukas** [comment]
Opraveno a přidány nové periodika k exportu
