### ISSUE TITLE
Nová verze - podpora e-dokumentů?

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#779]
Mám dotaz - v čem spočívá ta podpora e-dokumentů v nové verzi ProArcu? Chtěla jsem se podívat na formuláře, ale nenašla jsem tam žádný nový model. Takže tam ještě ty e-dokumenty nejsou?
https://github.com/proarc/proarc/releases/tag/v3.5-beta

**Comment by krizovj** [comment]
Určitě se má změnit ten konfigurační soubor ne? Můžete prosím někam napsat, co se do něj má přidat nebo změnit? Díky

**Comment by krizovj** [comment]
ok, díky

**Comment by krizovj** [comment]
Pořád tam ty elektronické dokumenty nemáme.

**Comment by MartinRumanek** [comment]
Prosím zkontroluj, že máš skutečně nasazenou posledně vydanou verzi
Build: 20180723132416, revize e16fe37ef

Další problém může být, že aplikace nebyla po změně konfigurace restartována. Přidání pluginu vyžaduje restart tomcatu.

**Comment by krizovj** [comment]
Už to tam je, tak to vypadá, že se to asi nějak samo restartovalo přes víkend. Dík
