### ISSUE TITLE
 v.3.4.1 a 3.5-SNAPSHOT nelze exportovat víceúrovňové vícesvazky

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#782]
Pokud založím Vícedílnou monografii, která má strukturu:
![obrazek](https://user-images.githubusercontent.com/13831946/44089632-cd4c8b36-9fc7-11e8-95b4-32a184012a04.png)
objeví se po zadání exportu chyba a export neproběhne.
Tento způsob zápisu by měl být možný podle standardů https://www.ndk.cz/standardy-digitalizace/pravidla_pro_popis_monografii_v2-1-2  str. 12

**Comment by MartinRumanek** [comment]
@SykoraLukas opravil. Bude v releasu 3.5.1.
