### ISSUE TITLE
3.5 - SNAPSHOT - Vícedílná eMonografie - uložení

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#785]
Když vyplním "title" (povinný) a uložím záznam, tak se bez problémů uloží. Což je špatně, měl by mě upozornit, že není vyplněn povinný element "originInfo". 

Když vyplním cokoliv v elementu "originInfo", tak se záznam neuloží a vyskočí "Neočekávaná chyba".

**Comment by MartinRumanek** [comment]
@SykoraLukas opravil. Oprava bude v releasu 3.5.1.
