### ISSUE TITLE
3.5 - SNAPSHOT - Svazek eMonografie - Editor digitalizovaných dat

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#788]
Z Editoru digitalizovaných dat se nejde přepnout na Metadata, zůstane tam Editor:
![emonografie](https://user-images.githubusercontent.com/21309201/44508377-59728d80-a6ae-11e8-867a-66aea5d5bc80.jpg)

Taky je v tom Editoru pro ta PDF asi k ničemu to přiblížení. Na PDF to nefunguje, je tam prohlížečka PDF a tam se to PDF dá taky přiblížit nebo oddálit. Přiblížení v ProArcu je asi určené pro skeny ne?
![pdf -](https://user-images.githubusercontent.com/21309201/44508476-bcfcbb00-a6ae-11e8-8a3b-0b2fcc402d3e.jpg)

**Comment by SykoraLukas** [comment]
Opět funkční. Opraveno v #781. Pokud bude zájem přiblížení se může odebrat pro tyto model, v takovém případě prosím založit nové issue
