### ISSUE TITLE
3.5 - SNAPSHOT - NDK Periodikum

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#789]
Když chci vytvořit nový záznam periodika, tak když ho stáhnu, tak se záznam vytvoří v pořádku, ale když vyplním prázdný formulář bez stažení, tak při uložení vyskočí "Neočekávaná chyba" a prostě se to neuloží. Žádné povinné pole mi nechybí.

**Comment by krizovj** [comment]
Asi to bude podobný problém jako https://github.com/proarc/proarc/issues/785 s "originInfo".

**Comment by krizovj** [comment]
Dělá to i u NDK Čísla.

**Comment by krizovj** [comment]
Ten problém asi bude u všech modelů, kde je element "originInfo"

**Comment by nezbedova** [comment]
Tato chyba se řešila v  #694

**Comment by SykoraLukas** [comment]
Opraveno u všech modelů s elemenetem OriginInfo. Problém byl v elemenetu <originInfo:Place:Type>, ve kterém byla defaultně nastavena hodnota TEXT, ale šablona MODSová vyžaduje pouze hodnotu text nebo code.

**Comment by MartinRumanek** [comment]
@SykoraLukas opravil. Oprava bude v releasu 3.5.1.
