### ISSUE TITLE
3.5 - SNAPSHOT - NDK eČíslo - Editor digitalizovaných dat

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#792]
V Editoru digitalizovaných dat u NDK eČísla chybí tlačítko pro smazání dokumentu. U eČlánku a u NDK Svazku eMonografie tlačítko je. 
NDK e Číslo:
![ecislo](https://user-images.githubusercontent.com/21309201/44512798-ef60e500-a6bb-11e8-863e-b8122391a7ad.jpg)

NDK Svazek eMonografie:
![emonografie2](https://user-images.githubusercontent.com/21309201/44512846-16b7b200-a6bc-11e8-84bf-f675e3bbcb66.jpg)

**Comment by MartinRumanek** [comment]
@SykoraLukas opravil. Oprava bude v releasu 3.5.1.
