### ISSUE TITLE
Číslo periodika - element part

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#794]
V elementu "part" je ve formuláři předvyplněna hodnota "issue", která je povinná, ale celý element je O. A problém je, že i když ten element "part" použít nechci, tak mi ho to v xml stejně vyrobí:
![cislo part](https://user-images.githubusercontent.com/21309201/44770158-663c2900-ab67-11e8-809f-eef09fc42dc9.jpg)
Šlo by to udělat tak, že pokud nevyplním to další pole "Detail caption", tak se ten element do xml vůbec nepropíše? A bude tam až když vyplním ten další údaj?

**Comment by SykoraLukas** [comment]
Ano, toto by šlo udělat

**Comment by krizovj** [comment]
Stejnou věc mi dělá formulář u NDK svazek monografie, s tím rozdílem, že tam je hodnota "volume". Šlo by to udělat stejně jako u toho čísla?
