### ISSUE TITLE
Implementovat Text Encoding Initiative (TEI)

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc#804]
https://en.wikipedia.org/wiki/Text_Encoding_Initiative

**Comment by svetlym** [comment]
Na co konkrétního by se tento formát používal?

**Comment by nezbedova** [comment]
Na STT.

**Comment by zabak** [comment]
V jakém rozsahu? TEI je hodně komplexní formát, teď se řeší v rámci projektu DL4DH ale pro implementaci bude potřeba poměrně přesná specifikace. Je cílem vyrábět v proarcu balíčky pro Manuscriptorium?

**Comment by luckajirku** [comment]
A není tohle issue už přežitý? Že se dohodlo, že v ProArcu se bude dělat podle toho doporučení (protože knihovny, které to chtěly používat, to chtěly primárně zpřístupňovat přes vlastního Krameria) a NK si stvoří nějaký nástroj na převod a o co bude stát, to si do formátu pro Manuscriptorium následně převede sama?

**Comment by zabak** [comment]
Právě, navrhuji zavřít.

**Comment by SykoraLukas** [comment]
Zavírám na základě labelu.
