### ISSUE TITLE
Ošetřit všechna data na GDPR

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc#805]

**Comment by pavelkocourek** [comment]
JK - zjistí, co vše bude třeba ošetřit.

**Comment by krizovj** [comment]
Je potřeba přidat nějaké odsouhlasovací okno, kde bude uživatel souhlasit se shromažďováním osobních údajů. Což je jméno, příjmení a e-mail. Přesný text ještě doplním později.

**Comment by krizovj** [comment]
Dále je potřeba, aby bylo možné vypsat všechny záznamy, které daný uživatel vytvořil.

**Comment by krizovj** [comment]
Nevím, jak budou ve správě uživatelů řešena oprávnění uživatelů? To s tím souvisí, ptž my například jsme měli jako uživatelské jméno v ProArcu příjmení. To se změnilo na šifru, ale potřebovali bychom, aby ten uživatel s novým uživatelským jménem mohl spravovat taky ty svoje záznamy, které vyrobil pod tím původním uživatelským jménem. 
Existuje pro to nějaké podrobné zadání, jak to bude přesně fungovat?

**Comment by krizovj** [comment]
Přidat možnost, aby šlo přepsat vlastníka objektu a pak smazat uživatele (kvůli odchodu zaměstnanců apod.).

**Comment by ZdenkaSera** [comment]
Na schůzce vývojového týmu 7.11.2023 se rozhodlo o uzavření issue s tím, že výše vyjmenované kroky připravené k realizaci jsou postačující.
