### ISSUE TITLE
Test v. 3.4.4 Nejde Export pro K4 s kapitolami

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#817]
Po přidání Kapitol u NDK monografie nejde Export pro K4. Píše to tuto chybu:
[object Object]
Status: -90
Query: { "operationType":"add", "dataSource":"isc_ExportDataSource_4", "data":null, "requestId":"isc_ExportDataSource_4$627249", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP5", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_4", "data":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" }, "requestId":"isc_ExportDataSource_4$627249", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP5", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1537792381801, "useHttpProxy":null, "actionURL":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "params":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public", "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_ExportDataSource_4", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "callback":{ "target":{ "ID":"isc_ExportDataSource_4", "dataFormat":"json", "requestProperties":{ "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog" }, "fields":[ { "name":"target", "type":"text", "$61":true, "$62":{ "validators":[ { "type":"isString", "typeCastValidator":true, "_generated":true, "$174l":true, "stopIfFalse":true, "defaultErrorMessage":null } ], "name":"text", "$68":true }, "title":"Target", "$76s":true } ], "operationBindings":[ { "operationType":"add", "dataProtocol":"postParams", "requestProperties":{ "httpMethod":"POST" } } ], "dataURL":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "jsonPrefix":"", "jsonSuffix":"", "recordXPath":"/response/data" } }, "_dsRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_4", "data":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public", "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_ExportDataSource_4", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "requestId":"isc_ExportDataSource_4$627249", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP5", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_ExportDataSource_4", "data":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" }, "requestId":"isc_ExportDataSource_4$627249", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "showPrompt":false, "lastClientEventThreadCode":"MUP5", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog", "$135u":null, "bypassCache":true, "originalData":{ "pid":[ "uuid:114323eb-9196-4bec-bc36-9834dbaf385e" ], "policy":"policy:public" } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1537792381801, "useHttpProxy":null }, "transport":"xmlHttpRequest", "serverOutputAsString":true, "suppressAutoDraw":true, "$185x":"https://proarc-test.libj.cas.cz/proarc/rest/v1/export/kramerius4", "promptCursor":"progress", "useCursorTracker":false, "cursorTrackerConstructor":"Img", "cursorTrackerProperties":{ "src":"[SKINIMG]shared/progressCursorTracker.gif", "size":16, "offsetX":12, "offsetY":0 }, "operation":{ "ID":"custom", "type":"rpc" }, "transactionNum":248 }

**Comment by nezbedova** [comment]
Export bez kapitol jde.

**Comment by nezbedova** [comment]
Problé je, že nejde u STT, kde není jiná možnost exportu. Proto přidávám příznak bag.

**Comment by krizovj** [comment]
@nezbedova mohla byste prosím vyzkoušet, jestli to v současné testovacím verzi pořád nejde nebo jde? Že bychom to zavřeli.

**Comment by SykoraLukas** [comment]
@ZdenkaSera muzeme prosim pohnout s timto issue? Mohla byste to prosím otestovat?

**Comment by nezbedova** [comment]
K4 export ve v 3.7 proběhl.

V testovacím Krameriovi se v jádru zobrazuje https://k4test.lib.cas.cz/search/i.jsp?pid=uuid:bbaf5d76-372e-4804-af80-6b471e5a5556&q=kniha :
![obrazek](https://user-images.githubusercontent.com/13831946/134307973-011e1e06-a30d-4b66-945f-a71e24b82ade.png)



V novém klientovi v. 2.1.2 se žádné kapitoly nezobrazují.

https://new-client-test.lib.cas.cz/view/uuid:bbaf5d76-372e-4804-af80-6b471e5a5556?page=uuid:305c7261-bb31-403d-907c-4d0db496cc92

@ZdenkaSera @kerschfilip @SykoraLukas Nevím, zda to je chyba ProArcu nebo Krameria.

**Comment by SykoraLukas** [comment]
Bohužel sek vám na testovacá server nemůžu připojit. Ale obecně platí, že jestli že je správně ve starém klientovi/jádru, ale v novém ne, tak je problém v novém klientovi Krameria.

**Comment by ZdenkaSera** [comment]
Koukala jsem na to včera - je to sice historicky nahlášeno jako chyba Krameria, ale chci se ještě podívat na metadata podle standardu. Z pohledu exportu ale navrhuji toto issue zavřít. @nezbedova Souhlasíš?

**Comment by nezbedova** [comment]
@ZdenkaSera souhlasím se zavřením.

**Comment by ZdenkaSera** [comment]
@nezbedova Děkuji a zavírám.
