### ISSUE TITLE
ProArc - chybová hláška

### ISSUE THREAD

**Issue by bjacekj** [proarc/proarc#820]
Při spuštění ProArcu (http://proarc.fsv.cuni.cz/proarc/#doManager:) se objeví chybová hláška "_Načítají se číselníky a lokalizace formulářů..._" a dále se ovšem nic neděje. Podobnou chybu vidím poprvé a trvá již dva dny.
--

**Comment by SykoraLukas** [comment]
Mohu se zeptat jakou verzi ProArcu používáte? Nejspíš je problém v načtení nějakých parametrů. Mohl byste mi prosím poslat do mailu váš konfigurační soubor(y). Dříve vám ProArc fungoval, nebo toto je první spuštění?
