### ISSUE TITLE
Možnost označit vše

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#824]
Prosíme o úpravu funkčnosti - při záměny strany za jinou ve vazbách ( při opravě ) - při klepnutí na "Uložit změny" - aby se v celé dávce ( resp. číslo nebo monografie ) se automaticky přepočítal index stran a uložil.

**Comment by SykoraLukas** [comment]
Reindexaci chtele dělat z editoru vazeb? 

Příklad: V okně "Hledat" najedu na model Svazek monografie a kliknu na "Vazby". V editoru vazeb zedituji podřízené modely (v tomto případě strany) a kliknu na tlačítko "Uložit", které se váže na právě otevřený model.

Při ukládání by se reindexovaly všechny strany, které patří pod ten rozkliknutý model (Svazek monografie)?

**Comment by luckajirku** [comment]
no... byla bych asi proti. Je to opravdu takový problém, že to potřebujete dělat automaticky?

**Comment by SmejkalovaAnna** [comment]
Bylo by to pro nás jednodušší....zpříjemnění práce....

**Comment by luckajirku** [comment]
Zpříjemnění práce... V tom případě bych přidala i tlačítko "Uvařit kafe" :-)
Dobře, teď vážně. Při výměně strany za stranu to moc nechápu, protože tam není co přeindexovávat u zbytku dokumentu - pokud je to strana za stranu, tak starou smažu, u nové doplním číslo strany a index a mám hotovo. Navíc pokud by se automaticky přeindexovávalo - uvědomí si uživatel, že u čísel stran se mu tohle dít nebude, že tam to musí udělat ručně?
Prostě aby systém přeindexoval strany, když uživatel klikne na Uložit, tomu bych se bránila - uživatel od Uložit čeká právě uložení toho, co udělal, a ne že systém bude kreativní a bude dělat něco navíc. Navíc u velkých dávek by to znamenalo zbytečné čekání, kdyby člověk dělal nějakou jinou změnu a chtěl opravdu jen uložit tu změnu, která se do indexů stran vůbec nepromítne. Na začátku je možnost přidělit indexy automaticky na zaškrtávání - tady by uživatel neměl možnost volby, a to není v pořádku.

ALE: něco jiného by byla možnost (tlačítko?) přeindexovat vše v té dávce bez nutnosti označit strany - bez kliknutí na Vybrat vše a pak Editovat index stran... - tam bych možná smysl viděla, ušetříme dvě kliknutí.

**Comment by SmejkalovaAnna** [comment]
Ano ano, tu druhou možnost, šlo by to tak udělat?  Udělat ve vazbách tlačítko **Vybrat vše**.... a pak už si to dávkově zedituji....

**Comment by luckajirku** [comment]
Jako bylo by to fajn - v Editoru připojených objektů vedle Označit řadu by se přidalo tlačítko Označit vše - v okně Metadata bychom tím pádem nemuseli ručně označit všechny řádky, kterých se to má týkat, pokud chci např. změnit index u celého dokumentu.
Jak by se to ale chovalo v případě, že tam budu mít v monografii mezi stránkami kapitoly, tedy vnořený jiný model? Asi by to muselo provádět kontrolu - a pokud by všechny objekty (strany) nebyly stejného modelu, tak zařvat a neudělat to...

**Comment by SykoraLukas** [comment]
V `editoru vazeb` a v obrazovce `příprava metadat` přidat možnost vybrat všechny objekty, které mají stejný model jako ten, na kterém stojím.

**Comment by krizovj** [comment]
V editoru vazeb jsem nenašla nic, co by vypadalo jako vybrat vše. Je tam jen tlačítko "Reindexovat", které se objeví, jen když jsem na straně, když se překliknu na záznam kapitoly, tak zmizí. Reindexace stran funguje. 
To je ono?

**Comment by krizovj** [comment]
V přípravě metadat je tlačítko "označit vše" a funguje:
![824test](https://user-images.githubusercontent.com/21309201/73047059-bb6f8d80-3e74-11ea-8cda-adfdb6ad2aa0.jpg)

V editoru vazeb není tlačítko "označit vše", ale je tam tlačítko "reindexovat". 
@nezbedova stačí to takhle? Může se zavřít?

**Comment by nezbedova** [comment]
Stačí. Zavírám.
