### ISSUE TITLE
Validátor vyhodí chybu u kapitoly

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#829]
Když zařadím kapitolu do NDK Monografie, tak se mi vyexportuje NDK balík, ale validátor mi hodí chybu viz přiložený log. 
[2018_11_01_11_53_37_aba007-00004u.txt](https://github.com/proarc/proarc/files/2538301/2018_11_01_11_53_37_aba007-00004u.txt)

**Comment by SykoraLukas** [comment]
Jakou chybu konkrétně myslíš? Mohla bys mi poslat do mailu balík, který validuješ? Jediný rozdíl oproti normální NDK Monografii bez kapitol vidím v tomto _ERROR: checkBibliographicMetadataMatchProfile: prázdný typ šablony pro CHAP_ER_0001; pøeskakuji validaci MODS a DC zázanamù_ a z toho se nedá určit, kde je chyba. 

Ostatní chyby a warningy jsou již opravené a budou v nové verzi.

**Comment by SykoraLukas** [comment]
Mohla bys mi tento balík vyexportovat do archivního balíku abych si ho mohl naimportovat u sebe do sveho proarcu a otestovat to?
