### ISSUE TITLE
3.5. - SNAPSHOT - nepropisuje se datum ročníku z formuláře do popisu

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#830]
Z metadatového formuláře se nepropíše datum vydání do stromové struktury periodika ( jak to bylo dřív např. 63, 1965 )

**Comment by SykoraLukas** [comment]
Jaký model NDK Číslo?

**Comment by SmejkalovaAnna** [comment]
NDK ročník, v Modsu to je ale nezobrazí se to v PA v té stromové struktuře

**Comment by SykoraLukas** [comment]
Opraveno, nejprve je rok a poté datum, tak jak to bylo dříve.
