### ISSUE TITLE
3.5. - SNAPSHOT - NDK Ročník - chybí element Genre

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#832]
Při vytváření NDK Ročníku se do pole Genre předepíše "title" ale má tam být "volume". Validátor mi hodil chybu, že tam chybí celý element: MODSMD_VOLUME_0001: /mods:mods: nenalezen očekávaný povinný element 'mods:genre[text()='volume']'
z PA:
![obrazek](https://user-images.githubusercontent.com/24409660/47858548-a1b7d580-ddec-11e8-846b-c74d02858b54.png)

**Comment by tumovam** [comment]
Řešeno již v issue [#790](https://github.com/proarc/proarc/issues/790)
