### ISSUE TITLE
PA 3.5.1 - Nevytvoří se nový objekt

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#838]
Při zakládání nového objektu, mi vyběhne hláška, že nesmí být Eventype prázdný a objekt se nevytvoří viz obrázek níže. Bez toho nemohu dále testovat
![obrazek](https://user-images.githubusercontent.com/24409660/47985708-cd7fd780-e0da-11e8-8b85-e0829d628efc.png)

**Comment by SykoraLukas** [comment]
Podívám se na to

**Comment by SykoraLukas** [comment]
Podívám se na to

**Comment by SykoraLukas** [comment]
Můžete mi poslat odkaz na záznam, který se snažíte stahnout?

**Comment by SmejkalovaAnna** [comment]
No je to v tom obrázku je tam čárový kód a stahuju to z našeho katalogu, my nekontrolujem katalogizační záznamy....

**Comment by SykoraLukas** [comment]
Zkontroloval jsem vas zaznam. Je podle standardu RDA a obsahuje 2 originInfo. Jeden má definovaný eventtype=publication druhý nemá. Opravte mě, pokud se pletu, ale jestli dobře chápu standard, tak pokud jsou pravidla RDA, tak musí být vždy vyplněn eventType.

**Comment by SmejkalovaAnna** [comment]
Lukáši já fakt nevim... já nejsem katalogizátor, já viděla pravidla aacr naposledy ve škole a RDA nikdy.......ale jak je možný, že jsem tuhle knížku asi před měsícem zpracovala ve verzi 3.4.1 a normálně to prošlo? Dám podnět do katalogizace, aby to opravili.... díky

**Comment by SykoraLukas** [comment]
Souvisí to s opravou #828. EventType je povinný jen pokud jsou pravidla RDA. Proto nemůžeme udělat, že je pole required. Jak jsi psala, aby to upozornovalo na to, že chybí vyplněná hodnota EventType pokud je RDA, tak jsem to udělal tak, že pokud je RDA a není vyplněné EventType, tak to hlásí chybu a nedojde k uložení, bohužel poté to vede k tomu, že když je špatně popsaný záznam, Pravidla RDA ale nevyplněný eventType tak se objekt nevytvoří vůbec. 

Jsou tedy 2 možnosti jak toto řešit. Budto se musí opravit záznam v katalogu a ten poté znovu stáhnout, nebo se zruší oprava z #828. Co je lepší?

**Comment by SmejkalovaAnna** [comment]
Asi je lepší aby se to opravilo v katalogu... nechcete to jak to je, jak jste to opravili.... nic s tim tedy zatím nedělejte. Proberu to s Martinou, až tady bude. Ale myslím, že katalogizační záznam by měl být primárně v pořádku... díky

**Comment by SykoraLukas** [comment]
Mohl bych poprosit ještě o nějaké čárové kody jiných monografii/periodik? Vyzkouším na nich, jak se to chová. Je totiž možné, že je problém v transformační šabloně.

**Comment by SmejkalovaAnna** [comment]
Jasný, pošlu do mejlu...

**Comment by luckajirku** [comment]
A není zas zpátky ten problém s dvojením origininfo viz #747? Ten záznam vypadá v pořádku.

**Comment by SykoraLukas** [comment]
AACR fungují správně.

Problém je se záznamy RDA, bohužel nevím jak vypadá původní záznam, ale do ProArcu se to překládá takto:
![image](https://user-images.githubusercontent.com/27210823/48001530-1f3f5680-e109-11e8-89fd-d9521dfd3eda.png)

**Comment by luckajirku** [comment]
původní záznam těch superhrdinů je tady https://vufind.lib.cas.cz/ustav/KNAV/Record/002313277#details

**Comment by SykoraLukas** [comment]
Když koukám do standardu, tak pole 250|a patří pod standard AACR, ale pole 264 pod RDA. Je to tak Lucko?

**Comment by luckajirku** [comment]
250 je u obojího, ne? co se rušilo je v aacr 260 a z té je v rda 264

**Comment by SykoraLukas** [comment]
Podle [standardu pro monografie str. 33](https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2) právě není. Edition uvádějí jen u AACR. OriginInfo podle RDA se o takové možnosti vubec nezminuje.

**Comment by SykoraLukas** [comment]
A myslim, ze to je ten duvod, proc se vytvaří originInfo bez eventType a následně neprojde vytvoření objektu

**Comment by luckajirku** [comment]
hm, vypadá to, že by asi stačilo to ve standardu jen na té straně 33 oranžově podbarvit. Ale v šabloně LoC to je.

**Comment by luckajirku** [comment]
Pořád nějak nechápu, proč se Origininfo tvoří dvojí. Evidentně ten první výskyt je poskládaný z údajů z LDR, 008 a 250 a ten druhý čistě jen z 264.

**Comment by luckajirku** [comment]
Hele já bych se držela tohohle: "Element je opakovatelný. **Alespoň v jednom případě** musí být vyplněna hodnota eventType=”production” nebo eventType=”publication”. "
Takže u RDA povinně mít OriginInfo tvořené z 264 s Eventtype, ale povolit i další výskyty OriginInfo tvořené z těch jiných polí a tam eventtype nevyžadovat, protože tam nemá co dělat.

**Comment by SykoraLukas** [comment]
Dobře, takže zrusit opravu #828, souhlasíte?

**Comment by SmejkalovaAnna** [comment]
No tak asi jo.... Co Lucka na to?

**Comment by SykoraLukas** [comment]
@luckajirku můžu tě poprosit o vyjádření, zda s odebráním změny #828 souhlasíš?

**Comment by luckajirku** [comment]
Upřímně nerozumím tomu, co přesně ta změna dělá, resp. jestli to řeší náš problém. Než se tam zas udělá něco narychlo, tak je potřeba nejdřív vědět, jestli u těch RDA záznamů bude vždy ten eventtype. Kopíruju z https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/katalogizacni-politika/katalogizace-podle-rda-ve-formatu-marc-21-tistene-a-elektronicke-monografie-katalogizace-na-urovni-minimalniho-doporuceneho-zaznamu: "Podle POVINNÉ JE VŽDY POLE 264 S DRUHÝM INDIKÁTOREM 1, a to i v případě, že údaje nelze převzít z knihy, ale musíme je dohledat či logicky odvodit alespoň místo a datum vydání. Pouze pokud pro pole 264_1 nelze zjistit ani tyto základní údaje, je doporučeno použít další výskyty s příslušnými indikátory (viz Doporučený záznam níže). Tato situace ale není příliš pravděpodobná, protože neznámé místo a rok vydání obvykle lze odvodit buď z údajů o distribuci nebo z údajů o tisku" 
- takže předpokládejme, že 264_1 budeme mít (až na pár výjimek) vždy, tzn. origininfo s eventtype by měl být vytvořen u RDA záznamů vždy. Já pořád nerozumím tomu, o co vlastně jde, vidím to takhle https://github.com/proarc/proarc/issues/838#issuecomment-435911022.

**Comment by luckajirku** [comment]
Nebo ta varování nejsou schopná vzít v potaz i jiný výskyt Originfo v tom objektu? Jestli to chápu správně, tak potřebujeme, aby to po nás vyžadovalo vyplněné origininfo s eventtype, ale zároveň, pokud je tahle podmínka splněna, to už neřvalo u dalších výskytů origininfo.

**Comment by SykoraLukas** [comment]
Dobře, mohu to udělat tak, když budou pravidla RDA a alespoň jeden originInfo s vyplněným eventType tak chybová hláška nevyskoci a vše bude v pořádku. Pokud ale nebude vyplněný žádný eventType vyskočí varovná hláška a v případě ze by to nastalo u stahování dat z katalogu objekt nebude vytvořen, protože to znamená, ze je špatně záznam v katalogu.

**Comment by SmejkalovaAnna** [comment]
To vypadá fér :) Co Lucka na to?

**Comment by luckajirku** [comment]
No úplně přesně s vyplněným eventtype s ”production” nebo ”publication”, ale jinak OK, tohle už by mělo vyřešit jak původní problém, který se měl tou 828 vyřešit, tak ten, který naopak ta úprava vyvolala:-).

**Comment by SykoraLukas** [comment]
Dobře, takže když bude alespon jeden eventType _production_ nebo _publication_ tak to nebude hlasit chybu, jinak ji to hlasit bude.

**Comment by SykoraLukas** [comment]
To znemožnění se váže na tu hlášku. Když si data vyplnuji sam a nemam to podle pravidel RDA, tak mi vybehne hlaska a tam musim odsouhlasit ze s tim souhlasim a pak se to uloži i špatně, ale uživatel o tom ví. Pokud stahuji data z katalogu a není to podle pravidel (chybí vyplněný eventType při RDA) tak to neí jak uživateli sdělit, aby si mohl odkliknout, že i přesto s tím souhlasí (omezení smartGWT). Proto nedojde k uložení takového objektu.

**Comment by luckajirku** [comment]
A to se týká všech povinných elementů?

**Comment by SykoraLukas** [comment]
Ne jen u tohohle elementu

**Comment by luckajirku** [comment]
Pak mi to nedává smysl. Je nakladatel mnohem zásadnější údaj než třeba název? Proč při absenci jednoho povinného pole uživatel objekt nezaloží, a při absenci jiného ano?

**Comment by SykoraLukas** [comment]
Protože aby se mohla kontrolovat pole podminena pravidly rda/aacr, musela se vytvořit pravidla, která toto kontrolují. Když je něco v obou pravidlech a uživatel to nevyplní, tak mu vyskočí u daného pole červený vykřičník (kontroluje to klient). Když je to pole povinné jen pokud je to např RDA, tak se to nedá kontrolovat na klientovi, ale musí to kontrolovat server a ten pokud to je ma byt vyplněný tak nedokaze k poli dát vykřičník, ale vyhodí okno s hladkou, kde j3 napsané, jaké pole neni vyplněné.

**Comment by SykoraLukas** [comment]
Ano, tohle je ideální příklad.

Nový klient musí brát ohled na zvolena pravidla a podle nich hlídat, které pole mají být vyplněna a která nesmějí.

**Comment by SykoraLukas** [comment]
Opraveno, pokud mám vybrané pravidla RDA a v originInfo ani v jednom případě nemám _eventType=publication_ nebo _eventType=production_ tak se vyhodí hláška a uživatel ji musí odsouhlasit.

**Comment by nezbedova** [comment]
Znovu otevřeno. Nelze testovat nové záznamy STT.

**Comment by nezbedova** [comment]
Nový objekt STT Monografie:
nejde založit http://clavius.lib.cas.cz/katalog/l.dll?cll~P=516088&TL=MR21

jde založit (kombinace AACR a RDA): http://clavius.lib.cas.cz/katalog/l.dll?cll~P=515134&TL=MR21
jde založit (AACR) http://clavius.lib.cas.cz/katalog/l.dll?cll~P=389632&TL=MR21


jde založit (RDA) https://aleph22.lib.cas.cz/F/GU68Y91IA4YUVT5FI2M15H27FRST8P2S6KXCFRUFR883SLHPL4-27595?func=full-set-set&set_number=001383&set_entry=000002&format=002

jde založit (AACR)https://aleph22.lib.cas.cz/F/GU68Y91IA4YUVT5FI2M15H27FRST8P2S6KXCFRUFR883SLHPL4-28410?func=full-set-set&set_number=001383&set_entry=000005&format=002

Nejde založit ani jako NDK monografie http://clavius.lib.cas.cz/katalog/l.dll?cll~P=516088&TL=MR21

Zjišťuji rozdíly mezi záznamy.

**Comment by nezbedova** [comment]
@luckajirku Myslíte si, že by to mohlo být chybějícím znakem na druhém místě u pole 210 ?
Záznamy s polem  210 00 jdou založit.
Záznamy s polem 210 0# nejdou založit.
Nebo mám hledat ještě dál? U polí 260 a 264, která jsou vyplněna v jednom záznamu současně (ano, je to nesmysl) tam to je jedno. To projde. Jediný rozdíl jsem našla u pole 210.

**Comment by luckajirku** [comment]
To není chybějící znak, to je jedna z možných platných hodnot. Zkoušela jste to na různých záznamech, nebo také na tom samém záznamu? To bych zkusila u toho, který neprochází, změnit zkusmo druhý indikátor na 0, jestli to projde.

**Comment by nezbedova** [comment]
Zkoušela jsem to na různých záznamech. Ve spolupráci s KVO jsem vyzkoušela 210 00 a nejde to.

**Comment by luckajirku** [comment]
Tak bude chyba ještě jinde. Já na to dnes už nemám čas ty záznamy porovnat, až příští týden...

**Comment by nezbedova** [comment]
Záznam nejde založit, pokud má v "descriptionStandard" vyplněné RDA.
Záznam, který nejde založit, jsem založila jako Záměr. Smazala jsem datum, doplnila Event a stejně to hází chybu a nejde to založit. Když jsem to opravila, aby to odpovídalo AACR, tak to stejně nejde založit. A to ani jako NDK monografie.

**Comment by pavelkocourek** [comment]
Návrh ze schůzky 25.3. - konfigurovatelná možnost pro model Staré tisky nekontrolovat při načtení data
