### ISSUE TITLE
3.5.1 - U NDK Ročník - nepropíše se číslo ani datum ročníku do stromové struktury

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#839]
stejně jako v minulé verzi issue 830, ale teď se nepropíše do názvu ve stromové struktuře ani číslo ani datum ročníku... zůstavá tam pořád otazník

**Comment by SykoraLukas** [comment]
Uzavřeno omylem nebo schvalne?

**Comment by SmejkalovaAnna** [comment]
Schválně, omlouvám se, chyba byla dána prohlížečem. Teď to už funguje. Tak to ignorujte nebo smažte jestli to jde.
