### ISSUE TITLE
Vylepšení kontroly indexů stran při exportu (jedinečnost, vzestupná řada)

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#840]
Bylo by dobré vylepšit kontrolu indexů stran při validaci v okamžiku exportu. Během zpracování se u každé strany kontroluje samotné vyplnění indexu, ale při exportu by bylo dobré doplnit ještě další kontroly:

- jedinečnosti
- vzestupné řady

V případě, že by dvě či více stran měly shodný index, zahlásilo by to chybu, stejně tak pokud by nebyla dodržena vzestupná řada 1 až ...

(Proč - občas se stane, že chybou zpracovatele je v balíčku stejný index u několika stran, chybu neodchytneme a do Krameria se pak naimportuje jen první ze stran se shodným indexem)

**Comment by SmejkalovaAnna** [comment]
Minulý týden jsme toto taky řešili.... proto to issue s tou změnou indexu, jak jsi se k tomu taky vyjadřovala.... tento návrh jednoznačně podporuji... určitě to chceme taky a brzy :)

**Comment by SykoraLukas** [comment]
V případě chyby při kontrole indexů, export neproběhne (balíček se smaže) a uživateli se zobrazí hláška "Nevalidní kontrola Indexu" + popsána chyba, která nastala

**Comment by krizovj** [comment]
Šlo by to přidat taky do archivního exportu? Pro NDK export to funguje!
