### ISSUE TITLE
3.5.1 - NDK eMonografie - originInfo-dateIssued

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#841]
V elementu originInfo - dateIssued je povinný atribut point. Šlo by z něj udělat MA, i když ve standardu je M? Ono i v tom standardu je uvedeno, že se to vyplňuje jen pokud tam je rozmezí dat, ale mají to nesmyslně označeno jako M. 
Pokud je rok vydání jen jeden (a ne rozmezí dat), tak tam ten atribut prostě není možné uvést. Jedině, že by se uvedlo například start: 1990 a end: 1990 a to je nesmyslné.

**Comment by SmejkalovaAnna** [comment]
To je stejný, jak u NDK Monografií... ty jsi říkala, že jsi jim už dala podnět, ať tu položku ve standardu zruší... vyšlo to už v novým standardu? Resp. kdy vyjde?

**Comment by krizovj** [comment]
Jasný, oni už to u těch tištěných monografií opravili, takže tam už je ve standardu MA :) Ve standardu je to strana 33: https://www.ndk.cz/standardy-digitalizace/dmf_monografie_1-3-2 

Ale v těch elektronických to zůstalo no...

**Comment by SykoraLukas** [comment]
Chcete to tedy opravit u obou monografii? Nebo jen u tištěné ať se držíme standardu?

**Comment by krizovj** [comment]
Ano, u obou monografií. Díky

**Comment by SmejkalovaAnna** [comment]
Bezva díky
