### ISSUE TITLE
3.5.1 - chyba ve validaci - asi jen v označení?

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#846]
Validátor mi vyhodil na Periodiku jen tuto jednu chybu:
checkBibliographicMetadataMatchProfile: záznam MODSMD_TITLE_0001 není validní podle  mods_3.5.xsd: cvc-enumeration-valid: Value '3.6' is not facet-valid with respect to enumeration '[3.5, 3.4, 3.3, 3.2, 3.1, 3.0]'. It must be a value from the enumeration.

**Comment by SykoraLukas** [comment]
Toto je v pořádku. Validátor ještě neumí validovat podle nových standardů a tedy ani podle MODS 3.6. Jakmile bude validátor aktualizován na nové standardy, chyba zmizí

**Comment by SykoraLukas** [comment]
Mohu issue zavřít?
