### ISSUE TITLE
Hlásit chybu, když uživatel zkusí exportovat periodikum, které nemá žádná čísla

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#847]
Když se uživatel pokusí exportovat periodikum, které nemá žádná čísla (stránky jsou přímo pod ročníkem), tak aktuálně export projde jako úspěšný, ale v exportním adresáři pak je pouze log. Toto pak může vést k problémům viz #744. Týká se to jak exportu do PSP, tak archivního exportu.

Žádoucí chování: Při pokusu o export ohlásit uživateli chybu ve stylu: "Pokoušíte se exportovat periodikum, které nemá žádná čísla. Periodika se exportují po číslech, takže není co exportovat."

**Comment by svetlym** [comment]
Hmm, to samé vlastně platí i pro pokus přidělit URN:NBN, což uživatel nejspíš zkusí ještě před exportem (protože bez URN:NBN se nedá exportovat) viz 744.

**Comment by jkremlacek** [comment]
Problém je primárně s připojováním stránek pod špatné objekty (nepovolená vazba, která by vůbec neměla vzniknout).

Řešení https://github.com/proarc/proarc/issues/741 nefunguje v případě, že k připojení stran dochází v rámci importního procesu, bude zapotřebí dodělat tuto variantu.

**Comment by svetlym** [comment]
Souhlasím, že je žádoucí, aby nevalidní vazby vůbec nešlo vytvořit. Uživatel ale každopádně potřebuje vědět, jak má problém vyřešit, i když zrovna potká chybu, která neměla nikdy vzniknout.

**Comment by krizovj** [comment]
Mně to teda vyhodí chybu jen když zkusím vyexportovat NDK balíček, ale ne archivní.

**Comment by nezbedova** [comment]
Mně to hodilo chybu u NDK monografie při pokusu exportovat archive balíček.

**Comment by krizovj** [comment]
Mně to právě pro ten archivní balíček (u NDK monografie) chybu nevyhodilo. Řeklo to, že export proběhne, pak, že proběhl. Nekoukala jsem, jestli skutečně proběhl, ale chybu nevyhodil.
