### ISSUE TITLE
3.5.1 - NDK eMonografie verze MODS

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#849]
V XML se zobrazuje verze MODS 3.6, ale ve standardu je verze 3.5.

**Comment by SykoraLukas** [comment]
Tohle nedokazu vyresit. V proArcu smi byt jen jedna verze MODSu a protože nejnovejsi verze tisknutých dokumentů již implementuje verzi 3.6 musí být i audio dokumenty a eDokumenty ve verzi 3.6 ačkoli ve standardu mají pouze verzi 3.5. 

MODS 3.6 umí nekterá pole navíc oproti 3.5, ale umí všechna pole co jsou ve verzi 3.5.

Šlo by popostrcit standard eDokumentů, aby přešel na verzi 3.6?

**Comment by SykoraLukas** [comment]
Kdyby byl rozdíl v polích, pochopil bych to, takhle nevím.

**Comment by krizovj** [comment]
To je jasný, já to chápu. Spíš nechápu, proč je tam 3.5. Kdybychom potřebovali něco posílat do NK, tak bych se bála, aby na to ten validátor nepřišel. Že jako v této verzi standardu je 3.5, ale my tam nic posílat nebudeme a předpokládám, že by snad nemuselo vadit změnit to na 3.6., tak bych to tak asi nechala. Navíc validátor pro epublikace ještě není...
