### ISSUE TITLE
3.5.1 - NDK svazek eMonografie - URN:NBN

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#850]
Při pokusu o přidělení URN:NBN (podle standardu je povinné) mi to vyhodí neočekávanou chybu :-(
Tady jsou detaily:

[object Object]
Status: -90
Query: { "operationType":"add", "dataSource":"isc_UrnNbnDataSource_0", "data":null, "requestId":"isc_UrnNbnDataSource_0$62753", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "promptStyle":"dialog", "prompt":"Probíhá registrace...", "lastClientEventThreadCode":"TMR4", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "showPrompt":true, "originalData":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_UrnNbnDataSource_0", "data":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] }, "requestId":"isc_UrnNbnDataSource_0$62753", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "promptStyle":"dialog", "prompt":"Probíhá registrace...", "lastClientEventThreadCode":"TMR4", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "showPrompt":true, "originalData":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1542109862771, "useHttpProxy":null, "actionURL":"https://proarc-ozc-test.lib.cas.cz/proarc/rest/v1/object/urnnbn", "params":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ], "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_UrnNbnDataSource_0", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "callback":{ "target":{ "ID":"isc_UrnNbnDataSource_0", "dataFormat":"json", "requestProperties":{ "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "promptStyle":"dialog" }, "fields":[ { "name":"target", "type":"text", "$61":true, "$62":{ "validators":[ { "type":"isString", "typeCastValidator":true, "_generated":true, "$174l":true, "stopIfFalse":true, "defaultErrorMessage":null } ], "name":"text", "$68":true }, "title":"Target", "$76s":true } ], "operationBindings":[ { "operationType":"add", "dataProtocol":"postParams", "requestProperties":{ "httpMethod":"POST" } } ], "dataURL":"https://proarc-ozc-test.lib.cas.cz/proarc/rest/v1/object/urnnbn", "jsonPrefix":"", "jsonSuffix":"", "recordXPath":"/response/data" } }, "_dsRequest":{ "operationType":"add", "dataSource":"isc_UrnNbnDataSource_0", "data":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ], "_operationType":"add", "_textMatchStyle":"exact", "_dataSource":"isc_UrnNbnDataSource_0", "isc_metaDataPrefix":"_", "isc_dataFormat":"json" }, "requestId":"isc_UrnNbnDataSource_0$62753", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "promptStyle":"dialog", "prompt":"Probíhá registrace...", "lastClientEventThreadCode":"TMR4", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "showPrompt":true, "originalData":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] }, "unconvertedDSRequest":{ "operationType":"add", "dataSource":"isc_UrnNbnDataSource_0", "data":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] }, "requestId":"isc_UrnNbnDataSource_0$62753", "$135x":null, "useStrictJSON":null, "$135v":null, "fallbackToEval":false, "textMatchStyle":"exact", "$178g":true, "promptStyle":"dialog", "prompt":"Probíhá registrace...", "lastClientEventThreadCode":"TMR4", "$135w":null, "parentNode":null, "httpMethod":"POST", "useSimpleHttp":true, "httpHeaders":{ "Accept":"application/json", "Accept-Language":"cs" }, "$135u":null, "bypassCache":true, "showPrompt":true, "originalData":{ "pid":[ "uuid:bbf6f14b-b685-46a1-a815-9c81d0bbc819" ] } }, "dataProtocol":"postParams", "isRestRequest":true, "dataFormat":"json", "$85o":1542109862771, "useHttpProxy":null }, "transport":"xmlHttpRequest", "serverOutputAsString":true, "suppressAutoDraw":true, "$185x":"https://proarc-ozc-test.lib.cas.cz/proarc/rest/v1/object/urnnbn", "promptCursor":"progress", "useCursorTracker":false, "cursorTrackerConstructor":"Img", "cursorTrackerProperties":{ "src":"[SKINIMG]shared/progressCursorTracker.gif", "size":16, "offsetX":12, "offsetY":0 }, "operation":{ "ID":"custom", "type":"rpc" }, "showedPrompt":true, "transactionNum":55 }

**Comment by SykoraLukas** [comment]
Mohl bych poprosit o log z tomcatu? Z tohoto neni poznat kde je chyba

**Comment by PetrKotynek** [comment]
Posílám logy:
[logy.zip](https://github.com/proarc/proarc/files/2594130/logy.zip)
Petr Kotýnek

**Comment by krizovj** [comment]
Tak mi to udělá i při pokusu přidělit URN:NBN číslu (NDK eČíslo), jak na úrovni čísla, tak na úrovni celého periodika (NDK ePeriodikum).

**Comment by krizovj** [comment]
Mám jen dotaz, musí se u té nové verze něco změnit v konfiguraci, aby to přidělování URN:NBN fungovalo? Ptž nám to pořád nefunguje (3.5.3). Díky

**Comment by PetrKotynek** [comment]
# A name of the subject that owns the package. The sigla recommended.
export.ndk.agent.archivist=ABA007
export.ndk.deletePackageIfUrnNbnIsMissing=true

**Comment by krizovj** [comment]
Aha, takže to chce vyplnit někam siglu, aby mi to dalo URN:NBN? V tomhle standardu totiž není, kam tu siglu vyplnit. Je jenom v informacích o vlastníkovi záznamu. Do standardu to nechtěli původně dávat, ptž jde o elektronický dokument, ale v příští verzi by se to mělo doplnit.
https://github.com/NLCR/Standard_NDK/issues/70

**Comment by luckajirku** [comment]
Možná se pletu, ale nešlo v tomhle případě o to, že je třeba přidat do cfg do nastavení urn:nbn ty e-modely?

**Comment by krizovj** [comment]
Jo, já vím, že se někam mají přidat ty modely, ale chtělo by to nějak popsat. Pokud se má změnit konfigurace, tak by to chtělo napsat k té nové verzi, co se tam má přesně přidat a co to udělá.

**Comment by SykoraLukas** [comment]
Modely jsem musel přidat já v serverové konfiguraci URN:NBN resolveru, s tím vy nic nědlat nesmíte. Pan @PetrKotynek mi poslal konfigurák a v něm je chyba. 
,,
## URN:NBN resolvers
# Comma separated list of resolver profiles.
#urnnbn.resolvers=knav-test

# KNAV Test Resolver
urnnbn.resolver.knav-test.registrar=aba007

#urnnbn.resolver.knav-test.archiver=?
urnnbn.resolver.knav-test.title=KNAV Test
urnnbn.resolver.knav-test.url=https://resolver-test.nkp.cz/api/v3
urnnbn.resolver.knav-test.user=KNAV_test
urnnbn.resolver.knav-test.passwd=uogK7xh
,,

prosím v řádku **#urnnbn.resolvers=knav-test** odmažte hash (zakomentování)
