### ISSUE TITLE
3.5.1 - NDK svazek eMonografie - element location

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#851]
Při stahování z katalogu mi to v XML vyrobí element location-physicalLocation s hodnotou sigly knihovny. Ve standardu tenhle element pro elektronickou monografii vůbec není, ptž se nepočítá s tím, že to jako někde fyzicky je. 
Pokud vyplňuji záznam ručně, tak se tam ten element nevyrobí. 
Šlo by ho tam při stahování záznamu z katalogu nedávat?

**Comment by SykoraLukas** [comment]
On se tam přidává defaultně kvuli šabloně, ale dá se nastavit, že v případě eDokumentů se odmaže. Může to být takto?

**Comment by luckajirku** [comment]
No já nevím. Neměl by standard být v souladu s katalogizačními pravidly? I podle minimálního (natož doporučeného) záznamu ty údaje z 910 jsou v záznamu povinné https://www.nkp.cz/o-knihovne/odborne-cinnosti/zpracovani-fondu/katalogizacni-politika/minimalni-zaznam-rda-marc-21-pro-specialni-monograficke-zdroje - a zrovna vlastník je docela podstatný údaj, ne?

**Comment by krizovj** [comment]
No, vlastník asi je důležitý, ale možná by měl být v případě těch elektronických publikací jinde, než v elementu "physicalLocation", když "fyzicky" ten dokument nikde vlastně není...

**Comment by luckajirku** [comment]
Jak to, že není? Jestli je někde na serveru, nebo na polici, je v podstatě jedno, ne?

**Comment by krizovj** [comment]
No, to je taky pravda, v tom standardu to ale bohužel není. Zatím to teda asi necháme a pokusíme se to do standardu přidat.

**Comment by luckajirku** [comment]
Jde pak taky o to, jak s tímhle údajem pracuje systém při zpřístupnění... Když to budeš mít ve vlastní DK, kde budeš mít jen svoje věci, tak OK - ale jakmile to bude jinde - místo uložení bude prázdné... Co třeba u těch věcí, co nepustíš veřejně - asi by měl uživatel vidět, kde se na to může podívat na místě... Prostě než něco zavedeme/zrušíme, popřemýšlejme o tom:-)

**Comment by krizovj** [comment]
No jo...čdk. Dík za upozornění! :)

**Comment by SykoraLukas** [comment]
Mám tedy tento údaj nechat (a budeme uvádět o údaj více, než vyžaduje standard) nebo ho smazat (a jet podle standardu)?

**Comment by krizovj** [comment]
Zatím nechat, prosím. Pardon za issue, nedošly mi ty okolnosti...
