### ISSUE TITLE
3.5.1 - NDK ePeriodikum - Neplatná data - Issuance

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#855]
Ve formuláři pro NDK ePeriodikum mi při uložení vyskočí chyba: "Neplatná data".
Postup:

1. Stáhnu záznam z katalogu. 
2. Uložím
3. Vyskočí chyba "Neplatná data" a chce po mně vyplnit pole "Issuance" a "Digital origin" v OriginInfo. 
4. Vyplním Digital origin a Issuance a uložím. 
5. Uloží se
6. Udělám/doplním/smažu/změním cokoliv a kdekoliv ve formuláři
7. Uložím
8. Vyskočí chyba "Neplatná data" a chce po mně znovu vyplnit pole "Issuance", ptž je najednou zase prázdné.

**Comment by krizovj** [comment]
S tím souvisí ještě další věc. Šlo by, aby se hodnota "born digital" v poli Digital origin předvyplňovala u všech NDK e formulářů, kde to tohle pole chce? Takže všude kromě ročníku.

**Comment by SykoraLukas** [comment]
Mohl bych poprosit o id zaznamu abych to mohl vyzkouset primo pro dany zaznam? Dekuji
