### ISSUE TITLE
3.5.1 - NDK eČlánek - relatedItem

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#859]
Šlo by z elementu relatedItem vyhodit element "part"? U eČlánku jsme tam (blbě) zapisovali rozsah článku v čísle, ale to se má správně zapisovat do elementu "part", který je mimo relatedItem. V relatedItem mě teď nenapadá, na co bychom "part" potřebovali.
![part](https://user-images.githubusercontent.com/21309201/48764256-728bda00-ecaf-11e8-8a65-886b10a8d8d2.jpg)

Spíš by se tam místo "part" hodilo přidat pole "partNumber" a "identifier". 
Šlo by, aby se do titleInfo v elementu "RelatedItem" stáhnul název časopisu a ISSN z úrovně titulu a číslo (partNumber) a uuid (identifier, type=uuid) čísla z úrovně čísla? Ve standardu je doporučeno dávat u článků do relatedItem údaje o čísle, ve kterém ten článek je. 
Jinak bych v relatedItem u NDK eČlánku nechala všechno tak, jak to je.

**Comment by SykoraLukas** [comment]
Název, ISSN, NamePart kopírujeme z titulu periodika, PartNumber a UUID se kopíruje z čísla periodika. Je to tak v pořídku?

Formulář je opraven

**Comment by krizovj** [comment]
Jasně, díky.
