### ISSUE TITLE
RDflow - Test v. Verze: 3.5.1 - chybová hláška a změna údajů

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#866]
V obrazovce Workflow - Nový záměr - si vyhledám záznam. Při vyplnění metadat titulu přidám podtitul, signaturu a čárový kod. Nebo změním něco ve staženém formuláři. Po kliknutí na uložit a překonání chyb (začátek vydávání, který je povinný u periodik) naskočí chybová hláška: 
![obrazek](https://user-images.githubusercontent.com/13831946/49286986-1e95a800-f49c-11e8-9623-2276b4596f7c.png)
Dám OK. Záměr se založí, ale v xml není to, co jsem doplnila ani změnila.
Když nic nedoplňuji ani neopravuji hláška se neobjeví.
Po vyplnění prázdného formuláře se hláška objeví. Uloží se prázdný formulář.

**Comment by nezbedova** [comment]
Pokud výše uvedené úpravy udělám při Vytváření nového objektu (kliknutím v RDflow), tak zůstanou vyplněné/změněné.

**Comment by nezbedova** [comment]
Ve v. 3.5.3 nelze při zakládání nového záměru stažením cokoli měnit nebo dopsat.

**Comment by nezbedova** [comment]
v. 3. 5.7 - chyba je odstraněna

**Comment by nezbedova** [comment]
v. 3. 5. 9 chyba se opět objevila

**Comment by SykoraLukas** [comment]
Funkční v 3.5.10
