### ISSUE TITLE
RDflow - Možnost založení nového záměru stažením z RD

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#867]
V obrazovce "Nový záměr" do rozbalovátka "Pole" přidat možnost "Stav" a umožnit stahování z Registru digitalizace záznamy, u kterých je stav "Plánováno".
Pak by se mohl vybrat titul, který je v RD nový. Po dohodě a upravách v Alephu - mám předjednáno.

**Comment by pavelkocourek** [comment]
Bude řešeno v 2. pol 2019

**Comment by nezbedova** [comment]
Stále čeká na NK

**Comment by ZdenkaSera** [comment]
@nezbedova Martino, tady jsem vzhledem k posunu v čase a verzích změnila název issue.

**Comment by ZdenkaSera** [comment]
K tomuto issue doplníme požadavky v souvislosti s předběžně plánovanou červnovou schůzku k RDFlow. Plánovaný způsob využívání registru digitalizace prochází v KNAV revizí.

**Comment by SykoraLukas** [comment]
Zavírám před schůzkou na základě labelu.
