### ISSUE TITLE
Kontrola URN NBN pro Export Archive

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#868]
Prosím o vylepšení Exportu Archive balíků - při volbě exportu Archive by se PA zeptal: Máte přidělené URN:NBN? Chcete pokračovat?  Ano - Ne.

**Comment by nezbedova** [comment]
Navrhuji začlenit to jako povinnost jako tomu je u NDK. Bez přiděleného URN:NBN by export neproběhl.

**Comment by luckajirku** [comment]
Tady nemá být na výběr, prostě exportuju archivační balíček s NDK exportem, tak musí mít všechny náležitosti NDK.

**Comment by pavelkocourek** [comment]
Jde jen o doplnení hlášky, rozhodnu pracovník
