### ISSUE TITLE
RDflow - přepis informací z metadat do tabulky Biblio. info

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#869]
Ve "Správa záměrů" v části Materiál - Bibliografický záznam je v Metadatech v xml zapsána signatura a čárový kod. Tyto údaje jsem doplnila ručně při zakládání nového záměru. Potřebujeme, aby se tyto dva údaje zobrazily v tabulce nad metadaty, kde jsou pro ně připravená pole. A hodilo by se to i u pole Rok. 
(Jedná se o NDk monografii, periodika jsem ještě nezkoušela.)
V test v. 3.5.2 se nezobrazují a když si je tam znovu ručně doplním a dám "Uložit", tak zmizí. 
Dříve to nějak jít muselo, protože u pokusu ze dne 28.03.2017 mám signaturu zapsanou.
Tyto identifikátory jsou pro nás velmi důležité. Bez nich se dost špatně hledá.

**Comment by SykoraLukas** [comment]
Opravené

**Comment by nezbedova** [comment]
Signatura se propíše, ale čárový kód ne.

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 28.1. .. pokračuje #1077

**Comment by pavelkocourek** [comment]
Zavřeno na schůzce 28.1. .. pokračuje #1077
