### ISSUE TITLE
RDflow - automatizace exportů v test v. 3.5.2

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#871]
V rámci automatizace by se po proběhnutí Exportu pro Kramerius, NDK PSP a archivace měl v RDflow dokončit příslušný úkol.
Nevím, zda se to má nějak opravit/připravit v xml.

**Comment by nezbedova** [comment]
Na nově založeném záměru se po K4 exportu neobjeví nic.  (Ostatní exporty nefungují viz issue #1106)

Má se nějak opravit xml?

**Comment by SykoraLukas** [comment]
Prosím o screen obrazovky z úkolem k4 export a o zaslání workflow.xml

**Comment by nezbedova** [comment]
![obrazek](https://user-images.githubusercontent.com/13831946/74219703-dd0ea880-4cad-11ea-998f-82af5dbef47c.png)

**Comment by nezbedova** [comment]
U mě to stále nefunguje. Slíbíl jste mi nové xml. Prosím o jeho zaslání.

**Comment by nezbedova** [comment]
Nahrála jsem Vaše xml. Ale Export pro Krameria se automaticky neuložil.

**Comment by nezbedova** [comment]
ProArcVerze: 3.5.18
--
Funguje. Zavírám.
