### ISSUE TITLE
Testovací server

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#873]
Nainstalovat a zpřístupnit Testovací server pro uživatele,

**Comment by SykoraLukas** [comment]
Vytvořit účty pro nové uživatele: zástpce Hradce Králové (@luckajirku), zástpce KNAV (@nezbedova, @krizovj, @tumovam, @MLhotak), zástupce MZK (René Hlaváček), zástupce Jihlavy (Martin Musil), @pavelkocourek

**Comment by krizovj** [comment]
Vyřeší se možností přihlásit se do testovacího ProArcu KNAV.
