### ISSUE TITLE
EPublikace - export (v. 3.5.3)

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#877]
U epublikací (jak periodika, tak monografie), je pořád původní SIP balíček. V NDK standardu původně byly jak SIP, tak AIP. Pak se přišlo na to, že ten SIP by měl vlastně vypadat jako popsaný AIP a AIP by tam nemusel vůbec být. 
Takže teď je ve standardu jen SIP (dříve AIP) a v exportu z ProArcu je něco, co ve standardu vůbec není. 

Export obsahuje vlastně MODS + PDF + info xml, chybí MD5, celý METS, technická metadata,...

**Comment by pavelkocourek** [comment]
29.4. KNAV - bude aktualizován export po vydání standardu NK
