### ISSUE TITLE
mazani uzivatelskych uctu ProArc

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#878]
Zdravím,
máme od uživatelské obce požadavek na smazání "neaktivních" účtů.  Může mít případné smazání příslušných řádků v  tabulce proarc_users v databázi proarc nějaký neblahý ( destruktivní ) vliv na cokoli ? 
Popřípadě jak správně "deaktivovat"  uživatelský účet.
Petr Kotýnek

**Comment by jkremlacek** [comment]
Souvisí s https://github.com/proarc/proarc/issues/531

Vymazat uživatele z tabulky proarc_users nestačí, protože uživatel je vytvořen i do Fedory ProArc-u (group:_username_ a user:_username_) a odkazuje na záznam také tabulka proarc_group_members.

UI i po manuálním vymazání uživatele funguje (ve smyslu že se načte a fungují základní operace, negarantuji korektní fungování netriviálních funkcionalit), nicméně může dojít ke spoustě neočekávaných chyb po delší době (napadá mě například problém při řešení dávek, které smazaný uživatel vlastnil, nebo znovuvytváření uživatele s daným jménem).

Za mě manuální zásah do back-endu za účelem smazání uživatele znamená příliš velká rizika. Pokud je tato funkcionalita pro něco nutná, pak by měl být vznesen požadavek do vývojového týmu.

**Comment by PetrKotynek** [comment]
Děkuji, 
zatím tam tedy změním hesla a účty nechám být.   
Petr Kotýnek
