### ISSUE TITLE
RDflow -  nevygeneruje uuid

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#879]
Při tvorbě nového záměru se u STT ani v prázdném formuláři, ani po stažení údajů z RD nevygeneruje uuid. U NDK Monografií to funguje.

[RDflow_test_2018_18.txt](https://github.com/proarc/proarc/files/2754293/RDflow_test_2018_18.txt)

**Comment by nezbedova** [comment]
Při zakládání záměru se uuid nevygeneruje.  Vygeneruje se až když se ze záměru vytvoří nový objekt.
Možná to tak má být.
U NDK monografií to je stejné.

**Comment by nezbedova** [comment]
Přetrvává i v ve v.3.5.5

**Comment by pavelkocourek** [comment]
20.3 schuzka
