### ISSUE TITLE
RDflow - STT zobrazuje se staré xml

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#880]
Po založení záměru Staré tisky se zobrazí úkoly, které tam byly dříve, nikoli ty z nového xml. A ještě přeházené.

![obrazek](https://user-images.githubusercontent.com/13831946/51100993-f7d7ca80-17d8-11e9-9e8d-dd122b3a8afc.png)
![obrazek](https://user-images.githubusercontent.com/13831946/51101076-6026ac00-17d9-11e9-903b-19a00ac3253d.png)

**Comment by pavelkocourek** [comment]
MN přejmenuje položku. 
Schůzka 13.5.2019

**Comment by nezbedova** [comment]
Opraveno.
