### ISSUE TITLE
Vylepšení - nabídka Typu stran

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#881]
Při rozbalení nabídky typů stran by bylo praktické, kdyby se zobrazily jen ty nejčastěji používané strany ( podle četnosti užívání přihlášeného uživatele ) - např. jen 8 nejčastěji používaných, a pod tím to omezeným seznamem by byla možnost rozbalení ostatních typů...... co myslíte?

**Comment by SykoraLukas** [comment]
Toto není možné v současné verzi udělat, ale je to možné udělat v nové verzi klienta.

**Comment by SmejkalovaAnna** [comment]
Fajn, díky, tak se budem těšit na nového klienta :)

**Comment by pavelkocourek** [comment]
Přesunuto : Vylepšení - nabídka Typu stran (#881) #21
