### ISSUE TITLE
PA 3.5.3 - Validator - "amd_mets_aba007-00006i_0009.xml: Chybí odkaz"

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#882]
Vaildátor mi hlásí v Technických metadatech: amd_mets_aba007-00006i_0009.xml: Chybí odkaz (relatedObject) z ALTO (ID=OBJ_003) na archivní kopii (ID=OBJ_002). 
Postupovala jsem takto: vytvořila jsem novou NDK Monografii stažením záznamu z katalogu KNAV a ve vazbách pod ní přesunula pár stran z jiné knížky ( kterou jsme tam předtím naimportovali z Archive balíku ), dále jsem pak u některých nastavila jiný typ strany. Přidělila URN:NBN a vyexportovala NDK a zvalidovala....

**Comment by SykoraLukas** [comment]
Toto bylo již probíráno na vývojové schůzce. Jde o stejnou chybu, jako je v případě validace vzorových balíčků z NDK. 

Bohužel nevím, jak tuto chybu odstranit.

**Comment by SmejkalovaAnna** [comment]
Aha, nebyla jsem si právě jistá, jestli je to to samé. Díky a issue zavírám.

**Comment by krizovj** [comment]
Otvírám, tu chybu to pořád hází. 
Vypadá to, že u nás se z ALTO (OBJ_003) odkazuje na Původní sken (OBJ_001), ale má se odkazovat na MC (OBJ_002). 
Zkoušela jsem dnes dát do validátoru (2.1) vzorový archivační balíček z NDK (https://owncloud.cesnet.cz/index.php/s/ry40SG2DhB5yMgK/download) a sice mi ho validátor vyhodil jako nevalidní, ale zrovna tahle chyba tam nebyla...
