### ISSUE TITLE
Šablona MARC/MODS - nepřevádí se údaje ze 700 s 1. ind. 0

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#884]
Je třeba opravit šablonu MARC/MODS, aby se převedly i údaje z pole 700 s 1. indikátorem 0. Teď se to při konverzi zahodí a přicházíme o autoritu. V šabloně LoC ta chyba byla opravena už v červnu 2018 (Revision 1.119 - Fixed 700 ind1=0 to transform - tmee 2018/06/21)

**Comment by SykoraLukas** [comment]
Opraveno
