### ISSUE TITLE
Možnost zamknout dokončený záznam

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc#887]
Zamčení v aplikaci stopne možnost editace omylem - návrh LJ schůzka 17.1. Prosím rozepsat.

**Comment by luckajirku** [comment]
Tohle bude do značné míry souviset se správou uživatelů a lépe řešenými právy, takže dokud nebude hotová správa, tak se o tom můžeme bavit, ale nedá se to rozepsat, když nevím, jaké budou potom možnosti. Takže netuším, proč mi bylo issue založeno:-).

**Comment by luckajirku** [comment]
@SykoraLukas - než rozepíšeme, jak by se to mělo chovat, potřebovala bych prosím tě vědět, jak to je z pohledu správy uživatelů. Musí být ta práva zamykat záznam/objekt a právo odemykat/dělat změny v zamčeném vázaná na roli uživatele (tzn. bude to moci dělat jen admin/superadmin, popř. jiná vybraná kategorie), nebo to půjde přidělit i konkrétnímu uživateli bez ohledu na roli?

**Comment by SykoraLukas** [comment]
Buďto to můžeme navázat na roli admin/superadmin (ale to si myslím, ze není vyhovující). Spíš se můžou udělat 3 nové vlastnosti (uzamknout, odemknout, editovat zamčený). Tyto role by se mohly nastavit pro jakékoli uživatele. Někdo by mohl jen zamykat, někdo jiný třeba odemykat a někdo by mohl mít ještě upravit. A pak samozřejmě jakákoli kombinace těchto tří rolí.

**Comment by luckajirku** [comment]
Jj, to zní dobře. 

Co se týká třeba periodik - dalo by ses zamykat počítám na různých úrovních - mám velké zatím nekompletní periodikum, kde chci ochránit už hotové zkontrolované ročníky - tak je zamknu, ale titul bude zatím otevřený a další ročníky přidávat/editovat půjdou.

Pak ještě přemýšlím - kromě manuálního zamykání by nebylo od věci mít i možnost automatického zamykání - jak moc by tohle mohlo být konfigurovatelné v té konkrétní instalaci? Dovedu si představit, že bychom měli nastavené automatické zamčení po kontrole nebo NDK exportu*, jiná knihovna by to mohla chtít jinak. A jak s propojením na RDflow? Počítám, že pro ty, co používají RDflow by to bylo lepší navázat na dokončený úkol v rdf... 
*jo, tohle je další věc - půjde zamčený objekt exportovat? Nebo to systém bere jako editaci?

**Comment by SykoraLukas** [comment]
Moje představ byla, že by se zamkla editace metadat, administratiních metadat a vazby objektů. I po zamčené by šlo editovat uživatelský komentář a možnost spouštět jakýkoli export. 

Automatického zamčení je otázkou, muselo by se říct, kdy se to má automaticky zamykat, případně vymyslet několik bodů, kde to zamykat a pak by to šlo dělat konfigurovatelné.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím o opravu překlepu v dialogu chyby ("zrušena"):

![image](https://user-images.githubusercontent.com/79305516/168083785-cbcf3d41-b17b-415d-9674-701f89848185.png)

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Testovala jsem to už před časem, nenašla jsem problém. Ale prosím o přetestování z Vašeho pohledu + pro STT, periodikum a objekt s RDF. Děkuji.

**Comment by ZdenkaSera** [comment]
Testováno v klientovi jako ok, s RDF zatím netestujeme, dávám návrh na uzavření. @nezbedova

**Comment by SykoraLukas** [comment]
Uzavřeno na základě labelu během schůzky 17.6.2022.
