### ISSUE TITLE
Test v3.5.4 - nejde načíst k4 export - návod

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#895]
Prosím o instrukce, jak na Zpětný import K4 exportů.
Pokud vezmu K4 export a chci postupovat jako u archive, tak mi to nejde.

**Comment by nezbedova** [comment]
K4 export jde načíst pouze když je vyplněný druh skeneru. Prosím zrušit tuto podmínku.
V rozbalovátku je "Kramerius" 3x, myslím si, že nám stačí jeden řádek.

**Comment by SykoraLukas** [comment]
Podmínku zrušit můžu, ale poté nastává problém při exportu. 

Jestliže z toho budete chtít vytvořit NDK balíček, balíček se vyexportuje, ale validátor bude hlásit chybu, neboť bude chybět element:mix k záznamu.

**Comment by SykoraLukas** [comment]
Pro zprovoznění importu balička Kramerius je nutné nejprve nakonfigurovat soubor proarc.cfg. Poté se mezi možnými profily, pod kterými chcete importovat objeví profil Kramerius (záleží, jak ho nazvete).

Vyberete profil a je nutné doplnit i skener.
Kramerius export jde dělat jen u balíčků, které obsahují soubory s příponou xml.

Poté vše probíhá stejně jako u Archive importu.

**Comment by krizovj** [comment]
Pardon za založení toho duplicitního issue, založila jsem ho ptž to bylo pro verzi 3.5.5 a tohle issue je pro tu starší, ale pokud se v tom dá vyznat tak v pohodě. 

Pořád se nám nedaří najít v ProArcu ten naimportovaný balíček. Dělali jsme to přesně, jak píšeš, ale není tam, no.
Ptala jsem se pana Kotýnka a psal, že to není ani nikde ve Fedoře, tak nevím. Paní Nezbedová tam zkoušela myslím importovat K4export z ProArcu a ten to zřejmě vzalo dobře, ale tohle byl export z Krameria a ten tam není.

**Comment by SykoraLukas** [comment]
Mohla bys mi prosím poslat tento balíček, který se snažíš naimportovat? Kouknu na nej co je jinak od toho vzorového co mám.

**Comment by krizovj** [comment]
Právě jsem ti to poslala na mail přes FileSender. Je to ročník časopisu.

**Comment by PetrKotynek** [comment]
pripojuji nějaké logy kde jsem naše 486d8302-b934-11e1-2544-001143e3f55c
[895_logy.zip](https://github.com/proarc/proarc/files/2914778/895_logy.zip)
Petr

**Comment by SykoraLukas** [comment]
Děkuji za soubory. Zjistil jsem, že se data nenačnou kvuli nadbytečnému elementu v XSI:SCHEMALOCATION v DC datastreamu. Pracuji na opravě

**Comment by SykoraLukas** [comment]
@krizovj podarilo se mi nahrat vse do mého ProArcu. Problém však je v systému, který data vytváří. Nezapisuje v něm jednotlivé vazby, jen pod jaké periodikum daný objekt patří. (Vazby na ročník a číslo) zde nejsou žádné. 

Zkouším vymyslet nějaký postup, jak nasimulovat správné propojení s nadřazeným objektem. Mám zatím vydat verzi s importem, aniž bude obsahovat  propojení objekt a nadřazený objekt (ty by se pak museli udělat ručně v editoru nadřazených objektů).

**Comment by krizovj** [comment]
Teď se jen ujišťuju, že jsem to pochopila správně :)

Takže když prostě naimportuju do ProArcu třeba jeden ročník časopisu, který má dejme tomu 8 čísel, tak v ProArcu to bude vypadat jak? 

Bude záznam časopisu a pod ním budou na stejné úrovni záznamy toho ročníku a těch 8 čísel? A pod těmi čísly budou ty stránky, nebo ty stránky budou na úrovni těch čísel a ročníku? 

Takže jako takhle:
![import](https://user-images.githubusercontent.com/21309201/53713985-13606880-3e4d-11e9-9056-a270f4326c11.jpg)

nebo takhle?
![import1](https://user-images.githubusercontent.com/21309201/53713991-19eee000-3e4d-11e9-9cc9-1edcd1f9f989.jpg)

**Comment by psenickam** [comment]
Zeptam se asi bllbe, ale mam za to ze Kramerius neexportuje nadrazene urovne objektu a musi se stejne rucne doplnovat? Nevyresila by toto spis uprava Krameriovych exportu? Pokud se pletu tak se omlouvam za dotaz mimo. Nicmene Vami navrhovana uprava, a to ze  importuji a pak zalozim nadrazene urovne a ve vazbach priradim, je rovnez ve hre. A to pokud mam data na urovni napr. rocniku, vytisku (bez nadrazene urovne) jiz nekde na ulozisti vyexportovana, pripadne prevzata z jine instituce.

**Comment by SykoraLukas** [comment]
Jak píšete, Kramerius neexportuje tu hlavní úroveň, jen na ní uvádí odkaz před uuid. Proto ve chvíli, kdy chcete importovat data (pro příklad uvedu periodikum) se naimportují jednotlivé urovne krome peridika (naimportuje se rocnik, cislo a strany). Nic z toho vsak není propojeno, kazdý uvadí pouze odkaz na periodikum. 

Možnost změnit export z krameria by byla idealni, ale nabizi se otazka, co je na tento export napojeno a jak by to ovlivnilo připadnou funkčnost napojených aplikací na Krameius export.

**Comment by krizovj** [comment]
Dobře, může se vydat verze, kde to bude fungovat jen takhle napůl bez těch vazeb. Vyzkoušíme to, jestli je to použitelné alespoň takhle částečně. 
Ale v té verzi by určitě mělo být opravené tohle issue: https://github.com/proarc/proarc/issues/906 -objevilo se ve verzi 3.5.5 a takhle je to pro nás nepoužitelné

Jinak tohle issue prosím nezavírat, dokud to nebude hotové i s těmi vazbami. Díky
