### ISSUE TITLE
Test v3.5.4 změna konfigurace?

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#896]
Je potřeba něco pro novou verzi měnit v konfiguračním souboru, aby tam fungovaly věci, které mají (např. ten K4 import). Díky

**Comment by SykoraLukas** [comment]
Pro Import Krameria je nutné změnit [konfiguraci](https://github.com/proarc/proarc/wiki/Konfigurace#kramerius-reimport).

Pro URN:NBN není potřeba nic konfigurovat.
