### ISSUE TITLE
příloha periodika: chyba v div type "SUPPL" / má být "SUPPLEMENT"

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#899]
Při marné snaze naimportovat do Krameria periodikum s přílohou jsme narazili na to, že je v ProArcu zřejmě  špatně nastavený mets div type pro přílohu - je tam TYPE="SUPPL" místo TYPE="SUPPLEMENT".

**Comment by luckajirku** [comment]
Tak ne zřejmě, ale určitě:-). Ta chyba se tam musela zanést v některé z verzí v posledním roce, ve starších balíčcích je SUPPLEMENT.

**Comment by krizovj** [comment]
Tak jsem na to koukala a určitě jsme o tom někde mluvili, ptž ono je v NDK standardu v elementu "mods" uvedeno "SUPPL" (změnilo se to mezi verzí 1.3 a 1.4 z původního SUPPLEMENT), ale ProArc donedávna psal "SUPPLEMENT". Validátor to házel jako upozornění (žlutá chyba). Tak  se to změnilo na SUPPL jako je to v NDK standardu. Ale právě v tom elementu div type je ve standardu pořád "SUPPLEMENT". Nemůže to tedy být tím? Že se to nespojí s tím MODSem, ptž u toho MODS záznamu je "SUPPL" a u toho divtype je "SUPPLEMENT"?

**Comment by luckajirku** [comment]
To asi musí řict @SykoraLukas , jak je to propojené. Každopádně periodika s přílohami potřebujeme dostat do Krameria:-)

**Comment by SykoraLukas** [comment]
Ano je to propojené, při úpravě standardu, jsem měnil SUPPLEMENT na SUPPL a nevšiml jsem si, že v divu zůstala původní hodnota. 

Tato chyba se týká také Přílohy Ndk Monografie.

**Comment by krizovj** [comment]
Tak já to zadám na GitHub NDK, aby si to tam opravili, ve standardu je totiž v tom div type taky SUPPLEMENT:

![image](https://user-images.githubusercontent.com/21309201/52931113-78936480-334b-11e9-8981-fd86ac1e147e.png)

**Comment by luckajirku** [comment]
Zkusili jsme po té opravě periodikum nově vyexportovat a naimportovat do Krameria, postoupili jsme o krok dál, že import proběhne:-), příloha ve struktuře se ukáže, ale - její stránky se nezobrazují. např. tady: http://kramerius4.svkhk.cz/search/handle/uuid:32eefa05-db81-4bc5-bb9c-4a42f6ad18c9
@SykoraLukas můžeš to prosím prověřit, kde je chyba? Jestli takhle z ProArcu je to skutečně OK? Zkoušel někdo před releasem, jestli skutečně po novu vyexportovaný balíček jde naimportovat a je vidět v Krameriovi?

**Comment by luckajirku** [comment]
Znovu otevírám, tohle bychom potřebovali dořešit.

**Comment by JanHouserek** [comment]
Jak to vypadá s tímto issue? Vidím, že je ještě otevřené. Do Kram. jsem importoval NDK monografii se dvěma NDK přílohami. Když jsem nahradil SUPPL za SUPPLEMENT, tak se mi strany zobrazují, přičemž ve [starém rozhraní](http://kramerius.kr-olomoucky.cz/search/handle/uuid:6f9b227f-0638-4310-9479-8adf18f4597a) se mi zobrazí obě přílohy, v [novém klientovi v digitalniknihovne cz](http://www.digitalniknihovna.cz/vkol/uuid/uuid:6f9b227f-0638-4310-9479-8adf18f4597a) jen ta první. ProArc máme verzi 3.5.7 (nejnovější budeme zkoušet asi příští týden).

**Comment by krizovj** [comment]
Klient má s dvěma přílohami problém, ale už jsou na to založená issue: https://github.com/ceskaexpedice/kramerius-web-client/issues/177
