### ISSUE TITLE
Test v. 3.5.4 - subject / name

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#903]
Všude, kde je element subject by měl element "name" v elementu "subject" vypadat jinak. My tam teď máme jen "Namepart", ale má to vypadat stejně jako element "name" pro původce dokumentu.

Tedy stejné atributy a struktury, name, atribut type (family, given, date,…), atd. Ptž takhle tady bude to jméno vypadat jinak, než třeba u name, tam bude rozděleno na jméno a příjmení a datum a tady bude všechno v jednom řádku, navíc, kam dám datum? 

Ve standardu je to jen napsané: „Struktura a atributy stejné jako pro údaje o původcích – viz element <name>“ – ale nerozepsané

**Comment by krizovj** [comment]
Platí i pro v. 3.5.5

**Comment by SykoraLukas** [comment]
Ve všech modelech kde je subject
