### ISSUE TITLE
Test 3.5.5 import dat z Krameria

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#905]
Mám dotaz, jak to má přesně fungovat? 
Dělá se to přes normální import? předpokládám, že ano. 
Jaký je prosím přesný postup, aby to správně fungovalo?
Zkusili jsme tam něco naimportovat a teď to tam nemůžeme najít.

**Comment by SykoraLukas** [comment]
Pro zprovoznění importu balička Kramerius je nutné nejprve nakonfigurovat soubor proarc.cfg. Poté se mezi možnými profily, pod kterými chcete importovat objeví profil Kramerius (záleží, jak ho nazvete).

Vyberete profil a je nutné doplnit i skener.

Kramerius export jde dělat jen u balíčků, které obsahují soubory s příponou xml.

Poté vše probíhá stejně jako u Archive importu.

**Comment by SykoraLukas** [comment]
Duplicitní s #895
