### ISSUE TITLE
Test 3.5.5 eČlánek údaj o recenzování

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#906]
Při stažení článku z katalogu se automaticky vybere hodnota "recenzovaný článek", což je špatně, potřebovali bychom to přesně opačně, ptž nerecenzovaných článků je více než těch recenzovaných. U záznamů stažených z katalogu to nejde přepnout na "nerecenzovaný článek". Když to přepnu na "nerecenzovaný", tak se to v XML neprojeví.

Další problém, který s tím zjevně souvisí je, že se do pole genre /type vyplňuje hodnota "peer-reviewed", což je nesmysl. 
Vypadá to takhle:
![recenzovani](https://user-images.githubusercontent.com/21309201/53473340-737c9680-3a6a-11e9-819e-ba4ff618124d.jpg)
Ve složitém formuláři to jde teoreticky dát pryč, ale ve zjednodušeném ne:
![recenzovanizjednoduseny](https://user-images.githubusercontent.com/21309201/53473366-85f6d000-3a6a-11e9-9d9a-40cc72b08fea.jpg)

Takhle to vypadá v našem ostrém ProArcu, který aktuálně používáme (v. 3.4.1):
![recenzovaniakt](https://user-images.githubusercontent.com/21309201/53473657-4086d280-3a6b-11e9-9645-f4252c88e355.jpg)

Takže bychom potřebovali, aby to fungovalo jako v té verzi 3.4.1. Takže:
1. stáhnu záznam článku z katalogu
2. ve formuláři je přepínátko nastaveno defaultně na "nerecenzovaný článek"
3. atribut "type" u polí genre je prázdný

**Comment by SykoraLukas** [comment]
Opraveno a otestováno dle záznamu z [katalogu KNAV Monografie](https://vufind.lib.cas.cz/ustav/KNAV/Record/002070804#holdings)
