### ISSUE TITLE
Doplnění dokumnetace - archivace

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#907]
Na: https://github.com/proarc/proarc/wiki/Archivace
je uvedený popis archive balíčku, ale chybí dokumentace (návod) co vše je potřeba nastavit. 
@MartinRumanek prosím doplnit

**Comment by nezbedova** [comment]
@SykoraLukas @MartinRumanek 
Jak to vypadá?

**Comment by tumovam** [comment]
@SykoraLukas můžu upravit stránku https://github.com/proarc/proarc/wiki/Archivace ? Doplnila bych jak vypadá současný archive balíček a zároveň i archivní export pro STT. Příp. technickýé věci by byly na Tobě... Díky, Markéta

**Comment by tumovam** [comment]
Doplněn popis složek a struktura balíčku: https://github.com/proarc/proarc/wiki/Archivace

**Comment by SykoraLukas** [comment]
Já myslím, že dobrý. Může se uzavřít.

**Comment by SykoraLukas** [comment]
Uzavírám na základě testování.
