### ISSUE TITLE
STT - přidělení URN:NBN

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#911]
NDK export funguje, ake chybí možnost přidělovat URN:NBN. U ostatních NDK balíčků je to povinný identifikátor. Myslím si, že by měl být i zde.

**Comment by pavelkocourek** [comment]
Ověřit zdali, má být URBN:NBN přidělováno - MN
Ze schůzky 20.3.

**Comment by SykoraLukas** [comment]
Po konzultaci s @luckajirku: URN:NBN se přiděluje jen modelům, pro které existuje standard NDK. Z tohoto důvodu se toto issue odkládá do doby, než bude standard NDK pro Staré tisky

**Comment by krizovj** [comment]
@nezbedova Je v tom novém doporučení pro STT také možnost přidělovat starým tiskům urn:nbn nebo ne?

**Comment by nezbedova** [comment]
Není.

**Comment by tumovam** [comment]
MZK uvažuje o přidelování urn:nbn...

**Comment by ZdenkaSera** [comment]
Odpověď p. Beňačkové ohledně registrace STT v CZIDLe:

Pokiaľ budete pre starý tisk žiadať o urn:nbn, tak použijete klasický model pre monografiu. Dobrou praxou potom je, aby (pokiaľ vám to váš systém umožní) ste do nepovinného atribútu documentType dopísali, že sa jedná o starý tisk (metodika str.45).

**Comment by ZdenkaSera** [comment]
@SykoraLukas Chtěla jsem vyzkoušet, jak by se přidělení pro STT zachovalo - u STT není tlačítko pro přidělení urn:nbn dostupné na liště.

**Comment by SykoraLukas** [comment]
Zatím jsem toto nezařadil do vývoje, protože teď to byla oprava a ne vývoj. Bude to součástí příští verze.

**Comment by ZdenkaSera** [comment]
Samozřejmě - to byl jen komentář pro jistotu - nepřítomnost tlačítka jsem si dřív neuvědomila :-)

**Comment by ZdenkaSera** [comment]
Povinnost nebo možnost přidělení? Prosím MZK a KNAV o komentář.

**Comment by ZdenkaSera** [comment]
LS: lze řešit varováním při exportu bez urn:nbn

**Comment by ZdenkaSera** [comment]
LJ: nelze konfigurovat na úrovni knihovny?

**Comment by ZdenkaSera** [comment]
@erikamirova @nezbedova Prosím o reakci, děkuji.

**Comment by nezbedova** [comment]
O povinnosti přidělení nemůžeme rozhodovat. 
Přikláním se k  - nepovinné a PA má jen upozornit při exportu, že urn:nbn chybí

**Comment by erikamirova** [comment]
@ZdenkaSera Za MZK se také přikláníme k tomu mít možnost ho přidělit nepovinně.

**Comment by ZdenkaSera** [comment]
@erikamirova @nezbedova Děkuji.

@SykoraLukas Vracím to k Vám a prosím o úpravu. Děkuji.

**Comment by vjirousek** [comment]
> O povinnosti přidělení nemůžeme rozhodovat.
> Přikláním se k - nepovinné a PA má jen upozornit při exportu, že urn:nbn chybí

Povinnost (M) je definována v Definici metadatových formátů pro digitalizaci monografických dokumentů, z níž Metodika pro STT vychází. Metodika řeší jen oblasti, v nichž se popis od novodobých fondů liší, ostatní povinnosti DMF zůstávají v platnosti.

**Comment by zabak** [comment]
@vjirousek je ale jisté, že všechny digitalizované STT mohou dostat URN:NBN?

**Comment by luckajirku** [comment]
>  
> Povinnost (M) je definována v Definici metadatových formátů pro digitalizaci monografických dokumentů, z níž Metodika pro STT vychází. Metodika řeší jen oblasti, v nichž se popis od novodobých fondů liší, ostatní povinnosti DMF zůstávají v platnosti.

@vjirousek nevím, tohle jsem asi pochopila od začátku jinak - když NK nechtěla pro STT udělat NDK standard, ale schválit "jen" doporučení - jak se potom na to doporučení můžou vztahovat povinnosti ze standardu?

**Comment by ZdenkaSera** [comment]
Při procházení zápisu k ProArcu jsme narazila na tuto poznámku : někteří zpracovatelé (míněno STT) nejsou registrátory, povinnost urn:nbn pro ně komplikací".

**Comment by ZdenkaSera** [comment]
@luckajirku @nezbedova @erikamirova Abychom se v této věci posunuli dál a měli možnost začít přidělení urn:nbn STT testovat, resp. pak i realizovat, se @SykoraLukas navrhujeme po domluvě zatím toto řešení: Při exportu STT se v případě chybějícího urn:nbn objeví dialogové okno s oznámením, že urn:nbn chybí a s dotazem, zda chce uživatel přesto pokračovat. Při volbě :ano“ pak bude zatím možné dokončit export i bez přiděleného urn:nbn.  @vjirousek

**Comment by luckajirku** [comment]
za nás je navržené řešení v pořádku

**Comment by erikamirova** [comment]
@zabak Za mě je toto řešení v pohodě, ale asi by ses k tomu měl vyjádřit i ty.

**Comment by nezbedova** [comment]
Za KNAV souhlasím.

**Comment by zabak** [comment]
Za MZK taky souhasím.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím, mohl byste to tedy takhle připravit? Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Prosím o přidání možnosti (tlačítka na liště) přidělení urn:nbn starým tiskům i do jádra, budeme v něm nejspíš ještě chvíli pracovat :-)

**Comment by ZdenkaSera** [comment]
@SykoraLukas urn:nbn jde STT přidělit, ale chybí hláška, pokud expoertuji objekt bez něj.
Testováno v jádře na vydané verzi 3.8. v KNAV a v novém klientovi na Inovatiice - chyba v obou případech

**Comment by SykoraLukas** [comment]
Varování s hláškou je náročné na implementaci ve starém klientovi, proto to bude fungovat jen v novém klientovi. 

Nový klient:
Pokud udělám export bez přiděleného URN:NBN, aplikace mi zobrazí zprávu, že objekt neobsahuje URN:NBN a možnosti "I Přesto Exportovat" nebo "Zrušit". Zrušením dojde ke zrušení exportu, Možností "I přesto exportovat" proběhne export bez URN:NBN. 
Starý klient:
Export se bude chovat stejně jako nyní u NDK modelů. Buďto URN:NBN bude přiděleno a půjde export, nebo URN:NBN přiděleno nebude a export nepůjde.

**Comment by ZdenkaSera** [comment]
@erikamirova @nezbedova za mne je to ok, ale prosím Váš názor. Děkuji.

**Comment by albertoh** [comment]
Pridal jsem moznost v klientovi "Přesto exportovat" pri teto chybe

**Comment by ZdenkaSera** [comment]
@albertoh Díky, založím nové issue k otestování v kleintovi.

**Comment by nezbedova** [comment]
Toto řešení nám vyhovuje. Děkuji.

**Comment by ZdenkaSera** [comment]
@SykoraLukas Lukáši, tak to tak uděláme, MZK by to vadit nemělo vzhledem k tomu, že už pracují v novém klientovi :-) :@erikamirova

**Comment by ZdenkaSera** [comment]
@SykoraLukas Zdá se domluveno, předávám :-) Díky.

**Comment by ZdenkaSera** [comment]
Zavírám na základě štítku.
