### ISSUE TITLE
Import dat z Krameria - v 3.5.6

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#912]
Existuje nějaký popis nebo dokumentace k importu dat z Krameria? Jako myslím, který údaj se kam stahuje, v jakém modelu se to založí apod.?
Už se nám podařilo ten import v ProArcu najít, ale nejsou tam žádná, jako že vůbec žádná metadata. Jen popis stran a někde jsem myslím zahlídla datum vydání (ale až přímo v záznamu, ve struktuře to vidět není), takže se podle toho nedá moc orientovat:
![image](https://user-images.githubusercontent.com/21309201/54529292-cd90bd80-497f-11e9-8f80-440e2223a615.png)

V ProArcu se to navíc založilo jako K4 ročník (a K4 výtisk). To se bude dělat vždycky? Myslím i potom, co budou v exportu z Krameria vazby? Většinou asi budeme chtít vyrobit z těch starších dat NDK balíčky. Takže když mám starší data, tak by se měla namapovat v ProArcu do těch NDK formulářů, doplním chybějící data a pak to vyexportuju jako NDK balíček. Což takhle nejde. Takhle bych musela založit celou strukturu znovu v NDK formulářích a pak bych tam ručně musela přesunout všechny ty obrázky.

**Comment by SykoraLukas** [comment]
Nutná konfigurace https://github.com/proarc/proarc/wiki/Konfigurace#kramerius-reimport
