### ISSUE TITLE
Převod PDF do PDF/A

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#915]
Bylo by možné, aby ProArc uměl převést naimportované PDF do PDF/A? PDF soubory se importují jednotlivě k jednotlivým záznamům buď eČlánků nebo k NDK eMonografii nebo k NDK eČíslu a také v budoucnu k NDK eČlánku.

**Comment by PetrKotynek** [comment]
Zatím neslibnější z "open-source" je použití Ghostscriptu přes export do .ps formátu. Z náhodně vybraných 550  pdf souborů, všechny neprojdou na PDF/A test. Po následující lázni prošlo 435 tedy 79 %.   Petr Kotýnek  
# přímé použití Ghostscriptu pdf to pdf zlepší skóre o pár %
gs -dPDFA -dBATCH -dNOPAUSE -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -sPDFACompatibilityPolicy=1 -sOutputFile=output_filename.pdf input_filename.pdf
# lepší
Get-ChildItem C:\temp\pom -Filter *.pdf | ForEach-Object {pdf2ps c:\temp\pom\"$_" c:\temp\pom\ps\$($_.BaseName).ps}
Get-ChildItem C:\temp\pom\ps -Filter *.ps | ForEach-Object \
{gswin64c -dPDFA -dBATCH -dNOPAUSE -dPDFSETTINGS=/prepress -dNOOUTERSAVE -sColorConversionStrategy=UseDeviceIndependentColor -sProcessColorModel=DeviceRGB -sDEVICE=pdfwrite -sPDFACompatibilityPolicy=1 -sOutputFile=c:\temp\pom\double\"$($_.BaseName)".pdf c:\temp\pom\ps\"$_"}

c:\tools\v\verapdf.bat --format text -f 0 --success c:\temp\pom\*.pdf > c:\temp\src_score.txt
c:\tools\v\verapdf.bat --format text -f 0 --success c:\temp\pom\double\*.pdf > c:\temp\double_score.txt

PS C:\temp> gswin64c --version
9.26
PS C:\temp> c:\tools\v\verapdf.bat --version
veraPDF 1.12.1

**Comment by SykoraLukas** [comment]
@filip Prosím o návrh nástroje, který by se měl používat.

**Comment by PetrKotynek** [comment]
Není někde k mání zkušební set pdf na kterém by šlo něco trochu zkoušet, já něco mám ale bude to dost zastaralé PK

PDF2ARCHIVE
PDFsam
Ghostscript
PDFLite

**Comment by kerschfilip** [comment]
@SykoraLukas máme návrh řešení, prosím o komentář, jestli je to takto realizovatelné:

Protože konverze do PDF/A není vždy úspěšná (podle našich testů i [NK](https://itlib.cvtisr.sk/wp-content/uploads/2022/07/1_2_2022_Hrzinova_Jirousek.pdf) to vychází cca na 80 %), tak by ProArc neměl převod do PDF/A vynucovat, ale spíš ho uživatelům nabízet.

Navrhujeme přidat do klienta dialogové okno pro nahrání PDF, jako bylo ve starém rozhraní
![image](https://github.com/user-attachments/assets/da3c7f5e-174c-43be-aa96-ca17a0140bd3)

okno bude obsahovat pole pro nahrání PDF z adresáře + zaškrtávátko, jestli se má PDF převést na PDF/A (defaultně nezaškrtnuté)

Ke konverzi navrhujeme použít Ghostscript a PDF konvertovat do PDF/A-2. Ideální by bylo, kdyby dialogové okno vrátilo hlášku, jestli se konverze povedla, úplně nejlepší by bylo rovnou spustit i validaci pomocí veraPDF

Kromě samotného Ghostscriptu je ke zvážení použití [PDF2ARCHIVE](https://github.com/matteosecli/pdf2archive), kde se kombinuje GS s veraPDF a dělá to vlastně přesně to, co bychom teď chtěli my. Problém je jen, že převádí PDF jen do PDF/A-1, ale to by se asi dalo přepsat změnou parametru `-dPDFA=2`, když PDF2ARCHIVE volá GS.

**Comment by SykoraLukas** [comment]
Po prostudování PDF2ARCHIVE jsem zjistil, ze přímo v tom skriptu, který to pouští je parametr -dPDFA=1. Takže pokud se na každé instalaci tento parametr upraví, tak by to mělo být možné používat s převodem do PDF/A-2.

**Comment by ZdenkaSera** [comment]
Schůzka 6.8. - LS:
Tlačítko vygenerovat PDF-A vedle tlačítka pro nahrání, zápis do správy procesů (zpětná vazba z Very)
příkazy v konfiguraci
zachovaly by se obě varianty PDF i PDF-A
do NDK balíčku by se použilo PDF-A (pokud by bylo)
mohla by existovat složka zdrojových data s původním PDF

**Comment by SykoraLukas** [comment]
Prosím o zaslání vzorových pdf, nad kterými můžeme změnu zkoušet.

**Comment by SykoraLukas** [comment]
> zápis do správy procesů (zpětná vazba z Very)

Tady asi není co zapsat. Celý ten výpis, když spustím generování vypadá takto:

```
proarc@proarc:/opt/pdf2archive$ ./pdf2archive /data/.proarc/oc_aba007-000av2.pdf
=== Welcome to PDF2ARCHIVE ===
GPL Ghostscript 9.55.0: Unrecoverable error, exit code 1
  Creating the definition file...
  Compressing PDF & embedding fonts...
  Converting to PDF/A-1B...
  Removing temporary files...
  Done, now ESSE3 is happy! ;)
  Suggestion: validate the resulting PDF to be sure it's PDF/A-1B compliant.

```

Pokud pustím i s validací vypadá takto:
```
proarc@proarc:/opt/pdf2archive$ ./pdf2archive --validate /data/.proarc/oc_aba007-000av2.pdf
=== Welcome to PDF2ARCHIVE ===
GPL Ghostscript 9.55.0: Unrecoverable error, exit code 1
  Creating the definition file...
  Compressing PDF & embedding fonts...
  Converting to PDF/A-1B...
  Removing temporary files...
  Done, now ESSE3 is happy! ;)
  Validating resulting file...
  FAIL /data/.proarc/oc_aba007-000av2-PDFA.pdf

```

To samé platí pro pdf/A-2, potom, co se všude přepíše hodnota A-1B na hodnoty A-2.

Jediné tedy co se dá zapsat je informace, že se vygenerovalo a jaký je stav validace: `PASS` nebo `FAIL`.

**Comment by kerschfilip** [comment]
PDF poslány mailem

> Jediné tedy co se dá zapsat je informace, že se vygenerovalo a jaký je stav validace: PASS nebo FAIL.

To by úplně stačilo. Chtěl bych, aby ze správy procesů bylo jasné, jestli se povedlo/nepovedlo vygenerovat PDF/A a jestli je validní/nevalidní.

**Comment by SykoraLukas** [comment]
A jak se chovat k nevalidnímu pdf? Smazat ho nebo i přesto ho dávat do NDK a Archivniho balicku?

**Comment by kerschfilip** [comment]
Můžeš to někam zapsat, že je nevalidní? Třeba do PREMIS? Pokud ano, pak může zůstat. Jestli to ale nejde, tak smazat.

**Comment by SykoraLukas** [comment]
Ono to totiz i zalezi na softwaru, ktery je pouzit. https://bugs.ghostscript.com/show_bug.cgi?id=703486#c2

**Comment by SykoraLukas** [comment]
Ahoj,

díky. Nikam do dávat nebudu, jen potřebuji relevantní data, na kterých 
to testovat.

Ohledně té chyby tak je to viz ten mail v issues - záleží to na verzi 
imageMagicku, který se použije. Pokud nějaký starší, tak validace 
projde, pokud nový tak validace spadne. Doufám tedy, že to je dočasný 
problém.

Jen nevím, do jakého elementu v premisu to zapsat. Zkusím zjistit.

S pozdravem,

Lukáš Sýkora
M +420 737 649 591
***@***.***


------ Původní zpráva ------
Od "kerschfilip" ***@***.***>
Komu "proarc/proarc" ***@***.***>
Kopie "SykoraLukas" ***@***.***>; "Mention" 
***@***.***>
Datum 21.08.2024 10:52:36
Předmět Re: [proarc/proarc] Převod PDF do PDF/A (#915)

**Comment by PetrKotynek** [comment]
Tady asi nezbude než si něco, nějaké konkrétní verse vybrat, třeba špatně.
Ze strany KNAV je tendence držet věci up-to-date, aktuálně "standardní"
Debian 12 Bookworm má příslušné balíčky trochu výše:
ghostscript 10.0.0~dfsg-11+deb12u4
imagemagick 8:6.9.11.60+dfsg-1.6+deb12u1
a veraPDF se instaluje i v Debianu a 1.16.1 asi není problém. Případné
zadání imagemagick 6 je skoro na kontejner.
PK

**Comment by SykoraLukas** [comment]
Pokud se podaří vygenerovat soubor, výsledek validace se zapisuje dočasně do Rels-EXT datastreamu (nezobrazen uživateli, je vidět ve FOXML). 

V případě NDK a archivního exportu se do balíčku vkládá nově vygenerované PDF. Do PRREMISu se zapíše pod `eventIdentifierValue = validation` validační status a vytvoří se nový agent, který kontrolu provedl (veraPDF).

```
<premis:event>
  <premis:eventIdentifier>
    <premis:eventIdentifierType>ProArc_EventID</premis:eventIdentifierType>
    <premis:eventIdentifierValue>PDF_validation_001</premis:eventIdentifierValue>
  </premis:eventIdentifier>
  <premis:eventType>validation</premis:eventType>
  <premis:eventDateTime>2024-08-27T10:59:37.979+02:00</premis:eventDateTime>
  <premis:eventDetail>validation</premis:eventDetail>
  <premis:eventOutcomeInformation>
    <premis:eventOutcome>failed</premis:eventOutcome>
  </premis:eventOutcomeInformation>
  <premis:linkingAgentIdentifier>
    <premis:linkingAgentIdentifierType>ProArc_AgentID</premis:linkingAgentIdentifierType>
    <premis:linkingAgentIdentifierValue>veraPDF</premis:linkingAgentIdentifierValue>
    <premis:linkingAgentRole>software</premis:linkingAgentRole>
  </premis:linkingAgentIdentifier>
  <premis:linkingObjectIdentifier>
    <premis:linkingObjectIdentifierType>ProArc_URI</premis:linkingObjectIdentifierType>
    <premis:linkingObjectIdentifierValue>info:fedora/uuid:e6f2e26a-988c-4c26-ba67-5bac7a9d8cba/PDF</premis:linkingObjectIdentifierValue>
  </premis:linkingObjectIdentifier>
</premis:event>
```

```
<premis:agent>
  <premis:agentIdentifier>
    <premis:agentIdentifierType>ProArc_AgentID</premis:agentIdentifierType>
    <premis:agentIdentifierValue>veraPDF</premis:agentIdentifierValue>
  </premis:agentIdentifier>
  <premis:agentName>veraPDF</premis:agentName>
  <premis:agentType>software</premis:agentType>
</premis:agent>
```

**Comment by SykoraLukas** [comment]
Nutná konfigurace a instalace [pdf2archive](https://github.com/matteosecli/pdf2archive) 

``` properties
# (4.2.1) ID procesu, ktery generuje z pdf soubor pdfa
#generate.pdfA.processor=generatePdfA
# (4.2.1) Umíst?ní spustitelného souboru, který má konverzi na starost
processor.generatePdfA.exec=/opt/pdf2archive/pdf2archive
# (4.2.1) Parametry procesu (aplikace doplní na posledni 2 mista vstupni a vystupni soubor konverze)
#processor.generatePdfA.arg=--validate
```

**Comment by PetrKotynek** [comment]
Oprava pdf2archive "./verapdf/verapdf" relativním odkazem ze spoušteného adresáře  PK


 VERAMSGOPTS=""
 #ERROPTS="2>/dev/null"
 SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

     #echo "  $(./verapdf/verapdf "$1" --extract --flavour 1b --format text "$2")"
     #echo "  $(/home/proarc/.local/pdf2archive/verapdf/verapdf "$1" --extract --flavour 1b --format text "$2")"
 
     echo "  $($SCRIPT_DIR/verapdf/verapdf "$1" --extract --flavour 1b --format text "$2")"



proarc@proarc-ozc-old-test:~$ /home/proarc/.local/pdf2archive/pdf2archive --validate /home/proarc/tmp/pdf/c2_pdfa.pdf
=== Welcome to PDF2ARCHIVE ===
  Creating the definition file...
  Compressing PDF & embedding fonts...
  Converting to PDF/A-1B...
  Removing temporary files...
  Done, now ESSE3 is happy! ;)
  Validating...
  PASS /home/proarc/tmp/pdf/c2_pdfa-PDFA.pdf

**Comment by PetrKotynek** [comment]
Fork pdf2archive je na https://gitlab.com/PetrKotynek/pdf2archive_proarc
PK

proarc-test@proarc-ozc:~$ cd .local
proarc-test@proarc-ozc:~/.local$ git clone https://gitlab.com/PetrKotynek/pdf2archive_proarc
Cloning into 'pdf2archive_proarc'...
warning: redirecting to https://gitlab.com/PetrKotynek/pdf2archive_proarc.git/
remote: Enumerating objects: 554, done.
remote: Counting objects: 100% (554/554), done.
remote: Compressing objects: 100% (312/312), done.
remote: Total 554 (delta 238), reused 545 (delta 235), pack-reused 0 (from 0)
Receiving objects: 100% (554/554), 4.66 MiB | 38.45 MiB/s, done.
Resolving deltas: 100% (238/238), done.


proarc-test@proarc-ozc:~$ /home/proarc-test/.local/pdf2archive_proarc/pdf2archive --validate-only "./work_data/users/fkdigi/import/dad3602b-91f6-4d08-860d-a640704e2ce2/aba007-0009ah/original/oc_aba007-0009ah.pdf"
  Validating...
  FAIL /home/proarc-test/./work_data/users/fkdigi/import/dad3602b-91f6-4d08-860d-a640704e2ce2/aba007-0009ah/original/oc_aba007-0009ah.pdf

processor.generatePdfA.exec=/home/proarc-test/.local/pdf2archive_proarc/pdf2archive
