### ISSUE TITLE
eČlánek - rozsah stran

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#918]
Nově od verze 3.5.7 máme ve formuláři pro náš eČlánek (nestandardní) přidané pole pro vyplnění rozsahu stran - part-extent-start a end. Dřív se to psalo do elementu relatedItem. 
Když stahuji záznam článku z katalogu, tak se tento údaj stahuje pořád do elementu relatedItem, měl by se stahovat do toho nového. 
Oprava stačí až ve verzi, která vyjde 1. 4. 2019

**Comment by SykoraLukas** [comment]
Na kterém záznamu mohu tuto chybu otestovat? Hledal jsem v Alphu KNAVky ale našel jsem jen články bez vyplněných údajů o straně.

**Comment by krizovj** [comment]
Třeba tady: 
https://vufind.lib.cas.cz/ustav/KNAV/Record/001888361#details

on tam rozsah stran je, ale do ProArcu se stahuje jen číslo první strany. 
Je to pole 773, podpole q. Konkrétně u tohoto článku jde o stranu 87:
63:2<87 (63 je číslo ročník, 2 číslo čísla a 87 číslo první strany článku).

**Comment by SykoraLukas** [comment]
Šablonu jsem upravil tak, aby pole 773 q stahovala do elementu `mods:part` viz obrazek níže. Je to takhle správně?

![918-MarcToMods-Template](https://user-images.githubusercontent.com/27210823/55354957-46872d80-54c7-11e9-83d2-6a302bb44a6f.PNG)

**Comment by krizovj** [comment]
Jo, takhle je to správně. Jak na to koukám, nešlo by ještě přehodit ty údaje o ročníku a čísle pod element relatedItem? I ve standardu je, že by údaje o číslu a ročníku měly být v relatedItem a taky mi to přijde logičtější. 

![image](https://user-images.githubusercontent.com/21309201/55377451-4d3c9180-5515-11e9-86c9-4b443433bb41.png)

**Comment by SykoraLukas** [comment]
To by šlo, opravím
