### ISSUE TITLE
3.5.7 - Nadřazený objekt - mizí

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#920]
Tlačítko "Nadřazený objekt" se chová nějak podivně. 
Když vyberu jako model jakékoliv periodikum (NDK Periodikum nebo K4 Periodikum), STT Vícedílnou monografii, K4 monografii, NDK zvukový dokument, tak tlačítko "Nadřazený objekt" zmizí (zmizí z obou lišt).

Proklikala jsem všechny modely a u všech NDK e modelů zmizí celá horší lišta a zůstane jen ta dolní, kde zároveň opět chybí tlačítko "Nadřazený objekt". 

Ostatní modely jsou v pohodě

**Comment by SykoraLukas** [comment]
To, že tlačtko mizí je v pořádku. Podle dříve definovaných pravidel (ještě než jsem nastoupil do ProArcu), se řeklo, že nad hlavní modely (titul periodika, vícedílnou monografii, zvukový dokument) nepůjde dát již žádný jiný element. 

Např: `titul periodika` se nedá navázat jako potomek jakéhokoli jiného modelu. 

Proto u těchto modelů mizí tlačítko vybrat `Nadřazený objekt`. 


U eDokumentů se to chová standardně jako u jiných modelů - to, že zmizí horní lišta je způsobené tím, že v databázi nejspíše nemáte žádný objekt vytvořený z vybraného modelu. Pokud vytvoříš například `eMonografii`, poté ji vyhledáš, poté bys už měla vidět i horní lištu. V případě že není vybraný žádný model, horní lišta mizí a dolní zůstává. V případě, že je vybraný model, vidíš obě lišty.

**Comment by krizovj** [comment]
jasný, díky za vysvětlení
