### ISSUE TITLE
3.5.7 - import dat z Krameria - přesun stran

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#921]
Mám v ProArcu naimportovaná data z Krameria, která se tam naimportovala jako model K4 Ročník. 
Chtěla jsem přesunout pár stran z jednoho výtisku pod svůj vytvořený záznam v NDK modelu. Ale přesunul se celý ten K4 Ročník, i když jsem přes funkci "nadřazený objekt" vybrala jen několik stran. 

![image](https://user-images.githubusercontent.com/21309201/55080947-463dfb00-509f-11e9-9e26-b4bc518e5a4e.png)

**Comment by SykoraLukas** [comment]
Více stran najednou nelze přesouvat. Není možné, že jste vyhledala K4 ročník, ten rozklikla - v dolním okně vybrala několik stran a na liště v horním okně vybrala Nadřazený objekt? Jestli to tak je, tak jse vybírala nadřazený objekt pro vybraný objekt v horním okně nikoli pro vybrané modely v dolním okně.

**Comment by krizovj** [comment]
Už jsem na to přišla... :)
