### ISSUE TITLE
(Kramerius) Havarující ingest do Fedory a následující komplikace s nekonzistencí

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#922]
Zdravím,
dovuluji si upozornit na závažné krameriovské/fedoří issue: 
https://github.com/ceskaexpedice/kramerius/issues/664 
Cituji kolegu Martina Dudu:
"Závěr - je potřeba už ve výrobě (ProArc) ošetřit délku polí mapovaných do DC a případně je zkrátit na povolenou maximální délku 2712 znaků (viz log databáze), nebo spíše o něco méně."

Petr

**Comment by SykoraLukas** [comment]
Mohu omezit maximální délku jen v DC. Do MODSu by se zapsal celý abstrakt, ale do DC by se pole ořízlo (vzalo by se prvních 2700 znaků). ALe potřebuji, aby to schválil člověk, který s tímto pracuje nejčastěji. Problé,m co v tom vidím, je nekonzistence mezi MODSem a DCorem, což nevím, zda by nevadilo NDK PSP balíku. @krizovj  co si o tom myslíš, šloby to takhle udělat?

**Comment by krizovj** [comment]
Tak za mě je hlavní, aby ten abstrakt byl v Krameriovi celý a aby se v něm vyhledávalo. Pokud to zůstane tak, což jsem teda moc nepochopila, jestli to tak je, tak je to za mě asi v pohodě. 

Celý abstrakt tedy bude jen v MODSu a do DC se překlopí jen omezený abstrakt třeba na těch 2700 znaků?
A Kramerius zobrazí tu verzi abstraktu z MODS, je to tak? 
Problém vidím akorát v tom, že do Europeany se z Krameria posílá DC, aspoň myslím. Na druhou stranu, je tam odkaz zase zpátky do ČDK, takže by to asi zas tak nevadilo. 

Na nekonzistenci MODS a DC a jestli to vadí z hlediska NDK se zeptám NK a dám vědět.

**Comment by krizovj** [comment]
Pomohlo by, kdyby se ten abstrakt rozdělil do více polí?

**Comment by mduda100871** [comment]
> Pomohlo by, kdyby se ten abstrakt rozdělil do více polí?

Ja myslím, že ano. Element `dc:description` by snad měl být opakovatelný...

MD

**Comment by krizovj** [comment]
Ano, je opakovatelný. V Alephu musíme abstrakt taky rozdělovat, pokud je příliš dlouhý. 

Šlo by to u záznamů stahovaných z katalogu udělat automaticky? Že by ProArc poznal, že je v tom poli moc znaků a vyrobil nové pole, kam by dal ten zbytek abstraktu nad 2700 znaků?

**Comment by krizovj** [comment]
Teď jsem dostala odpověď z NK, že nekonzistence mezi MODS abstraktem a DC nevadí.

**Comment by SykoraLukas** [comment]
Dobře, rozdělím to natvrdo po 2700 znacích. Jediné co nedokážu zaručit je udržování celých slov - tedy slovo na pomezí 2 700 znacích bude rozděleno do dvou elementů `dc:description`.

**Comment by krizovj** [comment]
A nešlo by to rozdělit už jako v MODSu? Že by to pole ve formuláři v ProArcu bylo omezené na 2 700 znaků a u záznamů stažených z katalogu by se to natvrdo rozdělilo a my bychom si na to dali pozor a třeba bysme to ve formuláři rozdělili líp, aby tam nebyla ta rozdělená slova. Když by bylo MODS pole omezeno na 2 700 znaků, tak už by neměl být problém ani v DC, ne? 
A u záznamů, které se vyplňují ručně by prostě bylo to pole taky omezené a přidalo by se ručně další... 
Šlo by to takhle? Tím by se to vyřešilo a zároveň by MODS a DC byly stejné...

**Comment by SykoraLukas** [comment]
Takhle to v současné verzi udělat nejde, můžeme to upravit v novém klientovi. Ve smartGWT to nelze, proto zatím upravím upravím podle toho, jak jsem napsal výše.

**Comment by SykoraLukas** [comment]
Rozdělit pole i v Modsu a nastavit pevnou maximální možnou vloženou hodnotu ve formuláři na 2700 znaků.

**Comment by PetrKotynek** [comment]
Ahoj Lukasi,
nemá být v popisu 3.5.10  misto
A mezi import.profiles je nutné doplnit příslušnou hodnotu
default_kramerius_import, ndk_monograph_kramerius_import,
ndk_periodical_kramerius_import

A mezi ... profile.default_kramerius_import,
profile.ndk_monograph_kramerius_import,
profile.ndk_periodical_kramerius_import
???
Petr
