### ISSUE TITLE
NDK export "Unable to find DIV for page order:ISSUE_0001 266"

### ISSUE THREAD

**Issue by PetrKotynek** [proarc/proarc#923]
Přikládám obrazovky, logy , a původní email. Petr Kotýnek

proarc-common\src\main\java\cz\cas\lib\proarc\common\export\mets\structure\MetsElementVisitor.java
... throw new MetsExportException("Unable to find DIV for page order:" + structLinkMapping.pageDiv + " " + structLinkMapping.pageOrder, false, null); 

Dobry den,

pri NDK exportu jednotlivych rocniku periodika Ceska literatura (viz. printscreen) mi ProArc hazi chyby a export zfailuje. Muzete se prosim kouknout cim by to mohlo byt? Rocniky 48 a 49 se vyexportovali v poradku.

Diky

Michal Psenicka 
[logexport_ndk_exp.zip](https://github.com/proarc/proarc/files/3033165/logexport_ndk_exp.zip)
![errjpg](https://user-images.githubusercontent.com/37083676/55391003-ba155300-5538-11e9-9687-b696e22b8934.jpg)
[err_klient.txt](https://github.com/proarc/proarc/files/3033171/err_klient.txt)

**Comment by SykoraLukas** [comment]
Z těchto logu nic nevyčtu. Potřebuji částečně vyexportovaný balíček. Vzhledem k tomu, že jde o NDK modely, zkuste prosím udělat Archive export a i ten mi zaslat.

**Comment by PetrKotynek** [comment]
Zdravím ,
" Pokud se odstrani z celeho rocniku hranate zavorky probehne export v poradku. "
"Podle mě tomu vadilo to, že to bylo pole pro index strany a tam samozřejmě hranaté závorky být nemají."

Petr

**Comment by PetrKotynek** [comment]
viz vyše PK
