### ISSUE TITLE
Tlačítko "Vybrat vše" ve vazbách

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#924]
Praktické by bylo přidat v okně **Vazby** tlačítko **"Vybrat vše"**

**Comment by pavelkocourek** [comment]
Přesunuto : Tlačítko "Vybrat vše" ve vazbách (#924)

**Comment by pavelkocourek** [comment]
Přesunuto : Tlačítko "Vybrat vše" ve vazbách (#924)
