### ISSUE TITLE
Hlášení duplicity

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#925]
V okně Příprava metadat pro načtení do úložiště a ve "Vazby" by mohl hlásit ( jen upozornění ) duplicitu na některé typy stran např. Přední/Zadní desky, Přední/Zadní přídeští, Titulní strana.... 
Ve Vazbách a možná i při Exportu hlásit duplicitu na Index strany....

**Comment by luckajirku** [comment]
> Ve Vazbách a možná i při Exportu hlásit duplicitu na Index strany....

Na kontroly indexů (nejen na duplicitu) je už issue založeno (https://github.com/proarc/proarc/issues/840)

**Comment by SmejkalovaAnna** [comment]
Už to vidím, tak to mažu a dáte prosím Fialový label na 840? Díky, nemám na to práva.

**Comment by luckajirku** [comment]
Není třeba zavírat, pokud je požadavek i na kontrolu typů stran, to v tom issue není, komentovala jsem jen ten index strany.
Co se týká labelu, tak ten Nový klient chápu tak, že se dává u issues, které v současném klientovi řešit nelze, což není ten případ si myslím.

**Comment by pavelkocourek** [comment]
Přesunuto : Hlášení duplicity (#925) #18
