### ISSUE TITLE
rda/aacr u přílohy periodika

### ISSUE THREAD

**Issue by luckajirku** [proarc/proarc#927]
Vytvořím přílohu periodika a jako výchozí pravidla se ukazují AACR, i když je titul podle RDA.
Proč se to v příloze chová, jak se to chová a nepřebere si pravidla z titulu?
(Navíc třeba u čísla se neukazují pravidla ve formuláři vůbec.)

**Comment by luckajirku** [comment]
@SykoraLukas můžeš se na to prosím podívat? Díky.

**Comment by luckajirku** [comment]
Stav ve verzi 3.5.13: 
1. titul je aacr, ročník i číslo se založí automaticky aacr, příloha se založí rda. 
2. titul je rda, ročník i čísla se založí automaticky rda, příloha se založí aacr.

**Comment by SykoraLukas** [comment]
Můžeš mi prosím potvrdit, že u takto špatných příloh jsou 2 elementy recordInfo? Je to dobře vidět v xml záznamu.

**Comment by luckajirku** [comment]
Ano, recordInfo je tam 2x, jednou recordCreationDate + recordChangeDate + descriptionStandard a ve druhém výskytu je jen descriptionStandard.

**Comment by SykoraLukas** [comment]
Tím pádem jsem toto už opravil

**Comment by luckajirku** [comment]
@SykoraLukas máš prosím tě představu, kdy verze s touhle opravou bude k použití?

**Comment by SykoraLukas** [comment]
Ahoj, tohle by mělo vyjít během přístího týdne.

**Comment by luckajirku** [comment]
ve verzi ze 14.10. to vypadá OK

**Comment by SykoraLukas** [comment]
Uzavírám po úspěšném testování.
