### ISSUE TITLE
Rozšíření limitu na počet poznámek a deskriptorů

### ISSUE THREAD

**Issue by svetlym** [proarc/proarc#929]
Uvítali bychom možnost přidání dalších polí u obecné poznámky k titulu "Note RA" - v současné době se dá přidat jen 10 polí a když je poznámek více, musíme je vtěsnat jen do těchto 10 polí tudíž nemá jedna poznámka jen jedno pole jak by správně měla.

Stejně tak v údajích o věcném třídění "Subject R" bychom rádi měli tuto možnost doplnit více než 10 polí. Pokud se nenaimportují z našeho knihovnického systému všechny údaje, doplňujeme je ručně a při nedostatku těchto polí to řešíme vepsáním do obecné poznámky.

**Comment by SykoraLukas** [comment]
Kterých modelů se toto týká a na jaký počet byste potřebovali rozšířit počet?

**Comment by svetlym** [comment]
> Kterých modelů se toto týká

Určitě monografií a periodik, ale řekl bych, že asi všech. Jestli se nepletu, tak poznámky a deskriptory mohou být u všeho.

> na jaký počet byste potřebovali rozšířit počet?

To záleží na tom, co povolují standardy (je to v nich vůbec nějak omezeno?) a taky to souvisí s issue https://github.com/proarc/proarc/issues/930. Pokud s tím od určitého počtu nejde rozumě pracovat, tak je asi rozumné to omezit.

**Comment by SykoraLukas** [comment]
Zvýšeno na 30 (místo současných 10). Případně se dá opět zvýšit.

Rychlost načítání souvisí s použitím SmartGWT. Přechodem na nového klienta, by se měla problém s pomalostí vyřešit - pokud však budou velmi dlouhé popisy, bude s tím mít problém i nový klient a posléze i Kramerius.
