### ISSUE TITLE
v. 3.5.8 - Autority

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#941]
Ve verzi 3.5.8 mi nefungují autority. 

Uvádím postup, jestli jsem třeba nepostupovala špatně.

1. Vytvořím záznam
2. Otevře se prázdný formulář
3. Začnu vyplňovat, blabla, dojdu k elementu "name"
4. V záložce "Metadata" vyberu možnost "Autority"
Stane se jedna z následujících věcí
5.a Nestane se nic (nereaguje)
5.b Otevře se formulář pro stažení záznamu z katalogu, kde ale není možnost vybrat databázi autorit. Vypadá úplně stejně, jako formulář pro stažení záznamu z katalogu. 

Zkoušela jsem to u eČlánku, NDK eMonografie, NDK Monografie, NDK eČísla, NDK Čísla, NDK Ročníku, NDK eRočníku, pak už mě to nebavilo, takže jsem to nevyzkoušela úplně u všech modelů.

Ještě jsem pak zkusila po vyplnění několika polí záznam uložit a pak dát teprv "Autority", ale to taky nepomohlo. 

Zkoušela jsem to v Chromu (73.0.3683.103) a Mozille (66.0.3).

**Comment by krizovj** [comment]
Ještě mě tak napadlo, není potřeba něco měnit v konfiguraci? Ale tomu se mi nechce věřit, to by přece bylo někde napsáno, ne?

**Comment by krizovj** [comment]
Verze 3.5.9 - je potřeba něco pro autority nastavovat v konfiguraci? Nikde je totiž nevidím...

**Comment by krizovj** [comment]
Verze 3.5.10 - zase se objevilo tlačítko "Autority", pod funkcí "Katalog", ale dělá to stejnou věc, jako ve verzi 3.5.8 (viz popis výše)

**Comment by tumovam** [comment]
Verze 3.5.11 - tlačítko "Autority" opět zmizelo (hledala jsem ve více modelech). Když rozkliknu "Metadata", vidím pouze "Formulář", "XML" a "Katalog". Jsou "Autority" někde jinde? Díky za odpověď :)

**Comment by SykoraLukas** [comment]
Dočasně bylo staženo, čeká na NK

**Comment by SykoraLukas** [comment]
Nově se bude stahovat ze Z39.50, který bude automaticky nakonfigurován v konfiguraci.

**Comment by tumovam** [comment]
@SykoraLukas můžeme toto issue zavřít? Autority už jsou minimálně ve v3.6.5 a v3.6.6. Díky

**Comment by SykoraLukas** [comment]
Souhlasím
