### ISSUE TITLE
Verze 3.5.8 i verze 3.5.7 - Nefunguje vyhledávání dle ČNB

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#948]
Nefunguje vyhledávání v souborném katalogu podle ČNB

**Comment by krizovj** [comment]
Teď jsem to zkoušela ve verzi 3.5.17 a šlo mi to:
![vyhledavanpodleccnb](https://user-images.githubusercontent.com/21309201/79435341-cc412280-7fcf-11ea-870e-053e89ec0699.jpg)
