### ISSUE TITLE
Vyhledávání v souborném katalogu podle pole 001

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#949]
Bylo by možné přidat do vyhledávání v souborném katalogu i možnost vyhledat podle pole 001? Díky.

**Comment by luckajirku** [comment]
Pokud se nepletu, tak tohle je záležitost konkrétní instalace ProArcu a nastaví se v konfiguraci pro Z39.50.
Každopádně s tou 001 v SK bude problém, pokud se něco nezměnilo, tak to přebírá 001 původního záznamu a pokud tam instituce nemá svůj prefix, mohou se teoreticky čísla více záznamů shodovat. I sám SKC nabízí hledání jen podle sysna, ne podle 001. Z 001 tam lze vyhledávat ve spojení se siglou z pole 910 - tedy pole 910, podpole a-x (sigla-id.číslo záznamu).

**Comment by nezbedova** [comment]
To jsme nevěděly. Zavírám a zakládám na hledání podle sysna.
