### ISSUE TITLE
Vyhledávání v souborném katalogu podle sysna

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#950]
Bylo by možné přidat do vyhledávání v souborném katalogu i možnost vyhledat podle sysna?

**Comment by jkremlacek** [comment]
Pro vyhledávání podle sysna by v konfiguraci ProArc-u mělo stačit doplnit další druh pole pro daný katalog.

Ukázka řešení (je třeba nahradit `aleph_mzk01` správným názvem v konfiguraci): 
```
catalog.aleph_mzk01.fields=bar, cnb, ssn, sbn, sg, sig, sys
catalog.aleph_mzk01.field.sig.query=sig
catalog.aleph_mzk01.field.sig.title=Signatura
catalog.aleph_mzk01.field.bar.query=bar
catalog.aleph_mzk01.field.bar.title=Čárový kód
catalog.aleph_mzk01.field.cnb.query=cnb
catalog.aleph_mzk01.field.cnb.title=CCNB
catalog.aleph_mzk01.field.ssn.query=ssn
catalog.aleph_mzk01.field.ssn.title=ISSN
catalog.aleph_mzk01.field.sbn.query=sbn
catalog.aleph_mzk01.field.sbn.title=ISBN
catalog.aleph_mzk01.field.sg.query=sg
catalog.aleph_mzk01.field.sg.title=Zkrácená signatura
catalog.aleph_mzk01.field.sys.query=sys
catalog.aleph_mzk01.field.sys.title=Sysno

```

**Comment by nezbedova** [comment]
Nefunguje to. prosím o jinou radu.

**Comment by jkremlacek** [comment]
V tom případě nebude chyba na straně ProArc-u (výše uvedená konfigurace je otestována a je funkční).

Pokud tedy máte správně nakonfigurovaný katalog (analogicky k příkladu, který jsem uvedl výše), pak je třeba zjistit od provozovatele SKC, zda v rámci Aleph XServices umožňuje vyhledávání pomocí sysna a dále, zda je vyhledávání pomocí sysna prováděno pomocí parametru `sys`.

**Comment by nezbedova** [comment]
Jenže ono nejde vyhledat nic z SKC. Tedy ani ISSN a to dříve šlo.

**Comment by jkremlacek** [comment]
Jen pro upřesnění - vyhledávání pomocí ISSN bez úpravy konfigurace, kterou jsem navrhoval, funguje vpořádku?

Jinak mnou uvedená konfigurace katalogu je aktuálně bez problému používána v ProArc-u MZK na verzi 3.5.8 v kombinaci s Alephem MZK.

Co se týče Alephu NKP, tak tam to otestovat bohužel nemohu, protože přístup k XServices NKP byl pro MZK a veřejné IP zablokován.

**Comment by mjtecka** [comment]
Nedávno jsem taky narazil na to, že přístup k XServeru Alephu NKP je omezený. 

Jestli nejde vůbec nic, tak asi budete muset požádat NK aby vám přístup pro IP adresu ProArcu/ProArců otevřela.

**Comment by nezbedova** [comment]
A ještě bych uvítala stahování z databáza KPS - Databáze Knihopis, také z Národní knihovny.

**Comment by nezbedova** [comment]
Z SKC lze stahovat po povolení IP adresy. 

O možnost stahování z KPS se asi bude muset požádat. Proberu s p. Kotýnkem.
