### ISSUE TITLE
RDflow_test_3.5.10_chybová hláška při zakládání nového záměru

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#957]
Při pokusu o založení Nového záměru, nelze tento záměr uložt. Naskočí "Neočekávaná" chyba. A to ikdyž nic nevyplňuji.

**Comment by nezbedova** [comment]
Oprava, záměr se uloží, ale nepřepne se do správy záměrů.

**Comment by nezbedova** [comment]
Test v. 3.5.13
![obrazek](https://user-images.githubusercontent.com/13831946/67262617-c4cc1100-f4a5-11e9-9738-c8b42bdf2be4.png)

![obrazek](https://user-images.githubusercontent.com/13831946/67262654-e5946680-f4a5-11e9-8076-ed8bebe21652.png)

**Comment by nezbedova** [comment]
Nový záměr se i přes chybu založí.

**Comment by nezbedova** [comment]
Tato chyba se znovu objevila u nového profilu.
Mohu zakládat jen Monografie_nová digitalizace, ale monografie Monografie_z_úložště nejdou. STT založit jdou.

xml posílám @SykoraLukas

**Comment by nezbedova** [comment]
Tato chyba se projevila i u nově zakládaného záměru monografie. Tři předlohy prošly a K 2953 (č.k. 26009007374) má chybu.

**Comment by nezbedova** [comment]
Chyba není ve více druzích monografií, ale v RDA/AACR. Založeno samostatné #1235

**Comment by SykoraLukas** [comment]
Z jakého katalogu stahujete? Abych si mohl chybu nasimulovat i u sebe?

**Comment by nezbedova** [comment]
Knihovna AV ČR Monografie

**Comment by SykoraLukas** [comment]
U editoru objektu ve workflow nebyla implementována podpora pro chybu RDA/AACR. Opraveno. Tímto issue se opravuje také duplicitní issue #1235.

**Comment by nezbedova** [comment]
Zakládání záměrů RDA i AACR funguje.
