### ISSUE TITLE
Rozšířený balíček pro eMonografie

### ISSUE THREAD

**Issue by pavelkocourek** [proarc/proarc#960]
Bude realizováno - standard NDK

**Comment by krizovj** [comment]
Zkoušela jsem balíček vyexportovat a celý jsem ho prošla:

Info.xml
![info-xml](https://user-images.githubusercontent.com/21309201/63075484-303bb480-bf32-11e9-940b-e57dd609b4f9.jpg)

- Chybí element „mainmets“ (M), kde má být uveden „název hlavního METS souboru včetně přípony“
- Mezi identifikátory chybí uuid – proč?
- Chybí element „checksum“ (M)

METS
- Kořenový element METS – v elementu LABEL je správně název dokumentu, ale má tam být také datum vydání – chybí
- DC - Element dc:type – má být „model:electronicmonograph“, ale je tam jen „model:monograph“

V METSu úplně chybějí administrativní a technická metadata (Standard kapitola 3.6.: https://www.ndk.cz/standardy-digitalizace/dmf_e-publikace_monografie_2-2-1) a celá část filesec (standard kapitola 3.7: https://www.ndk.cz/standardy-digitalizace/dmf_e-publikace_monografie_2-2-1)

**Comment by SykoraLukas** [comment]
NDK Emonografie opravena, nyní by měla být dle standardu
