### ISSUE TITLE
Test v3.5.11 - Záhada exportu pro Kramerius

### ISSUE THREAD

**Issue by nezbedova** [proarc/proarc#966]
Pokud exportuji pro Krameria v loňském roce založenou vícedílnou monografii, objeví se "Neočekávaná chyba". Export proběhne a lze ho dát do Krameria.

Archive balíček posílám přes FS @SykoraLukas

**Comment by nezbedova** [comment]
Nově založená vícedílka je bez problémů.

**Comment by mjtecka** [comment]
My u nás vídáme tuhle "neočekávanou chybu" na našem testovacím systému tak často, že už jí ... tak trošku očekáváme;-). Přijde mi, že jde jen o chybu komunikace mezi uživatelským rozhraním exportním procesem na pozadí. Nevím teda přesně co se tam děje, ale obzvlášť pokud je export větší, je větší šance že to UI nevydrží a vyhodí (prázdnou) neočekávanou chybu.

**Comment by SykoraLukas** [comment]
Podívám se na to

**Comment by tumovam** [comment]
Vytvořila jsem nové NDK Periodikum + strukturu s ročníky, čísly a články a také nejde vyexportovat. Napíše "Neočekávaná chyba! :-(", pokud kliknut na "OK", tak se objeví hláška "Export zadán. Úloha bude probíhat v pozadí.", ale nic se nestane...

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Prosím, ještě se u nás tahle chyba opakuje? Pokud ne, zatím bych zavřela a v případě problémů znovu otevřeme nebo nově založíme. Děkuji.

**Comment by SmejkalovaAnna** [comment]
@ZdenkaSera Já myslim, že se to může zavřít, vícedílky  jsme už testovali hodněkrát a fungovalo to. Ještě počkej, co Martina...

**Comment by nezbedova** [comment]
@ZdenkaSera Otestovala jsem to na dříve založené vícedílce. Ve v.  3.7.1 funguje. Můžeš to zavřít. Děkuji.

**Comment by ZdenkaSera** [comment]
@nezbedova @SmejkalovaAnna Děkuji oběma, zavírám.
