### ISSUE TITLE
Sledování fáze načítání dávky

### ISSUE THREAD

**Issue by SmejkalovaAnna** [proarc/proarc#967]
V okně Import - správa importních dávek - by v pravé části, kde je sloupec Vytvořeno, Změněno, Stav, Uživatel, přibyl ještě jeden sloupec nebo ve sloupci Stav - by se během načítání zobrazoval aktuální stav tačítání např. v procentech, abychom věděli u větších dávek, jak dlouho se bude ještě dávka načítat.

**Comment by pavelkocourek** [comment]
Přesunuto : Sledování fáze načítání dávky (#967) #17
