### ISSUE TITLE
Zakládání nového účtu a propojení s exportní složkou - chybějící lomítko

### ISSUE THREAD

**Issue by tumovam** [proarc/proarc#971]
Dobrý den, 
v KNAV jsme přišli na problém při zakládání účtů a jeho propojení s exportní složkou. Pokud se na konci cesty k adresáři nedá lomítko, účet se vytvoří, ale už neproběhne export. 
Nešlo by zařídit, aby ProArc při zakládání uživatelského profilu toto lomítko na konci doplňoval, nebo kontroloval jeho přítomnost, příp. upozornil, že lomítko chybí? 
Děkuji

**Comment by PetrKotynek** [comment]
Přidávám obrázky 
![vyjimka](https://user-images.githubusercontent.com/37083676/62269864-a8837f80-b434-11e9-8d2c-d24218deff14.png)
![s_lomitkem](https://user-images.githubusercontent.com/37083676/62269869-ad483380-b434-11e9-90ff-8088830c9442.png)
![bez_lomitka](https://user-images.githubusercontent.com/37083676/62269895-bd601300-b434-11e9-9002-bd31346cc6ba.png)

Petr

**Comment by SykoraLukas** [comment]
Na jake verzi se to prosím stalo? Na nove verzi 3.5.11 mi to funguje - založí se user s lomítkem na konci.

**Comment by tumovam** [comment]
Uživatel byl založen někdy dřív (asi se nedá zjistit v jaké verzi?), ale přišli jsme na to při testování v3.5.11. Jak to tedy, prosím, nyní funguje? ProArc upozorní, že lomítko chybí, nebo ho automaticky doplní? Díky

**Comment by PetrKotynek** [comment]
Je to na testovacím účtu, od 30.7  je tam 3.5.11, před tím 3.5.10. A může to být nějaký pozůstatek. Petr

**Comment by PetrKotynek** [comment]
Podle časového razítka na users adresáři 2.11 2018, tedy 3.4.4 možná těsně začátek 3.5.1 BTW: 100 let český archeologie. PK

**Comment by SykoraLukas** [comment]
Opraveno, proarc automaticky vytvoří cestu
