### ISSUE TITLE
Problémy s převodem polí 00x z X server Alephu do MODSu ProArcu (ořezávání posledního znaku)

### ISSUE THREAD

**Issue by mjtecka** [proarc/proarc#975]
Zdravím,

narazil jsem na problém s automatickým převodem dat z polí 001 (Control Number) a 003 (Control Number Identifier) do MODSu při vytváření nového objektu. 

V konkrétních příkladech na Univerzitě Karlově (=zdrojem dat je Aleph UK) ztrácíme poslední číslo systémového čísla a poslední písmeno kódu v 005 (CZ-PrCU -> CZ-PrC) 

Používáme standardní xslt šablony z ProArcu, stejný problém máme u všech instalací.

Další pozorování: 
- díval jsem se na další záznamy zkonvertované ProArcem na KNAV, v MZK a v SVKHK a na tenhle problém jsem tam nenarazil (=je možné že máme jinak nastavený X-Server našeho Alephu(?) ... nebo ostatní instituce nepoužívají X-Server?.. či opravují chyby ručně?)

- podobný problém jsem řešil u nějakých vlastních skriptů; narazil jsem na to, že MARC z Alephu se musí ještě převést na OAI MARC, který předpokládá u všech polí 00X obalení závorkami ("fixfield must be enclosed between quotes because spaces are meaningfull" ..https://www.openarchives.org/OAI/2.0/guidelines-oai_marc.htm); šablony LoC s těmi úvozovkami počítají; nevím jestli to může být podobný problém i v ProArcu

- vypadá to podobně jako #581 , nicméně v tomto případě není zmíněný problém s 005

**Comment by mjtecka** [comment]
OAIMARC2MARC21slim.xsl od LOC a v ProArcu se liší:

ProArc: https://github.com/proarc/proarc/blob/61f8eedc20242a412cd8748c50f893ce10161e27/proarc-common/src/main/resources/xml/OAIMARC2MARC21slim.xsl#L28-L33

LOC (www.loc.gov/standards/marcxml/xslt/OAIMARC2MARC21slim.xsl):

```
    <xsl:template match="oai:fixfield">
         <xsl:element name="controlfield">
           <xsl:call-template name="id2tag"/>
           <xsl:value-of select="substring(text(),2,string-length(text())-2)"/>
        </xsl:element>
    </xsl:template>
```

Pokud to dobře chápu, tak LOC přepokládá uvozovky na začátku a na konci a v tomhle místě je odstraňuje - vezme podřetězec od indexu 2 a celý text zkrátí o dva znaky (úvozovky na začátku a na konci). 

V ProArcu se s úvozovkami nepočítá. Podřetězec se vezme od indexu 1... ale stejně se zkrátí o 1. Což to musí rozbít, ne? A nemělo by to fungovat nikomu... (??)

**Comment by luckajirku** [comment]
> * díval jsem se na další záznamy zkonvertované ProArcem na KNAV, v MZK a v SVKHK a na tenhle problém jsem tam nenarazil (=je možné že máme jinak nastavený X-Server našeho Alephu(?) ... nebo ostatní instituce nepoužívají X-Server?.. či opravují chyby ručně?)
 
Milane, u nás používáme od začátku Z39.50. A pokud se Aleph bez našeho vědomí nepřenastavil:-), tak to bude stejné i teď...

**Comment by mjtecka** [comment]
> > * díval jsem se na další záznamy zkonvertované ProArcem na KNAV, v MZK a v SVKHK a na tenhle problém jsem tam nenarazil (=je možné že máme jinak nastavený X-Server našeho Alephu(?) ... nebo ostatní instituce nepoužívají X-Server?.. či opravují chyby ručně?)
> 
> Milane, u nás používáme od začátku Z39.50. A pokud se Aleph bez našeho vědomí nepřenastavil:-), tak to bude stejné i teď...

Díky za info. Pokud by to bylo tím, že se hodně používa Z39.50 a ne Aleph, tak by to bylo nejspíš dobře. Oprava by pak snad nerozbila nic dalšího...

**Comment by ZdenkaSera** [comment]
@mjtecka Prosím, je tohle k uzavření? Děkuji.

**Comment by mjtecka** [comment]
> @mjtecka Prosím, je tohle k uzavření? Děkuji.

Nějak jsme to řešili, ale nevím jestli jsme to úplně dořešili. A teď už to nevyzkouším, protože už nemáme X-Server (ani Aleph :-)
