### ISSUE TITLE
Kramerius export ndkemonographvolume ProArc 3.5.11

### ISSUE THREAD

**Issue by fstepanovsky** [proarc/proarc#978]
Dobrý den,
v MZK jsme narazili při zpracování NDK eMonografie na nemožnost exportu do Krameria.
Rád bych se tedy zeptal, zda-li je to implementováno, nebo je potřeba to někde nakonfigurovat.

ProArc 3.5.11 [fc4b614](https://github.com/proarc/proarc/commit/fc4b614b34d643c2076e016a7f82391f2aabdc9b)

**Comment by krizovj** [comment]
Není, teď momentálně se čeká na opravu NDK balíčku, který ještě není kompletní. Export pro Kramerius není implementovaný vůbec, alespoň pokud vím. 

https://github.com/proarc/proarc/issues/960

**Comment by SykoraLukas** [comment]
Zatím nebyl požadavek na takovýto export. Můžeme toto probrat na schuzce v uterý

**Comment by zabak** [comment]
Podle navázaných issues je tohle už vyřešené, je to tak?

**Comment by tumovam** [comment]
Myslím, že K4 export se původně vůbec neplánoval implementovat. 
Když se ale dívám do verzí, které máme nasazené, tak závěr je následující: ve v3.6.2, v3.6.3 K4 export NDK eMonografie nejde, ve v3.6.7 K4 export NDK eMonografie funguje... 
Ale import do Krameria eMonografie je připraven pro NDK export (https://github.com/ceskaexpedice/kramerius/issues/817). Po importu foxml Kramerius zobrazí "finished", ale e-kniha se v Krameriovi nezobrazí...

**Comment by ZdenkaSera** [comment]
Po interní diskusi v KNAV navrhujeme issue přece jen k zavření, pohlížíme na něj spíše jako na dotaz a vyjasnění funkce. @zabak pro info

**Comment by ZdenkaSera** [comment]
Zavírám vhledem k návrhu na uzavření, který nikdo nerozporoval.
