### ISSUE TITLE
3.5.12 - NDK eMonografie - NDK balíček

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#989]
Mám dojem, a kdyžtak mě někdo opravte, že se to vrátilo k tomu původnímu osekanému balíčku, který v současném standardu už není. 

Tak ještě jednou. Myslela jsem, že je to jasný, ale asi ne...

Ve starší verzi standardu pro NDK eMonografie (https://www.ndk.cz/standardy-digitalizace/E_born_MONO_NDK_22.pdf) byly popsané dva balíčky: SIP a AIP. Po dotazu od M. Rumánka to v NDK upravili a to tak, že ten původní AIP přejmenovali na SIP a AIP zrušili. V současném standardu (který mimochodem vyšel v září 2018, takže je to žhavá novinka): https://www.ndk.cz/standardy-digitalizace/dmf_e-publikace_monografie_2-2-1
je tedy popsaný pouze jeden balíček. 

To, co leze z verze ProArcu 3.5.12 je ten původní SIP balíček ze staré verze standardu. 

Ve verzi ProArcu 3.5.11 chyběla v balíčku jen některá metadata, viz. https://github.com/proarc/proarc/issues/960. Ale tahle "oprava" ho vrátila zase do podoby, kterou měl před rokem... Radši nebudu ani uvažovat nad tím, kdy by mohl být správně :man_facepalming:

**Comment by SykoraLukas** [comment]
Pošli mi nový balíček na mail, díky, Lukáš

**Comment by krizovj** [comment]
Odesláno, poslala jsem balíček, který se mi exportuje z 3.5.12.
