### ISSUE TITLE
3.5.12 - je to určitě verze 3.5.12?

### ISSUE THREAD

**Issue by krizovj** [proarc/proarc#990]
Přijde mi, že se to vrátilo o několik verzí zpátky. Nejde uložit téměř žádný model (NDK periodikum, NDK ročník, NDK číslo, eČlánek, NDK eMonografie, dál už jsme to nezkoušeli). 

Není potřeba změnit konfiguraci? 

Ale zkoušeli jsme například export pro CEJSH a byla tam chyba, která už byla v některé z předchozích verzí opravená...

**Comment by SykoraLukas** [comment]
Prosím otebři nějaký NDK ročník a pod něj vytvoř NDK číslo. Jaké všechny identifikáry se zpokírovali z ročníku? Dík

**Comment by krizovj** [comment]
čnb a ISSN

**Comment by SykoraLukas** [comment]
Případně co píše proarc když otebřeš možnost o programu?

**Comment by SykoraLukas** [comment]
ideálně screen obrazovky

**Comment by krizovj** [comment]
![3512](https://user-images.githubusercontent.com/21309201/66547449-8e0a0880-eb3f-11e9-9893-de66282e74b9.jpg)

**Comment by SykoraLukas** [comment]
Mohla bys prosím vyexportovat nejakou jednoduchou monografii s málo stránkami a poslat mi ji? Psal jsem mail panu Kotýnkovi, tak čekám na odpověď, Lukáš

**Comment by krizovj** [comment]
Odesláno

**Comment by zabak** [comment]
Taky v téhle verzi není podpora zvukových dokumentů, která tam předpokládám už měla být.

**Comment by SykoraLukas** [comment]
Nyní jsem na stejné verzi nahrál v Národním Muzeu nový zvukový dokument včetně všech mp3 a wavu. Mohl bych poprosit o kontrolu konfiguráku, zda v obsahuje  `import.profiles=profile.soundrecording_import`?

**Comment by fstepanovsky** [comment]
Nyní už ano, ale bohužel jsem nebyl schopný nikde v dokumentaci dohledat co je potřeba za plugin k tomu a co je správné modelId, protože ve fedoře nic podobného nemáme.
