### ISSUE TITLE
ePeriodika

### ISSUE THREAD

**Issue by SykoraLukas** [proarc/proarc#998]
Upravit modely ePeriodika podle standardu (až vyjde), zatím podle dokumentu od @krizovj a naimplementovat NDK balíček

**Comment by SykoraLukas** [comment]
Upravit formuláře dle aktuálního standardu pro ePeriodika.

**Comment by SykoraLukas** [comment]
Odebírám label `2a k realizaci`, i v aktuálním zápisu je napsáno (opakuje se min. od ledna 2021)

```
Eborn
zatím jsou hotové eMonografie, i rozšířený balíček
dále spíše problém čtečky PDF v Krameriovi
stále čekáme na eKapitoly - https://github.com/NLCR/Standard_NDK/issues/133
```
Stále není standard, takže není podle čeho implementovat.

**Comment by kerschfilip** [comment]
@SykoraLukas informace, které uvádíte, se týkají emonografií, tam skutečně nejsou dořešené kapitoly a není doladěný archivní balíček, který je ale rozpracovaný (https://github.com/proarc/proarc/issues/1309)

ePeriodika (NDK ePeriodikum, NDK eRočník, NDK eČíslo a NDK eČlánek) dodělané ale nejsou - aktuální ProArc 3.8.2 nezvládá export NKD SIP a ve formulářích v novém klientovi jsou chyby - https://github.com/proarc/proarc-client/issues/230

Chápu, že se to táhne z více důvodů a že se dlouho čekalo na standard, nicméně v hlasování o rozvoji to již celé jednou bylo (a bylo to schváleno) a není pravda, že by nebyl standard - ten který nás ve vztahu k ProArcu zajímá a na kterém se podílel @krizovj zveřejnila NK na začátku roku 2021: https://standardy.ndk.cz/ndk/standardy-digitalizace/eborny_skladana_periodika_1.0.pdf

**Comment by SykoraLukas** [comment]
Pokud tedy na toto existuje standard tak formulář opravíme (v novém klientovi) a zprovozníme Export.

**Comment by ZdenkaSera** [comment]
Vzhledem ke komentáři výše odebírám štítek "návrh na rozšíření" @SykoraLukas @kerschfilip  Díky!

**Comment by kerschfilip** [comment]
Díky za implementaci e-periodik! Problémy, na které jsem při testování narazil navrhuju zapisovat do následujících issues, abychom se v tom neztratili:  
- formulář pro eperiodika se řeší tady: https://github.com/proarc/proarc-client/issues/230 (a čeká se na jeho opravu)
- exporty (NDK balíček a archivní export) tady: https://github.com/proarc/proarc/issues/687
